### ISSUE TITLE
need help for 12gpu setup in awesomeminer

### ISSUE THREAD

**Issue by ashokthakkar** [MultiPoolMiner/MultiPoolMiner#1000]
I m registere user of miningpoolhub.com

I wish to use [Awesome Miner software for miningpoolhub but i have 1 question  software support 12gup (1050ti or 1070) plz explain how many gup support in this software coz multipoolminer software support only 6gpu and advanced user can create additional or amend current miner files to support mining with more than 6 gpu but i m beginner so i didn't have much knowledge abt

i dont know Awesome Miner need any special steeing for 12gpu(1050ti or 1070)

So how i can setup 12gpu with Awesome Miner plz guide me step by step asap       

thanx in advance 
Regards,

**Comment by Scoty** [comment]
This is not the Awesome Miner repo! You are better asking @https://bitcointalk.org/index.php?topic=676942.3960

**Comment by aaronsace** [comment]
MultiPoolMiner supports far more than 6; just double click 'start.bat'.

**Comment by ashokthakkar** [comment]
Dear sir /madam

I saw only start instead of start.bat so how i can mining with 12gpu can
you plz give some idea abt setting

Regards,
