### ISSUE TITLE
MPM keeps downloading PowerShell 6 at Startup

### ISSUE THREAD

**Issue by romulus2k4** [MultiPoolMiner/MultiPoolMiner#1001]
Fresh extraction of the latest release is downloading Powershell 6 every time at startup. Any remedies?

**Comment by migdiluca** [comment]
Same here

**Comment by aaronsace** [comment]
Install it manually by double clicking: `\Downloads\PowerShell-6.0.0-win-x64.msi`

**Comment by smaugfm** [comment]
MPM keeps executing PS6 installer at every startup. Installer flashes quickly and then MPM proceeds normally.

**Comment by papacheal** [comment]
I would advise manually uninstalling any pre-final release PS6 (e.g. rc2) and the 6.0.0 final release via Control Panel/Programs and Features, then manually reinstall the 6.0.0 final release. Your issues may be related to the permissions/context used to initially install PS6. A reboot after doing this is never a bad thing, to ensure any updated system settings and variables are being used.

You can source the PS6 installer from the MPM download (see folder already mentioned) or directly from the PS6 GitHub link in the readme.

**Comment by aaronsace** [comment]
MultiPoolMiner successfully installed the new PowerShell when I just tried it now but the old RC version is still there. Uninstall the old version and it will start using the new version.

**Comment by JUPIE2008** [comment]
when i tried it gave an exe error had to download a fresh version it installed fine and all up and running

**Comment by romulus2k4** [comment]
I just removed the powershell bit from the updater.ps1
I had the very same runtime installed and still MPM insisted that it should be re downloaded.

**Comment by mtbor** [comment]
I can confirm that the recommendation of aaronsace worked for me.  Go to add remove programs in windows and you should see two versions of powershell there....  One probably ends in RC (release candidate), uninstall that one...  The other one is the actual release.

**Comment by romulus2k4** [comment]
I can create a YouTube video showing that what aaronsace is suggesting doesn't work, but it'll be a waste of time since I have gotten a solution already.

**Comment by igneb** [comment]
Hey, where to find that updater?

**Comment by aaronsace** [comment]
For anyone having issues, you are not using the latest version of 'pwsh'.
