### ISSUE TITLE
Auto exchanging with Auto Exchange "Not Set"

### ISSUE THREAD

**Issue by Crypto00** [MultiPoolMiner/MultiPoolMiner#1002]
Hi ! 

I didn't find the answer in the docs or in the issues so I ask it here.
On MiningPoolHub I have Auto Exchange set to "Not Set" (I would like to keep the mined coins) and all the exchange settings set to "OFF" but I'm seeing more and more coins in my auto exchange wallets since this morning.
Is there something else to do to completely disable the auto exchange ?

Thanks and keep up the awesome work ! 👍 

![autoexchange1](https://user-images.githubusercontent.com/35327048/34814506-30ce3a6a-f6ae-11e7-9fa5-75d8b839b351.png)
![autoexchange2](https://user-images.githubusercontent.com/35327048/34814509-34d0fe7c-f6ae-11e7-989d-ffd21cb61af2.png)

**Comment by aaronsace** [comment]
Takes hours/days for coin networks themselves to confirm the already mined coins.

**Comment by symalla** [comment]
This was from bug listed now on MPH website that caused all new minted coins to go to auto exchange
![2018-01-11 08_02_15-mining pool hub i account](https://user-images.githubusercontent.com/7012032/34829310-de99ec38-f6a5-11e7-8b44-2754ac07ff65.jpg)

**Comment by Crypto00** [comment]
Oh nice ! Thanks ! 🎉
