### ISSUE TITLE
How to add12gpu 

### ISSUE THREAD

**Issue by ashokthakkar** [MultiPoolMiner/MultiPoolMiner#1003]
Dear sir/madam 

How i can mining with 12gpu there any setting which i can edit ?? And while i extracts zip file i saw start file interested of start.bat file

**Comment by UselessGuru** [comment]
> there any setting which i can edit

There is no such setting. :-(

MPM is designed out of the box to only support 6 cards. 
You can run it on rigs with more cards and most miners will work fine out of the box on all cards. Some might not use all cards or simply throw errors.

Then plese post the issues you may find here. Thanks!

**Comment by aaronsace** [comment]
@ashokthakkar It should work with more than 6; some miners are just a bit quirky. Make sure that your CPU is good enough to handle 12 GPUs and definitely turn CPU mining off.

**Comment by 1337LutZ** [comment]
I was running with 12 GPUs on a H110 BTC+, all you need to do is tweak the Miner files so the arguments are correct (for ie. overclock). The rest worked pretty much out of the box.

**Comment by platinum4** [comment]
This issue was [resolved](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1003#issuecomment-357423667) by the person who opened it; it is no longer an issue for main releases and would need to be done by each individual using 7+ GPUs per miner-- it is not a codebase issue.  This can be closed.

**Comment by Braintelligence** [comment]
@1337LutZ Would you be so kind as to share your tweaks? I'm running into minor problems sometimes with ccminer.

**Comment by 1337LutZ** [comment]
Hey @Braintelligence ,
I don't use ccminer, what helped for some miners is to manually give all the GPUs in a parameter.

**Comment by Braintelligence** [comment]
@1337LutZ Aren't you missing out on lucrative stuff, if you don't use ccminer at all?

**Comment by 1337LutZ** [comment]
Could be, but currently im only mining: NeoScrypt, Ethash and Equihash. (mostly just Ethash)

**Comment by Braintelligence** [comment]
@1337LutZ So I guess you use the PalginNvidia miner for NeoScrypt if you say you don't use ccminer? Sadly I still have to use TPruvot, since I can't stop relying on watchdog...

**Comment by 1337LutZ** [comment]
Sorry im running 12x RX580 (so AMD) so no NVIDIA. Afaik i run nsgminer for NeoScrypt (if i run it)

**Comment by Braintelligence** [comment]
@1337LutZ Oh well, that explains it. I only run Ethash on my RX 580. Everything else (50+ GPUs) are nVidia.

**Comment by 1337LutZ** [comment]
@Braintelligence I actually quit using MPM for a while, purely using MiningPoolHub Ethash or PIRL. The 12x DAG generation sometimes makes 1 card hang, so mining one coin is more lucrative for me.

**Comment by Braintelligence** [comment]
@1337LutZ I currently let it switch between MPH and NiceHash. Not sure if I should dedicate myself to one thing currently, even though it looks like just staying with NiceHash could yield the best results.
