### ISSUE TITLE
[Request] Include power cost in profitability calculation

### ISSUE THREAD

**Issue by Lycerion** [MultiPoolMiner/MultiPoolMiner#1004]
Specifically with things like dual mining eth/sia, I'll often get 200-250 extra watts at the wall per psu (4 gpus each) over mining eth alone. This might make certain coins more profitable than others. An approximate power consumption can be pulled from each GPU, though I'm not sure how doable that is in powershell.

**Comment by Crypto00** [comment]
I saw this in the [MultiPoolMiner Version 3 Roadmap](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/378).

**Comment by fonyo** [comment]
Yes, it will come later in the pipeline.
