### ISSUE TITLE
Cannot bind argument to parameter 'DifferenceObject' because it is null.

### ISSUE THREAD

**Issue by zoglun** [MultiPoolMiner/MultiPoolMiner#1006]
I have upgrade everything to newest, and even move MPM to D;/ instead of C:/, but still get this error.

```
>> TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\MultiPoolMiner\MultiPoolMiner.ps1:144 char:77
+ ... rithm.Count -eq 0 -or (Compare-Object $Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\MultiPoolMiner\MultiPoolMiner.ps1:144 char:77
+ ... rithm.Count -eq 0 -or (Compare-Object $Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
```

**Comment by cmbconcretefire** [comment]
??? Try putting an extra folder in your D: drive so it looks like this D:\Crypto\Multipoolminer

**Comment by neone35** [comment]
Getting same error message, but it seems like miner is working.

**Comment by aaronsace** [comment]
FYI guys, upload log _files_ to GitHub posts; don't just paste small snippets from the screen. 

Anyway, please can you test that your computers are working correctly by running this: 
[oclDeviceQuery.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1629977/oclDeviceQuery.zip)

**Comment by neone35** [comment]
- Installed latest Nvidia driver version 390.65 with OpenCL 1.2
- Installed AMD SDK 3.0 with OpenCL 2.0

1. Don't see OpenCL.dll at Windows/System32 or Windows/SysWOW64 (I read they must be there?)
2. oclDeviceQuery output [pastebin](https://pastebin.com/FzWaNpV1)

But no red error anymore! 😋
