### ISSUE TITLE
Download only mode

### ISSUE THREAD

**Issue by Nickfost** [MultiPoolMiner/MultiPoolMiner#1008]
it would be super helpful if you were to add a download only mode so i can get binaries reliably. it takes almost a week to get all the miners to download because my connection is slow (mining works fine) most github.com downloads time out unless the file is under a few kb. github and many other file hosting websites limit the duration of open http connection to prevent resource waste. 

My situation is unique. I have access to a datacenter and a system i can use bandwidth on there. i would like to use multipool miner (with special flags to prevent mining on this system) to download all of the binaries. i can then zip them and send them to myself using something like resilio sync (which works well for my slow connection at my mining location) or move them to a flash drive and disperse them among my 6 mining systems. 

This approach with the command line would be preferred because each time you add a new miner my download script could just download the whole folder again. 

i was really disappointed [when i raised this issue 2 days ago it was closed](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/990) and i felt like i was not being heard, maybe i wasnt clear enough about my use case. 

Thanks aaronsace and all of the other contributors for making a decent miner.

**Comment by aaronsace** [comment]
Yes, bit of a unique case; normally you would have some sort of machine to test on that can then be distributed to all your rigs. Everyone is being heard but we can't do everything. Feel free to submit a pull request if you know what changes need to be made to the script.

**Comment by aaronsace** [comment]
FYI, 'downloader.ps1' is a separate file and your feature maybe better suited simply as a '.bat' file.

**Comment by carlo0000** [comment]
about the download
why the hell i have some computers each time i restart  multipool it s need to redownload powershell again and again ???  
and anyway i dobn't like the automatic download,  do we need to remove  downloader.ps1 ?

and i m really mad why the hell is multipoool stuck today on mining  for dev fee more than a half day or even longer

**Comment by aaronsace** [comment]
@carlo0000 Please don't spam. 

Uninstall PowerShell Version 6-**RC2**.
