### ISSUE TITLE
Question about fees

### ISSUE THREAD

**Issue by Crypto00** [MultiPoolMiner/MultiPoolMiner#1015]
Hi !

I try to estimate precisely how much my rig yields so I substract all fees.

I'm mining exclusively on MiningPoolHub ("Pool fee is 0.9%."), so 0.9 %.
For donating 24 minutes per day (default), it's 1.67 %.
For any withdrawal there is a fix fee applied (`/index.php?page=account&action=pooledit` pages on MiningPoolHub), for example 0.0002 BTG for Bitcoin Gold.

Finally, from a miner perspective, with MultiPoolMiner mining Bitcoin Gold (for example) on MiningPoolHub, and with default values, the overall fee is 2.57 % + 0.0002 BTG ?

Thanks !

**Comment by JUPIE2008** [comment]
A very interesting question......everybody say they dont trust multipool mining and but then where could we use  aaronsaces App beside MPH. and what other options are there.

**Comment by papacheal** [comment]
Don't forget the 0.2% fee for Auto-Exchange transactions on MPH, if you use that feature to amalgamate earnings to a single coin (e.g. Bitcoin). Some miners also take a small cut as they are used (e.g. DSTM, PalginNvidia).

If you get even more advanced (and you pay for your power), you have to consider the various power draws miners put on your rig and how your costs there will vary. Some forks of MPM help with this, but you can get mired in the details.

As far as "skimming", this is usually done by misrepresenting your miner's hash rate on the pool (i.e. "stealing" hash rate) which results in reduced payout for you. This is best determined by running your miner for at least 60 minutes on a pool then checking what it is reported for your hash rate. Repeat this using the same miner on the same protocol on a different pool to see if the reported hash rate is radically different. If so, you'll know which pool may be "skimming". Note that we're talking about what the POOL tells you your hash rate is, not what the miner shows in it's output.

I use MPH selectively when I want to mine a specific coin and keep it for a while, exchanging it later when I'm ready. It can be simpler to think about pools that do the exchange work for you, like AHashPool. They take a flat 1% cut on all your mining earnings, then only charge whatever the going rate is for the BTC transaction cost when an auto-withdrawal is processed (when your earnings exceed 0.008 BTC).

To be honest, the best test is to mine on a single pool for a week and determine your aggregate BTC profit for that pool. Then move on to the next pool and repeat. There are so many variables involved (exchange rates, network difficulty, pool hash rate) that you need a decent amount of time on a pool to average out the math.

**Comment by JUPIE2008** [comment]
That is exactly what im actually getting at .......i guess unless there is a massive diff between hashrates would one really know whether a pool is skimming or not  or not.I am also sure no one 60 minutes would be the same as another . Since i posted yesterday  at  around 11.30pm my time i got paid out in  Litecoin which is my choice because the transaction rate is much lower than some of the other  well known coins. and i hope im not wrong but i just got another payout (1x570Nitro & 1x 580) well in 18 hours i just got paid  into my Exodus wallet $7.65  bearing im mind the price of Litecoin also may not be the same as yesterday. Seems quiet good to me ?

**Comment by fonyo** [comment]
Improved calculation that accounts for pool, miner and other fees are coming by MPM v3.

**Comment by Crypto00** [comment]
@fonyo Ah yes it's in the [MultiPoolMiner Version 3 Roadmap](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/378).
I'll wait for this then.
