### ISSUE TITLE
What to do with excavator.exe and which version ?

### ISSUE THREAD

**Issue by kevharper** [MultiPoolMiner/MultiPoolMiner#1016]
From the Important Notes:
'You may need 'excavator.exe' if you don't already have it: https://github.com/nicehash/excavator/releases"

Can you provide a little more information?  Is there a specific version and where does it need to be located after downloading?

Thank you!  Great Miner!!

**Comment by JUPIE2008** [comment]
I think thats part of the Nvidia mining operation im on AMD so cant answer there

**Comment by TVanAusdall** [comment]
Download the latest version, create the directory "Excavator" in your multipool miner bin directory then put the downloaded excavator files in the Excavator directory.

**Comment by aaronsace** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/#q9-multipoolminer-says-it-cannot-find-excavatorexe
