### ISSUE TITLE
Pool not selected in config file yet they are being used.

### ISSUE THREAD

**Issue by rednkentucky** [MultiPoolMiner/MultiPoolMiner#1017]
Maybe this is me not fully understanding how the application works but I have searched high and low. I cannot find out how to make it only work certain pools without deleting the pools files I don't wish for it to use.  I don't wish to delete them as I may later decide to use this optional pools and would have to remember where I put them.  This just seemed to start happening in the last few versions.  The start file config with "-poolname miningpoolhub,zpool " am I incorrect in thinking that this is end all be all for what pools it should use?  

I am saying this because this AM I noticed that it was using aHashpool and I don't have it set anywhere.  I had noticed it was using niceHash the other day and forgot to look at it.

Thank you in advance.

**Comment by aaronsace** [comment]
Watchdog has kicked the pool. Specify 2-3 pools.

**Comment by papacheal** [comment]
The "-poolname" is an indication of "preferred" pools, not completely exclusive. As long as:

- Your algorithm list is supported by the combination of your preferred pools
- Those pools respond to MPM's API calls

...you'll stick to those preferred ones.

If you specific an algorithm that isn't available on your preferred pools or one of those pools doesn't respond in a timely manner to MPM's API calls, MPM will try to find an alternative pool for you from it's complete list of pools.

**Comment by komer83** [comment]
@aaronsace Is there a possibly to force MPM to just use the selected pool and if it not responded in a timely manner? (other then removing other pools files)

**Comment by UselessGuru** [comment]
> Is there a possibly to force MPM to just use the selected pool even if it not responded in a timely manner? (other then removing other pools files)

Currently no. But whats wrong with removing the pool files. It makes MPM work faster (= less CPU cycles, les power consumption -> better profitability)?
