### ISSUE TITLE
Profitability displaying equivalent to 1 GPU when running two. Hashrate is correct

### ISSUE THREAD

**Issue by plutov1383** [MultiPoolMiner/MultiPoolMiner#1019]
I am mining with a CPU and two GPU's and for the GPU's my hashrate using Dstm equihash is 1.0 KH/s, which is on point with the benchmark. Benchmark shows BTC/day at 0.00107 but the miner stat at the bottom is showing 0.00069; equivalent to one GPU and my CPU. Is there some setting to change based on how many GPU's you're using simultaneously for this to display correctly? Included screenshots below. 

![rate](https://user-images.githubusercontent.com/35393185/34904089-cab489e4-f803-11e7-87bd-6dc0c551a76e.PNG)
![benchmark](https://user-images.githubusercontent.com/35393185/34904105-3968dcb4-f804-11e7-9c8b-316dde5dcf7e.PNG)

**Comment by fonyo** [comment]
Run resetprofit.bat
