### ISSUE TITLE
Duel Xeon CPU - E5-2695 v4 - 36 Cores - only 50% usage

### ISSUE THREAD

**Issue by speedyrazor** [MultiPoolMiner/MultiPoolMiner#1020]
Hi, I have a spare Dell R730 server with two Xeon CPU - E5-2695 v4 with a total of 36 Cores. I am using MultiPoolMinerV2.7.1.4, set my .bat file accordingly, but when mining I am only seeing about 50% of my total CPU's being used in Task Manager, I obviously would like to use 100% of the CPU's. Is there a way to do this please?

**Comment by fonyo** [comment]
MultiPoolMiner only controls the software, it seems (just assuming) the cpu miner apps don't support dual cpu configurations.

**Comment by aaronsace** [comment]
Manually set the threads higher. 

Decide which CPU miner(s) that you would like to use then edit the file in the folder called 'miners'.

**Comment by speedyrazor** [comment]
Hi aaronsace, I looked in the miners folder, looked at all the CPU filkes, for example, CpuminerJayddeeAesavx.ps1, but there is no mention of 'thread'. How can I increase it to two?

**Comment by aaronsace** [comment]
Add this to the command: `-t 36`

**Comment by speedyrazor** [comment]
Thanks, but how do I add -t 36 into the command whilst still using MultiPoolMiner please?

**Comment by speedyrazor** [comment]
If I run two separate instances, from separate folders (whihc does max out the CPU to 100%), I get "API Bind to port 4048 failed" on the 2nd instance.

**Comment by aaronsace** [comment]
In 'CpuminerJayddeeAesavx.ps1'. Can you not see the command line at the bottom? Add `-t 36` to it.

**Comment by speedyrazor** [comment]
Ahh, I see, thanks for that. I actually tried manually adding it to my own command, but it still only used 1 physical CPU, it said 36 threads, but still only 1 CPU, and still only 50% of the total CPU compute.

**Comment by aaronsace** [comment]
@speedyrazor Does your CPU not allow anything to use all 36 cores?

**Comment by speedyrazor** [comment]
Yes, no problem to use all both CPU's and all 36 Cores. If I run two separate instances, from separate folders, does max out the CPU to 100%, I did get "API Bind to port 4048 failed" on the 2nd instance. to start with but seems OK now.

**Comment by aaronsace** [comment]
Why can't one program use all 36 cores though?

**Comment by aaronsace** [comment]
Do you need 72 threads...?

**Comment by aaronsace** [comment]
I don't get why one process can't use all the cores. Is it a bug in the miner or a limitation of the operating system?

**Comment by speedyrazor** [comment]
Must be the miner, as its Windows Server 2016. Thanks for the help and info.
