### ISSUE TITLE
PSSessionStateBroken

### ISSUE THREAD

**Issue by Sigri44** [MultiPoolMiner/MultiPoolMiner#1021]
Hi chief,

Sorry it's not long, but already the hassle.
Am to the problems of last night so I took the last release on github, I removed the 2/3 invalid algorithms for me, and I let MPM do the benchmark and download the miners. (The file is whitelist by the antivirus!)

And this Morning : 
![aaaaaaa](https://user-images.githubusercontent.com/9304947/34905195-3718c4b0-f854-11e7-80df-cba50cd81b3a.png)
[2018-01-12_23-41-03.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1628229/2018-01-12_23-41-03.txt)

Thx !

**Comment by aaronsace** [comment]
Why are you running as administrator and not just double clicking on 'start.bat'?

**Comment by Sigri44** [comment]
I just double clicking on start.bat ! My user is an Admin, but i don't use "launch in admin" option !

**Comment by aaronsace** [comment]
I'm suspecting you've messed something up somewhere in the OS but I'm not sure what. 

Can you try it on a fresh install of windows?

**Comment by Sigri44** [comment]
It's very hard, it's my personnal work computer .. :/ i use it all day to work, and all night to mine.

**Comment by aaronsace** [comment]
Your issues seem a lot deeper than the scope of this project. 

You could take this opportunity to finally get Windows 10 installed.

**Comment by Sigri44** [comment]
Windows 10 :'( Privacy... If i change, i use Debian Sorry.

**Comment by aaronsace** [comment]
Privacy is an illusion; don't think about it. 

If you are still having problems on a clean install then post a new issue.
