### ISSUE TITLE
MultiPoolMinerV2.7.1.4 not displaying daily rate on single -type

### ISSUE THREAD

**Issue by speedyrazor** [MultiPoolMiner/MultiPoolMiner#1022]
Hi, I am using the latest version, MultiPoolMinerV2.7.1.4, with cpu only, and it just refuses to display the daily amount in the terminal window (I have -currency set to gbp). This works fine in MultiPoolMinerV2.7.0.2). I do find though in MultiPoolMinerV2.7.1.4 if mine for nvidia and cpu, then the daily amount gets displayed, but not if only set -type to only cpu or only nvidia. Is this a bug or am I doing something wrong?

**Comment by aaronsace** [comment]
It's a bug, MultiPoolMiner runs through so fast that the downloader hasn't finished checking the miners. 

Fix comming soon.

**Comment by Braintelligence** [comment]
@aaronsace Even if you set it to nvidia only? It takes a while for me to download all miners.

**Comment by UselessGuru** [comment]
> Does it actually effect earnings?

No, as long as you see the miners working everything should be fine.

> I have -currency set to gbp

Just for a test change it to USD

**Comment by speedyrazor** [comment]
> Just for a test change it to USD
Changed to USD, same result. When you first run the .bat, 1st time round you get the daily earnings, once it refreshes, the daily earnings fail to show.

**Comment by UselessGuru** [comment]
Please post logs and a screenshot - TIA.

**Comment by speedyrazor** [comment]
Logs and screen grab attached.
[2018-01-18_16-53-39.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1644275/2018-01-18_16-53-39.txt)
![screen shot 2018-01-18 at 20 07 09](https://user-images.githubusercontent.com/14288265/35118923-550827a0-fc8b-11e7-89af-7f2570f4e31d.jpg)

**Comment by grantemsley** [comment]
Closing outdated issue.  If this is still a problem in the latest version (and there currently isn't an open issue for it) please open a new one.
