### ISSUE TITLE
Mining only one Algorithm ?

### ISSUE THREAD

**Issue by JUPIE2008** [MultiPoolMiner/MultiPoolMiner#1023]
I have become very comfortable using this program and have wondered. If for e.g i only wanted to mine one Algorithm at some stage ........would it be a simple as removing all the other algos' and forcing it to stay on the remaining algorithm.

**Comment by aaronsace** [comment]
I wouldn't recommend just mining one algorithm but it's as simple as setting the parameter called 'algorithm' in the 'start.bat'

**Comment by JUPIE2008** [comment]
Whatever you say M8. I been through  the whole lot and am quiet happy. Anything better atm will just be a bonus. Keep up the good work. 
P.S  Pity i only got a few GPUs ....will surely kick ass as i climb the ladder

**Comment by platinum4** [comment]
This issue is resolved and can be closed.
