### ISSUE TITLE
Issues with JayDDee miners with Ryzen Cpu's

### ISSUE THREAD

**Issue by LightningManGTS** [MultiPoolMiner/MultiPoolMiner#1025]
As of the current moment the self download from the miner config files is not pulling the latest version of his miner's with the new exe with better support for Ryzen processors. in my attempts to self configure it by setting a power shell file to point at $Path = ".\Bin\CPU-JayDDee\cpuminer-avx-sha.exe after downloading the latest version of cpuminer-opt and it binary's I can get it to run any algorithm I wish. The issues ends being the performance. Crypotnight ends up performing worse then xmrig by almost half and yescrypt while as potentially profitable as running xmrig ends up causing the computer to lock up if I try and run an algo switcher for my gpu's at the same time (specifically locks up when it attempts to close and open other miner applications) is there any special way that the power shell file needs to be set up or does the binary's for the latest version need to be configured in such away as to play nice with MultipoolMiner?

**Comment by fonyo** [comment]
Try lowering the intensity, higher speeds usually mean more efficient but also higher CPU utilisation.

**Comment by LightningManGTS** [comment]
oh? where would I got to set intensity per miner application? as of the current moment I'm doing something vaguely similar where I'm creating a bunch of different shortcut to set cpu priority per application type. is it something that needs to be tweaked in the main powershell file for the application or...?

**Comment by UselessGuru** [comment]
MPM does not support setting CPU priority at all. It supports adjusting intensity for miners, if they have a command line option for such tuning, e.g. Ccminer -i [number]

If you want to adjust CPU priorities per miner you'd have to resort to [3rd party tools](https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwjPrM7Vn93YAhUHJuwKHeJ5CbcQFgg_MAM&url=https%3A%2F%2Fwww.raymond.cc%2Fblog%2Fpermanently-set-process-priority-in-windows-task-manager-with-prio%2F&usg=AOvVaw1Xdtu6VEWvlFHwN4Gy4QZP)

**Comment by LightningManGTS** [comment]
well yes, hence the whole shortcut thingy majig I mentioned, also you clarify I attempted to set intensity in the miner powershell file but any intensity I set cause the miner to not launch
![yescrypt](https://user-images.githubusercontent.com/3919521/35009109-979be630-facc-11e7-9743-2bef677eb994.PNG)

**Comment by aaronsace** [comment]
@LightningManGTS You need a space before the hyphen. 

FYI, CPU miners are launched as low priority.

**Comment by LightningManGTS** [comment]
I saw that I did not add a space but doesn't even matter 
![capture](https://user-images.githubusercontent.com/3919521/35009346-43c90910-facd-11e7-8ce1-3abc57aedd33.PNG)

**Comment by HaTaX2** [comment]
For that miner you're going to want to play with different command line switches.  Trying running it manually from the command line with '--help' at the end to see everything available.  You can set process priority, cpu affinity, and thread count from there.  I have a FX-8350 and run all my CPU miners on the upper 7 'cores' leaving core 0 available for the system.  I have `" --threads=7 --cpu-affinity 0xFE"` on each of the algos in the ps1 file, never have set the priority as it's not been an issue for me.

Which Ryzen CPU do you have?  The settings above probably won't give you the best performance, with the exact CPU you're using I can give a better starting point.

**Comment by LightningManGTS** [comment]
I've tried something similar with the affinity command except I would use for instance 21845 as the value to just set processor affinity straight. I think that vqulue was to select the last 7 physical cores on my 1800x. If just doing that way is wrong I would love to be corrected

**Comment by HaTaX2** [comment]
So the 1800x is a 8 core, 16 thread CPU.  If you want to stick to just running on 7 of the 'real' cores, which is personally what I've seen perform best, then you'd want an affinity mask of 0x5554.  I think you're taking the decimal value of the mask where I believe the command line only takes a hex value. In any case they're both derived from the binary mask we're using.

'‭0101010101010100‬' - Binary, will use all cores with a '1' and highest core # is at the left of the string.  This string says use cores # 2,4,6,8,10,12,14 and excludes the first core.  This binary value is 21844 in decimal and 5554 in hex.  The decimal value you were using would actually include core 0.

Hopefully that helps explain it a little bit, I apologize if it's all info you knew already.  Give the affinity '0x5554' a try and see if it helps.  FWIW, XMRig and FireIce (Xmr-stak) always perform quite a bit better with Cryptonight, especially so if locked and large pages are enabled and being used.
