### ISSUE TITLE
The Big Question ?

### ISSUE THREAD

**Issue by JUPIE2008** [MultiPoolMiner/MultiPoolMiner#1026]
Hey guys i been following a few comments about RX580 graphics Cards compared to Vega 64. I am really impressed so far with aaronsace's program and have been thrown in the deep-end with this one. IF power was not the biggest issue and i decided to stick with multipool/multialgo Mining and the word that DAG rate will drastically increase in the near future with etherereum. What would my best option be for almost a similar price. 2x580's or 1 Vega 64. Bearing in mind the Vega has a massive  Crytonite advantage would it be wise to keep adding on 580's or start moving to the  Vega side. 

regards
JUPIE2008

**Comment by Powaful3000** [comment]
Depends on the price you get them for.

**Comment by fonyo** [comment]
Please post queries like this on the reddit.
