### ISSUE TITLE
MultiPoolMiner Script Refresh Causes GPU Usage to Drop for 1 Second

### ISSUE THREAD

**Issue by Philbar715** [MultiPoolMiner/MultiPoolMiner#1027]
Has anyone else noticed this? When the script auto updates (or re runs or whatever its doing when the main script is refreshing and calculating profitability) that GPU usage drops to 0% for about 1-2 seconds then spikes back up to 99/100%?

I have confirmed this by setting the -interval switch to 900 (15min) and my usage is 100% until that 15min mark when the script refreshes. I set it back to default (1min) and every min my GPU usage drops to 0 then back to 100%.

At first glance testing, this appears to be mildly affecting hash rates/profits.

Specs:
LGA 1150 Celeron
8GB DDR3 RAM
Biostar H81 Motherboard
3 GTX 1080TI on risers

**Comment by aaronsace** [comment]
Most likely your CPU is so bad that can't do two things at once.

**Comment by Philbar715** [comment]
It's a Celeron G3930. It should be more than enough. I'll test on my desktop that has a 4700k and 980Ti. I'll report back my findings.

**Comment by aaronsace** [comment]
@Philbar715 That's only dual core. One core for MultiPoolMiner then only one core left for the miners to run. 

Apart from getting a quad core, try deleting as many files as possible in both the 'pools' and 'miners' folder.

**Comment by borzaka** [comment]
2 Cores, 4 Threads (Core i3-4170) is enough?

**Comment by aaronsace** [comment]
@borzaka I can't say for sure but having 4 threads means it is highly likely to work smoothly even it is only 2 cores. MultiPoolMiner is single threaded for the most part but the miners that it launches require varying degrees of CPU power. 

G3930 is a $50 CPU so anything is better than that.

**Comment by fonyo** [comment]
What cards do you have and what algo/miner are they running?

**Comment by borzaka** [comment]
I have 3 1080 Ti and 3 1070 Ti in one rig.

Most of the time it mines equihash with EWBF.

Other popuplar miners/algo for my rig:
- NeoScrypt-Palgin\hsrminer_neoscrypt.exe
- Excavator\excavator.exe (Lyra2RE2)
- NVIDIA-Nanashi\ccminer.exe (lyra2z)
- Lyra2z-NVIDIA\ccminer.exe (lyra2z)

**Comment by fonyo** [comment]
That rules out the AMD architectural bug then (hashrate dropouts every minute or so).

**Comment by borzaka** [comment]
I don't experience GPU hashrate drop when MPM refreshes. How could I check it for sure?
I have 6*8+8 GB (6 card + physical memory) virtual memory. (Oh, I just realized that the 1080 Ti has 11 GB memory...)

**Comment by Philbar715** [comment]
Tested this out on my rig with a 4770K and 980Ti. No GPU usage drop and no hashrate decrease when script updates. Looks like it is my measly CPU. I'll be upgrading to an i5 for sure now.

I am checking GPU usage with MSI afterburner.

**Comment by borzaka** [comment]
Sometimes (not always) 2 of my 6 card rig experience a ~15% drop during script refresh, but I'am not sure it is caused by the script refresh.

ccminer has this feature: `stratum stale jobs workaround`
Basically it will stop your GPU from current job if there is a new one. It can improve performance. But the GPU usage drops to 0 for some ms if there is a new job.

**Comment by bbgobie** [comment]
I actually experience a drop in hash rate during the refresh as well.  For me my hash rate drop is noticeable.  During non refresh times my CPU hangs around 30-35%, but for a few seconds before I see the MPM screen refresh and during that time it can spike up to 97-98%.

I'm also on a basic Celeron 3930 and on a 6xgpu rig dedicated to Mining.

Will try removing some of the pool and miner files.  I usually do go through and do some basic edits, it just becomes a pain comparing to the new MPM version everytime in case you've added some new miners or fixes. I think I'll rename the files instead?

**Comment by Philbar715** [comment]
Just wanted to update this. Upgraded to a Core i5 - 3570 and a new motherboard. The GPU usage stays at 99/100% when the script updates. Maybe worth adding a line or two about it in the FAQ/readme? Because many miners are under the impression that the "cheapest" CPU for your motherboard will work for GPU mining. I would say that is true unless you are updating a lengthy powershell script every 60 seconds lol.

As a workaround, I set the interval to 300 seconds so it would only drop CPU usage once every 5 min until I got my new CPU and motherboard.

**Comment by UselessGuru** [comment]
Another workaround could be starting the MPM ps session with low priority.

**Comment by UselessGuru** [comment]
@aaronsace 

What about lowering MPM's priority? This would do:
`(Get-Process -Id $Global:PID).priorityclass = "BelowNormal"`

**Comment by aaronsace** [comment]
@UselessGuru I think the fault lies in people building mining rigs and forgetting all the normal check boxes to cover when build a computer. 

Go ahead and add that line; there is no interface so responsiveness shouldn't matter.

**Comment by UselessGuru** [comment]
> I think the fault lies in people building mining rigs and forgetting all the normal check boxes to cover when building a computer.

Very true, but then it is MPM not working well ;-)

**Comment by UselessGuru** [comment]
[Changed MultiPoolMiner.ps1 as proposed](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/c881a86774d19415efe11950839a51d6d47fd59f)

**Comment by borzaka** [comment]
I have updated my MultiPoolMiner.ps1 with the code above, and I can see GPU usage drops during MPM update. I'am using the default 60 second interval for this test. You can see the 15-20% usage drop on every GPU at every minute:
![mpm_gpu_drops](https://user-images.githubusercontent.com/1230402/35477674-fecbc456-03c8-11e8-8166-6e63a7a03e02.png)

- [Intel® Core™ i3-4170](https://ark.intel.com/products/77490/Intel-Core-i3-4170-Processor-3M-Cache-3_70-GHz) (3.70 GHz, 2 cores, 4 threads)
- 8 GB RAM
- Windows 10 64 bit
- I have deleted the unused pool files

My start.bat:
`-username borzaka -workername nvidiaworker -region europe -currency btc,usd,ltc -type nvidia -poolname miningpoolhub -algorithm ethash,equihash,groestl,lyra2re2,lyra2z,neoscrypt,nist5,skein -interval 60 -ExcludeMinerName Dstm -donate 10 -switchingprevention 3`

Miner during the test:
```
    Speed Active                      Launched Command
    ----- ------                      -------- -------
5,04 GH/s 00 Days 00 Hours 15 Minutes Once     Bin\NVIDIA-SP\ccminer.exe -a skein -o stratum+tcp://hub.miningpoolhub.com:17016 -u borzaka.nvidiaworker -p x -b 4068
```

No GPU usage drop with this miner:
```
    Speed Active                      Launched Command
    ----- ------                      -------- -------
3,89 KH/s 00 Days 00 Hours 11 Minutes Once     Bin\Equihash-EWBF\miner.exe --eexit 1 --api --server europe.equihash-hub.miningpoolhub.com --port 17023 --user borzaka.nvidiaworker --pass x --fee 0 --intensity 64
```

**Comment by UselessGuru** [comment]
> I have updated my MultiPoolMiner.ps1 with the code above, and I can see GPU usage drops during MPM update.

Your CPU is obviously too weak to handle both, mining AND MPM processing.

One last try: Try setting the MPM process priority to 'idle' (either per task manager  or edit MultiPoolMiner.ps1 and change
```
#Set process priority to BelowNormal to avoid hash rate drops on systems with weak CPUs
(Get-Process -Id $Global:PID).priorityclass = "BelowNormal"
```
to 
`(Get-Process -Id $Global:PID).priorityclass = "Idle"`

**Comment by borzaka** [comment]
With idle:
![mpm_gpu_drops_idle](https://user-images.githubusercontent.com/1230402/35481414-822c4474-0423-11e8-8b24-4d10ddfe0ce6.png)

Miner:
```
    Speed Active                      Launched Command
    ----- ------                      -------- -------
5,01 GH/s 00 Days 00 Hours 08 Minutes Once     Bin\NVIDIA-SP\ccminer.exe -a skein -o stratum+tcp://hub.miningpoolhub.com:17016 -u borzaka.nvidiaworker -p x -b 4068
```
With idle and another miner:

![mpm_gpu_drops_idle_lyra2z](https://user-images.githubusercontent.com/1230402/35481476-7e9e3118-0424-11e8-88e8-5061cc9dec60.png)

Miner:
```
     Speed Active                      Launched Command
     ----- ------                      -------- -------
14,12 MH/s 00 Days 00 Hours 04 Minutes Once     Bin\NVIDIA-Nanashi\ccminer.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:17025 -u borzaka.nvidiaworker -p x
```

But, it's looks like depends on the miner. Because with EWBF Equihash miner there is no drop.

**Comment by kevharper** [comment]
My CPU could not be much slower, I think.  E1-2100 1ghz with 8gb RAM.  Single 1070 and I see the drops.  I will as interval 300 to see if that helps.

**Comment by UselessGuru** [comment]
> My CPU could not be much slower, I think. E1-2100 1ghz with 8gb RAM. Single 1070 and I see the drops. I will add interval 300 to see if that helps

You will see drops.

If you are not using your rig for anything else than mining you can also try upping miner priority. 
Change Include.psm1:

`        $this.Process = Start-SubProcess -FilePath $this.Path -ArgumentList $this.Arguments -WorkingDirectory (Split-Path $this.Path) -Priority ($this.Type | ForEach-Object {if ($this -eq "CPU") {-2}else {-1}} | Measure-Object -Maximum | Select-Object -ExpandProperty Maximum)`

To
`        $this.Process = Start-SubProcess -FilePath $this.Path -ArgumentList $this.Arguments -WorkingDirectory (Split-Path $this.Path) -Priority ($this.Type | ForEach-Object {if ($this -eq "CPU") {-1}else {0}} | Measure-Object -Maximum | Select-Object -ExpandProperty Maximum)`

This will increase the priority for all GPU miners to 'Normal'. Priority will therefor be higher than MPMs main loop.
_For daily use this is not recommended because it will sloooooooooow down your computer, it will react sluggish._ 

**Note: This is an unsupported hack. Get better hardware :-)**

**Comment by borzaka** [comment]
In my case, this Normal priority didn't make my rig sluggish or slow.
Maybe can this priority settings can be a new option via command line?

The usage drops can be because of this in ccminer?
`[2018-01-28 17:45:39] Enabled stratum stale jobs workaround`

**Comment by UselessGuru** [comment]
> The usage drops can be because of this in ccminer?

Maybe, ask the miner developer.

**Comment by Adam1901** [comment]
I've had the same problem, im running a G440 (2 core 2 Threads)
I had a play with the priority however kept on saving the same issues.
I however just changed the timer from 60 seconds to 300 seconds. I'd rather it drop to 1% every 5 mins then every minute. For now I'm happy but may look into it further in the future.

**Comment by kevharper** [comment]
When I tried to change the interval I must have done it wrong.  The command line crapped out.  How do you do it?

**Comment by borzaka** [comment]
`-interval 300` for 5 minutes

**Comment by Adam1901** [comment]
@kevharper 
I modified the MultiPoolMiner.ps1 and changed the following lines

Line 15 to [Int]$Interval = 300 
Line 71 to $DecayPeriod = 300
