### ISSUE TITLE
btc withdraw, missing btc

### ISSUE THREAD

**Issue by fusation** [MultiPoolMiner/MultiPoolMiner#1028]
Hi

after 3months of mining I finally got to 0.0443 btc on mining pool hub and had on auto payout and when I saw my wallet it turns out that I only got 0.0028 btc what happened to all my btc did I just get scammed?
or did something go wrong with my auto payout? please help.

**Comment by komer83** [comment]
I guess much of it was lost for exchange and other fees. I'm not so happy with MPH or Zpool to be honest.

**Comment by fusation** [comment]
If you look at the difference i initially had  0.0443 btc after fees taken off and into my wallet it is 0.0028 btc that is about 93% fees thats way more then what mining pool hub fees mentions. Which are 0.9% pool fee + 0.2$ exchange fee + 0.0005 btc withdraw fee, so how did I end up with 93% lost?

**Comment by Crypto00** [comment]
It's weird.
0.9 % for the pool + 0.2 % for the exchange = 1.1 % so you should have 0.0443 - 1.1% * 0.0443 - 0.0005 = 0.0433127 BTC in you wallet after the withdrawal.
Maybe it's related to the slowness of the Bitcoin network because some people say you have sometimes to wait two days for the transactions ?

**Comment by aaronsace** [comment]
There is no percentage to withdraw; just a 0.0005btc fee. 

You are miss reading the transactions: 
https://bitcoin.miningpoolhub.com/index.php?page=account&action=transactions

**Comment by Crypto00** [comment]
The 0.2 % for auto exchange is a mistake because you already have your BTC.
But the pool has to take 0.9 %, is it when you withdraw or is it when your balance is credited ?

**Comment by aaronsace** [comment]
I don't believe the 0.9% pool fee has anything to do with withdrawing because each coin is it's own pool. 

Anyway, nothing to do with the 93% fee nonsense.
