### ISSUE TITLE
Wrong minername on the website for Excavator

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1029]
I tried to exclude Excavator with this command:
`-ExcludeMinerName Excavator1,Excavator2,ExcavatorNvidia2,ExcavatorNvidia3`

I have got the miner names from the website: [https://multipoolminer.io/miners](https://multipoolminer.io/miners) as the readme suggested.

There is no `ExcavatorNvidia2` and `ExcavatorNvidia3`. It should be `ExcavatorNvidia1` and `ExcavatorNvidia2`.

**Comment by cmbconcretefire** [comment]
I don't understand the whole 'exclude' command. It's easier to just delete the miners you don't want. And if you're knowledgeable enough to know which ones you do and don't want, I still haven't figured out why you'd spend more time writing the 'exclude' command than just deleting the miners. I assume I'm missing something.

**Comment by borzaka** [comment]
I feel more comfortable editing the Start.bat than deleting multiple files from multiple directories. 
After updating, you don't have to delete the miners again, you just copy your Start.bat.
And it's easier to undo.

**Comment by papacheal** [comment]
If you follow the thread on the excavator GitHub page, they recommend you don't use more than one worker per instance. I imagine this is why the ExcavatorNVidia3 was removed from later releases of MPM. In practice, I only use the ExcavatorNVidia1 and have disabled the Cryptonight and Neoscrypt in them (as those implementations are broken). The only algorithm they seem to be best with is Lyra2RE2 (i.e. Lyra2v2).

As far as managing miners, I find it cleaner to just create a backup directory off the MPM root called MinersDisabled and move any miners I don't want to use into it. This prevents them from being picked up by MPM but makes them readily accessible. If I want to get them back at a later date, I just move them back. Easy as pie and means I only run miners I want.

**Comment by fonyo** [comment]
*website updated*
