### ISSUE TITLE
MPM mined for 1 hour on aaronsace's account over 28 hours

### ISSUE THREAD

**Issue by jsaltzman** [MultiPoolMiner/MultiPoolMiner#1031]
I have had mpm running for about 28 hours. Over that time it mined for aaronsace's mph account for a half hour despite having -donate 0. Is there a minimum donation time?

![image](https://user-images.githubusercontent.com/2000982/34917277-588470b8-f912-11e7-8ed8-6da5f102b46a.png)

**Comment by aaronsace** [comment]
10 minutes per day. You mined 3 x 10 minutes. 

It's on the website home page and the GitHub read me.

**Comment by Kaoz99** [comment]
It's like a 0.7% fee and if you ask me  it's well worth encouraging the devs to maintain and improve this miner and lead to potentially very significant gains.

**Comment by jsaltzman** [comment]
Question answered, feel free to close the "issue."

**Comment by kevharper** [comment]
@aaronsaceso, did I read it right that it mined for almost 3x more time than stated it should?

**Comment by aaronsace** [comment]
@kevharper No, the donation works.

**Comment by jsaltzman** [comment]
@aaronsace am I reading this wrong, or did this mine for you for 30 minutes over the course of like 2 hours? I understand there is some overlap here since Im both cpu and gpu mining.

![image](https://user-images.githubusercontent.com/2000982/34925056-e72abfd6-f974-11e7-9900-0b35f8e9a3c8.png)

**Comment by aaronsace** [comment]
@jsaltzman If you think something is wrong then post the log files.

**Comment by jsaltzman** [comment]
Here are the logs from yesterday. I quit and relaunched the program a bunch since I use the computer, maybe that explains part of this, but you will see that in 3 of the 4 logs, MPM mined for you. You will see it all adds up to more than 10 minutes. Further, the last log (which ran overnight) alone adds up to more than 10 minutes despite running for less than 24 hours.

[2018-01-14_12-43-59.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1631592/2018-01-14_12-43-59.txt)
[2018-01-14_11-15-36.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1631593/2018-01-14_11-15-36.txt)
[2018-01-14_19-08-38.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1631594/2018-01-14_19-08-38.txt)
[2018-01-14_17-52-29.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1631595/2018-01-14_17-52-29.txt)

**Comment by aaronsace** [comment]
It overrun on the 19:08 log because MultiPoolMiner completely stopped functioning; same happened on the 11:15 log to a lesser extend. It is just as likely to miss the donation all together. 

Basically, don't turn on watchdog if you have deleted all the pool files: 

```
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
WARNING: No pools available.
```

**Comment by jsaltzman** [comment]
Thanks for taking the time to look into this.

I deleted all the pool files because MPM was mining on Nicehash and zpool despite the fact that I only specified MiningPoolHub as my pool. My computer isnt powerful enough to switch around like that, Ill never get paid out. Is there an alternate fix to this issue.

**Comment by aaronsace** [comment]
Just turn watchdog off as it is mainly for rigs.

**Comment by jsaltzman** [comment]
Ok, I will turn off watchdog. And Im assuming, add back the pools? Finally, would it be helpful to remove the -wallet parameter if Im only using MPH (I wonder if because I specified a -wallet it mines zpool and Nicehash)?

**Comment by aaronsace** [comment]
If you turn watchdog off then it's fine to have only one pool file.

**Comment by thericeking** [comment]
@aaronsace So I should turn watchdog off too? I only mine in Mining Pool Hub. I also delete the other pools I don't mine on.

**Comment by aaronsace** [comment]
@thericeking Yes; if you have deleted them all. 

MiningPoolHub has very limited algorithms for NVidia anyway; adding Zpool would be a better option.
