### ISSUE TITLE
Cannot download multiple miners

### ISSUE THREAD

**Issue by blckassassin** [MultiPoolMiner/MultiPoolMiner#1033]
I did a fresh setup MPM and everything is running okay except that I keep getting these cannot download errors for a few miners.  It looks like the folder names have changed which is why it's throwing the errors.  All I did was rename the folder names to what MPM is expecting and the errors have gone away and looks to be running fine.  Not sure if the code should be changed since these folder names have changed so it doesn't give the errors, just thought I would post about it in case someone else gets the same issue.

> WARNING: Cannot download C:\Users\Home\Desktop\MultiPoolMinerV2.7.1.4\Bin\AMD-Ni
> ceHash\sgminer.exe distributed at https://github.com/nicehash/sgminer/releases/d
> ownload/5.6.1/sgminer-5.6.1-nicehash-51-windows-amd64.zip.
> 
> WARNING: Cannot find C:\Users\Home\Desktop\MultiPoolMinerV2.7.1.4\Bin\AMD-NiceHa
> sh\sgminer.exe distributed at https://github.com/nicehash/sgminer/releases/downl
> oad/5.6.1/sgminer-5.6.1-nicehash-51-windows-amd64.zip.
> 
> WARNING: Cannot download C:\Users\Home\Desktop\MultiPoolMinerV2.7.1.4\Bin\Lyra2z
> -AMD\sgminer.exe distributed at https://github.com/djm34/sgminer-msvc2015/releas
> es/download/v0.3/kernel.rar.
> 
> WARNING: Cannot find C:\Users\Home\Desktop\MultiPoolMinerV2.7.1.4\Bin\Lyra2z-AMD
> \sgminer.exe distributed at https://github.com/djm34/sgminer-msvc2015/releases/d
> ownload/v0.3/kernel.rar.
> 
> WARNING: Cannot download C:\Users\Home\Desktop\MultiPoolMinerV2.7.1.4\Bin\Skein-
> AMD\sgminer.exe distributed at https://github.com/miningpoolhub/sgminer/releases
> /download/5.3.1/Release.zip.
> 
> WARNING: Cannot find C:\Users\Home\Desktop\MultiPoolMinerV2.7.1.4\Bin\Skein-AMD\
> sgminer.exe distributed at https://github.com/miningpoolhub/sgminer/releases/dow
> nload/5.3.1/Release.zip.

**Comment by grantemsley** [comment]
What do you mean by the folder names have changed?  Can you be more specific?

**Comment by blckassassin** [comment]
For the last example sgminer, The folder that gets downloaded is Release.zip, but MPM is looking for a folder named Skein-AMD right?  So if you change **Release** to **Skein-AMD** it works fine and didn't give the cannot download or cannot find error.

**Comment by grantemsley** [comment]
No, it automatically moves it to the right folder.

Most likely either your antivirus or Windows defender is interfering.  Windows defender in particular likes to do that without generating any alerts.

**Comment by blckassassin** [comment]
MPM moved it to the right folder, it just wasn't renaming the folder.  It would download to the Downloads folder, unzip to the Bin folder, but it wouldn't rename the new folder.  That's what appears to be causing the errors.

That would make sense if it was windows defender, I never got any sort of alert or notification.

**Comment by grantemsley** [comment]
Yeah, I've seen that exact behavior, and it was windows defender locking the files so the folder couldn't be renamed.
