### ISSUE TITLE
2.7.1.4 not closing miners when switching

### ISSUE THREAD

**Issue by i3luefire** [MultiPoolMiner/MultiPoolMiner#1034]
[2018-01-14_14-04-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1630042/2018-01-14_14-04-24.txt)
version 2.7.1.4 does not properly close old miners before opening new ones. so I end up with 8+ ccminer instances and 6+ excavator instances all trying to run at the same time.

**Comment by i3luefire** [comment]
![image](https://user-images.githubusercontent.com/3527233/34941430-46c02460-f9b9-11e7-9fc7-7682bfe92066.png)
this is on 2.7.1.2 so i guess it is happening on all versions. 
I only noticed this after adding a second GTX 1080 video card to the system with one GTX 1080

**Comment by UselessGuru** [comment]
This is very abnormal behavior. I doubt that this has to do with the added card.
Does this happen on every start, or just during initial benchmarking?

**Comment by i3luefire** [comment]
every start. 
I switched to nemos miner this morning before work. 
I do not have remote access to the miner but according to MPHstats it looks like it is not mining currently.
I can look in more detail after 1800 CDT.

**Comment by i3luefire** [comment]
i was able to confirm that NemosMiner-v2.3c is doing the same thing on that machine.

**Comment by aaronsace** [comment]
@i3luefire MultiPoolMiner closes the miner as if you press the close button. 

What's odd about your task manager is that they are backgroud processes...

**Comment by i3luefire** [comment]
i agree that is odd. it seems when i first start the miner that it backgrounds a window or 2 but idk if that is it trying to download something or if it is opening the miners that way.

**Comment by i3luefire** [comment]
since i am not at home i cannot really do much troubleshooting. but i had someone at the house restart the computer to close out all the background tasks and had them run [the stupid easy miner that tends to lose millions of $worth BTC] while i am at work that way i am not missing out on most of a day's worth of mining.

**Comment by aaronsace** [comment]
This fail safe needs adding (but don't add to the wrapper): 
`if(-not $this.Process.WaitForExit(10000)){$this.Process.Kill()}`

**Comment by i3luefire** [comment]
should i try to run from source. [https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip](url) when i get home or just make a fresh install folder for the 2.7.1.4 ?

**Comment by aaronsace** [comment]
Let me know if that mitigates the problem and I will add to the next release.

**Comment by aaronsace** [comment]
Don't run the source, stick with the release.

**Comment by i3luefire** [comment]
In what file and where in the file does the line of code you posted go? 
`MultiPoolMiner.ps1` at some line# ?

**Comment by aaronsace** [comment]
Here: 
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/f21fb9180de38f0f9ac5e3c432ca3ad1e36dfb3a/Include.psm1#L514-L517

**Comment by i3luefire** [comment]
Okay. The problem was that stupid auto start idea i had with the task scheduler. I forgot I actually tried that out because I did it on ambien. So that was the problem. 

Sorry.
