### ISSUE TITLE
MPM switching between Nicehash regional servers while mining any one NH also

### ISSUE THREAD

**Issue by TagUrToast** [MultiPoolMiner/MultiPoolMiner#1035]
Hi,

I've found this issue where MPM likes to switch between servers in a region while mining. For example, It will keep switching between neoscrypt.HK.hicehash.com then to neoscrypt.IN.hicehash.com then to neoscrypt.BR.hicehash.com etc.

The issue that this causes, is that the miner keeps being closed, then reopened with the same algorithm, but different server. This causes at least 30sec of delay before shares are being accepted on neoscrypt for example.

Please see attached photo.

<img width="810" alt="screenshot 2018-01-15 11 01 33" src="https://user-images.githubusercontent.com/35436664/34927561-25ebb770-fa0b-11e7-8559-56c1513819d1.png">

While I've thought about just taking additional Nicehash servers out of a region, I would prefer not to, as it's a great method of providing some form of fault tolerance. 

Does anyone else have this issue and/or a fix?

Also - Using Asia region if it makes a difference.

**Comment by UselessGuru** [comment]
Can no longer reproduce this issue. Please create a new issue if required.
