### ISSUE TITLE
Possible to add different wallets for different pools?

### ISSUE THREAD

**Issue by russellt83** [MultiPoolMiner/MultiPoolMiner#1036]
Hi Guys,

Is it possible to add different wallet addresses and currencies for different pools? And also different payout currencies for pools that autoconvert like zpool and hashrefinery?

I'd do it myself if i was smart enough. I've figured out to change the wallet address in start.bat and the currency in the pool file.

**Comment by UselessGuru** [comment]
This is NOT implemented in the current edition of MPM. I might be implemented in a later version.

However: MPM is witten in powershell so you can add the necessary features yourself:
Open each pool file (folder "\Pools") and look for  
`$Name = Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName`

Next to this line add
`$wallet="...your...wallet..here..."`
, or for pools that require a username add
`$username = "put_your_username_here"`

**Comment by fonyo** [comment]
Please do what @UselessGuru mentioned at your own risk. There is a reason this has not been implemented (at least yet), it can cause you to lose your hard-earned $£€ for mining if the pool does not have enough coins to settle your balance.
