### ISSUE TITLE
New Excavator version is out

### ISSUE THREAD

**Issue by Kaoz99** [MultiPoolMiner/MultiPoolMiner#1038]
Excavator tends to be pretty good in general and this version improves Neoscrypt and adds Nist5. Should be worth adding ASAP :)

**Comment by borzaka** [comment]
[Version 1.3.9 alpha NVIDIA](https://github.com/nicehash/excavator/releases)

**Comment by alucard20724** [comment]
neoscrypt doesn't work for me on any of my machines.. 1060,1070, nor 1080ti... it just fails.  1.3.7a, 1.3.8 both fail for me also.

nist5 works fine with this newest release

**Comment by borzaka** [comment]
For me ExcavatorNvidia1 works, ExcavatorNvidia2 doesn't.

**Comment by papacheal** [comment]
As mentioned in the release notes for the new Excavator (and previous ones), don't use more than one worker thread on any protocol other than Equihash (max of 2). My recommendation is to remove ExcavatorNVidia2/3 from your miners folder permanently, as there are better Equihash miners anyway (DSTM, BMiner). Using ExcavatorNVidia1 for Neoscrypt requires you have lots of virtual memory set up (very roughly 8GB x number of GPUs).

**Comment by SaintPistachio** [comment]
Seems to work really well for nist5. Better than the other miner I have listed for it.

**Comment by Kaoz99** [comment]
I manually updated the excavator files, just wondering if adding Nist5 functionality is a simple fix I can do on my side?

**Comment by aaronsace** [comment]
Yes, the files in the folder called 'miners' are the configuration files.

**Comment by UselessGuru** [comment]
> Nist5 functionality is a simple fix 

Edit the excavator miner files, look for the part 
```
$Commands = [PSCustomObject]@{
    "blake2s" = @() #Blake2s
```
and an entry "nist5" = @() #Nist5

**Comment by borzaka** [comment]
Excavator miner config files for NVIDIA:
- Miners/ExcavatorNvidia1.ps1
- Miners/ExcavatorNvidia2.ps1

After adding that line what UselessGuru wrote, add `nist5` to your `-algorithm` option in your .bat file as well.
Note: not all pools has nist5 algo support, but for example NiceHash has, so I added `nicehash` to the `-poolname` option. In this case, you need to add your NiceHash/external wallet BTC address via `-wallet` option as well.

**Comment by platinum4** [comment]
[This issue](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/971) may still occur on 1.3.9alpha

**Comment by papacheal** [comment]
For what it's worth, 1.4.0alpha is now out, with Neoscrypt fixes/improvements.

**Comment by borzaka** [comment]
I had 3% improvement on NeoScrypt.

And there is a new version :)

[Version 1.4.1 alpha NVIDIA](https://github.com/nicehash/excavator/releases)
> fixed reconnect issues on Equihash, DaggerHashimoto and CryptoNight

**Comment by UselessGuru** [comment]
Testusers wanted: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1104

**Comment by Braintelligence** [comment]
@UselessGuru I'm on it.
