### ISSUE TITLE
10+ hours mining Skein %67 accuracy Thanks MPM

### ISSUE THREAD

**Issue by thericeking** [MultiPoolMiner/MultiPoolMiner#1039]
10+ hours mining Skein %67 accuracy Thanks MPM

Only noticed it now. All my miners did the exact same thing. This is the second time this happens to me.

SwitchPrevention was on default 2

Lost $

**Comment by papacheal** [comment]
The solution is simple: if you are getting crappy payout from a flaky algorithm with high Margin of Error, don't use it.

If you'd like to try a customized Margin of Error calculation I suggested, see #1018 for details. It won't necessarily stop Skein from jumping the queue, but it should help overall for less flaky algorithms.

From my experience, the recommended list for solid profitable NVidia protocols right now is:

neoscrypt,equihash,lyra2re2,lyra2v2,lyra2z,x17,phi,nist5 (+xevan if you're feeling saucy)

Couple that with an "-interval" of at least 300 and you'll be good. This assumes you're using pool(s) with legit payout, no hash-stealing etc.

**Comment by aaronsace** [comment]
Even set to all the algorithms, it has never mined Skein for 10 hours. 

This is a place to report issues, please attach full log(s) files.

**Comment by platinum4** [comment]
Close this.  This is due to mismanagement of one's own miners.
