### ISSUE TITLE
PC unresponsive while mining after Windows update. Halp

### ISSUE THREAD

**Issue by BocajisH3R3** [MultiPoolMiner/MultiPoolMiner#1040]
CPU: i7 7700
GPU: 1080Ti

I understand this isn't really your problem, but I've browsed through the web as best I can to no avail.
Would be appreciated if I could get some input.

Process "Client Server Runtime Process" peaks at 90+% for 2s anywhere between 10s and 30s repeatedly on GPU usage, causing mouse to become unresponsive and laggy, while GPU miner is running. (Normal usage with no miner running peaks at just 5% of GPU)

Doesn't seem to be linked to any action by miner in particular. It does the same while only the miner windows and Task manager are open, and I'm not touching anything else, nor moving my mouse (GG Microsoft)

Is there a way I can try and diagnose this a little further?
Can I throttle the miner to 50% of the GPU to see if it has the same effect, and if so how?
Changing "Alloc_Percent" in my .bat doesn't seem to have the desired outcome.

**Comment by komer83** [comment]
My guess is Neoscrypt, just adjust the insanity.

**Comment by fonyo** [comment]
Insane enough as is! 😜
