### ISSUE TITLE
When you add ahashpool?

### ISSUE THREAD

**Issue by Alex735566** [MultiPoolMiner/MultiPoolMiner#1041]
Really need this pool with a small Commission

**Comment by aaronsace** [comment]
Please stop spamming the issues: 
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Pools/AHashPool.ps1

**Comment by Alex735566** [comment]
in ahashpoo works only 4 of the algorithm?
 ( $ AHashPool_Algorithm_Norm ) {
        "equihash" { $ Divisor  / =  1000 }
        "blake2s" { $ Divisor  * =  1000 }
        "blakecoin" { $ Divisor  * =  1000 }
        "decred" { $ Divisor  * =  1000 }

How can I get the bat file to ahashpool?

**Comment by Alex735566** [comment]
you have written to txt file

- Supports benchmarking, multiple platforms (AMD, NVIDIA and CPU) and mining on MiningPoolHub, Zpool, Hash Refinery and Nicehash (Ahashpool support is coming soon)

**Comment by Alex735566** [comment]
WARNING: Pool API (AHashPool) has failed.
WARNING: Pool API (ItalYiiMP) returned nothing.
