### ISSUE TITLE
Tell me how mine is better at all or 1 pool

### ISSUE THREAD

**Issue by Alex735566** [MultiPoolMiner/MultiPoolMiner#1042]
Tell me how better mine 1 farm with 8 graphics cards, all to use a pooled or sit on one? When constantly jumping from one to the other, then little should be charged?

**Comment by aaronsace** [comment]
I recommend using between 2 and 3 pools.

**Comment by Alex735566** [comment]
any?

**Comment by Alex735566** [comment]
Which pools?
