### ISSUE TITLE
Is it possible to use all algorithms?

### ISSUE THREAD

**Issue by Alex735566** [MultiPoolMiner/MultiPoolMiner#1043]
Tell us why in the bat file does not include all algorithms which are listed here https://multipoolminer.io/algorithms?
What will happen if they are all to write in bat file?

**Comment by Alex735566** [comment]
What algorithms exactly is better off?

**Comment by aaronsace** [comment]
It's an example; you don't need to specify any algorithms.

**Comment by Alex735566** [comment]
What algorithms are best to use and what should I turn off?

**Comment by aaronsace** [comment]
Up to you; if you are not sure then you can try them all or stick to the example ones for now.

**Comment by Alex735566** [comment]
What algorithms do not work properly and they need to be turned off?

**Comment by aaronsace** [comment]
Users maybe able to assist with optimal configurations.

**Comment by Alex735566** [comment]
Friends, please help advice what is necessary to disable the algorithms that would have all worked and was considered correctly?

**Comment by komer83** [comment]
Which GPU you use? I've selected everything NiceHash supports and let it run. MPM is pretty smart in switching.

**Comment by Alex735566** [comment]
I use nwidia 1060 3 gb, you only use the pool nisehash?

**Comment by komer83** [comment]
Nvidia is good, go for Neoscrpyt, Skunk, nist5, lyra,lyra2rev2, blake2s, sib (x11gost) and Equihash (also Sia, but I haven't seen any active mining on that) . Today I'm only using Nicehash as it gives me much better results then zpool and MPH, I haven't checked all the pools supported by MPM, will try next version.

**Comment by fonyo** [comment]
1. Check [whattomine.com](http://whattomine.com/coins?utf8=%E2%9C%93&adapt_q_280x=1&adapt_q_380=0&adapt_q_fury=0&adapt_q_470=1&adapt_q_480=1&adapt_q_570=0&adapt_q_580=1&adapt_q_vega56=0&adapt_q_vega64=0&adapt_q_750Ti=0&adapt_q_1050Ti=0&adapt_q_10606=1&adapt_q_1070=6&adapt_1070=true&adapt_q_1070Ti=0&adapt_q_1080=0&adapt_q_1080Ti=0&eth=true&factor%5Beth_hr%5D=180.0&factor%5Beth_p%5D=720.0&grof=true&factor%5Bgro_hr%5D=201.0&factor%5Bgro_p%5D=780.0&x11gf=true&factor%5Bx11g_hr%5D=69.0&factor%5Bx11g_p%5D=720.0&cn=true&factor%5Bcn_hr%5D=3780.0&factor%5Bcn_p%5D=600.0&eq=true&factor%5Beq_hr%5D=2580.0&factor%5Beq_p%5D=720.0&lre=true&factor%5Blrev2_hr%5D=213000.0&factor%5Blrev2_p%5D=780.0&ns=true&factor%5Bns_hr%5D=6000.0&factor%5Bns_p%5D=780.0&lbry=true&factor%5Blbry_hr%5D=1620.0&factor%5Blbry_p%5D=720.0&bk2bf=true&factor%5Bbk2b_hr%5D=9600.0&factor%5Bbk2b_p%5D=720.0&bk14=true&factor%5Bbk14_hr%5D=14400.0&factor%5Bbk14_p%5D=750.0&pas=true&factor%5Bpas_hr%5D=5700.0&factor%5Bpas_p%5D=720.0&skh=true&factor%5Bskh_hr%5D=165.0&factor%5Bskh_p%5D=720.0&factor%5Bl2z_hr%5D=420.0&factor%5Bl2z_p%5D=300.0&factor%5Bcost%5D=0.1&sort=Profitability7&volume=0&revenue=24h&factor%5Bexchanges%5D%5B%5D=&factor%5Bexchanges%5D%5B%5D=abucoins&factor%5Bexchanges%5D%5B%5D=bitfinex&factor%5Bexchanges%5D%5B%5D=bittrex&factor%5Bexchanges%5D%5B%5D=bleutrade&factor%5Bexchanges%5D%5B%5D=cryptopia&factor%5Bexchanges%5D%5B%5D=hitbtc&factor%5Bexchanges%5D%5B%5D=poloniex&factor%5Bexchanges%5D%5B%5D=yobit&dataset=Main&commit=Calculate) 
2. Change the settings to match the (number of) cards you have, don't change anything else.
3. Press calculate
4. It will show you the top most profitable coins in the last 7 days.
5. Look through the list and add the top 5 algorithms to your start.bat file using the correct commands and parameters.

This will enable you to have a list of highly profitable but more importantly STABLE algorithms.

**Comment by Alex735566** [comment]
komer83, are you using nisehash with this program or native, which on their official website?
Why nisehash gives better profit than other pools?

**Comment by Alex735566** [comment]
fonyo, and how did you do it? can I have your list of algorithms?

**Comment by Alex735566** [comment]
fonyo, you can read more why you cannot use all the algorithms, or where you can read about it

**Comment by komer83** [comment]
@Alex735566 I use Nicehash with MultiPoolMiner for now, it gives me about 10-20% more then the native software, mainly because of Nist5 and Keccak. Why NH gives better profit? to be honest, I don't. I guess there are less fees because you don't pay for exchanging the coins to BTC.

**Comment by Alex735566** [comment]
@komer83 на русском можете общаться?

**Comment by komer83** [comment]
@Alex735566 No :-P (I can read some Russian, but can't speak or write)

**Comment by Alex735566** [comment]
@komer83 какую программу ты используешь для nicehash, nisehash miner или MultiPoolMiner?

**Comment by Alex735566** [comment]
@fonyo and how did you do it? can I have your list of algorithms?

**Comment by SaintPistachio** [comment]
I don't use any -algorithms in my start.bat. A majority of my pool time in on ahashpool. I use Hashrefinery,AHashPool,miningpoolhub,miningpoolhubcoins,zpool,nicehash.

**Comment by Alex735566** [comment]
I don't understand how you can use different pools without algorithms?

**Comment by Alex735566** [comment]
I don't understand how you can use different pools without algorithms @SaintPistachio

**Comment by Alex735566** [comment]
@SaintPistachio I don't understand how you can use different pools without algorithms?

**Comment by SaintPistachio** [comment]
My options look like this.

`set "command=& .\multipoolminer.ps1 -wallet **BTCWalletAddress** -username **MPHUsername**-workername **YourWorkerName** -region us -currency btc,usd -type nvidia -poolname Hashrefinery,AHashPool,miningpoolhub,miningpoolhubcoins,zpool,nicehash -donate 24 -watchdog -switchingprevention 2"`

**Comment by fonyo** [comment]
*Just for you:*
       -poolname miningpoolhub,nicehash -algorithm ethash,ethash2gb,equihash,lyra2rev2,neoscrypt,skunk

All I did is followed my own instructions to get historic profitability data for the last 7 days for 1060 cards. I directly linked to the pre-defined settings. I cannot do more than that.

If you are interested in the whys, please read the Documentation a few times and carefully! The README has become quite extensive on explaining the whole logic of MPM but even knowing the commands should give you a better understanding of the software. I am well aware people don't like to read in general but I can only state what is already there. 

There are Miner and Algo lists on the website at https://multipoolminere.io, all organised neatly in tables that should give you a better understanding of the available parameters for the aforementioned categories, as well as what we are currently working with.

@SaintPistachio Please don't confuse each other with unconventional usage. Listing all pools will also spread the earnings. For a single card it can be an eternity for a single payout. I appreciate the help and the idea, though!

**Comment by SaintPistachio** [comment]
With the profitability settings should it still need algos to be limited? Wouldn't that do all the work for you?

**Comment by Alex735566** [comment]
Here is what I got? Is this normal?
![image](https://user-images.githubusercontent.com/35488013/35029614-919f3dac-fb7d-11e7-8051-359f599330ad.png)

**Comment by Alex735566** [comment]
Why is it always 0?

**Comment by Alex735566** [comment]
if the benchmark to beat is not correct, then when this algorithm will work, Hasrat this algorithm will be updated?

**Comment by aaronsace** [comment]
@Alex735566 Why you using the source code??? It's not even tested properly. 

Just download the release package and run the start.bat file: 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases

It all works fine.

**Comment by Braintelligence** [comment]
@fonyo Thank you for the thorough example!

**Comment by Braintelligence** [comment]
@fonyo How can I incorporate Lyra2z there, though?
