### ISSUE TITLE
How to modify the bat file to support 8 graphics cards?

### ISSUE THREAD

**Issue by Alex735566** [MultiPoolMiner/MultiPoolMiner#1045]

**Comment by aaronsace** [comment]
Seriously, stop creating loads of issues. It supports any number of cards.

**Comment by borzaka** [comment]
Quote from the [readme](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md):
> Currently mining with upto 6 GPUs is fully supported. Where required advanced users can create additional or amend current miner files to support mining with more than 6 graphics cards.
