### ISSUE TITLE
Claymore's CPU Cryptonight (XMR) added....

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1047]
Claymore's cpu cryptonight has always been the fastest xmr miner for cpu for intel processors for me.  the only this is that NsCpuCNMiner64 needs to be set up with administration rights in order to be the fastest.  I'm also having problems with mpm not shutting claymore down when switching algos.

https://bitcointalk.org/index.php?topic=647251.0

Here's the scrypt i've been running.

[
    {
        "Type":  "CPU",
        "Path":  ".\\Bin\\CryptoNight-Claymore-Cpu\\NsCpuCNMiner64.exe",
        "Arguments":  "-r -1 -mport 3333 -o $($Pools.CryptoNight.Protocol)://$($Pools.CryptoNight.Host):$($Pools.CryptoNight.Port) -u $($Pools.CryptoNight.User) -p $($Pools.CryptoNight.Pass)",
        "HashRates":  {"CryptoNight":  "$($Stats.ClaymoreCPU_CryptoNight_HashRate.Week)"},
        "API":  "Claymore",
        "Port":  "3333",
        "Wrap":  false
    }
]

**Comment by platinum4** [comment]
This script causes a fault in MultiPoolMiner.ps1

```
At C:\COIN\Miners\MultiPoolMinerV2.7.1.4\MultiPoolMiner.ps1:193 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
```

**Comment by platinum4** [comment]
Seems to be in the same code-string as this issue as well:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/920

**Comment by alucard20724** [comment]
i have been running it under 2.7.1.2, so i don't have an answer for the fault in 2.7.1.4

**Comment by UselessGuru** [comment]
Miner file added: https://github.com/MultiPoolMiner/MultiPoolMiner/commit/059d1c9e93653dd04baf9740722feef7dd50f75f
