### ISSUE TITLE
Can't get BMiner to run

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#1049]
There's at least one person on the bitcointalk.org forum with the same issue.

BMiner won't run.  It does nothing.  No output at all.

Even running it with the downloaded mine.bat file, or running from the command line, it just exits after a second or two.  No error message, no output at all.  Nada.

Anyone else having that problem?  Any idea how to fix it?  Maybe a dependency is missing on my system?

**Comment by Nexworks** [comment]
Running the 5.1 that came out the other day? Its been flawless for me (two systems with a 1070 each)

**Comment by grantemsley** [comment]
Have tried 5.1 and 5.0.  both do the same thing.

**Comment by Nexworks** [comment]
Something else running then its conflicting with? Id post this under the Bminer thread on bitcointalk as the dev is active there: https://bitcointalk.org/index.php?topic=2519271.0

**Comment by titvs** [comment]
No problems here @grantemsley ... Running ok on machines with a mix of GPUs: 980, 1050TI and 1070. Version 5.0.0.

**Comment by UselessGuru** [comment]
For those where it does NOT work? Does the path to MPM contain spaces?

**Comment by platinum4** [comment]
> For those where it does NOT work? Does the path to MPM contain spaces?

No spaces for mine.  Doesn't load; as we've discussed on your fork as well.

**Comment by UselessGuru** [comment]
There is no solution yet. Workaround: do not use BMiner (It is not really faster anyway); delete the Miners\Bminer.ps1 file.

**Comment by jsholcomb** [comment]
I was having a similar issue. I had to edit the bminer config file as it was adding the x as the password to the worker name and wasn’t causing issues creating a new worker which wasn’t following the rules MPH  needed.

**Comment by jsholcomb** [comment]
Also I see a bminer.txt in my miner folder but no bminer.ps1. The miner still is in the Bin folder so I am not sure how to tell the program to avoid the miner.

**Comment by UselessGuru** [comment]
Also read https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1127
