### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection

### ISSUE THREAD

**Issue by reo4k** [MultiPoolMiner/MultiPoolMiner#1050]
Parameter name: index
At line:1 char:1
+ & .\multipoolminer.ps1 -wallet <my wallet address> -us ...
 --
I installed the MPM on my win 10 1080ti machine and it worked perfectly. I then went to my win 7 980ti machine and did the exact same thing and I get this error. Also when I try to go back a version the excavator.exe won't work properly because it's missing .json files, specifically ethash_3.json

Any ideas for a fix would be appreciated.

**Comment by samdoe88** [comment]
I got the same on a single Radeon HD7850 (Tahiti)

**Comment by jumpingshades** [comment]
I'm having the same issue after editing my bat file. I'm using a gtx 1080. I should note that the bat file is different than the ones in the guide. They have extra lines and commands. I have even tried to make changes to make it identical to the guide, but the same "Index was out of range. Must be non-negative and less than the size of the collection." error pops up.

> C:\Mine\MultiPoolMinerV2.7.1.4>setx GPU_SINGLE_ALLOC_PERCENT 100
> 
> SUCCESS: Specified value was saved.
> 
> C:\Mine\MultiPoolMinerV2.7.1.4>set "command=& .\multipoolminer.ps1 -wallet ***************** -username ***** -workername ***** -region us -cu
> rrency usd -type nvidia -poolname miningpoolhub -algorithm cryptonight,ethash,et
> hash2gb,equihash,groestl,lyra2re2,lyra2z,neoscrypt,siaclaymore -donate 24 -watch
> dog -switchingprevention 2"
> 
> C:\Mine\MultiPoolMinerV2.7.1.4>pwsh -noexit -executionpolicy bypass -windowstyle
>  maximized -command "& .\multipoolminer.ps1 -wallet ***************** -username ***** -workername ***** -region us -currency usd -type nvidia
>  -poolname miningpoolhub -algorithm cryptonight,ethash,ethash2gb,equihash,groest
> l,lyra2re2,lyra2z,neoscrypt,siaclaymore -donate 10 -watchdog -switchingpreventio
> n 2"
> 'pwsh' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Mine\MultiPoolMinerV2.7.1.4>powershell -version 5.0 -noexit -executionpolicy
> bypass -windowstyle maximized -command "& .\multipoolminer.ps1 -wallet ***************** -username ***** -workername ***** -region us -curren
> cy usd -type nvidia -poolname miningpoolhub -algorithm cryptonight,ethash,ethash
> 2gb,equihash,groestl,lyra2re2,lyra2z,neoscrypt,siaclaymore -donate 10 -watchdog
> -switchingprevention 2"
> Index was out of range. Must be non-negative and less than the size of the
> collection.
> Parameter name: index
> At line:1 char:1
> + & .\multipoolminer.ps1 -wallet ***************** -us ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], ArgumentOutOfRangeExce
>    ption
>     + FullyQualifiedErrorId : System.ArgumentOutOfRangeException

**Comment by maciozo** [comment]
I also get this issue, even with the default `Start.bat`

**Comment by maciozo** [comment]
Fixed by installing Powershell 6.0.0

**Comment by samdoe88** [comment]
I have Powershell installed from the scratch off the links provided. So, it is of no help in my case.

**Comment by aaronsace** [comment]
Uninstall PowerShell 6.0**-RC2**
Install PowerShell 6.0
Download MultiPoolMiner 2.7.1.4
Upload full log file(s) to GitHub post

**Comment by samdoe88** [comment]
I have PowerShell 6.0.0.0 (sha1, sha256 signed Jan. 09, 2018)
Not sure how to check the miner’s version. Script modified Jan. 05, 2018 8:10:30 PM

**Comment by aaronsace** [comment]
v2.7.1.4: https://github.com/MultiPoolMiner/MultiPoolMiner/releases

**Comment by jumpingshades** [comment]
I have tried reinstalling powershell 6.0, but it is not making any difference for me.  Is my information posted above an adequate report or is something more needed?

**Comment by aaronsace** [comment]
Logs please.

**Comment by jumpingshades** [comment]
What directory are the logs stored? Do I need to enter a command or something to get to them?

**Comment by aaronsace** [comment]
In the folder called 'logs'.

**Comment by jumpingshades** [comment]
I have had to create the folder myself. I will see what happens.

**Comment by aaronsace** [comment]
That's not how it works. 

Download the release, extract then double click on 'start.bat': 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases

**Comment by Muaadib** [comment]
Getting the same issues as well. GTX1060 ran fine on windows 10 but when i moved to windows 7 (using the same MPM folder to mine) i keep getting this message. Redownloaded the official release but still get the message.

**Comment by aaronsace** [comment]
Check PowerShell 6 is installed and that .NET is up to date; I would also recommend ditching Windows 7. 

No logs means MultiPoolMiner hasn't even opened.

**Comment by Muaadib** [comment]
PS6 and .NET up to date. I can't ditch windows 7 since this PC has an ancient P4 cpu that doesn't support win 10 64. It can run win 10 32-bit but all miners fail to run in it

**Comment by reo4k** [comment]
It is still an issue. 

    On Thursday, February 8, 2018 8:48 AM, UselessGuru <notifications@github.com> wrote:
 

 Is this still an issue? If not then please close - TIA.—

**Comment by UselessGuru** [comment]
Could you please provide 
- logs
-some screen shots
- directory listing of the 'Pools' and 'Miners' folder

**Comment by Freshbrewed** [comment]
Here is a simple solution for your problem. It worked for me after I've tried everything & everything I could find.

Step 1. Press **Windows**-button, then type "**pwsh**". If nothing happens or the window disappears right after, then you are _missing packages needed to run PowerShell 6.0/6.0.1_ correctly.

Step 2. Supposedly you don't have Windows 7 Service Pack 2 installed. Go install it here:
https://answers.microsoft.com/en-us/windows/forum/windows_7-update/how-to-obtain-and-install-windows-7-sp2/c2c7009f-3a10-4199-9c89-48e1e883051e?auth=1

Follow instructions in there. You need **KB3020369** and **Convenience Update (SP2)** which are listed in the aforementioned site.  First, apply KB3020369 and then Convenience Update (SP2).

3. Restart computer. Press _Windows -key_ and type "**pwsh**". If a window opens and stays open, the missed packages were installed succesfully by Windows Updates. Now everythings working as expected!

**Comment by grantemsley** [comment]
Closing outdated issue.  If this is still a problem in the latest version (and there currently isn't an open issue for it) please open a new one.

**Comment by e-stonia** [comment]
I installed Powershell 6,0,2 and had same issue. Then installed 6.0.0 and it all worked fine until MPM downloaded and istalled again 6.0.2 and again not working.

**Comment by Dulanic** [comment]
Ya I keep seeing this too, I finally resolved it by adding the powershell path to my env variables. Seems MS removed pwsh as a environment command in recent releases.
