### ISSUE TITLE
Monitor command line in start.bat file

### ISSUE THREAD

**Issue by wizmanza** [MultiPoolMiner/MultiPoolMiner#1052]
Hi guys,

I've added the url monitor as well as the key like this
-minerstatusurl https://multipoolminer.io/monitor/miner.php -MinerStatusKey xxx-xxx-xx

it gives an error on startup stating invalid parameter.

Please can someone paste an example?

Thanks all

**Comment by aaronsace** [comment]
I've not pushed that change yet. The current code branch uses your BTC wallet.

**Comment by wizmanza** [comment]
ah ok thanks, just saw on you main site....how must i use BTC address to do monitoring?

**Comment by aaronsace** [comment]
I believe it should pick it up from the command line '-wallet'

**Comment by wizmanza** [comment]
:-) i have the -walltet setting of course....I'm asking how can i monitor via a URL to see if worker is active? or must i wait for when you publish this new feature? Thanks aaronsace

**Comment by aaronsace** [comment]
It should still work: https://multipoolminer.io/monitor/?address=1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb

**Comment by wizmanza** [comment]
mine does not...must i have the -MinerStatusKey setting in startfile? and just specify wallet adress?

**Comment by aaronsace** [comment]
I'm running the code. 

Are you using the latest master code branch?

**Comment by wizmanza** [comment]
2.7.1.4?

**Comment by wizmanza** [comment]
set "command=& .\multipoolminer.ps1 -wallet 1Dw8jSHSgiRZUULh5SpZ9S87hcBmpA9pPi -username wizmanza -workername digger -region europe -currency btc,usd,zar -type nvidia -poolname miningpoolhub,miningpoolhubcoins -algorithm equihash,groestl,lyra2re2,lyra2z,neoscrypt,ethash,siaclaymore,skein,x11,ethash2gb,myriadGroestl,Keccak -donate 0 -watchdog -switchingprevention 2 -excludeminername nsgminer, hsrminer, nsgminernvidia, hsrminernvidia, PalginNvidia, Palgin, ReorderNvidia, Prospector, Eminer -ExcludePoolName Nicehash, BlockMunch, AhashPool, HashRefinery,zpool"

here's my batch file

**Comment by wizmanza** [comment]
never mind...got it...bit slow this morning
thanks for the help.

**Comment by wizmanza** [comment]
you can close the "issue" - thanks
