### ISSUE TITLE
Claymore Ethash 10.5 is out

### ISSUE THREAD

**Issue by platinum4** [MultiPoolMiner/MultiPoolMiner#1055]
https://mega.nz/#F!O4YA2JgD!n2b4iSHQDruEsYUvTQP5_w

**Comment by titvs** [comment]
It has been reported that a version of claymore miner has a security problem. Hope this one solves the issue.

http://www.tomshardware.com/news/claymore-miner-software-vulnerable-botnet,36356.html

**Comment by UselessGuru** [comment]
> it's easily dealth with by making monitoring read-only.

True, the problem here is backwards compatibility, We can easily implement the read-only feature in the miner file, but:
- do all users want this?
- it will probably case a lot of issues here because not all users will update the binary

**Comment by titvs** [comment]
@UselessGuru and how about including it on the next release of MPM with the read-only feature active?

**Comment by UselessGuru** [comment]
> That's not a severe issue and probably it's easily dealth with by making monitoring read-only.

Changes all Claymore ports to negative value.
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/8877c60a1432b2b03e9201cc5c5f77168bf49100
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/b9ce59231090595708e687540fae2dff64ebdcae
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/7e327e93d22b3a8df32b230c35de7e50fd4fc320
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/ea6f0454a120ac88ae3ee486f9c21513bc97b423
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/de76ddbfc540da3e11986c1ea0c200601186c827
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/f6b09baa8c0c018741737f98617f6f6de4a9485d

**Comment by yuzi-co** [comment]
"Port": "23333" should remain positive number, unless the api parsing script knows how to handle negative values...

only the "-mport -23333" should be negative

**Comment by UselessGuru** [comment]
> only the "-mport -23333" should be negative

Good point - I'll fix this!
