### ISSUE TITLE
CPU won't start

### ISSUE THREAD

**Issue by komer83** [MultiPoolMiner/MultiPoolMiner#1056]
Getting some strange thingy. Still using 2.7.1.4

[2018-01-17_12-11-36.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1638645/2018-01-17_12-11-36.txt) 

![screen shot 2018-01-17 at 12 41 13](https://user-images.githubusercontent.com/20399230/35038801-922c4452-fb84-11e7-8f9b-1d5e483497ef.png)

**Comment by platinum4** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1047

**Comment by UselessGuru** [comment]
> Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi

is NOT in the official MPM code base. You must be using code from an alternate build [probably mine?](https://github.com/UselessGuru/MultiPoolMiner).
Please download and reinstall MPM into a new directory. Then copy start.bat from the old installation. If you want to keep your stats (benchmark results) then also copy the stats folder to the new installation.
