### ISSUE TITLE
Benchmarking Stats for GPU/CPU tuning?

### ISSUE THREAD

**Issue by rednkentucky** [MultiPoolMiner/MultiPoolMiner#1059]
I am curious how often the bench marking stats are updated?  Is it only done when you run the "ResetBenchmark.bat" after the first bench marking?  

If this is the case, is it possible to update the stats as they are run dynamically updating the stats?  

The reason I ask this is I would like to tune my CPU and GPU's clocks and voltage but don't wish to run the bat file and wait for all of the stats to be updated every time I adjust something.  Also when I only update a single GPU or the CPU.  This ability would make tuning quicker, easier and more profitability if it was reported back to Stats every time a miner or algorithm was run. Then once these are reported for MPM to report on the latest stat would be shown and the last time it was reported. 

I searched through issues and couldn't find anything that pointed me to this question; if there is please point me there.  

Thank you for all y'all are doing!

**Comment by komer83** [comment]
The benchmarks just give you a base line, you can, but there's no need, to run it again. Perhaps if you change versions or drivers if you want to see any changes.

**Comment by UselessGuru** [comment]
MPM updates the stats for the running miner on every loop. 

There is no reason to reset stats unless: you change your hardware or overclock settings.
So far I have not seen any mayor performance changes caused by driver updates.

**Comment by cacipriani** [comment]
I sometimes have an issue where my performance goes down by around 20%. I do not know why, because my OC settings remain the same, For example, sometimes I get 16mh/s on Ethhash2gb and sometimes I get 13mh/s. I haven't figured out what causes it.  However, when it happens, the performance drops enough that it is below the threshold of being counted and updating the performance stats. Is there any way to adjust the threshold percentage so that it can be counted?

**Comment by UselessGuru** [comment]
> Is there any way to adjust the threshold percentage so that it can be counted?

[Readme Q18](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#q18-how-to-change-fault-tolerance-limit-to-a-higher-percentage)

**Comment by OzGoober** [comment]
One of my GPU's was running hot (80 c) and it throttled down the GPU clock to less than 50% of max. I manually set the fan speed to 75% and gpu clock went back to max.
