### ISSUE TITLE
Why shows 000000

### ISSUE THREAD

**Issue by Alex735566** [MultiPoolMiner/MultiPoolMiner#1060]
I did reset the benchmark and reset a profit, but why is 0000 after passing the benchmark?
![image](https://user-images.githubusercontent.com/35488013/35059509-304010c6-fbdd-11e7-977b-e30f309a38c1.png)

**Comment by UselessGuru** [comment]
Logs please :-) I suspect a temporary connection problem to Coinbase.

**Comment by n3cr0cr0w** [comment]
I have the same issue, I'm not sure if it is a coinbase issue, I also noticed it no longer says USD/Day but now u/Day.

**Comment by Alex735566** [comment]
[2018-01-17_23-31-47.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1640178/2018-01-17_23-31-47.txt)

[MultiPoolMiner-2018-01-17.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1640173/MultiPoolMiner-2018-01-17.txt)

**Comment by aaronsace** [comment]
@Alex735566 Please stop using the code. 

This is the release: 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases

**Comment by n3cr0cr0w** [comment]
Alex, what he is saying is we shouldn't pull the code from git but use the packaged official releases.

**Comment by Alex735566** [comment]
I don't know what he wants.

**Comment by n3cr0cr0w** [comment]
Download from here. ----> https://github.com/MultiPoolMiner/MultiPoolMiner/releases

**Comment by Alex735566** [comment]
What is there to download? I all downloaded there already

**Comment by n3cr0cr0w** [comment]
You cloned/downloaded from the development branch which has code that isn't ready for release. This is the same thing I do. You shouldn't file bug requests when you are running the bleeding edge code. Bug reports for this project are for helping when you are running the official release code.

**Comment by bloodclot** [comment]
Set currency as `-currency usd,btc,eur `

and it will only show USD.

There seems to be an issue when listing only usd, only btc works though.
