### ISSUE TITLE
what code I use, you can normally explain and not to close the thread?

### ISSUE THREAD

**Issue by Alex735566** [MultiPoolMiner/MultiPoolMiner#1061]

**Comment by Alex735566** [comment]
I used this to run
cd /d %~dp0

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

set "command=& .\multipoolminer.ps1 -wallet 17UL8xLfSirWdxsW4ggJjy7QF41fe31TkV -username Alex735566 -workername 1 -region europe -currency usd -type nvidia -poolname miningpoolhub,miningpoolhubcoins,zpool,nicehash -algorithm cryptonight,decred,decrednicehash,ethash,equihash,groestl,lbry,lyra2re2,lyra2z,neoscrypt,pascal,sia,siaclaymore,sianicehash,sib,skunk,nist5,keccak -donate 10 -watchdog -minerstatusurl https://multipoolminer.io/monitor/miner.php -switchingprevention 2"

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0/PowerShell-6.0.0-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

pause

**Comment by Alex735566** [comment]
The developer, you can normally tell and not to close branches?

**Comment by aaronsace** [comment]
@Alex735566 Please stop post non-sense. This isn't a chat room. 

Just download the release and use it: 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases

**Comment by Alex735566** [comment]
it does not work
@

**Comment by aaronsace** [comment]
@Alex735566 It's right here: https://github.com/MultiPoolMiner/MultiPoolMiner/releases

If it does not work then post a real issue with the log(s).
