### ISSUE TITLE
PS 6 being installed every time I restart?

### ISSUE THREAD

**Issue by xfactor8383** [MultiPoolMiner/MultiPoolMiner#1062]
I downloaded PS 6 before installing MPM, but now everytime I start MPM it auto downloads and installs again? Is that on purpose? Why is it built into the .bat file? I removed those lines from the .bat file and it still downloads PS 6 from github???

**Comment by tomasfil** [comment]
Hey, just unninstal from widnows the rc2 version and you should be fine.
