### ISSUE TITLE
Update PowerShell download link in the README.md and README.txt

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1063]
There is a new [v6.0.0 release of PowerShell Core](https://github.com/PowerShell/PowerShell/releases)

The *.bat files are already updated in the following commits: dc274eb624557f8c8cf6f9f25b759551b7dd4cd8, b2cbf13dc9fa278b56027fb4a9098a69b26506fa, 64f17d10254b8ebe0304c0d0d2128f4b57e823da, 6f91f56921286d05f27d107b98da75c2f5b54282

The [IMPORTANT NOTES](https://github.com/MultiPoolMiner/MultiPoolMiner#important-notes) part is still containing the RC version download link.

**Comment by UselessGuru** [comment]
[Links updated](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1064)
