### ISSUE TITLE
Whats the monitoring status key?

### ISSUE THREAD

**Issue by gatistaabb** [MultiPoolMiner/MultiPoolMiner#1067]
On the websites monitoring part, you can create a status key, what does it do since i dont use it anywhere at the config in local machine?

I tought it would be for identification...

**Comment by gatistaabb** [comment]
I figured that if you put your wallet you find your miner on status key... but the create new status key feature seems irrelevant.

Was just wondering...

**Comment by fonyo** [comment]
It will be used by users mining on MPH who don't have a btc address.
