### ISSUE TITLE
MultiPoolMiner.io website shows WordPress Setup Configuration File

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1068]
[MultiPoolMiner.io](https://multipoolminer.io) redirects to [https://multipoolminer.io/wp-admin/setup-config](https://multipoolminer.io/wp-admin/setup-config), where I can setup your WordPress :)

**Comment by aaronsace** [comment]
@fonyo Wordpress is corrupt; seems like something has been deleted...?

**Comment by fonyo** [comment]
WP has done an auto-update, and replaced some files. It was fixed within minutes from occurence.
