### ISSUE TITLE
Worker not showing up when running bminer. How do i know MPH is accepting hash?

### ISSUE THREAD

**Issue by simbee** [MultiPoolMiner/MultiPoolMiner#1070]
Updated to the latest master today. Now when bminer equihash is running, the worker does not appear on MPH. When MPM switches to another algo, the worker shows up. Am i still contributing with hash to my account at MPH? 

Im seeing some errors in the logfile. Not sure what they mean. Im attaching the log files. Help would be much appreciated

[2018-01-18_16-10-56.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1643684/2018-01-18_16-10-56.txt)
[MultiPoolMiner-2018-01-18.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1643685/MultiPoolMiner-2018-01-18.txt)

**Comment by UselessGuru** [comment]
This is the same issue as this: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1049

**Comment by simbee** [comment]
No its not. In my case Bminer is running. Its giving normal output like hashrate and accepted/rejected shares. 

My problem is that no worker shows up in MPH when running Bminer. Works fine when MPM switches to another algo and different miner. Anyone else with same issue?

**Comment by UselessGuru** [comment]
@simbee 

You seem to have a corrupt Miners\DSTM.txt miner file (errors in the log). 
How did you update to the latest master?
Before you update make sure ther are absolutely NO FILES in the folders
- Miners
- Pools

Bminer: The window stays minimized, is that what you are saying? From a code point of view this would not make any sense at all. All miners are started the same way (Wrapper excluded), so the should behave the same.

**Comment by simbee** [comment]
Sorry for being unclear. English is not my native language.

Everything seem to be running normal. Multipoolminer and Bminer window open. Output from Bminer also looks normal. Here is a screenshot: 
![screenshot](https://user-images.githubusercontent.com/26580361/35150619-5e292ba0-fd1b-11e7-8d76-1f2d0f94ccbb.jpg)

The problem is that my worker doesnt show up in miningpoolhubstats.com or at miningpoolhub.com when running Bminer through Multipoolminer. However, the worker does show up if i run Bminer manually outside of Multipoolminer. 

I did a fresh install in a new directory for the latest master. Then edited miningpoolhub batfile with my user/worker and deleted pools and miners i did not use. Then ran the bat file.

**Comment by UselessGuru** [comment]
> the worker does show up if i run Bminer manually outside of Multipoolminer.

When you run it manually outside MPM what command line are you using then?

What happens when you copy&edit(you will have edit and remove extra spaces & line break)&paste command the line from MPM?

**Comment by priyavadan** [comment]
I tried, this, am getting a Get-NetTCPConnection is not a valid cmdlet?

Running Powershell 6 ,so am unable to figure out why that would be..

**Comment by UselessGuru** [comment]
> I tried, this, am getting a Get-NetTCPConnection is not a valid cmdlet?

You are mixing to builds. Do not attempt to use miners & pools from [my build](https://github.com/UselessGuru/MultiPoolMiner) together with vanilla MPM, they are NOT COMPATIBLE. 

`while ([Bool](Get-NetTCPConnection -State "Listen" -LocalPort` comes from _my_ Bminer file :-)

If your are desperate and really want to use my miner files then change the beginning of MultiPoolMiner.ps1.

using module .\Include.psm1
**import-module $env:Windir\System32\WindowsPowerShell\v1.0\Modules\NetTCPIP\NetTCPIP.psd1**

**Comment by priyavadan** [comment]
correct, I wasnt able to find the release that had BMiner. 

Should I download this https://github.com/UselessGuru/MultiPoolMiner/archive/0.2-beta.zip ?

Above edits, will make my current issue go away I assume?

**Comment by UselessGuru** [comment]
> correct, I wasnt able to find the release that had BMiner.

[Bminer is supported](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/BMiner.txt), but can behave strange:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1049
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1070
BTW: It is not really faster.

> Should I download this https://github.com/UselessGuru/MultiPoolMiner/archive/0.2-beta.zip ?

Up to you, but then please post all finding in https://github.com/UselessGuru/MultiPoolMiner/issues
 > Above edits, will make my current issue go away I assume?

It did in my case :-)

**Comment by priyavadan** [comment]
Thanks, will try!

Actually i did notice bminer is about 3% faster than DSTM on my cards, thereby negating the DSTM fee + 1%
