### ISSUE TITLE
MPM just stops working without any message

### ISSUE THREAD

**Issue by aloth** [MultiPoolMiner/MultiPoolMiner#1072]
MPM just stops working without any message or any sign of failure!

I'm using a Ryzen 8-core and 2 GPUs (1x 1080, 1x 1070).

I tried to disable CPU mining, it did not help. As no message appears, I guess there is something wrong with a loop, e.g. running intervals forever. Also web monitoring does not get updated.

Disabling Watchdog did not help. I also tried @UselessGuru's fork with the same behavior.

Any ideas what could be wrong here?

**Comment by aaronsace** [comment]
Logs please.

**Comment by aloth** [comment]
Logs attached.

I'm using Remote Desktop to logon from another machine. MPM seems so become more alive, when I reconnect. Could that be the point? Miners do not pause, they just work.
[2018-01-18_18-50-58.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1644502/2018-01-18_18-50-58.txt)

**Comment by grantemsley** [comment]
This error seems to indicate some of your files are corrupt or have been edited incorrectly:

```
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\MPM\Wrapper\23333.txt' because it does not exist."
```

**Comment by aloth** [comment]
That file exists and has regular content:
[23333.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1644588/23333.txt)


Can it be an issue of the wrapper that stops working once the remote connection is closed?

**Comment by grantemsley** [comment]
But it doesn't exist when it tried to read it...hmm.  Odd.

Any chance you are accidentally selecting some text in the window?  That definitely freezes the script.

**Comment by UselessGuru** [comment]
Are u using the latest version of [API\Wrapper.ps1](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/APIs/Wrapper.ps1)?

**Comment by aloth** [comment]
Tried the latest Wrapper scripts, did not solve the problem.

@grantemsley: nothing was selected.

Is there anyone who could try to reproduce if this issue is related to closed Remote Desktop connection?

**Comment by grantemsley** [comment]
I access mine all the time over remote desktop and close the connection.  Never had an issue with it.

**Comment by titvs** [comment]
To rule out Remote Desktop, try with an alternative software like AnyDesk. I’m using it without issues.

**Comment by aloth** [comment]
Ok, confirmed. It’s not Remote Desktop’s fault.

What else could cause the issue?

**Comment by cmbconcretefire** [comment]
Probably way off base here, but have you disabled / optimized settings for screen savers kicking in....disabling sleep mode, optimizing power for full power 100% of the time, etc?

**Comment by komer83** [comment]
Don't use Remote Desktop, it creates a dummy user try UltraVNC (I use it)

**Comment by aloth** [comment]
Reinstalled Windows 10, now it works fine.
