### ISSUE TITLE
Guidance on the master version would be appreciated. 

### ISSUE THREAD

**Issue by cmbconcretefire** [MultiPoolMiner/MultiPoolMiner#1073]
I've been told that the 'release' version does not get updated in real time with all the changes being done on the master version. I'm fine with that. But guys, you are not 'fixing' these files in the master version for no reason. You ARE improving things. 

Perhaps a dumb question but worth a shot: Is there "parts" of the master I can safely incorporate into the release version at this point? And are there parts I should avoid for now? I seriously need to get on Skype. Screw it, I'm doing it now @aaronsace . Literally. No more putting it off. But a response to my question would be nice. Thanks guys.

**Comment by fonyo** [comment]
At this point in time, it is not wise to incorporate anything without serious powershell knowledge as there are many fundamental changes already merged onto the master. If you think we missed out on fixing bugs, could you please list their issue number here (such as #1073 - this one) so they can be looked at? 

We do appreciate your feedback but thrash talk will not help your case and will definitely be not tolerated. Thank you.

**Comment by cmbconcretefire** [comment]
Huh? ...... I don't know where you're getting 'thrash talk?' I've been telling @aaronsace for days I'd get on Skype and contact him to try to help out. I'm afraid this is just one of those unfortunate times where things didn't come out right over the internet. If you could have heard me say it out loud....I was in a very jovial mood. :) Sorry for the confusion.
