### ISSUE TITLE
Disable nvidia miners for AMD cards

### ISSUE THREAD

**Issue by AdriaanVisser** [MultiPoolMiner/MultiPoolMiner#1075]
I downloaded V2.7.1.4 yesterday (it updated from 2.7.1.1 every time I launched anyway), and to my annoyance the first thing MPM did was download excavator and then tried to benchmark 4 or 5 algorithms with it. Would it be possible to detect beforehand that I have an AMD card, and thus that downloading and attempting to benchmark excavator is a waste of time? The same holds for the CUDA version of prospector.
Otherwise MPM is running fine again, thanks for the effort!

**Comment by komer83** [comment]
Remove the amd flag in that start batch.

**Comment by UselessGuru** [comment]
Did you have "NVIDIA" in your start.bat even though you have a AMD only rig? This may explain your phenomena.

**Comment by UselessGuru** [comment]
> So removing '-type amd' should do the trick?

Nope, your config looks fine. There is an issue with miners that work on both, AMD & Nvidia hardware. We'll have to look into this.

>  Before benchmarking the double one shows 2 prospectors, 4 excavators and 2 Eminers, after benchmarking only the Eminers and one prospector are left.

This intended behavior. The disappeared miners failed repeatedly during benchmark, so MPM recorded a hash rate 0 for them -> they will no longer be used.

**Comment by AdriaanVisser** [comment]
Thanks for clearing this up! I've benchmarked already, so I no longer have the issue, but fixing it for the next benchmark would be great indeed. Keep up the good work!

**Comment by UselessGuru** [comment]
@AdriaanVisser 

Could you please post your logs. TIA

**Comment by UselessGuru** [comment]
Thank you for the logs.
Unfortunately I cannot see why Excavator (all 4 variants) and prospector (CryptoNight & Ethash2gb) failed. One reason could be overclocking.
All these algorithm should be working all right on AMD. 
You can try to benchmark again (remove the stats file for these miner/algos. look for errors on in the miner windows.
Note: I cannot simulate this because I don't own AMD hardware.

**Comment by richardg867** [comment]
It should be noted that Excavator no longer supports AMD, despite Excavator1 and Excavator2 being listed as AMD,NVIDIA. The old 1.2.11 version still works though, and richardg867@d4695f8 (separate the AMD,NVIDIA instances of excavator from the NVIDIA ones) is a potential solution for this issue.

**Comment by aaronsace** [comment]
Excavator dropped AMD support on the latest releases due to stability and there is no ETA for it being added back. 

Under no circumstance does Excavator get downloaded regardless of what it may look like. Excavator was already on your computer. If you can't be bothered waiting for the benchmark to fail; exclude the miner or delete it from the miners folder.

**Comment by AdriaanVisser** [comment]
@UselessGuru I didn't overclock, and the error is usually something along the lines of "No compatible (CUDA) devices found". I'll leave it here for the time being, and when I update anything in my system and benchmark again I'll try to exclude the miners, thanks.

**Comment by UselessGuru** [comment]
> I downloaded it because the FAQ explicitly states that I should download it myself,

[I've updated the readme.](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/7b80f7b86da52a43a2822193f831afd1e34752be)

And I know now why MPM tried Excavator: You still have 2 files named 'Excavator1.ps1' / 'Excavator2.ps1' in your miners folder. These are no longer valid (they were OK when Excavator was still supporting AMD) - please delete them.

A general not on how to update:
Always delete all files in the 'Miners' and 'Pools' folders. This will avoid retired / invalid Pools or Miners to be used (Errors guaranteed :-))

**Comment by UselessGuru** [comment]
@aaronsace 

Could you clarify the strategy on Excavator?
Currently we have 4 files: Excavator1/2 (AND&NVIDIA) and ExcavatorNvidia1/2 (NVIDIA only)
I see 2 options:
a) Remove Excavator support for AMD entirely -> remove Excavator1/2 (AND&NVIDIA)
b) Keep AMD support -> Rename Excavator1/2 (AND&NVIDIA) to ExcavatorAmd1/2 and remove NVIDIA type

**Comment by aaronsace** [comment]
@UselessGuru There was no AMD only option. Either remove the AMD/NVidia combo or split.

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/790ca1619c89ad74cd6a791afd8fee8865876dad

Please remove Miners\Excavator1.ps1 and Miners\Excavator2.ps1.

**Comment by UselessGuru** [comment]
Do the [new miner files](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/790ca1619c89ad74cd6a791afd8fee8865876dad) work for you? If yes then please [update this thread](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1104)

**Comment by AdriaanVisser** [comment]
@UselessGuru  I moved away from the multipool miner, as for my single-card set-up it's more convenient (and in my experience) more profitable to mine just ETH always. I have no idea whether the AMD-only excavators work, sorry I can't be of any help.

**Comment by UselessGuru** [comment]
@AdriaanVisser 

Thank you. Happy mining.
