### ISSUE TITLE
Feature: Institute xmrig CPU Miner

### ISSUE THREAD

**Issue by jsaltzman** [MultiPoolMiner/MultiPoolMiner#1078]
I get about 33% higher Cryptonight hashes by using xmrig. Is it possible to integrate this into MPM?

**Comment by aaronsace** [comment]
It is...?

https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/XmrigCpu.txt
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/XmrigAmd.txt
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/XmrigNvidia.txt

**Comment by jsaltzman** [comment]
My CPU mining options are limited to CpuminerJayddee
