### ISSUE TITLE
Enhancement Request for Nicehash Internal Wallet when mining on Nicehash

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1080]
Would like to request an additional feature for when i mine on nicehash, to mine into a Nicehash Internal Wallet.  This would allow me to withdraw from nicehash into coinbase with no minimum nor additional fees.  But at the same time, when i'm not using nicehash to mine, to mine into my existing external wallet.

Nicehash currently requires a minimum of 0.1 btc for auto payout to external wallet... and sporadically for minimums of 0.01 btc.

I currently have 0.03 btc that i won't receive until i get 0.1btc or they decide to run an irregular payout.

Their internal wallet has 0.001 btc minimum (though there's a post somewhere that raised it to 0.002btc). 

https://www.nicehash.com/help/when-and-how-do-you-get-paid

thanks... would be a greatly appreciated feature added.

**Comment by UselessGuru** [comment]
> Would like to request an additional feature for when i mine on nicehash, to mine into a Nicehash Internal Wallet.

[This feature is already implemented - documentation will follow](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/d23dc7376eeba155cd01de13fea5e268b3ff6f7c). To use it you will have to download and install the [latest zip file](https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip).


Edit the section for NiceHash

    "NiceHash": {
      "BTC": "$Wallet",
      "Worker": "$WorkerName"
    },

 and change the line

      "BTC": "$Wallet",
Replace "$Wallet" with your NiceHash BTD address, e.g.

`"BTC": "1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb"`

**Comment by alucard20724** [comment]
what file is "the section" in?
