### ISSUE TITLE
Web Monitor is working!!!!Geat job guys....

### ISSUE THREAD

**Issue by nickvasel** [MultiPoolMiner/MultiPoolMiner#1082]
With having figured out the other issues I had. I only have one question.
I cant seem to get the monitoring to work, I have 2 machines running with different names. I have attached the start.bat file for both. Do I need the minerstatuskey ?
[Start-MiningPoolHub.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1649848/Start-MiningPoolHub.txt)

**Comment by nickvasel** [comment]
I was able to fix the warnings by creating the folder and copying the required files.
Another question, no matter how I add the "-minerstatusurl https://multipoolminer.io/monitor/miner.php"
to the start.bat. So I can monitor via web interface, keep getting error unrecognized command?

**Comment by UselessGuru** [comment]
Please post your start.bat.
Also make sure you are running the latest MultiPoolMiner.ps1. Line 55 (or close) must read `    [String]$MinerStatusUrl = "https://multipoolminer.io/monitor/miner.php",`
