### ISSUE TITLE
Another Question on Powersheel

### ISSUE THREAD

**Issue by xfactor8383** [MultiPoolMiner/MultiPoolMiner#1084]
Sorry to go back to this. Does both PS 6 RC and PS6 need to be installed? Every time i start Powershell it says acquiring PS6 and then it looks like it installs it. I tried removing PS6 rc, and the miners wouldn't start. 
Thanks

**Comment by UselessGuru** [comment]
> I tried removing PS6 rc, and the miners wouldn't start.

In your case try uninstalling both, restart and re-install the final version
You only need the final version 6.0.0 installed.
