### ISSUE TITLE
Getting a series of errors after updating Windows 10 to build 17074 (Insider Preview)

### ISSUE THREAD

**Issue by erikszewczyk** [MultiPoolMiner/MultiPoolMiner#1085]
I updated to the latest Insider Preview Slow build last night and I'm getting a series of errors where Compare-Object cannot bind, here is an example (it gives about 50 of these errors in quick succession before the screen clears and mining resumes):

```
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\crypto miners\MultiPoolMinerV2.7.1.4\MultiPoolMiner.ps1:179 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

```
I tried reinstalling PowerShell 6, any other suggestions?

**Comment by aaronsace** [comment]
You've not posted the log file. If it mentions 'opencl' anywhere then install the full graphics drivers.

**Comment by erikszewczyk** [comment]
You're right, it sure did have an OpenCL error.  I reinstalled the NVIDIA drivers and it's not erroring anymore.

Thanks for the quick response!
