### ISSUE TITLE
Prospector miner failed to run because of invalid/missing config file generated

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1086]
MPM window:
```
   Status: Running

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 00 Minutes Once     Bin\Prospector\prospector.exe -c _Ethash2gb_.toml
```

Prospector miner window:
```
21:28:57 - INFO   prospector 0.0.13-ALPHA starting
Could not load  cuda library dll/so
21:28:57 - ERROR  Could not load CUDA: Unknown error - Unknown error
21:28:57 - INFO   OpenCL Initialized
21:28:57 - WARN   Configuration file in default location does not exist. creating it.
21:28:57 - WARN   run prospector.exe --help gen-config to see extended options for generating configuration
21:28:57 - WARN   run prospector.exe --config <file> to specify different configuration
21:28:57 - WARN
21:28:57 - INFO   Generated configuration saved in config.toml
21:28:57 - INFO   Configuration successfuly loaded from config.toml
21:28:57 - INFO   Not launching CPU miner
21:28:57 - INFO   Miner starting on gpu 0-0 - gfx901
21:28:57 - INFO   Miner starting on gpu 0-1 - gfx901
21:28:57 - INFO   Miner starting on gpu 0-2 - gfx901
21:28:57 - INFO   Device 0-3 disabled
21:28:57 - INFO   Starting api server on localhost:42000/api/v0/
21:28:57 - ERROR  Signatum: network client disconnected, Trying to reconnect
```
The ERROR goes forever...

My start.bat:
`-username borzaka -workername vegaworker -region europe -currency btc,usd,ltc -type amd -poolname miningpoolhub -algorithm ethash2gb -interval 60 -donate 24 -watchdog -switchingprevention 2`

## Basic info
- I was testing this issue: #767
- Tested with AMD (3x Vega 64), only `ethash2gb` algorithm was added.
- 2018-01-18 master version
- full log: [2018-01-18_21-24-33.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1649655/2018-01-18_21-24-33.txt)
The Prospector benchmarking starts at the ~1305th line.

**Comment by UselessGuru** [comment]
[You did not define your wallet.](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#sample-usage)

**Comment by UselessGuru** [comment]
> Tested with AMD (3x Vega 64), only ethash2gb algorithm was added.

Did you expect another result? ethash2gb is the only algo in your start.bat

**Comment by borzaka** [comment]
I was just testing for you guys: #767

That's true, but what if I don't have a wallet address, or I don't need one to specify, because my username is enough. For example in Mining Pool Hub.

There should'nt be an error in that case. Right?

Quote from the README:
> -wallet Your Bitcoin payout address. Required when mining on Zpool, Hash Refinery and Nicehash.

I was mining to miningpoolhub.

**Comment by Caspar007** [comment]
I have the same issue, prospector won't start. 
If I run prospector manually, everything is fine.

I took a closer look at the config files. My manual file for testing reads:

`[general]
gpu-coin = "sigt"
cpu-coin = "xmr"
default-username = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 
default-password = "x"
[pools.eth]
url = "stratum+tcp://daggerhashimoto.eu.nicehash.com:3353/"

[pools.sia]
url = "stratum+tcp://sia.eu.nicehash.com:3360/"

[pools.sigt]
url = "stratum+tcp://skunk.eu.nicehash.com:3362/"

[pools.xmr]
url = "stratum+tcp://cryptonight.eu.nicehash.com:3355/"

[pools.zec]
url = "stratum+tcp://equihash.eu.nicehash.com:3357/"

[gpus.1-0]
enabled = true
[gpus.1-1]
enabled = true
[cpu]
enabled = false`

The generated config looks like:

`[general]
gpu-coin = "sigt"
[pools.sigt]
url = "stratum+tcp://skunk.mine.zpool.ca:8433/"
username = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
password = "digger,c=BTC"
[gpus.1-0]
enabled = true
[gpus.1-1]
enabled = true
[gpus.1-2]
enabled = true
[gpus.1-3]
enabled = true
[gpus.1-4]
enabled = true
[gpus.1-5]
enabled = true
[gpus.-1-0]
enabled = true
[gpus.-1-1]
enabled = true
[gpus.-1-2]
enabled = true
[gpus.-1-3]
enabled = true
[gpus.-1-4]
enabled = true
[gpus.-1-5]
enabled = true
[cpu]
enabled = false`

Here is the result of prospector.exe list-devices:

`C:\MPM\Bin\Prospector>Prospector list-devices
03:55:29 - INFO   prospector 0.0.13-ALPHA starting
Could not load  cuda library dll/so
03:55:29 - ERROR  Could not load CUDA: Unknown error - Unknown error
03:55:29 - INFO   OpenCL Initialized
03:55:29 - INFO   Platform 0 - Intel(R) OpenCL
03:55:29 - INFO   Device 0-0 - Intel(R) HD Graphics 4600
03:55:29 - INFO   Device 0-1 - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
03:55:29 - INFO   Platform 1 - AMD Accelerated Parallel Processing
03:55:29 - INFO   Device 1-0 - Ellesmere
03:55:29 - INFO   Device 1-1 - Ellesmere
03:55:29 - INFO   Device 1-2 - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

C:\MPM\Bin\Prospector>`

**Comment by UselessGuru** [comment]
There are several issues with the prospector miner file. 
- Incorrect TOML file names when no pool information for the prospector algorithm is present
- Mixed rigs: also uses AMD cards even if only NVIDIA is specified in start.bat (or vice versa)
- Incorrect parameters for Ethash2GB algorithms

I am currently working on ironing them out.

**Comment by UselessGuru** [comment]
Testusers wanted! 

Since I do not have AMD hardware I need some assistance.
Delete the existing miners\prospector.ps1 file and replace with the 3 files in the zip file:

[ProspectorMiners.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1656320/ProspectorMiners.zip)

Expected result:
- ProspectorNvidia.ps should only mine on all NVIDIA cards, cards with less than 3GB memory should not mine Ethash (Ethash2GB only), should NOT mine on AMD cards or CPU
- ProspectorAmd.ps1 should only mine on all AMD cards, cards with less than 3GB memory should not mine Ethash (Ethash2GB only), should NOT mine on NVIDIA cards or CPU
- ProspectorCpu.ps1 should only mine on the CPU(s), but not use any GPU (algos Cryptonight and sia, eth and sigt are not supported on CPU)

**Comment by Caspar007** [comment]
testing now, will post results after 24h run

**Comment by UselessGuru** [comment]
> testing now, will post results after 24h run

To make it short:
I hope you have a mixed rig with AMD and NVIDIA card installed. Then
- Move all miners files (except ExcavatorAmd1.ps1) somewhere.
- Run MPM
- It should begin mining on all AMD cards (check the miner screen), but it should NOT use any NVIDIA card. If this is true: Horray, step 1 done
- Next: Stop MPM
- Replace ExcavatorAmd1.ps1 with ExcavatorNvidia1.ps
- Start MPM
- It should begin mining on all NVIDIA cards (check the miner screen), but it should NOT use any AMD card. If this is true: Horray, step 2 done. Mission completed.

**Comment by Caspar007** [comment]
Hi Guru,

I did a quick test, please see below my findings.

The first thing I noticed is that the script was not able to connect to the miner API. After that little amendment to ..\API\prospector1.ps
```
using module ..\Include.psm1

class Prospector : Miner {
    [PSCustomObject]GetMinerData ([String[]]$Algorithm, [Bool]$Safe = $false) {
        $Server = "localhost"
--->	$Port = 42000 <---
```
the script worked.

The good news is, that the individual miner file prospectorAMD does work. 
Attached logs.

The bad new is that the miner file prospectorCPU is not working.

The ugly news is, that running two instances of prospector.exe is not working on my machine.
It's not your script, it seems to be a problem with the prospector.exe



[Prospector_configs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1665891/Prospector_configs.zip)
[ProspectorAMD_Test_Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1665892/ProspectorAMD_Test_Logs.zip)
[ProspectorCPU_Test_Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1665893/ProspectorCPU_Test_Logs.zip)

**Comment by UselessGuru** [comment]
@Caspar007 Thank you for your valuable feedback

> The ugly news is, that running two instances of prospector.exe is not working on my machine

The current version of Prospector has a fixed API port. So this is a problem right now. I have contacted the author.

> After that little amendment to ..\API\prospector1.ps

You should not need to do this.
`$Response = Invoke-WebRequest "http://$($Server):$($this.Port)/api/v0/hashrates" -UseBasicParsing -TimeoutSec $Timeout -ErrorAction Stop`

$this.port is 42000 already.

**Comment by UselessGuru** [comment]
Prospector is no longer supported by MPM
