### ISSUE TITLE
Update README about supported number of GPUs

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1087]
Quote from the [README](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md):
> Currently mining with upto 6 GPUs is fully supported. Where required advanced users can create additional or amend current miner files to support mining with more than 6 graphics cards.

@aaronsace said in #1045 that it's supports any number of cards.

**Comment by UselessGuru** [comment]
> said in #1045 that it's supports any number of cards.

MPM does, but not all the miners do. E.g. excavator only works with up to 10 cards. I am not sure about all other supported miners.
 -> Volunteers wanted who put together a list of all supported miners and their max. number of cards :-)

**Comment by papacheal** [comment]
This could be another parameter built into the miner config file, once the info is gathered by the masses. This also sounds like a feature that would sync well with the "algorithm-per-device" feature requested by someone else earlier that would allow select GPUs to be used for specific algorithms (or miners, even).

That way, in a 12-GPU rig, if the miner with the best benchmark could only mine on 6 cards, a second instance of it could be fired off with configuration flags that mapped directly to the unused GPUs. This would require MPM to keep a running table of mapping miner/algorithm instance -> GPU used. It also would require miners that supported identifying specific devices (e.g. "-d" switch)...which is another table that needs to be built. =/

**Comment by borzaka** [comment]
[Cast XMR](https://bitcointalk.org/index.php?topic=2256917.0;all) can't be used with NiceHash if more than 8 GPUs are used.
Can this be a general rule for every miner?

> nicehash support will automatically disabled if more then 8 GPUs are used. Otherwise search space could be exhausted to early and the GPUs search in overlapping nonce ranges.

**Comment by Nickduino** [comment]
> This could be another parameter built into the miner config file, once the info is gathered by the masses. This also sounds like a feature that would sync well with the "algorithm-per-device" feature requested by someone else earlier that would allow select GPUs to be used for specific algorithms (or miners, even).

Bench each card, open a (potentially different) miner for each card. Great. And that would allow profit splitting as well.

But I don't think all miners number the cards the same, so you'd have to build a correspondance table.
