### ISSUE TITLE
Update README about A Hash Pool support

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1088]
Currently in the [README](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#feature-summary):
> Supports benchmarking, multiple platforms (AMD, NVIDIA and CPU) and mining on MiningPoolHub, Zpool, Hash Refinery and Nicehash (Ahashpool support is coming soon)

It's already supported: [https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Pools/AHashPool.ps1](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Pools/AHashPool.ps1)

**Comment by UselessGuru** [comment]
[Updated](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/f11b7525d13191c4e8feeafa63593c5eb5d931c5). Thanks for the hint :-)
