### ISSUE TITLE
Missing wallet/address error

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1089]
My start.bat
`-username borzaka -workername vegaworker -region europe -currency btc,usd,ltc -type amd -poolname miningpoolhub -algorithm ethash2gb -interval 60 -donate 24 -watchdog -switchingprevention 2`

```
C:\Users\Attila\Downloads\MultiPoolMiner-master\ReportStatus.ps1 : Cannot bind argument to parameter 'Address' because it is an empty string.
At C:\Users\Attila\Downloads\MultiPoolMiner-master\MultiPoolMiner.ps1:580 char:64
+ ... Config.MinerStatusURL) {& .\ReportStatus.ps1 -Address $Wallet -Worker ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [ReportStatus.ps1], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,ReportStatus.ps1
```

**Comment by UselessGuru** [comment]
[You did not define your wallet](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#sample-usage).

**Comment by borzaka** [comment]
That's true, but what if I don't have a wallet address, or I don't need one to specify, because my username is enough. For example in Mining Pool Hub.

Quote from the README:
> -wallet Your Bitcoin payout address. Required when mining on Zpool, Hash Refinery and Nicehash.

I was mining to miningpoolhub.
