### ISSUE TITLE
Theoretical question: mining to NiceHash and A Hash Pool pools - how to do it?

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1090]
They booth require a BTC address, and if you use NiceHash's internal wallet address, that can't be used with A Hash Pool. There is only one `-wallet` option in MPM.

Related issues:
- #1036
- #1080

**Comment by UselessGuru** [comment]
[See here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1080)
