### ISSUE TITLE
Enhancement request - Useful window titles

### ISSUE THREAD

**Issue by cacipriani** [MultiPoolMiner/MultiPoolMiner#1091]
I am wondering if it is possible we could have useful window titles on processes that are started by MPM. For example, maybe with the algorithim and pool being mined? So instead of just seeing the path name to ccminer.exe as the window title for the process, the title might be "NIST5 on Nicehash"

**Comment by UselessGuru** [comment]
I think this would make sense.

**Comment by grantemsley** [comment]
I like the idea, but I don't believe it's possible with the way the miners are currently launched.
