### ISSUE TITLE
Most profitable pool/algo

### ISSUE THREAD

**Issue by gatistaabb** [MultiPoolMiner/MultiPoolMiner#1092]
Let me present the situation:

I have one machine mining for weeks and other recently configured to the same configs.

On the machine that I started mined for weeks, it kept mining on HashRefinery most of the time.
On the machine that i recently configured(4 days ago), it mined on NiceHash. In the 4rth day it changed.

They are on the same router, same network, same internet/ISP, same everything...

So... or the first machine is taking days to change to the most profitable or the second machine is getting the numbers wrong. Or something I havent figured out...

I'm using -interval 300 on both machines.

Can someone give me some insight?

**Comment by grantemsley** [comment]
They are weighted based on historical data that MPM accumulates.  It keeps the average profit for each algorithm/pool over the last week and uses that to smooth out large, probably erroneous, spikes.

Your older machine will have plenty of historical data to do that with, but the new one won't.

If you want them the same, you can copy the '''*_Profit.txt''' files from the Stats directory from one machine to the other.  But you are probably best off just leaving it be and letting MPM do it's job.

**Comment by gatistaabb** [comment]
I knew that... but I understand that some hours to change is OK. But days is strange...

That means if I'm mining algo X for some time and suddenly Y is more profitable I'll wait several days for the change?

Multi algo mining means change whenever is more profitable. Sure there must be some spike smoothing but I think it's taking too long to make the change.

**Comment by aaronsace** [comment]
Smoothing is the wrong word; the prices are the live figures. 

It also takes into account the price fluctuations to reduce switching but the price __is__ live.
