### ISSUE TITLE
MiningTool.exe - Error

### ISSUE THREAD

**Issue by Braintelligence** [MultiPoolMiner/MultiPoolMiner#1094]
Anyone have an idea where MiningTool.exe comes from? I can't seem to find it in my MultiPoolMiner folder. It creates an error as soon as my rig runs out of memory due to numerous ccminer errors that accumulate over time.

**Comment by UselessGuru** [comment]
> where MiningTool.exe comes from?

It does NOT com from MPM.

**Comment by Braintelligence** [comment]
Maybe it's part of one of the miners?

**Comment by Braintelligence** [comment]
It's just that on this rig nothing else happened than Windows install + driver install via Windows Update and nVidia-website (checked for correct SSL connection) + MPH install from GitHub (checked for correct SSL connection).

There's nothing else where this may have come from, if my memory serves me.

I've activated ressource monitor and will try to see if it comes up again while running.

**Comment by Braintelligence** [comment]
Oh man, I'm dumb. It's the ASUS Mining Tool that has crashed due to out of memory.
It's a free app that you can get on the B250 Mining Expert Mainboard support site that shows you if your GPUs are connected and working and that will restart the rig and the mining app if a GPU fails.

Sorry for the trouble.
