### ISSUE TITLE
Suggestion: Do away with 'all prurpose' and 'combined AMD&NVIDIA' miners

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1095]
The current implementation has some shortcomings with mixed rigs: 
e.g. [Prospector will always use all available AMD & NVIDIA cards event if only one GPU type (e.g. NVIDIA) is configured.](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1075)
Also it is not possible to enable CPU mining with the normal prospector.
Other miners are affected likewise.

Currently the following miner types exist:
- NVIDIA only
- AMD only
- CPU only
- AMD&NVIDIA
- AMD&CPU
- NVIDIA&CPU

This should be reduced to the first 3 types.

I propose creating separate miner instances for each CPU/AMD/NVIDIA type, e.g. breaking up prospector in an AMD only, a NVIDIA only and a CPU only miner.

I see the following benefits:
a) Better profitability. Example: For algo 'a' prospector is better on AMD, but ccminer is better on NVIDIA. Running two miners will increase profit.
b) We can limit GPU usage to only the card types configured

All the necessary code is already in MPM. So just the miner files need adjustment.

**Comment by grantemsley** [comment]
Is there any case where one miner on both types of cards is more profitable than two separate miners?

**Comment by UselessGuru** [comment]
> Is there any case where one miner on both types of cards is more profitable than two separate miners?

Rhetorical question :-) 
I can not think of such a situation.

**Comment by aaronsace** [comment]
@UselessGuru They are only together because there wasn't an option to do so. If you are able to split them then go for it.

**Comment by UselessGuru** [comment]
[Excavator split](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/790ca1619c89ad74cd6a791afd8fee8865876dad)

**Comment by aaronsace** [comment]
@UselessGuru How does that work...?

**Comment by UselessGuru** [comment]
> How does that work...?

I see you point now (I did not understand your rather brief comment 'there wasn't an option to do so' in the first place and the impact thereof.)
Basically ExcavatorNvidia and ExcavatorAmd both suffer from the same shortcoming. Both miners always take all available cards :-(
So apart from the naming there is not much change.
Unfortunately Excavator has removed the '--na' parameter to skip AMD cards altogether.

**Comment by UselessGuru** [comment]
@aaronsace 

Since I don't have AMD hardware and you seem to have a mixed rig:
- Does the latest Excavator still work (at least on the old algos) work on all cards? 
- What is the device list output by Excavator ({"id":1,"method":"device.list","params":[]})
I am trying to find a match between the Excavator dev list and [OpenCl.Device]::GetDeviceIDs. That way we could select AMD or NVIDIA cards only.

**Comment by aaronsace** [comment]
I believe NiceHash said that the device order is the same as the OpenCL output. 

Platform 0 Device 0 is Excavator device 0
Platform 0 Device 1 is Excavator device 1
Platform 1 Device 0 is Excavator device 2
Platform 1 Device 1 is Excavator device 3

**Comment by aaronsace** [comment]
AMD was dropped for now though so I'm not sure it's worth the hassle. Probably best to just delete.

**Comment by aaronsace** [comment]
Not on the NVidia ps1 file as I disabled OpenCL.

**Comment by aaronsace** [comment]
When I say 'platform', I am referring to the numbers allocated by OpenCL (they have no meaning in themselves).

**Comment by UselessGuru** [comment]
> Not on the NVidia ps1 file as I disabled OpenCL.

According documentation '-na' does no longer exist. Does it still work?

**Comment by aaronsace** [comment]
Maybe because they removed OpenCL support so there is no need for the switch to disable it. Does that switch throw any errors? If not then just leave it in.

**Comment by UselessGuru** [comment]
Once we have 'pure' miners only we could take this a step further:
Split the Miners directory into 3
- MinersCPU
- MinersAmd
- MinersNvidia

The get AllMiner routine could then be changed to read only the miners in the directories which are listed in 'Type'. This will increase speed.
Miner files could be downloaded automatically based on selected 'Type'. The default MPM package would no longer contain and miner files.

**Comment by UselessGuru** [comment]
Device enumeration info by dropky (Excavator):

> If you would have a mixed rig, first NVIDIA devices would be listed and then AMD. Anyway, since we removed the support for AMD you should only see NVIDIA gpus.
