### ISSUE TITLE
-excludepoolname not working

### ISSUE THREAD

**Issue by jasdjensen** [MultiPoolMiner/MultiPoolMiner#1096]
I'm still getting reports from excluded pools (I exclude them all and only use miningpoolhub).  Or is my thinking incorrect.  I'm thinking it shouldn't bother doing anything with other pools, much less reporting issues.

I'm using "-poolname miningpoolhub -ExcludePoolName AHashPool,Blockmunch,Hashrefinery,ItalYiiMP,MiningPoolHubCoins,NiceHash,Zpool"

and still getting:
WARNING: Pool API (ItalYiiMP) returned nothing.

**Comment by UselessGuru** [comment]
>I'm using "-poolname miningpoolhub -ExcludePoolName AHashPool,Blockmunch,Hashrefinery,ItalYiiMP,MiningPoolHubCoins,NiceHash,Zpool"
> WARNING: Pool API (ItalYiiMP) returned nothing.

MPM will still attempt to retrieve data from all pools.
But the retrieved information will not be used for profit comparison.
