### ISSUE TITLE
Claymore Miner disappears

### ISSUE THREAD

**Issue by jweber018** [MultiPoolMiner/MultiPoolMiner#1097]
Progressively, every "instance" of Claymore miner stops being called by MPM. I tried deleting stat files for the miner and it benchmarks it perfectly, but it never calls it again and it disappears from the list. This is happening as of latest commit.

Let me know and I will attach logs.

Thanks in advance, guys. You are doing an unbelievable job with this tool.

**Comment by UselessGuru** [comment]
You need the latest Claymore miner files:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/db4be2d261c39d6cb444b58e919f212323871d58

Delete the stats files again. It will benchmark and then the miner will remain available.

**Comment by jweber018** [comment]
Thank you mate, that worked perfectly. Let me ask about one more thing: I am currently not able to get MPM to mine DCR, I'm using MPH, Zpool, AHashPool and YiiMP, but Decred does not appear in the list (I obviously have the miner files and Decred in my list of selected algos). Do you have any clue why?

**Comment by UselessGuru** [comment]
> I'm using MPH, Zpool, AHashPool and YiiMP,

Decred is not profitable, but if you really need it here are some answers:

There are currently only 2 pools in your list providind decred mining
Nicehash and YiiMP

YiiMP requires extra configuration (latest build + wallet addresses for each coin in the YiiMP section in config.txt) -> If you did not configure this, then YiiMP will not be operational and there is no point in keeping YiiMP (delete miner file for best performance)

Nicehash has a special decred variant called DecredNicehash. Do you see this?
