### ISSUE TITLE
Enhancement "Total Value of Coins"

### ISSUE THREAD

**Issue by rcloutier78** [MultiPoolMiner/MultiPoolMiner#1100]
It would be really nice to have a "Total Value of Coins" in my MPH account (e.g. total value in my wallets) based on the currency identified in my startup batch file... this would allow me to not have to spend so much time updating prices of each coin so I know how much I am holding in MPH. Thank you so much for your consideration of this. Rob

**Comment by Muaadib** [comment]
Personally, i use Miningpoolhubstats.com. it's based on a fork from multipoolminer that can even report hashrates live.

https://github.com/miningpoolhubstats/MultiPoolMiner

**Comment by rcloutier78** [comment]
Thanks. So do I. But, it does not calculate the total value of my coins -
only the daily total - or am I missing something?

*Rob*
Robert Cloutier, Ph.D.
robert.cloutier@calimar.com
Cell: 251-259-7826


https://www.crcpress.com/Systems-Engineering-Simplified/Cloutier-Baldwin-Bone/9781498706681

**Comment by Muaadib** [comment]
The Stats/Minimal view pages on the site calculate the total of each coin with its current price

**Comment by grantemsley** [comment]
I have this built into the GUI I am working on.  It gets the balances from all pools, including converting the altcoins to your chosen currency. 

Not done yet but it'll come eventually.

**Comment by aaronsace** [comment]
I have had total balance for all pools in BTC long before MultiPoolMiner but it's on my personal PHP page but was originally wrote in PowerShell... may add it to MultiPoolMiner...
