### ISSUE TITLE
Nanopool Support

### ISSUE THREAD

**Issue by korishan** [MultiPoolMiner/MultiPoolMiner#1101]
First off, great program. I'm using it with minimal setup. Working great. Only problem is I needed to set up an account with MPH.
I was wondering if you'd be supporting NanoPool any time soon. I like they way their web site is setup to follow what your miners are doing. MPH is kinda hard to work with and a bit clunky, imho.
Thanks for your work,
Korishan

**Comment by papacheal** [comment]
I'm guessing it's possible, but it would likely involve some creative math using the "approximated_earnings" API calls to all of the sub-pools with baseline hashrates to gather standardized data similar to the predication stats used by other pools (Estimated BTC/GH/Day)

e.g.

https://api.nanopool.org/v1/eth/approximated_earnings/:hashrate

You just need someone with time to build up the PowerShell script to gather this info in an MPM consumable format.

**Comment by korishan** [comment]
ie, wwwaaaaaay over my head  :P

I was hoping it'd be something a bit more simple that I could trudge through and figure out. But, I suppose thats one of those areas that's outta my reach, currently.

**Comment by papacheal** [comment]
It's actually not too hard, but one of the challenges currently is that Nanopool (along with other coin-specific pools) isn't auto-exchange, so you need to specify a wallet specific to that pool/coin. The good news is that the next release of MPM will likely support custom wallets per pool. At that point, you will likely see a bunch of new pools supported, perhaps Nanopool.

**Comment by korishan** [comment]
Nice, thanks  :) 👍

**Comment by UselessGuru** [comment]
> that the next release of MPM will likely support custom wallets per pool

Aaronsace (the real MPM guru) has already implemented it in the code published here. It requires editing config.txt. See my comment on https://github.com/MultiPoolMiner/MultiPoolMiner/commit/7a7715f7972d36f9d566bb56959093def5be814f

**Comment by korishan** [comment]
Thanks UselessGuru. But, unfortunately, I don't know what you mean in your post about adding 

> 
    "YiiMP": {
      "GRS": "_put_your_GRS_wallet_here",
I understand that GRL and wallet is the respective of the coins. I don't know where you mean to put that as I don't see an example anywhere, and I'm lost looking at the Pools/YiiMP.ps1 file.
The api call doesn't work, either, for getting status or whatnot.  :(

**Comment by papacheal** [comment]
If you get the latest code release via master, you'll notice that some variables have been moved out to a "config.txt" file. In that file, you customize some variables. In addition, the pool scripts themselves (i.e. Pools/YiiMP.ps1) have been updated to permit custom wallet config, as per @UselessGuru comment. None of this is fully documented yet, but if you dig through the commits you will find mention of them and how they can be used.

**Comment by korishan** [comment]
Ahh, gotcha. I was downloading from the releases folder, which is mid-December. Got the copy of the repo and doing the config now.

**Comment by toony63** [comment]
It is difficult to add Nanopool to MPM because it would be necessary to make at least 1 share every 2 days in order not to lose the blasting done since after 48 hours Nanopool removes the account
I tried to modify the YiiMP file to run Nanopool but I'm not strong enough to run this pool
But good if aaronsace work on the project I would be the first to use it: p

**Comment by UselessGuru** [comment]
@ korishan

> Thanks UselessGuru. But, unfortunately, I don't know what you mean in your post about adding

See the [updated documentation](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/e2a0b2b754b5605286410292a57458fcb28b581e/README.md) in this PR:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435
