### ISSUE TITLE
HSRNeo working API

### ISSUE THREAD

**Issue by nemosminer** [MultiPoolMiner/MultiPoolMiner#1103]
HSRNeo
with no dev fee
working API

https://github.com/justaminer/hsrm-fork

**Comment by borzaka** [comment]
Be careful with that fork. The [original hsrminer](https://bitcointalk.org/index.php?topic=2565979) is a closed source. The author of this fork [says](https://bitcointalk.org/index.php?topic=2765610.0), that he was able to reverse engineering the source from the binaries/modify the binaries to add new features, remove dev fee, etc.

**Comment by Nicheuji** [comment]
I'm willing to try this out. How do I go about adding this to MPM?

**Comment by Braintelligence** [comment]
@borzaka From what I heard it's also running a virtualisation engine so as to mask how the underlying new mechanisms work.

**Comment by UselessGuru** [comment]
>  I'm willing to try this out. How do I go about adding this to MPM?

[Copy this](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1664200/HSRMinerHack.txt) to the miners folder (I cannot test it because the hacked miner does not work for me - it exits after 10secs.)

I don't think we should support this hack officially.

**Comment by Braintelligence** [comment]
@UselessGuru I'm with you on not supporting it, but then again it's a long time ago that we heard something new from Palgin if I'm not mistaken.

**Comment by borzaka** [comment]
From the [official forum](https://bitcointalk.org/index.php?topic=2565979.msg28610102#msg28610102):

> I recently spoke with Palgin, he has small family problems, he promised to be later, so we look forward to his return

I'am with you @UselessGuru to not support this unofficial version of hsrminer neoscrypt miner.
