### ISSUE TITLE
Documentation updates for YiiMP

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1105]
@fonyo 

A few things regarding YiiMP documentation should be changed:

https://multipoolminer.io/algorithms:

YiiMP is not an auto exchange pool. Do NOT mine to BTC addresses. The readme needs to be changed.
A separate wallet address per coin needs to be configured. Exact how to instruction on editing config.txt is needed.

The correct URL is http://yiimp.eu/ (not http://www.yiimp.eu/)

**Comment by grantemsley** [comment]
How exactly *do* you set the wallet for each coin in that pool?  I've read the code, but still not getting it.

I'm working on updating my setup GUI for the new config.txt method, so I'll need to figure that out.

**Comment by UselessGuru** [comment]
@grantemsley 

To my understanding like I commented here: https://github.com/MultiPoolMiner/MultiPoolMiner/commit/7a7715f7972d36f9d566bb56959093def5be814f

config.txt needs this:
```
  "Pools": {
    "Yiimp": {
      "GRS": "FhCwkk9w8cFsJqzq9Q7qxNYK4eY9abpdm7",
      "Worker": "$WorkerName",
      "abc": "_wallet_for_abc",
...
```
This structure is passed down to the pool in line 230:
`            Get-ChildItemContent "Pools\$($_.Name)" -Parameters $Pool_Parameters`

You will now have the following variables available in Yiimp.ps1:
```
$GRS = "FhCwkk9w8cFsJqzq9Q7qxNYK4eY9abpdm7"
$Worker = "$WorkerName"
$abc ="_wallet_for_abc"
```
Look at lines 35, 61 & 62 in YiiMP.ps1:
```
35:    $YiiMP_Currency = $_
$YiiMP_Currency will become "GRS"

61:            User          = Get-Variable $YiiMP_Currency -ValueOnly
62:            Pass          = "$Worker,c=$YiiMP_Currency"
```

`Get-Variable $YiiMP_Currency -ValueOnly` will now retrieve 'FhCwkk9w8cFsJqzq9Q7qxNYK4eY9abpdm7'

Aaron amazes me again and again. Very smart coding!

**Comment by grantemsley** [comment]
Ah, that makes sense!  I was expecting another level to the array like 

'''
"Yiimp": {
  "Wallets": {
    "BTC": "blah",
    "BCH": "asdf"
  }
}
'''

But having them all at the same level works just as well (as long as nobody makes a coin called Worker).

If you don't have a particular currency listed, does it skip over that one?  Or does it throw errors or mine to an invalid address?

**Comment by UselessGuru** [comment]
> If you don't have a wallet for a particular currency setup, does it skip over that one? Or does it throw errors or mine to an invalid address?

No error, all fine.
There will be no pool if there is no wallet for it. (But I have not found the code where this filtering takes place)

**Comment by fonyo** [comment]
Website updated, documentation will be updated near or after release date.

Have we got a date yet for the new release? @aaronsace

**Comment by bbgobie** [comment]
Thanks for this, I was about to raise an issue about it.

**Comment by mserpell** [comment]
I'm trying to mine BTX on YiiMP by modifying config.txt (to the below) but I'm not having much luck.

    "YiiMP": {
      "BTX": "1ExsyDdmFFtnWKEnqN7WwHqmbv3bxhJRaV",
      "Worker": "$WorkerName"
    },

**Comment by UselessGuru** [comment]
> but I'm not having much luck

Erros? Logfiles? Screenshots? (My crystal ball is currently in maintenance :-))

**Comment by aaronsace** [comment]
@mserpell You've not provided any logs or information so here is how to mine only Bitcore and only on YiiMP. 

**Config:**
```
{
  "Pools": {
    "YiiMP": {
      "BTX": "1ExsyDdmFFtnWKEnqN7WwHqmbv3bxhJRaV",
      "Worker": "$WorkerName"
    }
  },
  "Miners": {
  },
  "Interval": "$Interval",
  "Region": "$Region",
  "SSL": "$SSL",
  "Type": "$Type",
  "Algorithm": "Bitcore",
  "MinerName": "$MinerName",
  "PoolName": "YiiMP",
  "ExcludeAlgorithm": "$ExcludeAlgorithm",
  "ExcludeMinerName": "$ExcludeMinerName",
  "ExcludePoolName": "$ExcludePoolName",
  "Currency": "$Currency",
  "Donate": "$Donate",
  "Proxy": "$Proxy",
  "Delay": "$Delay",
  "Watchdog": false,
  "MinerStatusURL": "$MinerStatusURL",
  "MinerStatusKey": "$MinerStatusKey",
  "SwitchingPrevention": "$SwitchingPrevention"
}
```

**Bat file:**
```
cd /d %~dp0
pwsh -noexit -executionpolicy bypass -command "& .\multipoolminer.ps1"
pause
```

**Comment by mserpell** [comment]
That works a treat, thanks.  (it's a good baseline from which to learn how to use Multipoolminer more broadly).

**Comment by embezon** [comment]
Hi, first off all : THX for the great work!

When in config.txt I fill in 
"Type": "nvidia,cpu" I get these error : "No miners available".
Or in
Currency "eur,btc" I get no values for profits.
When i fill in "nvidia" and "eur" everything works ok ....

Can I fill-in more than one option in config.txt, or just one?
If yes, what is the separation-mark?

Thx!

**Comment by UselessGuru** [comment]
@embezon 
Arrays (e.g. Currency & Type) need to be defined like this:
    "Currency":  [
                     "EUR",
                     "BTC",
                     "USD"
                 ],
    "WorkerName":  "BLACKBOX",
    "Region":  "Europe",
    "Type":  [
                 "NVIDIA",
                 "CPU"
             ],

**Comment by embezon** [comment]
It works, thanx again!
