### ISSUE TITLE
CCMiner port conflict

### ISSUE THREAD

**Issue by bbgobie** [MultiPoolMiner/MultiPoolMiner#1107]
Last night I decided to try mining with a very limited algo and miner config.
Since my miners were nearly all ccminer variants I noticed that when MPM switches algorithm, it launches the next CCMiner window slightly before closing the old one.  This seems to cause CCMiner not to be able to run the api on the default port.
It than increments the port to the next number.

It seems MPM is than unable to pick up the stats from CCMiner and eventually fails it since it can't connect, even though the miner is working.

My combination was CCMiner Klaust, Trupvot and HSR (Which by the way is the fastest x17 miner by far!)

**Comment by bbgobie** [comment]
Actually, I can duplicate this with ccminer HSR with 2 algorithms.  If it switches to itself, the new instance runs on port 4069 since 4068 is unavailable.

**Comment by grantemsley** [comment]
You can fix this by specifying "-delay 10" in the switches in start.bat

That makes it wait 10 seconds between closing old miners and starting new ones.

Not all systems requires the delay, which is why it's optional.

**Comment by bbgobie** [comment]
Thanks!
Gotta read the manual next time!
