### ISSUE TITLE
Different Startup file

### ISSUE THREAD

**Issue by korishan** [MultiPoolMiner/MultiPoolMiner#1108]
Not sure where I'm supposed to put this at, but I have a suggestion for the .bat files.

I've altered mine so they are a bit easier to read:

> set "wallet=3JQbSU8asbq4gwhgQAbW7yrEivvxoFY44m"
> set "algorithm=cryptonight,ethash2gb,equihash,groestl,lyra2re2,neoscrypt,siaclaymore"
> set "username=korishan"
> set "workername=multipoolminer"
> set "poolname=nicehash"
> 
> set "command=& .\multipoolminer.ps1 -wallet %wallet% -username %username% -workername %workername% -region us -currency usd -type amd,cpu -poolname %poolname% -algorithm %algorithm% -donate 24 -watchdog -switchingprevention 2"

Kinda makes it a lot easier to work with and make changes if need be.  Just a thought  :)

Kori

**Comment by fonyo** [comment]
We have a new config file system coming in the next release.
