### ISSUE TITLE
MPM not closing hung miners

### ISSUE THREAD

**Issue by korishan** [MultiPoolMiner/MultiPoolMiner#1110]
I have had on several occasions where a miner will hang and "Press any key" is all that it takes to close the miner. Sometimes the text is visible, sometimes not. But once I press a key, the miner closes, and MPM will continue on it's merry way and either relaunch the miner, or move on to another one.
Not sure if I've missed a setting somewhere, if this is a bug, or if this is something specific to my rig. 

Things I should check....????

thnx,
Kori

**Comment by cowboyjunkie** [comment]
If it is happening on xmr-stak try adding the command below to see if it helps.
If you are using windows add this to your startup script under the set x commands.

setx XMRSTAK_NOWAIT=1

cd /d %~dp0
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
setx XMRSTAK_NOWAIT=1

set "command=& .\multipoolminer.ps1

**Comment by korishan** [comment]
thnx, ill give i a try when i get home

**Comment by UselessGuru** [comment]
This may also happen with Excavator.

**Comment by UselessGuru** [comment]
Duplicate
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1034
