### ISSUE TITLE
Expression error in the log files from latest git master

### ISSUE THREAD

**Issue by cowboyjunkie** [MultiPoolMiner/MultiPoolMiner#1111]
I was looking at my logs and saw a lot of expression errors after pulling down the latest git master.  I usually overwrite the folders with the new one.  I saw the errors and setup a new clean install, and had the same errors.  It looks like it is happening when the multipool miner.ps1 is loading the miners.  It looks like an expression was not closed somewhere, but I could not find it.

Also you guys are doing an AWESOME JOB with this keep up the good work.  I really like all the new features.  Thanks...

I have attached the log files
[2018-01-24_20-01-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1664441/2018-01-24_20-01-24.txt)
[MultiPoolMiner-2018-01-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1664445/MultiPoolMiner-2018-01-24.txt)

**Comment by UselessGuru** [comment]
These errors are caused by Aarons change in Get-ChildItemContent beginning in line 202. The 'try' is causing it:

    function Invoke-ExpressionRecursive ($Expression) {
        if ($Expression -is [String]) {
            if ((Invoke-Expression "`"$Expression`"") -ne $Expression) {
                try {$Expression = Invoke-Expression $Expression}
                catch {$Expression = Invoke-Expression "`"$Expression`""}
            }
        }

I have not found a way to suppress these errors yet. It's ugly and confusing to read in the log, but the code is working fine.

**Comment by aaronsace** [comment]
The try/catch is for backward compatibility as it supports none string outputs now. 

There is no way to suppress terminating errors that I know of. 

Quotes need adding in the JSON files going forward.

**Comment by grantemsley** [comment]
Does adding ```-ErrorAction SilentlyContinue``` to all the invoke-expression commands suppress them?

Not at my computer to test it right now.

**Comment by UselessGuru** [comment]
> Does adding -ErrorAction SilentlyContinue to all the invoke-expression commands suppress them?

Nope, it does not :-(
