### ISSUE TITLE
hsrminer_neoscrypt.exe not working

### ISSUE THREAD

**Issue by rinkal26783** [MultiPoolMiner/MultiPoolMiner#1112]
launch failure. It open the exe in powershell and shut it down in 1 second. It keep trying to run the exe but its not working.
 
Status: Running

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 00 Minutes Once     Bin\NeoScrypt-Palgin\hsrminer_neoscrypt.exe -o
                                            stratum+tcp://neoscrypt.mine.zpool.ca:4233 -u
                                            34qbpoXtRcTvom65Jys3VZD95P3MXerbdj -p multipoolminer,c=BTC

**Comment by UselessGuru** [comment]
What happens when you run the same command manually?

**Comment by rinkal26783** [comment]
problem is with hsr algorithm. It keeps benchmarking forever. powershell keep shutting down. 

Pinging monitoring server...
Success


   Type: NVIDIA

Miner            Algorithm        Speed      BTC/Day Accuracy BTC/GH/Day Pool
-----            ---------        -----      ------- -------- ---------- ----
PalginNvidia     HSR       Benchmarking Benchmarking       8%    0.03627 Zpool
CcminerTpruvot   Lbry         1.14 GH/s      0.00018       3%    0.00016 Zpool
ExcavatorNvidia1 Lbry         1.17 GH/s      0.00019       3%    0.00016 Zpool
ExcavatorNvidia2 Lbry         1.21 GH/s      0.00019       3%    0.00016 Zpool
CcminerTpruvot   Equihash     1.24 KH/s      0.00069      12%  552.96000 Zpool
CcminerTpruvot   NeoScrypt    2.01 MH/s      0.00082      13%    0.40678 Zpool
CcminerTpruvot   Nist5      120.95 MH/s      0.00082      12%    0.00681 Zpool
CcminerTpruvot   Groestl    153.13 MH/s      0.00085      11%    0.00552 Zpool
CcminerKlaust    Groestl    168.61 MH/s      0.00093      11%    0.00552 Zpool
ExcavatorNvidia1 Equihash     1.81 KH/s      0.00100      12%  552.96000 Zpool
CcminerHsr       HSR         25.11 MH/s      0.00091       8%    0.03627 Zpool
ExcavatorNvidia2 Equihash     1.84 KH/s      0.00102      12%  552.96000 Zpool
Ewbf             Equihash     1.86 KH/s      0.00103      12%  552.96000 Zpool
Dstm             Equihash     1.89 KH/s      0.00105      12%  552.96000 Zpool
CcminerTpruvot   Sib         43.38 MH/s      0.00092       5%    0.02132 Zpool
CcminerSib       Sib         48.56 MH/s      0.00104       5%    0.02132 Zpool
CcminerTpruvot   X17         39.39 MH/s      0.00140      12%    0.03555 Zpool
CcminerSkunk     Skunk      122.39 MH/s      0.00136      10%    0.01113 Zpool
CcminerNanashi   NeoScrypt    3.67 MH/s      0.00149      13%    0.40678 Zpool
CcminerKlaust    NeoScrypt    4.17 MH/s      0.00169      13%    0.40678 Zpool
ExcavatorNvidia1 NeoScrypt    4.58 MH/s      0.00186      13%    0.40678 Zpool
ExcavatorNvidia2 NeoScrypt    4.66 MH/s      0.00189      13%    0.40678 Zpool
CcminerTpruvot   Lyra2RE2   142.01 MH/s      0.00333       7%    0.02348 Zpool
ExcavatorNvidia1 Lyra2RE2   169.56 MH/s      0.00398       7%    0.02348 Zpool
ExcavatorNvidia2 Lyra2RE2   170.66 MH/s      0.00401       7%    0.02348 Zpool
CcminerTpruvot   Tribus     233.27 MH/s      0.00495       3%    0.02122 Zpool

**Comment by UselessGuru** [comment]
> problem is with hsr algorithm. It keeps benchmarking forever.

As written before this miner it not officially supported because of the very problem you describe. Until Palgin updates the miner to enable API MPM cannot reliably benchmark the miner. 

https://github.com/MultiPoolMiner/MultiPoolMiner/issues?utf8=%E2%9C%93&q=palgin
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1030
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/889
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1030
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/991
