### ISSUE TITLE
OT: Anyone have a FanSpeed-Script for Nvidia Inspector users?

### ISSUE THREAD

**Issue by Braintelligence** [MultiPoolMiner/MultiPoolMiner#1113]
Hey everyone,

maybe some of you guys also use Nvidia Inspector for OCing your GPUs like me.

My problem with it is that I can't save the fan settings with the startup profile, so I have to set fans manually after every crash/restart.

Does anyone have an idea how I could efficiently set all of my fan speeds to 100% on startup on all of the GPUs?

**Comment by Sniffle** [comment]
Not sure what OS your using, but have you considered setting up custom fan profiles in something like msi afterburner or the like and setting them to default.  And in said fan profiles the fans spin to 100% at an abnormally low value say 60c.  T hats what I've done using EVGA overclocking tool

**Comment by Braintelligence** [comment]
MSI Afterburner doesn't work with more than 8 GPUs (or was it 10?) also it eats up a lot more CPU power than Nvidia Inspector for me, which is more lightweight.

Does EVGA OC tool support 13 GPUs?

**Comment by Sniffle** [comment]
I seriously doubt it, technically mpm only supports up to 6 gpu's, but I'll see if I can come up with something as well.  Something has to control the fans, and should be able to be controlled.

**Comment by Sniffle** [comment]
Found this don't k ow if it'll help, but looks like there is or used to be a command when starting nvidia inspector that will set fanspeeds, and you just set nvidia inspector shortcut to run at Windows startup.

https://postimg.org/image/f3zjq9d0v/

**Comment by Braintelligence** [comment]
@Sniffle 
> technically mpm only supports up to 6 gpu's
That's just plain wrong. I'm running on 13 GPUs just fine, not with all miners but with all relevant ones.

I also found what you found but I don't think it will set the fan speed for all GPUs.

**Comment by Sniffle** [comment]
It's not wrong, it's been stated by the devs to only support 6, that's not saying you can't do more just that that's all they officially support.

On the other hand as far as the fan speeds go, the only real way to test would be to set the automatic startup for the fanspeeds to something like 80:100 so the min speed would be 80% and see which cards spun up to 80% on a reboot.  That should be a large enough value you should be able to verify per card if it controls all of them.  The noise alone from 13 cards at 80% should be pretty impressive

**Comment by Braintelligence** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/884#issuecomment-354598352

You were saying?

**Comment by Sniffle** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1087

I wasn't entirely wrong either... 
I was just trying to help... you don't have to be a jerk...  considering I'm the only person that actually piped up and even attempted.

**Comment by Braintelligence** [comment]
I'm sorry if I come off as a jerk but I am a bit fed up with people implying running more than 8 GPUs with MPM is subpar per se.

With Nvidia Inspector you can't set an interval. You can either set Auto or a static speed. I will try out if it works on all GPUs, even though I doubt it.

What I'm looking for here is a script I can run on startup setting all fans to 100. If possible completely separate from other OC tools.

**Comment by Sniffle** [comment]
I never meant to imply that more than 6 was sub par, just stating what I had read and that it was possible to do more.

That being said.  I saw scripts for Linux but not much for anything else.  My only curiosity is if there is a config tweak somewhere for evga precisionx or msi afterburner that isn't well known about that can raise the "total gpu" limit beyond what is technically supported.  I wouldn't want to use them either but if nothing else is available... I sadly don't have experience with more than 6, just don't have the funds yet.

**Comment by Braintelligence** [comment]
I am happy I found Nvidia Inspector because MSI Afterburner was really taxing on my 6 GPU systems that ran on a Skylake Celeron. Mining runs a lot smoother on them now.

So I'd rather not switch :/

**Comment by Sniffle** [comment]
Ok, I had a chance to look closer,
It looks like your going to need a batch file that on startup does

Nvidiainspector.exe -setFanSpeed:0,100 -setFanSpeed:1,100, Etc, until :12,100
If I'm reading this right, -setFanSpeed:x,y
Where X is the gpu index and y is the percent of speed and -1 is auto.  

You might even(once nvidia inspector is running) to just use the command -setFanSpeed:x,y

Trying to thing of ways you can maybe test without needing to reset.  Either way it's going to take a bit of experimenting to build the script to suit your needs.  If you can either manipulate via command line to test or close nvidia inspector and reload it with a batch file and some tests to change fan speeds on reload to experiment and build what you need.

**Comment by Braintelligence** [comment]
Thanks, I'll try it out. Didn't have the chance yet.

**Comment by Braintelligence** [comment]
Looks like it worked, great!
Now I just have to put this in the startup folder.

**Comment by Braintelligence** [comment]
Anyone who also uses nvidiaInspector can just create a .bat-file in the same folder like this:

```
nvidiaInspector.exe -setFanSpeed:0,100 -setFanSpeed:1,100 -setFanSpeed:2,100 -setFanSpeed:3,100 -setFanSpeed:4,100 -setFanSpeed:5,100 -setFanSpeed:6,100 -setFanSpeed:7,100 -setFanSpeed:8,100 -setFanSpeed:9,100 -setFanSpeed:10,100 -setFanSpeed:11,100 -setFanSpeed:12,100
```
It will work for up to 13 GPUs.

**Comment by tempdude** [comment]
@Braintelligence thank you for the post but why stop there? I undervolt with nvidia-smi script and set nvidiaInspector cclock and mclock and now thanks to you fan speeds. I've attached the two files I use. 
I had to rename them from bat to txt to include them here. Hopefully someone will find them useful.


[undervolt.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1866019/undervolt.txt)
[oc.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1866020/oc.txt)

**Comment by hogito** [comment]
@tempdude Do you run your scripts on a loop for any interval?  I have noticed that sometimes nvidiainspector loses it's setting for a single card on a multi-card rig.

Has anyone considered using nvidia-smi to OC settings?  I am trying to figure it out, but don't have it yet.

**Comment by tempdude** [comment]
@hogito I am planning to write a loop script but haven't yet. I have noticed the same issue though. As far as nvidia-smi, I use it to undervolt only. I'm running GTX 1060 cards and most of the options available in the smi program don't apply to my cards.

**Comment by KLivanos** [comment]
@hogito try that
:loop 
your script
timeout /t 1800
goto :loop

**Comment by Quad5Ny** [comment]
Save what is below as a ".xml" and import it into Task Scheduler.  After which edit it to your liking.

`<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>NVIDIA (GPU0) Power and Light Management.</Description>
    <URI>\GTX Management</URI>
  </RegistrationInfo>
  <Triggers>
    <BootTrigger>
      <ExecutionTimeLimit>PT10S</ExecutionTimeLimit>
      <Enabled>true</Enabled>
      <Delay>PT15S</Delay>
    </BootTrigger>
    <EventTrigger>
      <ExecutionTimeLimit>PT10S</ExecutionTimeLimit>
      <Enabled>true</Enabled>
      <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="System"&gt;&lt;Select Path="System"&gt;*[System[Provider[@Name='Display'] and EventID=4101]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
      <Delay>PT15S</Delay>
    </EventTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT30S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>"%ProgramFiles%\NVIDIA Inspector\nvidiaInspector.exe"</Command>
      <Arguments>-setFanSpeed:0,-1 -setPowerTarget:0,100 -setTempTarget:0,0,80 -setBaseClockOffset:0,0,000 -setMemoryClockOffset:0,0,000 -setIlumination:0,0,100 -setIlumination:0,1,100</Arguments>
    </Exec>
  </Actions>
</Task>`
