### ISSUE TITLE
Can I use MultiPoolMiner to prevent mining cryptocurrencies malwares?

### ISSUE THREAD

**Issue by a4khuffash** [MultiPoolMiner/MultiPoolMiner#1114]
Can I imagine this software as a whitelist solution which only allows its owner to do mining cryptocurrencies? Thanks in advance.

**Comment by Sniffle** [comment]
Not entirely sure what you are asking.  This only mines crypto that is available to be mined on the available pools.  It does not mine anything else.  If you are curious what is mined check out the respective available pools.

**Comment by FabianGabor** [comment]
MultiPoolMiner only fetches the data from the pools, calculates every algorithm's profitability on miner's benchmark data and launches the most profitable miner for the most profitable algorithm. It does nothing more (it has some other cool features, but let's just say this for simplicity). What actually happens depends on the miner software that it launches, by that I mean it depends what each miner's developer put into his code. Most miners available are open source from proven and trusted developers but there are some that are not open source, for example Claymore's Miner, but he as a developer is trusted by the community. So in theory nobody should get infected by malwares but that doesn't really depend on MPM (only by the factor that it uses 3rd party softwares) but on those 3rd party softwares.

**Comment by fonyo** [comment]
Most of the possible answers have been posted here but can you elaborate further or reword your question for us to have a clear understanding of what you mean by this?

**Comment by aaronsace** [comment]
@a4khuffash Yes, we seek out the safe miners for you and set your antivirus settings so you don't download malware.
