### ISSUE TITLE
Yiimp host url is incorrect

### ISSUE THREAD

**Issue by bbgobie** [MultiPoolMiner/MultiPoolMiner#1116]
From yiimp.eu the algorithm hosts don't have the algorithm in them.
So yiimp.ps1 line 59 should be:
            Host          = "$YiiMP_Host"

-o stratum+tcp://yiimp.eu:<PORT> -u <WALLET_ADDRESS> [-p <OPTIONS>]

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/be429b75e1ea2acd4fd1d611d8a87ef6f3ce7d97
