### ISSUE TITLE
Unexpected character '$' in OpenCL\Cl.cs

### ISSUE THREAD

**Issue by SSteveSS** [MultiPoolMiner/MultiPoolMiner#1118]
I've tried everything I can think of.   MPM runs for a while and then crashes with the following:

'& : c:\mph\OpenCL\Cl.cs(308) : Unexpected character 
'$'
c:\mph\OpenCL\Cl.cs(307) :    if (count*elemSize < (int)arraySize) {
c:\mph\OpenCL\Cl.cs(308) : >>>  throw new InvalidOperationException($"Array size is incompatible with managed element size: array size = {arraySize}, sizeof({typeof(T)}) = {elemSize})");
c:\mph\OpenCL\Cl.cs(309) :             }
At line:1 char:3
+ & .\multipoolminer.ps1 -wallet 1JxxxxxxxxxxxxxxxxNfGU -us ...
+   ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (C:\mph\Include.psm1:String) [], RuntimeException
+ FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand'

[Error.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1668530/Error.txt)
[Log.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1668567/Log.txt)

Sometimes it will go days without the error and other times it happens every 30 minutes.   Sorry about the formatting.  See attached txt file.

**Comment by aaronsace** [comment]
That code does not exist; you've downloaded some old development code. 

This is the release page: 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases

**Comment by SSteveSS** [comment]
I guess that might explain things.   Thank you for the quick response.
