### ISSUE TITLE
mkxminer doesn't benchmark

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1120]
doesn't benchmark.. .just keeps closing out.

Powershell window displays "multipoolminer wrapper started" shows up for a few seconds, and then closes out.

**Comment by aaronsace** [comment]
@alucard20724 Sounds like a problem with the miner. Have you tested to see if you get the same result outside MultiPoolMiner?

**Comment by alucard20724** [comment]
the problem isn't mkxminer... the miner works outside of mpm.  i would like it to work with mpm.

**Comment by aaronsace** [comment]
Please post the command line that you are using and the command line that MultiPoolMiner is using.

**Comment by r0dn0r** [comment]
For me mkxminer only works when appending the `--platform` command. I have both AMD and Nvidia running on the same rig.

**Comment by aaronsace** [comment]
@r0dn0r That's easy to add but are you sure; it says on the version log that it auto detects...?

> v2.0.1: 12 December 2017 - Added VTC pool, AMD platform autodetection.

**Comment by r0dn0r** [comment]
Hmm...now it seems to be working without `--platform`, but I'm sure that before it didn't work and only started working after I added `--platform 1` and I didn't change anything else.

**Comment by r0dn0r** [comment]
And now it again doesn't work....seems to be a miner issue.

**Comment by richardg867** [comment]
Mkxminer appears to be very intermittent (for me and for @aaronsace too if I'm not mistaken), just leave it be until the author gets down to these issues.

**Comment by Mooglee** [comment]
how do u tag something to not be benchmarked?

**Comment by UselessGuru** [comment]
> how do u tag something to not be benchmarked?

Create a benchmark file with 0 hashrate:

```
{
  "Live": 0,
  "Minute": 0,
  "Minute_Fluctuation": 1.0,
  "Minute_5": 0,
  "Minute_5_Fluctuation": 1.0,
  "Minute_10": 0,
  "Minute_10_Fluctuation": 1.0,
  "Hour": 0,
  "Hour_Fluctuation": 1.0,
  "Day": 0,
  "Day_Fluctuation": 1.0,
  "Week": 0,
  "Week_Fluctuation": 1.0,
  "Duration": "00:01:10.4448433",
  "Updated": "2018-01-24T22:33:44.2433105Z",
  "Enabled": "true"
}
```
