### ISSUE TITLE
YiiMP API reporting GH instead of MH for some currencies

### ISSUE THREAD

**Issue by r0dn0r** [MultiPoolMiner/MultiPoolMiner#1126]
YiiMP API reporting GH instead of MH for some currencies.
Saw it with bitcore, lbry, tribus, x17 and xevan.

**Comment by aaronsace** [comment]
It doesn't mention that on the website... 

So do these four algorithms need dividing by 1000? 

> bitcore, lbry, tribus, x17 and xevan

**Comment by r0dn0r** [comment]
I edited the pool file to this and now it seems to be ok ( MPM doesn't report earnings*1000).
switch ($YiiMP_Algorithm_Norm) {
        "equihash" {$Divisor /= 1000}
        "bitcore" {$Divisor *= 1000}
        "blake2s" {$Divisor *= 1000}
        "blakecoin" {$Divisor *= 1000}
        "decred" {$Divisor *= 1000}
        "lbry" {$Divisor *= 1000}
        "tribus" {$Divisor *= 1000}
        "x17" {$Divisor *= 1000}
        "xevan" {$Divisor *= 1000}
    }

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/4d4412d1ff5346cad55947315b0f5d6f7e05d00c
