### ISSUE TITLE
Be careful with Bminer Equihash miner

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1127]
Be careful with Bminer. There is a possibility that this is a scam miner;
- [Zcash forum where the author got banned](https://forum.z.cash/t/new-miner-bminer-a-fast-equihash-miner-for-cuda-gpus-5-1-0/26197)
- [bitcointalk forum where users reporting strange things with this miner](https://bitcointalk.org/index.php?topic=2519271.340)

It's already in MPM: [Add Bminer 5.0.0 für NVIDIA](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/f21fb9180de38f0f9ac5e3c432ca3ad1e36dfb3a)

**Comment by fonyo** [comment]
We should only include miners that are at least 2-3 months old.

**Comment by f3rs3n** [comment]
I've taken the risk and tried it, 48 hours no-stop running right now, no crash and sol/s much more stable and 5% higher than dstm (even with -nofee that disable some optimizations).  On the pool side, earning seem to be what it should.

**Comment by aloth** [comment]
To get this really fixed, it would help if MPM reads out the actual hashrate on the pool, instead of the hashrate reported by the mining software. Comparing these would be much more accurate!

**Comment by UselessGuru** [comment]
> instead of the hashrate reported by the mining software. Comparing these would be much more accurate!

The pool does not have any idea of the miners hash rate, it just sees the number of found shares. From there the pool tries to extrapolate a hash rate based on the current difficulty.
The hash rate as reported by the pool will become more stable over time, but it will take a few minutes until we find get a reliable value.

**Comment by borzaka** [comment]
It's still in MPM, consider remove it. There are many problems with this miner.

> Very impressive higher sols with Bminer but how come the number of shares would be less than EWBF and DSTM?

> Somtimes even crashes on "GPU hang" but running a EWBF miner works fine...

> Currently i'm having 6402 accepted and 24 rejected for 21 hour period, you can do the math to see percentage wise. But i dont see higher rejected shares than other miners software.

> One stability issue I had was that bminer appeared to be running normally, but hashrate at the pool dropped to zero like it was disconnected; this went on for about an hour before I noticed it.

[...]

Source: [official bitcointalk.org forum](https://bitcointalk.org/index.php?topic=2519271.0)

**Comment by lear001** [comment]
Just found some fair test result from bitcointalk, The test shows bminer is a clear winner  5%  on the plus.  
 
https://bitcointalk.org/index.php?topic=2519271.msg32329006#msg32329006
https://bitcointalk.org/index.php?topic=2519271.msg32336363#msg32336363
https://bitcointalk.org/index.php?topic=2519271.msg32355765#msg32355765
https://bitcointalk.org/index.php?topic=2519271.msg32366684#msg32366684
https://bitcointalk.org/index.php?topic=2519271.msg32393199#msg32393199
https://bitcointalk.org/index.php?topic=2519271.msg32408925#msg32408925
