### ISSUE TITLE
Revert changes to AHashPool?  Altcoin payouts are not supported.

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#1128]
Per their website:

> Announcement: (2018-01-26 08:32 UTC) There appears to be miners who are trying to connect to our stratums with invalid parameters in the password field such as "c=LTC" , "x" , "c=BTC-i" etc. Please check your miner settings. We only support "c=BTC". You will not be able to connect to our stratum if you do not set this correctly. 

I'm wondering if it's us with the new ```$AHashPool_Currencies | ...``` block is causing that, if people are adding other currencies in their config.txt, not realizing AHashPool doesn't support it.

That pool specifically only supports BTC payouts, so should probably be reverted to the old setup that only used BTC wallet addresses.

**Comment by aaronsace** [comment]
Remove this: 
` + ($AHashPoolCoins_Request | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name) | Select-Object -Unique | Where-Object {Get-Variable $_ -ValueOnly -ErrorAction SilentlyContinue}`

**Comment by UselessGuru** [comment]
Fixed as suggested by@aaronsace

https://github.com/MultiPoolMiner/MultiPoolMiner/commit/8d0a320efe4529a6b31fe69edc2dc278a7b0eb18

**Comment by grantemsley** [comment]
Might I suggest removing or just commenting out this line as well?

```$AHashPoolCoins_Request = Invoke-RestMethod "http://www.ahashpool.com/api/currencies" -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop```

With the currencies removed that doesn't get used now, so it's hitting their API a second time for no good reason.  Wastes time in the script and is putting a heavier load on their servers than we need to.

**Comment by UselessGuru** [comment]
> Might I suggest removing or just commenting out this line as well?

[Makes sense, done!](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/5395429ca945191c93de0b5b4fe2da3584e03c0b)
