### ISSUE TITLE
Start-MiningPoolHub.bat missing some supported algorithm

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1131]
Current algorithm list in Start-MiningPoolHub.bat:
`-algorithm cryptonight,ethash,ethash2gb,equihash,groestl,lyra2re2,lyra2z,neoscrypt,siaclaymore`

But there are [more](https://miningpoolhub.com/):
![image](https://user-images.githubusercontent.com/1230402/35488812-c5b916de-048e-11e8-9fb5-2d94720fdf62.png)

Consider adding some of them to the .bat:
- Keccak
- MyriadGroestl
- Skein

**Comment by Nicheuji** [comment]
You could simply add or remove algos yourself. Every time you download a new version of the miner you'll have to make edits to the .bat anyway, and because if that I don't see adding/removing algo as an extra inconvenience.

**Comment by korishan** [comment]
You could also create your own starting .bat file that does initial setting of the algo's. 
Then, just make a quick edit to the other .bat and replace the algo listing with %algos% and they'll automatically be inserted.
I've made these changes to mine:

> set "wallet=3JQbSU8asbq4gwhgQAbW7yrEivvxoFY44m"
> set "algorithm=cryptonight,ethash2gb,equihash,groestl,lyra2re2,neoscrypt,siaclaymore"
> set "username=korishan"
> set "workername=multipoolminer2"
> set "poolname=nicehash"
> 
> set "command=& .\multipoolminer.ps1 -wallet %wallet% -username %username% -workername %workername% -region us -currency usd -type amd,cpu -poolname %poolname% -algorithm %algorithm% -watchdog -switchingprevention 2"

Altho, aaron said they're changing the configuration options in the next release. So, this might be a mute point in a week or so.

Kori

**Comment by UselessGuru** [comment]
> Consider adding some of them to the .bat:

It is NOT advisable to mine ALL available algorithms, because:
- The more algos the more pool hopping -> you'll lose shares -> less profit
- Some algos are dodgy, the appear to give high payouts, but then you get much less

Feel free to add more algos to your personal start files. We recommend to just use the one we include by default.

**Comment by borzaka** [comment]
Skein algorithm was the most profitable to mine for me in the last ~24hours. It has been mined for 66% of the time. Digibyte-Skein was the coin.
