### ISSUE TITLE
Siacoin's difficulty skyrocketed because of ASICs

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1133]
GPU mining this algo is pointless.

[Overall Siacoin hashrate, difficulty chart](https://siastats.info/mining.html)

**Comment by wizmanza** [comment]
Thanks, my rig seems to still like the claymore dual mine with ETH and SC. If SC is now so diff why does MPM still chooses that? Any pointers?

**Comment by borzaka** [comment]
Maybe 0,001 BTC/day (Ethash) + 0,000000000000000000001 BTC/day (Sia) is more than just 0,001 BTC/day (Ethash) alone. It's 0,001000000000000000001 BTC/day :)

_Note: the numbers are fiction, I just watend to represent my point. I calculate everything in BTC/day._

**Comment by wizmanza** [comment]
also true i guess...makes sense....thanks

**Comment by AdriaanVisser** [comment]
Still mining at miningpoolhub, but they really should set up DCR and LBRY pools by now. They have always been more profitable than SIA anyway, and now that SIA mining is impossible, it'd be great if those were added. Does anyone know a way to contact MPH? I can't find an email address or something to tell them to add those pools.

**Comment by aaronsace** [comment]
Add another pool for higher profits.

**Comment by wizmanza** [comment]
another pool?

**Comment by AdriaanVisser** [comment]
The problem for a single-card miner like myself is that I actually use this PC as well, so if I earn ~€2/day it's a great day for me. If I create an account at another pool, I'm usually required to being paid out in ETH amounts so large I should mine for very long amounts of time, which is why I like MPH.

**Comment by fonyo** [comment]
All,

Unfortunately, it is what it is. Please remove siaclaymore from your list of algos in your start.bat file if you don't want to waste electricity. As @aaronsace said, lbry, decred and pascal are only available on other pools, so you would need to either split your earnings by mining on multiple pools or moving away from MPH with your AMD rigs completely. If you specify -poolname nicehash, you will be able to mine both ethash and the most profitable secondary coin in dual mode. Please see the algorithm list on the website for the correct parameters you need to specify to start mining on Nicehash using MPM and Claymore Dual.

**Comment by wizmanza** [comment]
I've redone my benchmarks and now claymore starts-up most of the times without the dual SC coin - yeah
