### ISSUE TITLE
Errors in latest master

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1134]
![image](https://user-images.githubusercontent.com/34346751/35512313-5788bc84-04cd-11e8-9cc9-1cf6302dc960.png)

I'm getting this that didn't exist in the older version I'm using.  I've tried comparing the code but unfortunately I'm not that good.

I went to this one figuring that maybe excludeminername would work and it still doesn't, just tells me that it is not a valid command.  Trying to get rid of the claymore miners as my gtx950 doesn't work with them.

Last I see the Yiimp pool was added but that pool clearly states on the site that they don't do autoexchange so how does that work?

**Comment by robl45** [comment]
also tried release version as well,  error is in different code line but both are in the allminers section.

**Comment by UselessGuru** [comment]
> I'm getting this that didn't exist in the older version

Please post logs and stat.bat.
Are you using CPU mining only?

> excludeminername would work

The error is in line 283. This is where MPM is reading the miner data. So the error is not related to any pool information.
Make absolutely sure you only have files in the 'Miners' directory that were delivered with MPM, do not keep any *.bak or similar files there.

> Last I see the Yiimp pool was added but that pool clearly states on the site that they don't do 
autoexchange so how does that work?

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1105

Note: Please do not mix different questions in  the same post. It becomes difficult to track :-)

**Comment by robl45** [comment]
okay, so problem was I copied the miners folder over as I made a couple of changes to intensity so my GTX950 will run with the gtx1060's.

It appears it was the ccminerpalgin file causing the issues.  So I can't use ccminer palgin anymore with this?  That produced way better hashrates for x17 and others.

**Comment by UselessGuru** [comment]
> So I can't use ccminer palgin anymore with this? 

Palgin has officially removed his binary. MPM does still work with it if you have access to the binary.
Note that this miner is not really faster - it just showed better rates on screen. Google and you'll find out :-)

The last MPM supported Ccminer Palgin files was here:

https://github.com/MultiPoolMiner/MultiPoolMiner/commit/a8827d408f1a98388d8bd410ea16d6dd53ca65aa

**Comment by robl45** [comment]
okay, seems to be working now.  I copied over the miners so I guess something in there was messing it up.  
One suggestion would be to have an easier way to upgrade this.  If I have to make changes to the miners and I can't copy them over, then every time I have to go and edit the miners files.

**Comment by UselessGuru** [comment]
> then every time I have to go and edit the miners files.

We cannot take into account every possible individual modification.
The files should work fine as they are distributed. What modifications did you make to the miner files that derive from standard?

**Comment by robl45** [comment]
at a minimum I have to drop the intensity on Xevan or it doesn't work with my GTX950.  Same thing with the palgin nvidia for X17 although that appears to be going away.

**Comment by aaronsace** [comment]
Use unmodified code and install the full graphics drivers from NVidia/AMD.
