### ISSUE TITLE
Euro profit per miner/algo zero?

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#1135]
Ive noticed that when i select only Euro as the currency for profit stats, the column e/Day on the tables miner/algo reads 0.000000000, altough at the bottom it shows the actual profit per day in Euro.
This happens on the table NVIDIA, CPU and {AMD, NVIDIA}.

If i select btc,eur, only btc / day is shown on the miner/algo tables. Is this "by design" or im doing something wrong? 

Ive attached my log so you guys can see what im talking about... Btw, this is happening on the last master.

[2018-01-29_18-53-43.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1674853/2018-01-29_18-53-43.txt)

**Comment by UselessGuru** [comment]
Until a proper fix is available y
As a temporary workaroun define a second currency, like "EUR,BTC".

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/1ea10792bb94d2769b9349273ebab42e16455bd8
