### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by wizmanza** [MultiPoolMiner/MultiPoolMiner#1138]
Hi, is there a way that the monitoring can send an e-mail when workers is reported as offline for a few minutes? Maybe it is in the enhancement list already?

Thanks,

**Comment by Braintelligence** [comment]
@wizmanza https://github.com/miningpoolhubstats/MultiPoolMiner/releases + https://miningpoolhubstats.com

**Comment by wizmanza** [comment]
hi, can this fork be trusted? same dev's?

**Comment by Braintelligence** [comment]
Not same dev, just check the commits he applied to the fork to see if you can trust it...

**Comment by grantemsley** [comment]
That works if you exclusively use miningpoolhub as your only pool.

Notifications about workers that are down is something I'm working on.

**Comment by wizmanza** [comment]
Thanks a mil

**Comment by Braintelligence** [comment]
@grantemsley I'm using the notification function already. Other than "remembering" worker names that I ceased to use for weeks it works very well.

**Comment by wizmanza** [comment]
@aaronsace  is there possibility that i can contact you privately to ask something please?
