### ISSUE TITLE
-excludeminername gives error

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1139]
When using -excludeminername, it just tells me that the switch doesn't exist.

**Comment by UselessGuru** [comment]
You must be using the latest [MultiPoolMiner.ps1](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/MultiPoolMiner.ps1) for this.

**Comment by UselessGuru** [comment]
@robl45 

Issue resolved? If yes then please close this. We should keep the open issue list short. Thank you!

**Comment by robl45** [comment]
I am using latest master.  I get red thing showing 
![image](https://user-images.githubusercontent.com/34346751/35622666-a62cc2ba-0656-11e8-90bd-980af0150075.png)
When I didn't have exludeminername in there it said the same thing about the statusurl yet that is working.

**Comment by aaronsace** [comment]
@robl45 Post the actual log.
