### ISSUE TITLE
stats at bottom do not seem to be updating

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1140]
![image](https://user-images.githubusercontent.com/34346751/35533197-c17ba3bc-050a-11e8-842b-deec0cd75f69.png)

Its been showing blake2s at the bottom for hours,  the amounts have changed a little bit but blake 2s is nowhere near the top miner now.  It used to switch between the miners previously.

**Comment by aaronsace** [comment]
@robl45 They are week averages not live figures. The live figures are in the tables above.
