### ISSUE TITLE
Question ccminer-x64-2.2.3

### ISSUE THREAD

**Issue by nickvasel** [MultiPoolMiner/MultiPoolMiner#1142]
Will the next MPM release have the latest ccminer version=2.2.4 ?

**Comment by UselessGuru** [comment]
It is already on version 2.2.4
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/CcminerTpruvot.ps1

**Comment by nickvasel** [comment]
thank you for the fast reply....
