### ISSUE TITLE
Not to be a pain...ccminer not at 2.2.4

### ISSUE THREAD

**Issue by nickvasel** [MultiPoolMiner/MultiPoolMiner#1144]
![capture](https://user-images.githubusercontent.com/35632631/35544172-f4cf1d1a-0560-11e8-9f06-640bfc887b17.GIF)
![capture1](https://user-images.githubusercontent.com/35632631/35544175-f7944a16-0560-11e8-9baa-ffdd8ba5dc3d.GIF)
I downloaded a new file and this is what came up? am I seeing this wrong? wrong

**Comment by adamje42** [comment]
MPM will not currently overwrite the miner. Delete the NVIDIA-Tpruvot folder in your \bin\ directory. Then make sure in your \Downloads\ directory the .zip archive is also deleted. Assuming you have the latest CcminerTpruvot.ps1 file, when you launch MPM again it should download the latest version.

**Comment by nickvasel** [comment]
nope, didn't work. now it downloads this....
![capture2](https://user-images.githubusercontent.com/35632631/35544672-904213f4-0563-11e8-9317-0762ff47d91e.GIF)

**Comment by adamje42** [comment]
If that's what happened then you didn't replace this file:

[Miners/CcminerTpruvot.ps1](https://raw.githubusercontent.com/MultiPoolMiner/MultiPoolMiner/master/Miners/CcminerTpruvot.ps1)

**Comment by nickvasel** [comment]
I thought you meant the latest Miners/CcminerTpruvot.ps1 file from the main download site. re deleted files used your CcminerTpruvot.ps1 file and now it downloads the 2.2.4 ver....
