### ISSUE TITLE
ccminer.exe cannot proceed because MSVCR120.dll was not found

### ISSUE THREAD

**Issue by mattsawka** [MultiPoolMiner/MultiPoolMiner#1145]
I am currently running the benchmark and this error keeps popping up. I reinstalled the MSVCR120.dll but that is not working.

**Comment by adamje42** [comment]
I hope you didn't download that from some random .dll website. From the readme:

> CCMiner (NVIDIA cards only) may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784

**Comment by mattsawka** [comment]
I downloaded it from the microsoft website do not worry

**Comment by Crypto00** [comment]
I had this issue and installed the x86 versions, not the x64 ones, to get it working.

**Comment by mattsawka** [comment]
That worked! Thank you so much!

**Comment by UselessGuru** [comment]
Readme updated. On a x64 system always x86 versions too.
