### ISSUE TITLE
Add phoenix miner?

### ISSUE THREAD

**Issue by migdiluca** [MultiPoolMiner/MultiPoolMiner#1146]
I've seen this miner and i'm getting slightly better hashrate than Claymore and the fee is just 0.65% 
[https://bitcointalk.org/index.php?topic=2647654.0](url). Maybe you would want to add it!

**Comment by Sniffle** [comment]
Check the pull requests, it's available for testing, and works quite well now after a few hiccups

**Comment by adamje42** [comment]
#1121

**Comment by migdiluca** [comment]
My bad, thank you!
