### ISSUE TITLE
Switching (or anti-switching) logic is not working as expected

### ISSUE THREAD

**Issue by RooiWillie** [MultiPoolMiner/MultiPoolMiner#1147]
I have noticed on my miner that a specific miner runs many times in a day, yet it was used for the majority of the time. When I had a closer look, I found that the miner was restarted, although it is the current most profitable:

![error](https://user-images.githubusercontent.com/35950838/35553117-337e4958-059f-11e8-958f-7f5a08d86bd1.png)

Simplest way to reproduce this was to restart MPM.

Rig Info:
2 x Zotax GTX 1050ti
16GB Page file
4GB RAM
Core2Duo E8400
Windows 10 Pro 64 Bit

Overclock Info:
Memory: +600MHz
Core Clock: +100MHz
Power Limit: 80%

Mined on Mining Pool Hub, with MPH's internal switching.

**Comment by UselessGuru** [comment]
It is well possible the the miner got started two time, but probably with different parameters. MPM cannot change parameters for a running miner.

**Comment by RooiWillie** [comment]
I had a quick look in the log file - it does not seem to be the case.

Please see log file below:
[Logfile.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1676747/Logfile.txt)

**Comment by UselessGuru** [comment]
I checked you log.
For three loops MPM could not retrieve valid hash rate from the miner (for what ever reason - there is no information on that in the log). Then watchdog knocked the miner and restarted it. On the second loop MPM got valid hash rate -> The miner is running continuously.

**Comment by RooiWillie** [comment]
That is quite strange. I have another logfile that shows exactly the same, but in this case, I was actually looking at the EthDcrMiner64 console window when it closed down - it definitely reported Total Speed > 0.

[Log2.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1676953/Log2.txt)

From what I see, it happens at random intervals - is there something that I can do to activate more verbose logging?

**Comment by UselessGuru** [comment]
> From what I see, it happens at random intervals - is there something that I can do to activate more verbose logging?

No.

> definitely reported Total Speed > 0

What you see on the screen is not what the API reports. What Version of Claymore Dual are you using.
Make sure you use the latest 10.5 version.

**Comment by RooiWillie** [comment]
It is version 10.3. Let me try out 10.5.

**Comment by RooiWillie** [comment]
Ok, I have tried version 10.6 and the problem still persists. This time around, I have the logs for Claymore and MPM:

[Claymore_1517310638_log.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1677443/Claymore_1517310638_log.txt)
[Log3.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1677444/Log3.txt)

Claymore definitely reported MH/s > 0 on the console and the log confirms it.

**Comment by aaronsace** [comment]
I think you have been messing with the miner files. 

Why do you have two???

`Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool europe.ethash-hub.miningpoolhub.com:17020 -ewal RooiWillie.Frankenstein -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2 -tt 0 -mode 1`

`Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool europe.ethash-hub.miningpoolhub.com:17020 -ewal RooiWillie.Frankenstein -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2 -tt 0`

**Comment by RooiWillie** [comment]
I have indeed changed the command line for Claymore. 

-tt 0 was added to switch of temperature monitoring, as one of these restarts was due to that.
-mode 1 was added as it is not profitable to mine Sia anymore, so dual mining can be switched off as a default.

I am not quite sure what is to blame for the 0 speed though. If the API reports 0, then the API is to blame. I could however, not find anything on the matter.

Is there any possible workaround?

**Comment by UselessGuru** [comment]
Clear the miner file situation (make sure you only have one) and try again. Will the issue remain?

**Comment by aaronsace** [comment]
But you have TWO. 

See above.

**Comment by UselessGuru** [comment]
If you do not want dual mining for Sia, then delete the dual miner files ClaymoreNvidiaSia?0.txt / ClaymoreAmdSia?0.txt

Also I would appreciate if you were to use the newest Claymore files, the enhance security.

**Comment by RooiWillie** [comment]
Yes, there were indeed 2. I made the changes one by one.

I can confirm that the arguments line is now:
"-r -1 -mport 23333 -epool $($Pools.Ethash.Host):$($Pools.Ethash.Port) -ewal $($Pools.Ethash.User) -epsw $($Pools.Ethash.Pass) -esm 3 -allpools 1 -allcoins 1 -platform 2 -tt 0 -mode 1"

I have deleted the Sia dueal mining files. I am also running Claymore 10.6.

Here comes the kicker... The same just happened with ethminer.exe:

[Log4.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1677606/Log4.txt)

**Comment by UselessGuru** [comment]
Read the log closely:


This is EthMiner mining for you:
26,52 MH/s 00 Days 00 Hours 03 Minutes Once     Bin\Ethash-Ethminer\ethminer.exe --api-port 23333 -S europe.ethash-hub.miningpoolhub.com:17020 -O **RooiWillie.Frankenstein:x** -SP 2 --cuda


This is EthMiner mining on the donation account:
0  H/s 00 Days 00 Hours 06 Minutes Once     Bin\Ethash-Ethminer\ethminer.exe --api-port 23333 -S europe.ethash-hub.miningpoolhub.com:17020 -O **fonyo.multipoolminer:x** -SP 2 --cuda

And you still have a mess with your Claymore miners (still TWO versions, see the different parameters):
0  H/s 00 Days 00 Hours 46 Minutes 2 Times  Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool europe.ethash-hub.miningpoolhub.com:17020 -ewal RooiWillie.Frankenstein -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2 -tt 0 **-mode 1**
0  H/s 00 Days 00 Hours 02 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool europe.ethash-hub.miningpoolhub.com:17020 -ewal RooiWillie.Frankenstein -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2 -tt 0

**Comment by aaronsace** [comment]
Why is your hash rate so low? 

`WARNING: Stat file (ClaymoreNvidia_Ethash_HashRate) was not updated because the value (17420000) is outside fault tolerance (25639191 ... 31336790).`

It didn't happen with Ethminer.

**Comment by RooiWillie** [comment]
I am suspecting the the CPU is simply not up to the task. I spent some time looking at CPU usage, it runs at 60% when I am logged in via teamviewer. Just before the MPM console refreshes, there is this spike:

![cpu](https://user-images.githubusercontent.com/35950838/35567268-17e83a5e-05cd-11e8-90d2-38cd052a64f8.png)

I guess it may be related to this one:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1027

The 2 different sets of arguments were when I modified them. It is most definitely just the one, with both -tt 0 and -mode 1 (it was just the same log file).

**Comment by aaronsace** [comment]
You definitely have two miner files that do the same thing: 

`Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool europe.ethash-hub.miningpoolhub.com:17020 -ewal RooiWillie.Frankenstein -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2 -tt 0`

`Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool europe.ethash-hub.miningpoolhub.com:17020 -ewal RooiWillie.Frankenstein -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2 -tt 0 -mode 1`

Anyway, fix the hash rate problem and/or turn off watchdog.

**Comment by RooiWillie** [comment]
Please see the log file below confirming there is definitely just the one set of arguments used.

I have since rebooted the PC and stayed off for the last 30 minutes, and the hash rate has stabilized. Considering that TeamViewer does use a fair bit of CPU, I am even more sure now that the CPU is at fault. 

[Log5.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1677779/Log5.txt)

**Comment by RooiWillie** [comment]
Please see the log file below confirming there is definitely just the one set of arguments used.

I have since rebooted the PC and stayed off for the last 30 minutes, and the hash rate has stabilized. Considering that TeamViewer does use a fair bit of CPU, I am even more sure now that the CPU is at fault. 

[Log5.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1677779/Log5.txt)
