### ISSUE TITLE
Miner redraw causing gpu drops and hash rates to temporarily lower

### ISSUE THREAD

**Issue by Adam1901** [MultiPoolMiner/MultiPoolMiner#1148]
Hi,

I've been using MPM for a little under a week now and quite like it.

However my one issue with it as MPM redraws the console output it causes the GPU's to "restart", which drops the gpu usage across all 6 cards to 0% for a fraction of a second. This drop causes the hashrate to dip to ~1500K/H from 1900K/H

I've had a dig around the code but could not see anything glaringly obvious.

![image](https://user-images.githubusercontent.com/16060576/35563834-f62a172e-05af-11e8-8b10-6b7bcaa7bfd7.png)

Current GPU specs
4*1060 3gb
2*1060 6gb

**Comment by aaronsace** [comment]
It tends to happen on dual core processors. 

Try this work around: 
c881a86774d19415efe11950839a51d6d47fd59f

**Comment by UselessGuru** [comment]
Duplicate, please update here:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1027

**Comment by revpolitic** [comment]
I write here because #1027 is closed.
I'm same problem with low performance CPU G4400. 
I notice drops in GPU ussage every MPM profiability check.
I try increase -interval to 180, but only solve partially, so GPUs drops less times per hour.
Today i try setting priority of zm.exe to normal (It was set to below normal). 
It works, no more drops in GPU ussage, but with Win10 Task Manager i have to set priority everytime zm.exe is loaded. 
I googled for permanent priority setting but seems no way to do it with Win10 Task Manager.
I find a freeware solution (ProcessHacker) in sourceforge for that, but i don't try this permanent solution.

**Comment by UselessGuru** [comment]
> Today i try setting priority of zm.exe to normal (It was set to below normal).

The current MPM implementation runs all miners with priority 'below normal':

`            $this.Process = Start-SubProcess -FilePath $this.Path -ArgumentList $this.Arguments -LogPath $Global:ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(".\Logs\$($this.Name)-$($this.Port)_$(Get-Date -Format "yyyy-MM-dd_HH-mm-ss").txt") -WorkingDirectory (Split-Path $this.Path) -Priority ($this.Type | ForEach-Object {if ($_ -eq "CPU") {-2}else {-1}} | Measure-Object -Maximum | Select-Object -ExpandProperty Maximum)`

This part of include.psm1 line 500 ' -Priority ($this.Type | ForEach-Object {if ($_ -eq "CPU") {-2}else {**-1**}} ' is responsible :-) -1 = BelowNormal; 0 = Normal

@aaronsace: I propose making the priority $Config item. This keeps popping up a lot.

**Comment by aaronsace** [comment]
@revpolitic Have you tried the latest code first? 
https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

I can change the priority but that will mean MultiPoolMiner will have a lower priority than the miner it's tasked to close. I don't think that's good practice but if it fixes 100% of the issues on that awful processer that everyone keeps buying then I'll change it and move on.

**Comment by revpolitic** [comment]
@aaronsace I have not tried the last code.
I understand the problem of MPM priority over the other miners but apparently there is no problem and the change of miner continues to work with that priority change. 
As soon as I can, I try the last code .

PS. You are right, my CPU sucks. I ordered a i5 to solve once and for all this issue.

**Comment by aaronsace** [comment]
I think it works on the latest code but if you are still having issues then a config option could be added as @UselessGuru suggests.

**Comment by revpolitic** [comment]
I´m benchmarking new release right now. I'll post results.
Thanks.

**Comment by Synicide** [comment]
Thank you for the responses.  The two following changes fixed the issue for me.  CPU is C3930.
Running 48 hours and the stability of hashrates is now resolved, and no other issues.

1)Update in MultiPoolMiner.ps1 to set priority to Idle.   Line 86 insert after #Start the log section.
#Set process priority to BelowNormal to avoid hash rate drops on systems with weak CPUs
(Get-Process -Id $Global:PID).priorityclass = "Idle"

2) Changed Priority of miner to Normal (0). 
include.psm1 line 500 ' -Priority ($this.Type | ForEach-Object {if ($_ -eq "CPU") {-2}else {0}}
