### ISSUE TITLE
MPM devfee

### ISSUE THREAD

**Issue by angelics** [MultiPoolMiner/MultiPoolMiner#1149]
does MPM take miner devfee into account? ex. subtract benchmark.
could not find anything related in any of the ps..

**Comment by UselessGuru** [comment]
> does MPM take miner devfee into account? ex. subtract benchmark.
could not find anything related in any of the ps..

No, currently it does not.

Dev fee is approx 1-2%. If you compare this with the difference between reported payout by the pool vs. real payout then dev. fee is almost neglectable.

The same can be said for pool fees. Here we have the face the unpleasant fact that not all pools report their fees through their API. So MPM has no way to get proper information for its calculations.

**Comment by Braintelligence** [comment]
@UselessGuru Sorry for derailing, quick question: We had a few commits in the past days, is a new release-version ready soon?

**Comment by UselessGuru** [comment]
> We had a few commits in the past days, is a new release-version ready soon?

This is not up to me to decide... Ask master Aaron :-)

**Comment by Braintelligence** [comment]
@aaronsace Oh dear master, please bless us with thine update of the heavens. :D

**Comment by angelics** [comment]
ps able to -match $minername then *.99 for 1% dev fee during benchmark?
i have no idea how ps work. but thats how nicehashlegacy substract some of the hashrate during benchmark

**Comment by adamje42** [comment]
@angelics It's definitely possible. /tutulino/Megaminer/ Does something similar in with software:

`if ([double]$Miner.Fee -gt 0) {$MinerRevenue=$MinerRevenue -($MinerRevenue*[double]$Miner.fee)} #MinerFee
if ([double]$_.Fee -gt 0) {$MinerRevenue=$MinerRevenue -($MinerRevenue*[double]$_.fee)} #PoolFee`

Where each miner file has something like:
`"Fee":  "0.02"`

I'm having some troubles wrapping my head around Aaronaces profit calculations in MultiPoolMiner.ps1. Him and tutulino have very different scripting styles. It'd be easy to add the % fee to each miners file but I'm not quite sure how to factor it in myself and start experimenting with it.

**Comment by angelics** [comment]
@adamje42  thanks for pointing it out. i got it working here. might make a pull request but i doubt @aaronsace will like it.

**Comment by UselessGuru** [comment]
> It's definitely possible. /tutulino/Megaminer/ Does something similar in his software:

The calculations are not the problem. 
The difficult part is adding the correct information to the pool & miner objects.
MPM retrieves all data for its calculations from the pool (price / speed etc.). I the pool does not send fee data, then how should that work?
For miner binaries this is a bit easier to implement because it is a set value per binary (or two in case where dev fee is different for ssl and non-ssl connections).

**Comment by adamje42** [comment]
@UselessGuru I was only referring to miner binaries. For pool data we'd most likely just have to do it manually, short of the pools implementing it in their APIs

**Comment by angelics** [comment]
i tested with dstm only. adding 50% dev fee and it work as intended tho

**Comment by Braintelligence** [comment]
@UselessGuru Would you say that using current master branch would be stable enough or are there things that need to be resolved before?

**Comment by UselessGuru** [comment]
> Would you say that using current master branch would be stable enough or are there things that need to be resolved before?

Ask master Aaron. He's the man in charge.
The question is: Stable enough for what?

**Comment by Braintelligence** [comment]
Stable enough for letting it run productively on all of my mining rigs? 😸

**Comment by UselessGuru** [comment]
You can always just download the latest ZIP-file. This includes all 'official' commits:

https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

**Comment by Braintelligence** [comment]
That's what I meant when I was saying "current master branch". In some projects it's not a wise thing to do, because the latest commit isn't always functional.

**Comment by Nickfost** [comment]
@Braintelligence i think it's understood that most of us who watch this repo pull the master often and run that. i don't think it's smart if you want 100% stable results (sometimes two days later they'll revert and say something was a bad idea) 

I do know others actually just git pull from the repo daily and run it without an issue

**Comment by Braintelligence** [comment]
@Nickfost I saw an issue here somewhere, where a guy was running latest master commit and looked for assistance in a problem and aaronsace wondered why he used the latest commit instead of the release, recommending to use the latter to solve his problem, because the latest commit is not necessarily meant to deliver a completely working app.

**Comment by aaronsace** [comment]
Apologies, I've delayed the release until next week as there were more issues and less time than anticipated. 

I like people running the master as long as they realize it's for testing and development. Once the master code is complete and tested then a release tag is added but is marked as a pre-release for a few days to allow for any bugs to be reported.
