### ISSUE TITLE
Cannot Bind Argument to Parameter "DifferenceObject" because it is null

### ISSUE THREAD

**Issue by priyavadan** [MultiPoolMiner/MultiPoolMiner#1150]
![image](https://user-images.githubusercontent.com/3895377/35581931-e2368d76-05b2-11e8-8d78-3afa95a2641c.png)

**Comment by priyavadan** [comment]
running latest from master branch.

**Comment by aaronsace** [comment]
You have not posted your log but if it says 'opencl' anywhere then you need to install the full graphics drivers.

**Comment by priyavadan** [comment]
re-installing the drivers right now, will update in a bit

**Comment by priyavadan** [comment]
no more errors after reinstalling drivers! did a clean re-install.
