### ISSUE TITLE
Separate WorkerName for Cpu/Gpu

### ISSUE THREAD

**Issue by korishan** [MultiPoolMiner/MultiPoolMiner#1151]
I like to split things up and get as much individual detail as possible. When I was running the miners manually before, I had one Korishan.GPU and the other Korishan.CPU so that I could tell what the hash rates were being reported to the pool when I viewed the web site (I use NanoPool, MiningPoolHub, NiceHash). This allowed me to easily see which one might be stuck, or needs to be tweaked.
Currently, there's only 1 Workname listed and it's broastcasted to all miners regardless of type.

I'm still learning MPM, so is there a way to split the Worknames up and I just missed it, or is just not available? If it's not available, could it potentially be made available in a later build?

Thanks for all your hard work.
Kori

**Comment by aaronsace** [comment]
You'll struggle to follow it as it switches across pools and algorithms. 

You are best using the monitor that @grantemsley is working on: https://multipoolminer.io/monitor

**Comment by korishan** [comment]
Yeah, I saw that one. But I currently wasn't wanting to setup a web server to run it. I suppose I could do a virtual system and see how it runs.

Thanks aaron

**Comment by grantemsley** [comment]
You don't need to run your own copy, you can use the hosted one at https://multipoolminer.io/monitor

Running your own is an option for people running large farms or who want to keep their mining extra private, but the hosted one works for most people.

**Comment by korishan** [comment]
Yeah, there is that   :)  Thanks.  *zoom!!!* straight over my head  :P
