### ISSUE TITLE
Add keccak or more supported algorithm to Excavator miner file

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1154]
The new [Excavator releases](https://github.com/nicehash/excavator/releases) are performing very well with CUDA 9.1.

Consider adding all the supported algorithms into the Excavator miner file.

![image](https://user-images.githubusercontent.com/1230402/35619212-8933dc94-067d-11e8-99bf-28fe38e672dc.png)

**Comment by UselessGuru** [comment]
They will be included soon (except for sia which is no longer profitable due to ASIC mining):

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1104

If you are satisfied with this answer then please close this - we should keep the list of open issues short. Thank you!
