### ISSUE TITLE
Request: Please add support for zergpool

### ISSUE THREAD

**Issue by jrafaelmdo** [MultiPoolMiner/MultiPoolMiner#1155]
Hello Devs,

Please add support for Zergpool.

ZERGPOOL MINING - 0% fee multialgo, multicoin, autoexchange pool

https://bitcointalk.org/index.php?topic=2759935.0
http://zergpool.com/

Thanks.

**Comment by caesarmine** [comment]
Note: Sniffdogminer already has support for this.

**Comment by robl45** [comment]
Zergpool looks decent, a lot better than some other pools.

**Comment by evanvz** [comment]
Try this... attached. Haven't tested it as I'm using @UselessGuru's miner. Just changed a few things from another pool file.

[Zergpool.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1685496/Zergpool.zip)

**Comment by evanvz** [comment]
Made one for @UselessGuru's miner that seems to work.
[Zergpool.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1685542/Zergpool.zip)

**Comment by robl45** [comment]
Tried with useless guru miner and appears to work fine, I assume it would work in the main program as well.

**Comment by UselessGuru** [comment]
### Testusers wanted!

**Important: Support for ZergPool requires newer builds of MPM which support config file 'config.txt'.**

Howto: Download the [lastest MPM package](https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip), then put attached [ZergPool.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1692714/ZergPool.txt) to the 'Pools' folder and rename to ZergPool.ps1.
Please report issues regarding ZergPool in this thread - Thank you!

**Note: Zergpool allows three different options for payout:**

_Option 1 - Mine in particular algorithm_
This will let pool to mine most profitable coin in this algo or use merged mining benefits, and auto exchange rewards to your coin wallet. You should use coin wallet address as username.
Use c=SYMBOL in password to make sure payout wallet coin is identified correctly.
Example to mine in Scrypt algorithm and get payout in BTC
-o stratum+tcp://zergpool.com:PORT -u <YOUR_BTC_ADDRESS> -p c=BTC

_Option 2 - Mine particular coin_
Use your coin wallet address as username in mining software. Specify c=SYMBOL as password to idenfify payout wallet coin, and the same coin in mc=SYMBOL to specify mining coin
Example to mine Guncoin and get payout in Guncoin
-o stratum+tcp://zergpool.com:PORT -u <YOUR_GUNCOIN_WALLET_ADDRESS> -p c=GUN,mc=GUN

_Option 3 - Mine particular coin with auto exchange to wallet address_
This will mine coin you specified in password field only and autoexchange it to your wallet currency for payout.
Use c=SYMBOL in password to make sure payout wallet coin is identified correctly. Use mc=SYMBOL to target particular coin for mining
Example to mine in Innova coin and get payout in LTC
-o stratum+tcp://zergpool.com:PORT -u <YOUR_LTC_ADDRESS> -p c=LTC,mc=INN

**Currently only auto-conversion payout to BTC (Option 1) is fully supported by MPM.**
Options 2 & 3 require changes to pool parameter handling and are currently NOT supported.

**Comment by robl45** [comment]
what is different between lastest file and file that evanvz provided?

**Comment by Chron-O-John** [comment]
Just tried it.
It seems that it only works without the -poolname parameter.
I tried to include it using "-poolname miningpoolhubcoins,Zergpool"
result is, that only miningpoolhub is used.

Did I do something wrong or is it not (yet) supported?

**Comment by airwalker1** [comment]
Can you add zergpool to miningpoolhubstats?

**Comment by evanvz** [comment]
Hi @robl45 

The pool file I provided works only for @UselessGuru MPM setup.

E

**Comment by evanvz** [comment]
ZergPool down

From there site

"We are on maintenance after hack and following DDoS attack. Working hard to move service to AWS with proper DDoS protection. Takes a bit more time than anticipated, hope to get online during weekend only."

**Comment by genstian** [comment]
I dunno, added this to my several of my rigs, and the income estimates jumped 50%, and it was pretty much mining exclusively on zergpool over a test period of 48 hours, meanwhile the actual income dropped 30% compare to MPH+nicehash.

Its the worst overestimation pool I've tried. But atleast the pool file seems to work just fine.

**Comment by paulpoco** [comment]
0% fee, nothing is never free.

**Comment by robl45** [comment]
Yup, garbage pool that keeps changing the payout so I'm stuck mining on it for god knows how long until I finally reach the new payout.

**Comment by UselessGuru** [comment]
To be continued in https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1362
