### ISSUE TITLE
Program and Miners Randomly Close

### ISSUE THREAD

**Issue by WJSM5** [MultiPoolMiner/MultiPoolMiner#1156]
As the title states, the miner will run for about 6-8 hours and then randomly close. The computer DOES NOT crash. All GPUs stay below 64C and there are no errors recorded in Windows Event Log.

Log files attached.
[2018-01-31_06-21-15.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1682262/2018-01-31_06-21-15.txt)
[2018-01-31_10-36-03.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1682263/2018-01-31_10-36-03.txt)

**Comment by aaronsace** [comment]
Uninstall PowerShell 6.0.0-**RC.2**; there is a new version.

**Comment by WJSM5** [comment]
@aaronsace Perfect, thanks. I will let it run 8 hours and see if this solves the problem and report back for others.

**Comment by WJSM5** [comment]
@aaronsace happened again with this being the last line in the log:

PS>TerminatingError(Invoke-RestMethod): "A task was canceled."
WARNING: Coinbase is down.
PS>TerminatingError(Invoke-RestMethod): "A task was canceled."
WARNING: Pool API (MiningPoolHub) has failed.

**Comment by UselessGuru** [comment]
> WARNING: Coinbase is down.

Exacly what is says. MPM cannot contact Coinbase for exchange rate updated

> WARNING: Pool API (MiningPoolHub) has failed.
API of of MiningPoolHub is not responding.

Both messages could be caused by internet connectovity issues. Make sure your interen conneciton is working reliably.
There is nothing that MPM can do about it. MPMs code is working fine.
