### ISSUE TITLE
Documentation is missing information.

### ISSUE THREAD

**Issue by thericeking** [MultiPoolMiner/MultiPoolMiner#1157]
Documentation sample shows exactly where to put -MinerStatusURL https://multipoolminer.io/monitor/miner.php

However it doesn't say where exactly to put -MinerStatusKey d3f69e53-55a3-4f25-8530-742eb86de572

See for yourself if you don't believe me by scrolling down to "SAMPLE USAGE" here https://multipoolminer.io/docs

I would like to try this new feature

Thank you

**Comment by jweber018** [comment]
If you leave it blank, your status key is the same as your selected wallet address.
