### ISSUE TITLE
Trojan comes in the current version to download.

### ISSUE THREAD

**Issue by Imperiumt** [MultiPoolMiner/MultiPoolMiner#1158]
There was a zombie miner that installed when I unzipped the files for multipoolminer.  NO it wasnt multipoolminer itself but a seperate zombie miner that would constantly restart when the task was stopped.

**Comment by aaronsace** [comment]
Nothing to do with MultiPoolMiner. There is no real Trojans. 

https://github.com/MultiPoolMiner/MultiPoolMiner/releases

**Comment by Imperiumt** [comment]
Happened last night;.  Unzipped then my spu went to 50% usage and stayed there.  Checked tasks and there was some Strangely named task.. stopped it and it kept restarting.   ran superantispyware which saidit removed it but didnt .  As today when i turned on pc another task by different name using the same 50% and wiht same symbol.. but was removed by malwarebytes.   Maybe you didnt put one in there.  but someone did.
