### ISSUE TITLE
Nicehash Wallet?

### ISSUE THREAD

**Issue by Klein80** [MultiPoolMiner/MultiPoolMiner#1159]
I not understand this Miner.
Wallet = xxxxx
Nicehash Wallet = ???? i have not 1 Wallet for NIcehash and others... Nicehash have a other Wallet?

Thank you

**Comment by aaronsace** [comment]
Man, could you write the issue any more confusing...

You don't need a nicehash wallet; enter your Bitcoin wallet. 

NiceHash wallet support is coming soon.

**Comment by Klein80** [comment]
Ok  thank you.

**Comment by UselessGuru** [comment]
See also https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1080

Full documentation on the new config.txt items and how-to will follow.
