### ISSUE TITLE
BTC/GH/DAY not updating

### ISSUE THREAD

**Issue by nickvasel** [MultiPoolMiner/MultiPoolMiner#1160]
MPM ran for 8 hours today and the BTC/GH/DAY did not change once stuck on mining Lyra2z all day. log files and start.bat attached. 
[2018-01-31_13-09-56.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1683694/2018-01-31_13-09-56.txt)
[Start-MiningPoolHub.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1683695/Start-MiningPoolHub.txt)

**Comment by aaronsace** [comment]
You paused the script after 16 minutes. Microsoft Windows has a feature where by clicking your curser on the command line window pauses it. Press any key to resume.

**Comment by nickvasel** [comment]
OMFG.... wow thanks... I'll try it...

**Comment by nickvasel** [comment]
that did it.... close it.
