### ISSUE TITLE
API not working?

### ISSUE THREAD

**Issue by Klein80** [MultiPoolMiner/MultiPoolMiner#1161]
My Friend, i have start the Programm + make Benchmark.
Say API from Y... and MPH not working... :(

i have 0 lucky

**Comment by UselessGuru** [comment]
> Say API from Y... and MPH not working... :(

The error will go away when API of the contacted pool is working again. Not MPM's fault.

**Comment by michaelps100** [comment]
Hi guys, anyone have idea to solve this cloudflare problem?

"
WARNING: Coinbase is down.
WARNING: Pool API (MiningPoolHub) has failed.
WARNING: Pool API (MiningPoolHubCoins) has failed.
WARNING: Pool API (Zpool) has failed.
"

I have this ultil last week, follow log:

**********************
PowerShell transcript start
Start time: 20180201153356
Username: DESKTOP-GESUNUK\Mick Love
RunAs User: DESKTOP-GESUNUK\Mick Love
Configuration Name: 
Machine: DESKTOP-GESUNUK (Microsoft Windows NT 6.2.9200.0)
Host Application: C:\Program Files\PowerShell\6.0.0-rc.2\pwsh.dll -noexit -executionpolicy bypass -windowstyle maximized -command & .\multipoolminer.ps1 -wallet 1EJJDXdjau1sxTysE9s1fSbzXLc1ryhV8u -username michaelps100 -workername GPU -region us -currency btc,usd -type nvidia, cpu -poolname miningpoolhub,miningpoolhubcoins,zpool,ahashpool -algorithm Bitcore, Blakecoin, Blake2s, blakevanilla, C11, CryptoNight, Ethash, Decred, Equihash, Groestl, HMQ1725, hsr, jha, Keccak, Lbry, Lyra2RE2, Lyra2z, M7M, MyriadGroestl, NeoScrypt, Nist5, PHI, Polytimos, Quark, Qubit, scrypt, SHA256, Sia, Sib, Skunk, Skein, Timetravel, Tribus, Veltor, X11, X11evo, X11gost, x13, x14, X17, Xevan, Yescrypt, siaclaymore -donate 0 -watchdog -switchingprevention 2
Process ID: 1908
PSVersion: 6.0.0-rc.2
PSEdition: Core
GitCommitId: v6.0.0-rc.2
OS: Microsoft Windows 10.0.16299 
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is .\Logs\2018-02-01_15-33-56.txt
PS>TerminatingError(Invoke-RestMethod): "     
  

Attention Required! | Cloudflare

**Comment by aaronsace** [comment]
@michaelps100 You have been banned from Coinbase: 
"Attention Required! | Cloudflare"

Try resetting your internet connection.

**Comment by michaelps100** [comment]
My ip is fixed... :(
Any suggestion VPN Service that runs correct with that?

**Comment by korishan** [comment]
>Try resetting your internet connection.
>>My ip is fixed... :(

This doesn't mean get a new ip address. Try cycling the power to your router(s). Our network has similar issues and just rebooting the cable modem and primary router, network speed and traffic resumes without problems.
