### ISSUE TITLE
useless guru edition question

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1163]
Don't know if this is the right place, please advise if there is another place to ask.  Trying the useless guru version that I saw mentioned here.  I like that I can separate my 1060's from my 950 card but currently the 950 card is stuck on CCminer alexis  because the intensity is too high for the 950.  I dropped the intensity in the miner file for ccminer Xevan as there is only that miner for Xevan but I assumed that eventually it would just quit ccminer alexis on the 950.  It has run it 10 times already where on the main fork it would have given up after like 3 or 5 tries.  Does it ever give up?

**Comment by UselessGuru** [comment]
Please report questions regarding my fork over there. Thank you!

>  It has run it 10 times already where on the main fork it would have given up after like 3 or 5 tries. Does it ever give up?

It should, but I know there is a problem in the code. I'll fix it eventually. As a work around for now create a benchmark file manually (copy a existing one) and set all hash rates to 0. That will do.
