### ISSUE TITLE
Files format from master is bad (Strange behaviour) 

### ISSUE THREAD

**Issue by komer83** [MultiPoolMiner/MultiPoolMiner#1164]
Ok, this issue is strange.

Downloading the master and editing the files is hard as there are no line breaks like in the release files. HOWEVER, checking the same files with MacOS text editor, they look perfectly normal. 
Went back to Windows text editor (I don't even know what it's called) and again no line breaks. Checking the files from the release, they look normal. 
Double checking on MacOS, the master files are fine, going to Windows, no line breaks.

Is it a local problem of my Windows or anyone can see this too?

**Comment by korishan** [comment]
I just use Notepad++ and it formats the text correctly regardless. You can even do CR/LF conversion, too.

**Comment by aaronsace** [comment]
@komer83 Use GitHub desktop which detects your operating system downloads the correct line breaks.
