### ISSUE TITLE
After installing and running once MPM, the card is much slower

### ISSUE THREAD

**Issue by utnalove** [MultiPoolMiner/MultiPoolMiner#1166]
Hello,
I am using Windows 8.1
I have a new EVGA GTX 1080ti KINGPIN since 2-3 days.
I was mining with EWBF and miningpoolhub. All good.

Without overclocking the card it run at 740sol/s.
With overclocking 790 sol/s.

I turned of the EWBF miner and then.
I installed MultiPoolMiner.
I put the escavator in a new folder in /bin and the run start.bat.

A lot of "Stuff" appeared in a cmd window. I waited about 5-10 minutes, then I realized that it was using the GPU/CPU because the computer started to answer slow to the mouse.

So I understood that:
-or it is benchmarking the hardware,
-or it is already mining with a default/sombody else's data

So I said to myself I don't have time to check how to configure it for myself, I will check in the evening, and I turned it off, and went back to EWBF.

But now.... 
EWBF started to mine at 550 sol/s!!!
I restarted it few times, the same.

I rebooted the computer and a watchdog blue screen appeared.
I rebooted once again and now I was able to login to Windows.
I restarted EWBF and now it is mining at 605 sol/s. If I turn on overclock it goes to 660.
rebooted the pc several times and all the same :/

Very small for such VGA.

Can anybody suggest what may have happened? All straight after running MPM.

**Comment by aaronsace** [comment]
740 sols is correct for 1080Ti but nothing you wrote is anything to do with MultiPoolMiner. 

Just start standard ICT checks. Download drivers of the NVidia website. Make sure everything is set to default clock settings. Check the temperature is not throttling your card. Check the PSU is providing enough stead power and motherboard is functioning correctly. All that's left then is that the card is faulty.

**Comment by utnalove** [comment]
I remember once the card was mining for about 2 hours at 770 sols. Then without doing anything I went back to 500 sol. I was far from the PC so I didn't even click anything at all.

I will reinstall the drivers. So far I installed the ones from the CD.

The temperature is working between 74 and 79 C. It's in a normal Thermaltake case, not in a rig (yet).

How to check if the PSU is providing enough stead power? The PSU is 1250W... and the whole computer is using about 450W (i have the tester always on in the socket)/

**Comment by UselessGuru** [comment]
@utnalove The code in MPM has absolutely nothing that would make your card slower.
If it is slower you will have to look for other reasons such as thermal throttling, or your CPU is too slow to handle mining _and_ MPM's processing.
In your post you write is was using CPU for mining too. -> turn CPU mining off.

**Comment by aaronsace** [comment]
Install the graphics drivers from the NVidia and AMD websites.

**Comment by utnalove** [comment]
I installed the drivers from the EVGA website. Should it be from the NVIDIA website instead?
