### ISSUE TITLE
New Ethminer

### ISSUE THREAD

**Issue by Imaminer** [MultiPoolMiner/MultiPoolMiner#1168]
There is a new version of Ethminer that I have tested on one of my AMD rigs. It runs nice.
I added some stuff to your command....Check it out if you like.

{
        "Type":  "AMD",
        "Path":  ".\\Bin\\Ethash-Ethminer\\ethminer.exe",
        "Arguments":  "--farm-recheck 200 -G -S $($Pools.Ethash.Host):$($Pools.Ethash.Port) -O $($Pools.Ethash.User):$($Pools.Ethash.Pass) -SP 2 --cl-local-work 256 --cl-global-work 16384",
        "HashRates":  {"Ethash":  "$(if(([OpenCl.Platform]::GetPlatformIDs() | ForEach-Object {[OpenCl.Device]::GetDeviceIDs($_, [OpenCl.DeviceType]::All)} | Where {$_.Type -eq 'GPU' -and $_.Vendor -eq 'Advanced Micro Devices, Inc.'} | Where-Object {$_.GlobalMemsize -ge 3000000000}).Count -eq 0) {0} else {$Stats.EthminerAmd_Ethash_HashRate.Week})"},
        "API":  "Claymore",
        "Port":  "13333",
        "URI":  "https://github.com/ethereum-mining/ethminer/releases/download/v0.14.0.dev1/ethminer-0.14.0.dev1-Windows.zip"

**Comment by UselessGuru** [comment]
This is a dev version. Will wait 'til the final version is out.
