### ISSUE TITLE
opens new miner without closing the previous one

### ISSUE THREAD

**Issue by PaLiMe** [MultiPoolMiner/MultiPoolMiner#1170]
Hi,

since today I am facing the above problem. It opens new miner till the system crashs. Attached two screenshohots and the log file. Has anyone an idea? Thanks for your support! 
![image](https://user-images.githubusercontent.com/36117300/35772788-5f988b7c-0944-11e8-87fc-df6c835034df.png)

![image](https://user-images.githubusercontent.com/36117300/35772793-8257b50c-0944-11e8-855b-2008d10b9e77.png)

[2018-02-03_23-33-59.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1692319/2018-02-03_23-33-59.txt)

**Comment by grantemsley** [comment]
Use the ```-delay``` parameter in start.bat

```-delay 10``` will make it wait 10 seconds between closing old miners and opening new ones.  This will give them a chance to shut down and release the video hardware, and you won't have this issue anymore.

**Comment by PaLiMe** [comment]
I´ll try that. thanks..

**Comment by PaLiMe** [comment]
it did not solve the problem unfortunately. I added delay and start the MPM. direct after a minute it opens the second one
[2018-02-04_02-02-15.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1692357/2018-02-04_02-02-15.txt)

**Comment by aaronsace** [comment]
@PaLiMe The miners have crashed and you are out of memory; I think you have system issues. 

The latest commits should be more robust but I can't guarantee that it will fix your problem: c768136c5caf893cba9b8a1c02b7f2040186a763

**Comment by PaLiMe** [comment]
strange, it works fine till today. I thought this "out of memory" message is related to these many open miners. one miner, enough memory?!... can you please tell me if i can ignore the error in the log file. it looks  new to me: 

PSEdition: Core
GitCommitId: v6.0.1
OS: Microsoft Windows 10.0.16299 
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.1
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is .\Logs\2018-02-04_02-02-15.txt
PS>TerminatingError(Start-SubProcess): "Exception setting "PriorityClass": "Zugriff verweigert""
Start-SubProcess : Exception setting "PriorityClass": "Zugriff verweigert"
At C:\Users\admin\Desktop\MultiPoolMinerV2.7.1.4\Include.psm1:438 char:25
+ ... s.Process = Start-SubProcess -FilePath $this.Path -ArgumentList $this ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Start-SubProcess], SetValueInvocationException
+ FullyQualifiedErrorId : ExceptionWhenSetting,Start-SubProcess
Start-SubProcess : Exception setting "PriorityClass": "Zugriff verweigert"
At C:\Users\admin\Desktop\MultiPoolMinerV2.7.1.4\Include.psm1:438 char:25
+ ... s.Process = Start-SubProcess -FilePath $this.Path -ArgumentList $this ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Start-SubProcess], SetValueInvocationException
+ FullyQualifiedErrorId : ExceptionWhenSetting,Start-SubProcess

**Comment by aaronsace** [comment]
The miner has crashed.

**Comment by comicchang** [comment]
@aaronsace hello, commit https://github.com/MultiPoolMiner/MultiPoolMiner/commit/c768136c5caf893cba9b8a1c02b7f2040186a763 breaks excavator. it will report normal hashrate to MPM, but wont find a single share.

**Comment by aaronsace** [comment]
@comicchang What you are describing makes no sense but there are commits coming that will improve hashrate reading speed/accuracy; also there will be an overhaul on the Excavator interaction so I'll be testing Excavator.

**Comment by aaronsace** [comment]
44d46c92e6489864d54fd9227b8679d16844dd5b
