### ISSUE TITLE
New Cast XMR Version 0.8.5

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1171]
> ## [Cast XMR Version 0.8.5 (2018/2/1)](http://www.gandalph3000.com/cast_xmr/cast-xmr-optimized-cryptonight-miner-for-rx-vega/)
> - 1% performance gain for Vega Frontier Edition with Blockchain driver (fastest GPU around)
> - 1% performance improvement with current stock driver (18.1.1) for RX Vega 56/64 (40% to go to reach Blockchain driver)
> - fix for random blocking console output
> - GPU now always logs with its device id not the order they are listed in the -G argument
> - --log option to log output to a file
> - remote access includes CORS support in HTTP header

[Cast XMR 0.8.5 for Windows (64 bit)](http://www.gandalph3000.com/download/cast_xmr-vega-win64_085.zip)

Their [forum](https://bitcointalk.org/index.php?topic=2256917.0) is not updated regularly.

**Comment by UselessGuru** [comment]
Miner updated to version 0.8.5

Howto update:
- delete 'Bin\CryptoNight-Cast' folder
- delete 'Stats\Bin\CryptoNight-Cast.*'
- replace 'Miners\Bin\CryptoNight-Cast.txt' with [latest miner file](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/028c92d74cf07c02e46fa8c86b3545ac17d1d7ac).
- restart MPM - it will download and unpack latest miner binary and re-benchmark cast miner.

**Comment by Sayyiditow** [comment]
Is it ever possible to do more than 8 vegas with the BC drivers? Having a lot of trouble. Can only do 8 on one PC. All 10 show up but 2 don't show up as "vega", but "Microsoft Display Adapter"
