### ISSUE TITLE
XMR-STAK is 10-15% Faster than XMRIG

### ISSUE THREAD

**Issue by kevharper** [MultiPoolMiner/MultiPoolMiner#1175]
On my nVidia cards, XMR-STAK is significantly faster than XMRIG.  Can it be added?

**Comment by aaronsace** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/FireiceNvidia.ps1

**Comment by kevharper** [comment]
Thanks.  
I think you can get more speed out of the 1070's with the following  (I get **3,650 H/s** out of my 5 card rig) with these settings:
    "threads" : 16, "blocks" : 90,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : false,

With your settings (the following) I get **3,430 H/s**:
    "threads" : 28, "blocks" : 45,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,


Any idea how to make it work with a 970?  It crashes immediately for me with your settings - probably because they are for 1070 only.   For my 970, I use the following & get 450 H/s when I run xmr-stack separately:
"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 13, "blocks" : 39,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : false,
  },

**Comment by adamje42** [comment]
The nvidia.txt/amd.txt/cpu.txt files are auto-generated by xmr-stak when it launches. MPM does not come with any or have anything to do with how they are generated. If you want to duplicate the results you see when you run the miner separately, just copy your config files from your separate xmr-stak folder into /Bin/CryptoNight-FireIce/.

**Comment by kevharper** [comment]
Thanks.  I figured that out with a fresh install of  MPM.  Works great on my 1070 systems.     I still have issue with my gtx 970 system though.  It will launch xmrfireice & it runs but the benchmark never finishes and MPM  launches another instance of it without closing the first.    Not sure how to figure that one out.  Maybe it has to do with the 970 having less memory.

**Comment by kevharper** [comment]
It will just keep opening more and more instances....

![capture](https://user-images.githubusercontent.com/34816613/35787335-499475a4-09fb-11e8-9edc-678af2392376.JPG)
