### ISSUE TITLE
NiceHash + MPH - Equihash not working

### ISSUE THREAD

**Issue by ztowne13** [MultiPoolMiner/MultiPoolMiner#1177]
I'm on the latest version of MPM. When I run MPM with NiceHash only, the NiceHash Equihash algorithm is there and it mines on it when most profitable. When I mine on both MPH and Nicehash, Equihash doesn't even show up. I read another post where the developer said that's how it's supposed to be but currently, the NiceHash equihash algorithm is the most profitable algorithm but it just doesn't even show up on the list or ever gets mined so I'm currently mining MPH's top Equihash coin. That's fine but I could be earning a few more BTC p/ day if I had access to the NiceHash equihash pool.

This is a picture of when I run MPM with NiceHash + MPH (No NiceHash equihash ALGO)

![capture](https://user-images.githubusercontent.com/6634230/35782842-7c7268ca-09b3-11e8-83ea-10e30962169e.png)

This is a picture of when I run NiceHash ONLY (NiceHash equihash ALGO appears)

![capture2](https://user-images.githubusercontent.com/6634230/35782844-832c226e-09b3-11e8-87a8-dfe0c415d28c.png)

As you can see, the equihash algorithm runs fine with NiceHash, as long as it's not with MPH. And also, as you can see, the equihash is as profitable if not more profitable currently on NiceHash then MPH.

Any help would be appreciated, thanks!

**Comment by aaronsace** [comment]
NiceHash is a 'pool' not an algorithm.

**Comment by aaronsace** [comment]
Also, your screenshots show that MiningPoolHub is currently 0.00009 BTC more profitable...?

**Comment by ztowne13** [comment]
I am aware NiceHash is a pool, not an algorithm, I apologize for my incorrect terminology. I am referring to NiceHash's equihash pool. I also know that in the screenshot MPH is more profitable, earlier that was not the case for a few hours. The point is that NiceHash's equihash pool doesn't show when running with MPH + Nicehash together, and is there any way for me / you to fix this? Thanks in advance!

**Comment by aaronsace** [comment]
No, this is not a bug; MultiPoolMiner knows what's more profitable. If you want to use NiceHash only then just select NiceHash.

**Comment by ztowne13** [comment]
Can you please explain to me how it's a bug... I didn't have time to write this post at the exact time of my discoveries but yesterday I booted NiceHash with only Equihash and MiningpoolHub + NiceHash with only equihash and NiceHash's equihash algorithm WAS 100% more profitable without a doubt (and the accuracy is not low at all). This is 100% a bug in the code, please stop denying it because NiceHash Equihash pool being mined at over .0008 BTC/day compared to MPH's ZCash equihash pool being at around .0007 BTC/day is DEFINITELY more profitable. And I understand my pictures don't show that fact but you and I both know that profitability of certain algos on certain pools goes up and down with time...

Regardless, even if it wasn't more profitable EVER, why does MPM have to show all of the useless algos like LBRY or Groestl or Keccak (yes I know I have them enabled - but I also have equihash enabled) that are ALSO not profitable ever and not show the equihash algorithm so I can at least see it's profitability.

I'm not trying to attack you, your program is fantastic and I really appreciate the work you've done, I just feel like you're getting very defensive over something that I don't see how it could otherwise be a bug...
