### ISSUE TITLE
Altminer.net support

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#1178]
I ran across this pool that seems to have significant amounts of hashpower and thus more consistent payouts for high difficulty algorithms (lux, bitcore, etc).   It's auto exchange, looks YIIMP,   if anyone can throw a pool file together, or give me hints on how to do it, I would like to get it going with MPM.

**Comment by grantemsley** [comment]
Is it auto exchange?  Doesn't look like it:

> we do payouts in the currency you mine

**Comment by mtbor** [comment]
Ah perhaps not, I saw the line about setting c=currency and figured it
was...  Oh well.  We can close this out.

**Comment by grantemsley** [comment]
It can still be added if people want it.  Support for per-currency wallets has been added to the master branch.

**Comment by UselessGuru** [comment]
I have put together a pool file for AltMiner.net. 

**Important**: AltMiner.net is not an auto exchange pool. **Do NOT mine to BTC addresses**. 
A separate wallet address per coin needs to be configured: 
Add a section similar to this (note the commas):
```
,
    "AltMiner": {
      "INN": "<INN_WALLET_ADDRESS>",
      "MGT": "<MGT_WALLET_ADDRESS>",
      "Worker": "$WorkerName"
    }
```
**Do NOT put BTC anywhere in the AltMiner section!**
Also read:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1105
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/438983b7926de401d90c1e0642d6ae5e08ca58fd

**Prerequisite**: A newer MPM build is required which usese config.txt for configuration details. (If you do not find this file in the MPM directory, then you need to update MPM first).

**Howto**:
- edit config.txt to define a wallet address for each coin you wish to mine
- put [AltMiner.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1698464/AltMiner.txt) in the 'Miners' folder, then rename to AltMiner.ps1
- restart MPM

**Comment by AndriiKravtsiv** [comment]
Hello,
The payout of LUX have been sent 100 min ago but I still haven't receive anything. Is it a known issue or is it something wrong in my case?
P.S. Sorry, if this is not an appropriate place for reporting this issue but I didn't know where to ask.
Thanks!

**Comment by UselessGuru** [comment]
> I didn't know where to ask.

Ask the pool operator.
MPM can support you if something is not working with launching the miner, but as soon as you see submitted hash rate being reported at the pool then all is fine from MPM's point of view.

**Comment by UselessGuru** [comment]
Pool is gone
https://bitcointalk.org/index.php?topic=3088934.0
