### ISSUE TITLE
Insufficient memory to continue the execution of the program

### ISSUE THREAD

**Issue by baker-travis** [MultiPoolMiner/MultiPoolMiner#1182]
This error happens in tandem with a warning that says "No Pools Available" even though my internet connection is alive and well. What is happening here? I've attached the logs.
[2018-02-04_22-55-43.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1695431/2018-02-04_22-55-43.txt)

**Comment by geocurt** [comment]
Having the same issue.  Miners seem to be working but the cmd window that tracks everything is straight errors.

**Comment by skulldeath420** [comment]
For me it´s the same!

**Comment by m-bosch** [comment]
Did you try to update your Powershell already?

**Comment by baker-travis** [comment]
I’m on 6.0.1. Downloaded the version linked in the README.

**Comment by m-bosch** [comment]
@baker-travis sorry, my mistake, I didn't read your logfile well. That is the correct version indeed. I use it also.

**Comment by aaronsace** [comment]
The latest release is definitely working.
