### ISSUE TITLE
What download link to use?

### ISSUE THREAD

**Issue by nickvasel** [MultiPoolMiner/MultiPoolMiner#1183]
I found 2 download links:
https://github.com/miningpoolhubstats/MultiPoolMiner/releases
and this one:
https://github.com/MultiPoolMiner/MultiPoolMiner/releases

Is anyone more updated?

**Comment by aaronsace** [comment]
We are the developers.

**Comment by nickvasel** [comment]
I understand and great job BTW...
Is the only difference between the 2 is one monitors and one doesn't?

**Comment by aaronsace** [comment]
Lots of people make amendments and fiddle the donation address. 

Our monitor works: https://multipoolminer.io/monitor/

**Comment by nickvasel** [comment]
Yes it works great! I don't think I'm making sense. what link should I be using to download the latest version is what I want to know.

**Comment by aaronsace** [comment]
Ours is the official one.

**Comment by nickvasel** [comment]
thank you...
