### ISSUE TITLE
mph not working shuts down, reset, blues screen etc

### ISSUE THREAD

**Issue by fusation** [MultiPoolMiner/MultiPoolMiner#1194]
[2018-02-08_18-53-56.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1705858/2018-02-08_18-53-56.txt)
I'm having problem trying to run the bat file each time I run it after 30mins my screen turns off then after awhile my pc restarts, I did a clean reinstall of windows 10 and still not working please need help

**Comment by UselessGuru** [comment]
MPM itself is most liekly not responsible for issues like this. 
I assume that one of the miners launched by MPM will either exhaust the power supply unit (-> restarts) or crashes the graphics driver (-> black screen).
Turn off overclock (memory and GPU) on all graphics cards. 
To investigate issues with the power supply reduce the power target of your graphics card(s).

**Comment by fusation** [comment]
sorry but i just did that and put gpu back to factory and it's working for a but still my windows firewall blocks the ccminer-x64 then shows the "crash blue screen", even though I had the firewall turned off, how do I stop it from crashing and how do I bypass the firewall even when it's turned off?

**Comment by UselessGuru** [comment]
> how do I stop it from crashing and how do I bypass the firewall even when it's turned off?

If a miner is crashing your system then please direct your question to the developer.
MPM is only finding the best paying miner/algo combination and then start the miner with the required parameters.

**Comment by fusation** [comment]
how do I direct this to the developer, don't they view these pages too?

**Comment by UselessGuru** [comment]
> how do I direct this to the developer, don't they view these pages too?

No, they won't. This is about MPM and not about any of the various Ccminer variants

**Comment by fusation** [comment]
@UselessGuru sorry but I don't understand where that "downloaded url" is, could I get a screenshot of what is and where to look for it. Thanks

**Comment by UselessGuru** [comment]
> Look at the download URL in the miner file.

What miner is causing it? -> Locate that miner file (either .ps1 or .txt) in the '[MPM]\Miners' folder -> View the contencts -> there is a line like '$Uri = https://github.com/KlausT/ccminer/releases/download/8.20/ccminer-820-cuda91-x64.zip'

-> goto to https://github.com/KlausT/ccminer to ask for help.

**Comment by m-bosch** [comment]
Think this can be closed if @fusation found the link and contacted KlausT for CCminer

**Comment by fusation** [comment]
Thanks, but sorry all of this was no help at all there is something wrong with the bat file or my machine because this only happens when the bat file suddenly closes and when relaunch the bat file errors show up as well as crash screen, blue screen, black screen, white screen, pc freezing etc even missing excavator folder.

But I have temporally fixed it, but it is a long process just to get the bat file to run without issues.

Thanks for trying to help me.

**Comment by aaronsace** [comment]
Ideas like this can spread so can I just make it 100% clear that MultiPoolMiner cannot in any way cause a BSOD or any other form of hardware failure. MultiPoolMiner runs solely within PowerShell and is not in anyway interacting with graphics hardware or performing any mining operations.

**Comment by fusation** [comment]
Hi


Thanks for getting back to me.

It seems like you really do like me so I will stop posting on github about my problems and if delete my account there. Just to make sure that I don't have to bother you again. So if I come to a problem and I can't figure it out I'll just delete MPM and find something else that I can use without problems.


Also about what I posted and what I emailed you about was just a problem that I was having and needed help to solve, so if you don't want to help me that's ok you don't need to respond I will eventually decide whether to stay and use MPM or find something else.


Thanks for the help and advice, I'll try my best for to post anymore thing up on github.


________________________________

**Comment by aaronsace** [comment]
@fusation This isn't a platform to make friends; either your issue is solved or not.
