### ISSUE TITLE
Opencl and CPU mining

### ISSUE THREAD

**Issue by erickfung** [MultiPoolMiner/MultiPoolMiner#1195]
I'm newbie here. 
I am wondering whether it is a must to have OpenCL on my PC when there is no GPU but CPU only.

**Comment by UselessGuru** [comment]
> I am wondering whether it is a must to have OpenCL 

Yes, it is a must. Some miners require the presence of OpenGL libraries on your system.
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/862
