### ISSUE TITLE
Suggestion: More reliable benchmark results

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1196]
As default the benchmarking (as far as I know and see) will take 60 seconds up till 3x 60 seconds per miner. Many miners, like Bminer will increase on speed / results during the way. Wont it be better (like NiceHash) to do benchmarking on a scale of 300sec. /5 minutes?

This way the benchmark results will be more Reliable.

**Comment by UselessGuru** [comment]
> Wont it be better (like NiceHash) to do benchmarking on a scale of 300sec. /5 minutes?

That would make benchmarking very slow. Furthermore it is not necessary because MPM constantly updates the hash rate stored in the benchmark file on every run.

**Comment by m-bosch** [comment]
@UselessGuru True, it would take longer, but as far as I know is it only 1 time (the first time).

The updated hash rate counts only for the miners that will be used right? so for example the second best won't be activated until the first on will have a lower rate during activity. In my opinion the runner-up could be better way before that time but won't be re-benchmarked or re-activated right?

Or am I wrong and do you mean something else with 'every run'?

possibility 2: every week/month a re-benchmarking to check if the best results are still the best results?

**Comment by UselessGuru** [comment]
> but as far as I know is it only 1 time (the first time).

Yes, but if you have lots of miners and algos then you may well benchmark for several hours. This does IMHO not compensate for the little benchmark differences. From a profitability point of view it makes much more sense to focus on optimal OC & voltage settings.

> Or am I wrong and do you mean something else with 'every run'?

No, you are right.

**Comment by aaronsace** [comment]
There is no actual benchmark as such; just continuous running stats. When getting the first reading, it waits for a less than 5% variance then takes the highest figure to be safe.

**Comment by m-bosch** [comment]
Ok thanks for the explanation. 

Never the less I think that a low benchmark can resolve in a case that a specific miner doesn't start for a specific algorithm while this could be very profitable. 

I know, can't do everything at one time. but please think about a case that could be better. I would try to do the same.

**Comment by korishan** [comment]
From what I gather, the benchmark that MPM does is really to see what algo's actually work on your system. If an algo/miner doesn't work, (ie crashes, no response, 0H/s in elapsed time, etc), then MPM will not use that algo/miner. There'd be no point.

Am i correct in this thinking?

So, with that said (if the above is true) and to go along with UselessGuru mentioned in 1st reply, the benchmark files are updated on a regular basis. No need to re-run the benchmark when you have "real-world" numbers to go by. If you benchmark and get 30H/s, but the real-world is showing only 18H/s (or vice-versa), then the benchmark is off for some reason. It's constantly adjusted over the course of running.

**Comment by m-bosch** [comment]
@korishan i understand. but like I tried to say/ask is: it only updates the miners that you are using, and those are the ones with the best benchmarks. This way the poor benchmarks won't be adjusted.

**Comment by aaronsace** [comment]
@m-bosch Are you actually finding that to be the case as it's storing the highest value initially to be safe?

**Comment by gak45** [comment]
I always use -interval 300 for benching and running. Yes it takes longer... but I dont do every alog on a pool. So its done in a couple hours. IMHO its worth the wait - as its the ONLY way to get X17 stats that MPM wont puke out on due to 'variability'.

**Comment by aaronsace** [comment]
I'm not going to increase the interval but I'm going to rework this a little for all the miners.

**Comment by m-bosch** [comment]
Thanks @aaronsace, maybe the interval doesn't have to be increased. Im just curious. what happens with the miners that don't work, they don't get a chance to re-bench, also for the ones on the watchdog-kill

**Comment by kiLLeen** [comment]
Probably makes sense to do something along the lines of x% change over y time for benchmarking. Similar to what someone else said earlier, my initial benchmark of x17 is half what my average is with Alexis and Palgin. Thanks for all the hard work!

**Comment by kiLLeen** [comment]
Oh and when I say x% over y time, I meant relative to the last hashrate snapshot.

**Comment by UselessGuru** [comment]
> m just curious. what happens with the miners that don't work, they don't get a chance to re-bench, 
No, if they fail 3x (one attempt is 3x interval) time they get disabled (0 hash rate benchmark file in 'Stats' folder) and stay disabled until you delete the stat file

> also for the ones on the watchdog-kill
From readme: 'Watchdog timers reset after three times the number of seconds it takes to get to stage 3.'
If you cannot wait: restart MPM. Watchdog is a memory only thing and gets cleared on MPM restarts.

**Comment by UselessGuru** [comment]
Latest MPM versions provide better results due to the implemented code optimizations.
Also see https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1682
