### ISSUE TITLE
Suggestion: Filter out miners with way lower results

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1197]
Hi There, won't it be possible to eliminate all miners of a type of algo's except the 2 best according to the benchmark? this way the script won't load and walk through that many every time.

in my example it would be great if I only have like 2 miners for equihash, 2 for ethhash etc.

<img width="478" alt="schermafbeelding 2018-02-08 om 18 17 32" src="https://user-images.githubusercontent.com/16580113/35987580-5eff8704-0cfc-11e8-89c2-dfaa1d7ea1c0.png">

edit 1: I know I can exclude miners manually but some miners will do like 5/6 different algo's. I can manually edit that miner file to exclude that also, but thats a lot of manual editing every update...

**Comment by robl45** [comment]
What happens if those two miners go down, get caught by watchdog etc?  Will it bring back the others?

**Comment by m-bosch** [comment]
@robl45 good points, thats why it has to exclude it without deleting it. this way they are just hidden.

@aaronsace / @UselessGuru what happens with miners caught by the watchdog. do they ever return?

**Comment by UselessGuru** [comment]
> what happens with miners caught by the watchdog. do they ever return?

I assume this question is not directly related to this issue.
Yes, when you restart MPM or when 'Watchdog timers reset after three times the number of seconds it takes to get to stage 3.'

**Comment by UselessGuru** [comment]
See https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1711
