### ISSUE TITLE
Pool ItalYiiMP unavailable

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1198]
From the release version up to now (weekly updating the version with the master) I continuously get: 

```WARNING: Pool API (ItalYiiMP) has failed.```

After that I remove this pool from the pools directory to ignore this error.

Also I don't use this pool so it won't effect the work of MPM for me.

nevertheless I think it will have issues for other users.

**Comment by UselessGuru** [comment]
The pool is down. Deleting the pool file like you have done is the best solution.

**Comment by m-bosch** [comment]
Maybe exclude it from the upcoming version and add it later on when it is available again?

**Comment by aaronsace** [comment]
Best remove this pool as it's awful.

**Comment by UselessGuru** [comment]
@aaronsace 

What about an optional DL area where we can provide 'non-default' miners & pools?

**Comment by m-bosch** [comment]
defaults and opt-in's, sounds good.

**Comment by tboy1337** [comment]
Italyiimp is a scam guys, the guy made a version 2 after yiimp hack, then did exit scam, came back for a bit with a version 3 and then went again, don't add this pool again is my advice, the guy still owes me money.
