### ISSUE TITLE
CCminerKlaust-logfile has weird sign

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1200]
Hi there,

i was looking around in my logs because of many solutions/issues are referring to that and it shows great  information but:

in the ccminerklaust log is a weird sign what makes a block in the log on a regular txt editor but something like ```notepad++``` gives me the ```esc``` block.

<img width="844" alt="schermafbeelding 2018-02-08 om 19 58 01" src="https://user-images.githubusercontent.com/16580113/35992372-68217b4a-0d0a-11e8-80ed-612704573e6a.png">

<img width="787" alt="schermafbeelding 2018-02-08 om 19 58 40" src="https://user-images.githubusercontent.com/16580113/35992411-7fd523d6-0d0a-11e8-85d9-ac2c075fb33a.png">

I think (99% certain) this won't effect anything but I don't think it should be there right?

**Comment by aaronsace** [comment]
I noticed that and thought it was bit odd but it's what ccminer is sending to the console window.
