### ISSUE TITLE
Claymore Dual Miner v11.0 available / Feedback welcome

### ISSUE THREAD

**Issue by jestercore** [MultiPoolMiner/MultiPoolMiner#1202]
It's has so much new features, even new coins in dual!

**Comment by m-bosch** [comment]
@jestercore could you tell me what the advantages are?

I use NVIDIA cards and never used dual miner before. 

I do see a claymore miner in the total list though.

**Comment by m-bosch** [comment]
My 1070GTX cards prefer equihash most of the times. 

For ETH my order is miners is as followed:

- phoenixminernvidia
- ethminernvidia
- eminer
- prospector


as you can see claymore isn't even in my list

**Comment by jestercore** [comment]
1070 GPU's have powerful core, so nothing special. I'm mining with 2 1060 with overclocked (+375/+800) memory. 

Remove logs/benchmarks/profit stats with batch files and retest.

**Comment by m-bosch** [comment]
Wow +375 is a big difference with my overclocking. what your power? 110% or what? im curious.

**Comment by jestercore** [comment]
We are offtopic so much. I'm using 90% power limit, to extend GPU and cooler fans reliability.

**Comment by m-bosch** [comment]
Yes we are but can't ask it elsewhere to you :-).

But if it is not in beta/alpha, please add the new version of the miner in the new mpm version.

**Comment by jestercore** [comment]
It's released, and it's awesome.

https://bitcointalk.org/index.php?topic=1433925.0

**Comment by m-bosch** [comment]
@jestercore is it default on dual mining in MPM by the way?

I resette the stuff you told me and now he is back in the list.

-offtopic: btw my system crashes with that many + on core.

**Comment by jestercore** [comment]
@m-bosch +375 it's memory overclock on 1 GPU, and +800 memory overclock on 2 GPU. Sorry for unclearness.

**Comment by UselessGuru** [comment]
I am working on it...

**Comment by jestercore** [comment]
At least MPH+Nicehash ETH+Keccak dual benchmarking and mining working for me with 580. But we need to check lower dcri like 10, because there is significant ETH mining speed recution.
![benchkeccak](https://user-images.githubusercontent.com/33821148/36062862-386cc492-0ea7-11e8-8fd8-a0516224ae62.png)

**Comment by jestercore** [comment]
So, yea, i've checked -dcri 5 and -dcri 10, and it's SO better. Set 5, 10, and 15 to release, please.
![benchkeccak](https://user-images.githubusercontent.com/33821148/36063039-4b2ee008-0eaa-11e8-8291-c8177f9bfa87.png)
[ClaymoreAmdKeccak15.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1713470/ClaymoreAmdKeccak15.txt)
[ClaymoreAmdKeccak5.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1713471/ClaymoreAmdKeccak5.txt)
[ClaymoreAmdKeccak10.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1713472/ClaymoreAmdKeccak10.txt)



Take it <3

**Comment by m-bosch** [comment]
@jestercore how can I contact you e.g. twitter to talk about this and advice?

**Comment by UselessGuru** [comment]
More tuning options (incl. automatic fine tuning) will be added in a later release.

@ jesstercore: 

> MPH+Nicehash ETH+Keccak dual benchmarking and mining working for me with 580. But we need to check lower dcri like 15,10,5 

This may be true for slower cards, for higher cards the existing dcri values may even be too small :-)

**Comment by jestercore** [comment]
@uselessguru

Oh, sorry, forgot to mention, i have 1366mhz core, pretty average for 580, so this should be accurate result.

**Comment by UselessGuru** [comment]
Implemented in https://github.com/MultiPoolMiner/MultiPoolMiner/commit/a243bbd024f1270eb7f11b2abdc606fbfe20e541
