### ISSUE TITLE
Blazepool.ps1 ready for testing

### ISSUE THREAD

**Issue by gak45** [MultiPoolMiner/MultiPoolMiner#1203]
Any chance of adding http://blazepool.com/ to the pools (and removing Italyiimp)? Nemosminer already supports it... its just I rather use MPM - the watchdog option really is peace of mind!

**Comment by robl45** [comment]
Hi you can try this.

I don't know if it will work on this version, but it appears to be working on the useless guru version.



[Blazepool.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1711670/Blazepool.zip)

**Comment by gak45** [comment]
Thanks! For the latest release (non-master) just had to remove the # in front $PayoutCurrency = "BTC" to make it work. :)

**Comment by robl45** [comment]
Try this one, Host name was not quite correct in the first one.  It works but didn't add the algorithm at the beginning of the server name.

[New Compressed (zipped) Folder.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1712429/New.Compressed.zipped.Folder.zip)

**Comment by gak45** [comment]
Do you happen to have one for Ahashpool as well? Like the new minus fee calculation option you have in the ps1 file. :)

**Comment by robl45** [comment]
All I did was edit the zergpool file I had, I just know enough to be dangerous with this stuff :)  However I believe the calculation you are talking about will only work in the uselessguru version of multipool miner.  Someone else could confirm that.  The pool files in the useless guru version would have what you are looking for but I don't think they will do what you want in the main version.

**Comment by UselessGuru** [comment]
Coming soon...

**Comment by slovke** [comment]
I tested blazepool on my 1080 Ti rigs with Multipoolminer and i can confirm that all is working good and switching as it should. So for me its a go

**Comment by UselessGuru** [comment]
BlazePool is released:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/40a07b2a6d479232af3827ee57289a4ce3dd58c9
