### ISSUE TITLE
Multiple miners running simultaneously

### ISSUE THREAD

**Issue by korishan** [MultiPoolMiner/MultiPoolMiner#1204]
Ok, so I've downloaded the latest build (got it from grantemsley) and I started it fresh. I tried to merge with my existing copy, but there's way to many differences between them and I get a lot of red text in the PS console. So I let it run benchmark and do all sorts of configuring on it's own.

A few issues:
1) noticed in the MPM readme it shows:
>README.txt - updated on 29/01/2018 (dd/mm/yyyy) - v1.22.11
It was apparently written in the future  :P   Now, I know the version number doesn't match the current latest, but I think grantemsley version is a copy of the latest(?)
2) I'm having several miners running on the same hardware. I mean, several on CPU and several on the same GPU.
![image](https://user-images.githubusercontent.com/25021176/36031657-7e3955f0-0d79-11e8-8f39-98a653ab00b5.png)
The above image only shows currently several on CPU. But I've had several show up on GPU as well. This rig only has 1 GPU installed.

Any idea what's going on here? What should I collect together to show extra information to you guys?

**Comment by korishan** [comment]
Just realized that the same miner script was running on all those CPU listings. I wish I had the screenshot where they were different. I'll keep an eye on it and hopefully grab a shot of them. At one time I had 2 different miners on GPU and I think 2 or 3 on the CPU yesterday. I even had to go into Taskmanager and force close sgminer manually because MPM lost connection with it or something. When I closed MPM, the sgminer stayed loaded for several minutes afterwards (I only realized it was still loaded because my system was still acting oddly while I was watching a video and decided to check TM to see what was loaded and saw a heavy GPU activity even after MPM was closed)

**Comment by korishan** [comment]
Here we go, multiple GPU miners:
![image](https://user-images.githubusercontent.com/25021176/36048310-c951d5de-0dac-11e8-9954-fff7c2f615f0.png)

**Comment by m-bosch** [comment]
@korishan as far as I can see only 1 is active so the others are 'idle'?

I know the all are in the status running...well none has a current speed as-well, so sorry I don't get it.

**Comment by korishan** [comment]
that's the other thing, i hardly get any Current Speed listings, but I'll get coins on MPH. Strange

**Comment by aaronsace** [comment]
@korishan Best uploading the log files.

**Comment by korishan** [comment]
Here's a copy of the logs file:
https://drive.google.com/open?id=1BRlE8xro72ePl-QXCa18aS39BVTOynCf

**Comment by korishan** [comment]
![image](https://user-images.githubusercontent.com/25021176/36054867-9f456264-0dc6-11e8-967f-af707f153c0c.png)

**Comment by korishan** [comment]
The MPM page is showing correctly (I recently reloaded the MPM), but I noticed TM now shows 2 sgminers running on the GPU:

![image](https://user-images.githubusercontent.com/25021176/36057980-b9b99340-0de4-11e8-9151-02db3d3573fb.png)

**Comment by korishan** [comment]
Then a few minutes later:
![image](https://user-images.githubusercontent.com/25021176/36058014-a00be122-0de5-11e8-9d0e-cbe421598df9.png)
  ??????  What's going on here? Anything I can change in my settings to see if it makes any difference?

**Comment by grantemsley** [comment]
Try increasing the delay setting, and/or disabling CPU mining, and see if that helps.
