### ISSUE TITLE
Several pwsh.exe & Console Window Host in TaskMan

### ISSUE THREAD

**Issue by korishan** [MultiPoolMiner/MultiPoolMiner#1205]
Just curious, why are there several pwsh.exe and CWH processes running? We can only see 1 command window and that has the MPM statuses displayed.
Or is this how you get the windows to not be displayed but hidden?

![image](https://user-images.githubusercontent.com/25021176/36055080-e83e540c-0dc7-11e8-8e58-82c883b7f427.png)

**Comment by aaronsace** [comment]
The miners are running inside PowerShell processes and the PowerShell processes are sub-processes of the main program. So you can now see the total usage of the whole program together and nothing should be able to decouple from the main process.

**Comment by korishan** [comment]
ahhh, ok.  Which makes it easier to kill all sub processes when you close the main program.  Nice.
But why so many? I have 2 miners loaded (I just restarted it, so only 2 this time) but there are 3 CWH and 3 PWSH running (assuming these two are tied together, actually).

**Comment by UselessGuru** [comment]
> But why so many?

One for each process.
Apart from the running miner processes there is also the 'updater/downloader' as well as the 'firewall opener' process.
If you want to learn more then look for all the Start-Process commandlets in the code.
