### ISSUE TITLE
Claymore miner excluded

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1207]
It looks like claymore miner had an error and watchdog disabled it. How can I check this and if needed re-enabled this?

**Comment by UselessGuru** [comment]
> watchdog disabled it

If watchdog disabled it then you will need to restart MPM or just wait  until 'Watchdog timers reset after three times the number of seconds it takes to get to stage 3.'

> if needed re-enabled this?
If MPM set the hash rate to 0 in the Stats file (this is NOT watchdog) then you will need to delete the stats file to revive the miner/algo conbination.

**Comment by m-bosch** [comment]
I removed te stats file, restarted mpm and indeed its back thanks
