### ISSUE TITLE
Benchmarks all Zero except Claymore

### ISSUE THREAD

**Issue by darkstonexa** [MultiPoolMiner/MultiPoolMiner#1208]
Just downloaded latest Master Build, 
all Benchmarks except for Claymore dual mine Keccak and blake2s are coming back with Zero Speed in the stats files even though the pools are  registering that I have submitted valid shares.

Single 1060 6Gb card being benchmarked

**Comment by patq911** [comment]
Just came here to report the same actually. According to the multipoolminer log things are being benchmarked and succeeding but it's not being reported to multipoolminer.

[MultiPoolMiner-2018-02-10.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1713745/MultiPoolMiner-2018-02-10.txt)
