### ISSUE TITLE
MPM randomly stops mining to selected pools and uses pools within -excludepoolname list

### ISSUE THREAD

**Issue by xactr** [MultiPoolMiner/MultiPoolMiner#1209]
Tested Scenario - need some advice please
I wish to only use these pools: -poolname miningpoolhub,miningpoolhubcoins,nicehash
I do not wish to use these pools: -excludepoolname zpool,hashrefinery,ahashpool,blockmunch,italyiimp

This works solidly for a number of hours... then...

I find that randomly after a few hours of mining that excluded pools are being used and now have coins scattered on zpool, hashrefinery, etc

Without deleting the pool.ps1 files as some suggest, how can I make the -excludepoolname switch work as expected? Many thanks!

**Comment by aaronsace** [comment]
Logs please.

**Comment by xactr** [comment]
Log sample showing period of mining on preferred pools (correct) and then the random switch to pools that have been included with the -excludepoolname switch.
[SAMPLE_2018-02-11_09-46-33.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1713933/SAMPLE_2018-02-11_09-46-33.txt)

**Comment by UselessGuru** [comment]
The same happened with me. It is caused when donation kicks in:
- $Config.Pools gets filled with all available pools
- MPM mines for $Config.Donation to donation address @ any pool
- When danation ends $Config.Pools will be reduced to configured pools (excludedpoolnames will be filtered again)
so far all OK, but now the trouble starts:
Even though only selected pools are in $Config.Pools, miners for all other pools remain available.

-> Need to remove all miners on now defunct pools.

**Comment by xactr** [comment]
Thankyou for the quick turnaround; I have tested as well and this now looks to be fully working. Thanks!
