### ISSUE TITLE
Intial accuracy 0% on new pools

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1210]
While testing the new BlazePool.ps1 pool file I noticed that the initial accuracy is 0% and it takes ages until it reaches an acceptable value.

[BlazePool.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1714476/BlazePool.zip)

This was introduced with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/0e69c0ca7c28eb42f7a4ebe0af2bc66a782d1834#diff-cd61247de8e495a05e4fad61fa55fe8c

**Comment by aaronsace** [comment]
That's how the stats are currently set to work but it means that the pools without 24 stats have an initial advantage so I've now flipped it: 44898df7b7cd367025af8b72723d819bae4217ad
