### ISSUE TITLE
Integer underflow

### ISSUE THREAD

**Issue by G510Gamer** [MultiPoolMiner/MultiPoolMiner#1211]
nothing serious. just an active timer somehow got underflowed, still works just a minor bug
![capture](https://user-images.githubusercontent.com/17520437/36080568-fab7c2ce-0fe5-11e8-96c2-1ef8ec2271a6.PNG)

**Comment by aaronsace** [comment]
What version are you running?

**Comment by G510Gamer** [comment]
V2.7.1.4

**Comment by aaronsace** [comment]
Cheers; should be fixed in 2.7.2.
