### ISSUE TITLE
Pre-Release 2.7.2: Process priority for miner binaries wrong

### ISSUE THREAD

**Issue by boro2000** [MultiPoolMiner/MultiPoolMiner#1213]
All miner binaries (zm.exe, ccminer.exe ..) are being launched with maximum Process-Priority "Normal", even if a higher Process-Priority is set in Include.psm1 / Method StartMining.

**Comment by aaronsace** [comment]
3c0c64bf76a42c4da48ad29720ee6b0d7c6630e1
