### ISSUE TITLE
Warning:Pool Price are out of sync

### ISSUE THREAD

**Issue by BobTheTool** [MultiPoolMiner/MultiPoolMiner#1216]
Hi, i have the error Price out of sync every time i open the 2.7.2 version. 
That's annoying because the miner keep the same miner because there is no fluctuation in profitability with MPH. I'm stuck with equihash all the time.
Thanks

**Comment by aaronsace** [comment]
The pool prices being out of sync is not causing it to mine Equihash all the time. 

If you mix MiningPoolHub with other pools then the prices will go out of sync due to a limitation in MiningPoolHub's API. MultiPoolMiner copes with it and continues to make decisive switches.

**Comment by dlrookie86** [comment]
Do you have a workaround to resolve the "problem"? I use only miningpoolhub and i have the same problem.

**Comment by angelics** [comment]
my idea was to make interval time independent with pool. 
create interval time in pool.ps. 60s default interval + pool.interval = proper interval api refresh rate.

**Comment by m-bosch** [comment]
I only have miningpoolhub as pool and will get the same problem:

```WARNING: Pool prices are out of sync```

I see that some accuracy's drop and de earning rise of some alto's.

This causes many switches to unreliable algo's/accuracy.

**Comment by aaronsace** [comment]
@m-bosch I'll check it this evening but can you upload the logs for reference.

**Comment by m-bosch** [comment]
@aaronsace sure,

[MultiPoolMiner_2018_02_13.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1719175/MultiPoolMiner_2018_02_13.txt)

**Comment by aaronsace** [comment]
Sorry, can you post the other log as well.
(The one with the screen output that lists the pools and miners etc. )

**Comment by m-bosch** [comment]
Where should this be listed? in the logs directory are logs from each miner and the multipoolminer log like I posted.

**Comment by aaronsace** [comment]
`MultiPoolMiner_yyyy-MM-dd_HH-mm-ss.txt`

**Comment by m-bosch** [comment]
hi @aaronsace,

MPM didn't create a file for that today but in the one from yesterday it should work as-well.

[MultiPoolMiner_2018-02-12_17-43-17.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1720260/MultiPoolMiner_2018-02-12_17-43-17.txt)

**Comment by dlrookie86** [comment]
[MultiPoolMiner_2018-02-13_04-46-57.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1720850/MultiPoolMiner_2018-02-13_04-46-57.txt)
[MultiPoolMiner_2018-02-13_04-16-54.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1720851/MultiPoolMiner_2018-02-13_04-16-54.txt)
That's my logs for the bug.

**Comment by BobTheTool** [comment]
Did this problem affect the efficiency of switching between algorithms ? I want to know because i continue to use the pre release version and don't know yet if i need to continue to mine with "warning : Price are out of sync"
Thanks Aaron for your work

**Comment by aaronsace** [comment]
@BobTheTool I'm looking into it.

**Comment by BobTheTool** [comment]
@aaronsace Thanks, I have another issue, excavator not working when it was working with 2.7.1.4

**Comment by m-bosch** [comment]
@BobTheTool correct, noticed also, buit thought it was already an issue.



@aaronsace because of the price out of sync my miners swap a lot (see times launched and time).

<img width="608" alt="schermafbeelding 2018-02-13 om 21 32 24" src="https://user-images.githubusercontent.com/16580113/36172206-6cf221b6-1105-11e8-8fd8-26a5e8cf09b1.png">

**Comment by aaronsace** [comment]
You will still see it sometimes if mixing MiningPoolHub with other pools but it should now be working correctly when running MiningPoolHub only. 

9aff1e7b326a3b49e60b5392197ec3e33ed18fc9

**Comment by m-bosch** [comment]
@aaronsace thanks, I will wait for the 2.7.2.1 version where this commit will be included. thanks.

but the way: I only use MPH

**Comment by diown** [comment]
I am using the latest miner from today and using Miningpoolhub only, but I am also getting WARNING: Pool prices are out of sync. a lot
[MultiPoolMiner_2018-02-14.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1724468/MultiPoolMiner_2018-02-14.txt)

**Comment by platinumdubs** [comment]
i am still currently receiving this message from startup

**Comment by BobTheTool** [comment]
me too...i can't use the miner because the pool price didn't actualize. I returned to awesome miner :(

**Comment by aaronsace** [comment]
Guys, warnings are not errors. It just means MultiPoolMiner is not hiding information from you. If you only select one pool in the bat file then this warning will get displayed a lot less.

**Comment by platinumdubs** [comment]
my bad i wasnt implying that there was an error just making mention that i am also getting the error and i just downloaded MPM last night. still benchmarking tho

**Comment by BobTheTool** [comment]
I thought yes but i experienced a lot less switching and the price didn't actualize as much (or null during all the night) as in the 2.7.1.4. The warning comes at every refresh.
I think in your developper side you don't have the same effect as we experienced.
I have also only miningpoolhub and also exclude other pool. I don't know how to get rid of that.

**Comment by aaronsace** [comment]
MiningPoolHub uses Cloudflare so you need to wait 30 minutes for anything to change. It doesn't compare out of sync prices but it always displays and uses the actual figures being reported by the pools. 

I'll check it again this evening.

**Comment by cyrus104** [comment]
I wanted to see if was resolved, I'm only using miningpoolhub but I keep getting pool prices are out of sync AND zpool pool api has failed. 

Not sure why zpool pool api is even active with just miningpoolhub active.

**Comment by aaronsace** [comment]
@cyrus104 Please post a new issue with logs if you think there is a bug.

**Comment by r0dn0r** [comment]
Could the cause of the "WARNING: Pool prices are out of sync" be that the Pool API's are reporting 0 profit for some coins and MPM is filtering that and doesn't update the "Updated" date in the pool stat file?
This seems to be happening for Electroneum on MiningPoolHubCoins and Blake256r8vnl on Nicehash and a few others.
