### ISSUE TITLE
LTC payouts

### ISSUE THREAD

**Issue by romajc84** [MultiPoolMiner/MultiPoolMiner#1218]
From reading the faq I am a bit confused.

Do I just add "-Passwordcurrency LTC" to the start.bat files or am I supposed to go into another file and change the payout coin?

**Comment by UselessGuru** [comment]
> Do I just add "-Passwordcurrency LTC" to the start.bat files or am I supposed to go into another file and change the payout coin?

Nope, it does not work like this.
First of all only a few pools allow payout in another coin than BTC.
[Read this](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1178) to get an idea.
To find out which pool supports payouts in non-BTC it might be helpful to download [grantemsleys setup GUI](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1187)

**Comment by aaronsace** [comment]
Put this in the config file instead of BTC: 
```
    "Zpool": {
      "LTC": "EnTeRlTcWaLlEt",
      "Worker": "$WorkerName"
    }
```
