### ISSUE TITLE
Bminer mine 50% of the time to aaronsace pool

### ISSUE THREAD

**Issue by BobTheTool** [MultiPoolMiner/MultiPoolMiner#1220]
I have a strange issue that occurred this night. Multipool miner constantly switch in dev fee and bminer is always mining on aaron pool.
Thanks

**Comment by aaronsace** [comment]
Which version are you using? 
Have you paused MultiPoolMiner? 
Please can you post the logs to your post?

**Comment by BobTheTool** [comment]
Hi, 
i'm using the 2.7.2. I don't know how to pause the miner so i don't do that. 
Here is the log 
[MultiPoolMiner_2018-02-13.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1719878/MultiPoolMiner_2018-02-13.txt)

**Comment by aaronsace** [comment]
Sorry, can you post the other log as well.

**Comment by aaronsace** [comment]
This one: 
`MultiPoolMiner_yyyy-MM-dd_HH-mm-ss.txt`

**Comment by aaronsace** [comment]
aa4f639c4a79e1b7e2b54b5325b84bfd5017ea19
