### ISSUE TITLE
Unwanted pools detected

### ISSUE THREAD

**Issue by Ragnar3k** [MultiPoolMiner/MultiPoolMiner#1222]
After I downloaded and launched MPM 2.7.2 I got strange lines in logs that says I'm working on other pools except MiningPoolHub. I am registered only on MPH, not on AHashPool, or Zpool. Loosing profit as a result.
Here is the log of my miner. Up until line 4740 everything was fine. From line 4740 Zpool has appeared. From line 15508 AHashPool appeared as well. At line 42540 it started to mine on AHashPool.
[MultiPoolMiner_2018-02-13_12-13-03.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1720900/MultiPoolMiner_2018-02-13_12-13-03.txt)
My running config is here: 
[start MPH.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1720927/start.MPH.txt)
Major parts of that config came from previous versions. Never had such kind of issues before with older versions.
Am I doing something wrong, or is this a bug?

**Comment by UselessGuru** [comment]
> Am I doing something wrong, or is this a bug?

No, all is fine. MPM is on it's donation run - look at the BTC address :-)
Just make sure you have https://github.com/MultiPoolMiner/MultiPoolMiner/commit/100de942d3fffc619d60c628a5c58e12e887c096 installed.

If you are happy with the solution then please close the thread. TIA!

**Comment by Ragnar3k** [comment]
Yes, when it's on donation run, it runs on BTC address, but never had other pools, except Miningpoolhub in profitability calculator. Thing is, it becomes most profitable sometime, and ofc switches to it. 
Line 42590 in file above:

> Bin\NVIDIA-TPruvot\ccminer-x64.exe -a lyra2v2 -o stratum+tcp://lyra2v2.mine.ahashpool.com:4533 -u  -p rig,c=BTC --submit-stale

Never seen "rig" workername as a donation rig.
 100de94 is installed

**Comment by UselessGuru** [comment]
> Never seen "rig" workername as a donation rig.

True, there is something fishy going on. But from the contents of the log I can only guess what is happening.

For some unknow reason i appears as if not all donation pool & miner info is properly removed from the list of available objects ($Pools and $Miners) when the donation period ends.

I think this is an issue for master aaron - I am out of luck here.

**Comment by UselessGuru** [comment]
Just saw this commit: https://github.com/MultiPoolMiner/MultiPoolMiner/commit/3acef2fc5aacab18f671f4200f9b679e05273c6d

Maybe this fixes your issue.

**Comment by aaronsace** [comment]
I'm think #1220 is related to this.

**Comment by aaronsace** [comment]
aa4f639c4a79e1b7e2b54b5325b84bfd5017ea19
