### ISSUE TITLE
full V2.7.2

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1225]
Hi All,

im very happy with MPM and using it as much as possible. the pre-release of 2.7.2 had some issues according to the commits and issues the last few days.

I know @aaronsace and the team working hard every day at this project but can you give me an update when you expect to release the 2.7.2?

**Comment by titvs** [comment]
Im with @m-bosch but waiting for release 2.7.3 which i  hope will include a miner monitor window... Using a pre-"miners as jobs" commit for the time being since its easier to monitor and kill the window of a problematic miner.

**Comment by m-bosch** [comment]
@titvs there are more then discussions enough about the window issue. I think @aaronsace and the team explained why they choose this way,

I will follow them in that, there are many ways to see these logs. 

Just a change of mindset and way to work.

**Comment by Sledgemoto** [comment]
I have to say the non-window mode has stabilized my mixed rig. absolutely zero crashes/restarts since I've been using it.

**Comment by titvs** [comment]
Ive already said that the development is heading to a nice future. Having a log per miner is great imo.
I'll give it a try after a few commits and with Notepad++ ;P

**Comment by aaronsace** [comment]
v2.7.2.1 will be released soon as the bugs have been fixed and marked as final. 
Probably a day or two. 

Thank you for the support.
