### ISSUE TITLE
Question about Nicehash pool

### ISSUE THREAD

**Issue by cmbconcretefire** [MultiPoolMiner/MultiPoolMiner#1228]
Can someone explain to me how the nicehash pool works in regards to MPM? With every other pool known (to me), it's pretty simple. You point your rig to that pool, mine X coin or X algo and meet the minimum payout and get paid. 

But Nicehash has it's own miner. And technically, you're not mining but someone is paying you to mine. Sorta. 

So yeah, how does using a Nicehash pool work? Do they still take out fees for using their pool? Etc...

**Comment by UselessGuru** [comment]
> But Nicehash has it's own miner

What are you trying to say?

> So yeah, how does using a Nicehash pool work?

Exactly the same as any other pool. You point your rig to that pool, mine X coin or X algo and meet the minimum payout and get paid. 
Or in my own words: You submit shares and get credited for them in BTC :-)

> Do they still take out fees for using their pool?
 
Yes, they take fees, how much depends on the type of wallet (internal or external).

Another difference. NH is PPS whereas most other pools are PPLNS. Google and you will learn ( a full explanation on this subject is beyond this thread)
With PPS you will get paid immediately for every share you submit, and to my experience projected payout with NH is much closer to reality than with any other pools (approx 90% compared with other pools where I get maybe 60%)

**Comment by cmbconcretefire** [comment]
@UselessGuru , I wasn't trying to say anything negative if that's what you were thinking. To make an analogy, I think of all pools as sort of "Microsofts." It is what its. Where as Nicehash is like "Apple." They do things a bit differently (from what I have read.) 

So, I was just trying to get a little clarification of pointing MPM to their pool. That's all. So, if I have this correct, I just plug in their internal wallet addy but use MPM to mine from them / to them....and all of their other normal rules apply? Fees, payout schedules, etc?

**Comment by aaronsace** [comment]
@cmbconcretefire If you use the internal wallet, make sure you enter it inside the config file and not the command line.

**Comment by cmbconcretefire** [comment]
@aaronsace , roger that. Thanks. Wait, what? Config file I understand. Not sure how the .bat file should look. Example? Please?

**Comment by UselessGuru** [comment]
> Not sure how the .bat file should look. Example? Please?

NOT in start.bat.
Edit config.txt, look for 'Nicehash' and replace $Wallet with your internal NiceHash address:

```
    "NiceHash": {
      "BTC": "<INTERNAL_NICEHASH_ADDRESS>",
      "Worker": "$WorkerName"
    },
```

**Comment by cmbconcretefire** [comment]
Thanks.
