### ISSUE TITLE
"Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null." + more.

### ISSUE THREAD

**Issue by awdtalon92** [MultiPoolMiner/MultiPoolMiner#1230]
Keep getting this error in RED letters repeatedly on the screen, for about 10 seconds, then finally diplays in yellow: **WARNING: Pool prices are out of sync.** then it goes away, goes back to displaying stats and around 60 seconds later it happens again, this cycle continues repeatedly.  It happened during benchmark, and after the benchmark was done.  

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\CryptoCoins\MultiPoolMinerV2.7.2\MultiPoolMiner.ps1:244 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Ideas on what this is, and how to correct?

**Comment by awdtalon92** [comment]
Trying to attach a recent log, but it is 400MB in size from only 24 hours! The error just keeps repeating.  I'm attaching the log from the first run, where benchmark just started to take place.
[MultiPoolMiner_2018-02-12_23-42-47.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1722657/MultiPoolMiner_2018-02-12_23-42-47.txt)

**Comment by awdtalon92** [comment]
Downloaded v2.7.1.4 instead of v2.7.2, no issue so far.  Allowing to tun for 24 hours.

**Comment by UselessGuru** [comment]
@awdtalon92 

Line 244 is where MPM reads the pool information.
I appears that a pool file is broken. Pool files are compatible between MPM versions.

Could you please try 2.7.2 again, and then remove ONE pool file, run MPM, if the error goes away then we have found the broken pool file, if not then remove the next one. 
This is the only way to find the culprit.

Benchmark and profit files are also compatible between versions, so you will not have to go through the lengthy benchmark process again. Just copy&past the 'Stats' folder :-)

Alternatively you can compare the pool files between the two versions. Spot the difference! :-)

**Comment by awdtalon92** [comment]
@UselessGuru

You hit the nail on the head.  I only wanted to use one pool for now, but instead of deleting the pools I wasn't using, I added .BAK to the filename.  I didn't realize that anything in that folder would be read even if the extensions were not the default.  I'm guessing the correct way of doing this would be to exclude unused pools in  the command line.

Thanks for your help!
