### ISSUE TITLE
allow miner window to start

### ISSUE THREAD

**Issue by orangeclaimer** [MultiPoolMiner/MultiPoolMiner#1231]
Hi,

please give us the option to enable the miners-window. If you tell people to use an older version they have to manually update their miners, since they got not implemented at that time or didn't even exist back then.

Please consider it, thank you.

**Comment by UselessGuru** [comment]
See here https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1215

**Comment by alucard20724** [comment]
the other thread was locked... this latest release makes it feel like going from windows 7 to windows 8... no one liked windows 8.  I'll wait for the windows 10 version to be released before i update from the windows 7 version and just run the version that shows the miner windows.
