### ISSUE TITLE
Separrate dual mining and solo mining configuration

### ISSUE THREAD

**Issue by jestercore** [MultiPoolMiner/MultiPoolMiner#1238]
What about splitting algorithms in configs like:
"Keccak, KeccakSolo, KeccakDual"
Keccak - dual mining (Claymore) and solo mining (ccminer)
KeccakSolo - solo mining (ccminer)
KeccakDual - dual mining (Claymore)

**Comment by UselessGuru** [comment]
> Keccak - dual mining (Claymore) and solo mining (ccminer)
KeccakSolo - solo mining (ccminer)
KeccakDual - dual mining (Claymore)

I don't understand. What is your goal here?
For miners it is the miner binary that matters.
Mpm created miner object like this:
1. Reads all miner definition files (Folder 'Miners')
2. Iterates throug the miner definitions and looks for supported algorithms (Commands = [PSCustomObject]@{...})
3. Per Miner/Algo combination a miner file is created.

> splitting algorithms in configs like
Where to split?
Waht to split?
Why?

**Comment by jestercore** [comment]
Just i don't want to mine Keccak only, i want to mine it with Claymore + Ethash. Filter out solo mining coins, that can be mined with Claymore.

**Comment by aaronsace** [comment]
MultiPoolMiner decides what to mine.

**Comment by jestercore** [comment]
Yes, that's only to make benchmark time shorter

**Comment by aaronsace** [comment]
You save about 2 minutes; if you don't want to solo mine anything then just remove ccminer.

**Comment by jestercore** [comment]
Ok, sorry for disturbing. Awesome software, thank you.

**Comment by UselessGuru** [comment]
> Just i don't want to mine Keccak only, i want to mine it with Claymore + Ethash. Filter out solo mining coins, that can be mined with Claymore.

Instead of removing the miner entirely you can also edit the miner file and comment out the unwanted algos (currently you will lose this customitzation when you you update MPM)

There are enhancements in the works to make it easier to enable / disable algorithms on a per miner basis.
