### ISSUE TITLE
Error in logfile

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1239]
the error in the screen and log file is:

``` 
Invoke-RestMethod : Er heeft een time-out van de bewerking plaatsgevonden
At C:\Users\userx\Desktop\MultiPoolMinerV2.7.2\ReportStatus.ps1:32 char:1
+ Invoke-RestMethod -Uri $MinerStatusURL -Method Post -Body @{address = ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: POST, R...m-urlencoded
}:HttpRequestMessage) [Invoke-RestMethod], HttpRequestException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

also your website isn't reachable at the moment of writing. perhaps this errors means no connection to the API?

**Comment by Gandalf15net** [comment]
I have exactly the same error, also just opened a issue about it! Seems like you are not alone!

**Comment by m-bosch** [comment]
Im 99% confident is have to do with the website being offline. @grantemsley

**Comment by aaronsace** [comment]
Cloudflare has now been running for a few hours and seems to be stopping the constant DDoS. 

This shouldn't happen again but I will add checks in the code as well so it fails a bit more gracefully.
