### ISSUE TITLE
Invoke-RestMethod : Das Zeitlimit für den Vorgang wurde erreicht

### ISSUE THREAD

**Issue by Gandalf15net** [MultiPoolMiner/MultiPoolMiner#1240]
Gday

I am running MPM for less than a week now. Everything went smooth. Now I saw that there was an update out.

I started with v2.7.1.4, then Monday updated to v2.7.2.
With v2.7.2 I suddenly got an error this morning:

Invoke-RestMethod : Das Zeitlimit für den Vorgang wurde erreicht
At C:\pathtomyminer\MultiPoolMinerV2.7.2.1\ReportStatus.ps1:32 char:12
+ Write-Log (Invoke-RestMethod -Uri $MinerStatusURL -Method Post -Body  ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: POST, R...m-urlencoded
}:HttpRequestMessage) [Invoke-RestMethod], HttpRequestException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

I saw, that there is again an update out, v2.7.2.1. I downloaded the zip and copied my Stats, config.txt and start,bat

Then suddenly zpool was gone.  I then saw the PowerShellScript Updater. 

I decided to copy my v2.7.2 dir and run that. It told me there is an update available and downloaded something.

The error is still there with both versions (the one downloaded as zip and the one with the updater).

Also I see it suddenly switching between CpuminerJayddeeAvx2 and CpuminerJayddeeAesavx back and forth every minute.

2018-02-15 13:02:53 INFO: Closing miner (CpuminerJayddeeAvx2) because it is no longer the most profitable. 
2018-02-15 13:02:53 INFO: Starting miner (CpuminerJayddeeAesavx): 'C:\......

I think that is wrong, since the window tells me : 

CpuminerJayddeeAvx2     Lyra2z      633.23 KH/s 0.001683      93%     2.657809 Zpool
CpuminerJayddeeAesavx   Lyra2z      398.62 KH/s 0.001059      93%     2.657809 Zpool

I think Avx2 is more profitable, I dont get why it should switch. Maybe has to do with the error.

Anyone is able to help me?

Thank you!

**Comment by m-bosch** [comment]
the url error is 99% sure an error caused by the website not being online at the moment

**Comment by Gandalf15net** [comment]
Thank you. Didnt check the website itself. But any idea about why it switches to a less profitable miner? Also does the updater script work or should one always download newest zip?

**Comment by Gandalf15net** [comment]
2018-02-15 13:22:02 VERBOSE: CpuminerJayddeeAvx2: [2018-02-15 13:21:56] Accepted 5/5 (100%), diff 0.00445, 669.18 kH/s
2018-02-15 13:22:02 INFO: Starting next run. 
2018-02-15 13:22:02 INFO: Updating exchange rates from Coinbase. 
2018-02-15 13:22:02 INFO: Loading saved statistics. 
2018-02-15 13:22:04 INFO: Loading pool information. 
2018-02-15 13:22:20 INFO: Selecting best pool for each algorithm. 
2018-02-15 13:22:21 WARNING: Pool prices are out of sync. 
2018-02-15 13:22:21 INFO: Getting miner information. 
2018-02-15 13:22:27 INFO: Calculating profit for each miner. 
2018-02-15 13:22:37 INFO: Closing miner (CpuminerJayddeeAvx2) because it is no longer the most profitable. 
2018-02-15 13:22:37 INFO: Starting miner (CpuminerJayddeeAesavx): 'C:\path\MultiPoolMinerV2.7.2.1\Bin\CPU-JayDDee\cpuminer-aes-avx.exe -a lyra2z -o stratum+tcp://lyra2z.mine.zpool.ca:4553 -u my wallet -p workername,c=LTC'
2018-02-15 13:22:37 INFO: Pinging monitoring server. 


It keeps on the loop between those 2 miners back and forth

**Comment by m-bosch** [comment]
Its no problem that is changes a lot. my system swaps a lot between dusty, bminer and ccminer.

**Comment by Gandalf15net** [comment]
I see. It might be due the out of sync prices. I will continue to monitor it then, It is just annoying for the mining break of several seconds every half a minute.
I just thought , why? Since the aesavx is clearly less hashes and less LTC/Day.
Thank you for your input!

**Comment by m-bosch** [comment]
i don't know your miners because I do gpu- and you do cpu-mining sorry

**Comment by Gandalf15net** [comment]
Actually I do both :) But its ok, if it keeps a consistent problem I will just blacklist the lower miner

**Comment by UselessGuru** [comment]
grantemsley monitoring server is down - > timeout message -> watchdog expires

Workaround:
Remove minerstatusurl from your config. Restart MPM

To reset any pool/miner deactivations: 
Restart MPM

**Comment by Gandalf15net** [comment]
Thank you @UselessGuru 

If the problem keeps consitent (found some older issue reports with same thing), I will eighter open a new issue or have to switch to another (multi)miner. Deactivating zpool is no option.
