### ISSUE TITLE
prerelease renamed?

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1241]
i see there is now a 2.7.2.1 pre release but it has the date and description of the pre-release before this 2.7.2.

Is this just a renaming?

@aaronsace told me a few days ago in a few days there would be an update thats way I ask.

**Comment by spyder52** [comment]
Yes it is different the '.1' was added and I assume changes were made.. though as you say there was no announcment or change to the release details

**Comment by Gandalf15net** [comment]
Same happend again today, 2.7.2.2. If you look closely, you see that in the same post you can download the previous versions. Also its now named Release and no more pre-release

**Comment by aaronsace** [comment]
2.7.2.3 is now out
