### ISSUE TITLE
You might want to remove bminer...

### ISSUE THREAD

**Issue by tavenger5** [MultiPoolMiner/MultiPoolMiner#1242]
Apparently it inflates hash rates to make it look better, and some other sketchy stuff:
https://bitcointalk.org/index.php?topic=2519271.msg30319191#msg30319191

**Comment by phenomeus** [comment]
I kicked the .txt file from /Miners

**Comment by borzaka** [comment]
Be careful with Bminer Equihash miner #1127

**Comment by OzGoober** [comment]
Why would bminer.exe use WTSAPI32.dll (Win Terminal Services). It's the first dll.

**Comment by UselessGuru** [comment]
> Why would bminer.exe use WTSAPI32.dll (Win Terminal Services). It's the first dll after the header.

I think you are asking in the wrong place. You sholud ask the developer.
We do not have any insight knowledge about Bminer (or any other miner as such).

**Comment by OzGoober** [comment]
I understand that this has nothing to do with MPM UselessGuru. From what I've read, the developer does not want to talk. It's just suspect. Thanks for your efforts!

**Comment by UselessGuru** [comment]
> It's just suspect.

I agree. If we (here) remove BMiner support then I can already see the 'Why is there no Bminer support anymore...' questions :-)

**Comment by borzaka** [comment]
> I agree. If we (here) remove BMiner support then I can already see the 'Why is there no Bminer support anymore...' questions :-)

Because it's a suspected scam miner, which is only a couple months old and the source code is closed.
Users feedbacks indicates that this miner is doing strange things.

**Comment by aaronsace** [comment]
I'm 99% sure this is not a scam; work backward then it makes no sense. 
Why make suspicious connections? 
Why inflate hash rates? 

Scams are about appearing trustworthy not suspicious. There is no point writing your own miner that has bugs and is less functional when you could just wrap an already working miner. 

Anyway, if you don't want to use it then just remove it.
