### ISSUE TITLE
No Miners Operating

### ISSUE THREAD

**Issue by alwaysninja** [MultiPoolMiner/MultiPoolMiner#1243]
When I run the Start-MiningPoolHub.bat, I get nothing but red text on the prompt. I have attached the log of my most recent running of the .bat

[MultiPoolMiner_2018-02-16_10-32-48.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1729948/MultiPoolMiner_2018-02-16_10-32-48.txt)

**Comment by aaronsace** [comment]
You need to install the full graphics drivers from NVidia/AMD.

**Comment by alwaysninja** [comment]
Ah thanks a ton!

**Comment by alwaysninja** [comment]
Everything is now working smoothly again, thank you.
