### ISSUE TITLE
Api miningpoolhub has failed

### ISSUE THREAD

**Issue by Inside99** [MultiPoolMiner/MultiPoolMiner#1246]
Hello,
![miningpoolhub-has-failed](https://user-images.githubusercontent.com/33549765/36301029-24ac82b2-130c-11e8-9277-501c851b730d.jpg)

I have a little problem.
Every time I start the program, she does not want to start, does not want to go ... I receive the message **Api pool has failed**.
The problem persists for 24h.
Does anyone know how to fix the problem?

**Comment by UselessGuru** [comment]
Pool APi is fine.

Firewall? Try another pool to test Internet Connection

**Comment by Inside99** [comment]
I have not made any changes to the pc for a few months, it does not work on any pool.
It's weird.

**Comment by aaronsace** [comment]
Have you been blocked by Cloudflare?

**Comment by Inside99** [comment]
I do not know.
How can I find out?

**Comment by Inside99** [comment]
I solved the issue.
Solving: A simple restart on the PC and the router. :)
