### ISSUE TITLE
ETHminer running although not included in settings

### ISSUE THREAD

**Issue by kitsunemakoto** [MultiPoolMiner/MultiPoolMiner#1247]
Currently right now I'm mining with my GPU (XFX R9 270 2GB) and my CPU (Pentium G4560) for ZCash, Feathercoin, Expanse and Monero respectively, to my MiningPoolHub account. I've removed ethash from the algorithms and kept only the ethash2gb (cause I want to mine Expanse with it), but ethminer (which is for Ethereum etc etc) keeps running although it's removed. I don't know if this is an issue or not, but to me it most probably is.

Cheers.

**Comment by aaronsace** [comment]
Are getting you getting mixed up between coins and algorithms...? 

Anyway, Ethash2gb is the same algorithm as Ethash but doesn't mine the high difficulty coins as they use too much memory.

**Comment by kitsunemakoto** [comment]
No, I don't get any mixups. But most of the time, Ethash is running rather than Ethash2gb.
