### ISSUE TITLE
New m parameter in excavator 1.4.4

### ISSUE THREAD

**Issue by mserpell** [MultiPoolMiner/MultiPoolMiner#1248]
Is it possible to include the new M parameter in excavator 1.4.4.; the performance improvement (~10%) for equihash is worth pursuing.

**Comment by borzaka** [comment]
Excavator is optimized for various NVIDIA cards; most of the time you don't have to do anything; the default settings works just fine.

The new M parameter in [1.4.4](https://github.com/nicehash/excavator/releases) is for NeoScrypt algorithm:
> speed improvements for neoscrypt (for some cards)
> added M (mode) parameter to neoscrypt

If you have the following cards, than the right M parameter value will be used for your card for best performance. [README.md](https://github.com/nicehash/excavator/blob/master/nvidia/README.md)
> NeoScrypt is tuned for next cards: 1080 Ti, 1080, 1070 Ti, 1070, 1060 6GB, 1060 3GB, 1050 Ti, 1050, 1030, P104-100, P106-100 and TITAN V. You may reach higher speeds by experimenting with parameters when using a different card.

This is nothing to do with Equihash.

You can experiment with different settings with different cards, but it's out of MPM's scope.

**Comment by UselessGuru** [comment]
> performance improvement (~10%) for equihash

Where did you see this? I wish it was true!
