### ISSUE TITLE
[Question] Using CcminerXevan for Skein

### ISSUE THREAD

**Issue by Nicheuji** [MultiPoolMiner/MultiPoolMiner#1249]
I've enabled skein in ccminerxevan.ps1 and it gives me the best hashrate for my GTX 1070
What I'm seeing is right or I'm just seeing false numbers?

p.s. I've not been able to compare that to ccminersp because I can never get it to work even with stock settings (see https://github.com/MultiPoolMiner/MultiPoolMiner/issues/987)

**Comment by UselessGuru** [comment]
> What I'm seeing is right or I'm just seeing false numbers?

Difficult to say. Can you see better rates at the pool? That's what really matters.
Note: a miner can tell you / report any number, some - I am not naming them - are reporting inflated numbers 👎

**Comment by aaronsace** [comment]
I leave it up to users to test configurations. If you have any recomendations for the default configuration that comes with MultiPoolMiner then post the results.
