### ISSUE TITLE
Excavator1 & Excavator2 not benchmarking

### ISSUE THREAD

**Issue by friendly-face** [MultiPoolMiner/MultiPoolMiner#1250]
I only have AMD cards.  I have never gotten Excavator to provide anything but a "0" value during benchmarking.  Didn't know if you might have some pointers to get this working or if I should just exclude it or delete it from the miners folder?

**Comment by adamje42** [comment]
Excavator no longer supports AMD cards.

**Comment by friendly-face** [comment]
Thanks,  I will exclude then.
