### ISSUE TITLE
CPUminer JayDDeeAvx2sha

### ISSUE THREAD

**Issue by friendly-face** [MultiPoolMiner/MultiPoolMiner#1251]
I have never gotten CPUminer JayDDeeAvx2sha to provide anything but a "0" value during benchmarking.  Didn't know if you might have some pointers to get this working or if I should just exclude it or delete it from the miners folder?

**Comment by adamje42** [comment]
Not all of the executables included with JayDDee will work for all CPUs. If JayDDeeAvx2sha only ever registers as a 0, chances are it is not compatible with your CPU.

**Comment by friendly-face** [comment]
Thanks.
