### ISSUE TITLE
Is there a way to exclude a specific miner-algorithm combination?

### ISSUE THREAD

**Issue by friendly-face** [MultiPoolMiner/MultiPoolMiner#1252]
I have a number of miner-algorithm combinations that only produce "0" during benchmarking.  Is there a way to exclude them from future benchmarking if I can't make them work?  Do I just delete the line in the powershell script that lists the particular algorithm?

**Comment by UselessGuru** [comment]
Yes, edit the miner file.
Look for [Commands]@{
...

**Comment by friendly-face** [comment]
Thanks.  More specifically for Prospector is there a way to remove the 2gb benchmark from running?

**Comment by UselessGuru** [comment]
> More specifically for Prospector is there a way to remove the 2gb benchmark from running?

You need to edit the miner file (see also
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1086)

**Comment by grantemsley** [comment]
Closing outdated issue.  If this is still a problem in the latest version (and there currently isn't an open issue for it) please open a new one.
