### ISSUE TITLE
Keeps jumping poolls

### ISSUE THREAD

**Issue by papadrams** [MultiPoolMiner/MultiPoolMiner#1253]
Even though i run Start-MiningPoolHub, it keeps changing pools. Going to nicehash, zpool, Blockmunch and others...

**Comment by nickvasel** [comment]
Remove the pools you don't want to use in the pools folder.

**Comment by UselessGuru** [comment]
> Even though i run Start-MiningPoolHub, it keeps changing pools. Going to nicehash, zpool, Blockmunch and others...

Logs please - also check if it not on its donation run (yoo should see a different BTC address/username).

**Comment by aaronsace** [comment]
It's either watchdog or donation.
