### ISSUE TITLE
Suggestion: Display a message in MPM indicating DevFee mining

### ISSUE THREAD

**Issue by platonicjesus** [MultiPoolMiner/MultiPoolMiner#1256]
I like how most miners say "Dev Fee mining starting" or something along those lines and was wondering if you could possibly add it to MPM so when it mines for you it lets us know.

**Comment by UselessGuru** [comment]
Like the idea! I think this could be the answer to https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1253 and other issues

**Comment by UselessGuru** [comment]
Implemented in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1719
