### ISSUE TITLE
DevFee 24h logging

### ISSUE THREAD

**Issue by jestercore** [MultiPoolMiner/MultiPoolMiner#1258]
What about DevFee logging?
MPM should calculate every hour it's working and then make do a DevFee job.
That's because some of us need's to restart mpm, or close is sometimes.
I'm gaming sometimes with my GPU, and restarting MPM twice or 3 times per day.

**Comment by platonicjesus** [comment]
Agreed I forgot to put that in my suggestion

**Comment by UselessGuru** [comment]
[Duplicate](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1256)
