### ISSUE TITLE
Problems with Kaspersky Internet Security

### ISSUE THREAD

**Issue by conscript91** [MultiPoolMiner/MultiPoolMiner#1259]
If I leave KIS protection on, MPM can't download anything and excavator is not working. I have to disable automatic protection and manually allow every request from MPM, how safe is that?

These urls looks very suspicious to be honest:

![1234](https://user-images.githubusercontent.com/36595410/36351319-4a93579c-14a8-11e8-98d0-6f6377f87c2c.PNG)

What are these?

Also, the MPM can't download xmr-stak and nsgminer even if I allow everything within firewall, URL problem or what?

EDIT: Just switched back to previous MPM version (V2.7.1.4), everyting works perfect even with automatic KIS protection enabled.

**Comment by UselessGuru** [comment]
None of the links above are related to MPM. 

> can't download xmr-stak and nsgminer even if I allow everything within firewall, URL problem or what?

Exact error messages please.
Make sure the the files are still available for download (e.g. try downloading them manually)

**Comment by conscript91** [comment]
Hm, not sure where did those URLs come from then.

I managed to solve download problems, but there are few other problems:
- Slow benchmarking, it took 5 minutes to launch the miner
- MPM randomly stops working, no error message, just hanging 
- "Pool prices out of sync" error message

**Comment by UselessGuru** [comment]
> MPM randomly stops working, no error message, just hanging

[This issue?](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/547) See AdrianAcala's solution

**Comment by conscript91** [comment]
I have already unchecked quick mode and edit mode. 

Benchmarking was done for Equiash with BMiner, and now it just won't continue benchmarking other miners. No error messages, except "Pool prices out of sync".

**Comment by UselessGuru** [comment]
> it is not opening miner window while benchmarking

The new version will not show miner windows. This is by design. 
Check / tail the files in the log folder for miner messages.

**Comment by conscript91** [comment]
Oh, okay. Didn't know that. But it does open window for some miners (excavator for example).

I had to delete ccminer, nsgminer, xmrig, they were having problems with Kaspersky. It didn't even help if I add them to exclusion list. 
![exclusion](https://user-images.githubusercontent.com/36595410/36353830-b206d200-14cb-11e8-8ec3-6315e0bf91de.PNG)

Everything working good so far, bencmarking is done. Thank you for help.

Kaspersky is making problems without reason in my opinion, but I have to keep it because this is my private PC. MPM should work fine on other computers without KIS I guess, will try it later.

Just one more thing:

![3333333333](https://user-images.githubusercontent.com/36595410/36353884-923a0e3c-14cc-11e8-954f-5f6af71c4d72.PNG)

I had these problem on v2.7.1.4 too.

**Comment by UselessGuru** [comment]
> excavator miner, without affecting other algos for that miner?

You need to edit the miner file:

Comment out (add #) the unwanted algo, e.g.
```
$Commands = [PSCustomObject]@{
    "blake2s" = @() #Blake2s
    "decred" = @() #Decred
    #"daggerhashimoto" = @() #Ethash
    "equihash" = @() #Equihash
    "lbry" = @() #Lbry
    "lyra2rev2" = @() #Lyra2RE2
    "neoscrypt" = @() #NeoScrypt
    "nist5" = @() #nist5
    "pascal" = @() #Pascal
}
```
