### ISSUE TITLE
WARNING: Pool prices are out of sync.

### ISSUE THREAD

**Issue by nickvasel** [MultiPoolMiner/MultiPoolMiner#1260]
Apologizes if this is already being looked at...
Also=USD/GH/Day seem a bit off?
[Start-MiningPoolHub.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1734724/Start-MiningPoolHub.txt)
[MultiPoolMiner_2018-02-17.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1734725/MultiPoolMiner_2018-02-17.txt)
![capture](https://user-images.githubusercontent.com/35632631/36352050-ad8ff100-14aa-11e8-9d28-722812e580a6.gif)

**Comment by UselessGuru** [comment]
> Also=USD/GH/Day seem a bit off?

What does not seem correct?

**Comment by nickvasel** [comment]
The USD/GH/Day for equihash, is that figure correct? Also I fixed the WARNING: Pool prices are out of sync. It was due to the fact that I deleted all the other pools in the pool folder, replaced the pools in the folder . No more warnings.

**Comment by tboy1337** [comment]
Ive had this issue a few times with new version

**Comment by UselessGuru** [comment]
> The USD/GH/Day for equihash, is that figure correct?

Yes. It seems high but it is correct. You have to put it in relation with the number of hashes (KH/s vs. GH)

**Comment by nickvasel** [comment]
Fair enough, Thank you....  please close ticket...
