### ISSUE TITLE
Zpool not showing up in benchmarking

### ISSUE THREAD

**Issue by Wonderboy88** [MultiPoolMiner/MultiPoolMiner#1262]
I have selected 4 pools in the start.bat file: "-poolname ahashpool,nicehash,zpool,miningpoolhub". All come up in benchmarking under "pools" except zpool. What am I missing here? 

![untitled](https://user-images.githubusercontent.com/25485874/36352788-18a083aa-14b6-11e8-8646-0ab88cd49052.png)

**Comment by UselessGuru** [comment]
> What am I missing here

Logs please...
Maybe Zpool is not the best paying pool for any algo. MPM will only use the best paying algo amongst all configured pools. For best profit it is best to include only a few (and not all available) pools. (Don't ask which pools are best - this is beyond politics and religion).

**Comment by Wonderboy88** [comment]
So it only benchmarks an algo on the most profitable pool? I assumed it would benchmark each algo on every available pool. That would explain it.

**Comment by UselessGuru** [comment]
>  I assumed it would benchmark each algo on every available pool.

There is no need to benchmark against each pool. Benchmarking is to find out how many hashes your card(s) can do. This is independent of the pool.
BUT: When you look at the hash rates reported at different pools you might/will see different numbers for the same card/hash rate at the miner -> hashes are disappearing somewhere???!!!??? Make an educated guess :-)
