### ISSUE TITLE
Zcash, Zclassic

### ISSUE THREAD

**Issue by conscript91** [MultiPoolMiner/MultiPoolMiner#1263]
Why are ZEC and ZCL coins missing? There is only BitcoinGold within the Equihash algo.

**Comment by m-bosch** [comment]
I thought the same this morning but last hours dusty is running classic for me.

**Comment by conscript91** [comment]
I got it, MPM is only showing the most profitable coin for specific algo. It was just a bit late with update, was showing btg instead of zcl whole day. It's fine nowg

**Comment by m-bosch** [comment]
@conscript91 Nice, please close this issue.
