### ISSUE TITLE
Is it possible to add a pause command?

### ISSUE THREAD

**Issue by jsaltzman** [MultiPoolMiner/MultiPoolMiner#1264]
I use MPM on my gaming computer. Usually on the weekends, I am very often closing MPM to game, reopening, closing again, etc. I would love to be able to pause instead of closing out of the program entirely. One reason is so that I don't reset the donation multiple times a day. If you added this feature I would consider increasing my donation amount to compensate.

**Comment by UselessGuru** [comment]
No need, the is a bug (feature? of Windows) that already does half of what you want:
 
[Read here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/547) and do the opposite of AdrianAcals' solution.
How to use this:
- Click into the MPM window (this will stop the MPM loop, (first half of request achieved)
- kill all running mining tasks via task manager (request complete)
I know this is not a sexy solution, but I will do trick nicely.
