### ISSUE TITLE
MPM monitor last seen gets really long time and turns pink?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1265]
What causes the monitor to lose track?

I am benchmarking right now 

Giving MPM a try again after using Nicehash Legacy for last month.

**Comment by UselessGuru** [comment]
> What causes the monitor to lose track?

??? What do you mean by this?
Later version of MPM do no longer show miner windows for most miners. Instead screen output is written to files in the 'Logs' directory

**Comment by paulpoco** [comment]
The logs lasted for about 1 hr last night.   Last time in log was almost midnight PST and did not start again until I closed mpm and started it again.

I may need to go back to the version before without all this web monitoring stuff like others have said.

I lost 6 hrs of mining last night

**Comment by aaronsace** [comment]
If there is no log then MultiPoolMiner is not switching. Check that you haven't paused the console.
