### ISSUE TITLE
"Enhancement" log deletion

### ISSUE THREAD

**Issue by nickvasel** [MultiPoolMiner/MultiPoolMiner#1268]
As I can only speak for me, the program preforms very well. After a period of up time the log folder can get crowded with "old" log files that are no longer needed. Is there a way to add an automation process that removes log files that are stale/or no longer needed after a day or so?
Thank you for all your efforts.

**Comment by thebeerbaron2018** [comment]
You can add this to your start.bat to delete on startup of the miner.... the "-d 7" is the number of days to retain - seven in this case.

forfiles -p "c:\PATH-TO-MINER-FOLDER\Logs" -d -7 /c "cmd /c del @path"

**Comment by nickvasel** [comment]
That would work, thank you. I really don't plan on restarting the miners so I'm looking for a process that runs in the background to monitor the age of the logs and delete when necessary.

**Comment by thebeerbaron2018** [comment]
Run that command as a scheduled task set on a 24 hour interval then from Windows Task Scheduler.
