### ISSUE TITLE
''Include.psm1 not loaded'' errors on 2.7.2.1

### ISSUE THREAD

**Issue by FrankMycHo** [MultiPoolMiner/MultiPoolMiner#1269]
Hi,

I constantly received these error messages since running 2.7.2.1:

Import-Module : The specified module 'C:\Bitcoin\MultiPoolMinerV2.7.2.1\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
+ CategoryInfo          : ResourceUnavailable: (C:\Bitcoin\Mult...ls\Include.psm1:String) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
& : The specified module 'C:\Bitcoin\MultiPoolMinerV2.7.2.1\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Bitcoin\MultiPoolMinerV2.7.2.1\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (C:\Bitcoin\Mult...ls\Include.psm1:String) [], RuntimeException
+ FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
& : The specified module 'C:\Bitcoin\MultiPoolMinerV2.7.2.1\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Bitcoin\MultiPoolMinerV2.7.2.1\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (C:\Bitcoin\Mult...ls\Include.psm1:String) [], RuntimeException
+ FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by UselessGuru** [comment]
Your installation is broken. In what directory did you copy all the MPM files?

**Comment by FrankMycHo** [comment]
I copied all files here: C:\Bitcoin\MultiPoolMinerV2.7.2.1
My previous version, which is working perfectly is here: C:\Bitcoin\MultiPoolMinerV2.7.1.4

Do you suggest that I re-copy MPM 2721 ?

I also kept my Miners folder from previous version to kept my benchmark

**Comment by UselessGuru** [comment]
Verify that that 'Include.psm1' exists in 'C:\Bitcoin\MultiPoolMinerV2.7.2.1'.

I suggest you install a full copy of MPM (either [release](https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.2.2/MultiPoolMinerV2.7.2.2.zip) or [latest ZIP file](https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip)) to a new directory.
Benchmarks are stored in the 'Stats' folder not (and not 'Miners'). To retain BM results you will need to copy the contents of the 'Stats' folder.

**Comment by aaronsace** [comment]
@FrankMycHo Please download and extract the latest release then double click on 'start.bat'.

**Comment by FrankMycHo** [comment]
Hi,

I deleted my previous folder, dowloaded the latest relesase which is now 2.7.2.3 and copied my BM (Stats and not Miners folder as previously mentioned).

It is now benchmarking some new algo for the CPU, no error so far.
I think you are right and my installation was broken (Include.psm1 was there).
I'll close the issue as soon as it complete the benchmark and fully works.

**Comment by FrankMycHo** [comment]
All good now
Thx for your help guys !
