### ISSUE TITLE
Windowstyle in .bat folder

### ISSUE THREAD

**Issue by Taks808** [MultiPoolMiner/MultiPoolMiner#1270]
Hello,

I am not sure this is really an issue but something that has been bothering me with both the 2.7.1.4 and 2.7.2.2 verion but......

I tried searching thru the issues both open and closed as well as read thru the README.txt but I couldn't find any information about changing the "-windowstyle" to something other than maximized in the .bat files. As with the new version 2.7.2.2 that the miner windows are now not being shown I am using MSI afterburner to track GPU temps and such. But with the windows being maximized i am having to manually resize the window to show me the GPU temps. Are there other options? Resizing a window in TeamViewer on my android cellphone is pretty tricky.

Thank you in advance

**Comment by ristoto** [comment]
Why not just remove it from the bat file? You're editing the bat file anyway to add your addresses, etc. so simply delete the -windowstyle maximized from it? Normal, hidden and minimized are your alternatives.

**Comment by Taks808** [comment]
Thanks for the reply. I didnt want to mess with the coding all that much. I have it set to normal now and I can see both MSI Afterburner and the MPM.
