### ISSUE TITLE
Release date of 2.7.3?

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1272]
When will 2.7.3 be released?   

I'm skipping 2.7.2... completely because of the hide miner window.   i don't remote into my computers since they're all right here and so this feature does not add any value for me, in fact it takes value away.

I like the miner window because it gives me real-time feedback and allows for better trouble shooting and tweaking of each of my systems.

thanks.

**Comment by bjtags** [comment]
Yes Please Unhide miners windows...!!!
No programming wiz.... But I know what the numbers mean and say about what's happening.
That real time feedback is helpful for us hardware freaks. Yes looking at the logs is helpful, but digging through them is a pain for us non-coders and still not live info. Being able to kill a dead or glitching miner on a remote machine is sometimes better then killing the whole rig or rebooting it.
Love your work!!! Your program has helped me recover from the mess that is NiceHack.
And doing much better... My 5 Loaded Rigs and growing thank you everyday.

**Comment by aaronsace** [comment]
March
