### ISSUE TITLE
after some time multipool starts using miners in default name

### ISSUE THREAD

**Issue by platinumdubs** [MultiPoolMiner/MultiPoolMiner#1278]
after sometime always different but 1 or 2 miners revert back to using aaron as the user name despite having tchanged this throughout the file. I remember seeing this issue somewhere else but I couldn't find the exact issue to be able to search for a fix so I apologize for the but I have attached log.

[MultiPoolMiner_2018-02-20_03-45-26.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1740152/MultiPoolMiner_2018-02-20_03-45-26.txt)

**Comment by UselessGuru** [comment]
That is when MPM is on it's donation run (1h after start)

**Comment by aaronsace** [comment]
The configurations are working in the latest release. 

Our team is solely funded by donations: 
> -donate Donation of mining time in minutes per day to aaronsace. Default is 24, minimum is 10 minutes per day (less than 0.7% fee).

**Comment by platinumdubs** [comment]
cool thank you for clearing at up keep up the good work guys 💯
