### ISSUE TITLE
excavator

### ISSUE THREAD

**Issue by tiotoi** [MultiPoolMiner/MultiPoolMiner#1280]
Hello,
just downloaded a new release and right after the start got these error below.....
any idea?

WARNING: Pool prices are out of sync (7294 minutes).
Get-Content : Access to the path 'C:\MultiPoolMinerV2.7.2.2\Miners\excavator' is denied.
At C:\MultiPoolMinerV2.7.2.2\Include.psm1:230 char:27
+                     ($_ | Get-Content | ConvertFrom-Json) | ForEach-O ...
+                           ~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\MultiPoolMin...iners\excavator:String) [Get-Content], UnauthorizedAccessException
+ FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Access to the path 'C:\MultiPoolMinerV2.7.2.2\Miners\excavator' is denied.
At C:\MultiPoolMinerV2.7.2.2\Include.psm1:236 char:54
+             if ($Content -eq $null) {$Content = $_ | Get-Content}
+                                                      ~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\MultiPoolMin...iners\excavator:String) [Get-Content], UnauthorizedAccessException
+ FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by aaronsace** [comment]
You've put a folder called 'excavator' in the folder called 'miners'. I think you meant to put it in the folder called 'bin'.

**Comment by aaronsace** [comment]
FYI, v2.7.2.3 is out.

**Comment by tiotoi** [comment]
@aaronsace  thanks a lot!
