### ISSUE TITLE
Miner Windows

### ISSUE THREAD

**Issue by Razalka** [MultiPoolMiner/MultiPoolMiner#1281]
In this version **MultiPoolMinerV2.7.2.3.zip** - _Miner windows no longer popup._
How to re-enable the miner windows again ?
I need it to monitoring the hashrate.
Im afraid if the GPU had the wrong setting or had some error or etc and the hasrate dropped, we can't monitoring the hashrate.
Thank you.

**Comment by UselessGuru** [comment]
[Duplicate](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1215)

**Comment by aaronsace** [comment]
You could not debug before but in this release you can: 
> Direct unaltered live streams of all active miners are also included in the logs folder.
