### ISSUE TITLE
best Process updating from Version to Version?

### ISSUE THREAD

**Issue by phenomeus** [MultiPoolMiner/MultiPoolMiner#1282]
is there a official way to update and keep up with constant development (thanks again! keep it up!)?

what do I have to copy over to continue mining and not benchmarking again?

maybe this info can also be added to the readme, couldn't find anything before

**Comment by UselessGuru** [comment]
> what do I have to copy over to continue mining and not benchmarking again?

Copy the 'Stats' folder, this is where all BM results are stored.

**Comment by phenomeus** [comment]
ok, just Stats, Excavator and Start.bat and the rest is downloaded, stored and it should start to work, right?

**Comment by UselessGuru** [comment]
> ok thanks, so just Stats, Excavator and Start.bat and the rest is downloaded, stored and it should start to work, right?

Yes.

**Comment by Gandalf15net** [comment]
And the new Config.txt if you have different wallets set up! Dont forget that!
