### ISSUE TITLE
Stats for YiiMP.eu are off for some coins/messing up/ impossible autoswitch

### ISSUE THREAD

**Issue by pitha7** [MultiPoolMiner/MultiPoolMiner#1283]
The stats for yiimp are off EUR/day and EUR/GH/Day messing up/ impossible autoswitch
My config.txt
[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1743515/Config.txt)
Bat file
cd` /d %~dp0

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

pwsh -noexit -executionpolicy bypass -command "& .\multipoolminer.ps1 -region europe -currency eur -type nvidia -poolname yiimp -algorithm x17,phi,bitcore,keccakc,lyra2v2,tribus,skein,bitcore,neoscrypt -donate 10 -watchdog -minerstatusurl https://multipoolminer.io/monitor/miner.php -switchingprevention 2"
pause

![stats](https://user-images.githubusercontent.com/36695084/36473633-62cfe470-16f5-11e8-9490-cde597bba407.jpg)
Please advise...

**Comment by UselessGuru** [comment]
MPM needs to benchmark these miner/algo combos first. That's why is says 'Benchamrking' and 'Unknown'.

**Comment by aaronsace** [comment]
@UselessGuru Please can you check the divisors in the pool file? Maybe compare with zpool? 

I don't use YiiMP but it doesn't mention that on the website: 
> * values in mBTC/MH/day, per GH for sha & blake algos, kSol. for equihash

**Comment by pitha7** [comment]
I did the benchmarking in total (not reflected in screenshot) but I kept getting these abnormal high values for EUR/day and EUR/GH/Day. Is this normal and will this straighten out after x time  and not influence autoswitch always to this extremely high EUR/day value as default?
![stats_marked](https://user-images.githubusercontent.com/36695084/36479497-32f52878-1709-11e8-96ea-3e2c98049596.jpg)

**Comment by UselessGuru** [comment]
> Is this normal and will this straighten out after x time and not influence autoswitch always to this extremely high EUR/day value as default?

No, this is not normal. The pool does not send proper data (a few dimensions off)

Could you please update your screenshot with the final results. Can you please also say for each algo by how much the results off (in 10^3)?

**Comment by aaronsace** [comment]
I think the homepage was correct but they all needed dividing by 1000 so this should fix it: f4da1cab5284884995f2ead52957ed9d16ef9840
