### ISSUE TITLE
Include.psm1 error

### ISSUE THREAD

**Issue by romajc84** [MultiPoolMiner/MultiPoolMiner#1284]
& : The specified module 'C:\Users\Joey\Desktop\Mining\Gaming-MultiPoolMiner\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Users\Joey\Desktop\Mining\Gaming-MultiPoolMiner\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (C:\Users\Joey\D...ls\Include.psm1:String) [], RuntimeException
+ FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by UselessGuru** [comment]
Your installation is broken.. Include.psm1 must not be in the pools folder. Only keep pool files (ending in .ps1) in the pool folder.

**Comment by romajc84** [comment]
Oh thanks.  That helped me figure it out.  I just added a folder in the Pools folder to hold all the pools I wasn't using.  Removing it fixed it.. Thanks!
