### ISSUE TITLE
Miner windows 

### ISSUE THREAD

**Issue by unikon2450** [MultiPoolMiner/MultiPoolMiner#1287]
> Recent changes since v2.7.1.4:
> Miner windows no longer popup.

Hey. Can you restore the mainer window? It is very useful. You can check the operation of every single card. This is very valuable information related to performance and stability.

Maybe you can enter on / off options?

**Comment by aaronsace** [comment]
Windows popping up are of no use on mining rigs; instead, all the miners are streamed directly into the logs folder instead. 

Live log reader is being released tonight for simplicity.
