### ISSUE TITLE
V2.7.1.4 "Cannot bind argument to parameter 'DifferenceObject'

### ISSUE THREAD

**Issue by cb515** [MultiPoolMiner/MultiPoolMiner#1288]
i modify the Start file
My command is :
set "command=& .\multipoolminer.ps1 -wallet 1JQJjXQsqaNWoEVQ5bAupLV1BrS5dCWid8 -username cb515 -workername cb1 -region usa -currency usd -type nvidia -poolname miningpoolhub -algorithm cryptonight,ethash,ethash2gb,equihash,groestl,neoscrypt -donate 10 -watchdog -switchingprevention 2"

then  i click it to start, at last i got a lots of red error in command line window as below:

PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\BitCoinMiner\MultiPoolMinerV2.7.1.4\MultiPoolMiner.ps1:179 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\BitCoinMiner\MultiPoolMinerV2.7.1.4\MultiPoolMiner.ps1:179 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\BitCoinMiner\MultiPoolMinerV2.7.1.4\MultiPoolMiner.ps1:179 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\BitCoinMiner\MultiPoolMinerV2.7.1.4\MultiPoolMiner.ps1:179 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

i dont know how to fix it , is there some people help me?

**Comment by aaronsace** [comment]
Install the full graphics driver from NVidia/AMD website.

**Comment by cb515** [comment]
@aaronsace thank you very much ! it works!
