### ISSUE TITLE
Out of Memory Exception

### ISSUE THREAD

**Issue by 3zero2** [MultiPoolMiner/MultiPoolMiner#1290]
I updated to 2.7.2.3 and during benchmarking I got the following Out Of Memory Exception.

```
PS>TerminatingError(Where-Object): "Exception of type 'System.OutOfMemoryException' was thrown."
PS>TerminatingError(AHashPool.ps1): "Thread failed to start."
PS>TerminatingError(): "Thread failed to start."
PS>TerminatingError(ForEach-Object): "Thread failed to start."
PS>TerminatingError(Get-ChildItemContent): "Thread failed to start."
```

![capture](https://user-images.githubusercontent.com/6965396/36569817-8f37394c-182f-11e8-8347-618b41008750.PNG)

**Comment by nickvasel** [comment]
"This issue occurs because the computer does not have sufficient memory to complete the requested operation." 
Dumb question, how much memory you have?

**Comment by tbergeron** [comment]
If you have a GTX 9xx: I had this kind of crash when benchmarking the palgin nvidia miner. I got rid of the `PalginNvidia` in `/Miners` and it stopped crashing. (https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/PalginNvidia.txt)

**Comment by 3zero2** [comment]
@nickvasel System has 8Gb of RAM. Was never an issue before I upgraded to version 2.7.2.3

@tbergeron I have an Nvidia Titan Xp - don't know if it falls under the GTX9xx umbrella. I disabled `PalginNvidia` and so far so good. Thanks for the tip.

**Comment by steamtyme** [comment]
Hey there,

This is my first build. I started getting this error yesterday; my first full day away. 

Everything ran fine for 5 days or so; since the reboot it made it a little over a day.

I'm running 4 rx 570 8gb cards with 4 gb of ram, and 120 gb ssd, with Windows 10 operating system

**Comment by steamtyme** [comment]
Sorry forgot to mention this shows up relating to PowerShell.
