### ISSUE TITLE
MultiPoolMiner keeps going IDLE. 

### ISSUE THREAD

**Issue by loco809** [MultiPoolMiner/MultiPoolMiner#1294]
Whenever I start the miner it starts mining briefly but after a couple minute it stops and goes idle while displaying the message “waiting for the next run” which also takes a couple minutes to start mining again. That’s a lot of wasted time not mining given that it does it VERY OFTEN. Is there a way to keep this constantly mining instead of being idle for like 5 minutes every 2 minutes? 

I haven’t changed any settings besides the ones that have to be changed,etc. any idea on the issue?

**Comment by UselessGuru** [comment]
> Whenever I start the miner it starts mining briefly but after a couple minute it stops and goes idle while displaying the message “waiting for the next run”

Are you sure it is idle? Current builds do no longer display miner windows for most miners.

**Comment by G510Gamer** [comment]
scroll up and you should see "active" that's the current mining software

**Comment by aaronsace** [comment]
@loco809 It's definitely always mining. 

As always, to ensure that you don't spam the pool sites' data and to decrease CPU usage, MultiPoolMiner leaves the miners to do there work for 60 seconds. 

Do you have any recommendations on the wording of that message?

**Comment by loco809** [comment]
Based on my GPU stats it definetly stops mining. GPU usage, Core clock,memory clock and temp all drop to idle levels as well.

**Comment by UselessGuru** [comment]
> Based on my GPU stats it definetly stops mining. GPU usage, Core clock,memory clock and temp all drop to idle levels as well.

@loco809 
What do the logs say? Did you check for error messages? Which miner is affected?

**Comment by loco809** [comment]
I’ll check when I get home later but it would pretty much stop because “isn’t the most profitable anymore” so it just hangs there idle for a while until it starts mining something else but that can take 5 minutes.

**Comment by loco809** [comment]
@UselessGuru Hi, it seems that I get a "Failed to connect to miner (ExcavatorNvidia1)." error message. It doesn't go to any other miner, it just hangs there idle.

**Comment by UselessGuru** [comment]
@loco809 

Please try with these files
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1104

Also try with the newest Excavator, currently 1.4.4.a

Please post the excavator log here.

**Comment by loco809** [comment]
@UselessGuru Nothing. It doesn't even create an excavator log.

**Comment by UselessGuru** [comment]
@loco809 

What happens If you try to run excavator with the exact same parameter as MPM does? [Have you tried these files?](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1104)

**Comment by loco809** [comment]
I've tried everything you have posted and still 0 results. Maybe it isn't meant to be lol.

Either way I appreciate all your help, thank you very much, I'll try an alternative software for now.

**Comment by loco809** [comment]
@UselessGuru by the way I actually decided to download the previous version of MPM and it seems to work fine now. Not sure if there's some bug on the most recent release.

**Comment by mkirov0** [comment]
I have an issue with this $#!@% Excavator... Running MPM 2.7.2.4
I have the ./APIs./nicehash.ps1 that came with the release, but can update if the one referenced above is different in any way that I did not see. 
<img width="164" alt="screen shot 2018-02-24 at 5 00 21 pm" src="https://user-images.githubusercontent.com/28104701/36631634-6157a1b4-1984-11e8-90a3-a71c59815249.png">
I have 2 excavatorNVIDIA.ps1(s) in the ./Miners folder. Can replace them with the ones linked above, but decided to ask if the linked above are different or newer.
<img width="172" alt="screen shot 2018-02-24 at 5 00 01 pm" src="https://user-images.githubusercontent.com/28104701/36631657-c5388932-1984-11e8-82fc-638c43c27ca2.png">
When I start Excavator outside MPM it works. I modified the excavator+web+transcript batch 
<img width="254" alt="screen shot 2018-02-24 at 9 11 36 pm" src="https://user-images.githubusercontent.com/28104701/36634108-60c998f0-19a8-11e8-8678-e239b5b75344.png">
and fed it the MPM *.auto_2_nvidia.json
<img width="913" alt="screen shot 2018-02-24 at 9 11 13 pm" src="https://user-images.githubusercontent.com/28104701/36634173-21840e36-19a9-11e8-86dd-064cee216832.png">
and ran it that way. I seems to work.
<img width="857" alt="screen shot 2018-02-24 at 9 14 42 pm" src="https://user-images.githubusercontent.com/28104701/36634167-102a5078-19a9-11e8-837a-5e0cb7c5be98.png">
If I can provide any additional info please let me know.
Any help would be appreciated!

**Comment by aaronsace** [comment]
@mkirov0 Step back a bit here as this is going way off the original issue. 

Lets start by opening MultiPoolMiner and copying the command line from the screen: 
`Bin\Excavator\excavator.exe -p 23456 -c Zpool_Blake2s_1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb_1_Nvidia.json -na`

Open PowerShell and run that command like this: 
```
Set-Location C:\Users\aaron\MultiPoolMiner\Bin\Excavator
.\excavator.exe -p 23456 -c Zpool_Blake2s_1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb_1_Nvidia.json -na
```

**Comment by aaronsace** [comment]
Once you have done that and posted a screen shot, please then use go to PowerShell again but this time format your command like this: 
```
$Path = "C:\Users\aaron\MultiPoolMiner\Bin\Excavator\excavator.exe"
$Arguments = "-p 23456 -c Zpool_Blake2s_1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb_1_Nvidia.json -na"
$Process = Start-Job ([ScriptBlock]::Create("Start-Process $(@{desktop = "powershell"; core = "pwsh"}.$Global:PSEdition) `"-command ```$Process = (Start-Process '$($Path)' '$($Arguments)' -WorkingDirectory '$(Split-Path $Path)' -WindowStyle Minimized -PassThru).Id; Wait-Process -Id `$PID; Stop-Process -Id ```$Process`" -WindowStyle Hidden -Wait"))
```

**Comment by mkirov0** [comment]
Done and Done
<img width="592" alt="screen shot 2018-02-24 at 10 07 48 pm" src="https://user-images.githubusercontent.com/28104701/36634643-44ef94c4-19b0-11e8-9d61-d1b902a19ea3.png">
<img width="597" alt="screen shot 2018-02-24 at 10 14 50 pm" src="https://user-images.githubusercontent.com/28104701/36634647-51d84eb0-19b0-11e8-8bec-307e4266a127.png">
I don't know if it is supposed to print anything... It just keeps blinking on the next line...
<img width="589" alt="screen shot 2018-02-24 at 10 16 15 pm" src="https://user-images.githubusercontent.com/28104701/36634656-793829da-19b0-11e8-9bc3-da5a046b31d3.png">

**Comment by aaronsace** [comment]
On the first screenshot, you have missed the dot and the back slash at the beginning. Also, I don't think that you have press enter because it would have shown an error. 

So enter that again and post the screenshot.

**Comment by mkirov0** [comment]
You are absolutely correct!
<img width="603" alt="screen shot 2018-02-24 at 11 44 18 pm" src="https://user-images.githubusercontent.com/28104701/36635392-a9898154-19bc-11e8-8897-734406a7a99d.png">
<img width="594" alt="screen shot 2018-02-24 at 11 48 18 pm" src="https://user-images.githubusercontent.com/28104701/36635439-734e1522-19bd-11e8-8ba9-35879f6167fe.png">
<img width="887" alt="screen shot 2018-02-24 at 11 55 25 pm" src="https://user-images.githubusercontent.com/28104701/36635487-4630d8ee-19be-11e8-861b-e39e3aa37cab.png">
Thanks for being patient!

**Comment by aaronsace** [comment]
So this one is working perfectly on your screenshot: 
![image](https://user-images.githubusercontent.com/21113644/36635553-fff32a12-19ae-11e8-8239-a56a971b1321.png)

So lets go back to MultiPoolMiner. 

Download/extract a fresh release from here: 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.2.4/MultiPoolMinerV2.7.2.4.zip

Add this to your command in the start.bat file: 
`-minername excavatornvidia2`

Run it then post logs and screenshot.

**Comment by mkirov0** [comment]
<img width="869" alt="screen shot 2018-02-25 at 12 55 03 am" src="https://user-images.githubusercontent.com/28104701/36636014-8ea5b308-19c6-11e8-8845-e997aca15152.png">
<img width="871" alt="screen shot 2018-02-25 at 12 56 47 am" src="https://user-images.githubusercontent.com/28104701/36636032-cb84a7ca-19c6-11e8-86a9-2f36ef25d705.png">
<img width="865" alt="screen shot 2018-02-25 at 12 59 16 am" src="https://user-images.githubusercontent.com/28104701/36636048-2b4a6776-19c7-11e8-8ddd-1e00ba78149e.png">
<img width="869" alt="screen shot 2018-02-25 at 1 01 15 am" src="https://user-images.githubusercontent.com/28104701/36636067-6c676948-19c7-11e8-9979-9076f9b78bfe.png">
and so it goes...

[MultiPoolMiner_2018-02-25_00-46-11.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1755415/MultiPoolMiner_2018-02-25_00-46-11.txt)
[MultiPoolMiner_2018-02-25_00-51-59.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1755416/MultiPoolMiner_2018-02-25_00-51-59.txt)
[MultiPoolMiner_2018-02-25_00-53-55.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1755417/MultiPoolMiner_2018-02-25_00-53-55.txt)
[MultiPoolMiner_2018-02-25.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1755418/MultiPoolMiner_2018-02-25.txt)

I can keep it running for longer if you think it will help.

**Comment by aaronsace** [comment]
You've not screenshot excavator so is it not there minimized at all?

**Comment by aaronsace** [comment]
This looks bad but I can't find out anything about that file: 
```
Unable to load DLL 'api-ms-win-core-job-l2-1-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
+ CategoryInfo          : NotSpecified: (:) [Start-Process], DllNotFoundException
+ FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.StartProcessCommand
+ PSComputerName        : localhost
```

**Comment by aaronsace** [comment]
Going back to the test I sent you, are you sure this worked?  
```
$Path = "C:\Users\aaron\MultiPoolMiner\Bin\Excavator\excavator.exe"
$Arguments = "-p 23456 -c Zpool_Blake2s_1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb_1_Nvidia.json -na"
$Process = Start-Job ([ScriptBlock]::Create("Start-Process $(@{desktop = "powershell"; core = "pwsh"}.$Global:PSEdition) `"-command ```$Process = (Start-Process '$($Path)' '$($Arguments)' -WorkingDirectory '$(Split-Path $Path)' -WindowStyle Minimized -PassThru).Id; Wait-Process -Id `$PID; Stop-Process -Id ```$Process`" -WindowStyle Hidden -Wait"))
```

**Comment by mkirov0** [comment]
Yes you are correct; excavator did not start at all. GPU-Z also did not show any load on the GPU.
Second test did not start excavator. 
It seems to be a problem on my end with that dll. I am looking for solutions in the mean time.

**Comment by UselessGuru** [comment]
@ arronsace: 

```
This looks bad but I can't find out anything about that file:

Unable to load DLL 'api-ms-win-core-job-l2-1-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
+ CategoryInfo          : NotSpecified: (:) [Start-Process], DllNotFoundException
+ FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.StartProcessCommand
+ PSComputerName        : localhost
```

I doubt that this related to excavator. In the log I can see that MPM attempted to start excavator a few times before, and there is no such error.

[Seems strongly related to this issue](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1377)

Excavator runs fine as a standalone application, but not via 'Start-Process'

**Comment by mkirov0** [comment]
@UselessGuru Thanks for referencing. I will start following the other issue.

**Comment by UselessGuru** [comment]
Excavator issues should be resolved with this commit:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/a0857c0757ac2577df7c2631e31d746383d5a442

Please open a new issue if you find the same issue is still valid.
