### ISSUE TITLE
console not clearing

### ISSUE THREAD

**Issue by G510Gamer** [MultiPoolMiner/MultiPoolMiner#1295]
in the prev builds the console window would clear itself on each update it no longer does this and makes it really hard to see what the most recent update is.
v2.7.1.4

**Comment by paulpoco** [comment]
Yes without clearing, it make it confusing what is going on actively.  Otherwise an excellent release.

**Comment by UselessGuru** [comment]
> Not sure why it was removed...

Get removed with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/4a5d90a968b0de895030ee8b7c6a70ce8aab6510#diff-69b5e62237d5f951ca1ac096869d0234

I quite liked keeping all output visible, it simplified troubles and shooting.

**Comment by aaronsace** [comment]
Ah, that's where it snuck in. Yeah, I tend to take it out when I'm testing. In normal usage though it's not much point leaving it trailing.
