### ISSUE TITLE
Updating changelogs

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1297]
Hi @aaronsace thanks for the updates lately.

Could you please update the changelogs between the versions? IMHO the changeling is now getting copy paste to the latest version without updating.

Thanks in advance.

**Comment by tbergeron** [comment]
There couldn't be a better changelog than the commit log itself: https://github.com/MultiPoolMiner/MultiPoolMiner/commits/master

Just see the commits up until which release you are using, you will see all changes. Also changes are all written down in the releases themselves. https://github.com/MultiPoolMiner/MultiPoolMiner/releases

Yes some changes are copy pasted, but I guess that's only to prevent people from digging too deep to see the latest changes. There's always differences between releases, just read it thoroughly.

**Comment by m-bosch** [comment]
every dot and comma I don't care, but if there are new variables to tune or stuff to exclude etc. it would be nice to know. this was before, but since 2.7.2 not (sub 1,2,3 and now 4).

**Comment by aaronsace** [comment]
I highlight everything on a new release. The final digit is bug fixes or very minor changes, not a new release. The exception being the new log monitor. 

I'm not copying and pasting this: 
https://github.com/MultiPoolMiner/MultiPoolMiner/commits/master
