### ISSUE TITLE
Removed -minerstatusurl from start.bat, but it keeps sending Miner Status

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1300]
My start.bat:

`-wallet [removed] -username [removed] -workername nvidiaworker -region europe -currency btc,usd,ltc,eth -type nvidia -poolname miningpoolhub -algorithm ethash,equihash,groestl,lyra2re2,lyra2z,neoscrypt,nist5,skein,keccak -ExcludeMinerName BMiner -interval 60 -donate 1 -watchdog -switchingprevention 3`

I have removed the `-minerstatusurl` parameter.

In the monitoring window:
```
2018-02-23 18:04:11 INFO: Pinging monitoring server.
2018-02-23 18:04:12 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
```

What data was sent?

Basic information:
- MultiPoolMinerV2.7.2.4.zip

**Comment by UselessGuru** [comment]
Check if it is config.txt. If so you need to remove it from config.txt too.

**Comment by borzaka** [comment]
I haven't touched the Config.txt, so I'am using the [default](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Config.txt).

So, I should remove following lines?
```
"MinerStatusURL": "$MinerStatusURL",
"MinerStatusKey": "$MinerStatusKey",
```

**Comment by UselessGuru** [comment]
Try putting this in start.bat

-minerstatusurl ""

**Comment by borzaka** [comment]
`-minerstatusurl ""`
```
The string is missing the terminator: ".
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```

`-minerstatusurl ''`
No error, but still sends data:
```
2018-02-23 18:35:32 INFO: Pinging monitoring server.
2018-02-23 18:35:33 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
```

I haven't deleted those two lines from the Config.txt.

**Comment by aaronsace** [comment]
I think you need to escape the quotation marks in the bat file for that method to work. 

Config file method would just be this: 
`"MinerStatusURL": "", `

**Comment by borzaka** [comment]
That worked, no more Miner Status updates in the monitoring window after I removed `$MinerStatusURL`. Thx.

I think if no `-minerstatusurl` present in the start.bat file, then no status updates should run.

**Comment by UselessGuru** [comment]
> I think if no -minerstatusurl present in the start.bat file, then no status updates should run.

Agree, created a [pull request](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1303)

**Comment by UselessGuru** [comment]
[Fixed with this commit](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1303)
