### ISSUE TITLE
New fancy parameter in dstm's ZCash Cuda miner 

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1301]
[Version 0.6](https://bitcointalk.org/index.php?topic=2021765.0)
- ui: add colorized output
`--color`

Please add this to the running parameters :)

_Or never mind, because we never see the miner windows in the new versions :(_

**Comment by aaronsace** [comment]
Should work, I added the colour back to the output: fcbe0af2f09d1483f69dd4d251b6e735f44563d9

**Comment by borzaka** [comment]
I have added myself, but it's not colorized:

![image](https://user-images.githubusercontent.com/1230402/36608316-c30b3a80-18c9-11e8-892d-347a5c165998.png)

Should look something like this:
![image](https://user-images.githubusercontent.com/1230402/36608435-1fbdb91a-18ca-11e8-9359-c55b79a7293c.png)

**Comment by UselessGuru** [comment]
The miner accepts the parameter, but it says 'color mode not supported'

**Comment by aaronsace** [comment]
Odd... I'm guessing DSTM is interacting with the console but the other miners are using escape sequences?

**Comment by UselessGuru** [comment]
I guess he detects the redirect, that's why it output 'color mode not supported'

**Comment by UselessGuru** [comment]
[Implemented with this commit](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1302)
