### ISSUE TITLE
Chinese characters in powershell

### ISSUE THREAD

**Issue by ehcorn** [MultiPoolMiner/MultiPoolMiner#1308]
So I guess this is relatively low priority, since my miner appears to be functioning normally, but my powershell looks like this: 
![image](https://user-images.githubusercontent.com/3020898/36623581-d042ec8e-18ba-11e8-8766-f96ca33ce7ce.png)

**Comment by Zalvador89** [comment]
Mine is the same...

**Comment by aaronsace** [comment]
What language is your operating system? 
Please can you post the logs files (drag and drop them onto the GitHub post)?

**Comment by aaronsace** [comment]
@Zalvador89 
Do you not have this log file? 
MultiPoolMiner_2018-02.txt

**Comment by Zalvador89** [comment]
This is the closeset, is that ok? No one with your specified name.
[MultiPoolMiner_2018-02-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754617/MultiPoolMiner_2018-02-24.txt)

**Comment by ehcorn** [comment]
here's my log file too
[MultiPoolMiner_2018-02-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754671/MultiPoolMiner_2018-02-24.txt)
I just checked my power shell and it appears to be working normally, so the log file from today might not have what you need. I pulled yesterday's logs as well: 
[MultiPoolMiner_2018-02-23_14-54-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754673/MultiPoolMiner_2018-02-23_14-54-05.txt)
[MultiPoolMiner_2018-02-23_14-51-53.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754674/MultiPoolMiner_2018-02-23_14-51-53.txt)
[MultiPoolMiner_2018-02-23_14-51-23.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754675/MultiPoolMiner_2018-02-23_14-51-23.txt)
[MultiPoolMiner_2018-02-23_14-48-55.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754676/MultiPoolMiner_2018-02-23_14-48-55.txt)
[MultiPoolMiner_2018-02-23_14-47-52.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754677/MultiPoolMiner_2018-02-23_14-47-52.txt)
[MultiPoolMiner_2018-02-23_14-45-21.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754678/MultiPoolMiner_2018-02-23_14-45-21.txt)
[MultiPoolMiner_2018-02-23_14-42-02.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754679/MultiPoolMiner_2018-02-23_14-42-02.txt)
[MultiPoolMiner_2018-02-23_14-40-56.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754680/MultiPoolMiner_2018-02-23_14-40-56.txt)
[MultiPoolMiner_2018-02-23_14-39-09.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754681/MultiPoolMiner_2018-02-23_14-39-09.txt)
[MultiPoolMiner_2018-02-23_14-36-27.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754682/MultiPoolMiner_2018-02-23_14-36-27.txt)
[MultiPoolMiner_2018-02-23_14-35-08.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754683/MultiPoolMiner_2018-02-23_14-35-08.txt)
[MultiPoolMiner_2018-02-23_14-25-48.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754684/MultiPoolMiner_2018-02-23_14-25-48.txt)
[MultiPoolMiner_2018-02-23_17-05-43.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754685/MultiPoolMiner_2018-02-23_17-05-43.txt)
[MultiPoolMiner_2018-02-23_16-54-36.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754686/MultiPoolMiner_2018-02-23_16-54-36.txt)
[MultiPoolMiner_2018-02-23_14-55-21.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1754687/MultiPoolMiner_2018-02-23_14-55-21.txt)

a few of these might contain some errors, so it's best to check the latest from the 23rd since that should contain my functional miner, I had some issues with the command line during initial setup.

**Comment by cheebeez** [comment]
Same bug

**Comment by Nabegh** [comment]
I had the same issue. Updating to PowerShell 6.0.1 seems to have fixed the issue
https://github.com/PowerShell/PowerShell/releases

**Comment by aaronsace** [comment]
Can you all try the solution from @Nabegh

**Uninstall PowerShell first** then install this one: 
https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/PowerShell-6.0.1-win-x64.msi

**Comment by ijardine** [comment]
Had the same issue, I just left it and it seemed to fix itself (or maybe it auto updates?). Second machine I installed it on had no issue at all

**Comment by Zalvador89** [comment]
I had powershell 6.0.1 installed the first time. Also tried uninstall/reinstall but same issue...

**Comment by almothafar** [comment]
Got the same issue with freshly installed windows 10

**Comment by Nickduino** [comment]
@UselessGuru I wouldn't call it fixed, people still have this issue (including me): https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1406

**Comment by UselessGuru** [comment]
This should fix it: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1384
