### ISSUE TITLE
Prospector appears to be trying to use aaronsace as the username on MiningPoolHub

### ISSUE THREAD

**Issue by NastyNateu** [MultiPoolMiner/MultiPoolMiner#1309]
Here is the failed benchmark parameters:  

Status: Failed

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 01 Minutes 3 Times  Bin\Prospector\prospector.exe -c MiningPoolHub_Ethash_aaronsace.multipoolminer.toml

The first time I got MPM running it worked fine. Rebooted my computer and it was crippled with write/access permission errors. Almost gave up after rebooting again a few times but it mysteriously worked fine and mostly finished the benchmark up until this failure. 

In the time I spent writing this the benchmarks for the two prospector miners finished, the Ethash Prospector instance failed, the cryptonight succeeded, but now both aren't on the benchmark list anymore. The bminer is definitely holding up the benchmark though, I assume it would be done if this wasn't happening. 

I'm sorry if this isn't the proper format, this is my first time posting to github.

**Comment by UselessGuru** [comment]
> 0 H/s 00 Days 00 Hours 01 Minutes 3 Times Bin\Prospector\prospector.exe -c MiningPoolHub_Ethash_aaronsace.multipoolminer.toml

Look at the logs. You will notice that this happened about 1h after the start. MPM is on its donation run (aaronsace)

> Rebooted my computer and it was crippled with write/access permission errors.

This usually happens when you computer crashes. MPM detects and recreates broken stat files.

**Comment by NastyNateu** [comment]
Oh alright, I think that was about an hour into the benchmarking so that makes sense, the dev mining happens an hour after startup every time and then 10 minutes per day?  I thought the benchmark was broken because of the username, it failed so many times. 

My computer didn't crash at all, is there a proper way to close the running processes so things don't get broken? What I did to fix this (I think) is copying the stats folder and then uncompressed a new MPM folder, could have been an issue with Powershell though. 

I have a question about the logs too. Are there any plans to add timestamps to the powershell logs? Or is there a trick to figuring out what time a certain event happened in the MPM logs?

**Comment by NastyNateu** [comment]
Thanks. 

2. There was something weird going on with my windows permissions, and powershell didn't install properly the first time. I was also having issues because I added a folder in the pools folder to hold the unused pool files. I've got most of that sorted now. My PowerShell is still black but everything seems to work.

3. I'm talking about the PowerShell Transcript that's labeled like: MultiPoolMiner_2018-2-24_13-52-58.txt. I think it would be decent to see exactly what time your benchmarks were taken at.  Like in my transcript from today I've got two consecutive benchmarks that are quite different in both order and profitability, but I can't tell exactly when this happened to check other logs.   Could you tell me if the transcript label (13-52-58) means the transcript was started at 1:52 or if it means it ended at 1:52 (if that's even what those number mean)

Sorry if I seem ignorant, I just started using this last evening. I also want to thank you for producing this wonderful program, it's amazing and you deserve every bit of profit you make from it. Thanks!

**Comment by UselessGuru** [comment]
> I added a folder in the pools folder to hold the unused pool files.

Don't do this. Also do NOT keep .BAK files or any non-MPM files in the folders 'Stats', 'Miners' and 'Pools'
