### ISSUE TITLE
Claymore Neoscrypt miner for AMD

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1311]
Hot off the presses

https://bitcointalk.org/index.php?topic=3012600.0

from the thread:
For stock cards I get the following speeds ("-powlim 50"):

following from thread:
RX480 - 930KH/s ("-a 2").
RX470 - 900KH/s ("-a 2").
RX580nitro+ - 1000KH/s ("-a 1").
Fury Nano - 1350KH/s.
390X - 1150KH/s.
270X - 450KH/s.
380X - 720KH/s.
280X - 825KH/s.
RX460 - 380KH/s.
Vega64 - 2200KH/s.

line that i added to ClaymoreAMD.txt  to master dated 01/16/2018

    {
        "Type":  "AMD",
        "Path":  ".\\Bin\\Neoscrypt-Claymore\\NeoScryptMiner.exe",
        "Arguments":  "-r -1 -mport 13333 -pool $($Pools.NeoScrypt.Host):$($Pools.NeoScrypt.Port) -wal $($Pools.NeoScrypt.User) -psw $($Pools.NeoScrypt.Pass)",
        "HashRates":  {"NeoScrypt":  "$($Stats.ClaymoreAmd_NeoScrypt_HashRate.Week)"},
        "API":  "Claymore",
        "Port":  "13333"
    }

benches, but doesn't show up on the list. (a hashrate file is created in the stat folder with the correct benchmark, but it doesn't show up on the list)
i little help please

I'm running drivers 18.2.2

**Comment by alucard20724** [comment]
figured it out... kinda.  it's being saved in the text file has kh/s instead of Mh/s..it's off by a 1000

**Comment by UselessGuru** [comment]
Miner is available: https://github.com/MultiPoolMiner/MultiPoolMiner/commit/9cf31285c2a09d9655e6224ae6771fda1e09741a
