### ISSUE TITLE
MPM chooses 2nd best after a while

### ISSUE THREAD

**Issue by orangeclaimer** [MultiPoolMiner/MultiPoolMiner#1312]
Hi,

I just downloaded newest version of MPM (24.02.2018) from Github and let it run all the benchmarks.
It did this on two systems (both WIN 10 64bit) and I got same results.

1st Excavator
2nd Palgin
3rd ccminernanashi
 
After Benchmarks:
MPM starts Excavator and mines neoscrypt for 1 min and than says that "excavator is no longer the most profitable miner" and starts Palgin or sometimes ccminernanashi (even though excavators Hashrate is still higher than those two). Than after another minute it goes back to Excavator and its starts all over...

I have it run for 2 hours and still got same thing happening (not only for neoscrypt alone also for others like equihash: Bimer goes to DSTM for example) all the time. I ended up putting Palgin and ccminernanashit away but still I would like to have them as a backup (and others too I can guess but don't know if that is just me).

**Comment by UselessGuru** [comment]
Please post log files. TIA

**Comment by borzaka** [comment]
I'am experiencing the same: MPM choosed the 2nd fastest miner on the same algorithm;
```
2018-02-25 23:40:23 INFO: Closing miner (Dstm) because it is no longer the most profitable. 
2018-02-25 23:40:23 INFO: Starting miner (ExcavatorNvidia1): 'C:\Users\Attila\Downloads\MultiPoolMinerV2.7.2.4\Bin\Excavator\excavator.exe -p 23456 -c MiningPoolHub_Equihash_borzaka.nvidiaworker_1_Nvidia.json -na'
```

(DSTM is an Equihash miner as well the next launched Excavator with the given parameters and config file.)

Logs:
- [MultiPoolMiner_2018-02-25.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1756810/MultiPoolMiner_2018-02-25.txt)
- [MultiPoolMiner_2018-02-25_23-13-58.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1756811/MultiPoolMiner_2018-02-25_23-13-58.txt)

**Comment by aaronsace** [comment]
These two lines conflict: 

https://github.com/MultiPoolMiner/MultiPoolMiner/blob/9a67e7463436fde9683a7d514c18380f70edc51a/MultiPoolMiner.ps1#L269

https://github.com/MultiPoolMiner/MultiPoolMiner/blob/9a67e7463436fde9683a7d514c18380f70edc51a/MultiPoolMiner.ps1#L459

**Comment by platonicjesus** [comment]
Having the same issue just with different currencies. Have to reset the profit every couple of hours to fix it. Thanks in advance!

**Comment by orangeclaimer** [comment]
Take a look at the picture. After a while it goes back and starts the cycle over.

[BMiner-1880_2018-02-24_14-17-34.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1758742/BMiner-1880_2018-02-24_14-17-34.txt)
![mpm why](https://user-images.githubusercontent.com/36467760/36672674-7ab778d2-1b00-11e8-9971-6593e253e1ea.jpg)

**Comment by boro2000** [comment]
Well, can be easily resolved by adding a flag to store, if pools are in sync.

Line 265:
```
    Write-Log "Selecting best pool for each algorithm. "
    $AllPools.Algorithm | ForEach-Object {$_.ToLower()} | Select-Object -Unique | ForEach-Object {$Pools | Add-Member $_ ($AllPools | Sort-Object -Descending {$Config.PoolName.Count -eq 0 -or (Compare-Object $Config.PoolName $_.Name -IncludeEqual -ExcludeDifferent | Measure-Object).Count -gt 0}, {($Timer - $_.Updated).TotalMinutes -le ($SyncWindow * $Strikes)}, {$_.StablePrice * (1 - $_.MarginOfError)}, {$_.Region -EQ $Config.Region}, {$_.SSL -EQ $Config.SSL} | Where-Object Algorithm -EQ $_ | Select-Object -First 1)}
    if (($Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {$Pools.$_} | Measure-Object Updated -Minimum -Maximum | ForEach-Object {$_.Maximum - $_.Minimum} | Select-Object -ExpandProperty TotalMinutes) -gt $SyncWindow) {
        Write-Log -Level Warn "Pool prices are out of sync ($([Int]($Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {$Pools.$_} | Measure-Object Updated -Minimum -Maximum | ForEach-Object {$_.Maximum - $_.Minimum} | Select-Object -ExpandProperty TotalMinutes)) minutes). "
        $Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {$Pools.$_ | Add-Member Price_Bias ($Pools.$_.StablePrice * (1 - ($Pools.$_.MarginOfError * $Config.SwitchingPrevention * [Math]::Pow($DecayBase, $DecayExponent)))) -Force}
        $PoolsInSync = $false
    }
    else {
        $Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {$Pools.$_ | Add-Member Price_Bias ($Pools.$_.Price * (1 - ($Pools.$_.MarginOfError * $Config.SwitchingPrevention * [Math]::Pow($DecayBase, $DecayExponent)))) -Force}
        $PoolsInSync = $true
    }
```
..

Line 460+
```
    #Don't penalize active miners
    $ActiveMiners | Where-Object {$_.GetStatus() -eq [MinerStatus]::Running} | ForEach-Object {$_.Profit_Bias = if ($PoolsInSync) {$_.Profit} else {$_.Profit_Comparison}}
```

**Comment by romajc84** [comment]
I always just remove the algos from the less profitable miners.  So only the top miner is able to miner each algo.  Only takes a minute to do.
