### ISSUE TITLE
MPM speeds off MINING with 3 RX570's

### ISSUE THREAD

**Issue by nickvasel** [MultiPoolMiner/MultiPoolMiner#1313]
I just got my AMD rig up and running with 3 RX570's modded and OCed, Planning to go with 3 moreRX570's total of 6. Hash rates as follows: 
Phoenix miner=ETHASH: 89.28 MH/s <-that's good 
ClaymoreAMD=EQUIHASH= 836 H/S <-- not good 
Lyra2RE2= Sgminer= 31 MH/s <--not good 
Lyra2z= Sgminer=1.10 MH/s <--not good
Will not run Skein log says "redirect not allowed"
using MPM ver. 2.7.2.4 latest commit downloaded last night
Let me know what log files you need.

**Comment by aaronsace** [comment]
When you say 'not good' do you mean they are wrong? 
Have you tried increasing the interval setting from '60' to '180' to allow more time for the miners to benchmark?

**Comment by nickvasel** [comment]
By not good I mean "slow speeds" I set interval to 180
Not sure why Skein is not working. log just says redirect
Running new benckmarks now, will let you know...

**Comment by nickvasel** [comment]
On my other rig with 6 1070's I get around 2.85 kh/s for equihash, I would expect it to be a little lower but not what I'm seeing with the RX570's.
Benchmark just finished equihash= 826 h/s

**Comment by aaronsace** [comment]
I don't think the issue is with MultiPoolMiner then. Try running Claymore on it's own. 

The command that MultiPoolMiner is using is displayed on the screen.

**Comment by nickvasel** [comment]
I just posted the logs, looks like there are some errors?

**Comment by aaronsace** [comment]
MultiPoolMiner is reading it correctly then: 
ZEC: GPU0 275.783 H/s, GPU1 274.588 H/s, GPU2 274.844 H/s

If you are sure that they should be faster then, try downloading the latest drivers from the AMD website and Claymore's documentation on the settings: https://bitcointalk.org/index.php?topic=1670733.0

**Comment by UselessGuru** [comment]
> In less you want to mess with why Skein is not working , you can close

Log please. What miner is not properly mining the Skein algo?

**Comment by nickvasel** [comment]
Sgminer and Sgminerskein, here are the log files.

**Comment by nickvasel** [comment]
For what ever reason Sgminer wont run on my AMD rig, could be the overclocking settings I'm using not sure.

**Comment by UselessGuru** [comment]
> could be the overclocking settings I'm using not sure.

Then try without OK first ;-). Unfortunately I cannot assist further because I do not have AMD hardware
