### ISSUE TITLE
error when downloading miners

### ISSUE THREAD

**Issue by PontiacGTX** [MultiPoolMiner/MultiPoolMiner#1314]
When it is tryign to download CPU miner for Corei7

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:463 char:152
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:463 char:152
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:463 char:152
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:463 char:152
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\UsersUser\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:463 char:152
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:463 char:170
+ ... s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:463 char:170
+ ... s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:465 char:163
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:465 char:163
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:465 char:163
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:465 char:163
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:465 char:163
+ ... ctiveMiners | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\User\Desktop\MultiPoolMiner\MultiPoolMiner.ps1:465 char:181
+ ... s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand # #

**Comment by aaronsace** [comment]
Please download the full graphics drivers from the AMD/NVidia website.

**Comment by PontiacGTX** [comment]
ok I will try with newer drivers, also found that when I try to run the first time the start.bat when modifying the miner parameter for algorithm it doesnt benchmark  Lyra2Rev2, it tries to benchmark first the first 3 algorithm (cryptonight,ethash,equihash) and then CPU, but doesnt starting Lyra2rev2 miner/download , does it doe it sequentially for the first 3 CPU+gpu miner or it only benchmark 3 at a time?

**Comment by aaronsace** [comment]
It benchmarks as many miners at the same time as it can.

**Comment by PontiacGTX** [comment]
Hey Aaron.. I have another issue when the miner tries to connect to MPH to mine with CPU-JayDDee it shows

[2018-02-25 18:50:48] Starting Stratum on stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:20581
[2018-02-25 18:50:48] 8 miner threads started, using 'lyra2z' algorithm.
[2018-02-25 18:50:48] stratum_subscribe send failed
[2018-02-25 18:50:48] ...retry after 10 seconds

**Comment by UselessGuru** [comment]
@PontiacGTX 
Please do not mix different issues in the same thread - it makes them very hard to track.

> [2018-02-25 18:50:48] Starting Stratum on stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:20581
> [2018-02-25 18:50:48] 8 miner threads started, using 'lyra2z' algorithm.
> [2018-02-25 18:50:48] stratum_subscribe send failed
> [2018-02-25 18:50:48] ...retry after 10 seconds

Try running the same command 'standalone (copy/paste from MPM window). What happens?
This error is usually caused by the pool.

**Comment by UselessGuru** [comment]
> here is what the miner says @UselessGuru
Try running the **same command 'standalone'** (copy/paste from MPM window, do NOT rund via MPM). What happens?

**Comment by PontiacGTX** [comment]
it works just fine as powershell shows

> C:\Users\User\Desktop\MultiPoolMiner\Bin\cpuminer-opt-3.8.2.1-windows>cpuminer-aes-avx.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025 -u PontiacGTX.1 -p x
> 
>          **********  cpuminer-opt 3.8.2.1  ***********
>      A CPU miner with multi algo support and optimized for CPUs
>      with AES_NI and AVX2 and SHA extensions.
>      BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT
> 
> CPU:        Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz.
> SW built on Feb 17 2018 with GCC 5.3.1.
> CPU features: SSE2 AES AVX.
> SW features: SSE2 AES AVX.
> Algo features: AVX AVX2.
> Start mining with AVX.
> 
> [2018-02-26 09:30:56] Starting Stratum on stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025
> [2018-02-26 09:30:56] 8 miner threads started, using 'lyra2z' algorithm.
> [2018-02-26 09:31:01] Stratum difficulty set to 10
> [2018-02-26 09:31:04] CPU #1: 65.54 kH, 34.66 kH/s
> [2018-02-26 09:31:04] CPU #3: 65.54 kH, 34.66 kH/s
> [2018-02-26 09:31:04] CPU #5: 65.54 kH, 34.66 kH/s
> [2018-02-26 09:31:04] CPU #2: 65.54 kH, 34.38 kH/s
> [2018-02-26 09:31:04] CPU #7: 65.54 kH, 33.82 kH/s
> [2018-02-26 09:31:04] CPU #0: 65.54 kH, 33.82 kH/s
> [2018-02-26 09:31:04] CPU #6: 65.54 kH, 33.55 kH/s
> [2018-02-26 09:31:04] CPU #4: 65.54 kH, 33.55 kH/s
> [2018-02-26 09:31:43] lyra2z block 76074, diff 26611.450
> [2018-02-26 09:31:43] CPU #2: 1337.47 kH, 33.87 kH/s
> [2018-02-26 09:31:43] CPU #3: 1360.63 kH, 34.45 kH/s
> [2018-02-26 09:31:43] CPU #6: 1342.33 kH, 34.04 kH/s
> [2018-02-26 09:31:43] CPU #1: 1337.79 kH, 33.87 kH/s
> [2018-02-26 09:31:43] CPU #7: 1323.64 kH, 33.55 kH/s
> [2018-02-26 09:31:43] CPU #0: 1274.28 kH, 32.30 kH/s
> [2018-02-26 09:31:43] CPU #4: 1269.46 kH, 32.19 kH/s
> [2018-02-26 09:31:43] CPU #5: 1323.56 kH, 33.51 kH/s
> [2018-02-26 09:32:43] CPU #6: 2042.14 kH, 34.04 kH/s
> [2018-02-26 09:32:43] CPU #7: 2012.91 kH, 33.51 kH/s
> [2018-02-26 09:32:44] CPU #3: 2066.71 kH, 34.28 kH/s
> [2018-02-26 09:32:44] CPU #2: 2032.34 kH, 33.71 kH/s
> [2018-02-26 09:32:44] CPU #5: 2010.40 kH, 33.28 kH/s
> [2018-02-26 09:32:44] CPU #4: 1931.29 kH, 31.93 kH/s
> [2018-02-26 09:32:45] CPU #1: 2032.02 kH, 33.15 kH/s
> [2018-02-26 09:32:45] CPU #0: 1937.86 kH, 31.36 kH/s
> [2018-02-26 09:33:43] CPU #2: 2022.31 kH, 33.81 kH/s
> [2018-02-26 09:33:43] CPU #6: 2042.58 kH, 33.97 kH/s
> [2018-02-26 09:33:43] CPU #7: 2010.32 kH, 33.40 kH/s
> [2018-02-26 09:33:44] CPU #5: 1996.87 kH, 33.29 kH/s
> [2018-02-26 09:33:44] CPU #3: 2056.89 kH, 34.19 kH/s
> [2018-02-26 09:33:44] CPU #1: 1988.71 kH, 33.31 kH/s
> [2018-02-26 09:33:44] CPU #4: 1915.81 kH, 31.62 kH/s
> [2018-02-26 09:33:45] CPU #0: 1881.77 kH, 31.16 kH/s
>

**Comment by UselessGuru** [comment]
We can see that the parameters to run the miner are correct. What do does it say in the individual miner logs (in folder 'Logs')? Can you find any hints on why thinks that the miner fails?

**Comment by PontiacGTX** [comment]
In Multipoolminer\logs


 file 
CpuminerJayddeeAesavx-4048_2018-02-25_17-31-06

>         **********  cpuminer-opt 3.7.4  *********** 
>      A CPU miner with multi algo support and optimized for CPUs
>      with AES_NI and AVX extensions.
>      BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT
>      Forked from TPruvot's cpuminer-multi with credits
>      to Lucas Jones, elmad, palmd, djm34, pooler, ig0tik3d,
>      Wolf0, Jeff Garzik and Optiminer.
> 
> CPU:        Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
> CPU features: SSE2 AES AVX
> SW built on Nov 28 2017 with GCC 4.8.3
> SW features: SSE2 AES AVX
> Algo features: SSE2 AES AVX AVX2
> Start mining with SSE2 AES AVX
> 
> [2018-02-25 17:31:06] 8 miner threads started, using 'lyra2z' algorithm.[0m
> [2018-02-25 17:31:06] Starting Stratum on stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:20581[0m
> [2018-02-25 17:31:06][31m stratum_subscribe send failed[0m
> [2018-02-25 17:31:06][31m ...retry after 10 seconds[0m
> [2018-02-25 17:31:17][31m stratum_subscribe send failed[0m
> [2018-02-25 17:31:17][31m ...retry after 10 seconds[0m
> [2018-02-25 17:31:27][31m stratum_subscribe send failed[0m
> [2018-02-25 17:31:27][31m ...retry after 10 seconds[0m
> [2018-02-25 17:31:37][31m stratum_subscribe send failed[0m
> [2018-02-25 17:31:37][31m ...retry after 10 seconds[0m
> [2018-02-25 17:31:48][33m Stratum difficulty set to 5[0m
> [2018-02-25 17:31:55] CPU #7: 65.54 kH, 33.47 kH/s[0m
> [2018-02-25 17:31:55] CPU #5: 65.54 kH, 32.83 kH/s[0m
> [2018-02-25 17:31:55] CPU #6: 65.54 kH, 33.11 kH/s[0m
> [2018-02-25 17:31:55] CPU #2: 65.54 kH, 29.41 kH/s[0m
> [2018-02-25 17:31:55] CPU #4: 65.54 kH, 31.40 kH/s[0m
> [2018-02-25 17:31:55] CPU #3: 65.54 kH, 29.45 kH/s[0m
> [2018-02-25 17:31:55] CPU #1: 65.54 kH, 26.40 kH/s[0m
> [2018-02-25 17:31:56] CPU #0: 65.54 kH, 21.36 kH/s[0m
> [2018-02-25 17:32:57] CPU #3: 1766.88 kH, 28.82 kH/s[0m
> [2018-02-25 17:32:59] CPU #7: 2007.94 kH, 31.24 kH/s[0m
> [2018-02-25 17:32:59] CPU #2: 1764.50 kH, 27.56 kH/s[0m
> [2018-02-25 17:32:59] CPU #6: 1986.62 kH, 30.88 kH/s[0m
> [2018-02-25 17:33:01] CPU #4: 1883.77 kH, 28.84 kH/s[0m
> [2018-02-25 17:33:02] CPU #5: 1969.69 kH, 29.51 kH/s[0m
> [2018-02-25 17:33:02] CPU #1: 1583.85 kH, 23.79 kH/s[0m
> [2018-02-25 17:33:29] CPU #0: 1281.65 kH, 13.75 kH/s[0m
> 

CpuminerJayddeeAesavx-4048_2018-02-24_19-00-28

File


       **********  cpuminer-opt 3.7.4  *********** 
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT
     Forked from TPruvot's cpuminer-multi with credits
     to Lucas Jones, elmad, palmd, djm34, pooler, ig0tik3d,
     Wolf0, Jeff Garzik and Optiminer.

CPU:        Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
CPU features: SSE2 AES AVX
SW built on Nov 28 2017 with GCC 4.8.3
SW features: SSE2 AES AVX
Algo features: SSE2 AES AVX AVX2
Start mining with SSE2 AES AVX

[2018-02-24 19:00:28] Starting Stratum on stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025[0m
[2018-02-24 19:00:28] 8 miner threads started, using 'lyra2z' algorithm.[0m
[2018-02-24 19:00:29][33m Stratum difficulty set to 10[0m
[2018-02-24 19:00:31] CPU #7: 65.54 kH, 32.62 kH/s[0m
[2018-02-24 19:00:31] CPU #3: 65.54 kH, 31.59 kH/s[0m
[2018-02-24 19:00:31] CPU #2: 65.54 kH, 31.50 kH/s[0m
[2018-02-24 19:00:31] CPU #1: 65.54 kH, 30.78 kH/s[0m
[2018-02-24 19:00:31] CPU #6: 65.54 kH, 30.82 kH/s[0m
[2018-02-24 19:00:31] CPU #5: 65.54 kH, 28.08 kH/s[0m
[2018-02-24 19:00:31] CPU #0: 65.54 kH, 27.36 kH/s[0m
[2018-02-24 19:00:37] CPU #4: 65.54 kH, 8103.48 H/s[0m
[2018-02-24 19:01:00] CPU #4: 486.21 kH, 20.78 kH/s[0m
[2018-02-24 19:01:44][33m Stratum difficulty set to 7[0m
[2018-02-24 19:01:52] CPU #1: 1846.59 kH, 22.74 kH/s[0m
[2018-02-24 19:01:53] CPU #2: 1890.11 kH, 23.17 kH/s[0m
[2018-02-24 19:01:53] CPU #3: 1895.58 kH, 23.15 kH/s[0m
[2018-02-24 19:01:55] CPU #0: 1641.41 kH, 19.73 kH/s[0m
[2018-02-24 19:02:01] CPU #5: 1685.05 kH, 18.75 kH/s[0m
[2018-02-24 19:02:04] CPU #6: 1849.19 kH, 20.00 kH/s[0m
[2018-02-24 19:02:09] CPU #7: 1956.94 kH, 19.88 kH/s[0m
[2018-02-24 19:02:15] CPU #4: 1247.09 kH, 16.82 kH/s[0m
[2018-02-24 19:02:37] CPU #5: 1125.18 kH, 31.66 kH/s[0m
[2018-02-24 19:02:40][33m Stratum difficulty set to 5[0m
[2018-02-24 19:02:40] CPU #6: 1200.03 kH, 32.79 kH/s[0m
[2018-02-24 19:02:43] CPU #3: 1388.90 kH, 27.90 kH/s[0m
[2018-02-24 19:02:45] CPU #2: 1390.26 kH, 26.39 kH/s[0m
[2018-02-24 19:02:46] CPU #7: 1192.57 kH, 32.31 kH/s[0m
[2018-02-24 19:02:48] CPU #4: 1009.06 kH, 29.95 kH/s[0m
[2018-02-24 19:03:22] CPU #1: 1364.59 kH, 15.28 kH/s[0m
[2018-02-24 19:03:37] CPU #0: 1183.95 kH, 11.61 kH/s[0m
[2018-02-24 19:03:58] CPU #5: 1899.43 kH, 23.43 kH/s[0m
[2018-02-24 19:04:27] CPU #6: 1967.29 kH, 18.34 kH/s[0m
[2018-02-24 19:04:30] CPU #4: 1796.78 kH, 17.67 kH/s[0m
[2018-02-24 19:04:31] CPU #3: 1674.07 kH, 15.42 kH/s[0m
[2018-02-24 19:04:34] CPU #7: 1938.74 kH, 17.93 kH/s[0m
[2018-02-24 19:04:38] CPU #1: 917.02 kH, 11.97 kH/s[0m
[2018-02-24 19:04:40] CPU #2: 1583.55 kH, 13.82 kH/s[0m
[2018-02-24 19:04:44] CPU #0: 696.53 kH, 10.33 kH/s[0m
[2018-02-24 19:05:02] CPU #6: 1100.56 kH, 31.74 kH/s[0m
[2018-02-24 19:05:04] CPU #3: 925.40 kH, 28.33 kH/s[0m
[2018-02-24 19:05:05] CPU #5: 1405.80 kH, 20.75 kH/s[0m
[2018-02-24 19:05:06] CPU #4: 1060.15 kH, 29.48 kH/s[0m
[2018-02-24 19:05:08] CPU #7: 1075.80 kH, 32.24 kH/s[0m
[2018-02-24 19:05:14] CPU #2: 829.44 kH, 24.45 kH/s[0m
[2018-02-24 19:05:45] CPU #0: 619.76 kH, 10.13 kH/s[0m
[2018-02-24 19:05:47] CPU #1: 718.43 kH, 10.39 kH/s[0m
[2018-02-24 19:06:05] CPU #5: 1245.02 kH, 20.82 kH/s[0m
[2018-02-24 19:06:10] CPU #0: 607.80 kH, 24.36 kH/s[0m
[2018-02-24 19:06:23] CPU #6: 1904.49 kH, 23.54 kH/s[0m
[2018-02-24 19:06:26] CPU #4: 1769.08 kH, 22.09 kH/s[0m
[2018-02-24 19:06:30] CPU #3: 1699.56 kH, 19.79 kH/s[0m
[2018-02-24 19:06:33] CPU #1: 623.11 kH, 13.54 kH/s[0m
[2018-02-24 19:07:01] CPU #7: 1934.19 kH, 17.17 kH/s[0m
[2018-02-24 19:07:07] CPU #2: 1466.84 kH, 12.91 kH/s[0m
[2018-02-24 19:07:11] CPU #5: 1248.92 kH, 18.98 kH/s[0m
[2018-02-24 19:07:24] CPU #7: 760.79 kH, 31.90 kH/s[0m
[2018-02-24 19:07:24][01;37m [32mAccepted[01;37m 1/1 (100%), 10.08 MH, 167.10 kH/s[0m
[2018-02-24 19:07:33] CPU #4: 1325.39 kH, 19.70 kH/s[0m
[2018-02-24 19:07:35] CPU #6: 1412.16 kH, 19.55 kH/s[0m
[2018-02-24 19:07:36] CPU #2: 774.43 kH, 26.81 kH/s[0m
[2018-02-24 19:07:39] CPU #3: 1187.53 kH, 17.11 kH/s[0m
[2018-02-24 19:07:45] CPU #0: 1461.38 kH, 15.36 kH/s[0m
[2018-02-24 19:07:47] CPU #5: 1138.50 kH, 31.39 kH/s[0m
[2018-02-24 19:08:17] CPU #1: 812.52 kH, 7865.96 H/s[0m
[2018-02-24 19:08:40] CPU #1: 471.96 kH, 20.37 kH/s[0m
[2018-02-24 19:08:42] CPU #6: 1173.19 kH, 17.69 kH/s[0m
[2018-02-24 19:08:42] CPU #3: 1026.83 kH, 16.32 kH/s[0m
[2018-02-24 19:08:42] CPU #4: 1181.91 kH, 17.13 kH/s[0m
[2018-02-24 19:08:55] CPU #7: 1913.94 kH, 21.09 kH/s[0m
[2018-02-24 19:09:05] CPU #2: 1608.85 kH, 18.08 kH/s[0m
[2018-02-24 19:09:14] CPU #0: 921.83 kH, 10.42 kH/s[0m
[2018-02-24 19:09:26] CPU #6: 1061.13 kH, 23.90 kH/s[0m
[2018-02-24 19:09:27] CPU #4: 1027.92 kH, 22.84 kH/s[0m
[2018-02-24 19:09:30] CPU #5: 1883.16 kH, 18.38 kH/s[0m
[2018-02-24 19:09:35] CPU #3: 978.91 kH, 18.41 kH/s[0m
[2018-02-24 19:09:35] CPU #1: 1222.09 kH, 21.94 kH/s[0m
[2018-02-24 19:09:45] CPU #0: 625.03 kH, 19.96 kH/s[0m
[2018-02-24 19:09:52] CPU #2: 1084.52 kH, 23.19 kH/s[0m
[2018-02-24 19:09:54] CPU #7: 1265.35 kH, 21.62 kH/s[0m
[2018-02-24 19:10:10] CPU #3: 1104.61 kH, 31.42 kH/s[0m
[2018-02-24 19:10:22] CPU #5: 1103.04 kH, 21.20 kH/s[0m
[2018-02-24 19:10:22] CPU #1: 1316.38 kH, 28.23 kH/s[0m
[2018-02-24 19:10:22] CPU #6: 1433.78 kH, 25.35 kH/s[0m
[2018-02-24 19:10:34] CPU #0: 1197.54 kH, 24.49 kH/s[0m
[2018-02-24 19:10:43] CPU #2: 1391.18 kH, 27.07 kH/s[0m
[2018-02-24 19:10:54] CPU #4: 1370.63 kH, 15.88 kH/s[0m

**Comment by UselessGuru** [comment]
@PontiacGTX 

Please apologize: But where is the problem now? If there is a problem with a miner you can find the error message in the log file (basically screen output redirected to a file).

To post logs you can drag/drop them directly here.

**Comment by PontiacGTX** [comment]
the problem is that MPM miner in CMD does shows that Cpuminer-Opt has failed

**Comment by UselessGuru** [comment]
> edit it seems the issue is the miner shows that AVX2 doesnt work with CPUs that lacks this hw so it reports the issue...

which is fine. There is no easy powershell command to determine the CPU capabilities and filter the available miners.

Just let the miner fail 3 times and they will be disabled permanently (0 hash rate).

**Comment by PontiacGTX** [comment]
Ok that was my only concern
