### ISSUE TITLE
A Hash Pool - wrong password format?

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1315]
From the [site](https://www.ahashpool.com/):
> <OPTIONS> must have c=BTC as one of the parameters. For example: ID=Rig01,c=BTC

Current announcement, where they provice a sample command line:
> Announcement: [2018-02-22 04:52 UTC] We are getting lots of queries on how to use Claymore-Dual miner v11.0 to dual mine Blake2s on Ahashpool. Here's the command line that works: 
> EthDcrMiner64.exe -epool [ETH_Pool_Address:ETH_Pool_Port] -ewal [ETH_Pool_ETH_Wallet_Address] -epsw x -dpool stratum+tcp://blake2s.mine.ahashpool.com:5766 -dwal [AhashPool_BTC_Wallet_Address] -dpsw ID=Rig001,c=BTC -dcoin blake2s -dcri 27 -mode 0

So, based on this, password option should be `ID=workername,c=BTC`, right? Currently MPM uses `workername,c=BTC`.
I don't have a long experience with A Hash Pool, but I don't want to lose mining time because of a wrong setting.

Can you check it guys?

**Comment by UselessGuru** [comment]
> I don't have a long experience with A Hash Pool, but I don't want to lose mining time because of a wrong setting.

There is no need for 'ID='. The only important parameter is the correct currency 'c=BTC'
As long a can see profit being accumulated @ the pool then all is fine.

```
<OPTIONS> must have c=BTC as one of the parameters. For example: ID=Rig01,c=BTC
If you fail to correctly set the currency to BTC, you will not receive anything.
```

**Comment by borzaka** [comment]
OK, but in every sample they reference `ID=` as well.
I started to see my earnings at the pool. Hope when I reach the limit, the payout will be successful. I will report back.

**Comment by UselessGuru** [comment]
> I started to see my earnings at the pool.

Then all will be fine.

**Comment by aaronsace** [comment]
The worker ID is kind of made up on these kind of pools. Basically, if the 'passwords' (pools don't actually have passwords so they get repurposed as a text input) are different then they will get grouped separately.
