### ISSUE TITLE
Powershell errors in output

### ISSUE THREAD

**Issue by kennydust** [MultiPoolMiner/MultiPoolMiner#1316]
Powershell 6 is installed. However, I get these errors in the output whenever the miner switches. Ignore or is there some way to address on my end?

& : The specified module 'C:\Miners\MultiPoolMinerV2.7.2.4\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Miners\MultiPoolMinerV2.7.2.4\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Miners\Multi...ls\Include.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

& : The specified module 'C:\Miners\MultiPoolMinerV2.7.2.4\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Miners\MultiPoolMinerV2.7.2.4\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Miners\Multi...ls\Include.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

& : The specified module 'C:\Miners\MultiPoolMinerV2.7.2.4\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Miners\MultiPoolMinerV2.7.2.4\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Miners\Multi...ls\Include.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

& : The specified module 'C:\Miners\MultiPoolMinerV2.7.2.4\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Miners\MultiPoolMinerV2.7.2.4\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Miners\Multi...ls\Include.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

& : The specified module 'C:\Miners\MultiPoolMinerV2.7.2.4\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Miners\MultiPoolMinerV2.7.2.4\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Miners\Multi...ls\Include.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

& : The specified module 'C:\Miners\MultiPoolMinerV2.7.2.4\Pools\Include.psm1' was not loaded because no valid module file was found in any module directory.
At C:\Miners\MultiPoolMinerV2.7.2.4\Include.psm1:223 char:19
+                 & $_.FullName @Parameters
+                   ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Miners\Multi...ls\Include.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by UselessGuru** [comment]
There is an invalid file in the pool folder.

Duplicate. See https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1269
