### ISSUE TITLE
new pools add

### ISSUE THREAD

**Issue by zuhair01** [MultiPoolMiner/MultiPoolMiner#1318]
I would like to add my pool http://zergpool.com/ this pool 0 fees and MineMoney.co
thank you,

**Comment by zuhair01** [comment]
Hi how easy is it to add additional pools in such as zergpool.com and MineMoney.co
excellent work so far

**Comment by UselessGuru** [comment]
@ zuhair01

How about using the search function? YOu could have found this:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1155
