### ISSUE TITLE
Repeated ParameterBindingValidationException

### ISSUE THREAD

**Issue by cgrohowski** [MultiPoolMiner/MultiPoolMiner#1319]
I am getting the following repeated over and over in MPM - I tried unzipping a fresh copy over what I have but it did not help (should I fully start from scratch, having to benchmark everything again?)  I have zpool and miningpoolhubcoins enabled only.

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At H:\crypto\MultiPoolMiner\MultiPoolMiner.ps1:245 char:91
+ ... ount -eq 0 -or (Compare-Object $Config.Algorithm $_.Algorithm -Includ ...
+                                                      ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

**Comment by aaronsace** [comment]
Download the release and do not modify it. 
Install the full graphics drivers from AMD/NVidia website.

**Comment by UselessGuru** [comment]
You might have non MPM standard files i the Pools folder.
Also see here: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1230

To avoid problems for Upgrades always start with a new MPM folder. If you do not want to benchmark again you can cop the contents of the 'Stats' folder.
