### ISSUE TITLE
Powershell CPU usage

### ISSUE THREAD

**Issue by BioRunner** [MultiPoolMiner/MultiPoolMiner#1320]
I don't know if this is really an issue, but wanted to mention it. I run a 3 GPU miner on some old hardware (older CPU, Mobo, not much ram), but it works. I have been trying out the recent releases of MPM and have pretty much stopped using it because it keeps crashing my system or stops mining because the miners crash out. 

Anyhow using MPM V2.7.2.4 is better now, but I noticed that powershell uses a lot of CPU on my system. I don't mine using the CPU because it is an older CPU, but if I were to mine with it I doubt it would run well seeing as how powershell jumps around from using 30% to 90% of my CPU. I don't know if this is causing other peoples CPU mining issues or low performance from CPU mining.

Anyway just wondering why the new MPM has to use so much CPU? Sucks to not be able to use MPM now.

**Comment by aaronsace** [comment]
@BioRunner If you are see a difference in task manager then it's because the CPU usage now encompasses all the miners and not just MultiPoolMiner itself. The actual MultiPoolMiner process only uses one core once per minute.

**Comment by BioRunner** [comment]
Yeah it seems to be the one window that shows now in V2.7.2.4 with all the scrolling text and updated info. Thank you for the reply. As I mentioned above, my miner is on some older hardware so others may not see an issue with the CPU usage like I do.
