### ISSUE TITLE
Optimal switching prevention value for NiceHash due to manipulated algos

### ISSUE THREAD

**Issue by FruitFace** [MultiPoolMiner/MultiPoolMiner#1322]
There's been much converstation on r/nicehash about algos that are regularly toyed with by hash buyers to game the miners to switch over, and then mine for cheap.

I know that there was a note on this site, about eventually eliminating switching prevention when using NiceHash, since, it is PPS, switching prevention would be detrimental, if hash buyers were not abusing the system.

BUT, since there appears to be manipulation, even for algos that tend to be profitable for Nvidia e.g. Neoscrypt, Lyra2rev2, we should be able to mitigate this manipulation by using the switching prevention value.

So what value has worked best for you, or do you just disable everything except ethhash?

In the current environment, ethhash is the most consistently profitable algo, on Nicehash, right now, for my 3x1070/1x1080ti and 1x 1080ti gaming rig.  Neoscrypt had been better, but I find it's profitability swings wildly on NiceHash.

**Comment by aaronsace** [comment]
@FruitFace I recommend increasing it until it stops switching. You should notice though that, as the stats gather over a few days, it switches less to bad pools/algorithms.

**Comment by FruitFace** [comment]
That is a good point.  Should we just rely on mpm to improve its accuracy
Stat, or mess with switching prevention.  I guess I don't understand why we
have both of the accuracy Stat would ultimately achieve the same goal, or
am I misunderstanding?

**Comment by FruitFace** [comment]
Thanks.   I've looked over the docs multiples times in the past, but I guess I didn't concentrate too much on that section.  So short answer is it allows for fine tuning behavior on the accuracy stat.
