### ISSUE TITLE
Mkxminer doesnt work with MiningPoolHub, MultiPoolMiner needs to add supported Pools

### ISSUE THREAD

**Issue by PontiacGTX** [MultiPoolMiner/MultiPoolMiner#1324]
The miner cant start benchmarking because it is limited to work with suprnova, it would be good that support for suprnova was added (and that one can use our login) maybe just download the miner and execute the default bat by oneself?

== = List of recommended pools
stratum+tls://stak.suprnova.cc:7710 (go here to register: https://stak.suprnova.cc/)
stratum+tls://mona.suprnova.cc:3001 (go here to register: https://mona.suprnova.cc/)
stratum+tls://vtc.suprnova.cc:5676 (go here to register: https://vtc.suprnova.cc/)

**Comment by UselessGuru** [comment]
@PontiacGTX 

suprnova does not have an API to get pricing information to determine the best mining option. So MPM can not support it.

BTW: Don't confuse MiningPoolHub and MultiPoolMiner, they are two completely different things and not releated in any way.

**Comment by PontiacGTX** [comment]
yeah i was just commenting on that the miner works with suprnova.. so you could add to the supported pools but since it doesnt have pricing information.. but i mean you could try comapred with some exchange price what is the rate you would get from those coins

**Comment by PontiacGTX** [comment]
@aaronsace so there is no chance you cna add suprnova to the pool list and compare the price of th vertcoin/monacoin/etc with some exchange online like does coinbase?

**Comment by yuzi-co** [comment]
it works with MPH for a while now...

> v3.0.0: 23 December 2017 - stratum+tcp pools are now supported.
