### ISSUE TITLE
Problem with determining Price Bias

### ISSUE THREAD

**Issue by kiLLeen** [MultiPoolMiner/MultiPoolMiner#1325]
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/9a67e7463436fde9683a7d514c18380f70edc51a/MultiPoolMiner.ps1#L267

This goes through the list of all pools and if only one pool is no longer in sync, then the condition is true.

We then go into the if:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/9a67e7463436fde9683a7d514c18380f70edc51a/MultiPoolMiner.ps1#L269

Then, because only one pool (one you may not even be using!) is not in sync. This line will set **all** pools price bias based on the stable price.

This whole block needs to be refactored such that only the pools that are not in sync have their price bias based on their stable price. Right?

**Comment by aaronsace** [comment]
No, it's not checking age; it's check that they are all the same time period.

**Comment by kiLLeen** [comment]
I understand that. I'm not sure where you thought I was referring to age at. 

The condition is to check if all are within a window. I'm saying that if only one is outside that window, then all of the pools use the stable price for their price bias.

**Comment by kiLLeen** [comment]
Go into one of the pool configuration files that you are not using and change the rest URI such that the call will fail to sync. Use the following code as a replacement for that if/else and you'll see that stable price is set for other pools and algos when a failure happens in the pool that you set above:

```
    Write-Log "Selecting best pool for each algorithm. "
    $AllPools.Algorithm | ForEach-Object {$_.ToLower()} | Select-Object -Unique | ForEach-Object {$Pools | Add-Member $_ ($AllPools | Sort-Object -Descending {$Config.PoolName.Count -eq 0 -or (Compare-Object $Config.PoolName $_.Name -IncludeEqual -ExcludeDifferent | Measure-Object).Count -gt 0}, {($Timer - $_.Updated).TotalMinutes -le ($SyncWindow * $Strikes)}, {$_.StablePrice * (1 - $_.MarginOfError)}, {$_.Region -EQ $Config.Region}, {$_.SSL -EQ $Config.SSL} | Where-Object Algorithm -EQ $_ | Select-Object -First 1)}
    if (($Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {$Pools.$_} | Measure-Object Updated -Minimum -Maximum | ForEach-Object {$_.Maximum - $_.Minimum} | Select-Object -ExpandProperty TotalMinutes) -gt $SyncWindow) {
        Write-Log -Level Warn "Pool prices are out of sync ($([Int]($Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {$Pools.$_} | Measure-Object Updated -Minimum -Maximum | ForEach-Object {$_.Maximum - $_.Minimum} | Select-Object -ExpandProperty TotalMinutes)) minutes). "
        $Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {$Pools.$_ | Add-Member Price_Bias ($Pools.$_.StablePrice * (1 - ($Pools.$_.MarginOfError * $Config.SwitchingPrevention * [Math]::Pow($DecayBase, $DecayExponent)))) -Force}
        $Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {Write-Log "$($Pools.$_) price bias set using stable price."}
    }
    else {
        $Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {$Pools.$_ | Add-Member Price_Bias ($Pools.$_.Price * (1 - ($Pools.$_.MarginOfError * $Config.SwitchingPrevention * [Math]::Pow($DecayBase, $DecayExponent)))) -Force}
    }
```

The only change happening here is the one extra line in the if block to output the test information.

```
        $Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | ForEach-Object {Write-Log "$($Pools.$_) price bias set using stable price."}
```

**Comment by aaronsace** [comment]
Sorry, I'm not follow as to what you are trying to show. It may be better to do a pull request.

**Comment by kiLLeen** [comment]
The if statement is likely not what you want. Here is the psuedocode of what is here currently:
```
if for all pools available there is one or more pools out of sync
  set all pools price bias based on the stable price
else
  set all pools price bias based on the price
```

What I'm saying it the logic should be:
```
for each pool that is currently enabled
  set the pool's price bias based on the price
  if the pool is out of sync
    set the pool's price bias based on the stable price    
```

**Comment by kiLLeen** [comment]
Here is another test for you:
Remove all pool files except for one you know to have a working API status response (I used ahashpool).
Setup your Start.bat to point only to the pool you chose. eg. `-poolname ahashpool -algorithm neoscrypt,xevan,x17,hmq1725,blake2s,sib,c11,bitcore,lyra2v2,myr-gr,tribus,nist5,skein,lbry,phi,hsr,skunk,groestl,blakecoin`
Start up MPM.
Eventually (after sync window) you will get the out of sync message, but the API responds with no issue.
You can monitor with the following as well: `watch -n 60 curl -v https://www.ahashpool.com/api/status/`

**Comment by UselessGuru** [comment]
@kiLeen / @aaronsace 

I think this happens when the pool (ahashpool in your scenario) no longer lists a pool in their API. Then the stat file for this algo gets outdated.
