### ISSUE TITLE
MPH algo switching causing MPM to kick miners

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#1326]
I just noticed something. MPM was trying to mine Equi on Mining Pool Hub, but I guess the 17xxx port switched algo at that time. This threw an error and the miner (DSTM) was kicked. DSTM was mining just fine on NiceHash for the last 6 hours.
<img width="864" alt="screen shot 2018-02-26 at 1 54 49 pm" src="https://user-images.githubusercontent.com/28104701/36669463-adc9db78-1afd-11e8-9019-ccc077e7e81d.png">
<img width="530" alt="screen shot 2018-02-26 at 2 03 08 pm" src="https://user-images.githubusercontent.com/28104701/36669511-d1bc419c-1afd-11e8-8903-2e63a01b34e1.png">
I am also looking for the log and will upload once I find it.

**Comment by UselessGuru** [comment]
> 17xxx port switched algo at that time

That name is misleading:
Algo switch mining (Port 17XXX)
We provide auto switching port for each algo. These ports switch coins time to time to mine the most profitable coin. Best for Rental, ASIC, FPGA miners.

The same port is always minig the **same algo**, but **different coins**

Port 17023 is for Equihash.
What happens when you run the miner standalone with the exact same parameters as shown in your first screen shot?

**Comment by mkirov0** [comment]
Miner works standalone and runs on nicehash. It also runs on MPH most of the time. It was just this one instance that made me ask this question.
OK in that case am I correct in understanding my MPH worker should be set up to mine most algos (or the ones I like) with the same user.worker?
Like so:
<img width="580" alt="screen shot 2018-02-26 at 3 37 10 pm" src="https://user-images.githubusercontent.com/28104701/36673295-f9d4b8f0-1b0a-11e8-997c-4291e8e2efb6.png">
Or should I create a different user.worker for each algo?

**Comment by PontiacGTX** [comment]
### Here a small doubt...I wonder how you could add Xevan to MPM?

**Comment by UselessGuru** [comment]
@PontiacGTX

> I wonder how you could add Xevan to MPM?

Xevan is already supported by CcminerXevan (NVIDIA only).
Do you know a decent ADM miner for the Xevan algorithm?

**Comment by UselessGuru** [comment]
@mkirov0 

> Or should I create a different user.worker for each algo?
This is not supported by MPM. ONE user/workername for all algo combinations is fine.
For details on how to setup your MPH config please ask in the pools forum. This is beyond the scope of MPM.

All that MPM does is:
During each loop:
- for each configured pool: retrieve list of all supported algos as well as pricing information
- calculate the optimal miner/algo combo based on the available hash rate of our HW and the above algo/price information
- run the best miner

**Comment by mkirov0** [comment]
Thanks for clarifying.

**Comment by PontiacGTX** [comment]
@UselessGuru https://github.com/LIMXTEC/Xevan-GPU-Miner
