### ISSUE TITLE
Percent to Switch feature

### ISSUE THREAD

**Issue by diown** [MultiPoolMiner/MultiPoolMiner#1328]
Hello,

It would be nice, especially because the coin rates are flucturating a lot lately, to have a percent to switch option. So that it only switches if new profit is greater than actual profit in specified percent. For me it's not necessary to switch for only 1 euro more / day. switchingprevention is already set to 10 with interval 300, but it's still switching too often.

Any plans for this?

Thanks!

**Comment by aaronsace** [comment]
Increase it higher until it stops. There is no limit on how high you can set it. 

Please be aware that there is a bug with mixing MiningPoolHub with other pools that is being fixed tonight.

**Comment by romajc84** [comment]
What is the bug?  I use Blazepool with MPH and in 5 days it hasn't used MPH once lol.

**Comment by aaronsace** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/releases
