### ISSUE TITLE
Support faster CPU miner 

### ISSUE THREAD

**Issue by PontiacGTX** [MultiPoolMiner/MultiPoolMiner#1330]
I just noticed that JayDDee miner performs worse than Claymore Cryptonote CPU miner on an i7 SB,could you add the claymore CPU miner to the list of cryptonight CPU miner?

**Comment by alucard20724** [comment]
it's already there.. been there a couple of months now

**Comment by PontiacGTX** [comment]
for some reason it gives priority to JayDDee miner because almost never uses claymore miner

**Comment by alucard20724** [comment]
you can also comment out the lines in JayDDee miners to not run the cryptonight for JayDDee.
i.e.   #"cryptonight" = "" #Cryptonight
