### ISSUE TITLE
1070 mining rig doesnt seem to be working correctly 

### ISSUE THREAD

**Issue by izzledude** [MultiPoolMiner/MultiPoolMiner#1331]
So i have 2 differnet mining rigs one with a 1050ti and one with a 1070  the 1050ti seems to be working well it doesnt often switch pools or gives errors but i noticed that the one with the 1050 seems to mine for a minute maybe 2 then will switch   im  not sure if im seeing this correctly but itll mine then go to  starting next run do that for a minute or two then go through those logs again .    Can anyone let me know if its set up correctly. ive looked though a lot of the questions and answers here but im still lost    any advice will be appreciated . Also noticed I will get errors  "Warning can not find" "Warning can not download" "Warning searching for"

**Comment by nickvasel** [comment]
Down load latest powershell, I think that will help you. make sure you get it from Microsoft.

**Comment by izzledude** [comment]
I do have the most recent powershell download.   i checked if maybe my anti virus was stopping the download but it doesnt seem to be   any other suggestions?

**Comment by UselessGuru** [comment]
@izzledude 

Your problem description does leave quite some room for interpretation ;-)

Could please post logs and possibly screen shots? TIA!

**Comment by izzledude** [comment]
Sorry should of done that sooner.    Here is the main one i see    what specific logs do you need?
![desktop screenshot 2018 02 27 - 07 37 47 93](https://user-images.githubusercontent.com/36867842/36735307-1c56de3e-1b93-11e8-919f-0a986b58fa80.png)

![desktop screenshot 2018 02 27 - 07 40 04 53](https://user-images.githubusercontent.com/36867842/36735240-f0a65db4-1b92-11e8-98f0-a20c5b2ddd70.png)

**Comment by UselessGuru** [comment]
@izzledude

There is an existing problem with automatic downloads (also see https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1229). 
As a workaround you can manually download and copy the miner files.

**Comment by izzledude** [comment]
So i was able to find and correct 2 out of the 4 download errors. I am unable to find the downloads for 
Ethash-Claymore\EthDcrMiner64.exe.
Equihash-EWBF\miner.exe.
I just want to make sure i get the correct ones in place in the correct folder as there was no URI download link in the miners page

**Comment by aaronsace** [comment]
@izzledude I think you have downloaded the source code by mistake. 

Release packages are located here on GitHub: https://github.com/MultiPoolMiner/MultiPoolMiner/releases

**Comment by izzledude** [comment]
Source code for the individual  miners or for MPM?    I thought i downloaded the correct one MultiPoolMinerV2.7.2.5.zip is the one i grabbed

**Comment by UselessGuru** [comment]
@izzledude 
> Ethash-Claymore\EthDcrMiner64.exe.
> Equihash-EWBF\miner.exe.
> I just want to make sure i get the correct ones in place in the correct folder as there was no URI download link in the miners page

There is no offical direct dl link for these two miners that works with MPM's downoader. That is why you need to dld them manually. Sources:
EWBF (miner.exe): https://bitcointalk.org/index.php?topic=1707546.0
ClayMore Dual (EthDcrMiner64.exe): See https://bitcointalk.org/index.php?topic=1433925.0
