### ISSUE TITLE
Downloaded v2.7.2.5, still asked to download new version

### ISSUE THREAD

**Issue by vhatzist** [MultiPoolMiner/MultiPoolMiner#1334]
I just downloaded v2.7.2.5. When I run it I get:

WARNING: The software (MultiPoolMiner) is out of date; there is an updated version available at https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.2.5/MultiPoolMinerV2.7.2.5.zip.

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1336
