### ISSUE TITLE
MPM not using ZEC or ZEN for the profit switch algorithm

### ISSUE THREAD

**Issue by temanyta** [MultiPoolMiner/MultiPoolMiner#1343]
Since I updated to 2.7.2.5 MPM doesn't show ZEC or ZEN on the profitability list:

https://prnt.sc/iklsel

I added ethash on the algorithm list but it still doesn't work:

`-algorithm cryptonight,ethash,ethash2gb,equihash,groestl,lyra2re2,lyra2z,neoscrypt`

**Comment by UselessGuru** [comment]
Could you please post logs and a complete print screen - TIA!

**Comment by aaronsace** [comment]
@temanyta MultiPoolMiner is grouped by algorithms not coins. 

Equihash encompasses all of these coins: 
Bitcoin-Gold, Zcash, Zclassic and Zencash
