### ISSUE TITLE
Eminer only uses Nvidia card in a 2 card system

### ISSUE THREAD

**Issue by NastyNateu** [MultiPoolMiner/MultiPoolMiner#1344]
I noticed this yesterday, had to wait to check a few times to be sure before posting this issue. I thought it might just be mining with one card for the devfee, but I've confirmed 4 more times now that whenever Eminer is running my power usage drops 130 watt and my AMD card is 0% utilized. At first I thought MPM was probably killing Eminer once it realized it wasn't making as much profit utilizing only one card, but this time it's been running 3.5 hours and looking at the logs it's been running off and on all night. I'm surprised I didn't notice this issue sooner. 

I deleted my MPM folder and copied my stats over and let it download everything. 5 minutes later it's back on Eminer using 1 card again so that didn't fix it.  I went and looked at the eminer.txt file and it says  "AMD", "NVIDIA".

I'm not sure what to look for next. I could just delete the eminer, but MPM must be using it for a reason and it does appear to be the highest profit miner on my system, BUT it's having a severe impact on my 24h est earnings after only 8 hours or so, so that clearly isn't the case in real world performance.

**Comment by aaronsace** [comment]
You are best deleting Eminer from the folder called 'miners'. 

Can zip up the folder called 'logs' and drop it on your GitHub reply?

**Comment by NastyNateu** [comment]
[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1768385/Logs.zip)

**Comment by UselessGuru** [comment]
Can you run eminer so does it properly uses both cards (AMD and NVIDIA)?
What happens when  you run the exact same command standalone (copy/paste the command from the MPM window)?

As a workaround (UNTESTED!) you can make eminer a NVIDIA ONLY miner by editing eminer.txt and removin the two  lines containing `"AMD",`:
```
        "Type":  [
                     "AMD",
                     "NVIDIA"
                 ],
```
MPM should then run eminer on NVIDIA cards and run another AMD only miner in parallel. 
Note: I cannot test this myself because I do not own AMD hardware.

**Comment by NastyNateu** [comment]
That workaround works perfectly for me. MPM is currently using Eminer for the Nvidia and the Claymore ethdecred miner for the AMD after I removed the "AMD" lines from the Eminer.txt file. Thanks!

Eminer is an executable so I don't know how to check the first questions you asked.

Is it normal for the teal 'downloading' status overlay thing to pop up occasionally for a few frames?

**Comment by aaronsace** [comment]
Looks broken to me, you should definitely remove Eminer because it's reporting the NVidia hash rate twice instead of AMD: 
```
INFO [02-28|09:38:50] GPU device information                   device=0 hashrate="24.474 Mh/s" temperature="38.00 C" fan=56.00%
INFO [02-28|09:38:50] GPU device information                   device=1 hashrate="24.474 Mh/s" temperature="38.00 C" fan=56.00%
```

**Comment by NastyNateu** [comment]
yea I noticed that too and after I added the modified Nvidia only Eminer.txt file back to the Miners folder I started checking to see if possibly Eminer was interfering with the AMD miner that was running. (or possibly 'combining' under the same worker and showing a shared hashrate if they were mining the same coin)So I've been checking miningpoolhubstats and miningpoolhub and there was only one worker listed, so I removed Eminer again and I'm mining and waiting to see if either of these sites will refresh and show me 2 workers active. 

miningpoolhubstats currently shows me mining musicoin at 19.11 MH/s and in MPM Claymore is showing 11.413 and DSTM at 565 Sols/s. When I checked the different coins that DSTM could have been mining like Zencash or Zcoin, Zencash was showing 18kh/s at the same time Zcoin was showing 19MH/s. Miningpoolhubstats just shows the musicoin at a higher hashrate than it should be.

**Comment by UselessGuru** [comment]
Unfortunately eminers config options are very limited (there is no way to select which GPU to use). So we cannot make it use exclusively Nvidia  or AMD hardware (unlike ClaymoreAmd / ClaymoreNvidia for example)
Also it is not really faster than other miners. As aaronsace said ist probaly best to remove it in a scenario like yours.

> Miningpoolhubstats just shows the musicoin at a higher hashrate than it should be

MPH is a pool. Pools usually do not read hash rates from miners. Instead they calculate an average hash rate value from the number of submitted shares. This will result in a rough and bouncy estimate
