### ISSUE TITLE
Monitoring window text color inherited from Palgin hsrminer NeoScrypt

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1345]
Before Palgin hsrminer neoscrypt (grey):
![image](https://user-images.githubusercontent.com/1230402/36801090-62ca8fea-1cb1-11e8-96c1-819afc74dcc9.png)

During Palgin hsrminer neoscrypt (neon green, white):
![image](https://user-images.githubusercontent.com/1230402/36801030-3d86cf0a-1cb1-11e8-8f84-0c1f94b729aa.png)

After Palgin hsrminer neoscrypt (white, grey):
![image](https://user-images.githubusercontent.com/1230402/36801362-32e38b28-1cb2-11e8-86f0-b87ea4d06085.png)

After hsrminer everything went back to normal: grey.

**Comment by aaronsace** [comment]
I can either remove the colours or leave them. I think they are fairly useful to people... https://github.com/MultiPoolMiner/MultiPoolMiner/commit/fcbe0af2f09d1483f69dd4d251b6e735f44563d9

**Comment by borzaka** [comment]
I agree that they are useful.

From my coding experince I would guess that maybe there are unclosed color tags, or maybe you should escape color code from the information/warning/verbose texts (`2018-02-28 19:17:03 INFO:`), and only accepting colors where the miner text should be.

**Comment by aaronsace** [comment]
It's not a problem in the individual miner logs because they are not mixed then in these logs I was just removing the colours but, when I started to show people the output, I wanted it to look as familiar as possible. 

Do you think that you could put a pull request together that fixes open colour tags?

**Comment by borzaka** [comment]
Sorry, I don't speak PowerShell :)

I'am happy with colors in the monitoring window, just wanted to let you guys know about this issue.

**Comment by grantemsley** [comment]
I finally upgraded to the newest version with the new launching mechanism.  I'm running into some big problems with it, and now that we can't see the miner windows, logs are more important than ever.

So I'm currently working on tackling the logs - hopefully going to make them easier to read and find things, easier to adjust their verboseness, have a good way of displaying them all, and have them clean up old logs.  The included log viewer is better than nothing, but I think we can come up with something even better.

**Comment by UselessGuru** [comment]
> The included log viewer is better than nothing, but I think we can come up with something even better.

My idea:
MPM knows which miners are running and the log file names that go with them. MPM should store the list of active log files in a variable. Have a separate GUI with a tab for each active log tailing the active log file. $Interval seconds after the miner stopped (log file revoved from the list) the log should be removed from the log viewer.
That way we can also fix issue https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1347

**Comment by grantemsley** [comment]
@UselessGuru I plan to add a property to the miner API to store the filename of its current log file.  Right now there's no way for the script to tell what file each miner is writing to.  Then the list of miners can be written to a clixml or json file on each loop to give other tools (log viewer, launcher GUI) access to that information.  Then it will be easy to find which log files belong to active miners.  Should also be able to use that info to draw attention to logs of miners that have failed.

**Comment by UselessGuru** [comment]
> miner API to store the filename of its current log file

How about this? It will fill the property $ActiveMiners.LogPath as long as the miner is running.
```
class Miner {
    $Name
    $Path
    $Arguments
    $Wrap
    $API
    $Port
    $LogPath
    [Array]$Algorithm = @()
    $Type
    $Index
    $Device
    $Device_Auto
    $Profit
    $Profit_Comparison
    $Profit_MarginOfError
    $Profit_Bias
    $Speed
    $Speed_Live
    $Best
    $Best_Comparison
    hidden [System.Management.Automation.Job]$Process = $null
    $New
    hidden [TimeSpan]$Active = [TimeSpan]::Zero
    hidden [Int]$Activated = 0
    hidden [MinerStatus]$Status = [MinerStatus]::Idle
    $Benchmarked

    hidden StartMining() {
        $this.Status = [MinerStatus]::Failed

        $this.New = $true
        $this.Activated++

        if ($this.Process) {
            if ($this.Process | Get-Job -ErrorAction SilentlyContinue) {
                $this.Process | Remove-Job -Force
            }

            if (-not ($this.Process | Get-Job -ErrorAction SilentlyContinue)) {
                $this.Active += $this.Process.PSEndTime - $this.Process.PSBeginTime
                $this.Process = $null
            }
        }

        if (-not $this.Process) {
            $this.LogPath = $Global:ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(".\Logs\$($this.Name)-$($this.Port)_$(Get-Date -Format "yyyy-MM-dd_HH-mm-ss").txt")
            $this.Process = Start-SubProcess -FilePath $this.Path -ArgumentList $this.Arguments -LogPath $this.LogPath -WorkingDirectory (Split-Path $this.Path) -Priority ($this.Type | ForEach-Object {if ($_ -eq "CPU") {-2}else {-1}} | Measure-Object -Maximum | Select-Object -ExpandProperty Maximum)

            if ($this.Process | Get-Job -ErrorAction SilentlyContinue) {
                $this.Status = [MinerStatus]::Running
            }
        }
    }

    hidden StopMining() {
        $this.Status = [MinerStatus]::Failed

        if ($this.Process) {
            if ($this.Process | Get-Job -ErrorAction SilentlyContinue) {
                $this.Process | Remove-Job -Force
            }

            if (-not ($this.Process | Get-Job -ErrorAction SilentlyContinue)) {
                $this.Active += $this.Process.PSEndTime - $this.Process.PSBeginTime
                $this.Process = $null
                $this.Status = [MinerStatus]::Idle
                $this.LogPath = $null
            }
        }
    }

    [DateTime]GetActiveLast() {
        if ($this.Process.PSBeginTime -and $this.Process.PSEndTime) {
            return $this.Process.PSEndTime
        }
        elseif ($this.Process.PSBeginTime) {
            return Get-Date
        }
        else {
            return [DateTime]::MinValue
        }
    }

    [TimeSpan]GetActiveTime() {
        if ($this.Process.PSBeginTime -and $this.Process.PSEndTime) {
            return $this.Active + ($this.Process.PSEndTime - $this.Process.PSBeginTime)
        }
        elseif ($this.Process.PSBeginTime) {
            return $this.Active + ((Get-Date) - $this.Process.PSBeginTime)
        }
        else {
            return $this.Active
        }
    }

    [Int]GetActivateCount() {
        return $this.Activated
    }

    [MinerStatus]GetStatus() {
        if ($this.Process.State -eq "Running") {
            return [MinerStatus]::Running
        }
        elseif ($this.Status -eq "Running") {
            return [MinerStatus]::Failed
        }
        else {
            return $this.Status
        }
    }

    SetStatus([MinerStatus]$Status) {
        if ($Status -eq $this.GetStatus()) {return}

        switch ($Status) {
            "Running" {
                $this.StartMining()
            }
            "Idle" {
                $this.StopMining()
            }
            Default {
                $this.StopMining()
                $this.Status = $Status
            }
        }
    }

    [PSCustomObject]GetMinerData ([Bool]$Safe = $false) {
        $Lines = @()

        if ($this.Process.HasMoreData) {
            $this.Process | Receive-Job | ForEach-Object {
                $Line = $_ -replace "`n|`r", ""
                if ($Line -replace "\x1B\[[0-?]*[ -/]*[@-~]", "") {$Lines += $Line}
            }
        }

        return [PSCustomObject]@{
            Lines = $Lines
        }
    }
}
```

**Comment by grantemsley** [comment]
Yep, that's virtually identical to what I've got.
