### ISSUE TITLE
The failed miners are no longer listed in the Status: Failed section?

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1346]
They are in the `Status: Idle` section as well as the other successfully runned miners.

I think it's very important to know which miner was failed; make some adjustment in the config, delete the stats file and run MPM again to try benchmark it again.

Update: probably there is a history limit of runned miners, and after that limit is reached, the runned miners history is not updated. This limit is 12 as I can tell.

Update 2: during benchmarks, many miners are runned, and after 12 successfully runned miner, no new miners get to the Status: Idle / Status: Failed section, therefore hard to check which miner is failed. I have to search the logs for failed miners.
If I keep running this same process, a runned miner history never updates, except the currently running.

**Comment by jeetbarman** [comment]
It's correct there is a limitation of 12 history but shouldn't they be properly grouped under same category?

In my case I can see 1 under running 2 under Idle 1 under Failed 1 under Idle 1 under Failed followed by 6 under Idle.

Generally all Failed / Idle should be grouped together but it seems there is bug which is creating issue out here.

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/4e6bf556b1fde87f105bae2189ecea91742aa233#diff-69b5e62237d5f951ca1ac096869d0234
