### ISSUE TITLE
Is it possible to mine pool such as zergpool to LTC instead of BTC?

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1350]
I'm asking because this works fine in Useless Guru version and I was thinking of trying the main branch again but I need to mine to LTC there because of ridiculous payout levels.

**Comment by aaronsace** [comment]
Yes, please use the config: 
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Config.txt

**Comment by robl45** [comment]
I'm not sure exactly what that means.  So I edit the confirm with Zergpool and where it says  BTC put in LTC and where it says $wallet put in the LTC wallet?

**Comment by UselessGuru** [comment]
Yes, please use the config:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Config.txt

You need to edit config.txt

Also see 
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1105
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1155

**Comment by robl45** [comment]
Here is my config.txt.  I just watched it do zergpool with C=BTC so clearly I have something wrong.

{
  "Pools": {
    "MiningPoolHub": {
      "User": "$UserName",
      "Worker": "$WorkerName",
      "API_ID": "$API_ID",
      "API_Key": "$API_Key"
    },
    "MiningPoolHubCoins": {
      "User": "$UserName",
      "Worker": "$WorkerName",
      "API_ID": "$API_ID",
      "API_Key": "$API_Key"
    },
    "NiceHash": {
      "BTC": "$Wallet",
      "Worker": "$WorkerName"
    },
    "zergpool": {
      "LTC": "LeTUNYViANaPTypGuUpCKXihwghJyK1nE2",
      "Worker": "$WorkerName"
    }
  },
  "Miners": {
  },
  "Interval": "$Interval",
  "Region": "$Region",
  "SSL": "$SSL",
  "Type": "$Type",
  "Algorithm": "$Algorithm",
  "MinerName": "$MinerName",
  "PoolName": "$PoolName",
  "ExcludeAlgorithm": "$ExcludeAlgorithm",
  "ExcludeMinerName": "$ExcludeMinerName",
  "ExcludePoolName": "$ExcludePoolName",
  "Currency": "$Currency",
  "Donate": "$Donate",
  "Proxy": "$Proxy",
  "Delay": "$Delay",
  "Watchdog": "$Watchdog",
  "MinerStatusURL": "$MinerStatusURL",
  "MinerStatusKey": "$MinerStatusKey",
  "SwitchingPrevention": "$SwitchingPrevention"
}

**Comment by robl45** [comment]
edited pool name to ZergPool thinking it might be case sensitive, still just using the c=btc and btc address.

**Comment by UselessGuru** [comment]
The test file provided [here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1155) does not allow for payout in any other currency than BTC (Only option 1 supported).

Attached file (rename to .ps1) MIGHT work for option 2 too. Any feedback is appreciated.
[ZergPool.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1771543/ZergPool.txt)

**Comment by aaronsace** [comment]
@UselessGuru This needs change from this: 
`$ZergPool_Currencies = @("BTC")`

To this: 
`$ZergPool_Currencies = @("BTC", "LTC")`

**Comment by UselessGuru** [comment]
@aaronsace 

I changed my file... 
Side note: I actually doubt that the zergpool file in it's original version makes sense. If there are multiple currencies specified in config.txt we get multiple miners  which all use the same algo for mining but payouts in several currencies. In which currency would the final payout be?

**Comment by aaronsace** [comment]
Not look through it much but you just need to mix these two pool files together and add 'LTC' next to 'BTC': 
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Pools/Zpool.ps1
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Pools/YiiMP.ps1

**Comment by UselessGuru** [comment]
Option 1 - Mine in particular algorithm
This will let pool to mine most profitable coin in this algo or use merged mining benefits, and auto exchange rewards to your coin wallet. You should use coin wallet address as username.
Use c=SYMBOL in password to make sure payout wallet coin is identified correctly.
Example to mine in Scrypt algorithm and get payout in BTC
-o stratum+tcp://mine.zergpool.com:PORT -u <YOUR_BTC_ADDRESS> -p c=BTC 

I do not see a way (as it stands now) how we cann create a config which allows for payout in BTC for algo a,b & c, and LTC for algo d,e & f.

The only thing that works to my understanding is a all-or-nothing solution which my revised file does (with BTC as fallback).

**Comment by aaronsace** [comment]
I think this is a mistake on the site: 

> We will guarantee BTC payouts for now

Because it says this at the top: 

> BTC and LTC are guaranteed payout coins, for others please check block amount we mine in pool.

Either way, you can actually put LTC as the payout even if it's not guaranteed.

**Comment by robl45** [comment]
Test file attached did not work. still just doing BTC.  I don't understand why the uselessguru fork did this just fine.  Zergpool has stupid payouts for BTC and they hare much less for LTC.  I have been using LTC there for 3 days or so already with the useless guru version.    And yes I changed the file to say LTC and BTC.

**Comment by robl45** [comment]
http://api.zergpool.com:8080/api/status  my understanding is this is the correct api for zergpool

**Comment by UselessGuru** [comment]
@robl45 

The Q is not the API...
[http://api.zergpool.com:8080/api/status ](http://api.zergpool.com:8080/api/status) is not relevant for the payout currency/coin. It only defines the profit per algo for a set hash rate.
ZergPool (in theory) for any algo alows payout to be in any currency/coin (options 2 & 3)

MPM does currently not support payout options 2 & 3. reason:
To use zergpool properly you need to define a static value pair of [algo]:[currency/coin] per algo, something that MPM cannot do.

**Comment by robl45** [comment]
Not sure I understand, I'm using option 1.  They support payouts in BTC and LTC.  LTC is ,0005 BTC equivalent so much better than doing BTC.  It is currently working, I was just pointing out that my understanding is you need to use that API I listed in order for it not to get blocked.

**Comment by UselessGuru** [comment]
> that API I listed in order for it not to get blocked

Not quite :-) No blocking involved in this one.

Let me explain:
- You want to always mine the best paying algo with your hardware.
- MPM has a list of supported miner binaries and the algos these binaries support (defined through the files in the 'Miners' folder)
- MPM knows how fast your hardware is (e.g. for each algo it can mine at a known speed). It determined this when it did the benchmarks. MPM stores the benchmark results in the 'Miners\..._benchmark.txt' files
Sidenote: Benchmarking ist not very profitable, you may see a little profit.
- MPM has a list of supported pools (defined through the files in the 'Pools' folder)
- With this knowledge MPM periodically polls each configured pool by calling the pools API (e.g. [http://api.zergpool.com:8080/api/status](http://api.zergpool.com:8080/api/status) for ZergPool)
Through the API request MPM learns about all supported algorithms, coins and the going rate per algo/coin (how much the pool pays you for a known hash rate). 
- MPM now has an internal list of miner binaries, available algos and prices
- MPM can now calculate the most profitable miner/algo/coin combo and starts the most profitable miner. The payout address is part of the miner command line. The pool accumulates the earnings of your shares to this BTC address.
Note: All above calculations are internally based on BTC prices (e.g. all pool API's so far list their prices in mBTC) regardless of the payout currency.

**Auto conversion and payout in BTC**
Most pools (but NOT Yiimp) support auto conversion and payout in BTC. 
- The running miner is mining Zcash using the Equihash algorithm (assuming this is the most profitable algo/currency combo). 
- When the pool finds a new Zcash block it gets rewarded with some Zcash. 
- The pool now sends the mined Zcash to an exchange (e.g. Bitfenix) where it gets exchanged into BTC at market price. 
- The exchange sends BTC back to the pool.
- The pool now pays you in BTC. 

**Payout in different currency** (MPM currently only supports option 1 at ZergPool and similar pools).
With some pools you can opt to receive payout in another currency, e.g. LTC. For this to work:
- MPM must tell the miner to mine towards a LTC address (the LTC address you configured in config.txt is being passed as parameter to the miner).
- MPM will now mine Zcash using Equihash (assuming this is the most profitable algo/currency combo). Note: The most profitable miner/algo combo is still calculated in BTC.
- When the pool finds a new Zcash block it gets rewarded with some Zcash.
- The pool now sends the mined Zcash to an exchange (e.g. Bitfenix) where it gets exchanged into LTC at market price.
- The exchange sends LTC back to the pool. 
- The pool now pays you in LTC. 
Important: It does not matter what coin/currency/algo combo you are mining, in this scenario payout will always be in the same currency 

If you wanted to use ZergPool option 2 or 3 you would have to tell MPM for each supported algo: 
- If algo is Equihash AND coin is Zcash, then payout address is in LTC/<YOUR_LTC_ADDRESS> (or any other supported currency)
- If algo is Ethash AND coin is Ethereum, then payout address is in XMR/<YOUR_XMR_ADDRESS> (or any other supproted currency)
- etc...

At present there is no way to define this configuration set.

**Comment by robl45** [comment]
I get that, the API gets blocked by DDOS protection thats why it has the 8080.  Thats all I was pointing out.

**Comment by robl45** [comment]
Apparently not working quite right.  As you can see.  With Zergpool two times it did c=BTC and once it did C=LTC.  I've seen it doing C=LTC when I'm watching but apparently the other is getting snuck is as well.


   Status: Running

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 25 Minutes 3 Times  Bin\Equihash-DSTM\zm.exe --telemetry --server us-east.equihash-hub.miningpoolhub.com --port 17023 --user robminer.rob --pass x --color


   Status: Failed

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-SP\ccminer.exe -a c11 -o stratum+tcp://zergpool.com:3573 -u  -p rob,c=BTC -b 4068


   Status: Idle

     Speed Active                      Launched Command
     ----- ------                      -------- -------
    0  H/s 00 Days 00 Hours 06 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a bitcore -o stratum+tcp://zergpool.com:3556 -u LeTUNYViANaPTypGuUpCKXihwghJyK1nE2 -p rob,c=LTC --submit-stale
    0  H/s 00 Days 00 Hours 28 Minutes Once     Bin\HSR-Palgin\hsrminer_hsr.exe -o stratum+tcp://zergpool.com:7433 -u  -p rob,c=BTC
13.54 MH/s 00 Days 00 Hours 03 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a x17 -o stratum+tcp://x17.us.hashrefinery.com:3737 -u 1GJDZKUFLeJfWaDeCRXTBC656vtkjeULoX -p rob,c=BTC --submit-stale

**Comment by UselessGuru** [comment]
With which zergpoo.l.ps1 did this happen?

**Comment by robl45** [comment]
[MultiPoolMiner_2018-03-01.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1772916/MultiPoolMiner_2018-03-01.txt)

That happened with the one you provided above.  There is something wrong as you can see in the log it passed -U with no address.  I have now put in the one from the Useless Guru version that I had been using and as you can see there is now an address.

**Comment by UselessGuru** [comment]
The longer I look at the 'payout in a different currency' thing, the less am I convinced that the current implementations of it work for Zpool, Zergpool or the like :-)

So stand by for some new ideas.

**Comment by robl45** [comment]
Your version of it works.   The pool file seems to be working from your version.   Maybe that's the solution for the main branch?

**Comment by UselessGuru** [comment]
> Your version of it works. The pool file seems to be working from your version. Maybe that's the solution for the main branch?

But this does not support payout in BTC?

**Comment by robl45** [comment]
Okay, I think we have some miscommunication going on here.

The file currently in your Useless Guru version works fine for payout in LTC or BTC.  I had to activate the lines in the pool file for currency choice and wallet.  

The file that you provided above in this thread and the changes Aaron mentioned did not work correctly as I documented sometimes it worked, other times it would pass c=BTC with no address.

**Comment by UselessGuru** [comment]
> I had to activate the lines in the pool file for currency choice and wallet.

Would mind posting the file please?

**Comment by robl45** [comment]
[Zergpool.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1774903/Zergpool.txt)

**Comment by UselessGuru** [comment]
@robl45 

Thanks for the file. Yes, that file will work for you. But the goal is to have a flexible architecture where no individual tampering of pool (or miner) files is required.

**Comment by robl45** [comment]
I completely agree, currently that is not working.

**Comment by UselessGuru** [comment]
To be continued in https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1362
