### ISSUE TITLE
Bminer: Failed to read from the network: Get : dial tcp: lookup : no such host 

### ISSUE THREAD

**Issue by mwodzynski** [MultiPoolMiner/MultiPoolMiner#1352]
[BMiner-1880_2018-03-01_04-24-19.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1771364/BMiner-1880_2018-03-01_04-24-19.txt)
[BMiner-1880_2018-02-28_23-09-30.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1771365/BMiner-1880_2018-02-28_23-09-30.txt)
[BMiner-1880_2018-03-01_04-26-56.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1771366/BMiner-1880_2018-03-01_04-26-56.txt)

Log from 2018-02-28 shows that BMiner was working fine, the other 2 logs show a failure, any ideas why?

**Comment by boro2000** [comment]
Since bminer makes calls to api.bminer.me, this host is either down, or the access is being blocked by a firewall, entry into hosts, or similar.

**Comment by mwodzynski** [comment]
@boro2000 

Firewall settings did not change, I checked and BMiner or MPM are not blocked.
By host, do you mean the pool or my rig?

**Comment by UselessGuru** [comment]
@ mwodzynski

This is a bminer internal issue and is not related to MPM. Please direct your request with the developer. 

FYI:
MPM just launches the miners based on best profitability as external processes. The command line used to run the miners is shown in MPMs main window. You would see the same type of error if you were to run this command outside of MPM (directly in a CMD window).
