### ISSUE TITLE
After restarting MPM, the monitoring window scrolls through the entire current day's log

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1354]
If you do this by the end of the day, then it would slow down your PC to completely unusable until it's finishes reading/scrolling the logs unti it's reaches the end.
I have a 5 MB log (~52000 lines) after 20 hours.

**Comment by grantemsley** [comment]
Not quite a duplicate, but related to #1347

**Comment by myfingerhurt** [comment]
I have the same issue, I suggest you put the log reader command in a separated bat file and launch it manually.

**Comment by UselessGuru** [comment]
[This should fix it](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1358). Please close if it does - thanks.

**Comment by borzaka** [comment]
Yes, it's fixed; after restarting, the last 1000 lines are displayed in the monitoring window.

**Comment by UselessGuru** [comment]
Thanks for the feedback.
