### ISSUE TITLE
Feature request: show current BTC value in USD, or in any given currency

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1356]
Examples:
- `-currency btc,usd,eur`: 1 BTC = x USD
- `-currency btc,eur`: 1 BTC = x EUR

This could be shown always on top of the screen. or in the title.

**Comment by grantemsley** [comment]
My GUI that is in development has this :)

**Comment by UselessGuru** [comment]
See https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1720
