### ISSUE TITLE
chosen less profitable algo

### ISSUE THREAD

**Issue by tiotoi** [MultiPoolMiner/MultiPoolMiner#1357]
Hi guys, could you please take a look on these screenshots below. I dont know why MPM chosen less profitable algo...
thanks a lot for any help
<img width="1383" alt="screen shot 2018-03-01 at 9 19 37 pm" src="https://user-images.githubusercontent.com/9711334/36880438-aa51c03c-1d96-11e8-926a-2169c08d768f.png">
<img width="1110" alt="screen shot 2018-03-01 at 9 19 15 pm" src="https://user-images.githubusercontent.com/9711334/36880439-aa5dc1ac-1d96-11e8-8c9f-931c00e9cc5e.png">

**Comment by mkirov0** [comment]
Mine did that in the first few/several hours when I fist installed it. It is getting better with time tho. If you haven't recently installed/reset stats it could be a different thing...

**Comment by tiotoi** [comment]
@mkirov0 thanks, I will test it today as well and let everybody’s know where we are

**Comment by tiotoi** [comment]
its working fine now, thanks
