### ISSUE TITLE
ZergPool miner file

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1362]
## Testusers wanted!

_Important: Support for ZergPool requires newer builds of MPM which support config file 'config.txt'._

### Howto
**Download the lastest MPM package, then put the attached ZergPool.txt to the 'Pools' folder and rename to ZergPool.ps1.**

[ZergPool.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1776644/ZergPool.txt)

Please report issues regarding ZergPool in this thread - Thank you!

### Zergpool allows three different options for payout

**Option 1 - Mine in particular algorithm**
This will let pool to mine most profitable coin in this algo or use merged mining benefits, and auto exchange rewards to your coin wallet. You should use coin wallet address as username.
Use c=SYMBOL in password to make sure payout wallet coin is identified correctly.
Example to mine in Scrypt algorithm and get payout in BTC
-o stratum+tcp://zergpool.com:PORT -u <YOUR_BTC_ADDRESS> -p c=BTC

**Option 2 - Mine particular coin**
Use your coin wallet address as username in mining software. Specify c=SYMBOL as password to idenfify payout wallet coin, and the same coin in mc=SYMBOL to specify mining coin
Example to mine Guncoin and get payout in Guncoin
-o stratum+tcp://zergpool.com:PORT -u <YOUR_GUNCOIN_WALLET_ADDRESS> -p c=GUN,mc=GUN

**Option 3 - Mine particular coin with auto exchange to wallet address**
This will mine coin you specified in password field only and autoexchange it to your wallet currency for payout.
Use c=SYMBOL in password to make sure payout wallet coin is identified correctly. Use mc=SYMBOL to target particular coin for mining
Example to mine in Innova coin and get payout in LTC
-o stratum+tcp://zergpool.com:PORT -u <YOUR_LTC_ADDRESS> -p c=LTC,mc=INN

### Basic mode
Without manual configuration of config.txt MPM will mine on ZergPool like with any other pool. All payouts will be made in BTC.

### Advanced mining options
Support for advanced features is available via manual configuration of config.txt.
These are:
- Support for payout in another currency than BTC (Option 1)
- Options 2 & 3

Edit config.txt and add/edit the following pool information (I strongly advise you make a backup of config.txt!!!):
```
    "ZergPool": {
      "Worker":  "$WorkerName",
      "PayoutCurrency":  "<PayoutCurrency, e.g. LTC>",
      "PayoutAddress":  "<YOUR_PayoutCurrency_ADDRESS>",
      "Currencies": {
          "c=GUN,mc=GUN":  "<YOUR_GUNCOIN_WALLET_ADDRESS>",
          "c=LTC,mc=INN":  "<YOUR_LTC_ADDRESS>"
      }
    },
```
Config description:
To receive payout in another currency than BTC define 'PayoutCurrency', e.g LTC & 'PayoutAddress'.
To receive payout in BTC to default BTC address remove 'PayoutCurrency' & 'PayoutAddress' lines.
To receive BTC payment to an alternate BTC address set 'PayoutCurrency' to "BTC" and 'PayoutAddress' to alternate BTC address.

To use ZergPool option 2 and 3 you need to add a line to the section "Currencies" for each currency/coin pair as described on http://zergpool.com/

Example to mine Guncoin and get payout in Guncoin (Option 2)
"c=GUN,mc=GUN":  "<YOUR_GUNCOIN_WALLET_ADDRESS>"

Example to mine in Innova coin and get payout in LTC (Option 3)
"c=LTC,mc=INN":  "<YOUR_LTC_ADDRESS>"

_Note: You cannot add comments / uncomment lines in config.txt! Remove all unneeded lines from the template._

**Comment by robl45** [comment]
Don't take this the wrong way, but first I don't think this is a good solution as it involves way too much manual processes and two could you provide a config.txt that is setup correctly to mine LTC as I just tried it and apparently messed up something I'm guessing with removing the currencies part that caused it to just shoot red lines everywhere.  I had to go back to old config.txt and zergpool file from your version.  And honestly and frankly I think that deleting a # sign in a couple of places in the pool file is way easier than this.

**Comment by UselessGuru** [comment]
@robl45 

> I think that deleting a # sign in a couple of places in the pool file is way easier than this.

I agree that the editing config.txt is tricky. In JSON files every comma counts... 
grantemsley is working on a GUI which will gets around this.

My file does not allow for donations.... If you want to be nice with aaronsace you should try the offical file... :-)

**Comment by robl45** [comment]
I did try the original file and apparently messed up a comma and I have done programming in C++ and Visual basic so I"m more aware of how this works than most users would be.  I tried it a couple of ways and it wasn't working.  I'm happy to try it if you provide a file I can just drop in.

**Comment by UselessGuru** [comment]
@robl45 

Based on the info you [posted here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1350) this should work for you (note there is stuff missing after the miners section which you did not include in OP):

```
{
  "Pools": {
    "MiningPoolHub": {
      "User": "$UserName",
      "Worker": "$WorkerName",
      "API_ID": "$API_ID",
      "API_Key": "$API_Key"
    },
    "MiningPoolHubCoins": {
      "User": "$UserName",
      "Worker": "$WorkerName",
      "API_ID": "$API_ID",
      "API_Key": "$API_Key"
    },
    "NiceHash": {
      "BTC": "$Wallet",
      "Worker": "$WorkerName"
    },
    "ZergPool": {
      "Worker":  "$WorkerName",
      "PayoutCurrency": "LTC",
      "PayoutAddress":  "LeTUNYViANaPTypGuUpCKXihwghJyK1nE2",
      "Currencies": {
      }
    },
    "Zpool": {
      "BTC": "$Wallet",
      "Worker": "$WorkerName"
    }
  },
  "Miners": {
  },
```

**Comment by robl45** [comment]
That works.  I deleted "currencies" as I wasn't using that, pretty sure that messed it up.

**Comment by UselessGuru** [comment]
Thanks for the feedback.

> I deleted "currencies" as I wasn't using that, pretty sure that messed it up.

Then you probably forgot to delete the comma at the end of the line preceeding "currencies"

**Comment by aaronsace** [comment]
@UselessGuru I think you've made this a bit overcomplicated. I'm going to push a commit that follows the existing design pattern.

**Comment by aaronsace** [comment]
Hopefully this works: 9e5e52028f5deb07b9484c47f985f82d9276892b

```
"ZergPool": {
  "LTC": "abc123",
  "BTX": "abc123",
  "Worker": "$WorkerName"
}
```

**Comment by UselessGuru** [comment]
@aaronsace 
I cannot see how this should work if you want payout in LTC only. There will be two miners per algo, one with payout BTC and one with LTC. As robl45 has written:

> Apparently not working quite right. As you can see. With Zergpool two times it did c=BTC and once it did C=LTC. I've seen it doing C=LTC when I'm watching but apparently the other is getting snuck is as well.

it will not stick to LTC

**Comment by robl45** [comment]
To add when it did c=btc before it would leave out the address.

**Comment by UselessGuru** [comment]
> To add when it did c=btc before it would leave out the address.

Noted this too... takes an hour until it starts donating :-) Should be fixed with this:
[ZergPool.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1776950/ZergPool.txt)

**Comment by aaronsace** [comment]
@UselessGuru BTC is not listed in the config that I posted above. Pool files should not have access to any wallet not listed in the pool config; there is a bug if it somehow gets a BTC address from somewhere.

**Comment by robl45** [comment]
Seems this is still in flux?  I downloaded the master again and it doesn't seem to have the new zergpool file in it.

**Comment by aaronsace** [comment]
@robl45 Not sure what you mean...

The file is still there: https://github.com/MultiPoolMiner/MultiPoolMiner/tree/master/Pools

**Comment by robl45** [comment]
It appears to be different than the one useless said to use

**Comment by aaronsace** [comment]
I rewrote the whole thing and posted to the master branch. Check my comments above.

**Comment by robl45** [comment]
That doesn't work quite right.  It is right if someone wanted to do option 3 I suppose as it is inserting a mc= as well as C=LTC .  Not sure where it is getting the MC=value from.  I deleted MC= in two places in the pool file and now it seems to be working correctly.

**Comment by aaronsace** [comment]
@robl45 I haven't tested it but Option 1, 2 and 3 should work. Please can you post your config and logs?

**Comment by robl45** [comment]
[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778913/Config.txt)
[MultiPoolMiner_2018-03-04_15-08-21.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778916/MultiPoolMiner_2018-03-04_15-08-21.txt)

**Comment by aaronsace** [comment]
Looks correct to me; you have entered your LTC address and it is using that address for either Option 1 or 3 depending which is better long term. (Option 1 is not always best. )

**Comment by robl45** [comment]
Why would I want to use option 3?

**Comment by aaronsace** [comment]
The profits are higher on your log.

**Comment by 3zero2** [comment]
Looks to be working fine with the zergpool file from latest master. 

I didn't make any changes to the config file

Note: With the two pool files uploaded here I have the address missing after -u

**Comment by aaronsace** [comment]
@3zero2 That's great to here. 

I'm liking the way ZergPool has implemented YiiMP but they could do with adding Equihash.

**Comment by UselessGuru** [comment]
> BTC is not listed in the config that I posted above. Pool files should not have access to any wallet not listed in the pool config; there is a bug if it somehow gets a BTC address from somewhere.

I see what you mean. This works well if run via start.bat. But if you run in from within PowerGUI (old - but it works for me) - or other dev environments for that matter - then BTC will also be available in ZergPoo.ps1. :-(

Regarding Option 2 & 3: I think we should split zergPool into 2 different miners. Reason:

a) Option 2 & 3 generate a lot of miners (>200! in my test case) which put a lot of calculation stress to the core.
b) Option 2 & 3 are not really meant to be used as aaronsace implemented. Opt. 2 & 3 are useful to mine to a specific wallet, e.g. GUN if this is more profitable than anything else. 
-> we need a config option to limit the coins that are used in opt 2 & 3.

@aaronsace Should I continue development in that direction? 2 Separate miners. For Option 1 use payout address as in your implementation. For option 2 & 3 use my config option (advanced feature. If no config item no miners for option 2 & 3)

**Comment by mkirov0** [comment]
I have a statement  thats more of a question...
I noticed MPM mining on ZergPool with a specific coin picked (sorry I had to do 2 screenshots since it does not fit in one)
<img width="895" alt="screen shot 2018-03-05 at 12 58 32 pm" src="https://user-images.githubusercontent.com/28104701/36971604-070dc66e-2075-11e8-942e-97a9b21985d5.png">
<img width="896" alt="screen shot 2018-03-05 at 12 58 46 pm" src="https://user-images.githubusercontent.com/28104701/36971607-08798ec0-2075-11e8-8bd6-1497565f1021.png">
If I understand correctly this is option 3 from the listed above. If I have not changed anything in the config.txt shouldn't MPM treat is as option 1 and just select the most profitable algo and mine it or is there some detail I am missing that makes mining particular coin more profitable? I also see it mining as Option 1 which makes me think it is set up correctly and begs this question.
<img width="901" alt="screen shot 2018-03-05 at 1 05 01 pm" src="https://user-images.githubusercontent.com/28104701/36971940-0bd76fb4-2076-11e8-8e8f-9f816785b37d.png">
<img width="909" alt="screen shot 2018-03-05 at 1 05 13 pm" src="https://user-images.githubusercontent.com/28104701/36971945-0ff694bc-2076-11e8-95d1-ff98dd75c371.png">
I can post logs, but I think there is something I am missing, so it should be an easy answer for you.

**Comment by UselessGuru** [comment]
@mkirov0 
Without any extra coin config MPM choses the most profitable coin/algo combo. Your payout will still be in BTC so you are not mining to someone elses wallet.

MPM uses profitability data sent by ZergPool. In your case ZergPool pays best when mining a coin (ARGO) instead of the more generic algo 'skein' (option 1)

**Comment by mkirov0** [comment]
I see. I was just assuming the poll will auto mine the most profitable coin for a given algo.
Thanks for the info!

**Comment by aaronsace** [comment]
@UselessGuru I'm really liking this as it is; is the performance hit that bad? 

I think I have used Option 2 and 3 as intended because it's not switching between coins; it's picking a coin or algo based on long term profits.

**Comment by UselessGuru** [comment]
> I'm really liking this as it is; is the performance hit that bad?

Difficult to say. If someone want to mine in LTC -> +200 stat files. This means 200 extra stat files that MPM will need to process on every loop.

> I think I have used Option 2 and 3 as intended because it's not switching between coins; it's picking a coin or algo based on long term profits.

I have a different view on this.
I interpret option 2 & 3 like: Mine A specific coin, e.g. GUN and I want to be paid in GUN for as long as this combo is most profitable. There is no way to configure the coin I want to receive this as it stands now.

> it's picking a coin or algo based on long term profits.
Having all possible coin/algo combinations as available miner makes little sense to me. As I understand it the pool will always mine the best paying coin/algo and convert to payout currency. Profit should not be higher if I mine to to a defined coin.

**Comment by Nickduino** [comment]
Agreed

**Comment by UselessGuru** [comment]
> Agreed

With what? God, the world and the universe? :-)

**Comment by robl45** [comment]
This is wrong and should be fixed immediately.  Major flaw with how this is being done.  Option 2 and 3 were not meant to be done like this.  They were meant if someone wants to do a specific coin.
Specific to multipool miner is we would like to auto exchange the earning whether it be BTC or LTC or whatever.  Many of the coins on Zergpool are set to no autoexchange yet MPM will still pick those coins.  Most importantly, even if you disable the mc= lines form the pool file, it is still reading the profit from coins that can't be mined on autoexchange so I've had to disable neoscrypt currently as the profits are completely wrong.

**Comment by aaronsace** [comment]
> Option 2 and 3 were not meant to be done like this. They were meant if someone wants to do a specific coin. 
That's exactly how it's being done, it's not switching between coins. 
> Many of the coins on Zergpool are set to no autoexchange yet MPM will still pick those coins. 
No it wont; their profits are set to zero. 
> Most importantly, even if you disable the mc= lines form the pool file, it is still reading the profit from coins that can't be mined on autoexchange so I've had to disable neoscrypt currently as the profits are completely wrong.
Don't remove 'mc='.

**Comment by robl45** [comment]
Trust me, it will, I just watched it do it, just because its no autoexchange doesn't mean its profits are set to zero.

**Comment by robl45** [comment]
Not Zero

![image](https://user-images.githubusercontent.com/34346751/37032939-2c99424e-2112-11e8-9d1f-46b0d71f5282.png)

**Comment by robl45** [comment]
any idea on how to fix this?  Is there something I can do quickly so I can re enable neoscrypt?

**Comment by aaronsace** [comment]
@robl45 I will add an option to select 1, 2 or 3 in the config but remove the code labelled Option 3 for now. 

I've contacted the pool op regarding this issue and awaiting a reply.

**Comment by robl45** [comment]
Okay, so where do we go to select option 1?  We need to make sure its only reading the main api and not all the separate coins.

**Comment by robl45** [comment]
I just commented out the extra currencies API for now.  Working correctly it seems now.

**Comment by mkirov0** [comment]
Answers both of my questions above...
<img width="619" alt="screen shot 2018-03-06 at 4 41 53 pm" src="https://user-images.githubusercontent.com/28104701/37038610-ecc5d69a-215d-11e8-81af-41f1561dc445.png">
<img width="596" alt="screen shot 2018-03-06 at 4 47 01 pm" src="https://user-images.githubusercontent.com/28104701/37038688-28589760-215e-11e8-8811-44dc2dd6b056.png">
Thanks!

**Comment by UselessGuru** [comment]
@mkirov0 
 > Answers both of my questions above...

I am trying to understand, can you clarify please? Thanks!

**Comment by robl45** [comment]
I think what he was trying to say is Bashcoin is sitting in his mined section because its non autotrade.

**Comment by mkirov0** [comment]
I was wondering why I would have a specific coin mining instead of the algo. That was answered earlier. And now after I read the all the posts and went to ZergPool and compared I understand why I had that issue #1405 so it all makes sense now. I have disabled ZergPool for now, but will follow closely what happens here.
Thanks for all the info

**Comment by UselessGuru** [comment]
Regarding option 2:

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1413 (in this case on MPH) is an example of how I think MPM should handle option 2.

**Comment by UselessGuru** [comment]
Follow up of https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1413 and why we need a different approach

Option 2 is a combination of coin AND payout currency. This is why I developed my initial ZergPool miner.

To fully support a ZergPool Option 2 scenario we need a MiningCurrency and a PayoutCurrency.
Where PayoutCurrency can very from coin to coin

**Comment by aaronsace** [comment]
@UselessGuru Option 2 is complete, it works the same as the YiiMP pool file.

**Comment by UselessGuru** [comment]
@aaronsace 

I think we should separate ZergPool into ZergPool and ZergPoolCoins. [This scenario](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1413) is not possible with a mixed miner; we cannot prevent 'normal' algo mining.

**Comment by aaronsace** [comment]
@UselessGuru I've just check Option 1 only needs '$ZergPool_Request' and Option 2+3 only needs '$ZergPoolCoins_Request' so do 'ZergPool.ps1' for Option 1 and 'ZergPoolCoins.ps1' for Option 2+3.

**Comment by UselessGuru** [comment]
@mkirov0 

Thanks.
No action is required. Latest ZergPool files point to [europe.]mine.zergpool.com.
