### ISSUE TITLE
Option To Not Mine Specific Coin

### ISSUE THREAD

**Issue by jeetbarman** [MultiPoolMiner/MultiPoolMiner#1364]
Is there any option by which we can specify coin that shouldn't be mined?

I can see on MPH header "Zcoin, Zclassic wallets are under maintenance in Bittrex. Auto exchange requests related to these currencies may be stopped or delayed temporarily" , I would like to stop mining Zclassic temporarily so is it possible to do so?

Under -algorithm property we can mention our liked algorithm but as we know many algorithm has the capability of mining multiple coin hence restriction on algorithm is not solving my issue.

**Comment by UselessGuru** [comment]
> Is there any option by which we can specify coin that shouldn't be mined?

Nope. There should be no need. This should be handled by the pool operators. If there is a problem with a coin then the coin should
- either not be available through the API
- or the API should indicate that it is not working by either setting the pricing info to 0 (no profit, which will then be filtered by MPM) or with a speed of 0 hash (which will cause MPM to ignore this coin)

**Comment by aaronsace** [comment]
'wallets are under maintenance in Bittrex' does not mean mining is down; you just need to log in to MiningPoolHub and click to move the coins to the exchange after the maintenance is over.
