### ISSUE TITLE
Unable to use Reorder with MPM version 2.7.2.6

### ISSUE THREAD

**Issue by romulus2k4** [MultiPoolMiner/MultiPoolMiner#1366]
I am having problems using Reorder with the latest release.

For some reason, it fails to execute the miner despite the configurations being accurate. 

Any help would be appreciated.

**Comment by UselessGuru** [comment]
> using Reorder with the latest release.

??? What is 'Reorder'?

Please post logs and screenshots - TIA!
I don't want to be rude, but when posting here always think of 'What would I need to know so that I could help efficiently?'

**Comment by romulus2k4** [comment]
Apologies. I thought most would be familiar with Reorder. It's a fork of CGMiner, used mostly for Skein and Keccak, performs really well on older HD 7000 cards.


`Redirection is not supported.`

This is what the log says. The configuration used as follows:

```
[
    {
        "Type":  "AMD",
        "Path":  ".\\Bin\\Reorder\\cgminer.exe",
        "Arguments":  "--api-port 4028 --api-listen --skein -o $($Pools.Skein.Protocol)://$($Pools.Skein.Host):$($Pools.Skein.Port) -u $($Pools.Skein.User) -p $($Pools.Skein.Pass) --gpu-threads 2 --worksize 64 --expiry 30 --queue 1 --scan-time 15 --intensity 7 --gpu-platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | Select-Object -ExpandProperty Vendor), 'Advanced Micro Devices, Inc.'))",
        "HashRates":  {"Skein":  "$($Stats.ReorderAmd_Skein_HashRate.Week)"},
        "API":  "Xgminer",
        "Port":  "4028",
        "Wrap":  false
    },
    {
        "Type":  "AMD",
        "Path":  ".\\Bin\\Reorder\\cgminer.exe",
        "Arguments":  "--api-port 4028 --api-listen --keccak -o $($Pools.Keccak.Protocol)://$($Pools.Keccak.Host):$($Pools.Keccak.Port) -u $($Pools.Keccak.User) -p $($Pools.Keccak.Pass) --gpu-platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | Select-Object -ExpandProperty Vendor), 'Advanced Micro Devices, Inc.'))",
        "HashRates":  {"Keccak":  "$($Stats.ReorderAmd_Keccak_HashRate.Week)"},
        "API":  "Xgminer",
        "Port":  "4028",
        "Wrap":  false
    }
]
```

This used to work on older releases, but was removed since this miner isn't compatible with newer AMD cards and just crashes.
