### ISSUE TITLE
scrypt is ASIC territory

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1367]
From [ahashpool.com](https://ahashpool.com/) announcement:

> FYI, "scrypt" is ASIC territory, you should never try to mine "scrypt" with GPUs or CPUs.

> You will not earn anything with GPUs or CPUs on "scrypt".

**Comment by alucard20724** [comment]
scrypt has been asic territory for many years, as has been sha256 also.
