### ISSUE TITLE
Scaling factor for profits

### ISSUE THREAD

**Issue by Exodus4400** [MultiPoolMiner/MultiPoolMiner#1368]
It seems like zpool and ahashpool have changed their scaling for scrypt and keccak from BTC to mBTC. My mining profitability about 1,000x bigger than what it should be, throwing everything off (4.3 eth per day instead of ~0.003 for all others.)

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1369
Zpool is alread fixed: https://github.com/MultiPoolMiner/MultiPoolMiner/commit/9ea7695b01a257f2247b1a2cde0f83a0e6d08fcf
