### ISSUE TITLE
mpm keeps starting next run over and over after only seconds. 

### ISSUE THREAD

**Issue by Arackis** [MultiPoolMiner/MultiPoolMiner#1371]
New to MPM and trying to change over from Awesome miner. but I'm having issues with pwsh.exe it keeps starting next run after 0-1 second. 
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/37025798/36938224-6f5c3f58-1ee4-11e8-9a7e-1e663d459126.PNG">

**Comment by Arackis** [comment]
<img width="947" alt="capture2" src="https://user-images.githubusercontent.com/37025798/36938252-b8d7788c-1ee4-11e8-9da5-ae3456e7ce16.PNG">

**Comment by aaronsace** [comment]
Please zip up the logs and drop them onto the GitHub post.

**Comment by Arackis** [comment]
Sorry Aaronsace. I think I figured it out. It just don't show the work as its doing it. I'm a noob at mpm and have been reading all morning trying to figure it out. I found it after I checked the log and saw that it was still mining even after I thought it wasn't. You can close this issue. Again I'm sorry for wasting your time and thanks for getting back to me.
