### ISSUE TITLE
Bminer Watchdog

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#1372]
Hi guys,

I'm running the latest commit wich has the Bminer crashes fix regarding its watchdog. I was looking at the logs because my rig froze (had to reboot it) and found this at the MPM log:

2018-03-03 19:27:45 INFO: Stopping miner (ExcavatorNvidia1). 
2018-03-03 19:27:45 INFO: Starting miner (BMiner): 'C:\MPM_NR\Bin\NVIDIA-BMiner\BMiner.exe -api 127.0.0.1:1880 -uri stratum://titvs.miner01:x@europe.equihash-hub.miningpoolhub.com:17023 -nofee -watchdog=false'
2018-03-03 19:27:45 INFO: Pinging monitoring server. 
2018-03-03 19:27:45 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
2018-03-03 19:27:46 INFO: Start waiting before next run. 
2018-03-03 19:28:16 INFO: Finish waiting before next run. 
2018-03-03 19:28:16 INFO: Saving hash rates. 
2018-03-03 19:28:17 VERBOSE: BMiner: [INFO] [2018-03-03T19:27:47Z] Bminer: When Crypto-mining Made Fast (v5.4.0-ae18e12) 
**_2018-03-03 19:28:17 VERBOSE: BMiner: [INFO] [2018-03-03T19:27:47Z] Watchdog has started._**                        
2018-03-03 19:28:17 VERBOSE: BMiner: [INFO] [2018-03-03T19:27:47Z] Starting miner on devices [0 1 2 3 4] 

Im puzzled... Is the watchdog running or not?

Regarding the rig freeze, i also found that its dev fee run was with Bminer at nicehash but it was returning these errors:

INFO] [2018-03-03T18:55:08Z] Connected to equihash.eu.nicehash.com:3357   
[WARN] [2018-03-03T18:55:08Z] Get error: End of file, resetting in 5 seconds 
[INFO] [2018-03-03T18:55:13Z] Connected to equihash.eu.nicehash.com:3357   
[WARN] [2018-03-03T18:55:13Z] Get error: End of file, resetting in 5 seconds 
[INFO] [2018-03-03T18:55:13Z] Started miner on device 4                    
[INFO] [2018-03-03T18:55:14Z] Starting the management API at 127.0.0.1:1880 
[INFO] [2018-03-03T18:55:18Z] Connected to equihash.eu.nicehash.com:3357   
[WARN] [2018-03-03T18:55:18Z] Get error: End of file, resetting in 5 seconds 
[INFO] [2018-03-03T18:55:23Z] Connected to equihash.eu.nicehash.com:3357   
[WARN] [2018-03-03T18:55:23Z] Get error: End of file, resetting in 5 seconds 
[INFO] [2018-03-03T18:55:28Z] Connected to equihash.eu.nicehash.com:3357   
[WARN] [2018-03-03T18:55:28Z] Get error: End of file, resetting in 5 seconds 
[INFO] [2018-03-03T18:55:32Z] [GPU 0] Speed: 121.82 Sol/s 65.67 Nonce/s Temp: 59C Power: 120W 1.02 Sol/J 
[INFO] [2018-03-03T18:55:33Z] [GPU 1] Speed: 86.89 Sol/s 46.46 Nonce/s Temp: 60C Power: 137W 0.63 Sol/J 
[INFO] [2018-03-03T18:55:33Z] [GPU 2] Speed: 49.19 Sol/s 26.14 Nonce/s Temp: 50C Power: 0W +Inf Sol/J 
[INFO] [2018-03-03T18:55:33Z] Connected to equihash.eu.nicehash.com:3357   
[WARN] [2018-03-03T18:55:33Z] Get error: End of file, resetting in 5 seconds 

I wonder if it caused Bminer to hang the machine... I've tested MPM with nicehash has its second pool but gave up because Nicehash is still very unstable with constant disconnects...

Just to let you guys know and to know if theres anyone else with the same behavior.

**Comment by UselessGuru** [comment]
> latest commit wich has the Bminer crashes fix regarding its watchdog.

Bminer never crashed in that scenario. :-) 
MPM killed it because Bminer launched an extra process for its internal watchdog which conflicted with MPMs process monitoring.

> 2018-03-03 19:28:17 VERBOSE: BMiner: [INFO] [2018-03-03T19:27:47Z] Watchdog has started.

This may be a different type of WD. ??? We here do not have any inside knowledge about Bminer's internal logic.
If you continue to have problems with Bminer then just remove it from MPM.

**Comment by titvs** [comment]
Well, Bminer now has run for more than 9 hours without problems. And has for the "internal logic", with all the things that have been said about it, i doubt anyone knows (only its author). :)
Thanks for the heads up UG.
