### ISSUE TITLE
Claymore dual mining, Nicehash and keccak dont want to play together

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#1375]
I have been dual mining eth and keccak for the last several hours on MPH and Nicehash only to just notice nice hash has not been receiving shares. I went into the logs and couldn't find anything, so took your advice and copied the parameters from MPM to my own .bat file in claymore and ran it that way. It says it does not recognize keccak as valid for -dcoin and defaults to dcr. MPM did not throw an error.
<img width="871" alt="screen shot 2018-03-04 at 1 14 48 am" src="https://user-images.githubusercontent.com/28104701/36940366-529fec6e-1f4a-11e8-8e9f-481d894ccb49.png">
<img width="864" alt="screen shot 2018-03-04 at 1 24 38 am" src="https://user-images.githubusercontent.com/28104701/36940412-e94a894e-1f4a-11e8-81e1-bee42ef71d46.png">
Logs attached below....
[MultiPoolMiner_2018-03-03.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778009/MultiPoolMiner_2018-03-03.zip)

**Comment by aaronsace** [comment]
You have got the wrong version of claymore. 
https://mega.nz/#F!O4YA2JgD!n2b4iSHQDruEsYUvTQP5_w

**Comment by mkirov0** [comment]
Yesss that did it. I'm a happy miner now!
Thank you!
