### ISSUE TITLE
Not picking most profitable algo

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1381]
Clearly in the image below, Tribus is way more profitable than X17 even factoring in accuracy and it just sits on X17.  Switching prevention is set to default 2.  I've never seen this behavior in previous versions of multipool miner.  Yesterday to today it did like 3 algos the whole time.  Normally it would be at least 10

![image](https://user-images.githubusercontent.com/34346751/36946274-52d01c3e-1f88-11e8-808c-97759129471b.png)

**Comment by robl45** [comment]
[MultiPoolMiner_2018-03-04_08-22-41.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778540/MultiPoolMiner_2018-03-04_08-22-41.txt)

**Comment by boecht** [comment]
Looks good to me. In your screenshot tribus profitability has spiked to about 5x its regular value, which is smoothed to prevent exaclty these switches from happening.

The list is always sorted by (biased) longtime profitability. If you see high profit values low in the list, they are extreme spikes.

**Comment by robl45** [comment]
I don't know, previous versions would switch much more with same settings.    If its going to mine essentially 2 algorithms in 24 hours. Whats the point of the program?

**Comment by alucard20724** [comment]
@robl45 I was having the same issue. @aaronsace 
 did s fix as posted in the last thread here https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1349.
I downloaded the master yesterday after his fix, and just copied my Bin and Stat folders over, and reset profit.  Everything appeared to be working after that.

**Comment by robl45** [comment]
Downloaded master again as you mentioned.  It is now picking algorithms like it used to so hopefully that fixedit.
