### ISSUE TITLE
Slow performance with  2.7.2.6 vs 2.7.1.4

### ISSUE THREAD

**Issue by akmeikle** [MultiPoolMiner/MultiPoolMiner#1382]
Exact same config gives $3.6/day profit with 2.7.1.4 but $2.40/day profit with 2.7.2.6

Why would the latest version be considerably less profitable?

**Comment by m-bosch** [comment]
It should be the rate of the cryptocurrency I guess. all the coins are lower atm.

**Comment by akmeikle** [comment]
I agree things are down but I will run v2.7.1.4 and I get a certain rate per day, and when I close it and then run v2.7.2.6 right after I get a significant decrease in $/day with identical start.bat files which doesn't make any sense to me.  Thats why i'm currently running v2.7.1.4

I shouldn't get a 33% decrease in daily revenue when I update the software . . .

**Comment by aaronsace** [comment]
@akmeikle Reset your stats.

**Comment by mkirov0** [comment]
Just curious if the old config uses the keccak algo in the calculations... There was an update on the pool side reporting which may be causing this...

**Comment by aaronsace** [comment]
@mkirov0 Anyone's guess; they haven't even posted the logs to compare.

**Comment by akmeikle** [comment]
Negative ok Keccak

set "command=& .\multipoolminer.ps1 -wallet **** -username **** -workername htpc_mpm -region US -currency btc,usd -type nvidia -poolname miningpoolhub -algorithm cryptonight,ethash,equihash,groestl,lyra2re2,lyra2z,myriadgroestl,neoscrypt,pascal -donate 10 -watchdog -switchingprevention 2 -minerstatusurl https://multipoolminer.io/monitor/miner.php"

Will reset stats on old miner and see what happens

**Comment by akmeikle** [comment]
Reset the stats and now i'm getting $2.83/day with the old miner instead of $3.60

I assumed the daily revenue I was setting with multipool miner was accurate so basically for the last couple months i've been earning 33% less revenue which is fairly significant 

How can I ensure more accurate numbers with multipool miner?

**Comment by mkirov0** [comment]
I always check with the pools every day or so to make sure reports are correct. Thats how I discovered (with some help from @aaronsace ) I had the wrong version of claymore installed and it was not dual mining. I guess I can put in a future feature request for MPM to survey the pools for earnings. Maybe if they can be saved and compared to what the pools report will keep them honest. Could also help with the fluctuation. I know its way easier said than done. Just putting an idea out there.

**Comment by aaronsace** [comment]
@akmeikle If you didn't realize already, the profit is stored in a text file called 'profit.txt'

> so basically for the last couple months i've been earning 33% less revenue?

No, that's completely the wrong assumption.

**Comment by akmeikle** [comment]
Version 2.7.1.4 was reporting $3.60 per day (on miningpoolhub)
I reset the stats folder and did the benchmarks again
Version 2.7.1.4 I now am earning $2.83 per day

I was expecting to see $3.60 but now I only see $2.83.  That's 22% less than I was expecting (not 33% as I clearly fail at math)

If I hadn't updated i'd be merrily thinking I was earning 3.60 when in fact I was not.

I assumed the daily rate was fairly accurate but in this particular case it clearly isn't.  This is the only way I can really see profitability as i'm algo switching and i'm just concerned that there can be such a difference with the daily revenue with the same version of a particular miner just because I reset the stats and did the benchmarks again

**Comment by aaronsace** [comment]
@akmeikle You're not getting it, have you actually looked at the 'profit.txt' file?

**Comment by mwodzynski** [comment]
I honestly think that profit should be only provided in BTC. The prices of BTC change so much that comparing Fiat is illogical, and can be very misleading. 

Example:
Today it will show you that you make 1 BTC - 8500 USD
Tomorrow it can show you make 1 BTC - $11000 USD

Your miner still has the same hash power (earn the same amount of BTC per day) but if you look at USD you will think that there was something wrong the previous day.

Just my 2 cents.

**Comment by UselessGuru** [comment]
> I honestly think that profit should be only provided in BTC. The prices of BTC change so much that comparing Fiat is illogical, and can be very misleading.

This a personal matter - I only care for how much fiat I make.
To make everyone happy MPM could introduce a config item for the currencies to be used to display profit.

**Comment by aaronsace** [comment]
The problem here is nothing to do with exchange rates. They are comparing the profit from the week to the profit now; they are obviously not going to be the same. 

Regarding fiat, if you selected to display it in fiat (instead of the default of BTC) then it uses the current exchange rate. Everything is auto-converted to Bitcoin (not fiat) so it's simply a viewing preference.

**Comment by mkirov0** [comment]
> 
I honestly think that profit should be only provided in BTC. The prices of BTC change so much that comparing Fiat is illogical, and can be very misleading.
> 
I also don't think in fiat so I have excluded USD,EUR or any other fiat from -currency in start.bat and I do not see anything but BTC. If I understand the above statement correctly this should fix it for you.

**Comment by aaronsace** [comment]
Check the example 'start.bat' on how to display everything in BTC.
