### ISSUE TITLE
MultipoolMiner V2.7.2.6 writes the log in chinese

### ISSUE THREAD

**Issue by scolarita13** [MultiPoolMiner/MultiPoolMiner#1383]
I have updated MultipoolMiner with new version and everthing was fine until I have seen weird characters on PowerShell window. I have opened the log and it started properly with English messages then it switched to Chinese.
I doesn't seem to affect the mining. 
I have attached the log.

When I started the log was properly written in English. Could you switch the language to either French or English?

[MultiPoolMiner_2018-03-04.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778748/MultiPoolMiner_2018-03-04.txt)

scolaritaMiner

**Comment by aaronsace** [comment]
I don't know what is wrong with the Write-Log function. 

If anyone knows why this is happening or has an alternative solution to the Write-Log function then please post here.

**Comment by grantemsley** [comment]
I've seen similar thing happen on one of my machines - not the weird language but everything suddenly having a space between each letter.

Seems to be from Windows deciding it's UTF8 encoded instead of ASCII.

I believe I know how to fix that.

**Comment by scolarita13** [comment]
I have ran the same version of the multipoolminer on the same machine but for Zpool and it does not have the log written in Chinese..

**Comment by grantemsley** [comment]
@scolarita13 No, it's just an intermittent issues that doesn't happen very often.

If you were to open it in a text editor that lets you specify the encoding, or in a hex editor, you'd see the top half of the file is ascii encoded, and the bottom half (where the "chinese" starts) is UTF-8 encoded.  Windows has never been very good at dealing with text encoding.

**Comment by scolarita13** [comment]
in the start command I have changed the line: start pwsh -noexit -executionpolicy bypass -command "& .\reader.ps1 -log 'MultiPoolMiner_\d\d\d\d-\d\d-\d\d\.txt' -sort '^[^_]*_' -encoding ASCII -quickstart" by adding -encoding ASCII. I have removed the logs and restart the Start-MiningPoolHub.bat. Everything seems to be back to normal. I am waiting for the second change when is released.
Question: Do I have to re-bench when a new release is installed? 

Thank you for your support.

**Comment by tiotoi** [comment]
@scolarita13 thanks a lot, its working for me

**Comment by UselessGuru** [comment]
> Question: Do I have to re-bench when a new release is installed?

It is recommended to update to a new directory. You can (not recommended) copy the contents of the 'Stats' folder to keep your existing benchmark data.
When updating a miner binary it is recommended to remove the benchmark files for that miner.

Sidenote: Please do not mix topics withing the same thread, it makes issues difficult to track. Thanks!

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1384
