### ISSUE TITLE
Mining to undesired pools

### ISSUE THREAD

**Issue by mwodzynski** [MultiPoolMiner/MultiPoolMiner#1385]
I just noticed that MPM is mining to pools that are not specified in start file. I am setup to mine only on Mining Pool Hub, but noticed other polls in my list are used:  

AhashPool, NiceHash, zpool, blazepool, 

It also looks like it is mining to aaronsace wallet address. WHY???

![screenshot 4](https://user-images.githubusercontent.com/34895306/36953920-ec2a8efe-1fe3-11e8-87bd-812d39065040.png)

**Comment by aaronsace** [comment]
@mwodzynski Please read the website or the readme.

**Comment by mwodzynski** [comment]
@aaronsace 

Are you referring to:

IMPORTANT:_ The specified pool here will be used as default (preferred) but this does not rule out other pools to be included. Selecting multiple pools is allowed and will be used on a failover basis OR if first specified pool does not support that algorithm/coin. See the -algorithm command below for further details and example.

I saw this but honestly did not think anything about it. Should I add my BTC wallet address to my start file just in case.

or are you referring to something different? 

Thanks

**Comment by mwodzynski** [comment]
I added -ExcludePoolName and -Wallet to my start file. I assume that you referred to these in your previous response.

Please let me know if I am missing something.

Great work with the MPM. Thanks a lot. I will make sure to increase my donation once my equipment ROIs.
