### ISSUE TITLE
CcminerLyra2RE2 (Lyra2RE2-NVIDIA\ccminer.exe) - Failing with output " ...retry after 30 seconds"

### ISSUE THREAD

**Issue by jeetbarman** [MultiPoolMiner/MultiPoolMiner#1389]
Since today morning observed new miner CcminerLyra2RE2 which is continuously failing with output "...retry after 30 seconds"
Tried to find previous log of this miner unfortunately same was not available and it seem CcminerLyra2RE2 was never used previously.
![image](https://user-images.githubusercontent.com/36787233/36957686-2139e68a-205c-11e8-86ad-a34aff75a762.png)
[MultiPoolMiner_2018-03-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1779518/MultiPoolMiner_2018-03-05.txt)
![image](https://user-images.githubusercontent.com/36787233/36957795-fbc9a25e-205c-11e8-912a-47103f72fdda.png)

**Comment by jeetbarman** [comment]
Last screenshot given was after running same command outside MPM .

So if I have got you correctly it's a connectivity issue of a specific miner i.e. (Lyra2RE2-NVIDIA\ccminer.exe) with miningpoolhub?

Miningpoolhub was running fine with other miner which means (Lyra2RE2-NVIDIA\ccminer.exe) is faulty one.

Shall I use -ExcludeMinerName for this issue?

**Comment by UselessGuru** [comment]
> Shall I use -ExcludeMinerName for this issue?

That is an option.

> Miningpoolhub was running fine with other miner which means (Lyra2RE2-NVIDIA\ccminer.exe) is faulty one.

Not necessarily, maybe the pool has an issue with just this one algo.

**Comment by jeetbarman** [comment]
@UselessGuru It's been observed (Lyra2RE2-NVIDIA\ccminer.exe) is always failing with output "...retry after 30 seconds".
If it would have been temporary issue then same would have been resolved by today.

[CcminerLyra2RE2-4068_2018-03-06_12-14-41.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783829/CcminerLyra2RE2-4068_2018-03-06_12-14-41.txt)
[CcminerLyra2RE2-4068_2018-03-06_11-35-54.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783830/CcminerLyra2RE2-4068_2018-03-06_11-35-54.txt)
[CcminerLyra2RE2-4068_2018-03-05_14-12-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783831/CcminerLyra2RE2-4068_2018-03-05_14-12-24.txt)
[CcminerLyra2RE2-4068_2018-03-05_09-45-02.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783832/CcminerLyra2RE2-4068_2018-03-05_09-45-02.txt)
[CcminerLyra2RE2-4068_2018-03-05_07-59-30.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783833/CcminerLyra2RE2-4068_2018-03-05_07-59-30.txt)
[CcminerLyra2RE2-4068_2018-03-05_07-20-47.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783834/CcminerLyra2RE2-4068_2018-03-05_07-20-47.txt)
[CcminerLyra2RE2-4068_2018-03-05_05-25-14.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783835/CcminerLyra2RE2-4068_2018-03-05_05-25-14.txt)

**Comment by jeetbarman** [comment]
![image](https://user-images.githubusercontent.com/36787233/37018533-c45f5f0a-213a-11e8-870f-19f33bf66fad.png)

**Comment by UselessGuru** [comment]
As you can see you have the error when starting the miner outside of MPM.
Then how should it work WITH MPM?

I testest on my PC and it works:

![untitled](https://user-images.githubusercontent.com/30080938/37019752-cd83e928-2119-11e8-844e-6e10980606b6.png)

Possible reasons for your problem:
- temp. issue with the pool
- FW issue

There is nothing MPM can do about this if it does not work for you.

**Comment by jeetbarman** [comment]
@UselessGuru I have included CcminerLyra2RE2 under exclusion list.

-ExcludeMinerName ExcavatorNvidia1,ExcavatorNvidia2,Excavator1,Excavator2,CcminerLyra2RE2

As per your previous suggestion I did excluded Excavator and Post exclusion there was no Staus: Failed instance, for last 9hr MPM is running smoothly without any issue.

Is there any specific Excavator version that I can use in order to resolve Excavator issue?

**Comment by UselessGuru** [comment]
> Is there any specific Excavator version that I can use in order to resolve Excavator issue?

I don't think so, the issue is caused by the launch process and not the miner itself. I'd be very surprised if it worked with an older version of excavator.

BTW: Excavator officially no longer supports AMD :-(

**Comment by jeetbarman** [comment]
@UselessGuru Issue has now been resolved post replacing existing ccminer with  

https://github.com/tpruvot/ccminer/releases/tag/2.2.1-tpruvot

![image](https://user-images.githubusercontent.com/36787233/37053490-50bd3c8a-21a2-11e8-8727-e23a7e7af602.png)

**Comment by UselessGuru** [comment]
> Issue has now been resolved post replacing existing ccminer with ccminer x86 file from below link.

That does not make sense, but if it helps you then fine.

Just note that you will not get same speed for lyra2v2 with 2.2.1 than with 1.7.6.
I am pretty sure that 1.7.6 will now work too :-)

**Comment by jeetbarman** [comment]
@UselessGuru Since you insisted I tried it again but still didn't worked with 1.7.6

![image](https://user-images.githubusercontent.com/36787233/37058389-5f40d6e6-21b0-11e8-986a-8887cd7be888.png)

**Comment by jeetbarman** [comment]
Working with 2.2.1 , speed is on lower side hence any other version which can be used for better speed?

![image](https://user-images.githubusercontent.com/36787233/37058728-723ce5a4-21b1-11e8-85a3-f34c989af067.png)

**Comment by jeetbarman** [comment]
It seem with 2.2.4 hash rate increased and no matter what I do 1.7.6 will never work.

![image](https://user-images.githubusercontent.com/36787233/37059979-f0bfcab0-21b4-11e8-9db6-eb6894652a85.png)
