### ISSUE TITLE
Are there any news for the known issues?

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1391]
Is this still an issue in the [readme](https://github.com/MultiPoolMiner/MultiPoolMiner#known-issues)?

> 
> ## KNOWN ISSUES
> 
> There are known issues with the following miners not submitting shares or show higher hashrate than what they actually do:
> - CCminerLyraZ
> - CCminerLyra2RE2
> 
> This is not a fault of MultiPoolMiner and nothing can be done on our end. Please raise an issue on their respective github pages. See FAQ#2 on how to exclude these if you wish to do so.

**Comment by UselessGuru** [comment]
Yes. Unless the miner binaries get updated (which tehy have not) the issues will remain.

**This is not a fault of MultiPoolMiner and nothing can be done on our end.**

**Comment by borzaka** [comment]
Then why don't you guys still include these miners?

**Comment by UselessGuru** [comment]
> Then why don't you guys still include these miners?

Because people scream 'why don't you?' if we didn't. The problem is well documented
