### ISSUE TITLE
Anyway to make watchdog less aggressive?

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1394]
As subject says, is there anyway to make watchdog less aggressive?  On my system it keeps kicking algorithms and I know the algorithms are working.    I don't want to eliminate watchdog, but maybe bring them off watchdog quicker.  Is there anyway to edit the code to do that?

**Comment by UselessGuru** [comment]
> Is there anyway to edit the code to do that?

Yes, sure there is :-) But you'll be deviating away from MPMs codebase.
The keywords are
$Strikes
$WatchdogInterval
$WatchdogReset

> On my system it keeps kicking algorithms

Woldn't it be better to eliminate the source of the problem?

**Comment by robl45** [comment]
I'd love to get rid of the source of the problem, but it seems completely random, there are 4 or 5 algorithms that seem to get kicked, coincidentally the most profitable ones typically and I'm watching now and watchdog timer is not moving up.  Othertimes I've seen it watchdog timer is constantly creeping up.  I know the miners and algorithms work as I'm watching them work.

As for the keywords you mention.  I saw those in the code, but I'm not sure what to do with it.  Just looking for an easy way to say watchdog reenable my algorithm after 10 minutes or something instead of after 2 or 3 hours or whatever its doing now.

**Comment by robl45** [comment]
Just lost Tribus.

![image](https://user-images.githubusercontent.com/34346751/36977009-a06e3050-204d-11e8-8b6d-ff0add5b756e.png)

**Comment by UselessGuru** [comment]
Can you please check the CcMinerXevan log file? If you are not sure which one is of interest then zip the whole log dir and uploaded it.

Without having seen any log my first wild guess is to much OC of GPU memory.

**Comment by robl45** [comment]
[CcminerXevan-4068_2018-03-05_08-25-02.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1780973/CcminerXevan-4068_2018-03-05_08-25-02.txt)
[CcminerTpruvot-4068_2018-03-05_08-11-03.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1780976/CcminerTpruvot-4068_2018-03-05_08-11-03.txt)
[MultiPoolMiner_2018-03-05_07-39-58.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1780981/MultiPoolMiner_2018-03-05_07-39-58.txt)
[MultiPoolMiner_2018-03-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1780983/MultiPoolMiner_2018-03-05.txt)

**Comment by robl45** [comment]
Now I just lost X16R algorithm that I just added for Zergpool.

[CcminerTpruvot-4068_2018-03-05_09-01-31.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1781079/CcminerTpruvot-4068_2018-03-05_09-01-31.txt)

**Comment by UselessGuru** [comment]
I cannot see anything wrong in the log files. 
But you are running MPM from a path with spaces. This is not recommended. Does the error persists if you run it from a directory without special characters?

**Comment by robl45** [comment]
highly doubt that will make a difference, but I did change the folder name.

**Comment by alucard20724** [comment]
I've noticed this problem too.  I've narrowed it to if the CPU is overloaded or not.   I see this often on my system with 10 gpu.  I've had to turnoff the watchdog on that system.  the cpu is a i7700K.
if the system has 4 gpu or less, this doesn't happen as often with the same cpu.

i think it's related to cpu load on the system.  it's affected more if you are mining with the cpu also, less if not.

**Comment by robl45** [comment]
kicked X16r again.

**Comment by robl45** [comment]
I removed watchdog for now, but that is not the solution especially when the algorithms appears to be working fine and are getting kicked anyway.  I don't even mind if it kicks them and I could set like 5 minutes to bring them back, but having it wait hours to bring them back and then kick them 10 minutes later doesn't make sense.

**Comment by robl45** [comment]
I reran again for that algorithm.  This is the third time rebenching it.

**Comment by aaronsace** [comment]
You must be able to see if it's wrong; it will just be obvious look at the mining running. 

If you want to give it more time, increase the interval from 60 seconds to 120 seconds.

**Comment by robl45** [comment]
Yes, I'm watching the miner run each time, its working fine and generating BTC at the pool.

**Comment by aaronsace** [comment]
@robl45 We are talking about the hash rate on your screen here.

**Comment by robl45** [comment]
Yes, hashrate seems fine.

**Comment by aaronsace** [comment]
Then it wont kick; done.

**Comment by robl45** [comment]
Thats the problem, it does kick, along with X17, Tribus, etc.  Its been doing this for awhile.

**Comment by aaronsace** [comment]
Just repeat the same steps.

**Comment by robl45** [comment]
I can rebenchmark the offending ones, but when I said its been doing this awhile, I meant through multiple versions of the software and multiple benchmarks.

**Comment by aaronsace** [comment]
Then your hash rates are wrong then and not 'fine'. 

You'll need to fix it as MultiPoolMiner can't fix it.

**Comment by robl45** [comment]
Correct me if I'm wrong, but X16R supposedly uses a bunch of different algorithms to defeat asic, so wouldn't it make sense that the hashrate is going to vary?

**Comment by aaronsace** [comment]
I have no idea; it wont work if it does.

**Comment by UselessGuru** [comment]
[X16R issues are discussed in this thread](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1412)

**Comment by UselessGuru** [comment]
See  https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1682
