### ISSUE TITLE
Can We Have LocalCurrency/Day Column

### ISSUE THREAD

**Issue by jeetbarman** [MultiPoolMiner/MultiPoolMiner#1400]
Referring to nemos miner we can see localcurrency/Day details on miner chart, can we have that same details on MPM?

**Comment by UselessGuru** [comment]
> localcurrency/Day details on miner chart,

What is the miner chart? Please post screenshots

**Comment by jeetbarman** [comment]
![image](https://user-images.githubusercontent.com/36787233/37018275-ca1b48ec-2139-11e8-992e-5d711180f7d4.png)

**Comment by UselessGuru** [comment]
And what would you like to have added?

**Comment by jeetbarman** [comment]
INR/DAY Column, like nemos

![image](https://user-images.githubusercontent.com/36787233/37018615-018d63b8-213b-11e8-82e7-9a4939b396b0.png)

**Comment by UselessGuru** [comment]
This exists already, You need to define  more than one currency in start.bat. The first currency will be shown as above.

**Comment by jeetbarman** [comment]
My Mistake I added BTC, INR under currency which in return was showing only BTC value. Now I have removed BTC and it's working perfectly fine.

Thank You.
