### ISSUE TITLE
Intensity Of Mining

### ISSUE THREAD

**Issue by cybertron2007** [MultiPoolMiner/MultiPoolMiner#1401]
Hi,

As multi pool miner will download & install multiple miners based on given mining type (i.e. CPU, GPU). As each miner will have their own intensity. Does multi pool provide some global setting on which we can set intensity for all miners. Like use only 30% CPU. 30% for Each GPU etc. Please let me if such settings available with multi pool miner.

Regards

**Comment by UselessGuru** [comment]
There is no such setting. It is technically not possible to apply the same intensity to all miners.
[Also read here.](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1143)

Please close it you are satisfied with the answer - TIA.
