### ISSUE TITLE
Help Required - Setting up backup pool with LTC payout

### ISSUE THREAD

**Issue by jeetbarman** [MultiPoolMiner/MultiPoolMiner#1402]
I want to setup blockmunch as  backup pool and want payment as Litecoin, how can I achieve this?

Under startup.bat
-wallet ----> Can I use LTC address?

Where can I define coin parameter LTC?

E.g from blockmunch.club :-
stratum+tcp://blockmunch.club:PORT -u wallet_address -p **_c=LTC_**    

Kindly let me know where can I define this coin parameter

**Comment by UselessGuru** [comment]
You need to edit config.txt. For a guideline see here:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1105

**Comment by jeetbarman** [comment]
@UselessGuru Since I will be adding this value manually would really appreciate if you can cross validate below command which will be entered on config.txt
 
"Pools": {
    "Blockmunch": {
      "LTC": "32dgKpDPDTGk3SeShYFnhv5QaJgbnBM1mJ",
      "Worker": "$WorkerName",
  
Do I have to add anything else apart from above details?

![image](https://user-images.githubusercontent.com/36787233/37032641-4ffc65fc-2169-11e8-8df8-4140ce994202.png)

**Comment by UselessGuru** [comment]
Be careful with the commas and brackets. Follow the examples closely.

```
"Blockmunch": {
"LTC": "32dgKpDPDTGk3SeShYFnhv5QaJgbnBM1mJ",
"Worker": "$WorkerName"
},
```
The last element in a series of elements must not have a comma.

**Comment by jeetbarman** [comment]
@UselessGuru It did worked, thank you very much.
