### ISSUE TITLE
Moving to a new version of MultiPoolMiner: WARNING: No miners available.

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1403]
Unfortunately it is essential to move frequently to a new version (even it's not a release yet), because currently every released version has an almost breaking issues; preventing to maximize the profit.

So, moving to a new version, this is my step:
1. download master (not a release)
2. copy my Stats folder from the previous version
3. run ResetProfit.bat
4. edit Start.bat (or copy from the previous version)
5. run Start.bat

```
2018-03-06 11:07:56 INFO: Updating exchange rates from Coinbase. 
2018-03-06 11:07:56 INFO: Loading saved statistics. 
2018-03-06 11:07:57 INFO: Loading pool information. 
2018-03-06 11:08:03 INFO: Selecting best pool for each algorithm. 
2018-03-06 11:08:03 INFO: Getting miner information. 
2018-03-06 11:08:10 INFO: Calculating profit for each miner. 
2018-03-06 11:08:11 WARNING: No miners available.
```

I think, in that case, MPM should download the miner binaries again. If I copy over the Bin folder from the previous version, there is a chance, that I will use an older version one of the miners.

**Comment by UselessGuru** [comment]
It is NOT recommended carry over miner binaries or stat files.

> I think, in that case, MPM should download the miner binaries again. If I copy over the Bin folder from the previous version, there is a chance, that I will use an older version one of the miners.

Miner version and stats file belong together.
You should NOT update the miner WITHOUT deleting the stats for it. Otherwise you will not profit from eventual performance improvement of the new miner version.

**Comment by borzaka** [comment]
What do you recommend for the following scenarios?
- moving from MultiPoolMinerV2.7.1.4 to MultiPoolMinerV2.7.2.6 (huge changes, many new miner versions, etc.)
- moving from MultiPoolMinerV2.7.2.x to MultiPoolMinerV2.7.2.y (minor changes, bug fixes, etc.)

Rebenchmark everything with 5 minutes interval is a half a day procedure :( I know it's mining during benchmark, but not the most profitable algo.

Miner updates not always comes with performance improvements. Sometimes it's just feature updates (`--color` option), or bug fixes, or more stable running with overclocks.
If I hear performance improvements, than I would delete the stats file and rebenchmark it.

**Comment by UselessGuru** [comment]
> It is NOT recommended carry over miner binaries or stat files.

That is the general guideline. Lots of people are not familiar with all the dependencies.
Stat files are compatible between releases (so far, maybe that will change in the future).

> If I hear performance improvements, than I would delete the stats file and rebenchmark it.

That's fine.

**Comment by paulpoco** [comment]
So eliminate algos from your start.bat that are always low profits for your GPUs or CPU to speed up benchmarking?

Are we close to a new point release from 2.7.2.6?

**Comment by UselessGuru** [comment]
> So eliminate algos from your start.bat that are always low profits for your GPUs or CPU to speed up benchmarking?

A good starting point are the algos that are included in the default 'start.bat'. You can always add more algos later. There is no need to benchmark all algos just 'because you can'.
