### ISSUE TITLE
ZergPool reports do not match actual returns

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#1405]
This is not an issue with MPM so thats why I did not add it to #1362 
@UselessGuru if you think it is related I can close this one and post there.

I have been mining (all available algos and pools added to MPM start.bat) on ZergPool for about 20 out of the last 24 hours as MPM switches to the most profitable algo reported by the pools. As I have been monitoring the reported profits I am certain the actual profit applied to the account (BTC wallet) on ZergPool's website is about 50% of what it should have been according to MPM which takes the stats from the pool.
I am just trying to see if anyone else has noticed similar difference between estimated and actual profits specifically with ZergPool. I know that MPM goes by what the pool reports, so its not an MPM issue.
I know I can disable ZergPool and reset stats and disable algos, but just want to gather some info before I do that.
Will appreciate any input. 
Thanks!
[MultiPoolMiner_2018-03-06.txt.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1785146/MultiPoolMiner_2018-03-06.txt.zip)
[MultiPoolMiner_2018-03-05.txt.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1785155/MultiPoolMiner_2018-03-05.txt.zip)

**Comment by robl45** [comment]
I don't know, i find that going by actual numbers in a 24 hour period in the pool is the only way to accurately see what you get.  Even before zergpool, the number MPM shows aren't realistic versus what you get from the pool.

**Comment by UselessGuru** [comment]
This is known issue with all pools (but not to the same extent)

Read [here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1011) or [here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/894) or [here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/647) ...

**Comment by mkirov0** [comment]
OK after reading the new info in #1362 my issue is probably related to it so I'm closing this one.
Thanks for the replies!
