### ISSUE TITLE
Hieroglyphs

### ISSUE THREAD

**Issue by Nickduino** [MultiPoolMiner/MultiPoolMiner#1406]
Any chance this is a known issue?

![Weird output](https://image.ibb.co/dvhAxn/hieroglyphs.png)

I think everything is up to date (powershell, vcredist and all) on my system.

**Comment by jeetbarman** [comment]
Check this post https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1308

**Comment by Nickduino** [comment]
Thanks @jeetbarman

**Comment by UselessGuru** [comment]
This should fix it: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1384
