### ISSUE TITLE
Insane profits

### ISSUE THREAD

**Issue by 3zero2** [MultiPoolMiner/MultiPoolMiner#1409]
I noticed that MPM was saying that it was over 1000% more profitable and hence I reset the profits. However after that the situation got even worst! Check below the profits recorded on a single Titan Xp.

```
Miner                 BTC                           EUR
-----                 ---                           ---
MultiPoolMiner        0,07496 ±0% (0,07493-0,07499) 652,58329 ±0% (652,32057-652,84612)
CcminerTpruvot-Keccak 0,07496 ±0% (0,07496-0,07496) 652,58329 ±0% (652,58329-652,58329)
```

Log file attached:
[MultiPoolMiner_2018-03-07_00-03-53.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1787116/MultiPoolMiner_2018-03-07_00-03-53.txt)

**Comment by UselessGuru** [comment]
Some pools have changed their divisors.

There are changes pending to fix that.

Workaround for now:
- delete the erroneous stat files
- update these pool files
Zpool.ps1: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1388
ZergPool.ps1: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1397

**Comment by 3zero2** [comment]
Thank you. 

That fixed it.
