### ISSUE TITLE
assigning miner status key command isn't in readme file

### ISSUE THREAD

**Issue by Exodus4400** [MultiPoolMiner/MultiPoolMiner#1410]
With the ability to generate a miner status key at https://multipoolminer.io/monitor/#, it would be nice if the command to assign the key was in the readme file and the website.

**Comment by mkirov0** [comment]
I am sure I read it somewhere, but just add -MinerStatusKey to your start.bat if thats the info you are looking for.

**Comment by UselessGuru** [comment]
Added to [readme in this PR](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435)
