### ISSUE TITLE
Is there a place to specify how many miners there must be to mine an algorithm?

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1411]
On the useless guru version, there is a way to specify don't mine an algorithm with less than X amount of miners.  Is there a way to do it on this version?  I can't seem to find it.

**Comment by UselessGuru** [comment]
> Is there a way to do it on this version? I can't seem to find it.

No, this is not available. It requires new pool files.

**Comment by robl45** [comment]
So how many miners must be on an algorithm for it to mine it?  Or does it mine it even if there are zero?

**Comment by UselessGuru** [comment]
> Or does it mine it even if there are zero?

It only mines if the pool reports hash rate greater 0

https://github.com/MultiPoolMiner/MultiPoolMiner/commit/dce83480b8b8864caf08242b75b88e0ca3f4bf2b
