### ISSUE TITLE
MPM only for ZCL

### ISSUE THREAD

**Issue by radugabrielvoicu** [MultiPoolMiner/MultiPoolMiner#1413]
Hi,
We want to use MPM, because of better hashrate, downtime feature, etc, to mine only ZClassic on MPH Pool. Is this possible ?
 We went through documentation, forum posts, but nothing came up.
Please help with the settings.

Much appreciated
Thanks

**Comment by UselessGuru** [comment]
> We want to use MPM, because of better hashrate, 

No need for MPM. Just mine with a static config. You will not get better hash rates.

MPM does not allow to mine a specific coin on MPH, you con just narrow it down to pool & algo, but not coin. Maybe this will come in the future.

**Comment by UselessGuru** [comment]
@aaronsace 

Does this look like a desirable enhancement?

**Comment by UselessGuru** [comment]
@radugabrielvoicu 

This might work for you:

1. In start.bat configure MiningPoolHub as only pool ` -poolname MiningPoolHub`
2. Rename the attached file to 'MiningPoolHubCoins.ps1' and copy to 'Pools' folder (replace existing file)
[MiningPoolHubCoins.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1790029/MiningPoolHubCoins.txt)
3. Edit config.txt and add/modify the section for 'MiningPoolHubCoins' and define the **Coins** you want to mine (case insensitive list, separate strings with comma):

```
    "Pools":  {
                  "MiningPoolHub":  {
                                        "User":  "$UserName",
                                        "Worker":  "$WorkerName",
                                        "API_ID":  0,
                                        "API_Key":  ""
                                    },
                  "MiningPoolHubCoins":  {
                                             "User":  "$UserName",
                                             "Worker":  "$WorkerName",
                                             "API_ID":  0,
                                             "API_Key":  "",
                                             "Coins":  ["ZClassic", "ZenCash"]
                                         },
```
Note the commas in the right place. To test the modified 'config.txt' use a web service like http://jsonviewer.stack.hu/

**Comment by borzaka** [comment]
ZCL is an Equihash algo, you can use MPM to benchmark only Equihash algo, and after it's finished, you can select the best performing miner, and use the command what was used by MPM and run from the Bin folder directly.
Beware! Mining Pool Hub's port for ZCL is 20575, MPM will use port number 17023 for Equihash, because it's Mining Pool Hub's coin switch port for Equihash.

**Comment by aaronsace** [comment]
@UselessGuru That config could be rolled out for ZergPool as well in the master code branch.

**Comment by UselessGuru** [comment]
> That config could be rolled out for ZergPool

This works for MPH and Zpool (I'll do a pull for these)

For ZergPool I don't think this works. 

ZergPool discussion [cont'd here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1362)

**Comment by aaronsace** [comment]
What would it do for Zpool? 

I was meaning Option 3 on ZergPool then it's finished.

**Comment by UselessGuru** [comment]
@borzaka

>  Beware! Mining Pool Hub's port for ZCL is 20575, MPM will use port number 17023 for Equihash, because it's Mining Pool Hub's coin switch port for Equihash.

MinungPoolHub.ps1 uses 17xxx ports.
MiningPoolHubCoins.ps1 uses ports from http://miningpoolhub.com/index.php?page=api&action=getminingandprofitsstatistics -> 20xxx

**Comment by UselessGuru** [comment]
@radugabrielvoicu 

Please report feedback if it works - TIA!

**Comment by radugabrielvoicu** [comment]
I will test it today and give the feedback.
Thanks

**Comment by radugabrielvoicu** [comment]
@ UselessGuru 
Hi,

Have tested and getting a lot of errors. It is not working. Please advise :

The property 'MinerStatusKey' cannot be found on this object. Verify that the property exists and can be set. At C:\Users\Rig2\Downloads\Mining\MultiPo lMinerV2.7.2.6\MultiPoolMiner.ps1:159 char:52 + ...  -and -not $Config.MinerStatusKey) {$Config.MinerStatusKey = $Wallet} +                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo          : InvalidOperation: (:) [], RuntimeException + FullyQualifiedErrorId : PropertyAssignmentException  Add-Member : Cannot bind argument to parameter 'InputObject' because it is null. At C:\Users\Rig2\Downloads\Mining\MultiPoolMinerV2.7.2.6\MultiPoolMiner.ps1:162 char:25 +         $Config.Pools | Add-Member $_.BaseName ( +                         ~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand  Add-Member : Cannot bind argument to parameter 'InputObject' because it is null. At C:\Users\Rig2\Downloads\Mining\MultiPoolMinerV2.7.2.6\MultiPoolMiner.ps1:162 char:25 +         $Config.Pools | Add-Member $_.BaseName ( +                         ~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand  Add-Member : Cannot bind argument to parameter 'InputObject' because it is null. At C:\Users\Rig2\Downloads\Mining\MultiPoolMinerV2.7.2.6\MultiPoolMiner.ps1:162 char:25 +         $Config.Pools | Add-Member $_.BaseName ( +                         ~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by robertedvin** [comment]
Hello,

Since I am testing this with Radu, I want to add that:

1. We tried the above with the original Config.txt and it also doen't work.
2. We tested with the original Config.txt and adding just the Coins argument and still doesn't work.
3. My guess is that the error is coming from the tweaked MiningPoolHubCoins.ps1

**Comment by UselessGuru** [comment]
@ robertedvin 
@ radugabrielvoicu 

Could you please post your counfig.txt

Why did you close the issue?

**Comment by robertedvin** [comment]
Hello,

We didn't close the issue, I don't know what happened.

While uploading the config.txt I found the error. It was a missing comma in the Config.txt file after the "API_Key":  "" statement.

However, it will still go on mining Equihash on port 17023 which is Zcash.

Regards,
Robert

**Comment by UselessGuru** [comment]
@robertedvin

You can also [test these ZergPool files](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435)

**Comment by robertedvin** [comment]
Hello,

I tried with more coins and it seems to be working as expected.

Thanks a lot.

I will test those too. You rock man.

Regards,
Robert

**Comment by UselessGuru** [comment]
All fixes are now in this PR: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435. Commit is pending.
