### ISSUE TITLE
New X16r miner for AMD

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1414]
I came across a new x16r miner for amd gpus.
http://cryptomining-blog.com/9515-raven-rvn-x16r-miner-now-available-for-amd-gpu-miners-as-well/

I won't have time for the next couple of days to work on a script to work with mpm.  So if someone else gets to it before i do.  cheers.

https://github.com/aceneun/sgminer-gm-x16r/releases

**Comment by UselessGuru** [comment]
Keep this discussion in mind:

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1412

**Comment by alucard20724** [comment]
Here's the code i have.  Currently doesn't work with mpm.  since mpm hides mining windows now, it's difficult to do real time debugging with mpm.

so... have at it.

using module ..\Include.psm1

$Path = ".\Bin\X16r-AMD\sgminer.exe"
$Uri = "https://github.com/aceneun/sgminer-gm-x16r/releases/download/5.5.5/sgminer-x16r.zip"

$Commands = [PSCustomObject]@{

    "x16r" = "" #X16r

}

$Name = Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName

$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | Where-Object {$Pools.(Get-Algorithm $_).Protocol -eq "stratum+tcp" <#temp fix#>} | ForEach-Object {
    [PSCustomObject]@{
        Type = "AMD"
        Path = $Path
        Arguments = "--api-listen -k $_ -o $($Pools.(Get-Algorithm $_).Protocol)://$($Pools.(Get-Algorithm $_).Host):$($Pools.(Get-Algorithm $_).Port) -u $($Pools.(Get-Algorithm $_).User) -p $($Pools.(Get-Algorithm $_).Pass)$($Commands.$_) --gpu-platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | Select-Object -ExpandProperty Vendor), 'Advanced Micro Devices, Inc.'))"
        HashRates = [PSCustomObject]@{(Get-Algorithm $_) = $Stats."$($Name)_$(Get-Algorithm $_)_HashRate".Week}
        API = "Xgminer"
        Port = 4028
        URI = $Uri
    }
}

**Comment by richardg867** [comment]
@alucard20724 I added the miner myself as well, but it doesn't work for me even outside MPM (silent amdocl.dll crash just like mkxminer), before jumping to MPM check if it works at all on your end.

**Comment by alucard20724** [comment]
@richardg867 i'm not getting an amdocl.dll crash.   I'm also running drivers 18.2.2 in compute mode.   18.2.3 gave me a hash rate drop across most algo, so i stayed with 18.2.2.   what drivers are you running?

**Comment by richardg867** [comment]
18.2.3 in compute mode, Windows 10. Hashrates look fine for me.

**Comment by UselessGuru** [comment]
> has anyone gotten that to work either?

You better post this in the miners developer forum.

**Comment by angelics** [comment]
@richardg867 i might b wrong. but it worked on me here
goto ur startbat. find set GPU_FORCE_64BIT_PTR=1
change to set GPU_FORCE_64BIT_PTR=**0**
took me a noon to freaking found out the problem with sgminer + MPM + silent crash

**Comment by richardg867** [comment]
I eventually figured that out as well. It's also part of the problem with
mkxminer crashing (its batch files are set to 0 when they should be 1 but
it still crashes even though MPM sets 1). This needs a MPM-level change to
individually set the environment variables for each miner.

**Comment by UselessGuru** [comment]
SgminerK10n is supported.
