### ISSUE TITLE
Blockmunch pool with Excavator Not Taking Auto Exchange Coin 

### ISSUE THREAD

**Issue by jeetbarman** [MultiPoolMiner/MultiPoolMiner#1416]
While running other miner for blockmunch pool we can see execution command of miner ending with -c parameter which indicates preferred auto exchange coin but while Excavator command was executing preffered coin parameter didn't got selected.

![image](https://user-images.githubusercontent.com/36787233/37111237-301be346-2265-11e8-842b-c4ebe887d86b.png)

**Comment by UselessGuru** [comment]
-c stands for config file

Look at the contents of the JSON file. If in doubt feel free to post a sample.

**Comment by jeetbarman** [comment]
@UselessGuru Correct & thank you

![image](https://user-images.githubusercontent.com/36787233/37113948-ed6aa3c2-226c-11e8-9d1e-a0c6485ad85d.png)
