### ISSUE TITLE
Cannot find neoscrypt miner

### ISSUE THREAD

**Issue by telvors** [MultiPoolMiner/MultiPoolMiner#1419]
I keep getting a message that it cannnot find the neoscrypt miner and doesnt download it as well. Is there any way that I can download it?

**Comment by mwodzynski** [comment]
You should be able to download it at:
https://mega.nz/#F!2VskDJrI!lsQsz1CdDe8x5cH3L8QaBw

Then place it in: 
 C:\Users\Mining\Desktop\Mining\MultiPoolMiner-master\Bin\PhoenixMiner

**Comment by mkirov0** [comment]
Make sure you download the latest one!
The older versions are troublemakers. ...now ask me how I know 🤣

**Comment by telvors** [comment]
How???? Help!! 
And after I download it do I just put it on the miners folder?

**Comment by UselessGuru** [comment]
> And after I download it do I just put it on the miners folder?

Then place it in:
C:\Users\Mining\Desktop\Mining\MultiPoolMiner-master\Bin\PhoenixMiner

**Comment by telvors** [comment]
Great!!! thanks!!

**Comment by telvors** [comment]
It seems to be missing the claymore neoscrypt miner as well. Link for that ??


Thanks guys!!!

**Comment by UselessGuru** [comment]
> Link for that ??

Look in the miner file.

**Comment by telvors** [comment]
Thanks!!1 Solved!!
