### ISSUE TITLE
https://multipoolminer.io is down!

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1423]
![untitled](https://user-images.githubusercontent.com/30080938/37162633-09de250e-22f6-11e8-8911-69ac7bdca952.png)

Mining is not affected, just ignore the error messages. As soon as the web site is back error messages will stop. No restart or manual interaction is required.

**Comment by mwodzynski** [comment]
I am getting account suspended 
![screenshot 8](https://user-images.githubusercontent.com/34895306/37162984-44ada20c-22bc-11e8-8180-9ee507c83a13.png)

**Comment by mtbor** [comment]
Account suspended is what I see.

**Comment by jeetbarman** [comment]
Account suspended.....

**Comment by mtbor** [comment]
Miroslaw, be careful what info is visible in screenshots.

**Comment by jeetbarman** [comment]
Kindly confirm if MPM need to be stopped or is it still mining as I can see mining speed.

![image](https://user-images.githubusercontent.com/36787233/37166126-37837d5a-2324-11e8-825b-7e37704f4fd8.png)

![image](https://user-images.githubusercontent.com/36787233/37166152-50cd06a0-2324-11e8-9432-732ef0f74714.png)

**Comment by grantemsley** [comment]
It's still mining, it's just not able to report it's status to the website.  Mining will not be affected.

**Comment by mtbor** [comment]
You should always be able to verify your hashrate on the pool your are mining to.

**Comment by jeetbarman** [comment]
Issue resolved, everything is working normal as expected.
