### ISSUE TITLE
MiningPoolHub Not reflecting

### ISSUE THREAD

**Issue by jeetbarman** [MultiPoolMiner/MultiPoolMiner#1424]
None of the MPH details are now reflecting on mining page, only Blockmunch is showing.

![image](https://user-images.githubusercontent.com/36787233/37170215-4156639a-2330-11e8-80bc-f8adb3274d63.png)

**Comment by grantemsley** [comment]
Please upload logs.  Can't tell much from just a portion of a screenshot.
