### ISSUE TITLE
Profit per day does not show in miner

### ISSUE THREAD

**Issue by telvors** [MultiPoolMiner/MultiPoolMiner#1426]
After working through all the issues thanks to the help of everyone here, i came across another one.

It seems that my USD/day value in the bottom is not being displayed. I reset the profit.bat and it comes back but then goes away again. Could someone help with this issue?

**Comment by UselessGuru** [comment]
> It seems that my USD/day value in the bottom is not being displayed. I reset the profit.bat and it comes back but then goes away again. Could someone help with this issue?

How about some screenshots?

**Comment by telvors** [comment]
How do i attach screenshots?

**Comment by telvors** [comment]
Here you go:
![screenshot_20180309-113411](https://user-images.githubusercontent.com/37151572/37212495-ea280926-238d-11e8-9ab8-70893cdfd512.jpg)

**Comment by telvors** [comment]
As you can see I cannot see the profit usd/day... I reset the profito ratio and i keep getting same issue.

**Comment by UselessGuru** [comment]
@telvors 

Could you  please post logs? Did you get download errors?

@aaronsace 
I think this could be a running download task

```
    #Display profit comparison
    if ($Downloader.State -eq "Running") {$Downloader | Wait-Job -Timeout 10 | Out-Null}
    if (($BestMiners_Combo | Where-Object Profit -EQ $null | Measure-Object).Count -eq 0 -and $Downloader.State -ne "Running") {
```
How about writing download messages to a log file? This could help with other download issues too.

**Comment by telvors** [comment]
[2018-03-08_23-49-03.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1797491/2018-03-08_23-49-03.txt)
[2018-03-08_20-11-37.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1797492/2018-03-08_20-11-37.txt)
