### ISSUE TITLE
mpm + claymore

### ISSUE THREAD

**Issue by haliavshik** [MultiPoolMiner/MultiPoolMiner#1427]
i have mixed rigs and i mine to nanopool with AMD - if i set ethash on Nvidia with MPM it constantly closes claymore - even if it does not mine with it on Nvidia. How to stop MPM from closing it? without turning off ethash algorithm

**Comment by UselessGuru** [comment]
> i have mixed rigs and i mine to nanopool with AMD - if i set ethash on Nvidia with MPM it constantly closes claymore - even if it does not mine with it on Nvidia. How to stop MPM from closing it? without turning off ethash algorithm

Suggestion:
Keep a separate copy of EthDcrMiner64.exe (e.g. EthDcrMiner64_AMD.exe) and use that for mining AMD. 

Please post your result here.

**Comment by haliavshik** [comment]
Running different name for .exe on amd worked. thank you.

**Comment by UselessGuru** [comment]
@aaronsace 

This one is worth looking into. Probably the same cause a bminer getting killed.
