### ISSUE TITLE
Nvidia GTX 780 Doesn't mine at all when multiple algorithms are enabled

### ISSUE THREAD

**Issue by IndiaVenom** [MultiPoolMiner/MultiPoolMiner#1428]
I enabled all algorithms, except I replaced Ethhash with Eth2gb, I'll attach my logs and batch file. But the GPU is never used, only the CPU. I did run a test with only allowing Eth2gb, and that used the GPU correctly.

Logs Linked here:
https://drive.google.com/open?id=1DZMrN3VPd1zOYE9u-CHc4_1nWofI-jGn

Start.bat:
cd /d %~dp0

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

set "command=& .\multipoolminer.ps1 -username IndiaJonathan -workername MainComp -region us -currency usd -type nvidia,cpu -wallet 3NwbWcfRconRi9hRUAVRCy4CWXgjTE6AsP -poolname miningpoolhub,miningpoolhubcoins -algorithm Bitcore, Blakecoin, Blake2s, BlakeVanilla, C11, CryptoNight, Ethash2gb, X11, Decred, Equihash, Groestl, HMQ1725, HSR, JHA, Keccak, Lbry, Lyra2RE2, Lyra2z, MyriadGroestl, NeoScrypt, Nist5, Pascal, Phi, Polytimos, Quark, Qubit, Scrypt, SHA256, Sib, Skunk, Skein, Timetravel, Tribus, Veltor, X11, X11evo, X17, Yescrypt -donate 10 -watchdog -minerstatusurl https://multipoolminer.io/monitor/miner.php -MinerStatusKey d819b45c-0bd1-41c5-af88-37026fe837f1 -switchingprevention 2"

start pwsh -noexit -executionpolicy bypass -command "& .\reader.ps1 -log 'MultiPoolMiner_\d\d\d\d-\d\d-\d\d\.txt' -sort '^[^_]*_' -quickstart"

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/PowerShell-6.0.1-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

pause

**Comment by UselessGuru** [comment]
@IndiaVenom 

Please stop all mining, clear the logs folder and do the test again. There is far too much information to troubleshoot easily.
