### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#1429]
A few times now I have come back to several of my computers after leaving them for about 16 hours and found the multipoolminer.ps1 script using huge amounts of RAM (>10GB).  This causes the system to be excruciatingly slow because it's using a lot of it's page file.

I suspect there's some variable that's just getting added to over and over on each loop, but before I waste a lot of time digging into it's memory usage to find the problem - are other people having similar issues, or is it just something my computers are doing?

**Comment by titvs** [comment]
@grantemsley on my machine, pwsh.exe is using about 1.3 Gb and Windows Command Processor about 600 Mb. Values from beeing switch on overnight... Seems ok to me...

**Comment by boecht** [comment]
I have seen the same behaviour in the last few days, 4 times while running CcminerSkunk, twice with CcminerTpruvot.
The memory usage grows in a linear fashion and pwsh.exe uses absurd amounts of RAM up until the point where mining stops.

**Comment by boecht** [comment]
It just is happening again on 2 computers no 20 minutes apart. Log is uneventful, but both end on "INFO: Saving hash rates."
One computer crashed with a blue screen (error: memory management), the other is currently still increasing memory usage. Right now it takes 13-14 seconds to go from 1918 MB to 2757 MB for pwsh.exe, then the cycle repeats, gaining about 2.5 MB each cycle. When I kill the miner the cycle speeds up to about 7-8 seconds per cycle.
One was mining phi with CcminerTpruvot, the other is mining skunk with CcminerSkunk.
I git pull at least once a day, so I am on 2.7.2.7. atm.
So my best guess right now is a problem with GetMinerData(), however I have not investigated further.

**Comment by grantemsley** [comment]
@paulpoco Sounds like what I'm seeing.  On my system, it took me a good 5 minutes to simply wake the screens, login, and open task manager via hotkey (since the mouse moved so sluggishly I couldn't aim it).

**Comment by axpatito** [comment]
+1 on this issue. Not enough memory available for pwsh.exe, it stops the whole miner.

**Comment by boecht** [comment]
Happened again earlier today, more than 10 GB for pwsh.exe after "INFO: Saving hash rates."

**Comment by aaronsace** [comment]
Are you sure that you guys are not mixing up the monitoring window and the mining window? 

The window with the date stamps doesn't need to stay open; it's just a log reader.

**Comment by boecht** [comment]
Yes, I never leave the log reader open and clean the log directory automatically before each start.

**Comment by aaronsace** [comment]
@boecht If you haven't got the log window open then something must not be running right. Have you noticed anything wrong? Please can you zip the logs up and drop onto the GitHub post?

**Comment by boecht** [comment]
I'll drop them as soon as it happens again. Today it happened while I was at work so I was only focused on getting it to work again asap.

**Comment by grantemsley** [comment]
@aaronsace It's definitely not the log window (at least for me).  It's the pwsh.exe instance running multipoolminer.ps1

I suspect that either only some miners are triggering it, or some miners do it much worse/faster than others, because I've seen it take a day to happen but I've also had it happen within just a few hours.

I've got a separate script logging memory usage on my system now, waiting for it to happen again so I can compare the logs against the memory usage at the time.

**Comment by Pihrra** [comment]
I have the same issue after a varying amount of time I find my computer completely frozen. It's rather recent because until a couple releases ago I could leave my computer unattended for days at a time without issues. Now sometimes even after just an hour or two it stops working.

**Comment by aaronsace** [comment]
@Pihrra Please can you do a full dump of your logs? 

Zip up the folder then drop it onto the post.

**Comment by Pihrra** [comment]
Here it is. I restarted it today and so far so good. The files from March 11th are from when it happened last.
[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1809260/Logs.zip)

**Comment by paulpoco** [comment]
On 2.7.2.7 no crashes ever yet.

**Comment by Pihrra** [comment]
The problem seems to have gone away on its own for me. It used to be that every time I checked on my miner it had frozen but it hasn't happened in days. Maybe it was related to an API somewhere I have no idea but I didn't change anything on my end and it works for now.

**Comment by boecht** [comment]
Same here. Hasn't crashed once since my last message, where is crashed 5 times in a week.
Super strange.

**Comment by grantemsley** [comment]
Same for me.  I still have my modified version of the script running that tracks it's memory usage, and it hasn't gone above around 375MB since.

I'm guessing that it's only happening when a certain miner is running or on unusual api responses or something.  I'll keep tracking it and see if it happens again.

**Comment by Pihrra** [comment]
It happened again today here are my logs.
[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1845644/Logs.zip)
