### ISSUE TITLE
Mining on wrong server?

### ISSUE THREAD

**Issue by aam583** [MultiPoolMiner/MultiPoolMiner#1430]
I am mining with a 6 card rig. 4 AMD and 2Nvidia. The AMDs are mining ETH just fine. However, the Nvidia has equihash BMiner as most profitable. The mining looks fine, but I get nothing on MiningPoolHub. It looks like the problem might be the server. The program is showing europe.equihash-hub.miningpoolhub.com:17023 while  Mining Pool Hub indicates the correct one is europe.equihash-hub.miningpoolhub.com:20575. Could this be the problem and if it is, how do I fix it? Any help would be appreciated.

**Comment by alucard20724** [comment]
no... it's correct.  17023 is for profit switching for all coins on equihash algo.  20575 is for Zclassic only on equihash, not any other coins on equihash.

**Comment by aam583** [comment]
Ok, I see. Thank you for your reply. What could be the problem then? MiningPoolHub shows me fairly accurately the eth mining, but nothing from equihash. I left it for a few hours and it just looks on that end that there is no equihash mining. I checked zclassic, zcash and zencash. All are on zero. Usually I see the miner active even after a few minutes...

**Comment by aam583** [comment]
I tried another thing in the meantime. I started mining directly with BMiner and this works fine. I see an inaccurate (as it usually is) hashrate in the MPH dashboard after about 5 minutes of mining. I'm not sure what it is, but to me it looks like it's something to do with MPM..

**Comment by lear001** [comment]
https://www.bminer.me/faq/#why-does-bminer-take-so-long-to-get-up-to-speed

there is an answer here

Bminer reports Exponentially Weighted Moving Average of the speed and takes the last couple minutes of the speed into account.

While the number of speed shown by bminer for the first few minutes is smaller, there is no differences on actual speed. The reported speed will converge to the real speed in several minutes.

**Comment by aam583** [comment]
The problem isn't a lower reported speed, but no speed at all when going with MPM. I changed the worker name and for eth, it appeared after a few minutes. For equihash it still hasn't shown up. It just looks like the shares from Bminer aren't seen on MPM. If I just use the standalone Bminer however, I see the shares after a few minutes - at low speed as you said

**Comment by UselessGuru** [comment]
@aam583 

If you provide some logs we might assist you better ;-)

**Comment by aam583** [comment]
Sure, here is the latest log.

[BMiner-1880_2018-03-10_05-34-06.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1799297/BMiner-1880_2018-03-10_05-34-06.txt)

I left it run overnight and nothing changed. ETH mining shows up, but no coin from Bminer

**Comment by aam583** [comment]
I can also provide my API to MPHStats if that would help identify the problem

**Comment by UselessGuru** [comment]
@aam583 

Please provide MPM log too (MultiPoolMiner_2018-03-10.txt). In that we can see the bminer command line.
