### ISSUE TITLE
Mining with only AMD Cards

### ISSUE THREAD

**Issue by aam583** [MultiPoolMiner/MultiPoolMiner#1433]
I have posted Issue 1430, and in the meantime I am trying to find a workaround, but having difficulties with it.

In a rig with 6 cards, 4 AMD and 2 Nvidia, I want to mine with my AMD cards with MPM and use Bminer separately to mine with the Nvidias. The problem is that when I remove Nvidia from miner type the miner gets rid of Nvidia, but not of {AMD, Nvidia} . So, I still end up with all 6 cards using Prospector or Eminer in MPM.

I tried deleting the stats for those 2 algos, but they start bench-marking again anyway.

**Comment by UselessGuru** [comment]
For prospector try [these prospector files](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1656320/ProspectorMiners.zip) (replace the existing one) as discussed in https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1086.
Please report back here. Thank you!

Eminer unfortunately cannot be limited to use selected GPUs (e.g. only AMD or NVIDIA cards). Note: This is miner binary limitation, not MPM cannot work around this
-> you need to exclude it from start.bat '-ExcludeMinerName Eminer'

**Comment by aam583** [comment]
Thank you. I excluded both miners with '-ExcludeMinerName'. Works great now only mining with the AMD cards

**Comment by UselessGuru** [comment]
@aam583 

Would you mind testing the prospector files?

**Comment by aam583** [comment]
Prospector wasn't very efficient for me. I was getting just 10% better with 6 cards (4amd+2nvidia) as opposed to Claymorer with only 4 amds. Still, because of that 10%, MPM was trying to use prospector first as it was a {amd, nvidia} miner.
