### ISSUE TITLE
How does Donate work? Love MPM, want to donate, but my connection is unstable. Does it reset¿

### ISSUE THREAD

**Issue by xoslin** [MultiPoolMiner/MultiPoolMiner#1436]
Hello there. Thanks for your amazing job with this program, it is my favourite mining program nowadays and I've been using it for weeks now on my desktop computer. I live in a mountainous very rainy place where my 6MB ADSL connection drops easily when the weather is bad, which isn't uncommon..

I want to donate and set it to 10 minutes out of fear that my connection drops and the counter resets again, so I again mine 10 minutes for the program, then again another 10 minutes. How does it work? Documentation page isn't available now.

Is there a way to unhide the miner's window? Sometimes I am not sure whether a miner is working or not. Best regards!

**Comment by UselessGuru** [comment]
> I want to donate and set it to 10 minutes out of fear that my connection drops and the counter resets again

MPM will mine to the donation address for a minimum of 10 (or minutes depending on -donate parameter) per day. Donation will start donation 1 hour after MPM started.

Connection drops do not reset the donation counter. Restarting MPM, however, does.

**Comment by UselessGuru** [comment]
> Is there a way to unhide the miner's window? Sometimes I am not sure whether a miner is working or not. Best regards!

No, [read here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1293)
