### ISSUE TITLE
Suggestion: Command for all algos and/or all pools

### ISSUE THREAD

**Issue by iwtym** [MultiPoolMiner/MultiPoolMiner#1437]
Hi, 

This is a suggestion to have one command to enable all algos (like a wildcard?) and all pools (also a wildcard?). I operate a rather large farm and could use this functionality. 

Love the program, keep up the good work.

Thanks!

**Comment by boecht** [comment]
Just omit the algo and pool arguments altogether. You can still use the exclusion arguments.

**Comment by iwtym** [comment]
This owrked. THank you
