### ISSUE TITLE
ethash woes

### ISSUE THREAD

**Issue by romulus2k4** [MultiPoolMiner/MultiPoolMiner#1440]
Long story short, if I use a .bat file to mine from the Ethash-Claymore directory, it sets the DAG to 34, which results in a higher hashrate.

The first time MPM runs the miner (like benchmarking) the miner sets the DAG to 34 sometimes, so the benchmark records the hashrate at 22 MH/s, but there will come a time when it'll start setting the DAG incorrectly to 70, and eventually MPM will deem the miner as "failed" as the increased DAG creates a discrepancy in the recorded hashrate vs the current hashrate.

Edit: This behavior isn't just limited to ethash2GB, but also is present with ethash itself. Tested using a RX 580.

What can be the fix for this?

**Comment by UselessGuru** [comment]
> The first time MPM runs the miner (like benchmarking) the miner sets the DAG to 34 sometimes, so the benchmark records the hashrate at 22 MH/s, but there will come a time when it'll start setting the DAG incorrectly to 70,

MPM does not set an DAG values. Nowhere.

**Comment by romulus2k4** [comment]
Yes, I am well aware that MPM doesn't set the DAG.

But this behavior is consistent. When I use a .bat file to mine from the mining executable's directory, the DAG is set to 34.

And when MPM enters this state, the miner sets it to 70, despite the parameters that are being passed being the exact same. And this behavior is reproducible, and can impact earnings.

Altering the miner's configuration within the ClaymoreAMD.txt file doesn't yield any difference.

**Comment by UselessGuru** [comment]
> And when MPM enters this state, the miner sets it to 70, despite the parameters that are being passed being the exact same. And this behavior is reproducible, and can impact earnings.

How do you verify the DAG value?

> And when MPM enters this state, the miner sets it to 70, despite the parameters that are being passed being the exact same. And this behavior is reproducible, and can impact earnings.

Please provide config details.

**Comment by romulus2k4** [comment]
> How do you verify the DAG value?

I copy pasted the parameters that are being passed by MPM's Powershell Window, and copy pasted it on to command prompt, and when the miner starts, it shows that it's setting the DAG to 70, which causes the hashrate to decline from 22.3 MH/s to around 17 MH/s. Once this behavior is triggered within MPM, MPM will eventually mark the miner as failed, as the hashrate has fallen significantly than what it has recorded, initially.

However, if I use a .batch file to do the exact same thing from the miner's executable directory, I can see the DAG being set to 34, and the hashrate stays consistently at 22.3 MH/s, as it should.

> Please provide config details.


[ClaymoreAmd.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1800319/ClaymoreAmd.txt)

This is the config file I am using.

`EthDcrMiner64.exe -r -1 -mport -13333 -epool asia.ethash-hub.miningpoolhub.com:20565 -ewal user.wroker -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 1 -etha 1 -asm 2 -estale 0`

This is the batch file I am using. They are passing the same parameters while mining. But still, there is a 5 MH/s discrepancy between the two, because of the DAG being set differently.

**Comment by UselessGuru** [comment]
There is not much MPM can do if the same command line parameters lead to different results. So you might better support at the developers forum. I cannot test myself because I only own Nvidia HW that does not show the reported performance drop.

Maybe you can find a parameter to set the desired DAG size:

-allcoins Specify "-allcoins 1" to be able to mine Ethereum forks, in this mode miner will use some default pools for devfee Ethereum mining. 
   Note that if devfee mining pools will stop, entire mining will be stopped too. 
   Miner has to use two DAGs in this mode - one for Ethereum and one for Ethereum fork, it can cause crashes because DAGs have different sizes. 
   Therefore for this mode it is recommended to specify current Ethereum epoch (or a bit larger value), 
   for example, "-allcoins 47" means that miner will expect DAG size for epoch #47 and will allocate appropriate GPU buffer at starting, instead of reallocating bigger GPU buffer (may crash) when it starts devfee mining.

**Comment by romulus2k4** [comment]
Okay, figured the issue out. The DAG size has something to do with the currency MPM is mining, a la the port it's connecting to changing. 

But still, if while benching, MPM records hashrate from a currency/fork that employs a lower DAG, and later mines a currency/fork with a higher DAG, instead of updating the hashrate, it deems it as a failure, resulting in exclusion.

I have tried changing the "-allcoins" value to no effect. It seems it's the pool that sets it.

**Comment by UselessGuru** [comment]
So when benchmarking the miner reports a higher than what you get in 'normal' operation.

This will cause 2 issues:
MPM will chose the miner because of over optimistic hash rate
MPM kicks the miner

Workarouns:
Modify the hash rate in the benchmark file.

**Comment by romulus2k4** [comment]
What's happening is that, while benchmarking, MPM may choose an ethereum fork that has a lower DAG size, resulting in higher hashrate being recorded.

Particularly, this ethereum fork which is tied to this address `asia.ethash-hub.miningpoolhub.com:20565`

Then once that fork being no longer profitable, MPM will eventually switch to something else that sets the DAG to 70 and thus the lower hashrate.

**Comment by UselessGuru** [comment]
@romulus2k4 

For a test (unsupported) you can use the attached miner (rename to ps1 and replace original file)
This allows disabling one (or even a set of) algorithm(s) on the pool. This requires manual modification of Config.txt:

                  "MiningPoolHub":  {
                                        "User":  "$UserName",
                                        "Worker":  "$WorkerName",
                                        "DisabledAlgorithms":  ["ethash2gb", "another_disabled_algo"],
                                        "API_ID":  0,
                                        "API_Key":  ""
                                    },

[MiningPoolHub.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1800391/MiningPoolHub.txt)

**Comment by angelics** [comment]
this is the proper, much more cleaner way to disable coins / algos
#1289 
mph does not auto exchange maxcoin, so mining keccak/maxcoin should be disable for those without yobit acc.
to disable coins in miningpoolhubcoins, use DisableCoins: , and `Where {$DisabledCoins -notcontains $_.coin_name}`
@UselessGuru theres typo in ur upload -inotcontains -> -notcontains

**Comment by UselessGuru** [comment]
@angelics

> to disable coins in miningpoolhubcoins, use DisableCoins: , and Where {$DisabledCoins -notcontains $_.coin_name}

Cool idea! I will keep this in mind and might be implemented in all pools in the future (if aaronsace agrees).

For now it is implemented in the attached file. 
[MiningPoolHub.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1809998/MiningPoolHub.txt)

To use edit config.txt:

```
              "MiningPoolHub":  {
                                    "User":  "$UserName",
                                    "Worker":  "$WorkerName",
                                    "DisabledAlgorithms":  ["ethash2gb", "another_disabled_algo"],
                                    "DisabledCoins":  ["disabled_Coin", "another_disabled_coin"],
                                    "API_ID":  0,
                                    "API_Key":  ""
                                },
```

> theres typo in ur upload -inotcontains -> -notcontains

Should be OK. the i in icontains stands for case insensitive.

**Comment by angelics** [comment]
thanks for pointing that out. learning new stuff again
