### ISSUE TITLE
WARNING: The software (MultiPoolMiner) is out of date; there is an updated version available

### ISSUE THREAD

**Issue by tudoram** [MultiPoolMiner/MultiPoolMiner#1441]
Hi,
Yesterday I have installed new MultiPoolMinerV2.7.2.7.
I copied only the stats from the previous versions and start.bat. I also re-downloaded excavator 
When I run the software miners were downloaded properly.
I still get this message.
WARNING: The software (MultiPoolMiner) is out of date; there is an updated version available at https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.2.7/MultiPoolMinerV2.7.2.7.
Mining seems to not be affected.
Is it something to be worried?
Thanks

**Comment by romulus2k4** [comment]
The version you downloaded was slightly updated, therefore the warning message.
