### ISSUE TITLE
Help with start.bat

### ISSUE THREAD

**Issue by kevinpat5** [MultiPoolMiner/MultiPoolMiner#1442]
Hi all and thank you for your effords. I'd appreciate any help setting up my start.bat, because i'm stuck with Nicehash's Neoscript for days.
I have 2x1070ti and i want to use MiningPoolHub+Nicehash. I excluded a few miners i noticed causing problems. Do i have way too many algos? Are there any essentially no-more-used among them? Is there anything else i can weed out? My batch file is as follows:

`set "command=& .\multipoolminer.ps1 -wallet MY_ADDRESS -username MY_USERNAME -workername MPM -region europe -currency eur -type nvidia -poolname miningpoolhub, miningpoolhubcoins, nicehash -algorithm blake2s, cryptonight, decrednicehash, ethash, equihash, groestl, keccak, lbry, lyra2re2, lyra2z, neoscrypt, pascal, sib, skunk -donate 24 -watchdog -minerstatusurl https://multipoolminer.io/monitor/miner.php -minerstatuskey MY_KEY -switchingprevention 2 -ExcludeMinerName NsgminerNvidia, XmrigNvidia, PalginNvidia, Prospector, BMiner, EMiner -ExcludePoolName AHashPool, Blockmunch, Hashrefinery, YiiMP, Zpool"`

**Comment by UselessGuru** [comment]
What is your exact problem? Your config looks fine.

**Comment by kevinpat5** [comment]
It never switches. It is stuck to Nicehash's Neoscrypt for days. I know this is potentially the most profitable, but i wonder wether my config is too cluttered and can be cleaned up a bit.

**Comment by UselessGuru** [comment]
You might reset your stats. See readme
