### ISSUE TITLE
Zergpool.ps1 - divisor for neoscrypt correct?

### ISSUE THREAD

**Issue by chrmat** [MultiPoolMiner/MultiPoolMiner#1444]
The profitability for neoscrypt on Zergpool seems to be three digits off. Is the divisor in Zergpool.ps1 correct?
"neoscrypt" {$Divisor *= 1000}

**Comment by UselessGuru** [comment]
Are you using the latest zergpool files from [here](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435)?
[ZergPool.ps1](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435/files#diff-ac3a482abd06f94d18cbd514a7d523bd)
[ZergPoolCoins.ps1](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435/files#diff-25c5a8fc5e89d019e5c970cab6278908)

Please post logs.
I try to test myself, but currently I am not getting any Neoscrypt profitability information.

**Comment by alucard20724** [comment]
it seems like a lot of values for zergpool is off compared to other pools.  Skein for instant.  with version 2.7.2.7, skein has been the top aglo for my 1060/1070/1080 cards for the last day, but all the other pools list skein at the bottom.  plus it would appear that the values used to profit estimates are the "current estimate" rather than the actual values.

**Comment by alucard20724** [comment]
maybe skein is profitable.. jumped to the top with ahashpool when zergpool was removed

**Comment by UselessGuru** [comment]
@alucard20724 

Please post screenshots. TIA

**Comment by chrmat** [comment]
Hi, 
The divisor for phi is also wrong in Zergpool.ps1 included in the MultiPoolMinerV2.7.2.7 release.
The line  "phi" {$Divisor *= 1000} should be deleted.

**Comment by UselessGuru** [comment]
> The line "phi" {$Divisor *= 1000} should be deleted.

Please provide screen shots - thank you!

**Comment by UselessGuru** [comment]
> The line "phi" {$Divisor *= 1000} should be deleted.
> "neoscrypt" {$Divisor *= 1000}" which I think is wrong. 

Managed to test it myself. [Deleted here,](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1461) waiting for commit.
