### ISSUE TITLE
Blazepool does not display miner names

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1446]
as the title says.  Blazepool does not display the miner names..i.e. ID of the miner.

**Comment by UselessGuru** [comment]
Pleas post a screenshot to better illustrate - thank you!

**Comment by alucard20724** [comment]
![capture](https://user-images.githubusercontent.com/28934670/37270925-b5f654c4-259e-11e8-98b8-922f72c5849f.JPG)

**Comment by alucard20724** [comment]
![capture](https://user-images.githubusercontent.com/28934670/37270994-0330a820-259f-11e8-83fe-ba41c0e16ab9.JPG)

**Comment by UselessGuru** [comment]
MPM is using the correct parameters, and payout is working:

ccminer.exe -a skunk -o stratum+tcp://skunk.mine.blazepool.com:8433 -u **1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb** -p multipoolminer,**c=BTC**

You might better ask the pool operator.

**Comment by UselessGuru** [comment]
I think I see the issue. BlazePool requires ID=[WorkerName] to show the rig name.
Unfortunately this is not clearly documented anywhere :-(

Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1447

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1447
