### ISSUE TITLE
./MPM/Bin subfolders not named properly after download and extract

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#1448]
I just downloaded the latest version of MPM and noticed it does unzip in the Bin folder but does not rename most of them. I do not remember it doing this before. As a result MPM throws a message it cannot find the miner in question. There were a couple of bad apples(miners) before that needed some human interaction but the rest was fully automated. I know how to fix this.  Maybe its a new way of doing the extraction and this is a nonissue just posting FYI...
<img width="307" alt="screen shot 2018-03-12 at 12 22 29 pm" src="https://user-images.githubusercontent.com/28104701/37278511-a016e18a-25f0-11e8-874c-2ee4f7ecdf71.png">

**Comment by grantemsley** [comment]
Sometimes antivirus causes problems like that.  Make sure that windows defender is completely disabled and try again.

**Comment by mkirov0** [comment]
It used to work with no issues, but some windows update may have turned on Defender.. I already fixed it, but will make sure to look at defender first next time i decide to do a full refresh of MPM. Thanks for the info.
