### ISSUE TITLE
MPM closes separate CPU mining window

### ISSUE THREAD

**Issue by opelgtman** [MultiPoolMiner/MultiPoolMiner#1449]
I use MPM with MPH.  I also mine turtle coin with my cpu.  If I use MPM and try to cpu mine another coin, MPM will close out the cpu mining.  It happens on both of my machines.  I can use nicehash and the cpu mining will never close out.

**Comment by grantemsley** [comment]
What specific miner program to do you use for turtle coin?

**Comment by UselessGuru** [comment]
@opelgtman 

Rename the non-MPM CPU miner binary to a different name than any miner binary in the MPM\Bin directory

This has problably the same cause as [this](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1427)

**Comment by opelgtman** [comment]
Renaming the exe fixed my issue.

**Comment by opelgtman** [comment]
I use xmr stak for turtle.
