### ISSUE TITLE
Typo in miners name in the known issues section of the readme

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1450]
> There are known issues with the following miners not submitting shares or show higher hashrate than what they actually do:
> 
> - CCminerLyraZ
> - CCminerLyra2RE2

It must be `CcminerLyra2z`.

**Comment by UselessGuru** [comment]
Thanks. 
Fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435/files#diff-26fd799ea07494916e9da9b91b2aac64
