### ISSUE TITLE
Monitor - Cleaning Up Old Miners in Monitor

### ISSUE THREAD

**Issue by JimKnightster** [MultiPoolMiner/MultiPoolMiner#1452]
Is there a way to clean up old workers in the monitor web site?  I made a mistake the last time I upgraded and typo'ed my worker name.  I corrected it after a few minutes when I noticed it, but the old worker is still showing up (red and offline) but its been there for about 2 days now.  Will it eventually disappear?

**Comment by alucard20724** [comment]
they seem to disappear after 7 days of inactivity

**Comment by JimKnightster** [comment]
that works thanks.

**Comment by mill99** [comment]
> they seem to disappear after 7 days of inactivity

ty
