### ISSUE TITLE
multipoolminer.io incorrectly summing inactive algo with active algo

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1454]
it's great that you have multipoolminer.io as an enhancement, but there's an error with mpm.io summing up btc/day of active and inactive algo giving erroneous results.
![capture](https://user-images.githubusercontent.com/28934670/37378778-ac7f6906-26fe-11e8-8fa4-bca9d299be76.JPG)

**Comment by JimKnightster** [comment]
i have seen this as well, have also see it with 5-10 0.000 BTC/Day Algo's stuck in it.  I typically have to kill everything and restart MPM when it happens.

**Comment by grantemsley** [comment]
Can you post the logs from the system at that time?

Looks like MPM thinks both miners are running...and maybe they both are.  It doesn't report miners that aren't running, so I'd like to see the logs to figure out what's going on.

**Comment by JimKnightster** [comment]
Sorry just now saw this,  I have the issue now, but showing 0.00 for the 2 that are not running, I checked taskmanager and they are not running (they also both show as failed in the MPM screen.  

![image](https://user-images.githubusercontent.com/13444381/38062598-d097deac-32c2-11e8-93c8-ed7f0f7a6130.png)

![image](https://user-images.githubusercontent.com/13444381/38062618-ee3fcfbe-32c2-11e8-8e30-f75800d72ff5.png)

logs attached, might not be totally accurate as the IO site is reporting 0.00 btc/day in the column but might give you a clue.  

[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1858196/Logs.zip)

**Comment by JimKnightster** [comment]
A more accurate depiction 
all 3 failed command lines, are listed:
![image](https://user-images.githubusercontent.com/13444381/38399926-523c2a90-391b-11e8-9b3e-a7295bb91315.png)
![image](https://user-images.githubusercontent.com/13444381/38399946-6fdb9270-391b-11e8-86d4-40c0974c4f1a.png)
Totals are 0 but sometimes the BTC/Day is not 0 and gets added

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1594/files
