### ISSUE TITLE
New xmr miner for AMD

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#1455]
link here
https://bitcointalk.org/index.php?topic=2962578.0

reading the first page... it might be faster than claymore's cryptonight miner for not vega cards

**Comment by UselessGuru** [comment]
[re-branded this so its now called SRBMiner](https://bitcointalk.org/index.php?topic=2962578.msg32748785#msg32748785)

https://bitcointalk.org/index.php?topic=3167363

I am working on an implementation for it now.
