### ISSUE TITLE
MultiPoolMiner freezes

### ISSUE THREAD

**Issue by kaZan18** [MultiPoolMiner/MultiPoolMiner#1459]
Hey! :)

I had this problem a few times now. MPM runs pretty nice, but sometimes it freezes. My Gpu`s keep running on full speed, but the powershell window doesnt update. Sometimes the past log gets loaded when pressing enter, but most times, is see it some hours later. Miner also doesnt switch then. That problem happen with all miners im using(phoenixNvidia,ccklaust,cctrpuvot,dstm,bminer). First log miner stopped @ 20.20 -> 20.38 is after manual restart! Meanwhile CcminerTrpuvot log says, it was mining all the time?! What is causing that issue? By the way... thank you :)

[MultiPoolMiner_2018-03-14 aaron.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1812873/MultiPoolMiner_2018-03-14.aaron.txt)

[CcminerTpruvot-4068_2018-03-14_20-11-39.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1812874/CcminerTpruvot-4068_2018-03-14_20-11-39.txt)

**Comment by UselessGuru** [comment]
How about this one? Please close if this applies - Thank you.

See AdrianAcala's answer.

**Comment by kaZan18** [comment]
Allright, ill give it a try. You get a feedback in a few days!

Thank you :)

**Comment by kaZan18** [comment]
Hello again,

So far... works good!!! The Powershell window checked "Quick Edit Mode" by itself one time. I had one freeze then. After unchecking it again it runs without freezing!
Now, from time to time, miner says:

2018-03-17 12:11:29 WARNING: The software (MultiPoolMiner) failed to update. 
2018-03-17 12:11:29 WARNING: The software (PowerShell) failed to update. 

Is there any correlation between the powershell "unchecks", and the displayed message?

Best regads

Daniel

**Comment by kaZan18** [comment]
Sometimes this happens, wasnt before unchecking, but miner keeps running good! :)

![screenshot 8](https://user-images.githubusercontent.com/34724621/37557808-5fab726e-2a0a-11e8-87eb-cab6126e1dd8.png)

**Comment by UselessGuru** [comment]
> Is there any correlation between the powershell "unchecks", and the displayed message?

No, and they are just informal. Nothing to worry about.
