### ISSUE TITLE
Multipoolminer.ps1 error

### ISSUE THREAD

**Issue by ailocha** [MultiPoolMiner/MultiPoolMiner#1463]
[2018-03-15_08-15-46.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1815306/2018-03-15_08-15-46.txt)

Any Ideas?

**Comment by UselessGuru** [comment]
There is a problem with the OpenGL libraries. Also [see here.](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/890)
You need to re-install your graphics driver (full install)

**Comment by ailocha** [comment]
fixed.  ty
