### ISSUE TITLE
New KlausT/ccminer version 8.21

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1465]
[8.21](https://github.com/KlausT/ccminer/releases)

> add option --cuda-schedule
> add option --logfile
> make ccminer compilable under OSX
> Neoscrypt: detect P104-100 and Tesla P100/V100
> Lyra2v2: fix verification bug (Linux)
> fix for intensities between 8 and 9

There is a CUDA 8 and CUDA 9.1 version.

**Comment by UselessGuru** [comment]
Thank you. [Pull request is pending](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1466)
