### ISSUE TITLE
NgsminerAmd.txt has a bug

### ISSUE THREAD

**Issue by scolarita13** [MultiPoolMiner/MultiPoolMiner#1469]
I think is something wrong with the the script which builds the command line.
The miner fails to connect to the pool.

Here is the log.
Thanks,

[NsgminerAmd-14028_2018-03-16_23-10-14.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1821231/NsgminerAmd-14028_2018-03-16_23-10-14.txt)

Thanks

**Comment by UselessGuru** [comment]
This is the wrong log, it does not show the effective miner command line.
Please upload MultiPoolMiner-2018-03-16.txt

**Comment by scolarita13** [comment]
MultiPoolMiner-2018-03-16.txt is huge and github does not accept it. Also this error provokes an infinite loop and freezes the rig. I had to shutdown the rig from power switch and restart.
I removed the nsgminer for the moment.
I copied MultiPoolMiner-2018-03-16.txt a snapshot with the command line in and how the error repeats, 
[error.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1821514/error.txt)

**Comment by UselessGuru** [comment]
There appears to be a compatibility issue. 
The command line parameters are correct, tested on zpool:
nsgminer.exe --api-port 14028 --api-listen --neoscrypt -o stratum+tcp://neoscrypt.mine.zpool.ca:4233 -u 3NzHpTkvmH9RFCaAfVxdgkvupgPJF4iGBh.scolaritaMiner -p x --gpu-threads 1 --worksize 64 --intensity 15 --gpu-platform 1

You should report this issue with NiceHash and the miner developer. MPM cannot fix this issue.

Workaround: Do not use this miner (-excludeminername nsgmner) or do not mine on Nicehash (-expludepoolname NiceHash)
