### ISSUE TITLE
Miners Logs Issues

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#1474]
Hi guys,
Ive been testing the latest master and ive noticed errors in the logs of some miners:

```
BMiner.exe : [INFO] [2018-03-17T20:49:22Z] Bminer: When Crypto-mining Made Fast (v5.5.0-aba7617) 
At line:1 char:99
+ ... lowNormal'; & 'C:\MPM_NR\Bin\NVIDIA-BMiner\BMiner.exe' -api 127.0.0.1 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([INFO] [2018-03...5.5.0-aba7617) :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Altough the error pops up, mining doesnt seem to be affected.

Affected miners with the same error tipe (NativeCommandError):

Bminer
CcminerKlaust
CcminerSp
EthminerNvidia
NsgminerNvidia

Also at startup, i've got these:

2018-03-17 11:23:40 WARNING: The software (MultiPoolMiner) failed to update. 
2018-03-17 11:23:40 WARNING: The software (PowerShell) failed to update. 

I can post the main logs if it helps.

Another question: to mine on ZergPool i need to download the two ps1 files from UselessGuru and edit the config.txt? they arent on the last master.

**Comment by UselessGuru** [comment]
@aaronsace 

Could this be linked to https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1299?
