### ISSUE TITLE
MKXMiner missing

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1475]
Apparently the file referenced for it https://filebin.net/vvgg69m5dbaf5suu/mkxminer301.zip
is missing.

**Comment by UselessGuru** [comment]
Thank you for reporting. The old link is no longer valid.

Unfortunately the author does no longer provide a direct download link that MPM can use. 

Workaround: A manual DL link has been provided [here](https://bitcointalk.org/index.php?topic=2360168.msg32529404#msg32529404):
https://ufile.io/494r3

**Comment by Kettoch** [comment]
Ok, not sure how to close an issue but thank you for the link,
