### ISSUE TITLE
Zergpool server update

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#1478]
I just noticed this so I'm posting FYI
<img width="1226" alt="screen shot 2018-03-18 at 8 24 58 pm" src="https://user-images.githubusercontent.com/28104701/37569426-ac988554-2aea-11e8-8e38-108329a50b1b.png">

**Comment by UselessGuru** [comment]
> Thanks.

The latest miner files containing all fixes are in this PR: #1435
Also see the enhanced documentation.

These are the two miner definition files:
https://raw.githubusercontent.com/MultiPoolMiner/MultiPoolMiner/a455a6318b7470294b58abb54aaa8271e5f92ed7/Pools/ZergPool.ps1
https://raw.githubusercontent.com/MultiPoolMiner/MultiPoolMiner/a455a6318b7470294b58abb54aaa8271e5f92ed7/Pools/ZergPoolCoins.ps1
There is no need to edit config.txt unless you want to change payout to another currency than BTC or if you want to limit the number of coins or algorithms.

**Comment by UselessGuru** [comment]
Just to keep it open to avoid further duplicates....

**Comment by robl45** [comment]
Sorry, maybe I'm nuts, but I fail to see how this is adding the algorithm to the front of mine.zergpool.com as it doesn't seem any different than the file I'm currently running.
