### ISSUE TITLE
V2.7.2.7 on AMD system constantly crashing reader.

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1479]
running the command from the start.bat by itself

pwsh -noexit -executionpolicy bypass -command "& .\reader.ps1 -log 'MultiPoolMiner_\d\d\d\d-\d\d-\d\d\.txt' -sort '^[^_]*_' -quickstart"

Causes system to crash.

**Comment by grantemsley** [comment]
What exactly do you mean by crash?  Completely locks up?  Blue screen of death?  Some sort of error message?

**Comment by paulpoco** [comment]
Running 24x7 AMD Ryzen 7 1700 just fine.

**Comment by Kettoch** [comment]
I did a repair on powershell 6.0.2 and all of my ps woes ended.
