### ISSUE TITLE
Could you add this pool to your pool list?

### ISSUE THREAD

**Issue by PontiacGTX** [MultiPoolMiner/MultiPoolMiner#1481]
I have found  pool this pool which have many different for NeoScrypt http://neopool.net/

**Comment by UselessGuru** [comment]
I had a quick look at the pool. It is basically a clone of BlockMunch (no auto conversion to BTC). So it's quite easy to build on this (copy blockmunch.ps1 to new file name, edit API url, possibly amend divisors. done).
However the number of active miners is very low (just 15 @ the time i checked. There is little sense to mine such a pool - it can take ages until you get paid.
As it stands now there is little point in making the effort to support it officially. Sorry - Our resources are limited :-)
