### ISSUE TITLE
Suggestion: Do not force autoupdate

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1482]
Just now MPM tried to update me automatically. I don't want to be updated automatically especially since certain files need changes such as to stop watchdog from cutting algorithms and Xevan algorithm to work on my cards.  

Further, if I"m running the master version, why is it telling me its out of date?

I don't have any logs if needed as it got all crazy in the log window with huge font after I stopped it from updating and I had to remove the logs to get the font back to normal.

**Comment by UselessGuru** [comment]
>  I don't want to be updated automatically especially since certain files need changes

Good idea, Create a pull request: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1483

Some customization stuff might be preserved if we add some intelligence into the pool and miner files as [I propose here](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1237). But this not going to be implemented in the very near future.
