### ISSUE TITLE
x16r miner for Nvidia not found and suggestion for solution

### ISSUE THREAD

**Issue by Falacio** [MultiPoolMiner/MultiPoolMiner#1485]
I've just installed last master version of MPM with last updated "Coins" branch.

The first thing that I've realized is an error when trying to benchmark x16r algo:

https://gyazo.com/e4ff07593f16980e6a6ecda4d72985d3

I had a look at miner readme and couldn't find x16r as valid algo. But it was the only miner the program tried during benchmark. I haven't found x16r algo as compatible in any other readme's available for the rest of miners I have in /bin folder, either. I'm mining with Nvidia only.

I've found this fork of tpruvot ccminer, but I haven't tried it yet:

https://github.com/todd1251/ccminer-x16r

Or maybe another miner from what we have now can be used, rather than KlausT ccminer, to mine x16r.

**Comment by UselessGuru** [comment]
> The first thing that I've realized is an error when trying to benchmark x16r algo:

This is fixed here: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1466

CcminerTpruvot 2.2.5 supports x16r: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1392

Keep in mind that MPM's watchdog do not get along well with the new x16r algorithm: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1412

**Comment by Falacio** [comment]
Oh, I see. Thanks for answering. I've also learnt to use search function :) 
I'm going to try both miners, and see how watchdog responds.
