### ISSUE TITLE
CcminerKlaust Freeze

### ISSUE THREAD

**Issue by kaZan18** [MultiPoolMiner/MultiPoolMiner#1486]
Hey there,

im using klaust for neoscrypt only, the log looks strange, and i had a freeze today @ 13:43, after a m8 restarted the miner @ 15:26 everything works fine. I dont know if the gpu`s where working meanwhile, because i wasnt @ home. I have problems with klaust only! :(. Last time i had freezes you told me to uncheck "Quick Edit Mode" and "Insert Mode". Thank you!

[MultiPoolMiner_2018-03-21.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1834853/MultiPoolMiner_2018-03-21.txt)

Best regards

Daniel

**Comment by UselessGuru** [comment]
Please define freeze properly.

- Does mining continue (are the GPUs busy)?
- Do some logs get updated?

**Comment by kaZan18** [comment]
My m8 didnt go for it, so i dont know if they were busy or not... :/

Thats the last log, it stopped @ 13:56

[CcminerKlaust-4068_2018-03-21_13-32-36.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1835184/CcminerKlaust-4068_2018-03-21_13-32-36.txt)

**Comment by UselessGuru** [comment]
> My m8 didnt go for it, so i dont know if they were busy or not... :/

???

You need to check if the miner is still mining (check at the pool), or if all MPM processes are dead.

Your log looks strange. Make sure you are running the [latest version](https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip)

**Comment by UselessGuru** [comment]
> Just to make sure, can i just replace the old files with the new ones?

Yes
