### ISSUE TITLE
Blazepool auto switch issues.

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#1490]
It seems as though whenever Blazepool is enabled it becomes fairly dominate to what pool is mined to (even though the profit doesn't seem dominate).  I also notice that MPM at that point sticks almost exclusively to x17 when enabled, even though its not generally the most profitable, though stable?

API issue?  Blazepool seems to be a different style of pool, maybe therein lies the problem.

**Comment by UselessGuru** [comment]
> it becomes fairly dominate

Remove all your profit stats.

> API issue? Blazepool seems to be a different style of pool, maybe therein lies the problem.

Nope. Make sure you use the [latest blaze pool file](https://raw.githubusercontent.com/MultiPoolMiner/MultiPoolMiner/a455a6318b7470294b58abb54aaa8271e5f92ed7/Pools/BlazePool.ps1) from this PR: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435 which contains updates to other pool files too.

**Comment by mtbor** [comment]
I don't think this is an issue at all.  I reset profit and updated the pool files.  Blazepool probably is reporting more profitable values, though I haven't disabled and reenabled it to compare values.  

The behavior is different than what I expected because one algorithm is significantly more stable than others, which hasn't happened much in the past.

This brings me to another thought, MPM seems to rank miners over time, and seems to be fairly slow to adapt.  In prior releases MPM would sometimes "snipe" high profit potentials by getting to them quickly (which I'm guessing has more to do with slow difficulty adaptation and less to do with exchange rate), though sometimes it might end up on the losing side of the leap.

**Could there be a setting to allow much faster sorting based on profit?**  I've moved switchingprevention to 1 or 0 without any results, so that's not it.   If you want this moved to its own issue thread, let me know.

**Comment by UselessGuru** [comment]
> Could there be a setting to allow much faster sorting based on profit? 

No, the curve is fixed. Just let MPM find its way. I will get more accurate better with ever loop.

> I've moved switchingprevention to 1 or 0 without any results, so that's not it. If you want this moved to its own issue thread, let me know.

Setting switchingprevention to 0 will force MPM to jump to the 'fastest' algo, which is NOT desirable as documented elsewhere.

**Comment by mtbor** [comment]
That's not how it's working on my end...  Switching prevention 0 and it's still mining x17 on Blazepool at $3 a day when probably 5 other miners and algorithms are $6-8 per day.

**Comment by aaronsace** [comment]
@mtbor Just upload your logs and tell us the section of the log that you want us to articulate.

**Comment by mtbor** [comment]
I downloaded the master and migrated some things over.  I'm thinking something got out of whack at some point and the miner stopped functioning as intended.  Could be that I am using Alexis78 and Palgin miners for x17 and had not updated the bottom portion of the miner script.
