### ISSUE TITLE
Suggestion to add ethash3gb param

### ISSUE THREAD

**Issue by beeyev** [MultiPoolMiner/MultiPoolMiner#1497]
Since 3 gb video cards can not mine Ethereum anymore, i think -ethash**3**gb would be useful.

**Comment by UselessGuru** [comment]
> -ethash3gb would be useful

You can still mine. It depends on the miner. e.g. with [ClaymoreDual with the -eres 0 switch](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1484)
But I agree we have to do something about it. Time will catch us.

The 3gb switch as such is not so hard to implement, but there are some other issues to resolve:
Assume you have five cards with the X GB RAM on board ()3GB cards marked bold:
deviceID0=11GB; deviceID1=8GB; **deviceID2=3GB**; deviceID3=8GB; **deviceID4=3GB**

- Custom miner commands, e.g. for intensities ' -i 22,20,**16**,18,**16**', must be converted -> ' -i 22,20,18'
- Each miner uses a different logic to select devices, some start counting deviceIDs from 0, other from 1, some require he device list separated with commas, aother with spaces....
- Benchmark files must be cleared, e.g. if you lose 2cards (3GB) out of five cards to mine -> hasrate drops -> watchdog

**Comment by UselessGuru** [comment]
Code for ClaymoreDual is 3GB algo ready.
Got implemented and commited in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1658
