### ISSUE TITLE
Started getting random error when running MPM

### ISSUE THREAD

**Issue by izzledude** [MultiPoolMiner/MultiPoolMiner#1500]
I started getting a random error on the main window shows in red after MPM has been running it will show up then seems to cycle go and start mining again . Randomly happens but goes away  the error scrolls so quick i dont have time to screen shot it but i was able to get a quick copy and paste.  It repeats itself a lot then goes away and starts mining.  

fiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObje

 Cannot bind argument to parameter 'ReferenceObject' because it is null.
M 2.7.2.7\MultiPoolMiner.ps1:479 char:152
s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
                                  ~~~~~~~~~~~~~~~~~
fo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
fiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObje


 Cannot bind argument to parameter 'ReferenceObject' because it is null.
M 2.7.2.7\MultiPoolMiner.ps1:479 char:152
s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
                                  ~~~~~~~~~~~~~~~~~
fo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
fiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObje

 Cannot bind argument to parameter 'ReferenceObject' because it is null.
M 2.7.2.7\MultiPoolMiner.ps1:479 char:152
s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Devi ...
                                  ~~~~~~~~~~~~~~~~~
fo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
fiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObje


 Cannot bind argument to parameter 'DifferenceObject' because it is null.
M 2.7.2.7\MultiPoolMiner.ps1:481 char:181
Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ...
                                          ~~~~~~~~~
fo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
fiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObje


 Cannot bind argument to parameter 'DifferenceObject' because it is null.
M 2.7.2.7\MultiPoolMiner.ps1:481 char:181

**Comment by UselessGuru** [comment]
Did you update the video drivers? If so re-install using the foll driver version - I suspect an OpenGL installation problem.

Did you modify a miner file? Or maybe a miner file got corrupted somehow. 

To find out: Make a save copy of all files in  the 'Miners' folder. Remove all but one miner file and restart MPM. If OK -> copy next miner file back, restart. etc.

**Comment by izzledude** [comment]
I handnt made any changes.  I re installed MPM and issue has been corrected.  Thank you for the support
