### ISSUE TITLE
-MinerStatusURL Invalid Parameter

### ISSUE THREAD

**Issue by Maddcow69** [MultiPoolMiner/MultiPoolMiner#1501]
I am getting the following error. The only way to correct it is to remove the -mierstatusurl string from the startup.bat file.

![error](https://user-images.githubusercontent.com/6981893/37871915-60de4e7c-2fc8-11e8-8e61-3b725b09d0a3.JPG)

I am using the following (slight edits) in order to run MPM-
set "command=& .\multipoolminer.ps1 -wallet xxx -username xxx -workername xxx -region us -currency btc,usd -type nvidia -poolname miningpoolhub,nicehash -algorithm ethash,equihash -watchdog -MPHApiKey xxx -ExcludePoolName Zpool,AhashPool,Hashrefinery -switchingprevention 2"

**Comment by UselessGuru** [comment]
Make sure you have the latest MP version.
https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip
