### ISSUE TITLE
Optimized CCMiner (CUDA miner) fork for x16r

### ISSUE THREAD

**Issue by nemosminer** [MultiPoolMiner/MultiPoolMiner#1507]
https://github.com/nemosminer/ccminernevermore/releases

Optimized CCMiner (CUDA miner) fork for x16r

Forked from https://github.com/tpruvot/ccminer
Alexis78 x16r support added by "brian112358" : https://github.com/brian112358/nevermore-miner
disabled fee and recompiled: https://github.com/nemosminer/ccminernevermore/releases

Note: compiled and tested x64 release performed better than 32bit
seems cuda 9 favors x64 over 32bit

11-hour side-by-side comparison on 1080 Ti show 20% increased hashrate over ccminer-2.2.5

compiled with vs2013 cuda 9

Best Regards
Nemo

**Comment by UselessGuru** [comment]
Pull request pending:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1517

**Comment by titvs** [comment]
I’ve been using it with MPM for a couple of days (added a miner file) and it’s indeed faster. No errors as of today with a mix of nvidia cards (9xx and 10xx).
