### ISSUE TITLE
pwsh high mem usage

### ISSUE THREAD

**Issue by SaintPistachio** [MultiPoolMiner/MultiPoolMiner#1508]
PWSH was using almost 9 GB of memory.
![tm](https://user-images.githubusercontent.com/31291909/37943453-3b3f498e-313d-11e8-8492-837b0c8de8d4.png)
[MultiPoolMiner_2018-03-26.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1850183/MultiPoolMiner_2018-03-26.zip)

**Comment by aaronsace** [comment]
@SaintPistachio You don't need to leave the log reader window open.

**Comment by SaintPistachio** [comment]
Ok I will just comment that line out then.
