### ISSUE TITLE
Use Excavator 1.4.4a only!!! MPM does not support later versions

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1509]
## Changelog

v1.5.0a
- bug fixes & improvements
- **changed stratum protocol to NiceHash Miner Protocol**
- API version bumped to 0.1.0
- added algorithm CryptoNightV7 (XMR)
- speed improvements for CryptoNight
- added support for Tesla P100

### Notes
- From version 1.5.0a further **excavator supports only NiceHash stratum servers**. Stratum servers are available at:
nhmp.LOCATION.nicehash.com (LOCATION: eu, usa, hk, jp, in, br).
- Excavator **API has changed**! Take a look at the config file examples and API documentation.
- This version of Excavator is not compatible with NiceHash Miner (yet).

[Excavator repo](https://github.com/nicehash/excavator)

---

So, the latest version that can be used on other pools then NiceHash is [Version 1.4.4 alpha NVIDIA](https://github.com/nicehash/excavator/releases/tag/v1.4.4a).

For me, the Excavator was the fastest miner in the following algos:
- NeoScrypt
- Lyra2RE2
- Nist5

**Comment by apiontek** [comment]
So, what I did for my linux python multipoolalgo script was just implement the new version of excavator as a completely new miner, like the many variants of ccminer. I just called it "excavator-nh" and it takes effect only for nicehash. It's working great. I haven't benchmarked everything but neoscrypt, lyra2v2, and nist5 are no faster. Equihash is marginally faster. Supposedly the devs are working on making equihash significantly faster so it'd be nice to be able to use the new version at nicehash in the future. It also does the new cryptonightv7 so that's another reason to include it.

**Comment by mserpell** [comment]
Would appreciate seeing this change being built into the next version of MPM.

**Comment by apiontek** [comment]
I still think this is the best approach for mpm for people who want to use excavator, but I must add, for anyone who hasn't tested, I did some extensive multi hour testing today between excavator and klaust's ccminer (for lyra2v2 and neoscrypt) and found that at least for me, excavator seriously over reports compared to what you actually get on the pool. I also tested it vs ewbf and dstm for equihash, and ethminer and claymore for ethash, and found it the worst of the three in both cases in terms of pool-reported hashrate. I will no longer care about using excavator at all anywhere going forward for anything.

**Comment by Maddcow** [comment]
apiontek - will you post the file that you created to get excavator to work.

Excavator hasn't work for me at all - regardless of version. Always errors out or displays 0 hash on all algorithms.

**Comment by apiontek** [comment]
This is my json template for excavator 1.4.4a

```json
[
  {
    "time": 0,
    "commands": [
      {
        "id": 1,
        "method": "algorithm.add",
        "params": [
          "{algorithm}",
          "{host}:{port}",
          "{user}:{password}"
        ]
      }
    ]
  },
  {
    "time": 3,
    "commands": [
      {
        "id": 1,
        "method": "worker.add",
        "params": [
          "0",
          "0"
        ]
      }
    ]
  },
  {
    "time": 10,
    "loop": 10,
    "commands": [
      {
        "id": 1,
        "method": "algorithm.print.speeds",
        "params": [
          "0"
        ]
      }
    ]
  },
  {
    "time": 13,
    "commands": [
      {"id":1,"method":"worker.reset","params":["0"]}
    ]
  }
]
```

And here's my template for excavator 1.5+:

```json
[
  {
    "time": 0,
    "commands": [
      {
        "id": 1,
        "method": "subscribe",
        "params": [
            "{host}:{port}",
            "{user}:{password}"
          ]
      }
    ]
  },
  {
    "time": 1,
    "commands": [
      {
        "id": 1,
        "method": "algorithm.add",
        "params": [
          "{algorithm}"
        ]
      }
    ]
  },
  {
    "time": 2,
    "commands": [
      {
        "id": 1,
        "method": "worker.add",
        "params": [
          "{algorithm}",
          "0"
        ]
      }
    ]
  },
  {
    "time": 10,
    "loop": 10,
    "commands": [
      {
        "id": 1,
        "method": "algorithm.print.speeds",
        "params": [
        ]
      }
    ]
  },
  {
    "time": 12,
    "commands": [
      {"id":1,"method":"worker.reset","params":["0"]}
    ]
  }
]
```

**Comment by apiontek** [comment]
@Maddcow -- on the off chance you're mining at miningpoolhub, it's blacklisted in excavator if you use hostnames. You can get around it by using an IP address for the pool server. I think when it can't get to a server is one of the times I've seen excavator sit there doing nothing and reporting 0 hashrate when I thought I had everything right in the json commands.

**Comment by Maddcow** [comment]
I am trying to use both MPH and nicehash but can only get MPH to work. As for the hostnames - i am using whatever the default settings are. What would I add/modify inorder for it to use the IPs instead? Is it possible to have it set to try the hostnames first and then the IP (in the off chance the hostnames isnt resolved)?

**Comment by apiontek** [comment]
What do you mean by "default settings?" Are you trying to use excavator on its own, or with MultiPoolMiner? I can't really provide support for the latter as I don't use it anymore.

**Comment by Maddcow** [comment]
Got ya - trying to be excavator to work with MPM.

**Comment by apiontek** [comment]
Well, if memory servers, MPM already auto-configures excavator, so you shouldn't have to mess with the excavator json files. If MPH is working but NH isn't, there must be something strange going on.

What I was talking about above was that I have my own mining scripts and got the new excavator 1.5+ to work with them, but what I did isn't a drop-in solution for MPM, and I don't have time to try to create one, sorry. I'm sure they'll get around to it.

But if it's any consolation, I'm finding excavator really over-reports its hashrates. On the console it looks like it's faster for neoscrypt and lyra2v2, but on the pool (I've tested with ahashpool and MPH so far), you actually get significantly lower hashrates.

I'm quite surprised, as I haven't seen anyone talking about excavator fudging hashrates, but I keep testing and I keep getting the same results -- you're far better off deleting excavator entirely and sticking to the various ccminers, ewbf/dstm, and ethminer/claymore.

**Comment by Maddcow** [comment]
Been using DSTM/PheonixMiner for the majority of my mining. Still rotating around different auto switches (AM, MPM, thinking of Nemos next). 

Thanks for info tho.

**Comment by apiontek** [comment]
@borzaka I'm curious, when you report excavator as fastest for neoscrypt, lyra2v2, and nist5 - is that with testing the rates you get on the pools, too? Or just what it reports in the console?

**Comment by borzaka** [comment]
@apiontek First, I believed that Excavator is the fastest on some algorithms only based on the miner reports, but I'am not sure anymore.
I had an extensive test, for 24 and 12 hours on [A Hash Pool](https://ahashpool.com/), and it turned out that lyra2v2 algo is almost half on the pool side, so as my earnings. It looks like that others experiencing this too. I don't want to link the issue, but you can find it in the official Excavator repo.
I have tested NeoScrypt as well, this algo was very accurate on the pool side in my long testing.
