### ISSUE TITLE
6 GPU + support 

### ISSUE THREAD

**Issue by psynauty** [MultiPoolMiner/MultiPoolMiner#1510]
Hi Aaron,
Could you let me know if MPM supports more than 6GPUs out of the box?
Your README file says up to 6GPU but I saw you replied to another thread saying just use Start.bat.
Not sure why Start.bat will be ok with more than 6GPUs vs. say Start-MiningPoolHub.bat.
If indeed more than 6GPUs are supported, why is are you suggesting in the README that it's not?
Are there some limitations above 6GPUs that you could outline?
Thanks for the great work,
-psynauty

**Comment by UselessGuru** [comment]
6 GPUs is the supported number. MPM has not been tested with more than 6 GPUs.

See here:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1087

If it works its fine, if not report in the above thread and let us know which miners are fine with > 6 cards, and which do not work, Thanks.

**Comment by psynauty** [comment]
According to the comment by Aaron
need help for 12gpu setup in awesomeminer on closed issue [https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1000](url), it's fine out of the box (use Start.bat).
But is the limitation on the miners?

**Comment by UselessGuru** [comment]
> But is the limitation on the miners?

Yes, can be. MPM has no known built in limitation
