### ISSUE TITLE
support for x16r algo v2.7.2.7

### ISSUE THREAD

**Issue by amolitor** [MultiPoolMiner/MultiPoolMiner#1512]
Heya there, any way that this algo can be supported ? (didnt see any support on website) mostly if for the new coin RVN at yimmp.eu tried to config like this:
    "YiiMP": {
      "RVN": "RUp2A4YYAZDXjdyiQUEuvPWxX5oMomSJyR",
      "Worker": "$WorkerName"
    }

But seems to be ignored, thanks.

**Comment by mkirov0** [comment]
I wish there was a way, but #1412  has more info on why its not that easy to implement.

**Comment by amolitor** [comment]
understood thanks.

**Comment by UselessGuru** [comment]
@amolitor 

FYI: Algorithm and poyout currency are not a married coubple. If you are mining on an auto-conversion pool (e.g. Zpool) you can mine ANY algorithm, but the received payouts is autoconverted to e.g. BTC.

Supporting an algo is done by providing a miner that supports it.

**Comment by amolitor** [comment]
@UselessGuru  i know that, but thanks anyway for the tip .. the issue is that at YIIMP they dont allow btc wallets, so was trying to make it work.
