### ISSUE TITLE
New miner CcminerSuprMiner: Supports new algorithms X16R & X16S

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1515]
[Download the miner file](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/CcminerSuprMiner.ps1) and put it in the 'Miners' folder.

**Note: Due to the very nature of the X16R algorithm you must turn watchdog off, otherwise the algo will be kicked.** read here: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1412

**New algorithm X16S**
http://cryptomining-blog.com/9639-check-out-pigeoncoin-pgn-with-new-x16s-mining-algorithm/

Zergpool has added the X16S algorithm 🥇

**Comment by alucard20724** [comment]
that's exactly what i do... turn watchdog off.

now if only we can get version 3.7.3 released so i can bring my AMD machines back on MPM with miner windows showing up.  I currently run my AMD machines on just x16r without mpm.

**Comment by mtbor** [comment]
@UselessGuru 
You mean zergpool has added X16R, right?

**Comment by alucard20724** [comment]
zergpool and now blazepool have X16R, and zergpool had X16s available for a short time but not as a tradeable coin.  I see that X16s has been removed from zergpool.  X16s was Pigeon coin, which to me is just a translation of "shit coin"

**Comment by UselessGuru** [comment]
SuprMiner is supported by MPM since https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1528
