### ISSUE TITLE
wrong port in ClaymoreCpu.txt

### ISSUE THREAD

**Issue by Caspar007** [MultiPoolMiner/MultiPoolMiner#1525]
Error in Miner file, port numbers are inccorrect. The "Port" reads -3333 (negative ports won't work)
Below corrected version:

    "API":  "Claymore",
    "Port":  "3333",
    "Wrap":  false

[ClaymoreCpu.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1864228/ClaymoreCpu.txt)

**Comment by grantemsley** [comment]
No, the negative port number is correct and completely intentional

> -mport   remote monitoring/management port. Default value is -3333 (read-only mode), specify "-mport 0" to disable remote monitoring/management feature. 
   Specify negative value to enable monitoring (get statistics) but disable management (restart, uploading files), for example, "-mport -3333" enables port 3333 for remote monitoring, but remote management will be blocked.

It disables remote management.

**Comment by Caspar007** [comment]
Hi Grant,

Thanks for the swift reply. 

Here is the line in ClaymoreCPU.txt you are referring to:
`    "Arguments":  "\"-r -1 -mport 3333 -o $($Pools.Cr....`
It is not set to -3333 as per your remark.

The bug report was meant to highlight another issue; the API is unable to read the actual hash rate, throwing the exception "Failed to connect to miner".

The API script is invoking a TCP connection, using the "Port" variable to refer the actual TCP port. 
A TCP connection to a negative port number won't work, as there are no negative ports! 

In the spirit of getting this very useful software better, please update the ClaymoreCPU.txt to reflect correct values.

Best regards
Christian

**Comment by grantemsley** [comment]
Ah my apologies, I see what you mean now.  The arguments should be negative but isn't.  The port field should be positive.  It's backwards now.

I'll get that fixed up.

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1527
