### ISSUE TITLE
Integrate Excavator API causes error if Excavator is only miner

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1538]
Is ist just me?

Since
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/a0857c0757ac2577df7c2631e31d746383d5a442

 on first run I get the following errors:

```
PS>TerminatingError(Get-Process): "Cannot validate argument on parameter 'Name'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain any null values and then try the command again."
Get-Process : Cannot validate argument on parameter 'Name'. The argument is null, empty, or an element of the argument 
collection contains a null value. Supply a collection that does not contain any null values and then try the command 
again.
At C:\Users\UselessGuru\Desktop\NewPoc\MultiPoolMiner.ps1:616 char:23
+ ... ocess -Name @($ActiveMiners | ForEach-Object {$_.GetProcessNames()})  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Command
PS>TerminatingError(Get-Process): "Cannot validate argument on parameter 'Name'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain any null values and then try the command again."
Get-Process : Cannot validate argument on parameter 'Name'. The argument is null, empty, or an element of the argument 
collection contains a null value. Supply a collection that does not contain any null values and then try the command 
again.
At C:\Users\UselessGuru\Desktop\NewPoc\MultiPoolMiner.ps1:616 char:23
+ ... ocess -Name @($ActiveMiners | ForEach-Object {$_.GetProcessNames()})  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Command
```

**Comment by grantemsley** [comment]
It seems to be working fine for me.  Excavator launches without any errors and the window is visible.

**Comment by UselessGuru** [comment]
Cause found - but it still not happen:
I am testing ExcavatorNvidia1 & 2. They are the only two miners configures. 
As soon as I add other miner files the error goes away.

Reason: 
Lines 10-13 in Api\Excavator.ps1
```
    [String[]]GetProcessNames() {
        return @()
    }
```

What is their reason?

**Comment by borzaka** [comment]
What Excavator version are you using?

With version 1.5.0a they changed some of the API methods. Versions 1.5.x are not compatible with old json files, check [API docs](https://github.com/nicehash/excavator/tree/master/api) changes and [new json file example](https://github.com/nicehash/excavator/blob/master/default_command_file.json).

Other info:
> From version 1.5.0a further excavator supports only NiceHash stratums.

So, there is two possibilities:
- old Excavator (<=1.4.4): for every pool with old API
- new Excavator (>=1.5.0): for only NiceHash with new API

**Comment by UselessGuru** [comment]
@borzaka 
1.4.4a

My question is not version related. It is about how to add custom command to the miner definition file.

**Comment by mtbor** [comment]
The integrated API doesn't work here, caused the miner to sit idle.  I deleted Excavator.ps1 from the API folder and it's back to working.  If any changes are made I'll give it another shot.

**Comment by UselessGuru** [comment]
> I deleted Excavator.ps1 from the API folder

Nooo... Api\Excavator.ps1 is needed to read hashrate from the miner. If deleted MPM's watchdog will disable Excavator.

**Comment by mtbor** [comment]
Won't run any other way...  I have re-downloaded the master and tried
again..  The API script is broken.  Who needs watchdog anyway?!?

**Comment by mtbor** [comment]
I reverted to this: [https://github.com/MultiPoolMiner/MultiPoolMiner/commit/a0857c0757ac2577df7c2631e31d746383d5a442#diff-69b5e62237d5f951ca1ac096869d0234](url)
I believe that was the point in time when it was last working.
