### ISSUE TITLE
Integrate Excavator API: howto use custom commands

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1539]
What is the correct format for custom commands?

And how do I use them If I want different commands per deviceID?
I can think of the following 3 variants 
a)     "blake2s" = @("A=1","B=2"),@("C=1","D=2") #Blake2s
b)     "blake2s" = @('"A=1","B=2"','"C=1","D=2"') #Blake2s
c)     "blake2s" = @(@("A=1","B=2"),@("C=1","D=2")) #Blake2s

Values for A&B are for deviceID0, C&D for deviceID1

**Comment by phanngocchien1986** [comment]
b) "blake2s" = @('"A=1","B=2"','"C=1","D=2"') #Blake2
