### ISSUE TITLE
Excavator failing

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#1542]
MPM is launching excavator with this command line:

```
C:\users\grant\desktop\testcopy\Bin\Excavator\excavator.exe [{"id":1,"method":"algorithm.add","params":["neoscrypt","13.228.127.224:4233","1FyaoHySEa4VY9f3TtPBvGiMsYQCuGtYGE:GRANTNEW,c=BTC"]},{"id":1,"method":"workers.add","params":["alg-0","0"]}]
```

Even when I run that manually from the command line, excavator outputs this:
```
[14:40:54][0x0000148c][info] Log started
[14:40:54][0x0000148c][info] core | Found CUDA device: GeForce GTX 1080
[14:40:54][0x0000148c][info] api | Listening on 127.0.0.1:3456
[14:40:54][0x0000148c][info] core | Initialized!
```
Then just exits.  %ERRORLEVEL% return code is -1.

Anyone else seeing that behavior?

**Comment by UselessGuru** [comment]
It works for me... but I have not tested extensively.

**Comment by scolarita13** [comment]
Yes I got this during benchmark.
I just have raised an issue.

**Comment by aaronsace** [comment]
The Excavator log should say what's wrong. It will say what commands are being sent to it and what messages are returning from it.

**Comment by scolarita13** [comment]
I have replaced excavator with a lower version: excavator_v1.4.4a_NVIDIA_Win64 and now it works.
The version which fails is excavator_v1.5.1a_NVIDIA_Win64

**Comment by scolarita13** [comment]
Where is this excavator log? I couldn't find anything in /Logs folder. The main MultiPoolMiner_2018-04-02 log contains the entry when he excavator is launched and nothing else.
As I said the lower version works. I think the new version has a bug.

**Comment by UselessGuru** [comment]
>The version which fails is excavator_v1.5.1a_NVIDIA_Win64

## Do NOT use 1.5x. It only works with NiceHash, The highest supported version is 1.4.4a

Note: This is an Excavator limitation, and not MPMs
