### ISSUE TITLE
After benchmark all algorithms with excavator miner are excluded

### ISSUE THREAD

**Issue by scolarita13** [MultiPoolMiner/MultiPoolMiner#1543]
I have finished the benchmark and I have observed the all algorithms which run with excavator miner are eliminated and I can't see any benchmark result.
During benchmark the excavator console was open but frozen.
I checked all stats for excavator and I have this:

{
    "Live":  0,
    "Minute":  0,
    "Minute_Fluctuation":  0,
    "Minute_5":  0,
    "Minute_5_Fluctuation":  0,
    "Minute_10":  0,
    "Minute_10_Fluctuation":  0,
    "Hour":  0,
    "Hour_Fluctuation":  0,
    "Day":  0,
    "Day_Fluctuation":  0,
    "Week":  0,
    "Week_Fluctuation":  0,
    "Duration":  "00:01:10.8716517",
    "Updated":  "\/Date(1522685687885)\/"
}

So no benchmark was executed.

**Comment by scolarita13** [comment]
I have replaced excavator with a lower version: excavator_v1.4.4a_NVIDIA_Win64 and now it works.
The version which fails is excavator_v1.5.1a_NVIDIA_Win64

**Comment by UselessGuru** [comment]
## Do NOT use Excavator 1.5x. It only works with NiceHash, The highest supported version is 1.4.4a

Note: This is an Excavator limitation, and not MPMs
#1509
