### ISSUE TITLE
Multipoolminer.io Algorithms

### ISSUE THREAD

**Issue by jestercore** [MultiPoolMiner/MultiPoolMiner#1547]
Hello dear devs, please, update this page https://multipoolminer.io/algorithms
We need this to write configs and batch files!

**Comment by alucard20724** [comment]
i think @grantemsley maintains the multipoolminer.io site

**Comment by grantemsley** [comment]
Actually it's @fonyo that usually does that.  I just wrote the monitoring part of the site.

**Comment by alucard20724** [comment]
is @fonyo even around anymore?.. haven't heard anything from him in over a month.

**Comment by jestercore** [comment]
Oh. I hope he is ok. 
What about adding algorithm list in readme guide on github?

**Comment by UselessGuru** [comment]
There is NO definite list of supported algorithms.

MPM recommends a subset of available algorithms to maximize profit. The recommended algorithms are the ones included in start.bat.

New algorithms & coins are constantly being added - it is the pool operators who add algorithms & coin names at will. Im MPM has a miner for the algorithm then MPM will automatically include it in its profitablilty calculations.
On each the list of available algorithms is changing. It can be retrieved through the API:
http://localhost:3999/algorithms

Implemented in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1732
