### ISSUE TITLE
benchmark ccminer for CcminerTpruvot and CcminerNanashi need to rung longer 

### ISSUE THREAD

**Issue by jjziets** [MultiPoolMiner/MultiPoolMiner#1549]
The benchmark is to short for Ccminer in most cases. 

![image](https://user-images.githubusercontent.com/19214485/38369513-26971d1a-38e8-11e8-8e96-ed62a1fa4d80.png)

If I run it for 5 minits i get +1000Kh/s

**Comment by jjziets** [comment]
that is neoscrypt. just using it as an example

**Comment by thebeerbaron2018** [comment]
You can set the interval in the command line.  I usually use 180 (3 minutes) - but you can set whatever value in seconds you wish.  Obviously remember that the longer you set, the longer it will take to benchmark.  Finally, you can change it to a lower value and restart if you want faster profit switching after the benchmarks are completed.  

-interval MultiPoolMiner's update interval in seconds. This is a universal timer for running the entire script (downloading/processing APIs, calculation etc). It also determines how long a benchmark is run for each miner file (miner/algorithm/coin). Default is 60.

**Comment by alucard20724** [comment]
yeah... what @thebeerbaron2018 said.   I normally run my my interval at 420 for invidia cards (mostly because of excavator and x16r) and interval 300 for my AMD cards (to get a good benchmark for claymore on nicehash), and 720 for cpu (because the cpu takes a longer time to find an accepted share and the benchmark only records for the accepted shares)

**Comment by jjziets** [comment]
great will set to 10min after a ran the first batch and then delete those stats only.

**Comment by thebeerbaron2018** [comment]
Don't do that.  Set to 10 minutes with "-interval 600" on the command line - let the benchmarks finish and then change to "-interval 60" or however many seconds you want between profit checks on the pools.  The stats files need to be present or it will benchmark again.

**Comment by alucard20724** [comment]
@thebeerbaron2018   "-interval 600" doesn't work... it never runs for 10 minutes... and i made a mistake for cpu... i run the interval for 420/540 for cpu.  for some reason, 600 never runs for 600, but 60 instead.

**Comment by thebeerbaron2018** [comment]
Can you post your .BAT file so I can see?  Please also make sure you don't use the quotes around the interval command.  The set line should look something similar to this (plus all your own customizations) - the values in CAPITALS need to be your values and you may need to change region or currency or type depending on your location and rigs.  The important part for the benchmark is the last interval command!

set "command=& .\multipoolminer.ps1 -wallet YOURWALLET -username YOURUSERNAME -workername YOURWORKERNAME -region europe -currency btc,usd,eur -type amd,nvidia,cpu -poolname YOURPOOLS -donate 24 -watchdog -minerstatusurl https://multipoolminer.io/monitor/miner.php -switchingprevention 2 -interval 600

**Comment by UselessGuru** [comment]
See https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1682
