### ISSUE TITLE
Restrict to certain GPUs?

### ISSUE THREAD

**Issue by flashburn2012** [MultiPoolMiner/MultiPoolMiner#155]
Is there a way to restrict running on only certain GPUs? I know you can manually do this in at least some of the miners, but if you want to switch from say running on 1 or 2 GPUs it's not really feasible to edit each miner.

**Comment by aaronsace** [comment]
Not yet sorry.

**Comment by flashburn2012** [comment]
Okay, thanks!

**Comment by Ondalf** [comment]
Is this question about Nvidia or scramble-my-devlist-AMD? Case of different models?

**Comment by flashburn2012** [comment]
The use case is basically, when I want to play a game, or otherwise use one of my GPU's for something else, it'd be nice to have the option to do so.

**Comment by Ondalf** [comment]
That would require some switches and probably user interaction for MPM. It's not impossible, but like dev said, not yet.

**Comment by flashburn2012** [comment]
Yeah, that's fine. I was just hoping it was something that was already supported. Thanks.

**Comment by fonyo** [comment]
Some of the miners support disabling certain cards. From the top of my head, press 0-9 in Claymore miners, sgminer and it's derivatives support it through pressing G, D, [0-9, the number for the card] and hit the enter key. This is much quicker and simpler than implementing switches in MPM.

**Comment by flashburn2012** [comment]
Except those settings aren't saved between runs, and like you said "some of the miners". I hacked the scripts to do it for Claymore at least, can just run a different build of the tool when I want to not run on my primary GPU.

**Comment by Ondalf** [comment]
If you run nvidia cards, there is a way that I implemented. Just remove all miners ending at 0 to remove your primary GPU out from miner-combo. Check nvidia-per-gpu branch. Not sure, how it scales on AMD, claymore etc. since I don't have such a GPU to play with...

**Comment by scaras** [comment]
i use the -di flag in the miner settings (and moving the files in and out the miner folder)
all files have a different name, so MPM remembers the correct speed.

**Comment by UselessGuru** [comment]
see https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1237

**Comment by grantemsley** [comment]
This is now possible.
