### ISSUE TITLE
XMR-XMV fork, updating cryptonight miners

### ISSUE THREAD

**Issue by oALiASo** [MultiPoolMiner/MultiPoolMiner#1556]
Not sure if this is on your road map yet since it's happening "now"

Monero fork to XMV is in progress and everyone has release new software. Looks like the version of xmr-stak used by MPM is pretty old. I don't know if this means more work for you guys.

Cheers.

**Comment by borzaka** [comment]
You are right. MultiPoolMiner is not ready for the Monero fork.

[http://minexmr.com/](http://minexmr.com/)
> You need to update to XMRig 2.5, Cast XMR 0.9.0, xmr-stak 2.3.0 or newer.

[https://monerohash.com/](https://monerohash.com/)
> These are the updated miners that support the new POW variant: XMRig 2.5, Cast XMR 0.9.0, xmr-stak 2.3.0, Claymore v11.3, CPUMiner forked by hyc.

Latest versions:
[XMRig](https://github.com/xmrig/xmrig/releases)
[Cast XMR](http://www.gandalph3000.com/)
[XMR-Stak](https://github.com/fireice-uk/xmr-stak/releases)
[Claymore's CryptoNote AMD GPU Miner](https://bitcointalk.org/index.php?topic=638915.0)

**Comment by grantemsley** [comment]
XMRig update just got commited.
Cast is already up to date.

XMR-Stak's release page says the config file format has changed, so some work may need to be done there to make sure we are generating correct configuration.

**Comment by angelics** [comment]
quickfix xmr-stak for those who need.
`-c $($Pools.CryptoNight.Name)_CryptoNight_$($Pools.CryptoNight.User)_Cpu.txt -C $($Pools.CryptoNight.Name)_CryptoNight_$($Pools.CryptoNight.User)_Cpu.txt --noUAC --noAMD --noNVIDIA`
and
`currency        = "monero7"`
im nt sure if u need to add rig_id in for it to work. i have them added in miner

**Comment by UselessGuru** [comment]
@angelics 

I don't quite understand the 'monero7' argument. Where did you learn about it? 
Can you post your working miner file? TIA!

**Comment by angelics** [comment]
@UselessGuru 

[FireiceNvidia242.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1888450/FireiceNvidia242.zip)

i did nt understand why they went for diff config file using -c -C

**Comment by borzaka** [comment]
In XMR-Stak there can be maximum 5 config file:
- config.txt
- cpu.txt
- nvidia.txt
- amd.txt
- pools.txt

There are changes in config.txt, amd.txt and pools.txt (which is new, extracted from config.txt) from prev versions.

For example this is my pools.txt for the new Monero PoW:
```
/*
 * pool_address    - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address  - Your wallet, or pool login.
 * rig_id          - Rig identifier for pool-side statistics (needs pool support).
 * pool_password   - Can be empty in most cases or "x".
 * use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 * pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool 
 *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
 *
 * We feature pools up to 1MH/s. For a more complete list see M5M400's pool list at www.moneropools.com
 */

"pool_list" :
[
	{"pool_address" : "pool.supportxmr.com:5555", "wallet_address" : "xxxyyyzzz", "rig_id" : "", "pool_password" : "probook470", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

/*
 * Currency to mine. Supported values:
 *
 *    aeon7 (use this for Aeon's new PoW)
 *    cryptonight (try this if your coin is not listed)
 *    cryptonight_lite
 *    edollar
 *    electroneum
 *    graft
 *    intense
 *    karbo
 *    monero7 (use this for Monero's new PoW)
 *    sumokoin
 *
 */

"currency" : "monero7",
```

Note the `currency` with the `monero7`.

**Comment by borzaka** [comment]
Command line options:
`xmr-stak.exe --noUAC --noCPU --currency monero7 -o url -u username -p password -r rigid -i 3335`

**Comment by grantemsley** [comment]
Fixed in commit ffea9dfea692d62788f2c92a0327bba395f5232a

**Comment by borzaka** [comment]
`-i --httpd HTTP_PORT       HTTP interface port`

Based on @grantemsley's commit, XMR-Stak is now only supports `monero7`? There are these options:
```
/*
 * Currency to mine. Supported values:
 *
 *    aeon7 (use this for Aeon's new PoW)
 *    cryptonight (try this if your coin is not listed)
 *    cryptonight_lite
 *    edollar
 *    electroneum
 *    graft
 *    intense
 *    karbo
 *    monero7 (use this for Monero's new PoW)
 *    sumokoin
 *
 */
```

If I want to mine Electroneum (another Cryptonight algo), than I can't, because `monero7` is burned in the config.

**Comment by grantemsley** [comment]
@borzaka xmr-stak was previously hard coded to use 'monero' for the currency setting.

**Comment by borzaka** [comment]
That's true, monero currency settings was for every Cryptonight algo coin, be now there are changes; you can't mine electroneum with monero7 currency setting.

**Comment by aaronsace** [comment]
CryptoNightV7 needs adding as an algorithm; Monero no longer uses Cryptonight. 

The MiningPoolHub site is wrong as it says still says 'Cryptonight' for both 'Monero' and 'Electroneum': 
https://miningpoolhub.com/

**Comment by UselessGuru** [comment]
Currently only NiceHash and MPH support mining CryptoNight.

NH is already exposing the new algo 'CryptoNightV7' throught its API. I am working on the FireIce miner files to support the new algo in parallel with the old ones.

**Comment by UselessGuru** [comment]
Fixed - Cryptonight V7 is fully supported now
