### ISSUE TITLE
Been Away for a bit .......anything i need to get this running correctly

### ISSUE THREAD

**Issue by JUPIE2008** [MultiPoolMiner/MultiPoolMiner#1557]
Hi Guys i been away for about 2 months and just got bsck yesterday. I am a lot rusty  and feel a bit lost ....please could you assist i however thereis something i need to do. Im using RX570 and 580 GPUS if that will help ...I get this justafter benchmarking
![capture3](https://user-images.githubusercontent.com/34841470/38424299-e1a0bb16-39b0-11e8-9124-8f0883438b51.PNG)

**Comment by mtbor** [comment]
The CL_MEM_OBJECT_ALLOCATION_FAILURE error is likely inadequate amounts of virtual memory.  Try increasing your virtual memory to some obscene amount...  Increase it until you no longer get the error..  try something like 64GB (64,000)...  If that works, decrease it until you get the error again...  Then give yourself several GB of buffer on top of that.
