### ISSUE TITLE
Zergpool Profit Accuracy

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#1560]
Zergpools implementation of Yiimp seems to balance hashrate across an algorithm, so some miners are mining the most profitable, but some are mining much less profitable coins.  The share percentage is directly tied to the coin you're mining, and your payout is based on this.

I have two rigs that I have had mining to zergpool, one will sometimes show just the algorithm it is mining, the other will often show which specific coin it is mining, the functionality to keep track of the profitability for each individual coin and make switching decisions based on this seems to exist, but be inconsistent.

As such, I must raise the question, how can we be sure that with Zergpool enabled, MPM is making accurate switching decisions?

**Comment by aaronsace** [comment]
@mtbor It's all accounted for. Option 1, 2 and 3 are supported. 

ZergPool is a mix of Zpool (fractional hashrate distribution with exchange) and YiiMP (individual coin mining). 

https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Pools/ZergPool.ps1

**Comment by mtbor** [comment]
aaronsace, thanks, where can I read more about these options?

**Comment by UselessGuru** [comment]
> where can I read more about these options?

http://zergpool.com/

**Comment by mtbor** [comment]
As far as control within MPM though, it's completely automatic?  It's just a matter of what data has been saved into stats whether it decides to pick a specific coin (option 2), or mine to the algorithm (option 1).  I only ask the question because I see different behaviors between my systems.

**Comment by mkirov0** [comment]
IMHO if you reset profits of both systems at the same time and start fresh the switching and mining targets should equalize.

**Comment by mtbor** [comment]
@mkirov0 You're probably right.  In the long run it only seems to latch onto a single coin if it's pretty dominant and stable.  In the short run it can look a little messy, only as good as the best data it's seen, which isn't much or very good.
