### ISSUE TITLE
ASUS ROG STRIX RX 580 8GB mining speed

### ISSUE THREAD

**Issue by BbyR023** [MultiPoolMiner/MultiPoolMiner#1561]
Hello guys, i don't know if here is the right place to ask this but, who has GPUs like mines RX580 8GB, what are your mining speed? I mine  ETH with 14-16 Mh/s and i don't know why. I think the right speed for these cards, are between 25-30 Mh/s, am i wrong? Can someone help me what should i change (parameters in mining programs, GPUs are already overclocked from factory, i tried to overclock more but no chance). Thank you guys !

**Comment by UselessGuru** [comment]
When it comes to MPM there are no extra parameters that need to be added to get your card to work at expected speed.

Are the speeds for other algorithms also too slow?

**Comment by BbyR023** [comment]
I don't know about the other algorithms speeds, I mean I know the speeds, but i don't know to what numbers to compare. e.g. FTC is around 7.5 Kh/s

**Comment by alucard20724** [comment]
you can't compare speeds of one algorithm to the speeds of a different algorithm.  FTC is not etherium and etherium is not FTC.  Your best bet is to go into the bitcointalk forums and find out the average etherium hashrate for an RX580.  You also need to know what version of eth miner they are using.  there's like 4 different eth miners out there.  Phoenix miner, Claymore (most popular one), GatelessGate, Etherminer.... and i think there's a couple others also.

or just Google "RX580 etherium algo miner".. or something such

**Comment by BbyR023** [comment]
and i didn't. I just told you the speed for FTC, didn't compare with ETH, but my eth speed is 14-16 mh\s and when i saw on internet the actual speed for eth (25-30mh\s) thats why i said something is not right

**Comment by symalla** [comment]
I am running 6 RX580's with MPM. These are my current speeds if that helps.

![2018-04-09 15_31_53-192 168 1 33 - remote desktop connection](https://user-images.githubusercontent.com/7012032/38521434-47686816-3c0b-11e8-9803-8ca6f0794395.jpg)

**Comment by BbyR023** [comment]
So guys, i asked in different forums about my problem, just like here. I got some answers and put them to the test. I want to share with you my results, but i know i should have better ones.

So i uninstall my actual AMD driver, download a suggested one ( i still don't know if this is the right one but it works better then the latest, you will see the link below from where i download it ) and i rebenchmarked the speeds in MPM. I was happy to see some improvements but i am still not 100% happy.

@symalla you are running your mining with aprox. same speed my RIG is hashing. so maybe you should try my "solution". 

I would be very happy if other users that have GPUs like mine RX 580 8G, and didn't know about this and they try it, to post here if my way worked for them. If theirs hashing speed improved or decreased, if i was a lucky guy with this or not.

If i will find another and better way to improve my hashing speed i will come and share with you, but if you already know please share it with me. I also appreciate the other users the replied until now to my post.


AMD driver link:  https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-Beta-for-Blockchain-Compute-Release-Notes.aspx

My new hashing speeds:
![speed1](https://user-images.githubusercontent.com/37816769/38572007-9efa00ea-3cfa-11e8-880b-77cb4b5342c9.jpg)
![speed2](https://user-images.githubusercontent.com/37816769/38572008-9f1eea54-3cfa-11e8-92c3-54fe7c9978ea.jpg)

**Comment by BbyR023** [comment]
Ty, I've done some changes, mining with 22.5Mh/s constantly, but i am kinda stuck at modding the GPUs. The site from Anorak is down, i tried to contact him on reddit, still no answer, but i don't think i will mod my gpus solo. I will try to contact him on other platforms he is active or ask others about those deeply parameters i need to change. 10x for your info until now, it helped me alot.
