### ISSUE TITLE
Prospector: ERROR  Signatum: network client disconnected, Trying to reconnect

### ISSUE THREAD

**Issue by IndiaVenom** [MultiPoolMiner/MultiPoolMiner#1567]
I constantly get this when I try to run MPM.

Here are my logs:
[MultiPoolMiner_2018-04-09_15-02-37.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1891620/MultiPoolMiner_2018-04-09_15-02-37.txt)
[MultiPoolMiner_2018-04-09_15-03-21.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1891621/MultiPoolMiner_2018-04-09_15-03-21.txt)

[MultiPoolMiner_2018-04-09.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1891623/MultiPoolMiner_2018-04-09.txt)

Because it won't let me upload the prospector .txt
https://pastebin.com/MK7ruBEg

**Comment by UselessGuru** [comment]
Do you have a local firewall? If so turn it off ans see what happens.

I have a similar issue with Xmrig-Nvidia. No matter how I configure my FW (Symantec Endpoint Protection) I still cannot connect.

**Comment by UselessGuru** [comment]
Prospector is no longer supported by MPM
