### ISSUE TITLE
Update Claymore's CryptoNote CPU miner

### ISSUE THREAD

**Issue by n3cr0cr0w** [MultiPoolMiner/MultiPoolMiner#1568]
This is also needed for Monero hard fork.

https://bitcointalk.org/index.php?topic=647251.msg33748163#msg33748163

- removed devfee, miner is completely free now.
- added "-pow7" option to support Monero hardfork, use "-pow7 1" value to enable it.

**Comment by grantemsley** [comment]
Added in latest commit.  New binaries must be manually updated.
