### ISSUE TITLE
MPM Errors on 1st Run

### ISSUE THREAD

**Issue by sidwayz240sx** [MultiPoolMiner/MultiPoolMiner#1574]
I have MPM installed on my PC working fine.  I'm trying to install it on my mining rig and I'm getting this error in powershell.  Can someone please she'd some light on this, it's driving me crazy.  I've tried older versions, the older excavator, and multiple reinstalls.

Transcript started, output file is .\Logs\2018-04-10_19-28-12.txt Exception calling "Create" with "1" argument(s): "At line:1 char:29 + Set-Location('C:\Users\Jake's Miner\Downloads\MultiPoolMinerV2.7.1.4' ... + ~ Unexpected token 's' in expression or statement.

At line:1 char:29 + Set-Location('C:\Users\Jake's Miner\Downloads\MultiPoolMinerV2.7.1.4' ... + ~ Missing closing ')' in expression.

At line:1 char:69 + ... et-Location('C:\Users\Jake's Miner\Downloads\MultiPoolMinerV2.7.1.4') + ~~ The string is missing the terminator: '." At C:\Users\Jake's Miner\Downloads\MultiPoolMinerV2.7.1.4\MultiPoolMiner.ps1:87 char:87 + ... onScript ([scriptblock]::Create("Set-Location('$(Get-Location)')")) - ... + ~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [], MethodInvocationException + FullyQualifiedErrorId : ParseException Exception calling "Create" with "1" argument(s): "At line:1 char:29 + Set-Location('C:\Users\Jake's Miner\Downloads\MultiPoolMinerV2.7.1.4' ... + ~ Unexpected token 's' in expression or statement.

At line:1 char:29 + Set-Location('C:\Users\Jake's Miner\Downloads\MultiPoolMinerV2.7.1.4' ... + ~ Missing closing ')' in expression.

At line:1 char:69 + ... et-Location('C:\Users\Jake's Miner\Downloads\MultiPoolMinerV2.7.1.4') + ~~ The string is missing the terminator: '." At C:\Users\Jake's Miner\Downloads\MultiPoolMinerV2.7.1.4\MultiPoolMiner.ps1:87 char:87 + ... onScript ([scriptblock]::Create("Set-Location('$(Get-Location)')")) - ... + ~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [], MethodInvocationException + FullyQualifiedErrorId : ParseException

**Comment by grantemsley** [comment]
Having an apostrophe in your username, while technically allowed by windows, will break all sorts of things. At the moment, MPM doesn't completely escape paths.  So it thinks everything is installed in `C:\Users\Jake` then sees a bunch of stuff that doesn't belong there after that.

Move the miner to `C:\MPM` or something similar and I bet it will get rid of all your errors.

**Comment by sidwayz240sx** [comment]
You Sir are an absolute genius.  That was it, problem solved.  I owe you a beer 🍻

**Comment by grantemsley** [comment]
Glad I could help!
