### ISSUE TITLE
Excavator doesnt get terminated

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#1576]
Tried today commit d8f455d and im still getting the error where Excavator doesnt get terminated. Its window keeps running when a new miner gets launched, casing obvious problems.

Am i the only one getting this behavior?

**Comment by aaronsace** [comment]
Why does leaving the window open cause problems?

**Comment by titvs** [comment]
@aaronsace MPM starts benchmarking Excavator (ExcavatorNvidia1 and ExcavatorNvidia2), it finishes and tries to terminate the miner but Excavator doesnt terminate (the miner window is still there and it shows the miner still running). Then MPM launches another miner on the next cycle, say, Ccminer, and im getting 2 miners running at the same time.

I have Excavator 1.4.4a. Should i update it to the newer version that, allegedly, only work with Nicehash?

**Comment by aaronsace** [comment]
It's the correct version but why does leaving the window open cause problems? Are there any problems?

**Comment by titvs** [comment]
Well, im getting two miners running simultaneously on the same hardware. Excavator and other one that is launched because Excavator isnt terminated.
Can you have 2 distinct miners running on the same GPU?

**Comment by aaronsace** [comment]
@titvs You are using the new code with the Excavator API; the Excavator **window** is not meant to close: https://github.com/MultiPoolMiner/MultiPoolMiner/commits/master

**Comment by grantemsley** [comment]
If I'm understanding the new excavator API properly:

- The first time excavator is started, it will launch the miner process, then add workers to it.
- When the script switches away from excavator it stops those workers but leaves the actual excavator program open permenantly (at least until the miner script is closed)
- If the script switches back to excavator, it will add new workers to the existing excavator program

Does that sound about right @aaronsace?

I guess that makes it faster to switch between pools on excavator, since you don't have to restart the entire program.  It shouldn't consume much resources while it sits idle.

**Comment by titvs** [comment]
@aaronsace @grantemsley Ok guys, ive been benchmarking Excavator with the new API and as aaron said, its window keeps open and excavator.exe running. 
It benchmarked the algos that were associated with it without the window closing. It only returned this error:

```
INFO: Starting miner (ExcavatorNvidia1): 'C:\MPM_NR\Bin\Excavator\excavator.exe [{"id":1,"method":"algorithm.add","params":["blake2s","185.177.113.20:5766","LeGKa3K1NHzeDuuW5mcV8kbhX82ENRjGvC:miner01,c=LTC"]},{"id":1,"method":"workers.add","params":["alg-0","0","alg-0","1","alg-0","2","alg-0","3","alg-0","4"]}]'
'Id' is a ReadOnly property.
At C:\MPM_NR\APIs\Excavator.ps1:30 char:17
+             if ([Excavator]::Service.Id = $this.Service_Id) {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
'Id' is a ReadOnly property.
At C:\MPM_NR\APIs\Excavator.ps1:30 char:17
+             if ([Excavator]::Service.Id = $this.Service_Id) {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

INFO: Pinging monitoring server.
```
MPM then switched to other miners (CCminerSp and CCminerTpr) and they seem to work ok. On the Excavator window it keps saying its getting "New_Job" from all the algos it benchmarked (log below), but nothing else.

[Excavator-23456_2018-04-11_20-14-17.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1900249/Excavator-23456_2018-04-11_20-14-17.zip)

When excavator is sitting "idle" its consuming about 500 Mb of RAM. 

Is this the supposed behaviour Aaron?

Thanks.

**Comment by grantemsley** [comment]
Ah, that would explain some of the issues I've seen with it!
Those `=` are almost certainly supposed to be `-eq`.  Tricky powershell.

**Comment by titvs** [comment]
Well, today i noticed that excavator window was running and MPM called it to work on the Lyra2 algo with the following command line:

`Bin\Excavator\excavator.exe [{"id":1,"method":"algorithm.add","params":["lyra2rev2","185.177.113.20:4533","---------xxxx-----:miner01,c=LTC"]},{"id":1,"method":"workers.add","params":["alg-0","0","alg-0","1","alg-0","2","alg-0","3","alg-0","4","alg
                                            -0","0","alg-0","1","alg-0","2","alg-0","3","alg-0","4"]}]`

But on the excavator window it returned 0 Hashes...

@grantemsley Is it possible to go back to a previous commit? Seems a bit buggy this one. Do you need the logs?

Gonna remove Excavator from the miner list for the time being.

**Comment by titvs** [comment]
so, today i tried to do more testing with Excavator but it isnt working on my machine.
Today, MPM launched it with the following command:

`8-04-14 23:29:32 INFO: Starting miner (ExcavatorNvidia1): 'C:\MPM_NR\Bin\Excavator\excavator.exe [{"id":1,"method":"algorithm.add","params":["neoscrypt","185.177.113.20:4233","LeGKa3K1NHzeDuuW5mcV8kbhX82ENRjGvC:miner01,c=LTC"]},{"id":1,"method":"workers.add","params":["alg-0","0","alg-0","1","alg-0","2","alg-0","3","alg-0","4"]}]`

Its window was open and connected but for this algo its speed was zero.

Also noticed that the following error popped up:

'Id' is a ReadOnly property.
At C:\MPM_NR\APIs\Excavator.ps1:30 char:17
+             if ([Excavator]::Service.Id = $this.Service_Id) {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
'Id' is a ReadOnly property.
At C:\MPM_NR\APIs\Excavator.ps1:30 char:17
+             if ([Excavator]::Service.Id = $this.Service_Id) {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Im attaching Excavator log and i wonder if someone else is having problems with excavator...
[Excavator-23456_2018-04-14_20-59-27.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1911396/Excavator-23456_2018-04-14_20-59-27.zip)

**Comment by grantemsley** [comment]
@titvs I made a pull request I believe will fix that.

To test it out, you can replace APIs\Excavator.ps1 with the one from this link: https://raw.githubusercontent.com/MultiPoolMiner/MultiPoolMiner/c61363ea48583961555df420097ba8e94b21bacd/APIs/Excavator.ps1

That should get rid of the errors.

**Comment by titvs** [comment]
@grantemsley Already downloaded the file and now testing. I will notify here if any errors pop up.

Thanks!

**Comment by titvs** [comment]
Been testing all day now and it seems to be working properly. MPM launched Excavator several times with 2 different algos with no problems.
All seems fine at the pool also. Issue closed!
