### ISSUE TITLE
Incorrect Region.

### ISSUE THREAD

**Issue by Maddcow** [MultiPoolMiner/MultiPoolMiner#1579]
My region is set to US but recently i have noticed that MPM is doing a mixer of all three (US, Europe, and Asia) depending on what miner is running.

Anyone else or just me...

**Comment by boecht** [comment]
Need more details.
Some pools only have endpoints on one continent, so it is plausible you use them despite being in another region.

**Comment by Maddcow69** [comment]
![untitled](https://user-images.githubusercontent.com/6981893/38768820-3dfb7c22-3fc7-11e8-88dc-a1178f46b3ed.png)

**Comment by UselessGuru** [comment]
Could you try this and see if it fixes it?
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1580/files

**Comment by Maddcow69** [comment]
The screen shot is from after updating the files to those you listed. Been looking through MPM and your pulls for the most recent inorder to find a fix.

**Comment by Maddcow** [comment]
Same issue. Just redid my folder with your cryptonight fix pull (looks to be the most recent). Running it now...

**Comment by UselessGuru** [comment]
@Maddcow 

Please post logs and your start.bat.

**Comment by GUICenter** [comment]
Should be able to fix that with this in MiningPoolHub.ps1:
$MiningPoolHub_Regions = "europe", "us-east", "asia"
if ($MiningPoolHub_Regions = "us") { $MiningPoolHub_Regions = "us-east"}
and in MiningPoolHubCoins.ps1:
$MiningPoolHubCoins_Regions = "europe", "us-east", "asia"
if ($MiningPoolHubCoins_Regions = "us") { $MiningPoolHubCoins_Regions = "us-east"}

**Comment by UselessGuru** [comment]
> Should be able to fix that with this

Can you try this solution:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1580

**Comment by Maddcow** [comment]
I ended up deleting everything. Currently bench marking - I used 2.7.2.7 with current commits. I did make changes to algorithm.txt (cyrptonightv7), XMR-STAK (monaro7), and the us-east changes.

Will update once everything finished but so far everything is pointing to the correct region (us-east). Thanks for the help.

**Comment by grantemsley** [comment]
After some thorough investigation, it looks like this can happen on rare occasions if the pool stats get out of whack or if a particular host for the pool is acting up.  See my comments in #1580 for details.

Glad you got it all sorted out.
