### ISSUE TITLE
Constant System Wide Hangs. Any advice is greatly appreciated. 

### ISSUE THREAD

**Issue by munsterrr** [MultiPoolMiner/MultiPoolMiner#1583]
**PROBLEM**
I am lucky If I make it a few minutes before the system hangs or quits. If the MOBO/PSU doesnt shut the system down completely, It will simply hang. I have let it hang for hours without any luck of it coming back to "life". NiceHash Legacy will run for days without problem. MPM will give problems almost instantly. 

**BUILD:**
FX-8320 with Hyper X 212 Cooler
2x Asus Strix RX570 O4G Gaming (Elpida)
![image](https://user-images.githubusercontent.com/17898497/38844859-105ab3fc-41aa-11e8-9a92-7cc5b69c930d.png)

**I've tried:** 
-different MOBOs (ASUS M5A97 R2.0 & ASROCK 970M PRO3) 
-different thermal paste methods
-"milk crate" builds
-Inside a 350D with 5x case fans, 2xCPU fans, 

**SNIPPET OF MINING POOL HUB BAT FILE EDITS**
-region US -currency usd -type amd -poolname miningpoolhub -algorithm cryptonight,ethash,ethash2gb,equihash,groestl,lyra2re2,lyra2z,neoscrypt -donate 24 -watchdog -minerstatusurl https://multipoolminer.io/monitor/miner.php -switchingprevention 2"

start powershell -noexit -executionpolicy bypass -command "& .\reader.ps1 -log 'MultiPoolMiner_\d\d\d\d-\d\d-\d\d\.txt' -sort '^[^_]*_' -quickstart"

powershell -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/PowerShell-6.0.1-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

pause

**LOGS BELOW**
[MultiPoolMiner_2018-04-16_18-49-36.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1917928/MultiPoolMiner_2018-04-16_18-49-36.txt)
[PhoenixMinerAmd-23335_2018-04-16_18-26-49.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1917929/PhoenixMinerAmd-23335_2018-04-16_18-26-49.txt)

**Comment by thinkplaystudios** [comment]
Yup, I agree, definitely hardware/build related.  If you are using PCI-e risers, make sure the riser has its own power as well as the GPU attached.  The motherboard also has a power attachment for the PCI-e slots.

**Comment by psynauty** [comment]
Guys, he just said that nicehash legacy doesn't hang the system. So I'm sure he knows how to paper the cards and the risers. 
I have the same problem. 
It's not hw

**Comment by grantemsley** [comment]
Nicehash legacy doesn't use all the same miner programs.  Some push your system harder or stress different parts of the cards.  Just because some programs work doesn't mean it's not hardware.

But that's why I suggested using furmark to test it without any mining software involved at all.  To start with the simplest tests.

If you are sure your hardware is fine, start disabling miners one by one until you find the one(s) that are crashing your system.  Then try running those outside of MPM.  Then when it crashes, you can report it to the author of that miner and see if they can fix it, or just leave it disabled.

**Comment by psynauty** [comment]
Meant MPM hangs / pauses and doesn't recover. 
I've only had such shutdown with nicehash legacy 1900 alpha.

**Comment by grantemsley** [comment]
MPM hanging is a completely different issue than what @munsterrr described.

That does happen, and is probably an issue with the script - I've had it happen myself.  But it seems to happen infrequently, possibly due to some invalid pool responses, making it very difficult to diagnose and troubleshoot.

**Comment by psynauty** [comment]
I see what you are saying. 
BTW, I hate these MPM hangs and indeed it's impossible to troubleshoot. The way to resolve it is to have watchdogs that reset MPM when GPU usage drops below a threshold. That would do it.

**Comment by grantemsley** [comment]
@psynauty In my case, GPU usage stays high - the script freezes, but the miners are still running, its just not reporting its stats or switching anymore.  Adding anything to the script to monitor it won't help - the whole script freezes.

I am working on adding something to my launcher that detects when MPM's log file hasn't been written to for awhile and restart it though.

**Comment by psynauty** [comment]
@grantemsley let me know if you figure it out. It’s a shame it hangs like this and doesn’t recover. It forces me to keep checking the worker monitoring to see if the time since last seen has been longer than expected. Too much stress

**Comment by grantemsley** [comment]
Your issue sounds very different from what I am describing.  I have no system lockups or rebooting. No driver crashes. No performance issues. Just the script getting stuck at a certain point and needing to be closed and opened again.

The issues you describe are almost certainly hardware or driver issues.

**Comment by thinkplaystudios** [comment]
Yup it was all related to very aggressive OC settings and undervolting.

**Comment by paulpoco** [comment]
During all this why did he not mention the PSU size or what or amount of cards?
