### ISSUE TITLE
NiceHash removes CryptoNight and Nist5 algorithm from NiceHash Miner and NiceHash Miner Legacy

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1584]
> Important notice for buyers
> With this release, we are also removing the CryptoNight and Nist5 algorithm from NiceHash Miner and NiceHash Miner Legacy. Buyers are still able to buy hashing power for CrpytoNight and Nist5 algorithm on NiceHash marketplace - but the orders will only be fulfilled by ASIC miners. Buyers can now also buy all CryptoNightV7 based coins (Stellite - XTL) that were previously not operational due to rejected shares.

[source](https://www.nicehash.com/news/important-update-nicehash-miner-2-0-2-2)

So, CryptoNight and Nist5 are now ASIC territory at NiceHash.

**Comment by paulpoco** [comment]
I thought CryptoNightV7 was made so it doesn't work on ASIC ?

**Comment by grantemsley** [comment]
@paulpoco that's true, but the old cryptonight algorithm still exists, and some other coins use it.  Monero switch but all coins switched.
