### ISSUE TITLE
Qubit and Quark algorithms have negative accuracy

### ISSUE THREAD

**Issue by scolarita13** [MultiPoolMiner/MultiPoolMiner#1585]
Hi,

I have observed that two algorithms Qubit and Quark have the accuracy negative. It seems this prevents MPM to launch them. I mine in Zpool.
I have run them manually they seems to be fine.
Any reason why? can I do something about?
Thank you,
Scolaritza

**Comment by mkirov0** [comment]
IMHO if you reset profits for Qubit and Quark it will fix the accuracy issue.

**Comment by scolarita13** [comment]
How do I do that? running ResetProfit.bat or deleting profit files for Qubit and Quark?

**Comment by mkirov0** [comment]
For this particular issue just deleting the pool stats for qubit and quark will do, but if you want to reset all by running resetProfit you can.

**Comment by scolarita13** [comment]
Thanks. It worked.
