### ISSUE TITLE
Updating Miners questiion

### ISSUE THREAD

**Issue by izzledude** [MultiPoolMiner/MultiPoolMiner#1592]
Quick question is there a way to auto update all the miners?  Or manual update them all at once?

**Comment by izzledude** [comment]
I noticed some on the miners i have are out of date  so i did the URL change to the ones on the updated code page and i noticed the the accuracy changed and the speed  i just want to make sure i do it correctly and efficiently  so just looking for best practice

**Comment by izzledude** [comment]
So how do i have MPM download the miners on its own?  and whats the best way to manual download it?  Also im getting an error saying MPM is unable to update even though i have the latest release

**Comment by paulpoco** [comment]
Deleting Bin folder will not download newer versions of miners as those are hard coded in the files.

Like other say start over each time, just copy your Start.bat file over to the new version.
