### ISSUE TITLE
After "Update" Errors

### ISSUE THREAD

**Issue by izzledude** [MultiPoolMiner/MultiPoolMiner#1593]
On my previous post i asked how to update the miners. So what i did was erase the version i had and re downloaded MPM from the site and did a fresh install.  After this i noticed that i have a lot of status failed  which i didnt have before and dont have on any other rig after doing the same and the MultiPoolMiner  monitor worker shows it switching a ton of times 

   Status: Running

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 17 Minutes 10 Times Bin\CPU-JayDDee\cpuminer-avx2.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025 -u IzzleDude.Rancho -p x
0  H/s 00 Days 00 Hours 13 Minutes 7 Times  Bin\NVIDIA-Nanashi\ccminer.exe -a neoscrypt -o stratum+tcp://neoscrypt.mine.blazepool.com:4233 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6 -p Rancho,c=BTC

   Status: Failed

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 13 Minutes 9 Times  Bin\NVIDIA-KlausT\ccminer.exe -a neoscrypt -b 4068 -o stratum+tcp://neoscrypt.mine.blazepool.com:4233 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6 -p Rancho,c=BTC
0  H/s 00 Days 00 Hours 29 Minutes 15 Times Bin\CryptoNight-CPU\xmrig.exe --api-port 3334 -a cryptonight -o stratum+tcp://cryptonight.usa.nicehash.com:3355 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6.Rancho -p x --keepalive --nicehash --donate-level 1
0  H/s 00 Days 00 Hours 17 Minutes 10 Times Bin\CPU-JayDDee\cpuminer-avx2-sha.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025 -u IzzleDude.Rancho -p x
0  H/s 00 Days 00 Hours 16 Minutes 11 Times Bin\NVIDIA-SP\ccminer.exe -a skein -o stratum+tcp://skein.mine.blazepool.com:4933 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6 -p Rancho,c=BTC -b 4068
0  H/s 00 Days 00 Hours 05 Minutes 4 Times  Bin\CPU-JayDDee\cpuminer-aes-avx.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:20581 -u IzzleDude.Rancho -p x
0  H/s 00 Days 00 Hours 07 Minutes 4 Times  Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a skein -o stratum+tcp://skein.mine.blazepool.com:4933 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6 -p Rancho,c=BTC
0  H/s 00 Days 00 Hours 04 Minutes 3 Times  Bin\CPU-JayDDee\cpuminer-avx2-sha.exe -a cryptonight -o stratum+tcp://cryptonight.usa.nicehash.com:3355 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6.Rancho -p x
0  H/s 00 Days 00 Hours 05 Minutes 3 Times  Bin\CPU-JayDDee\cpuminer-avx2.exe -a cryptonight -o stratum+tcp://cryptonight.usa.nicehash.com:3355 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6.Rancho -p x
0  H/s 00 Days 00 Hours 06 Minutes 3 Times  Bin\CPU-TPruvot\cpuminer-gw64-avx2.exe -a cryptonight -o stratum+tcp://cryptonight.usa.nicehash.com:3355 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6.Rancho -p x
0  H/s 00 Days 00 Hours 00 Minutes 3 Times  Bin\CPU-TPruvot\cpuminer-gw64-avx2.exe -a neoscrypt -o stratum+tcp://neoscrypt.mine.blazepool.com:4233 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6 -p Rancho,c=BTC
0  H/s 00 Days 00 Hours 03 Minutes 3 Times  Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a neoscrypt -o stratum+tcp://neoscrypt.mine.blazepool.com:4233 -u 35YeLTQUN8DWpeFdq9aqxo5BCE8orx4uc6 -p Rancho,c=BTC

Miner                  Pool               Algorithm   Watchdog Timer
-----                  ----               ---------   --------------
CcminerKlaust          BlazePool          NeoScrypt   590 Seconds
CpuminerJayddeeAvx2sha MiningPoolHub      Lyra2z      766 Seconds
CpuminerJayddeeSse2    MiningPoolHubCoins Lyra2z      2,087 Seconds
CcminerNanashi         BlazePool          NeoScrypt   78 Seconds
FireiceCpu             NiceHash           CryptoNight 1,784 Seconds
CpuminerJayddeeAvx2    MiningPoolHub      Lyra2z      76 Seconds
CcminerSp              BlazePool          Skein       1,219 Seconds
XmrigCpu               NiceHash           CryptoNight 226 Seconds

**Comment by mkirov0** [comment]
Can you upload the log files?

**Comment by izzledude** [comment]
Is there a specific log or just the whole folder?

**Comment by grantemsley** [comment]
@izzledude A zip file of the whole folder would be best.

**Comment by izzledude** [comment]
[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1939270/Logs.zip)


They are uploaded now

**Comment by grantemsley** [comment]
I looked through the logs.  All the miners are closing after just a few seconds.

Possible causes:
- Antivirus
- Corrupt files
- Some other program closing the miners (I had this happen when using my launcher, which kills miners when they aren't supposed to be running)
- Faulty hardware

I'd try:

- Making sure windows defender and any third party antivirus you have are disabled
- Redownload the program
- Try running some of the miners manually - you can see the full command line to run in the MultiPoolMiner_date.txt log file - look for "Status: Failed". See if they run ok on their own.

**Comment by izzledude** [comment]
Would webroot cause it to fail? Is it possible to make it bypass ? 

If they run ok I'm there own what would it mean at that point?

**Comment by izzledude** [comment]
Is there a way to know what could shutting down the Miner?

**Comment by izzledude** [comment]
I'm a noob at running the Miner Solo.  Is it the exe apps in the bin folders?
