### ISSUE TITLE
Ahashpool announcement about how to use password right

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1596]
> Announcement: [2018-04-22 10:20 UTC] Recently, we've received some queries about workers not showing up at the wallet page. This is usually because the username (BTC address) and password (c=BTC) are not correct. Some mining programs (such as Claymore config files) use comma , as a delimiter. Therefore you must either put c=BTC in your password first (like c=BTC,ID=Rig01 or escape the delimiter (Claymore escaped comma is double comma). You must set the username and password correctly to receive any earnings. 

[https://www.ahashpool.com/](https://www.ahashpool.com/)

**Comment by grantemsley** [comment]
I'm fairly certain all the miners configured by MultiPoolMiner are already setting the password correctly.

If you have any examples where it doesn't, we can take a look at them.
