### ISSUE TITLE
MPM does not show PhoenixMiner as an option with NVIDIA 397.31 drivers

### ISSUE THREAD

**Issue by JamesJ-Yuan** [MultiPoolMiner/MultiPoolMiner#1598]
After installing the newest NVIDIA 397.31 drivers PhoenixMiner no longer shows up in the list of possible miners. Running the PhoenixMiner command manually still works. Rolling back to 391.35 drivers also works.

**Comment by grantemsley** [comment]
What card are you using?

The latest drivers have some issues that I happened to see in my news feed this morning: https://www.pcgamer.com/nvidias-latest-gpu-driver-is-causing-installation-headaches-for-some-gtx-1060-owners/

**Comment by JamesJ-Yuan** [comment]
It happens on my 1060 6GB and 1070 Ti. There were no issues installing the driver though.

**Comment by paulpoco** [comment]
These new drivers do not work on my 1070s

**Comment by jestercore** [comment]
Don't use these drivers, some 1060 didn't work at all with these. Use 391.35

**Comment by UselessGuru** [comment]
No problem with 397.64
