### ISSUE TITLE
pwsh.exe is consuming 100% system memory.. 

### ISSUE THREAD

**Issue by aaronsta1** [MultiPoolMiner/MultiPoolMiner#1617]
everything stops responding. it comes back when you close the window.

**Comment by UselessGuru** [comment]
Make sure you clean out your log folder.
What version of PWSH are you running?

**Comment by UselessGuru** [comment]
I cannot reproduce your problem... have you modified any pool or miner files?

To troubleshoot I recommend
1. Reboot your box
2. Remove all MPM logs (or put them aside)
3. Put all miner and pool files aside
4. Start MPM and check mem consumption. Note: It will say 'no pools available'
5. Bring back pool files one by one. Check mem consumption between each step. Note: It will say 'no miners available'
6. Bring back the miner files.

**Comment by aaronsta1** [comment]
i have done this already. the only files ive changed are the zpool and hashrefinery pool files as i put them to mine ltc instead of btc.

**Comment by UselessGuru** [comment]
@aaronsta1 
>> are the zpool and hashrefinery pool files as i put them to mine ltc instead of btc

You don't need to change the pool files, there is a config item available in config.txt.
See latest readme.

**Comment by aaronsta1** [comment]
i didnt see that.. i was reading here in the readme.txt
Q14. Is it possible to change the payout currency from BTC to something else when mining on yiimp-based pools such as Zpool, Hash Refinery, etc?
A14. Yes, advanced users can edit the currency settings in each pool file by amending the password field (c=BTC), however, this is not recommended as your payout will become uncertain as all other payout currencies are internally exchanged therefore you may end up losing your earnings due to pool never having enough coins to pay you!

its basically the same thing i did, just changed the username and password to ltc address and c=LTC

**Comment by aaronsta1** [comment]
quick question.. do you have to run pwsh.exe or can you run the script without it showing you whats going on in that window?

**Comment by UselessGuru** [comment]
Q14 is now obsolete, thanks for pointing it out.

I am referring to 'Advanced configuration -> https://github.com/MultiPoolMiner/MultiPoolMiner#to-change-payout-currency-of-a-pool
