### ISSUE TITLE
Cryptonight mining pools

### ISSUE THREAD

**Issue by jweber018** [MultiPoolMiner/MultiPoolMiner#1619]
Hey there, pretty substantial feature request: there is a pool called miner.rocks (that's the actual URL). It has support for various cryptonightv7 and cryptonight-heavy coins (MSR, XHV, LOKI) which are very profitable for AMD miners. The pool provides USD/kH/s data. Is there any chance it could be added to MPM?

TIA guys

**Comment by grantemsley** [comment]
From what I can see, it doesn't have an API intended for public use that we can use in the script.

**Comment by jweber018** [comment]
Damn, how could I have missed that? Sorry. I'll ask them if they can make the API and I'll create a new issue if it happens. Thank you guys.
