### ISSUE TITLE
Tried latest Master from May 9, CPU mining never happened even though it was set in start.bat

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1666]
[MultiPoolMiner_2018-05-09_20-19-34.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1990443/MultiPoolMiner_2018-05-09_20-19-34.txt)
[MultiPoolMiner_2018-05-09_22-00-57.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1990444/MultiPoolMiner_2018-05-09_22-00-57.txt)
[MultiPoolMiner_2018-05-09.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1990445/MultiPoolMiner_2018-05-09.txt)

**Comment by UselessGuru** [comment]
Could you please post the output of 
- http://localhost:3999/config
- http://localhost:3999/devices

**Comment by grantemsley** [comment]
Also, can you please post:

- What CPU and GPUs are in the system (including any integrated graphics)
- What drivers are installed for AMD, Nvidia and/or Intel graphics

**Comment by paulpoco** [comment]
Ryzen 7 1700 CPU
2 x Asus DUAL-GTX1070-O8G
Nvidia 391.35 driver

I have to check the output of those config and devices.

**Comment by grantemsley** [comment]
@UselessGuru  He probably doesn't have CPU OpenCL drivers.

You can download them separate from the AMD graphics drivers. Normally I'd link you right to AMD's site for them (https://developer.amd.com/amd-license-agreement-appsdk/ ), but it's broken right now, so here's a mirror: https://community.amd.com/external-link.jspa?url=http%3A%2F%2Famd-dev.wpengine.netdna-cdn.com%2Fapp-sdk%2Finstallers%2FAPPSDKInstaller%2F3.0.130.135-GA%2Ffull%2FAMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64.exe

If that fixes it, it means some systems don't show their CPU in the OpenCL device detection.  We should change that type filtering to always enable CPU if it was specified.  Miners don't actually need the OpenCL drivers.

That means Get-Devices will be unreliable for detecting CPU devices.  Which is probably fine.  They obviously have a CPU, even if it's not in the list.  Unfortunately that means we can't rely on OpenCL for detecting things like how many cores/threads the CPU has :(

**Comment by paulpoco** [comment]
After installing the AMD CPU openCL drivers, and running MPM again it started downloading the CPU miners.

**Comment by grantemsley** [comment]
@paulpoco yay!

While they are useful, they shouldn't actually be required.  We'll fix that.

**Comment by UselessGuru** [comment]
> they shouldn't actually be required. We'll fix that.

There have been issues in the past when there were no CPU drivers were installed, e.g. 
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/890
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/862
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1191
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1195

So I think it is best to keep OpenGL a prerequisite. I'll add it as requisite to the readme.

**Comment by UselessGuru** [comment]
@paulpoco 
Could you please upload the working http://localhost:3999/devices for comparison. TIA!

**Comment by grantemsley** [comment]
@UselessGuru @paulpoco I can do that, I have a system that works and a system that doesn't (before not filtering CPUs)
[workingdevices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1994097/workingdevices.txt)
[notworkingdevices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1994098/notworkingdevices.txt)

They both have skylake processors, working one has nvidia+amd, notworking only has nvidia.

The OpenCL for CPU seems to come automatically with AMD drivers, but not for NVIDIA.

.

**Comment by UselessGuru** [comment]
> The OpenCL for CPU seems to come automatically with AMD drivers, but not for NVIDIA.

interesting find 🥇

**Comment by paulpoco** [comment]
[devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2003455/devices.txt)
Sorry so late,

**Comment by grantemsley** [comment]
That's from after installing those Open CL drivers, right?

In any case, this should be fixed in the recent changes, with or without those drivers.
