### ISSUE TITLE
Repeating algos in Algorithms.txt

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#1676]
Im confused with the new Algorithms.txt. There are coins and algorithms referring to the same coin/algo. Are the itmems listed by coin or by algo?
How are x17, xvg-x17, and verge-x17 different?
> "x17":  "X17"
"xvg-x17":  "X17"
"verge-x17":  "X17"

I guess the better question is are these used somewhere?
>  "verge-blake2s":  "Blake2s",
    "verge-lyra2re2":  "Lyra2RE2",
    "verge-lyra2rev2":  "Lyra2RE2",
    "verge-lyra2v2":  "Lyra2RE2",
    "xvg-blake2s":  "Blake2s",
    "xvg-lyra2re2":  "Lyra2RE2",
    "xvg-lyra2rev2":  "Lyra2RE2",
    "xvg-lyra2v2":  "Lyra2RE2",

**Comment by UselessGuru** [comment]
Algorithm.txt is a mapper to map different algo/currency/coin names to one common name.
The Get-Algorithm function is used widely in MPM to normalize the variations of names.

> I guess the better question is are these used somewhere?

They might be - or have been - It is up to the pool operators and miner developers to introduce or remove new types.

**Comment by mkirov0** [comment]
I see. That explains it. Thanks!
