### ISSUE TITLE
Problems with downloading miner binaries

### ISSUE THREAD

**Issue by Pandoraaaaa** [MultiPoolMiner/MultiPoolMiner#1679]
Hi, I'm somewhat of a noob, so sorry if I'm wasting anybody's time with this. I've downloaded master and I'm running Get-Binaries.ps1 to get everything set up. It is really working great except for two miners that are giving me error as follows:

WARNING: CcminerNevermore - incorrect version installed, delete .\Bin\NVIDIA-Nevermore directory and redownload - got
913DBACE37949F2BB718E3C57C9A080C3040454E5D4E27244E1CB2F785DFD9AF, expected
62489722C44CDAD3DF4C22E46A2A16A3E8A81E273D562C7C25398F77684A1C11

and this one

Downloading ClaymoreAmd2gbKeccak40 from https://github.com/MultiPoolMiner/miner-binaries/releases/download/ethdcrminer64/Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal_Blake2s_Keccak.AMD.NVIDIA.GPU.Miner.v11.7.-.Catalyst.15.12-18.x.-.CUDA.8.0_9.1_7.5_6.5.zip...
WARNING: Failed to download ClaymoreAmd2gbKeccak40 - download manually from
https://github.com/MultiPoolMiner/miner-binaries/releases/download/ethdcrminer64/Claymore.s.Dual.Ethereum.Decred_Siacoi
n_Lbry_Pascal_Blake2s_Keccak.AMD.NVIDIA.GPU.Miner.v11.7.-.Catalyst.15.12-18.x.-.CUDA.8.0_9.1_7.5_6.5.zip and extract to
 .\Bin\Ethash-Claymore\EthDcrMiner64.exe

I'd like to fix both errors and get a clean setup before I run the benchmarking, also I have to deal with all the antivirus exclusions first. Anyway, the second error for ethdcrminer64 is especially important because I have this test rig (nvidia) pointing to nicehash and the most profitable has been dual mining with Pascal. That binary wants to go into a lot of folders, I guess one for each coin, so I'd like to get the downloader happy and not try to do it all by hand.

Any help/advice is much appreciated! -P

**Comment by UselessGuru** [comment]
> delete .\Bin\NVIDIA-Nevermore

Did you delete it as told? What happened after?

> Downloading ClaymoreAmd2gbKeccak40 from https://github.com/MultiPoolMiner/miner-binaries/releases/download/ethdcrminer64/Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal_Blake2s_Keccak.AMD.NVIDIA.GPU.Miner.v11.7.-.Catalyst.15.12-18.x.-.CUDA.8.0_9.1_7.5_6.5.zip

That link is perfectly fine. If it does not work for you then you have a local problem. Workaround: Download and extract manually.

> That binary wants to go into a lot of folders

Nope, it should only go to Bin\Ethash-Claymore

**Comment by grantemsley** [comment]
The hash for nevermore is incorrect.  Not sure how that happened - I probably made a copy/paste error.  You can safely ignore that error for the moment, I will get it fixed.

For Claymore having issues downloading - I had that too on some systems.  Had to disable my antivirus completely while it was downloading - the exclusions didn't cover files being downloaded, so the antivirus was still stopping it.  Perhaps that's your problem as well?

**Comment by UselessGuru** [comment]
@grantemsley 

I think the long filename of ClaymoreDual could be a problem. 
It may not be related, but when comparing ClaymoreDual miner files the line containing the filename always gets marked as being different in GIT (ever though it is identical). WTF???

**Comment by grantemsley** [comment]
@uselessguru could be, if the path you have multipoolminer running from is already really long. Windows sometimes does weird things when paths get over around 250 characters, and that filename is 142 by itself.


I'll test it myself with a long path to the install folder and see what happens.
If that is the problem, we can rehost it with a shorter filename.

**Comment by grantemsley** [comment]
The long file name doesn't seem to cause any issues for me.  Tested on windows 10, might be different on 7 though:

<pre>
PS E:\reallylongpath\noimeanreallylong\reallyreallyreallylong\solongwindowsdoesntlikeit\especiallywithfilesthatalsohavereallylongnames\keepgoing\wewillmakeitlongenougheventually\arewethereyet\wearethere\grantmpm> .\Get-Binaries.ps1


WARNING: CcminerNevermore - incorrect version installed, delete .\Bin\NVIDIA-Nevermore directory and redownload - got 913DBACE37949F2BB718E3C57C9A080C3040454E5D4E27244E1CB2F785DFD9AF, expected 62489722C44CDAD3DF4C22E46A2A16A3E8A81E273D562C7C25398F77684A1C11
Downloading ClaymoreAmd from https://github.com/MultiPoolMiner/miner-binaries/releases/download/claymorecryptonoteamd/Claymore.CryptoNote.AMD.GPU.Miner.v11.3.-.POOL.-.Catalyst.15.12-18.x.zip...
Downloading ClaymoreAmd from https://github.com/MultiPoolMiner/miner-binaries/releases/download/zecminer64/Claymore.s.ZCash.AMD.GPU.Miner.v12.6.-.Catalyst.15.12-17.x.zip...
Downloading ClaymoreAmd from https://github.com/MultiPoolMiner/miner-binaries/releases/download/ethdcrminer64/Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal_Blake2s_Keccak.AMD.NVIDIA.GPU.Miner.v11.7.-.Catalyst.15.12-18.x.-.CUDA.8.0_9.1_7.5_6.5.zip...
Downloading ClaymoreAmd from https://github.com/MultiPoolMiner/miner-binaries/releases/download/neoscryptminer/Claymore.s.NeoScrypt.AMD.GPU.Miner.v1.2.zip...
PS E:\reallylongpath\noimeanreallylong\reallyreallyreallylong\solongwindowsdoesntlikeit\especiallywithfilesthatalsohavereallylongnames\keepgoing\wewillmakeitlongenougheventually\arewethereyet\wearethere\grantmpm>
</pre>

**Comment by UselessGuru** [comment]
> Can you link an example?

No link. I just spottet the looney:
**$Uri** = "https://github.com/MultiPoolMiner/miner-binaries/releases/download/ethdcrminer64/Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal_Blake2s_Keccak.AMD.NVIDIA.GPU.Miner.v11.7.-.Catalyst.15.12-18.x.-.CUDA.8.0_9.1_7.5_6.5.zip"
**$URI** = "https://github.com/MultiPoolMiner/miner-binaries/releases/download/ethdcrminer64/Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal_Blake2s_Keccak.AMD.NVIDIA.GPU.Miner.v11.7.-.Catalyst.15.12-18.x.-.CUDA.8.0_9.1_7.5_6.5.zip"

My bad.

**Comment by grantemsley** [comment]
@UselessGuru An, so the lines ARE ever so slightly different.  That makes sense.

Sometimes git is good about showing the specific changes in a line, sometimes not.  I don't use github desktop so I'm not sure how well it handles such things.

**Comment by mkirov0** [comment]
It is probably the long filename. I had issues installing on an old Win7 system where  I downloaded the file outside MPM, but still I couldn't unzip before shortening the name.

**Comment by Pandoraaaaa** [comment]
Thanks for all the comments, I am learning from your conversation. :)

Thanks for pointing out that the destination was only a single folder, I downloaded and extracted by hand as you suggested. 

The path to mpm was on my desktop and the folder name included a blank space "mpm gpu2" so I thought that space might be a problem. I turned off bitdefender av and renamed the desktop folder to mpm and started the benchmarking. There was still an error message about downloading, so the removal of the blank space did not fix that error message.

I did extract the miner manually to Ethhash-Claymore and mpm went looking for it and seems everything is working. I wonder if any of you are running without antivirus software as I am now?

**Comment by Pandoraaaaa** [comment]
Oh, forgot to add that I retrieved the latest, greatest from master before I started anything else this morning.

**Comment by grantemsley** [comment]
Spaces in the path will sometimes cause problems.

Most of us are running without antivirus or with a lot of exceptions made in our antivirus.  It sucks AV companies treat miner programs the same as viruses but that is the way it is.

**Comment by Pandoraaaaa** [comment]
Concur!

It's possible to get bitdefender running with mpm, I've done it more than once. SO much hassle though.

But that is why mpm is so great, because it pulls in so many miners.

**Comment by Pandoraaaaa** [comment]
I noticed that the start.bat file only lists three pools, nicehash, miningpoolhub, zpool. I don't have an account at zpool, so I'm very curious if the benchmarking will show it to be worthwhile.

But I'm also curious about all those other pools that the software supports - are they just less important in the big scheme of things?

**Comment by grantemsley** [comment]
@Pandoraaaaa The only pool that requires an account is MiningPoolHub.  The rest don't require signup at all, you just mine with your bitcoin address and they pay out to that.

The default only enables a few pools because people with only one or two cards mining probably don't want their profits split across a bunch of pools and have it take months to reach the payout threshold on any of them.  If you are patient, you can enable more pools to have potentially better profits.

Personally, I use: AHashPool, Hashrefinery, Miningpoolhub, and zpool.  Sometimes I enable nicehash and zergpool as well.

**Comment by Pandoraaaaa** [comment]
Ok, thanks for the clear explanation. 

Do guys have a discord channel? Would love to chat more...

**Comment by UselessGuru** [comment]
> Do guys have a discord channel? Would love to chat more...

No, we don't. We do not have to resources to go beyond this repository. Sorry.

**Comment by Pandoraaaaa** [comment]
Hey that's no problem for me. I just didn't want to muddy the waters around here unintentionally.
