### ISSUE TITLE
Claymore's Dual "-y" option

### ISSUE THREAD

**Issue by jestercore** [MultiPoolMiner/MultiPoolMiner#1699]
> -y   enables Compute Mode and disables CrossFire for AMD cards. "-y 1" works as pressing "y" key when miner starts. This option works in Windows only.

I think MPM need this parameter set by default

**Comment by UselessGuru** [comment]
> I think MPM need this parameter set by default

It is already implemented in the pending ClaymoreDual miner 
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1658

Please test it and report back in the PR thread. TIA!

**Comment by UselessGuru** [comment]
Now in latest zip file.
Got implemented and commited in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1658

**Comment by jestercore** [comment]
I want need release sooo baaadly
