### ISSUE TITLE
Broken with Nvidia?

### ISSUE THREAD

**Issue by aaronsta1** [MultiPoolMiner/MultiPoolMiner#1703]
so i went to fire up my 1080.. i dont run it very often.. and when i did i got this.

```
ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\Aaron\Documents\Miner\MultiPoolMinerV2.7.2.7 (1)\MultiPoolMiner.ps1:289 char:85
+ ... fig.Type.Count -eq 0 -or (Compare-Object $Config.Type $_.Type -Includ ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
```

i thought maybe some files got broke, so i downloaded it again and ran start.bat without changing anything and it still does it.

**Comment by UselessGuru** [comment]
You are not running the latest code.... Line 289 is different now.
I recommend you use https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

The error you are getting comes from a broken file in the 'Miners' folder.
Have you edited a miner file to add/remove some algorithms? Has the editor created a .bak file?
Make sure you only keep original MPM files int the folders 'Miners' and 'Pools'.

**Comment by aaronsta1** [comment]
i went here and downloaded the newest release? 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases

ill try the master.zip

**Comment by mkirov0** [comment]
I think I know what happened... Looking into it now...

**Comment by mkirov0** [comment]
Still trying to reproduce the problem

**Comment by aaronsta1** [comment]
the master.zip seems to work.

**Comment by mkirov0** [comment]
Do you still have the logs from the previous run? If you can upload it would be awesome.

**Comment by aaronsta1** [comment]
no i deleted the folder when i re downloaded it.. it was really just that line over and over and over in red.
im guessing the release needs updated to the new master..

**Comment by mkirov0** [comment]
I see. I was just afraid I broke something with the miner algo updates yesterday...
I started a fresh copy too, and I am still downloading the miners will see what happens when its all finished.

**Comment by aaronsta1** [comment]
there is one problem with the master zip i downloaded.. from the link above.
ethash-claymore isnt extracting in the right folder.. its getting put into
Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal_Blake2s_Keccak.AMD.NVIDIA.GPU.Miner.v11.7.-.Catalyst.15.12-18.x.-.CUDA.8.0_9.1_7.5_6.5
instead of /bin/ethash-claymore

so it cant find the exe.

**Comment by UselessGuru** [comment]
> so it cant find the exe.
Then do as told. 
Rename the zip file and unpack manually to bin/ethash-claymore

**Comment by aaronsta1** [comment]
yeah i did that..

**Comment by UselessGuru** [comment]
What files are in bin/ethash-claymore now?

**Comment by aaronsta1** [comment]
all the right ones.. all i had to do was move the folder up one because like i said it auto extracted to that long folder name.

**Comment by UselessGuru** [comment]
Then delete the zip file with the long name from your system, and also delete the long folder name.
All set.

**Comment by gs1960** [comment]
Hello guys.
I had the same problem with line 289 in V2.7.2.7, so i followed the advice to download the master.zip, but now the problem is at 316:
[MultiPoolMiner_2018-05-15_14-57-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2005112/MultiPoolMiner_2018-05-15_14-57-24.txt)
I dont understand much, can anyone help me, please?

**Comment by mkirov0** [comment]
Hmmm I downloaded the master and benched for a day and couldn't reproduce the problem. There was an issue in the first 5 min, but followed UselessGuru's directions (unzip in ./Bin/Ethash-Claymore and delete the long named folder) and after that ran without problems for a day. Still have 12 miners to bench 😄

**Comment by UselessGuru** [comment]
For those with problems with ClaymoreDual:

Please download the new miner versions from here:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1658

@gs1960

You have anon-original file in the Miners folder.
Pls remove ALL miner files and restore one by one until you've found the culprit. Make sure you do not have *.bak files or similar in there,

**Comment by gs1960** [comment]
Sorry, but I'm really stupid on the subject ....
I deleted everything with the name Claymore in the MINERS folder, but I always have the same error.
Then .... I have deleted all the files in the MINERS folder, but as soon as I add any file into this folder I get the error again....without miners too
Also I have an OpenCL error on startup ....
[MultiPoolMiner_2018-05-15_16-37-16.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2005421/MultiPoolMiner_2018-05-15_16-37-16.txt)

**Comment by gs1960** [comment]
Thank's @mkirov0 
Yes, i restarted...  
The PowerShell is the last.
I dont undestand really nothing about.....i'm fully newbie...excuse me..
I deleted all files in MINERS, then i add any file from the old folder MINERS and i have the error

**Comment by UselessGuru** [comment]
Start MPM, wait for the problem to occur, then post the contents http://localhost:3999/debug

**Comment by mkirov0** [comment]
> i add any file from the old folder MINERS 

Probably would have been a better idea to add the miners from here:
https://github.com/MultiPoolMiner/MultiPoolMiner/tree/master/Miners
UGuru will fix it!

**Comment by gs1960** [comment]
Sorry but how do I download the files?
I get this .....
[BMiner.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2005944/BMiner.txt)

**Comment by mkirov0** [comment]
That was just an odd comment. Just do as UslessGuru said.

**Comment by UselessGuru** [comment]
@gs1960 
> Sorry but how do I download the files?
I get this .....

Since you never got MPM to start properly I suggest you start from scratch (delete all MPM files).
The latest ZIP file contains the updated ClaymoreDual miner with a shorter DL path as well as some other bug fixes and performance enhancements.

**Comment by gs1960** [comment]
@UselessGuru thank you!
"delete all MPM files" do you mean delete the folder MultiPoolMiner, or i must do anything else?
"The latest ZIP file" do you mean the 2.7.2.7 or MASTER?
I deleted all, then i tried with the both version....
_2.7.2.7 error 289
_MASTER error OpenCL at the start and then error 316

Where i must locate the folder?On the desktop it's right?

**Comment by UselessGuru** [comment]
Start from scratch - delete the entire MPM folder.
It is recommended to install (unpack) MPM to the desktop.
Use these files: https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

Start MPM, wait for the problem to occur, then post the contents http://localhost:3999/debug

If you are getting an OpenGL error then reinstall you graphic drivers. Also see
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/862

**Comment by gs1960** [comment]
@UselessGuru 
Hi Dear, i solved the OpenCL issue with your last advice, thang you very much!
Now the miner work.

I have a last question.
Today i change the grafic card and installed a GTX970.
I deleted the old MPM folder and restarted from scratch.
MPM benchmark only 11 miners, instead  more than 100 of yestarday and seem that the GPU dont work and work only the CPU.
I must reset anything else? Or the MPM will learn the changes alone and will make work later the GPU?
With the old GPU (NVIDIA QUADRO FX4600) i received errors for missing nvidia driver, but now nothing.
In the system monitor of pc i see the cpu at 100%, but GPU 0%.....maybe i must wait the end of benchmarking?

Thank you again and excuse me for my bad english!

**Comment by gs1960** [comment]
I tried MPM 2.7.2.7 and it makes me work the GPU.
However, when GPU started at 100% with CPU over 100% (!!!) I had the black screen and I had to reset the pc.
So in the "start-miningpoolhub.bat" I also deleted CPU and left only nvidia.
Restarted and we are going to see.

Thanks again for the moment!

**Comment by gs1960** [comment]
Nothing to do .... when the GPU starts working at 100% the temperature rises above 90°C and the graphics card goes out.
PC on but black screen and card turned off .... I have to reset the PC.
Some advice?
Is it possible to limit the workload for the GPU to 60/70%?

**Comment by mkirov0** [comment]
@gs1960 
Depending on the manufacturer you can download a tool that allows you to do that. Just visit the manufacturer's website and download it from there.

**Comment by gs1960** [comment]
Thanks @mkirov0 
Yes i have uninstalled all old drivers.
Could it be the poor PSU?
I have installed a supplementary PSU (with add2psu) only for the GPU, but is a chinese PSU 625W by 30 $.
Could it be in crisis when the GPU is 100%?

**Comment by gs1960** [comment]
Hi guys, thank You.
Now it work.

For the high temperatures i replaced the thermal compound of the GPU and now it's much better.

I have another question.....
I have some miners with good benchmark and some with low hashrate.
Why the MPM choose always Bminer and DSTM, that have the lowest HR and dont privilege the miners with higher HR?
![immagine](https://user-images.githubusercontent.com/37365706/40623055-2c6a3d26-62a5-11e8-8a8d-08c3cab47123.jpg)
In this mode i have lower production of coins, or it's the same because MiningPoolHub adopting PPLNS system?
To use the better miners i must delete BMiner (and DSTM) from the folder MINERS.

Sorry, but i'm newbie and i try to understand....

**Comment by UselessGuru** [comment]
> I have some miners with good benchmark and some with low hashrate.

Profit is the keyword here. Also see https://github.com/MultiPoolMiner/MultiPoolMiner#general-overview

Hashrate is just a part of the following equation:

Profit = Hash rate * Price per hash 
Hash rate:
The hash rate is the number of hashes you computer can do per time unit.
Not all algorithms are equally fast, that's why you get different numbers. For the **same algorithm** the miner with the highest hash rate is the best.

Price per hash:
The pools pay per share you calculated and submitted to the pool (= your part of the work done at the pool until it found a block). The higher the difficulty for finding a block the more hashes are needed to find a block -> each share pays less less
Not all coins pay the same for a share. Check the pool webpages on this.

MPM retrieves the pricing information (how much will I get paid for a share of coin X?)

> To use the better miners i must delete BMiner (and DSTM) from the folder MINERS.

No need to delete anything. By doing so you deprave MPM from mining the most profitable combination.

**Comment by gs1960** [comment]
@UselessGuru You are a Big! Thank You very much!
You have a beer paid.
I start to understand...i dont have to worry about low hashrate, because MPM knows what it does.
It's just the same if i launch start, or start-MiningPoolHub?.....my worker is on MPH.
