### ISSUE TITLE
update CcminerAlexis.ps1 

### ISSUE THREAD

**Issue by nemosminer** [MultiPoolMiner/MultiPoolMiner#1714]
https://github.com/nemosminer/ccminerAlexis78/releases

https://github.com/nemosminer/ccminerAlexis78/releases/download/Alexis78-v1.1/ccminerAlexis78-v1.1.7z

added keccakc algo so you can also delete : CcminerCornzKeccakC.ps1

**Comment by UselessGuru** [comment]
> added keccakc algo so you can also delete : CcminerCornzKeccakC.ps1

https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1716
