### ISSUE TITLE
no kernel image? CcminerSuprminer

### ISSUE THREAD

**Issue by platinumdubs** [MultiPoolMiner/MultiPoolMiner#1715]
[CcminerSuprMiner-4068_2018-05-14_00-14-20.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1999442/CcminerSuprMiner-4068_2018-05-14_00-14-20.txt)
anyone else having this issue with ccminersuprminer I'm not sure exactly what the issue is here. I looked to see if someone else was having the same issue but couldn't find any other post.

**Comment by UselessGuru** [comment]
The executed command line would be very helpful for troubles & shooting :-)

**Comment by platinumdubs** [comment]
my bad, (CcminerSuprMiner): 'C:\Users\plati\Downloads\MultiPoolMinerV2.7.2.7\Bin\NVIDIA-SuprMiner\ccminer.exe -a lyra2v2 -o stratum+tcp://us-east.hub.miningpoolhub.com:20507 -u fonyo.multipoolminer -p x this is the current command line. I deleted all my folders and downloaded everything again and am currently benchmarking everything I thought that would fix the no kernel image but obviously hasn't

**Comment by platinumdubs** [comment]
just noticed that same exact issue with ccminernevermore as well

**Comment by UselessGuru** [comment]
I assume you get the same error when you run the miner outside MPM.
If so you better ask the miner developers for help.

**Comment by platinumdubs** [comment]
yes I get the error outside MPM as well I'll hit up the developers then thanks
