### ISSUE TITLE
update CcminerAlexis.ps1

### ISSUE THREAD

**Issue by nemosminer** [MultiPoolMiner/MultiPoolMiner#1723]
https://github.com/nemosminer/ccminerAlexis78/releases

https://github.com/nemosminer/ccminerAlexis78/releases/download/Alexis78-v1.2/ccminerAlexis78v1.2x32.7z

added polytimos algo so you can also delete : CcminerPolytimos.ps1

"hsr" = "" #Hsr
"poly" = "" #Poly
"blake2s" = "" #Blake2s
"veltor" = " -i 23" #Veltor
"keccak" = " -m 2 -i 29" #Keccak
"keccakc" = " -i 29" #Keccakc
"lbry" = "" #Lbry
"lyra2v2" = " -N 1" #Lyra2RE2
"nist5" = "" #Nist5
"skein" = "" #Skein
"c11" = " -i 21" #C11
"x11evo" = " -N 1 -i 21 " #X11evo
"x17" = " -i 20" #X17

**Comment by angelics** [comment]
MPM 1.1 had neoscrypt included, instant crash on my rig. plz test and exlcude it

**Comment by UselessGuru** [comment]
Thank you nemos!

Implemented in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1730

Neoscrypt disabled
