### ISSUE TITLE
Unable to get Cryptronite to work

### ISSUE THREAD

**Issue by izzledude** [MultiPoolMiner/MultiPoolMiner#1729]
Ive looked through reddit and through the issues page on how to get it to work correctly ive tried everything from what i read and i still cant seem to get it to even start bench marking it.  If anyone has a link to a crash course or the simplest way as all the things i found seem to over complicate it and just gets confusing. Any advice is appreciated.

**Comment by grantemsley** [comment]
The latest release does not have cryptonight working.  Please make sure you are using the master branch - https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

**Comment by grantemsley** [comment]
Mostly the same, but there are some configuration changes you might want to use.  Read through the readme.txt file for details.  A lot of new features have been added since the last release.

**Comment by izzledude** [comment]
Ok I'll try this today.  And it's the start.bat file not the multipoolminer.bat right

**Comment by izzledude** [comment]
Is there any way you could post the readme file so I can download that one.  In at work and want to get a jump start by reading it

**Comment by UselessGuru** [comment]
> And it's the start.bat file not the multipoolminer.bat right

There is no multipoolminer.bat.

> Is there any way you could post the readme file 

It is in the MPM directory. readme.txt
