### ISSUE TITLE
New Zealot Enemy 1.10

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#1743]
A new version is out! I am testing on my system and posting this here since its a mega link and I think it needs to be hosted on the MPM rep first. Will post results when I have them

https://bitcointalk.org/index.php?topic=3378390.0

**Comment by grantemsley** [comment]
@mkirov0 Go ahead and make a PR for it if you don't mind.  I can change the link after the PR is posted.
