### ISSUE TITLE
Large number of broken miner configs

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1745]
I have a couple of faulty miners relating to miningpool hub.

MiningPoolHubCOins_Cryptonight7_XXX_CPU.txt
  "pool_list": [
    {
      "pool_address": "us-east.cryptonight-us-east.cryptonight-hub.miningpoolhub.com:20580",
      "wallet_address": "Kettoch.Guardian",
      "pool_password": "x",
      "use_nicehash": true,
      "use_tls": false,
      "tls_fingerprint": "",
      "pool_weight": 1,
      "rig_id": ""
    }

That pool address cannot be pinged and there are others showing the same thing.

**Comment by angelics** [comment]
refer #1739

**Comment by Kettoch** [comment]
Additional Miner errors
CPU-JayDDee\*.exe  -- Does not support cryptonight_v7 it says it is cryptonightv7
Cryptonight-fireice\ Files for miningpoolhubcoins_cryptonightv7 all have us-east.cryptonight-us-east.cryptonight-hub.miningpoolhub.com which is not a valid DNS address

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1750
