### ISSUE TITLE
Getting strange values for mining rates.

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1746]
2 1080 TIs should not get

Miner                                                     BTC                             USD                                       EUR
-----                                                     ---                             ---                                       ---
MultiPoolMiner                                            0.30015 ±204% (0.09872-0.91258) 2,467.60623 ±204% (811.59502-7,502.60949) 2,099.52460 ±204% (690.53307-6,383.47926)
{FireiceNvidia-CryptoNightV7, CpuminerJayddeeAvx2-Lyra2z} 1.01703 ±1% (1.00373-1.03050)   8,361.33688 ±1% (8,252.02854-8,472.09314) 7,114.11418 ±1% (7,021.11087-7,208.34943)

I also see a lot of these
ClaymoreNvidia2gbDecred100 {Ethash2gb, DecredNiceHash}   {49.64 MH/s, 1.68 GH/s} 0.00024319 {100%, -112,606%} {0.00475838, 0.00000415} {MiningPoolHubCoins-Musicoin, NiceHash}
ClaymoreNvidia2gbDecred130 {Ethash2gb, DecredNiceHash}   {43.21 MH/s, 1.90 GH/s} 0.00021350 {100%, -112,606%} {0.00475838, 0.00000415} {MiningPoolHubCoins-Musicoin, NiceHash}
ClaymoreNvidiaDecred100    {Ethash, DecredNiceHash}      {65.97 MH/s, 2.23 GH/s} 0.00044528  {99%, -112,606%} {0.00660894, 0.00000415} {MiningPoolHubCoins-Ethereum, NiceHash}
ClaymoreNvidiaDecred160    {Ethash, DecredNiceHash}      {65.46 MH/s, 3.54 GH/s} 0.00044731  {99%, -112,606%} {0.00660894, 0.00000415} {MiningPoolHubCoins-Ethereum, NiceHash}
ClaymoreNvidia2gbDecred160 {Ethash2gb, DecredNiceHash}   {65.81 MH/s, 3.56 GH/s} 0.00032793 {100%, -112,606%} {0.00475838, 0.00000415} {MiningPoolHubCoins-Musicoin, NiceHash}
ExcavatorNvidia1           DecredNiceHash                             10.22 GH/s 0.00004240         -112,606%               0.00000415 NiceHash
ExcavatorNvidia2           DecredNiceHash                             10.22 GH/s 0.00004240         -112,606%               0.00000415 NiceHash

**Comment by Kettoch** [comment]
The negative values for accuracy seem strange.

**Comment by mkirov0** [comment]
I dont really understand the question to be honest, but will try to give some info.
One way of fixing the negative accuracy is to run ResetProfits.bat. You can also go into the Stats folder and cherry pick the trouble makers and delete them. In your case I see DecredNicehash. I think there are already ASICs out for decred, so if you profit of ETH+DCR is lower than just pure ETH I'd disable decred altogether.

**Comment by UselessGuru** [comment]
There is an issue with decred / decrednicehash which I am working on a fix for.

Two options for now:
- ignore it - it won't do much harm
- exclude decred & decrednicehash algorithms in start.bat

**Comment by mserpell** [comment]
I'm getting similar issues.  I've tried resetting profits and benchmarks, but it hasn't helped.

![image](https://user-images.githubusercontent.com/5593748/40385497-18fb51bc-5e4a-11e8-8e5e-86c918a1dc57.png)

**Comment by UselessGuru** [comment]
Fixed with #1759
