### ISSUE TITLE
Monitor Window Broken?

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#1751]
Hi guys,

Getting this messages on the monitor window from the latest commit:

`2018-05-22 08:57:28 VERBOSE: CcminerSuprMiner: ["summary",{"value":[{"NAME":"suprminer"},{"VER":"1.5"},{"API":"1.9"},{"ALGO":"neoscrypt"},{"GPUS":"5"},{"KHS":"2748.92"},{"SOLV":"0"},{"ACC":"28"},{"REJ":"0"},{"ACCMN":"80.000"},{"DIFF":"12.362434"},{"NETKHS":"0"},{"POOLS":"1"},{"WAIT":"0"},{"UPTIME":"21"},{"TS":"1526975848|\u0000"}],"Count":16}]`

Same problem for other miners...

**Comment by aaronsace** [comment]
That's not a problem; it's very useful information.

**Comment by titvs** [comment]
Ok aaron. I'll take your word for it.. :P
