### ISSUE TITLE
How to exclude certain coins while mining do some coins wallets are in maintenance?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1762]
XMR, BTG, MONA are the ones at MPH that currently are in Maintenance mode.  I.e.  auto exchange will not occur until those wallets are back up again.

Like BTG uses Equihash but so does the zcoins, so cannot remove Equihash.

**Comment by UselessGuru** [comment]
Use the pool files from here:

https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1435
