### ISSUE TITLE
Feature Request: in -algorithm section add "_" in front of an algo when one wants to not use that algo

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1763]
Feature Request: in start.bat in -algorithm section add _ in front of an algo when one wants to not use that algo.  This would save erasing the algo, then later when you add it back again you just get rid of the _.

Example:
-algorithm _CryptonightV7,Ethash,Equihash,Groestl,Lyra2RE2,Lyra2z,MyriadGroestl,NeoScrypt,Quark,Qubit,Scrypt,Skein,X11,Yescrypt

The _CryptonightV7 would mean don't use.  This way you can remember what you didn't want to use but maybe in the future to decide to use that algo again.

I am not sure what characters you are allowed to use in bat files?

**Comment by UselessGuru** [comment]
@paulpoco 

There is no code change needed for what you want. Adding and underscore to an algo is basically invalidating the algo (because there will be no algo with such a name). Does it NOT work for you?

**Comment by paulpoco** [comment]
Never tried it
