### ISSUE TITLE
Suggestion : Move running/active miner to the bottom

### ISSUE THREAD

**Issue by thebeerbaron2018** [MultiPoolMiner/MultiPoolMiner#1764]
If you've been running for a while the list of idle miners grows and scrolls the active miner off the top of the screen which is not handy for quick checking on a view only VNC connection.  It would be handy to display in this order :  grid of coins > idle miners > failed miners > active miner > watchdog > profit - that way the active miner would always be at the bottom and visible

**Comment by paulpoco** [comment]
Right above the line that show how much more profitable MPM is, would be a good place for the Running Miners section.

**Comment by grantemsley** [comment]
This has been done in PR #1807
