### ISSUE TITLE
Multipoolminer fails after Windows 10 April update.  Power Shell issue?

### ISSUE THREAD

**Issue by DocRumple** [MultiPoolMiner/MultiPoolMiner#1767]
What needs to be reconfigured after the Windows 10 April update?  The blue miner window opens up but the main monochrome window is full of red errors.

**Comment by UselessGuru** [comment]
Logs would be nice.... my crystal ball is currently in maintenance.

**Comment by paulpoco** [comment]
Note to self:
Delay Windows 10 April Update
Delay Nvidia driver Update

**Comment by UselessGuru** [comment]
@paulpoco 

> Delay Windows 10 April Update
> Delay Nvidia driver Update

Why? Neither is causing problems (here).

**Comment by DocRumple** [comment]
Ok UselessGuru, love the name btw, let's see if you can be useful lol.  I have installed powershell 6.0.1 and also repaired it once.  When I use the command $PSVersionTable on PS ISE it says this is my version 5.1.17134.48.  I have reinstalled the latest Multipoolminer.  As soon as the dumb windows update happened I can't start my batch file to get the dual 1080ti's mining on miningpoolhub.  Even after reinstalling the above it doesn't work out of the box.

Here is the error that shows up in red on the initial monochrome screen which actually does load the batch file and act like it's going to start.  Category Info:  Invaliddata: [CompareObject],ParameterBindingValidationException  FullyQualifiedErrorId:  ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand.

CompareObject Cannot Bind Argument to Parameter "DifferenceObject" Because it is Null AtC:\Users\Doc\Desktop\Multipoolminer.PS1:289 char 85

**Comment by UselessGuru** [comment]
> I have installed powershell 6.0.1 and also repaired it once. When I use the command $PSVersionTable on PS ISE it says this is my version 5.1.17134.48.

This is irrelevant. ISE will look for the powershell version that comes with windows (5.x), where as pwsh is different product.
To be current MPM will try to install the latest offical pwsh release (6.0.2 as of today) even though it is   not yet a requirement for MPM. 

>it doesn't work out of the box.

As I said this has nothing to do with the Windows update.

There have been quite a number of changes to MPM, so I cannot tell where the problem is because I cannot see what exactly line 289 now is.

Try this:
Download the latest ZIP file (https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip) and install it to a NEW folder. 
If the error persists please zip the contents of the 'Logs' folder as well as the output of 'http://localhost:3999' and upload it here for analysis.

**Comment by Rimplestilhskin** [comment]
From my testing there is issues with the recent Nvidia drivers 397+ versions, even when half the opencl cuda etc is missing and being forced to install the "experience" funny business then some of this opencl ....  is again active.
Overclocking default apps also fails if the "experience" parts is not installed or even if installed works half way vs older drivers.

Nvidia is seriously trying to create a "DriverGate" 

Best option is to download DDU from guru3d or other trusted download sites, then boot into win 10 safe mode, run as admin DDU and auto uninstall the latest drivers. Restart and install last known good driver or repeat until you find a stable driver from Nvidia.

This worked for me and tested it on min. 5+ different NVM SSD's with different win 10 versions on each and all the same results. Above ?396? is unstable or could be earlier, happy with my downgraded 391.01-desktop-win10-64bit-international-whql

Next time I suggest using a usb win 10 version to boot, install latest drivers and test by using mining software on other internal HD / SSD's as this should nat affect your stable win 10 mining system.

You need a fast usb3+ stick, copy of win 10 iso and win2usb or rufus or similar that can create a live usb win 10 version.

**Comment by nagabasha** [comment]
![image](https://user-images.githubusercontent.com/39555871/40882975-97a3fc12-670f-11e8-9209-e7556e01e1e5.png)
can any one help me to solve this error?
in this which username we have to give

**Comment by yuzi-co** [comment]
@nagabasha there is an problem with hands.dll
but seriously, read the error... you need space between "multipoolminer.ps1" and "-username"

**Comment by nagabasha** [comment]
Thank you.

**Comment by nagabasha** [comment]
![image](https://user-images.githubusercontent.com/39555871/40907543-d3ff8a30-6801-11e8-8f34-b0437df65bf0.png)
can any one help me to solve this error?
in this which username we have to give

**Comment by UselessGuru** [comment]
@nagabasha 

What has this error to do with the thread title? Please do not mix issues - thank you!

You are using an old version of MPM.
As the message says is a problem with the miner download uri. 
Please use the latest Zip file: https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip
