### ISSUE TITLE
New Master from today, gets an error message saying it doesn't know where pwsh is.

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1779]
New Master from today, gets an error message saying it doesn't know where pwsh is.
![screenshot_1](https://user-images.githubusercontent.com/801414/40636237-efe37e5e-62b2-11e8-8831-be08385cf35a.png)

**Comment by paulpoco** [comment]
added C:\Program Files\PowerShell\6.0.2 to PATH

This was never a problem before.  Weird

**Comment by angelics** [comment]
kwn problem for 6.0.2 at least for me. im nt 100% sure if 610p2 fixed it, but they do include checkbox for environment variable

**Comment by UselessGuru** [comment]
Do not use  610p2 - it is broken.
