### ISSUE TITLE
Latest Master Pool Warning

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#1780]
Downloaded today the new master and seems to be working but im getting these errors:

2018-05-29 10:01:35 VERBOSE: Pool Balance API (MiningPoolHub) has failed - no API key specified.
2018-05-29 10:01:35 VERBOSE: Pool Balance API (ZergPool) has failed - no wallet address specified.

Im running MPM with MiningPoolHub and BlockMasters, with ZergPool defined on the -excludepoolname switch.

**Comment by UselessGuru** [comment]
Fixed with #1781

**Comment by titvs** [comment]
Great!

**Comment by titvs** [comment]
Testing now. Seems ok. But @UselessGuru you guys need to fix MultiPoolMiner.ps1, there's a comma missing on line 71... ;P

**Comment by jestercore** [comment]
@titvs yes, there is a problem

**Comment by UselessGuru** [comment]
> But @UselessGuru you guys need to fix MultiPoolMiner.ps1, there's a comma missing on line 71... ;P

Thanks for the hint:
Fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1790
