### ISSUE TITLE
Bminer wrong commandline

### ISSUE THREAD

**Issue by jestercore** [MultiPoolMiner/MultiPoolMiner#1782]
![bminer](https://user-images.githubusercontent.com/33821148/40657205-2c8cb47e-6371-11e8-9b5d-18bcda114644.png)

**Comment by jestercore** [comment]
And there is something wrong with Phoenixminer, it's restarting to frequently, 39 times after 1 night. Delay was 120, and switchingprevention 2

**Comment by UselessGuru** [comment]
???

Title says BMiner, text says phoenix miner, and on the screenshot it does not show 120x... for any miner

And in any case logs are tremendously helpful to diagnose problems :-)

**Comment by jestercore** [comment]
Check idle section of screenshot, there is info about Bminer issue.

Can't send logs with phoenix miner issue currently because deleted it... Gonna send it later.

**Comment by UselessGuru** [comment]
> there is info about Bminer issue.

There is NO info. 

Try running the same command out of MPM. Same result -> Contact Bmainer makers.

**Comment by jestercore** [comment]
Oh, sorry, this weird Bminer config freaked me out. Looks so strange. You are right, excuse me.
