### ISSUE TITLE
Powershell Access Violation

### ISSUE THREAD

**Issue by thinkplaystudios** [MultiPoolMiner/MultiPoolMiner#1784]
Anyone else getting this with a mixed AMD/Nvidia rig?
![accviol](https://user-images.githubusercontent.com/7245178/40658554-a13ae762-6319-11e8-9879-0f00acf745f2.jpg)
There is very little in the logs except for the line "Starting MPM version 2.7.2.7 (c) MultiPoolMiner.io", etc.

When I disable all Nvidia cards and only run with AMD, I don't get the access violation error.

I run 6x AMD and 6x Nvidia on this rig.

Thanks.

**Comment by UselessGuru** [comment]
What ever the cause is it is not a MPM code issue.
Can you see anything interesting in the logs?

A wild guess: Your OpenGL installationis corrupt. Uninstall the Nvidia drivers with DDU and then install the latest Nvidia drivers

**Comment by grantemsley** [comment]
Looks to be most likely a hardware problem to me. Bad memory, PSU or a malfunctioning card would be my first guesses.  Either that or a bug with OpenCL.

Have you tried previous versions with 6xAMD and 6xNVIDIA cards?  I've never actually used a system with that many cards in it.

**Comment by thinkplaystudios** [comment]
Thanks guys, I don't quite know yet what's happened.  I have run miners manually on this for months and have decidedly to do some updates and try out MPM.  Once I am back, I'll try to reinstall drivers.  This is likely a corrupt cuda driver.  I'll report in, I just wanted to see if this is an occurrence with others.

**Comment by grantemsley** [comment]
Let us know what you find out.  Like I said, it's probably hardware or drivers, but there's a chance there's a bug with the OpenCL libraries we use when you have that many cards in a system - I'm not sure if others have tried it with a 12 card system.  And if does turn out to be a bug I want to try to track it down and fix it :)

**Comment by symalla** [comment]
I am currently running a system with 6x RX580 and 6x 1080ti and have not run into this issue yet.

**Comment by grantemsley** [comment]
@symalla excellent!  Thanks for letting us know.  So it's almost certainly a driver/hardware problem.

**Comment by jestercore** [comment]
I have 580+560+1060 combined, working fine

**Comment by thinkplaystudios** [comment]
So, the final result is that when I changed the CPU on the rig (faster CPU), for some reason, access to CUDA in any way is causing the access violation, and no matter if I do a clean uninstall of all display drives (DDU, etc), I just couldn't reset the drivers for Nvidia!  So, the final solution was to do a "fresh start" with Windows and have it revert to a fresh install (option within Windows).  After this, I'm back to how it was where everything is working, both sets of AMD and Nvidia cards (6 each) are working, with either separate manual miners for each GPU type, or mining using MPM.
