### ISSUE TITLE
verified files??

### ISSUE THREAD

**Issue by skovesh** [MultiPoolMiner/MultiPoolMiner#1789]
How do you releae 'verified' files with lot of red lines (errors) inside??

**Comment by UselessGuru** [comment]
Logs would be nice - what errors?

MY crystal ball is currently in maintenance.

**Comment by UselessGuru** [comment]
Maybe this was your issue:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1790

**Comment by skovesh** [comment]
Last multipoolminer. Ps1 writes lots of red lines... I update always only "verified" updates from the site. Right now on work, can provide this evenining the log. Thanks, Marcello                                                                                                                                                                        Still prefer BlackBerry, the most secure device                                                                                                                                                                           Da: notifications@github.comInviato: 30 maggio 2018 08:33A: MultiPoolMiner@noreply.github.comRispondi a: reply@reply.github.comCc: marcello.segal@gmail.com; author@noreply.github.comOggetto: Re: [MultiPoolMiner/MultiPoolMiner] verified files?? (#1789)  Logs would be nice - what errors?
MY crystal ball is currently in maintenance.
