### ISSUE TITLE
Donation run always within ~40mins of restarting

### ISSUE THREAD

**Issue by Dewbs** [MultiPoolMiner/MultiPoolMiner#1792]
Please consider different method of starting donation run.
Example - changing pools or algos requires restarting mpm and therefore resets donation 'clock':
result is (if need to change config as above) multiple minimum 10min donation runs per hour after changes.
I have no issue with min. 10min per day but if needing to restart (for config changes or even crashes etc.) then multiple min. 10min donation runs per day becomes excessive.
(example - blazepool had an issue earlier today so wanted to exclude them until settled, hence adjusting start.bat/restart/reset donation clock; another example when PGN difficulty drops and want to limit to X16s algo for that short period again adjusting/restarting/resetting donation clock)

**Comment by aaronsace** [comment]
You have one hour to do what ever you want before the donation kicks in. 

You don't need to restart MultiPoolMiner to edit any configurations; they are reloaded from scratch every minute.

**Comment by Dewbs** [comment]
The start.bat is reloaded every minute? How so?

**Comment by Dewbs** [comment]
Does config override start.bat?

**Comment by aaronsace** [comment]
Yes, it has ultimate control over everything to allow a GUI to be implemented.

**Comment by Dewbs** [comment]
Ok that's useful information I have edited config to suit, thank you
