### ISSUE TITLE
Adding DelosMiner 1.2.0-x16r (x16r-optimized Build)

### ISSUE THREAD

**Issue by centreece** [MultiPoolMiner/MultiPoolMiner#1795]
Could you consider to add both, the 32-bit and the 64-bit version?

> Notes: 32-bit version might perform faster for certain system configurations.

[Source](https://bitcointalk.org/index.php?topic=4344544.0)

**Comment by UselessGuru** [comment]
Available with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1787
