### ISSUE TITLE
Non fatal error with new balances when API is unavailable

### ISSUE THREAD

**Issue by thebeerbaron2018** [MultiPoolMiner/MultiPoolMiner#1797]
```
WARNING: Pool API (Zpool) returned nothing.
Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
At C:\Users\miner\Desktop\Miner\Include.psm1:21 char:5
+     $Balances += [PSCustomObject]@{
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

I assume this error occurs because it has a null or empty balance returned from the Zpool API

**Comment by UselessGuru** [comment]
How many pools do you have configured?

Could you  please post the contents of http://localhost:3999/balances & http://localhost:3999/config?

**Comment by UselessGuru** [comment]
In other words - The error is there if only one pool is responding?

**Comment by thebeerbaron2018** [comment]
Absolutely.  Sorry if I didn't explain myself enough.  It would seem that line 21 in include.ps1 is attempting to do an addition of the "total" fields from each of the pools balances - but it looks like when the Zpool API fails the balance is either blank or null and the addition sum command fails.

**Comment by UselessGuru** [comment]
If there is only on pool reporting then $Balances will be single valued variable, but 
$Balances += [PSCustomObject]@{
expects an array.

I am working on a fix. We might have the same problem in other parts of the code.

**Comment by UselessGuru** [comment]
Fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1798

**Comment by thebeerbaron2018** [comment]
Yep.  That's fixed it.  I was able to reproduce the problem every time by editing the zpool.ps1 file in the blanaces folder and make the URL unreachable (just added a few xxx into the URL).  This causes the error to throw right from the start and every interval.  I've updated to your code change and the error is gone!  Quick fix.
