### ISSUE TITLE
Config Problems

### ISSUE THREAD

**Issue by r0dn0r** [MultiPoolMiner/MultiPoolMiner#1802]
Trying to enter more than one thing in one field seems not to work. For example entering multiple currencies like this: "Currency": "EUR,LTC,BTC", breaks the profit calculation. I encountered the same problem with multiple pools in "PoolName" and "ExcludePoolName" .
Configuring it this way in Start.bat works.
Do you have to separate them with something else than the comma?

**Comment by grantemsley** [comment]
If you are putting it in config.txt, it has to be an array.  So it should look like this:

```
"Currency": [ "EUR","LTC","BTC" ],
```

**Comment by r0dn0r** [comment]
Ok, thanks! Maybe that could be included in the readme.
