### ISSUE TITLE
Updated miner software 1Jun2018

### ISSUE THREAD

**Issue by Rimplestilhskin** [MultiPoolMiner/MultiPoolMiner#1808]
I see this mining software updates is available.

**miners\Bminer.txt** 
Changed domain link to .me and is now version 8, there is lite and normal version for win 64
https://www.bminer.me/releases/

https://www.bminercontent.com/releases/bminer-v8.0.0-32928c5-amd64.zip

**miners\Cast.txt**
http://www.gandalph3000.com/download/cast_xmr-vega-win64_110.zip

**miners\EthminerNvidia.txt **
https://github.com/ethereum-mining/ethminer/releases/download/v0.15.0.dev11/ethminer-0.15.0.dev11-Windows.zip

**Comment by UselessGuru** [comment]
BMiner 8 can do eth & dual algo eth hash mining, but it is not fully compatible with MPM yet (Work In Progress)
Cast / Ethash-Miner
We do not support beta or dev versions
