### ISSUE TITLE
[Feature Request] Have benchmark earnings displayed in coin selected in start script

### ISSUE THREAD

**Issue by Jaerin** [MultiPoolMiner/MultiPoolMiner#181]
Currently you can have the profits change their display when you select a different coin other than BTC in the start script, but the benchmark prices are still shown in BTC.  Would be nice to have them also display in the coin of choice.  Also have it change the c=XXX entry in the pools password entry, but I'm not sure if that applies to Multipoolhub and maybe just zpool.

**Comment by aaronsace** [comment]
Definitely something I have thought about; not so easy to implement without it getting convoluted.

**Comment by Jaerin** [comment]
If you do end up doing this a calculation of how much you would mine if you just mined that coin straight might be useful as well.  I'm realizing converting to BTC is likely costing a lot of money in transfer fees.

**Comment by aaronsace** [comment]
Yes, fees are crazy at the moment. Not transferring anything below 0.1 BTC anymore.
