### ISSUE TITLE
Compare-Object error at MultiPoolMiner.ps1

### ISSUE THREAD

**Issue by thinkplaystudios** [MultiPoolMiner/MultiPoolMiner#1815]
```
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\MultiP00Lminer\MultiPoolMiner.ps1:531 char:130
+ ... pare-Object ($_.Combination | Select-Object -ExpandProperty Device_Na ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
```

**Comment by aaronsace** [comment]
@thinkplaystudios You need to upload the log file where you got that error from.

**Comment by thinkplaystudios** [comment]
Here is the latest run before the error.
[MultiPoolMiner_2018-06-03.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2066074/MultiPoolMiner_2018-06-03.txt)
[MultiPoolMiner_2018-06-03_11-25-09.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2066077/MultiPoolMiner_2018-06-03_11-25-09.txt)
[MultiPoolMiner_2018-06-03_11-26-48.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2066078/MultiPoolMiner_2018-06-03_11-26-48.txt)

**Comment by grantemsley** [comment]
I too am seeing this error with the latest changes to device handling.

I also notice that it's trying to run AMD only miners even though the system only had an NVIDIA card in it at the moment (previously you could leave all device types enabled and it would ignore miners for hardware you don't have).  Not sure if that's related or not.

PS @aaronsace have you been getting my skype messages?  Not sure if you just haven't had a chance to respond or if they aren't going through for some reason.

**Comment by thinkplaystudios** [comment]
I'm also just profiling (benchmarking) Nvidia cards only with this rig.  The logs I sent were freshly generated after clearing all stats and logs.  I have AMD cards waiting to be enabled on this rig as well.

**Comment by thinkplaystudios** [comment]
I've enabled the AMD cards and although I've only set -type amd in the argument, it proceeds to use the Nvidia cards as well as the AMD cards (both types now enabled in the rig).  Is this by design?

Also, what is the expected behaviour when any of the miners crash?  Does MPM time out in monitoring the miner and move on?  During benchmarking, it seems MPM doesn't catch the crashed miner and continues to wait for it, thus never moving on to the next miner to benchmark.  The only way to proceed is to manually restart MPM, then if the same miner finishes without crashing, then it proceeds to the next in the list.

**Comment by thinkplaystudios** [comment]
More to the findings:
The miner in question here is happens to be EthDcrMiner64.exe.  The miner doesn't crash as it ends unexpectedly because it wasn't able to find cards specified in the -di argument.  I'm not sure how MPM determines which cards are AMD cards (it passes -platform 1) but with the wrong list of device indices for AMD cards passed to -di the miner just closes and MPM doesn't pick up the miner exiting.  But the main problem is that MPM passes the wrong indices to the -di.  If I take command MPM uses to run the miner, and manually changes the indices for the -di to the correct one, the miner runs as expected.

Is there a way to reset or manually edit the device indices MPM uses?

**Comment by thinkplaystudios** [comment]
@grantemsley I am also seeing the same with CPU miners.  I don't want to use any CPU miners, and have set -type to exclude cpu mining, but this version of MPM launches cpu miners anyway.

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1849
