### ISSUE TITLE
Get-Device breaks ClaymoreEthash / wrong deviceID

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1819]
Configuration: 
1x NVIDIA, 1xAMD (see attached devices.txt)

MPM attempts to launch AMD with ' -di 1'

`Ethash-Claymore\EthDcrMiner64.exe -mode 0 -mport -13333 -epool europe.ethash-hub.miningpoolhub.com:20585 -ewal UselessGuru.BlackBox -epsw x -esm 2 -platform 1 -y 1 -allpools 1 -allcoins exp -dcoin blake2s -dcri 80 -dpool blake2s.eu.nicehash.com:3361 -dwal 3JQt8RezoGeEmA5ziAKNvxk34cM9JWsMCo.BlackBox -dpsw x -di 1`

**Comment by thinkplaystudios** [comment]
I pointed out a similar finding in https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1815

**Comment by thinkplaystudios** [comment]
EthDcrMiner64 is the only miner I am seeing this as a problem, PhoenixMinerAmd doesn't have the problem of specific the AMD card device indices.

**Comment by UselessGuru** [comment]
> PhoenixMinerAmd doesn't have the problem 

True, because it it not (yet) making use of Get-Device to retrieve device information.

**Comment by UselessGuru** [comment]
ClaymoreDual is still broken after https://github.com/MultiPoolMiner/MultiPoolMiner/commit/bfd1fb5926edd91a44c4730992f6693a27c985cc
[devices.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2070008/devices.zip)

**Comment by thinkplaystudios** [comment]
Updated to bfd1fb5 but still not working:

Bin\Ethash-Claymore\EthDcrMiner64.exe -mode 0 -mport -13333 -epool daggerhashimoto.usa.nicehash.com:3353 -ewal NICEHASHADDR.MINER -epsw x -esm 3 -platform 1 -y 1 -allpools 1 -allcoins exp -dcoin blake2s -dcri 80 -dpool blake2s.mine.blazepool.com:5766 -dwal BLAZEPOOLADDR -dpsw ID=alpha,c=BTC -di 789abc

Where the argument should be -di 123456

The argument MPM comes up with is for the Nvidia cards.

**Comment by thinkplaystudios** [comment]
With a6667d8, I am getting -di 000000.

**Comment by UselessGuru** [comment]
@thinkplaystudios 

> With a6667d8, I am getting -di 000000.

Please try https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1854

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1867
