### ISSUE TITLE
Ravencoin Miner 3.0

### ISSUE THREAD

**Issue by esseeme** [MultiPoolMiner/MultiPoolMiner#1820]
> Further optimizations to all hash functions
> Improvements to hash rate stability

Source: https://github.com/RavencoinProject/RavencoinMiner/releases

**Comment by thinkplaystudios** [comment]
Curious, which of the pools MPM support are working with ravencoin?

**Comment by UselessGuru** [comment]
> Curious, which of the pools MPM support are working with ravencoin?

Check the pools web pages :-)
