### ISSUE TITLE
TerminatingError(Compare-Object): "Cannot bind argument to parameter 'ReferenceObject' because it is null."

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1828]
INFO: Start waiting before next run.
INFO: Finish waiting before next run.
INFO: Saving hash rates.
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\pjb\Desktop\June 6 633pm\Stats\Excavator-1-GPU#00-GPU#01_Ethash_HashRate.txt' because it does not exist."
INFO: Starting next run.
INFO: Mining for you. Donation run will start in 00 hour(s) 32 minute(s).
INFO: Updating exchange rates from Coinbase.
INFO: Loading saved statistics.
INFO: Loading pool information.
INFO: Selecting best pool for each algorithm.
INFO: Getting miner information.
INFO: Calculating profit for each miner.
PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'ReferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\pjb\Desktop\June 6 633pm\MultiPoolMiner.ps1:529 char:129
+ ... pare-Object ($_.Combination | Select-Object -ExpandProperty DeviceNam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\pjb\Desktop\June 6 633pm\MultiPoolMiner.ps1:529 char:129
+ ... pare-Object ($_.Combination | Select-Object -ExpandProperty DeviceNam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

INFO: Stopping miner (Excavator-1-GPU#00-GPU#01).
INFO: Starting miner (CcminerKlaust): 'C:\Users\pjb\Desktop\June 6 633pm\Bin\NVIDIA-KlausT\ccminer.exe -a neoscrypt -b 4068 -o stratum+tcp://hub.miningpoolhub.com:17012 -u paulpoco.multipoolminer -p x'
INFO: Pinging monitoring server.
INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success

**Comment by Kettoch** [comment]
I am getting the same issue at the same point

**Comment by Kettoch** [comment]
It seems that Excavator is only using ONE GPU out of my pair of 1080 TIs.

**Comment by amolitor** [comment]
same error

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/4eee162154cca37aa83a014df8ab857b84b82dbd
