### ISSUE TITLE
FireIceAMD running but I don't have an AMD GPU

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1829]
![image](https://user-images.githubusercontent.com/801414/41074453-1af300ea-69bd-11e8-8329-a135df2c64a5.png)

-type nvidia,cpu

Here is a screen of the benchmarking going on, the top section is AMD?
![image](https://user-images.githubusercontent.com/801414/41074797-a035b9e0-69be-11e8-961f-0a5e58ae82f5.png)

**Comment by Exodus4400** [comment]
I also get Nvidia miners running when I don't have any connected and specify -type amd,cpu.
