### ISSUE TITLE
Add another SgMiner fork for more AMD Algos

### ISSUE THREAD

**Issue by Exodus4400** [MultiPoolMiner/MultiPoolMiner#1831]
I created a mining file for an SgMining Fork to support more AMD algos (aergo, tribus, x16r/s, x17, phi and xevan). What is the $HashSHA256 variable? What else needs to be changed for it to interface properly? I used the original SG miner file as the template and just subbed in the address of the zip and added the algos. Text is below.

using module ..\Include.psm1

$Path = ".\Bin\sgminer-kl\sgminer.exe"
$HashSHA256 = "C00DE0D33BD20BE3B5014FC019ED8A81D3AA5273C8AF96B17D6B51C5D8FA3933"
$Uri = "https://github.com/KL0nLutiy/sgminer-kl/releases/download/kl-1.0.5fix/sgminer-kl-1.0.5_fix-windows.zip"

$Commands = [PSCustomObject]@{
    "aergo" = " --intensity 19" #aergo
	"phi" = " --intensity 19" #phi
	"tribus" = " --intensity 19" #tribus
	"x16r" = " --intensity 19" #x16r
	"x16s" = " --intensity 19" #x16s
	"x17" = " --intensity 19" #x17
	"xevan" = " --intensity 19" #xevan
}

$Name = Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName

$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | Where-Object {$Pools.(Get-Algorithm $_).Protocol -eq "stratum+tcp" <#temp fix#>} | ForEach-Object {

    $Algorithm_Norm = Get-Algorithm $_

    [PSCustomObject]@{
        Type       = "AMD"
        Path       = $Path
        HashSHA256 = $HashSHA256
        Arguments  = "--api-listen -k $_ -o $($Pools.$Algorithm_Norm.Protocol)://$($Pools.$Algorithm_Norm.Host):$($Pools.$Algorithm_Norm.Port) -u $($Pools.$Algorithm_Norm.User) -p $($Pools.$Algorithm_Norm.Pass)$($Commands.$_) --text-only --gpu-platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | Select-Object -ExpandProperty Vendor), 'Advanced Micro Devices, Inc.'))"
        HashRates  = [PSCustomObject]@{$Algorithm_Norm = $Stats."$($Name)_$($Algorithm_Norm)_HashRate".Week}
        API        = "Xgminer"
        Port       = 4028
        URI        = $Uri
    }
}

**Comment by grantemsley** [comment]
The $HashSHA256 is the SHA256 has of the file named in $Path.  It's used by the Get-Binaries script to ensure the correct version is installed.

If you don't know how to find the hash, that's ok, just make a pull request and I can fix it before it gets committed.

If you don't know how to make a pull request, I can take this and test it then add it myself if you prefer.

**Comment by Exodus4400** [comment]
Okay, that sounds good. 

I am experiencing a problem: the miner won't create a stat file for the x16r or x16s algorithms. It will for all the other ones, just not those two. Do you have any insight?

**Comment by UselessGuru** [comment]
> won't create a stat file for the x16r or x16s algorithms

These algorithms use longer until they report proper hash rate. See https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1682

**Comment by grantemsley** [comment]
This miner does nothing but crash when GPU_FORCE_64BIT_PTR is set to 1, which is what multipoolminer sets it to.

**Comment by Exodus4400** [comment]
He compiled a 64 bit version that works with the GPU_FORCE_64BIT_PTR=1. Here's the updated bat:

using module ..\Include.psm1

$Path = ".\Bin\sgminer-kl\sgminer.exe"
$HashSHA256 = "7A29E1280898D049BEE35B1CE4A6F05A7B3A3219AC805EA51BEFD8B9AFDE7D85"
$Uri = "https://github.com/KL0nLutiy/sgminer-kl/releases/download/kl-1.0.5fix/sgminer-kl-1.0.5_fix-windows_x64.zip"

$Commands = [PSCustomObject]@{
    "Aergo" = " -X 256 -g 2" #aergo
	"Phi" = "  -X 256 -g 2 -w 256" #phi
	"Tribus" = "  -X 256 -g 2" #tribus
	"x16r" = "  -X 256 -g 2" #x16r
	"x16s" = "  -X 256 -g 2" #x16s
	"X17" = "  -X 256 -g 2" #x17
	"Xevan" = "  -X 256 -g 2" #xevan

}

$Name = Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName

$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | Where-Object {$Pools.(Get-Algorithm $_).Protocol -eq "stratum+tcp" <#temp fix#>} | ForEach-Object {

    $Algorithm_Norm = Get-Algorithm $_

    [PSCustomObject]@{
        Type       = "AMD"
        Path       = $Path
        HashSHA256 = $HashSHA256
        Arguments  = "--api-listen -k $_ -o $($Pools.$Algorithm_Norm.Protocol)://$($Pools.$Algorithm_Norm.Host):$($Pools.$Algorithm_Norm.Port) -u $($Pools.$Algorithm_Norm.User) -p $($Pools.$Algorithm_Norm.Pass)$($Commands.$_) --text-only --gpu-platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | Select-Object -ExpandProperty Vendor), 'Advanced Micro Devices, Inc.'))"
        HashRates  = [PSCustomObject]@{$Algorithm_Norm = $Stats."$($Name)_$($Algorithm_Norm)_HashRate".Week}
        API        = "Xgminer"
        Port       = 4028
        URI        = $Uri
    }
}
