### ISSUE TITLE
Errors in "commit 3c02ed5 a day ago"

### ISSUE THREAD

**Issue by Rimplestilhskin** [MultiPoolMiner/MultiPoolMiner#1832]
Just downloaded master branch, ran as is, only copied stats + bin & download folder. Rest is default.

nsgminer.exe : [2018-06-08 18:11:34] nsgminer.exe: --gpu-platform: Value out of range
At line:1 char:109
+ ... lowNormal'; & 'F:\MultiPoolMiner-master\Bin\Nsgminer\nsgminer.exe' -- ...
+                 
    + CategoryInfo          : NotSpecified: ([2018-06-08 18:...ue out of range:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

[2018-06-08 18:11:34] nsgminer.exe: --gpu-platform: Value out of range

\MultiPoolMiner-master\MultiPoolMiner.ps1:529 char:129
+ ... pare-Object ($_.Combination | Select-Object -ExpandProperty DeviceNam ...

[MultiPoolMiner_2018-06-08.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2085141/MultiPoolMiner_2018-06-08.txt)
[MultiPoolMiner_2018-06-08_18-11-04.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2085142/MultiPoolMiner_2018-06-08_18-11-04.txt)
[NsgminerAmd-14028_2018-06-08_18-11-34.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2085143/NsgminerAmd-14028_2018-06-08_18-11-34.txt)

**Comment by UselessGuru** [comment]
Please test https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1849
