### ISSUE TITLE
Modifying config.txt results in no pools available.

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1833]
I have started to customize the config.txt and I started getting errors.

I have deleted it and let it recreate it.  Hoping to see what triggers the failure.

Once I get a failure, I will post the config.txt at that point.

**Comment by Kettoch** [comment]
ok, I have my first odd issue.  With the current master, I am choosing AMD miners when I do not have AMD configured in the list.
`{
  "Pools": {
    "MiningPoolHub": {
      "User": "User",
      "Worker": "Worker",
      "API_ID": "$APIUser",
      "API_Key": "$API"
    },
    "MiningPoolHubCoins": {
      "User": "User",
      "Worker": "Worker",
      "API_ID": "$APIUser",
      "API_Key": "$API"
    },
    "NiceHash": {
      "BTC": "1MADXnqVKTtfgAjEQpsMaQcUWoXkg1ACof",
      "Worker": "Worker"
    },
    "Zpool": {
      "BTC": "1MADXnqVKTtfgAjEQpsMaQcUWoXkg1ACof",
      "Worker": "Worker"
    }
  },
  "Miners": {
  },
  "Interval": "$Interval",
  "Region": "us",
  "SSL": "$SSL",
  "DeviceName": [
      "nvidia",
      "cpu"
    ],
    "Type": [
      "nvidia",
      "cpu"
    ],
  "Algorithm": [
    "blake2s",
    "cryptonightV7",
    "decrednicehash",
    "ethash",
    "ethash2gb",
    "equihash",
    "groestl",
    "keccak",
    "lbry",
    "lyra2re2",
    "lyra2z",
    "neoscrypt",
    "pascal",
    "sib",
    "skunk"
  ],
  "MinerName": "$MinerName",
  "PoolName": [
    "miningpoolhubcoins",
    "zpool",
    "nicehash"
  ],
  "ExcludeAlgorithm": "$ExcludeAlgorithm",
  "ExcludeMinerName": "$ExcludeMinerName",
  "ExcludePoolName": "$ExcludePoolName",
  "Currency": [
    "btc",
    "usd",
    "eur"
  ],
  "Donate": "10",
  "Proxy": "$Proxy",
  "Delay": "$Delay",
  "Watchdog": "$True",
  "MinerStatusURL": "$MinerStatusURL",
  "MinerStatusKey": "$MinerStatusKey",
  "SwitchingPrevention": "$SwitchingPrevention",
  "ShowPoolBalances": "$True",
  "ShowPoolBalancesExcludedPools": "$ShowPoolBalancesExcludedPools",
  "ExtendIntervalAlgorithm": [
    "X16R",
    "X16S"
  ],
  "ExtendIntervalMinerName": [
    "PalginNvidia"
  ],
  "UseFastestMinerPerAlgoOnly": "$UseFastestMinerPerAlgoOnly",
  "IgnoreMinerFee":  "$IgnoreMinerFee"
}
`

**Comment by Kettoch** [comment]
Need to put something up on how to modify the json file.  Took me a while to figure out how to put a string array into the file.

**Comment by UselessGuru** [comment]
> Need to put something up on how to modify the json file. Took me a while to figure out how to put a string array into the file.

How about https://jsonblob.com/?
