### ISSUE TITLE
$IgnoreCosts not working

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1839]
Problem introduced with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/f67ea949bfd59e0effa66229532039f36e806367

How is it supposed to work?

My original code allowed it to be a per miner config settable in config.txt

And what about IgnorePoolFees?

**Comment by aaronsace** [comment]
@UselessGuru There is nothing implemented; unless it's hidden somewhere, I couldn't find anything.

**Comment by UselessGuru** [comment]
@aaronsace 

You changed IgnoreMinerFees to IgnoreCosts. What is your intention?

IgnoreMinerFees is documented in readme and implemented in a number of miners, e.g. CcminerDelos, CcminerZealot, ClaymoreNeoscryptAmd, ClaymoreEquihashAmd, JustAMinerNeoScrypt and the coming SRBMiner.

And what about IgnorePoolFees? I am about to post a PR that takes care of pool fees. Will you rename that parameter too?
