### ISSUE TITLE
Master: Excavator only uses one GPU

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1840]
It does not seem to matter what I do, But the current master does not seem to use more than one of my NVidia 1080 TIs.  It used to be one that got a LOT of activity.

Here is my log file for the Excavator.

[Excavator-5100_2018-06-10_14-14-07.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2088123/Excavator-5100_2018-06-10_14-14-07.zip)

**Comment by UselessGuru** [comment]
Please test https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1853

**Comment by grantemsley** [comment]
@Kettoch If you'd be willing to gather the information I ask for in #1857, it would be very useful to me for writing a proper fix for this. Thanks!

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1867
