### ISSUE TITLE
Adding Pigeoncoin Miner 2.6

### ISSUE THREAD

**Issue by centreece** [MultiPoolMiner/MultiPoolMiner#1844]
Could you please add the latest release of Pigeoncoin Miner?

https://github.com/Pigeoncoin-Miner/Pigeoncoin/releases/

**Comment by UselessGuru** [comment]
Is it any faster than existing miner? To me it looks just like any other poorly enhanced Ccminer (documentation and algorithm list is incomplete, no info about devfee 'Set Donation % with --donate'???)

**Comment by nemosminer** [comment]
its very fast for x16s fastest ive tested

**Comment by UselessGuru** [comment]
Available since https://github.com/MultiPoolMiner/MultiPoolMiner/commit/3dd363cbce6b8ea8e6065227338d70c9e8739b60#diff-6cb8480a8f28c789793786d2676a1167
