### ISSUE TITLE
master release 6/12/2018 with latest patch excavator giving out of memory issues neoscrypt

### ISSUE THREAD

**Issue by amolitor** [MultiPoolMiner/MultiPoolMiner#1851]
with the master release of 3 weeks ago , excavatornvidia1 works fine without issues.

[Excavator-5100_2018-06-12_20-43-33.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2096150/Excavator-5100_2018-06-12_20-43-33.txt)
and still experiencing the same issue of #1840

**Comment by UselessGuru** [comment]
@amolitor 

> **same issue of #1840**

Could you please post the output of http://localhost:3999/devices. Thank you!

> **Out of memory error:**

ExcavatorNvidia1 was only using 1 thread (hence the 1 in the name).
The new Excavator miner versions attempt to also run 2 threads which _for some might_ cause out-of memory errors.
Theses errors are purely cosmetic.  Two workarounds: 
- let MPM fail the benchmark, it will report 0 hashrate and will never attempt to mine it
- uncomment the failing algorythm in the miner file, e.g.     `#[PSCustomObject]@{Algorithm = "neoscrypt"; Threads = 2; Params = @()} #NeoScrypt`

**Comment by amolitor** [comment]
> Could you please post the output of http://localhost:3999/devices. Thank you!

[devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2097807/devices.txt)

About the memory issue:
Excavator-2-GPU#00-GP... NeoScrypt ...hmarking    Unknown     80 % 0.21351000 ZergPool[0.00 %]
Excavator-1-GPU#00-GP... NeoScrypt ...hmarking    Unknown     80 % 0.21351000 ZergPool[0.00 %]

Both of them gives me out of memory maybe excavator 2 is overlap the 1 config ? idk, well thanks.

**Comment by UselessGuru** [comment]
Please test https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1853

**Comment by amolitor** [comment]
> Please test #1853


its fixed, but out of memory issue on excavator1 still happening , heres the log:

[Excavator-5100_2018-06-13_10-33-53.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2098314/Excavator-5100_2018-06-13_10-33-53.txt)

**Comment by grantemsley** [comment]
@amolitor If you'd be willing to gather the information I ask for in #1857, it would be very useful to me for writing a proper fix for this.  Thanks!

**Comment by Kettoch** [comment]
Here we go 2xNVidia 1080Tis
`
C:\WINDOWS\system32>cd \MultiPoolMiner

C:\MultiPoolMiner>"C:\Program Files\NVIDIA Corporation\nvsmi\nvidia-smi.exe" -L
GPU 0: GeForce GTX 1080 Ti (UUID: GPU-35ed159d-88ac-bf05-32cc-f6908ab78cb6)
GPU 1: GeForce GTX 1080 Ti (UUID: GPU-bec5c9f8-5347-e5c7-6b60-b66b16055470)

C:\MultiPoolMiner>"C:\Program Files\NVIDIA Corporation\nvsmi\nvidia-smi.exe" -q

==============NVSMI LOG==============

Timestamp                           : Thu Jun 14 18:18:28 2018
Driver Version                      : 391.01

Attached GPUs                       : 2
GPU 00000000:17:00.0
    Product Name                    : GeForce GTX 1080 Ti
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : N/A
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : WDDM
        Pending                     : WDDM
    Serial Number                   : N/A
    GPU UUID                        : GPU-35ed159d-88ac-bf05-32cc-f6908ab78cb6
    Minor Number                    : N/A
    VBIOS Version                   : 86.02.39.40.32
    MultiGPU Board                  : No
    Board ID                        : 0x1700
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.04
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x17
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1B0610DE
        Bus Id                      : 00000000:17:00.0
        Sub System Id               : 0x36001028
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 13000 KB/s
        Rx Throughput               : 31000 KB/s
    Fan Speed                       : 23 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 11264 MiB
        Used                        : 476 MiB
        Free                        : 10788 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 229 MiB
        Free                        : 27 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 10 %
        Memory                      : 8 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 39 C
        GPU Shutdown Temp           : 96 C
        GPU Slowdown Temp           : 93 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 18.09 W
        Power Limit                 : 250.00 W
        Default Power Limit         : 250.00 W
        Enforced Power Limit        : 250.00 W
        Min Power Limit             : 125.00 W
        Max Power Limit             : 300.00 W
    Clocks
        Graphics                    : 139 MHz
        SM                          : 139 MHz
        Memory                      : 405 MHz
        Video                       : 544 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1911 MHz
        SM                          : 1911 MHz
        Memory                      : 5505 MHz
        Video                       : 1620 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 176
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 1936
            Type                    : C+G
            Name                    : Insufficient Permissions
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 7836
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 8800
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 8984
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 10176
            Type                    : C+G
            Name                    : C:\Windows\explorer.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 10276
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 11968
            Type                    : C+G
            Name                    : C:\Program Files (x86)\Alienware Update\DellUpTray.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 12820
            Type                    : C+G
            Name                    : C:\Program Files\WindowsApps\SiberSystemsInc.RoboFormEdge_8.5.1.0_x86__7kk3kr9e0p1np\RoboFormCompanion.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 13892
            Type                    : C+G
            Name                    : C:\Program Files\Alienware\Command Center\ThermalController.exe
            Used GPU Memory         : Not available in WDDM driver model
        Process ID                  : 14908
            Type                    : C+G
            Name                    : C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe
            Used GPU Memory         : Not available in WDDM driver model

GPU 00000000:65:00.0
    Product Name                    : GeForce GTX 1080 Ti
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : N/A
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : WDDM
        Pending                     : WDDM
    Serial Number                   : N/A
    GPU UUID                        : GPU-bec5c9f8-5347-e5c7-6b60-b66b16055470
    Minor Number                    : N/A
    VBIOS Version                   : 86.02.39.40.32
    MultiGPU Board                  : No
    Board ID                        : 0x6500
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.04
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x65
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1B0610DE
        Bus Id                      : 00000000:65:00.0
        Sub System Id               : 0x36001028
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : 23 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 11264 MiB
        Used                        : 137 MiB
        Free                        : 11127 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 229 MiB
        Free                        : 27 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 35 C
        GPU Shutdown Temp           : 96 C
        GPU Slowdown Temp           : 93 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 8.66 W
        Power Limit                 : 250.00 W
        Default Power Limit         : 250.00 W
        Enforced Power Limit        : 250.00 W
        Min Power Limit             : 125.00 W
        Max Power Limit             : 300.00 W
    Clocks
        Graphics                    : 139 MHz
        SM                          : 139 MHz
        Memory                      : 405 MHz
        Video                       : 544 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1911 MHz
        SM                          : 1911 MHz
        Memory                      : 5505 MHz
        Video                       : 1620 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : None


C:\MultiPoolMiner>.\Bin\Polytimos-NVIDIA\ccminer.exe --ndevs
The system cannot find the path specified.

C:\MultiPoolMiner>.\Bin\Ethash-Eminer\eminer.exe -L

+--------------------------------------------------+
|                  OPENCL DEVICES                  |
+--------------------------------------------------+

===================  PLATFORMS  ====================

Platform ID                 0
Platform Name               NVIDIA CUDA
Platform Vendor             NVIDIA Corporation
Platform Version            OpenCL 1.2 CUDA 9.1.84
Platform Extensions         cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer
Platform Profile            FULL_PROFILE

   ===  DEVICE #0  ===
   Device ID for mining     0
   Device Name              GeForce GTX 1080 Ti
   Vendor                   NVIDIA Corporation
   Version                  OpenCL 1.2 CUDA
   Driver version           391.01
   Address bits             64
   Max clock freq           1582
   Global mem size          11811160064
   Max constant buffer size 65536
   Max mem alloc size       2952790016
   Max compute units        28
   Max work group size      1024
   Max work item sizes      [1024 1024 64]
   PCI bus id               23

   ===  DEVICE #1  ===
   Device ID for mining     1
   Device Name              GeForce GTX 1080 Ti
   Vendor                   NVIDIA Corporation
   Version                  OpenCL 1.2 CUDA
   Driver version           391.01
   Address bits             64
   Max clock freq           1582
   Global mem size          11811160064
   Max constant buffer size 65536
   Max mem alloc size       2952790016
   Max compute units        28
   Max work group size      1024
   Max work item sizes      [1024 1024 64]
   PCI bus id               101

====================================================


Found 2 devices.

C:\MultiPoolMiner>.\Bin\AMD-Bitcore\sgminer.exe --ndevs
The system cannot find the path specified.

C:\MultiPoolMiner>.\Bin\CryptoNight-AMD\xmrig-amd.exe
 * VERSIONS:     XMRig/2.6.1 libuv/1.19.2 OpenCL/2.0 MSVC/2017
 * CPU:          Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz x64 AES-NI
 * ALGO:         cryptonight, donate=5%
 * POOL #1:      failover.xmrig.com:443
 * COMMANDS:     hashrate, pause, resume
[2018-06-14 18:18:29] compiling code and initializing GPUs. This will take a while...
[2018-06-14 18:18:29] No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-06-14 18:18:29] Failed to start threads

C:\MultiPoolMiner>.\Bin\Equihash-DSTM\zm.exe --list-devices
Device: 0    GeForce GTX 1080 Ti      MB: 11264 PCI: 23:0
Device: 1    GeForce GTX 1080 Ti      MB: 11264 PCI: 101:0

C:\MultiPoolMiner>.\Bin\Ethash-Ethminer\ethminer.exe --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] GeForce GTX 1080 Ti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 11811160064
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2952790016
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[0] [1] GeForce GTX 1080 Ti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 11811160064
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2952790016
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1080 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 11811160064
[1] GeForce GTX 1080 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 11811160064

C:\MultiPoolMiner>.\bin\Excavator\excavator.exe

=========================== www.nicehash.com =========================
           Excavator v1.4.4a_nvidia GPU Miner for NiceHash.
           Copyright (C) 2018 NiceHash. All rights reserved.
                              Developed by
                djeZo, dropky, voidstar, and agiz
                   with help and contributions from
           zawawa, pallas, Vorksholk, bitbandi, ocminer, and Genoil.
=========================== www.nicehash.com =========================

Build time: 2018-02-16 13:11:25
Build number: 4645
Provided startup commandline:
        .\bin\Excavator\excavator.exe

[18:18:30][0x00003c94][info] Log started
[18:18:30][0x00003c94][info] core | Found CUDA device: GeForce GTX 1080 Ti
[18:18:30][0x00003c94][info] core | Found CUDA device: GeForce GTX 1080 Ti
[18:18:30][0x00003c94][info] api | Listening on 127.0.0.1:3456
[18:18:30][0x00003c94][info] core | Initialized!
[18:18:56][0x00003c94][info] Shutting down
[18:18:56][0x00003c94][info] api | Closing

C:\MultiPoolMiner>.\bin\hsr-palgin\hsrminer_hsr.exe --listdevs
The system cannot find the path specified.

C:\MultiPoolMiner>.\bin\PhoenixMiner\phoenixminer.exe -list
Phoenix Miner 2.9e Windows/msvc - Release
-----------------------------------------

Available GPUs for mining:
GPU1: GeForce GTX 1080 Ti (pcie 23), CUDA cap. 6.1, 1e+01 GB VRAM, 28 CUs
GPU2: GeForce GTX 1080 Ti (pcie 101), CUDA cap. 6.1, 1e+01 GB VRAM, 28 CUs

C:\MultiPoolMiner>`

**Comment by Kettoch** [comment]
This fixed the memory error for me.

**Comment by amolitor** [comment]
@grantemsley 
[nvidia-smi.exe-Q.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2105835/nvidia-smi.exe-Q.txt)
[zm.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2105836/zm.txt)
[nvidia-smi.exe-L.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2105837/nvidia-smi.exe-L.txt)


hope it helps, grabbed the data while running.

**Comment by UselessGuru** [comment]
@Kettoch

> but I am still getting this out of memory error.

This has nothing to do with MPM (or even the new unified miner file), this is purely a miner issue and you'd see the same error if run outside of MPM with the same parameters. Just let the benchmarks fail and ignore the errors. 

Depending on card model you will receive out of memory errors on the 2 thread miner instances for other algorithms too.
The required amount of memory is not documented by Nicehash (Dropky) and depends on other factors too, so setting/detecting proper limits is beyond the scope of MPM for now.
I have posted a RFI on https://github.com/nicehash/excavator. If there is more information available then the issuee might be fixed for good.
