### ISSUE TITLE
-type argument not working?

### ISSUE THREAD

**Issue by jweber018** [MultiPoolMiner/MultiPoolMiner#1852]
I have two NVIDIA cards and one AMD, I specify "-type NVIDIA" and MPM starts benchmarking and mining with all cards (and the CPU also). This happened when last I pulled master, so the issue is quite recent.

Let me know if you need any logs or anything.

Thanks in advance, guys.

**Comment by jweber018** [comment]
Nope :( still mines with all available hardware. Let me know if you need any other data.

**Comment by UselessGuru** [comment]
@jweber018 

I have a suspicion. The parameter name has changed from 'Type' to 'DeviceName'.
Can you try with directly editing config.txt? Add a section like

```
...
    "Delay":  "$Delay",
    "DeviceName":  [
        "AMD",
        "CPU"
     ],
    "Donate":  "$Donate",
...
```

**Comment by jweber018** [comment]
I'll try it out as soon as I can and report back. Thank you mate

**Comment by jweber018** [comment]
Yup. DeviceName works. You rock.
