### ISSUE TITLE
CPU and device order detection is flakey with OpenCL

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#1857]
Detecting CPUs through OpenCL is unreliable.

On many systems they won't show up at all. On others, if you have the AMD or Intel OpenCL drivers, they will show up.  And in a very confusing case, you might end up with both the AMD and Intel OpenCL drivers, and your CPU will show up twice as 2 separate devices.

The OpenCL drivers aren't actually required by any of the miners, so we should detect CPUs even if they aren't available in OpenCL.  I'm going to work on making that work better, just putting this here so people know what's going on.

In the mean time, if your CPU isn't being detected, install the AMD OpenCL drivers from here: http://debian.nullivex.com/amd/AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64.exe

That works on both Intel and AMD CPUs.  Do not install the Intel OpenCL drivers as well - that will result in your processor showing up twice in the devices list.

**Comment by UselessGuru** [comment]
> Do not install the Intel OpenCL drivers as well

Is there any performance difference between the AMD & Intel implementation?
If so, it might actually be desirable to have them both in the device list and let the miner decide which one to use.

**Comment by grantemsley** [comment]
@Uselessguru no. The miners don't use open CL at all so it makes no difference to performance. We are just (trying) to use it to detect the CPU.

**Comment by aaronsace** [comment]
I guess duplicates could occur with GPUs as well if you install two OpenCL drivers... detect them and give them the same name? 

More information about devices could be added from other sources. OpenCL info is dumped into a variable.

**Comment by grantemsley** [comment]
@aaronsace I don't think you can install 2 different OpenCL drivers for video cards that would create duplicates.  NVidia has one that handles only their cards, and AMD has one for just their cards (+ CPUs).  They won't let you install 2 different OpenCL drivers on the same system, new ones replace the old ones.

CPUs are the only area it gets tricky.

What I'm thinking is to ignore any CPU info we get from OpenCL, and generate the device objects with the same structure for the CPU(s) from WMI, which is available and will be accurate no matter what drivers are installed.  That can include information as much information as we can gather that may be useful for configuring the miners, like how many cores there are, how much cache memory, and ideally if we can find a way to get it what instruction sets are supported.


If you agree, I can work on coding that and making sure it works properly on a variety of systems, including some with multiple physical processors.

**Comment by aaronsace** [comment]
@grantemsley Please can you look at getting the correct number of devices and in the correct orders for all the miners? 

Look at merging the information from available sources: 
OpenCL.dll
NVML.dll
Win32_Processor
Win32_VideoController

**Comment by grantemsley** [comment]
@aaronsace Yeah, I can check out those and a few other ways I've seen and I'll see what works best to determine the device numbering.

For extra fun, from what I've read the order cards are listed in OpenCL isn't guaranteed to be the same every time.  And will almost certainly be different from the device order in CUDA since it always puts the fastest card first, and we need it to match up with whatever method each miner uses to order the cards.

**Comment by grantemsley** [comment]
If anyone wants to help with this, I could use some information from as many different setups as possible.  I only have so many combinations I can test by myself, and I want to make sure it works across all possible setups.  So if you have machines with at least 2 video cards (single card machines aren't of interest), what I need is:

- a description of what video cards you have in the system, including which one(s) monitors are connected to
- Output from http://localhost:3999/devices when running the latest master branch version
- The output from all of the following commands (a few of them won't exit on their own, I just need the lines that are printed when they first start):
```
"C:\Program Files\NVIDIA Corporation\nvsmi\nvidia-smi.exe" -L
"C:\Program Files\NVIDIA Corporation\nvsmi\nvidia-smi.exe" -q
.\Bin\Polytimos-NVIDIA\ccminer.exe --ndevs
.\Bin\Ethash-Eminer\eminer.exe -L
.\Bin\AMD-Bitcore\sgminer.exe --ndevs
.\Bin\CryptoNight-AMD\xmrig-amd.exe
.\Bin\Equihash-DSTM\zm.exe --list-devices
.\Bin\Ethash-Ethminer\ethminer.exe --list-devices
.\bin\Excavator\excavator.exe
.\bin\hsr-palgin\hsrminer_hsr.exe --listdevs
.\bin\PhoenixMiner\phoenixminer.exe -list
.\bin\prospector\prospector.exe list-devices
```

If people can put all that information into a text file and attach the file here, that would give me a good idea of how each type of miner numbers the cards.

Of particular interest are:
- systems with several nvidia cards of the same model, but different brands (eg. a mix of EVGA and Zotac cards or something)
- systems with 2+ NVIDIA and 2+ AMD cards

**Comment by paulpoco** [comment]
[1857.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2104297/1857.txt)

**Comment by thinkplaystudios** [comment]
[grantemsley_report.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2115701/grantemsley_report.txt)

**Comment by Spudz76** [comment]
Note that `xmr-stak` does not play well with Intel OpenCL installed, at all, on Windows.  It will crash trying to enumerate devices, so best practice is never install Intel OpenCL for any reason, but especially never when using AMD and xmr-stak.
On Windows 10 it crashes silently and only logs the Intel IGD OCL DLL having crashed hard in the Event Viewer... the command window just goes away.
