### ISSUE TITLE
Increasing RAM usage over time

### ISSUE THREAD

**Issue by MaZeeT** [MultiPoolMiner/MultiPoolMiner#1858]
When I am running the software, 3x gpu, win7 based system... I see the RAM usage goes up over time to the maximum capacity I got of 8GB. In the end the processes pwsh.exe use around 3.4GB and powershell.exe uses 3.1GB.. 

At the moment I have setup a reboot each 2. day, but this isn't optimal and I would like to hear if somebody else face the same problem or if it is a bug in the program ?

Kind regards 
MaZeeT

**Comment by grantemsley** [comment]
What version are you using?

**Comment by MaZeeT** [comment]
I am using the 2.7.2.7 version, let me know if you need more information about my setup (thought I had included the importen ones already) =)

**Comment by grantemsley** [comment]
A lot of work has gone into optimizing it since the last release.  I'm pretty sure this is fixed in the latest master version.
