### ISSUE TITLE
Set-Stat errors

### ISSUE THREAD

**Issue by thinkplaystudios** [MultiPoolMiner/MultiPoolMiner#1865]
I'm now getting these errors after the 331cfc8 update:

```
Exchange rates: 1 BTC = USD 6662.98 = ETH 12.83944277
Cannot convert value "NaN" to type "System.Decimal". Error: "Value was either too large or too small for a Decimal."
At C:\MultiP00Lminer\Include.psm1:209 char:5
+     [PSCustomObject]@{
+     ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastIConvertible
```

And then:

```
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\MultiP00Lminer\MultiPoolMiner.ps1:350 char:257
+ ... SObject.Properties.Name $_.HashRates.PSObject.Properties.Name | Where ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
```

[MultiPoolMiner_2018-06-14_15-16-40.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2104215/MultiPoolMiner_2018-06-14_15-16-40.txt)
[MultiPoolMiner_2018-06-14.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2104216/MultiPoolMiner_2018-06-14.txt)

**Comment by paulpoco** [comment]
me too

**Comment by grantemsley** [comment]
The errors seem to be coming from ClaymoreEthash, specifically when you have multiple NVIDIA GPUs.  It's not recording the stats properly.

**Comment by grantemsley** [comment]
Same here, I'm looking into it.

**Comment by jesgatt** [comment]
Apart from the NULL error, I am also getting the following error: 
TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\#####\Desktop\MultiPoolMiner-master\MultiPoolMiner.ps1:350 char:96
+ ... bject $Config.Algorithm $_.HashRates.PSObject.Properties.Name | Where ...

**Comment by grantemsley** [comment]
@jesgatt yes, that's because of the invalid stats being created.  All part of the same problem.

**Comment by aaronsace** [comment]
Pool that reports zero is OK. Just make sure Set-Stat handles zeros correctly (if that  is the function causing invalid numbers).

**Comment by thinkplaystudios** [comment]
I'm thinking of setting up a local repo so I can assist with the changes.  I'm just worried about how often I can sit down to assist.

**Comment by grantemsley** [comment]
@thinkplaystudios feel free to, we will gladly look over pull requests from anyone.  Github makes it really easy to add changes from occasional contributors.

**Comment by grantemsley** [comment]
@jesgatt I was actually mistaken.  The DifferenceObject errors are caused by a bug in CcminerDelos, and will be fixed by https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1862

**Comment by Kettoch** [comment]
Adding the line this line at the top of the set-stat function and it is corrected.
`    If ([System.Double]::IsNaN($Value) -eq $True) {$Value=0}
`

**Comment by thinkplaystudios** [comment]
@grantemsley I'll update with #1862 and confirm that compare-object works as expected.
@Kettoch that should work, I'll add it manually.

**Comment by UselessGuru** [comment]
Fix: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1870

**Comment by thinkplaystudios** [comment]
Errors have been fixed with updates plus manual change @Kettoch recommended.
