### ISSUE TITLE
Include.psm1:209 char:5 Latest commit 331cfc8 

### ISSUE THREAD

**Issue by Rimplestilhskin** [MultiPoolMiner/MultiPoolMiner#1869]
Good day, just downloaded, unzipped and run as is, these errors showed up and repeats 12+ times in red text.

Transcript started, output file is .\Logs\MultiPoolMiner_2018-06-15_22-33-08.txt
Cannot convert value "NaN" to type "System.Decimal". Error: "Value was either too large or too small for a Decimal."
At C:\Users\775\Downloads\MultiPoolMiner-master\Include.psm1:209 char:5
+     [PSCustomObject]@{
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastIConvertible

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\775\Downloads\MultiPoolMiner-master\MultiPoolMiner.ps1:350 char:96
+ ... bject $Config.Algorithm $_.HashRates.PSObject.Properties.Name | Where ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

[MultiPoolMiner_2018-06-15.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2107418/MultiPoolMiner_2018-06-15.txt)
[MultiPoolMiner_2018-06-15_22-33-08.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2107419/MultiPoolMiner_2018-06-15_22-33-08.txt)

**Comment by Dewbs** [comment]
#1865
