### ISSUE TITLE
Newly downloaded MPM does not download miners

### ISSUE THREAD

**Issue by jweber018** [MultiPoolMiner/MultiPoolMiner#1871]
I just downloaded (cloned as per the last commit) the software and I'm encountering this issue. It just does nothing and says "No miners available", after this error from Include.psm1:

Transcript started, output file is .\Logs\MultiPoolMiner_2018-06-15_19-11-29.txt
INFO: Starting MultiPoolMiner® v3 © 2017-2018 MultiPoolMiner.io
INFO: Mining for you. Donation run will start in 00 hour(s) 36 minute(s).
INFO: Updating exchange rates from Coinbase.
INFO: Loading saved statistics.
INFO: Loading pool information.
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Bitcoin\Desktop\Cosas Lindas\MultiPoolMiner\Stats\ZergPool_AEX_Profit.txt' because it does not exist."
Cannot convert value "NaN" to type "System.Decimal". Error: "Value was either too large or too small for a Decimal."
At C:\Users\Bitcoin\Desktop\Cosas Lindas\MultiPoolMiner\Include.psm1:209 char:5     [PSCustomObject]@{
    CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    FullyQualifiedErrorId : InvalidCastIConvertible
Cannot convert value "NaN" to type "System.Decimal". Error: "Value was either too large or too small for a Decimal."
At C:\Users\Bitcoin\Desktop\Cosas Lindas\MultiPoolMiner\Include.psm1:209 char:5
   [PSCustomObject]@{
     CategoryInfo          : InvalidArgument: (:) [], RuntimeException
     FullyQualifiedErrorId : InvalidCastIConvertible

(Then it cicles and does the same thing again and again. I left it running for approx. 10 mins).

Sorry for bothering but this seems kinda major. Thanks guys.

**Comment by Muaadib** [comment]
Facing the same issue myself, with the added bonus of MPM downloading Powershell v6.0.2 everytime it starts, even though its already installed and the installer is available in the downloads folder.

**Comment by jweber018** [comment]
Yep. Same happens to me.

**Comment by UselessGuru** [comment]
This could be related to https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1862

**Comment by jweber018** [comment]
So for now removing CCMiner Delos should fix the issue?

**Comment by paulpoco** [comment]
#1862 seems to be working for me, but I downloaded the latest Master and then went thru some of the Pull requests(1872 1870 1868 1867 1864 1863 1862) and merged those with my Master.  Benchmarking right now and all is fine.

**Comment by n3cr0cr0w** [comment]
@Muaadib If MPM keeps trying to download PowerShell v6.0.2 then check your system path, I bet that your PATH varible still has the older RCs of PowerShell in there and not the new v6.0.2. Fix that to correct the issue.

**Comment by jweber018** [comment]
OK, tried what @paulpoco suggested and it still does not work. Same error. Any other idea?

**Comment by paulpoco** [comment]
I know I added Powershell to the System PATH in Windows 10.

**Comment by Muaadib** [comment]
@n3cr0cr0w Thanks for the suggestion but i don't have any older/RC versions of PowerShell. The only installed version is 6.0.2

**Comment by UselessGuru** [comment]
Duplicare of https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1865
