### ISSUE TITLE
Downloader 'banner' remains through multiple cycles

### ISSUE THREAD

**Issue by Dewbs** [MultiPoolMiner/MultiPoolMiner#1873]
Is it just me? The Cyan/yellow text 'banner' remains (indefinitely?) after download has completed.
I don't think this used to happen.
Wouldn't be that bothered but it can obscure miner info.

**Comment by paulpoco** [comment]
Weird I am not seeing that.

**Comment by Dewbs** [comment]
Hmm, thank for confirming! I’m using a bit of a mixture of pull request files at the moment so I’ll see if I can narrow it down!

**Comment by paulpoco** [comment]
I am using latest Master with PR 1872 1870 1868 1867 1864 1863 1862 1853 and all is fine.

A lot of those PRs are fixes.

**Comment by Kettoch** [comment]
I get the same thing, Until I restart it.

**Comment by Dewbs** [comment]
paulpoco have you had a download active with that current state? Could you delete a miner and let it download to check if not?

**Comment by paulpoco** [comment]
I deleted xmr-stak and it downloaded again and no constant banner.  In fact I saw very brief Blue banner that was it, less than a second.

**Comment by UselessGuru** [comment]
I can confim this. The banner stays forever.

**Comment by UselessGuru** [comment]
For me the banner disappears after successful download if all files are downloadable.
In my case DL for CcminerAllium failde and left the banner on.
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1908

Also see:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1906

**Comment by carlo0000** [comment]
you sure it s not because it s keep downloading the file as antivirus remove it ?
because  on 1 computer of me i forgot to exclude multipool folder from antivirus
and multipool was downloading over and over again the same files

**Comment by UselessGuru** [comment]
Hopefully fixed with 3.1.0:

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/3.1.0

**Comment by Dewbs** [comment]
It's back!
