### ISSUE TITLE
Unable to determine divisor for AeriumX using Aergo algorithm

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1874]
I downloaded the latest Master and then went thru some of the Pull requests(1872 1870 1868 1867 1864 1863 1862) and merged those with my Master. Benchmarking right now and all is fine other than the one message saying, "2018-06-16 10:11:23 INFO: Unable to determine divisor for AeriumX using Aergo algorithm" .

I don't use the Aergo algorithm so it would affect me.

[MultiPoolMiner_2018-06-16.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2108384/MultiPoolMiner_2018-06-16.txt)
[MultiPoolMiner_2018-06-16_10-11-10.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2108385/MultiPoolMiner_2018-06-16_10-11-10.txt)

**Comment by Dewbs** [comment]
#1870

**Comment by grantemsley** [comment]
Yes, if you merge 1870 you'll see that - because the pool isn't providing the proper information for that particular coin.  It's not a problem, unless you really wanted to mine that coin.

Without 1870 you'll get a bunch of errors instead.

**Comment by paulpoco** [comment]
Yes I just ignore it.
