### ISSUE TITLE
Benchmarking Excavator-2-GPU#00-GPU#01 only GPU#00 benchmarks

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1875]
![only one gpu running](https://user-images.githubusercontent.com/801414/41501120-f9424562-7152-11e8-8f1e-0c6a9eadbf04.png)

I downloaded the latest Master and then went thru some of the Pull requests(1872 1870 1868 1867 1864 1863 1862) and merged those with my Master. Benchmarking right now.

Benchmarking Excavator-2-GPU#00-GPU#01 only GPU#00 benchmarks see the screengrab during the time period around 2018-06-16 10:31:39.   I saw it before but never noted the time.  Happened again at 10:54:00, then at 10:58 what it was benchmarking started using both again.

[Excavator-5100_2018-06-16_10-11-58.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2108408/Excavator-5100_2018-06-16_10-11-58.txt)
[MultiPoolMiner_2018-06-16.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2108409/MultiPoolMiner_2018-06-16.txt)
[MultiPoolMiner_2018-06-16_10-11-10.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2108410/MultiPoolMiner_2018-06-16_10-11-10.txt)

**Comment by Kettoch** [comment]
Refer to https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1840 This seems to help.

**Comment by paulpoco** [comment]
I'll try that, thanks.  It is actually #1853 for the code.
