### ISSUE TITLE
Donation Mining should wait for benchmarking to be complete

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1876]
I am happy to have the script donate and I don't even mind that resetting the script causes it to reset its timer.

However, when benchmarking, it should at least wait until it has completed that first.

Requested change:  If there are benchmarks pending, postpone donation mining until 15 minutes after benchmarking is complete.

**Comment by paulpoco** [comment]
If switch to a different version folder, then it runs the Donation run again.

I guess the only to that would be to save some data outside in Windows but then it isn't really portable.

**Comment by Dewbs** [comment]
Why does it matter? If anything the benchmarks will be running non-optimal (profit wise) algos anyway ?

**Comment by Kettoch** [comment]
When I make major changes to the system, I like to watch the rig through the benchmarking looking for errors.

**Comment by Dewbs** [comment]
The errors would be the same whoever the mining recipient is though?

**Comment by aaronsace** [comment]
> The errors would be the same whoever the mining recipient is

**Comment by Kettoch** [comment]
What errors are we talking about?  I am talking about delaying the donation run so that the benchmarking can complete.

**Comment by Dewbs** [comment]
"I like to watch the rig through the benchmarking looking for errors."
