### ISSUE TITLE
Different AMD Cards produce multiple simultaneous miners

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1880]
So I have been working to integrate all these changes into my nvidia system and after making all of these changes stable, I decided to take the working directory and copy it to my other miner.

AMD FX8120 (my old gaming machine) and an RX580 and my old R9-290X.  for some miners (before all these changes), they would mine the same algo on both at similar but varying mining rates.

Of course this ok, as it was amazingly stable.  And even with MSI Afterburner, each has its own OC settings.

With these changes, the cards are identified by the differences in the GPU core.  That is ok, and when it benchmarked, it showed algos for each type and ones that did both.

Can I assume that since it is running the CPU, and two individual miners, that it determined that it was better to run them independently than any miners that could run on both cards?

I think that would be the case but the there does not seem to be a better place to discuss this than here.

My plan is to build a homogeneous rig with one to four Vega's in it but that is for later this year.

I guess the real question is would it seem that choosing a mine for each card (since they are different) would perform better than one that can use both?  My other system is a pair of 1080TIs (my current gaming system).  And it never splits them up after this change.

**Comment by UselessGuru** [comment]
> Can I assume that since it is running the CPU, and two individual miners, that it determined that it was better to run them independently than any miners that could run on both cards?

Since https://github.com/MultiPoolMiner/MultiPoolMiner/commit/7a6172ed0f67cbd37ecd973f35b523ffab4b045e
MPM runs separate miners per card model. This is by design to further optimize your returns.

**Comment by Kettoch** [comment]
This is VERY cool.  I actually saw it use a miner that uses both cards this morning so that answers my question.

Does the donation fee get spread amongst the group of you that are the most active in changes/development?

I am involved with another open source that has a primary and several very active secondaries and they spread the donation fees around ( unless they are specifically sent to one person ).

Just curious because if it is, my donation time is too small for the value I am getting.

**Comment by grantemsley** [comment]
@Kottoch actually its even cooler than @UselessGuru described.

It can do both separate miner per card, or one miner for all cards, or anywhere in between, depending on what the particular miner supports.

Right now only a few miners are doing separate instances for each card, but more will be updated to support that.  There are some miners that work better with a single instance for all the NVIDIA cards for example - and those can stay using all the nvidia cards for that one miner.  Some might only work on 1080s, so they can use ALL the 1080s while other miners mine on your 1070s.  And so on.

So we have a lot of flexibility on what miners run on what cards now.

**Comment by Kettoch** [comment]
We can close this now.
