### ISSUE TITLE
SGminer (all variants) causes crash with AMD

### ISSUE THREAD

**Issue by thinkplaystudios** [MultiPoolMiner/MultiPoolMiner#1881]
I've been battling with this issue with MPM on and off.  I've gone as far as resetting the several rx580's to their default, non-modded bios settings, but it seems the only time I was able to run reliably with sgminer and the AMD cards was when MPM allowed miner consoles to be shown (as opposed to being hidden, the default MPM setting).  When MPM closes the hidden SGminer, it somehow locks up the computer, crashing and prompting a reboot.  This does not seem to be an issue when the SGminer was visible (even if it is minimized), MPM can close SGminer without crashing my computer.

I've noticed the latest iteration of MPM does not have the ability to show the miner consoles?  Am I right?  Will that be coming back, if not, can someone point me in the code where the miners are run hidden?  I'd like to continue to verify this while I have spare time.

Thanks,

**Comment by UselessGuru** [comment]
> I've noticed the latest iteration of MPM does not have the ability to show the miner consoles? Am I right? 

No, you are not :-)
https://github.com/MultiPoolMiner/MultiPoolMiner#command-line-options (-ShowMinerWindows)

**Comment by grantemsley** [comment]
I have several systems with AMD cards running no problems with sgminer.

Usually lockups like that are hardware issues - drivers, overclock, power supply, etc.

The -showminerwindows switch will help you debug it.

**Comment by thinkplaystudios** [comment]
I had at -delay 6.  I'll bump it up to 10 or more and observe.  Worth a try :)

**Comment by thinkplaystudios** [comment]
I'll re-open this when I have time to track this down.  I will open a new issue regarding -ShowMinerWindow not working.
