### ISSUE TITLE
ShowMinerWindow argument not working

### ISSUE THREAD

**Issue by thinkplaystudios** [MultiPoolMiner/MultiPoolMiner#1882]
Putting -ShowMinerWindow was working at some point maybe a week ago, but I just realized it has stopped working.

**Comment by grantemsley** [comment]
Please post both your start.bat and config.txt files and I will take a look.

**Comment by thinkplaystudios** [comment]
[startMPM.bat.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2109534/startMPM.bat.txt)
[config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2109535/config.txt)

There are still some settings there when MPM would run CPU miners even when not specified in the -type switch, etc.

**Comment by thinkplaystudios** [comment]
Oh geesh, I didn't notice that wasn't there, same with disable update.

**Comment by grantemsley** [comment]
@thinkplaystudios we all missed it apparently, so thanks for the bug report :)
