### ISSUE TITLE
MPM does not detect NVIDIA GPUs in mixed configuration

### ISSUE THREAD

**Issue by jweber018** [MultiPoolMiner/MultiPoolMiner#1884]
OK, I think I have a greater understanding of what the issue is now. I applied every fix suggested in the previous issues I opened, all to no avail, UNTIL I changed the startup parameters from "-type nvidia" to "-type amd,nvidia". My rig consists of 6 GTX 1070s and 6 RX 570s, and so far it has been working no problem (in fact, using the latest "official" release of MPM I have no issues). So I think it could have something to do with device detection order?

I am not familiar with that section of the code, so I cannot say for sure. But just wanted you guys to know it's not MPM not downloading anything, it's MPM not detecting anything NVIDIA related.

I even tried merging #1868 #1870 and #1872 and the problem persists.

Again, thanks in advance, sorry for nagging you and let me know if you need any additional data.

**Comment by UselessGuru** [comment]
"-type nvidia" to "-type amd,nvidia".

The parameter name has changed from -type to -devicename

**Comment by jweber018** [comment]
Yeah, I know. Already tried that too :(

**Comment by jweber018** [comment]
A little more data / context: If I remove line 348 from MultiPoolMiner.ps1 ("Where-Object {$_.DeviceName} #filter miners for non-present hardware"), it works just fine but ignores the -devicename parameter (it even wants to mine with the CPU). My lowly-educated guess is that the software is failing to detect the NVIDIA cards. I will try reinstalling drivers in a while and report back.

**Comment by UselessGuru** [comment]
Please post http://localhost:3999/devices

**Comment by jweber018** [comment]
Nevermind guys, I reinstalled the drivers and it started working. No clue on what was the issue, but everything is functional now. Sorry for the bother.
