### ISSUE TITLE
Running a rig with mixed cards and models

### ISSUE THREAD

**Issue by lee-aaron** [MultiPoolMiner/MultiPoolMiner#1887]
Hey all, finally on summer break and I have a 4 card rig with 2 GTX 1070s and 2 RX 580s. It's hooked up but it seems to not be utilizing both of the graphics cards per model. Is there a proper way to go about this? I notice the hash rate reported is only for one graphics card (ie AMD = ~27 MH/s).
Here are the following cards in the system:
- GTX 1070 PNY
- GTX 1070 MSI Gaming X
- RX 580 MSI
- RX 580 XFX

I understand that it's not good to mix and match even the models but it was just what was within my price budget per card at the time. I notice the 1070 PNY and 580 MSI are running the algos but the Gaming X doesn't even have its fans on (XFX has fans spinning but does that even on no load). Does it have to do with the way I wired up the graphics cards? I have the two GTX 1070s linked on a SATA cable from the risers to the PSU and same for the 580s.
Thanks for your help!

**Comment by UselessGuru** [comment]
How about some logs so that I can compare with the findings of my crystal ball.

**Comment by lee-aaron** [comment]
[MultiPoolMiner_2018-06-18_21-42-06.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2116349/MultiPoolMiner_2018-06-18_21-42-06.txt)
[CcminerTpruvot-4068_2018-06-18_21-55-37.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2116354/CcminerTpruvot-4068_2018-06-18_21-55-37.txt)
[ClaymoreNvidia-23333_2018-06-18_21-31-31.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2116356/ClaymoreNvidia-23333_2018-06-18_21-31-31.txt)
[ClaymoreAmd-13333_2018-06-18_21-31-30.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2116355/ClaymoreAmd-13333_2018-06-18_21-31-30.txt)

I've attached some logs and took out my status key just for privacy reasons.

**Comment by UselessGuru** [comment]
@lee-aaron

You are not running the latest version. https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

Run this and upload the contents of http://localhost:3999/devices

**Comment by lee-aaron** [comment]
[Devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2116476/Devices.txt)
Yeah it doesn't see the MSI Gaming X 1070 or the XFX RX 580.

**Comment by UselessGuru** [comment]
> Yeah it doesn't see the MSI Gaming X 1070 or the XFX RX 580.

This is local (driver???) issue and has nothing to do with MPM code. Sorry mate.
Try cleaning up your windows drivers. DDU is your good friend.

**Comment by lee-aaron** [comment]
Those two graphic cards are in 16x slots with 1x risers. The other two are in 1x slots. I don't see any other devices in Device Manager but I don't think there are any other BIOS changes I need to make. I have an ASUS Z370-A and I did set the PCI speed to Gen 2 (tested with Gen 1 too). I'll try looking into other ways to get those two to be detected.

**Comment by UselessGuru** [comment]
> has anyone had success in getting them to work in the 16x buses?

No me... I use 1x slots.

You will have to check the PCI lanes configuration in BIOS and manual. Not all chipsets/mobos allow full bandwith to all slots.
