### ISSUE TITLE
Runtime Bug in updating Stats

### ISSUE THREAD

**Issue by lee-aaron** [MultiPoolMiner/MultiPoolMiner#1888]
[MultiPoolMiner_2018-06-19_20-36-16.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2117773/MultiPoolMiner_2018-06-19_20-36-16.txt)

It seems that it's passing in NaN to the stats function to parse in Include.psm1. I'm using the latest master version.

**Comment by angelics** [comment]
#1870

**Comment by lee-aaron** [comment]
Ah ok thanks. Will close this then
