### ISSUE TITLE
Add new Lyra2v2 miner for AMD

### ISSUE THREAD

**Issue by JamesJ-Yuan** [MultiPoolMiner/MultiPoolMiner#1894]
This new miner was released and it's the fastest Lyra2v2 miner I've seen for AMD

https://github.com/CryptoGraphics/lyclMiner

Speeds here:
https://www.reddit.com/r/vertcoin/comments/8svyvr/amd_full_release/

**Comment by alucard20724** [comment]
the posted results for new Lyra2v2 miner
AMD VEGA series
VEGA 64 -75mh/s
VEGA 56 -60mh/s

AMD 500 series
RX 580 -42mh/s
RX 570 -36mh/s
RX 560 -16mh/s
RX 550 -8mh/s

AMD 400 series
RX 480 -32mh/s

AMD 300 series

AMD 200 series
R9 280X -23mh/s
R9 270 ~13mh/s
7970- 21mh/s

**Comment by UselessGuru** [comment]
For full MPM support OpenCL detection needs to be enhanced: 

Selecting specific devices
By default, all devices are used. However it is possible to select specific ones using a **PCIeBusId** option.

@aaronsace Can you add PCIeBusId?

**Comment by UselessGuru** [comment]
Miner does not have an API and also does not work well as API='wrapper'

**Comment by UselessGuru** [comment]
Miner development seems to have come to a halt.
Without API the integration into MPM is not possible.
