### ISSUE TITLE
Adding Ravencoin Miner 3.1

### ISSUE THREAD

**Issue by centreece** [MultiPoolMiner/MultiPoolMiner#1895]
Could you add Ravencoin Miner 3.1?

with Cuda 9.2: https://github.com/RavencoinProject/RavencoinMiner/releases/tag/v3.1-cu92
with Cuda 9.1: https://github.com/RavencoinProject/RavencoinMiner/releases/tag/v3.1-cu91

**Comment by Majorbafe** [comment]
I added RavencoinMiner v3.1 cu91 and cu92 on both variants (x86 and x64) and for x16r the results were lower than CcminerZealot, CcminerSuprminer CcminerTpruvot and CcminerPigeon64cu91.

Can't see how RavencoinMiner is relevant...
