### ISSUE TITLE
Weird PC lockup with Windows Antivirus blocking access to hardware

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1900]
When i hard rebooted there was tons of Antivirus messages saying it was blocking access to hardware.

Anyone see this before?  I have the Folder for MPM excluded in Antivirus.  There was an update to Virus Definitions today but could not see what time that happened.
![screenshot_6](https://user-images.githubusercontent.com/801414/41803671-2bfe0210-7640-11e8-8216-0680cc555d0e.png)

[PhoenixMinerNvidia-23334_2018-06-22_14-09-41.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2129451/PhoenixMinerNvidia-23334_2018-06-22_14-09-41.txt)

[PhoenixMinerNvidia-23334_2018-06-22_13-17-30.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2129533/PhoenixMinerNvidia-23334_2018-06-22_13-17-30.txt)

**Comment by Kettoch** [comment]
you have SLI turned on?  This happens to me every time I forget to switch between SLI and NON.  My NVidia system is also the one I game with so I need to switch back and forth.

**Comment by Exodus4400** [comment]
I found that the mining program triggers the Timeout Detection and Recover (TDR) RegWord on multiple gpu system. Normally it's 2 seconds. I increased it to 8. This is a registry edit so use at your own risk, but I have had success in avoid this problem. [This is the Microsoft website that talks about the registry values and what they do.](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys)
Here are the steps:
Registry address:
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDrivers
Create an entry as TdrDelay as a DWORD (double word). It wasn't there for me so I had to add it.
Default value is 2 seconds, I increased it to 8 seconds. Make sure the entry is in decimal (as opposed to hex).

**Comment by thinkplaystudios** [comment]
Keep in mind if you have a 64bit Windows you need to create QWORD, and DWORD for 32bit.

**Comment by paulpoco** [comment]
I tried this and am still seeing it.
![image](https://user-images.githubusercontent.com/801414/42922645-67f73d22-8ad6-11e8-956b-f2802bce3c63.png)

**Comment by paulpoco** [comment]
@Kettoch my SLI is set to disabled.

**Comment by paulpoco** [comment]
I even got the same message yesterday with Chrome.

**Comment by paulpoco** [comment]
Tried all the suggestions still get them from time to time.

Really noticed it will happen when waking the Monitors from sleep to use the computer.

@Exodus4400 does anyone else get this?  Like i said I even got it once on chrome.exe.
