### ISSUE TITLE
ccminer Delos recording incorrect equihash hashrate

### ISSUE THREAD

**Issue by Exodus4400** [MultiPoolMiner/MultiPoolMiner#1904]
I'm getting a recorded hash rate of 11 mega sols for my 2x 1060's, which isn't correct. Anyone else having this issue?

**Comment by UselessGuru** [comment]
Can you verify by re-benchmarking this algo (remove the stat file).

It does not seem to make sence because all Ccminer use the same method to gather hash rate.

**Comment by Exodus4400** [comment]
Re-benchmarking caused it to go back to a reasonable value but I noticed the same thing happen on one of my other rigs. It triggers the watchdog and then seems to be okay. I ran it stand alone and found that the initial hashrate it reports can be extremely high sometimes. I guess it's okay? Thoughts?

**Comment by UselessGuru** [comment]
> I guess it's okay? Thoughts?

MPM cannot decide what hash rate is reasonable.... :-) I will take what ever the miner reports (API query).

**Comment by Majorbafe** [comment]
So... I've been reading that DelosMiner has some virus in it? 
And that the donation mining is very dodgy.
Can anyone elaborate? If so, it should be removed at once from MultiPoolMiner.

By the way: 1st post ever on github.

**Comment by UselessGuru** [comment]
@Majorbafe 

Where did you read this?

**Comment by Majorbafe** [comment]
https://bitcointalk.org/index.php?topic=4344544.0
Browse the thread and you will find people complaining.
Also there are some videos on youtube about this problem.
Something about the miner hacking wallets...
