### ISSUE TITLE
Downloader only works when binaries missing.

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1906]
The current master copy, does not seem to update miner binaries unless the binaries are missing.

Just had an incident with several of the recent miner binary updates and every single one required me to do delete the binary before it would download again.

Even if the new URI and Hash were changed in the files, it did not change.

**Comment by grantemsley** [comment]
Yes, the built in downloader works like that.  Eventually I will see about replacing it with how Get-Binaries works.

If you run `Get-Binaries.ps1 -Overwrite` it will replace any outdated miners with new ones and clear the stats for them so they get rebenchmarked.

**Comment by Kettoch** [comment]
get-binaries showed me the reason I was getting downloading flashes....

Posted an issue with it.  I hope we do convert to this.

**Comment by thinkplaystudios** [comment]
@grantemsley you mentioned using "Get-Binaries.ps1 -Overwrite", this is good to know!  I didn't know this capability existed.
