### ISSUE TITLE
Miner Issue: NVIDIA-Allium

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1908]
This miner apparently does not work.  I wonder if this is the source of the downloader flashing all the time.

**Comment by UselessGuru** [comment]
The miner binary is no longer available for download.
It is now included in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1897.

So the miner file is obsolete. I'll create a separate PR to remove NVIDIA-Allium.
