### ISSUE TITLE
PhoenixMiner 3.0c

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1914]
PhoenixMiner 3.0c: fastest Ethereum/Ethash miner with lowest devfee (Windows)
https://bitcointalk.org/index.php?topic=2647654.0

> Changes in version 3.0c (since 2.9e):
> - Implemented auto-tune function which will find the best GT value for each GPU. You can activate it by either omitting the -gt parameter in the command line, or by pressing 'z' in the console. Note that auto-tune process takes about 3 to 5 minutes on average and during this time the hashrate will be lower and will go up and down. You can abort the auto-tuning by pressing the 'g' key in the console window.
> - Added support for 'x' key in console window. This will allow you to select a single GPU for manual or automatic GT tuning.
> - Added support for direct mining (without DAG switching for DevFee) of the following coins: Nekonium (NUKO), MIX, EtherGem (EGEM), AURA, Hotelbyte Coin (HBC), Genom (GEN), EtherZero (ETZ), Callisto   (CLO). See the -coin option documentation below for details how to specify the coin you are mining.
> - Added support for on-the-fly reload of config.txt file and applying the new options by pressing the key 'c' in the console window. Note that most options require restart in order to change. Currently the follwing options can be changed without restarting: -mi, -gt, -clf, -nvf, and all hardware control parameters (-tt, -fanmin, -fanmax, -powlim, -tmax, -cclock, -cvddc, -mclock, -mvddc). This allows more convenient adjustment and fine-tuning of the mining rigs
> - Added -cdmrs option to reload the settings if config.txt is edited/uploaded by a remote manager. This allows you to change and reload the config.txt options via remote manager without access to the console window of the miner.
> - Small improvements in AMD kernels
> - Added -nvf 3 setting that could solve some problems with unstable Nvidia cards (but may affect hashrate negatively)
> - Added option -acm to turn on AMD compute mode on the supported GPUs. This is equivalent of pressing 'y' in the miner console.
> - Added option -retrydelay that sets the pause between the reconnection attempts in seconds (min value 0, default value: 20)
> - Added option -resetoc to reset the HW overclocking setting on startup to their default values
> - Added option -gpureset, which forces full reset of the GPU when the miner is paused (or before DAG generation when switching DAG epochs). This is designed to avoid problems like the hashrate drop of GeForce GTX1080 Ti after pause/resume. This option can be specified per GPU and is turned on by default for GTX1080 Ti.
> - Added option -gser for serializing of DAG creation if your PSU(s) can't take all GPUs generating DAG simultaneously.
> - Graceful shutdown when closed by the close button of the console window (including reseting OC settings to defaults)
> - Added option -gsi to set the speed stats interval (5-30 seconds, default 5; 0 turns off the speed stats). The detailed stats are still shown every 45 seconds and aren't affected by the -gsi value
> - Fixed crashing with Vega cards with AMD drivers 18.4.1 and newer
> - Many small fixes and changes

My start_miner.bat for a 6 card NVIDIA rig:
`PhoenixMiner.exe -pool europe.ethash-hub.miningpoolhub.com:17020 -wal username.workername -pass x -proto 4 -nvidia -gpus 1,2,3,4,5,6`

**Comment by UselessGuru** [comment]
I am working on it
