### ISSUE TITLE
FireIce miner (Nvidia) / Ideas wanted

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1920]
I try to create a per-device miner file for FireIce (https://github.com/fireice-uk/xmr-stak)

The Nvidia variant requires individual config files info per card, e.g.:

[nvidia.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2141178/nvidia.txt) (The miner created this file on first run, it will NOT get automatically updated when cards get added)

So to get per-device mining working I need to build the '"gpu_threads_conf"' section for each miner instance. As I can see there is no other way of selecting individual cards.

Here is the challenge:
I can not find way to properly determine the required parameter values.
By looking at the miner source code I can see that for optimal calculations the CUDA architecture level is required (code_extra.cu: props.mayor / props.minor):

```
{
		/* sm_20 devices can only run 512 threads per cuda block
		 * `cryptonight_core_gpu_phase1` and `cryptonight_core_gpu_phase3` starts
		 * `8 * ctx->device_threads` threads per block
		 */
		ctx->device_threads = 64;
		constexpr size_t byteToMiB = 1024u * 1024u;

		// no limit by default 1TiB
		size_t maxMemUsage = byteToMiB * byteToMiB;
		if(props.major == 6)
		{
			if(props.multiProcessorCount < 15)
			{
				// limit memory usage for GPUs for pascal < GTX1070
				maxMemUsage = size_t(2048u) * byteToMiB;
			}
			else if(props.multiProcessorCount <= 20)
			{
				// limit memory usage for GPUs for pascal GTX1070, GTX1080
				maxMemUsage = size_t(4096u) * byteToMiB;
			}
		}
		if(props.major < 6)
		{
			// limit memory usage for GPUs before pascal
			maxMemUsage = size_t(2048u) * byteToMiB;
		}
		if(props.major == 2)
		{
			// limit memory usage for sm 20 GPUs
			maxMemUsage = size_t(1024u) * byteToMiB;
		}

		if(props.multiProcessorCount <= 6)
		{
			// limit memory usage for low end devices to reduce the number of threads
			maxMemUsage = size_t(1024u) * byteToMiB;
		}

```

@aaronsace: Could you add this as a property of $Devices (using OpenGL)?
Other options:
- Retrieve the information from NVIDIA_SMI
- Build a lookup table of some sort which includes parameter sets for all cards (where can we get all that information from? How to maintain it?)
- Determine architecture type from device name (will this work reliably?)
- Retrieve the values from the automatically created NVIDIA.TXT (Problems: a) JSON file contains comments which ConvertFrom-JSON cannot handle, b) does not necessarily contain info for all installed cards)

**Comment by grantemsley** [comment]
index is easy - we already have that.

affine_to_cpu should probably be set to true based on the comments in that file

bfactor and bsleep can be left at their defaults of 6 and 25 respectively.

That leaves threads and blocks to figure out.  Looking through the issues on their github repo I see even the defaults don't always work for people - so it's pretty much trial and error to see what works.  Setting them too low and the miner is slow, set them too high and it crashes or gets even slower.  It's not just the card model that will affect it either - overclock settings and such will too.

Which means we could treat them like the intensity options in ClaymoreEthash - benchmark a few different settings on each card and see what works best.

**Comment by UselessGuru** [comment]
> benchmark a few different settings on each card and see what works best.

We do not have all available card models... :-(
Keeping/managing parameter sets for each and every card is not desirable, nor feasible.

Best results are achieved if we can use as much ram as possible (= very high values for threads and blocks). We know the available amount of ram.
As my try and error test have shown there is currently no way to calculate the optimal settings for these two values based on the available info in OpenCL.

> Looking through the issues on their github repo I see even the defaults don't always work for people

In the past they did not (I even opened an issue on that :-)).
For best results I would like to use the same algorithms as in the original miner.

**Comment by grantemsley** [comment]
> We do not have all available card models... :-(
Keeping/managing parameter sets for each and every card is not desirable, nor feasible.

I meant for each card in a particular user's system, not for each model of card Nvidia makes.  Some will fail, some will be slow, but the best one for that particular card in that particular person's system will come out ahead.

> As my try and error test have shown there is currently no way to calculate the optimal settings for these two values based on the available info in OpenCL.

So what is it based on then?  The code you posted shows it setting memory limits, but not the threads or block size from what I can see.

**Comment by grantemsley** [comment]
`ctx->device_threads = max_intensity / ctx->device_blocks;`

Do you know where is ctx (specifically the device_blocks property) being defined?
You can get the number of stream processors from OpenCL already - but it doesn't tell you how many cores each stream processor has, which may or may not be important.

**Comment by UselessGuru** [comment]
The main problem really is to get the correct amount of available memory as done in the first snippet. From there we can calculate the correct values (from what I gather).
The calculation is based on:
- available memory
- number or stream processors
- architecture

**Comment by angelics** [comment]
--nvidia (gpuindex_algo).txt -> --nvidia 01234_CryptoNightV7.txt
any gpu that is added or removed will have diff .txt for diff config

**Comment by UselessGuru** [comment]
@angelics 

> will have diff .txt for diff config

Getting the values for the config is the challenge, not how to pass the config file... :-)

**Comment by UselessGuru** [comment]
Feature requested here:
https://github.com/fireice-uk/xmr-stak/issues/1692

**Comment by Spudz76** [comment]
That `ctx` is from the CUDA backend and is part of an internal miner context struct. Typically xmr-stak does not use OpenCL to drive nVidia as that's just another layer on top of CUDA, waste of glue.
CUDA reports memory amounts and everything you are looking for, but they do not export it (properly?) to OpenCL always.  We also have heck of a time with some AMD older gen stuff not reporting correct info in OpenCL (solution there is to run antiquated AMD 13.x drivers).

The `ctx.device_threads` and `ctx.device_blocks` come directly from the config file.
If you pass `-1` it will autocalc at runtime start-up (once) identical to how it would to generate a new config file.
So make a config file with `-1` for everything and it does what you're trying to duplicate externally?

That being said the defaults are never optimal, and some combos of cores/memory will and do crash hard on default guesses.  Others run but not best possible speed.  Most are pretty close to optimal but hand tuning always opens up a little more hashrate.

I suspect some of the workloading depends on memory type as well, which we can't obtain reliably.  GDDR3 cards just don't have the bandwidth to do a "full" load of work so those need detuning from "math derived" settings, GDDR5 generally work good on defaults, but them GDDR5x or HBM sort of don't again (those seem to like multiple host threads per card, which xmr-stak autoconfig does not and probably will not handle in autoconfig, but is completely possible by hand).

**Comment by UselessGuru** [comment]
> So make a config file with -1 for everything 

This is what I create:

HW config file (FireiceNvidia-1xGTX10606GB.txt):
```
    "gpu_threads_conf":  [
                             {
                                 "index":  1,
                                 "threads":  -1,
                                 "blocks":  -1,
                                 "bfactor":  8,
                                 "bsleep":  100,
                                 "affine_to_cpu":  false,
                                 "sync_mode":  3
                             }
                         ],
    "platform_index":  {
                           "PlatformId_Index":  1
                       }
```

Pool file (FireiceNvidia-1xGTX10606GB-MiningPoolHubCoins-CryptoNightV7-Port3301.txt):
```
    "pool_list":  [
                      {
                          "pool_address":  "europe.cryptonight-hub.miningpoolhub.com:20596",
                          "wallet_address":  "[Username.Workername]",
                          "pool_password":  "x",
                          "use_nicehash":  true,
                          "use_tls":  false,
                          "tls_fingerprint":  "",
                          "pool_weight":  1,
                          "rig_id":  "BlackBox"
                      }
                  ],
    "currency":  "cryptonight_v7",
    "call_timeout":  10,
    "retry_time":  10,
    "giveup_limit":  0,
    "verbose_level":  3,
    "print_motd":  true,
    "h_print_time":  60,
    "aes_override":  null,
    "use_slow_memory":  "warn",
    "tls_secure_algo":  true,
    "daemon_mode":  false,
    "flush_stdout":  false,
    "output_file":  "",
    "httpd_port":  3333,
    "http_login":  "",
    "http_pass":  "",
    "prefer_ipv4":  true
```

and it does not work 👎 
```
xmr-stak.exe --noUAC --noAMD --noCPU -i 3301 -C FireiceNvidia-1xGTX10606GB-MiningPoolHubCoins-CryptoNightV7-Port3301.txt --nvidia FireiceNvidia-1xGTX10606GB.txt
-------------------------------------------------------------------
xmr-stak 2.4.5 b3f79de3

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-07-11 11:44:28] : Mining coin: cryptonight_v7
[2018-07-11 11:44:28] : Starting NVIDIA GPU thread 0, affinity: 623648224.

GPU -351276648: invalid device ordinal
C:/xmr-stak/xmr-stak-2.4.5/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu line 456
[2018-07-11 11:44:28] : Setup failed for GPU 0. Exiting.
```

**Comment by Spudz76** [comment]
I have tried this also and indeed, it doesn't work.  I swear I saw some '-1' handling in the code so I'm not sure why it doesn't work.

I get 555.5MH/S from each 1060 using 32/30 (default nvidia.txt)
