### ISSUE TITLE
Miner (CcminerKlaust) requires CUDA version 9.2.00 or above

### ISSUE THREAD

**Issue by skovesh** [MultiPoolMiner/MultiPoolMiner#1921]
I have only ATI radeon boards. Can I install the CUDA version requested without interferring with my graphic Radeon settings ? How?

**Comment by UselessGuru** [comment]
You might be better off posting in another place. This has nothing to do with MPM per se.

**Comment by grantemsley** [comment]
@UselessGuru It kind of does though.

```
# Miner requires CUDA 9.2
$DriverVersion = (Get-Device | Where-Object Type -EQ "GPU" | Where-Object Vendor -EQ "NVIDIA Corporation").OpenCL.Platform.Version -replace ".*CUDA ",""
$RequiredVersion = "9.2.00"
if ($DriverVersion -lt $RequiredVersion) {
    Write-Log -Level Warn "Miner ($($Name)) requires CUDA version $($RequiredVersion) or above (installed version is $($DriverVersion)). Please update your Nvidia drivers. "
    return
}
```

That will print the warning message on systems that have no NVIDIA cards at all (since $DriverVersion will be null).  It should only print that warning if there actually are NVIDIA cards, and the drivers are too low of a version.
