### ISSUE TITLE
[Question] Config.txt

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1922]
I want to use the method to configure by the Config.txt file.

first of all, I need to eliminate some settings in the start.bat file I assume?

next; for example the excludePools: do I need them to add like:

"ExcludePoolName": "pool-a,pool-b, etc",

OR like:

"ExcludePoolName": "{'pool-a', 'pool-b''}?

just to be sure. every parameters that is there will be set by the start.bat?

**Comment by UselessGuru** [comment]
> first of all, I need to eliminate some settings in the start.bat file I assume?

MPM will use whatever values you have in config.txt:
a) If a parameter value looks like "$Paramname" then MPM will use the value from the command line (if given), or the hardcoded default value at the beginning of MultiPoolMiner.ps1
b) Put a hard coded value into config.txt. These values will take precedence over a)

>  do I need them to add like:
[See readme](https://github.com/MultiPoolMiner/MultiPoolMiner#advanced-config-options-are-available-via-configtxt). https://jsonblob.com/ is very helpful too.
For each parameter variable type (see source code) you need to use the correct syntax. Unfortunately we cannot put comments in the JSON files for guidance (comments are not supported by ConvertFrom-JSON / ConvertTo-JSON).

**Comment by m-bosch** [comment]
Hi,

Thank you for the clear and fast response. I did look at the readme where you show how to set booleans. unfortunately i couldnt find anything for what i discribed.

how to exclude multiple pools for example. the simple question is, should this be a json array of just a string?

**Comment by UselessGuru** [comment]
> should this be a json array of just a string

Q: Of what type is ExcludeAlgorithm? -> Array
