### ISSUE TITLE
Display of Miner info some parts get cut off with "..."

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1926]
Display of Miner info some parts get cut off with "..."
![image](https://user-images.githubusercontent.com/801414/42118395-ac3f6352-7bb7-11e8-8c15-dd6e0878a436.png)

It looks like when there is 3 or more digits like xxx.xx it will never show the whole left part of the number.

Also it doesn't happen all the time.
![image](https://user-images.githubusercontent.com/801414/42118497-4b53b4f2-7bb8-11e8-839c-e696ec7f6d12.png)

**Comment by UselessGuru** [comment]
That is part of PowerShells internal life... PS decides when add dots and when not depending on the available screen space. 

Workaround: Make the PowerShell window larger than the output, or reduce font size.

**Comment by paulpoco** [comment]
It is full screen.
![image](https://user-images.githubusercontent.com/801414/42296658-616fe708-7fad-11e8-821f-778020e23449.png)
