### ISSUE TITLE
Device type property

### ISSUE THREAD

**Issue by thinkplaystudios** [MultiPoolMiner/MultiPoolMiner#1927]
Hi guys, this is more of a question than an issue:

In the bat file, you can specify the -devicename to amd, nvidia, cpu, but when the powershell script is running, the devices are labeled as gpu#01, gpu#02, etc.

Is there a way to determine if the running miner is for amd or nvidia?  $miner.devicename shows gpu#01, etc.

**Comment by Kettoch** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1872

**Comment by thinkplaystudios** [comment]
The challenge that I see is that some of the miner binaries can be used for both AMD and Nvidia.
