### ISSUE TITLE
Discussion: Naming scheme for miners (binary directories and miner file/stats)

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1931]
Currently the miner binary directories come in a variety of different names, some include AMD or NVIDIA, other include an algorithm...

Here is my suggestion:

All Miner binary directories should follow a common naming scheme like

**Type**-**MinerName**[**Algorithm_Norm**]

- Type can by any of:
AMD, CPU, NVIDIA or any combination concatenated by underscore (values sorted alphabetically). 
E.g. if a miner works for AMD and NVIDIA it will be AMD_NVIDIA

- MinerName
 should include common name information like Excavator or Ccminer

- Algorithm_Norm 
optional, only when miner is only for one single algorithm family (e.g. CryptoNight), as normalized by Get-Algorithm

The structure could then look something like this:
```
AMD-CastCryptoNight
AMD-ClaymoreCryptoNight
AMD-ClaymoreEquihash
AMD-ClaymoreNeoScrypt
AMD-EthminerEthash
AMD-FireIceCryptoNight
AMD-MkxminerLyra2RE2
AMD-NsgminerNeoScrypt
AMD-SgminerAvermore
AMD-SgminerBitcore
AMD-SgminerLyra2re2
AMD-SgminerLyra2z
AMD-SgminerSkein
AMD-Sgminer-Xevan
AMD-SgminerKL
AMD-SgminerNiceHash
AMD-SRBMiner
AMD-XmRigCryptoNight
AMD_NVIDIA-PhoenixMiner
CPU-CcminerTPruvot
CPU-ClaymoreCryptoNight
CPU-FireIceCryptoNight
CPU-XmRigCryptoNight
NVIDIA-CcminerAlexis78hsr
NVIDIA-CcminerAnxmodPHI
NVIDIA-CcminerDelos
NVIDIA-CcminerKlausT
NVIDIA-CcminerLyra2RE2
NVIDIA-CcminerLyra2z
NVIDIA-CcminerNanashi
NVIDIA-CcminerNevermore
NVIDIA-CcminerPigeonCoin-X16s
NVIDIA-CcminerSib
NVIDIA-CcminerSkunk
NVIDIA-CcminerSP
NVIDIA-CcminerSuprMiner
NVIDIA-CcminerTPruvot
NVIDIA-CcminerXevan
NVIDIA-CcminerZealot
NVIDIA-CryptoDredge
NVIDIA-DSTMEquihash
NVIDIA-EthminerEthash
NVIDIA-EWBFEquihash
NVIDIA-Excavator
NVIDIA-ExcavatorNHMP
NVIDIA-FireIceCryptoNight
NVIDIA-HSRPalgin
NVIDIA-JAMNeoScrypt
NVIDIA-NsgminerNeoScrypt
NVIDIA-XmRigCryptoNight
```

Edit 07/09/2018: Removed dash between Name and optional algo. This was all minernames will match aaaa_bbb

**Comment by DarenDaigle** [comment]
Wow @uselessguru that is a great idea.

**Comment by grantemsley** [comment]
I agree, renaming them that way would be a bit simpler to tell at a glance which miner is which.

**Comment by UselessGuru** [comment]
Beginning with 3.1.0 all miners will follow this name scheme
