### ISSUE TITLE
Devicename not working

### ISSUE THREAD

**Issue by caniko2** [MultiPoolMiner/MultiPoolMiner#1936]
I get the following error:
A parameter cannot be found that matches parameter name 'devicename'.

**Comment by UselessGuru** [comment]
Logs please... My crystal ball is currently in maintenance.

**Comment by caniko2** [comment]
It happens before the log is created. I get the following red text on cmd:
C:\Miners\MPM\MultiPoolMiner.ps1 : A parameter cannot be found that matches parameter name 'devicename'.
At line:1 char:151
+ ... -region europe -currency btc,usd,eur -type nvidia -devicename nvidia# ...
+                                                       ~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [MultiPoolMiner.ps1], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,MultiPoolMiner.ps1

**Comment by UselessGuru** [comment]
By the looks of it you are not using the latest code...

Line 151 is
$WalletDonate = @("1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb", "1Fonyo1sgJQjEzqp1AxgbHhGkCuNrFt6v9")[[Math]::Floor((Get-Random -Minimum 1 -Maximum 11) / 10)]
and has nothing to do with your error.

Please download and install  the lastest ZIP file: https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

**Comment by caniko2** [comment]
Thanks! The release page is very outdated :D
