### ISSUE TITLE
Pool Balance API Errors

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#1940]
Hi guys,

Im getting the 2 following erros from the latest commit:

2018-07-04 14:18:19 VERBOSE: Pool Balance API (MiningPoolHub) has failed - no API key specified.
2018-07-04 14:18:19 VERBOSE: Pool Balance API (ZergPool) has failed - no wallet address specified.

Im running MPM only with MPH and ZergPool. Ive edited the generated Default.txt config file to include the ZergPool config:

    "ZergPool": {
      "LTC": "LeG(…)GvC",
      "Worker": "$WorkerName" 
    },

Oddly the benchmark is running and the command lines for ZergPool is being generated correctly with the LTC address.

As for MPH im at a loss. Is there something missing?

PS: also getting: 

2018-07-04 14:26:13 ERROR: Failed to connect to miner (Excavator-2-GPU#03).

**Comment by grantemsley** [comment]
Are you certain you're up to date - specifically, that this PR was included? https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1932

@UselessGuru why did you change $ShowPoolBalancesExcludedPools default to true?  I thought you wanted it off by default.

@titvs The balance checking may only give proper results when mining to BTC, not other coins.  I'm not entirely sure since I only mine to BTC so can't really test it.

**Comment by titvs** [comment]
@grantemsley Yeap, downloaded the latest commit this morning (GMT timezone)… Did the specified PR got merged with the master branch? Weird...

**Comment by grantemsley** [comment]
Oh I see what's wrong.  Because the balance checking is expecting to see a BTC address.  It runs because the pool is configured, but fails because there is no BTC address.

In any case it's perfectly fine to ignore that message.  Eventually I may add checking balances of other coins.

**Comment by titvs** [comment]
That leaves the Excavator issue. I guess it was already reported

**Comment by UselessGuru** [comment]
> @UselessGuru why did you change $ShowPoolBalancesExcludedPools default to true? I thought you wanted it off by default.

Can't remember, but I think it is better to turn it off...
