### ISSUE TITLE
Web interface #1939 not showing Balances

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1943]
[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2167443/Config.txt)
I x'd out part of my API ID and Key.

[ClaymoreEthash-Keccak-30-GPU#00-GPU#01-5001_2018-07-05_09-36-35.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2167451/ClaymoreEthash-Keccak-30-GPU.00-GPU.01-5001_2018-07-05_09-36-35.txt)
[MultiPoolMiner_2018-07-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2167452/MultiPoolMiner_2018-07-05.txt)
[MultiPoolMiner_2018-07-05_09-29-57.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2167453/MultiPoolMiner_2018-07-05_09-29-57.txt)
[MultiPoolMiner_2018-07-05_09-35-35.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2167454/MultiPoolMiner_2018-07-05_09-35-35.txt)
[Start.bat.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2167467/Start.bat.txt)

**Comment by grantemsley** [comment]
Have you by chance also merged #1941?  Add `-showpoolbalances` to the command line in your start.bat, without that it doesn't check your balances so it doesn't show in the script or web interface.

**Comment by paulpoco** [comment]
I had all PRs but was missing "-showpoolbalances" in start.bat.

Put that in my start.bat, all works and looks like your screenshot.
