### ISSUE TITLE
https://multipoolminer.io/miners missing miners

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1944]
Went to add -ExcludeMinerName to my start.bat to save Benchmarking time and went to the miner listing page and these miners are missing:

CcminerSuprminer
CcminerDelos
CcminerNevermore
CcminerAlexis

**Comment by UselessGuru** [comment]
> these miners are missing

???

**Comment by grantemsley** [comment]
@UselessGuru I think he means the website hasn't been updated in awhile.  Which is true... @fonyo was handling that, and I haven't seem him around in quite awhile.

**Comment by paulpoco** [comment]
I meant the document at that site.
