### ISSUE TITLE
Add variants of algos? (ig - Equihash-BTG)

### ISSUE THREAD

**Issue by AndyWongDev** [MultiPoolMiner/MultiPoolMiner#1945]
Is there an FAQ to manually copy an algo and just set the parameters into the code for BTG? I want to switch between Equihash, Ethash, and Equihash-BTG

**Comment by UselessGuru** [comment]
Equihash-BTG is currently only available at MinigPoolHub(Couns). But their API reports wrong information (incorrect host names).

So to get it working you not only need a miner supporting it, but also a working pool. Be patient. MPM will support it once the pool issues are sorted out (this is our of our control).

**Comment by paulpoco** [comment]
With regards to BTG at MPH, Auto exchange has not worked since May 18th because the Bittrex wallet is Inactive.

**Comment by jasdjensen** [comment]
So in the mean time if we just add "-ExcludeMinerName EWBF" to our batch file.. that will stop any useless mining of Bitcoin Gold?  What else uses EWBF?  Is there a way to stop BTG only (coin restriction instead of algorithm restriction)?

**Comment by UselessGuru** [comment]
> So in the mean time if we just add "-ExcludeMinerName EWBF" to our batch file

No, EWBF is mining old Equihash. Like all the other Equihash miners.
This algo is still used by Zcash and other currencies.

Equihash-BTG is an all-new algorithm aka Equihash_144_5 and is used to mine Bitcoin-Gold

**Comment by jasdjensen** [comment]
So what you're saying is since it's new, any old algorithm/miner combinations don't need to be excluded to stop them mining on the old fork, right?

**Comment by UselessGuru** [comment]
Correct. To mine Bitcoin-BTG you will need a new miner (in the works).

**Comment by UselessGuru** [comment]
Miner for Equihash-BTG and other new Equihash variants is available for testing:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2002

**Comment by CryptohoboJustin** [comment]
Multipoolminer still does not feature equihash-btg. Is there a way to make this happen, for myself at least?
