### ISSUE TITLE
Failed to update MultiPoolMiner

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1946]
HI All,

im getting the following error when I execute the start.bat file.

im using the version till commit: 1893

> 2018-07-05 21:16:01 INFO: Starting MultiPoolMiner® v3 © 2017-2018 MultiPoolMiner.io
2018-07-05 21:16:06 INFO: Mining for you. Donation run will start in 01 hour(s) 00 minute(s). 
2018-07-05 21:16:06 INFO: Updating exchange rates from Coinbase. 
2018-07-05 21:16:06 INFO: Loading saved statistics. 
2018-07-05 21:16:09 INFO: Loading pool information. 
2018-07-05 21:16:10 WARNING: The software (MultiPoolMiner) failed to update. 

> 

What could be the reason the software update failed? All the miner etc are downloaded fine.

**Comment by m-bosch** [comment]
@grantemsley maybe this has something to do with your repo where I read about with auto updating stuff?

**Comment by UselessGuru** [comment]
This is not an error, it is a warning :-)

Currently there is not new version available - just ignore the warning or run MPM with the parameter 
-DisableAutoUpdate

**Comment by UselessGuru** [comment]
It is checking versions.... individual commits must first be merged.
Then a new release (version) must be built by aaron.

For best results I recommend the latest zip file + PR's if told so.
https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

**Comment by m-bosch** [comment]
Thanks for the clear answer. Issue Can be closed
