### ISSUE TITLE
How to disable ClaymoreEthashKeccak-30-GPU

### ISSUE THREAD

**Issue by vhatzist** [MultiPoolMiner/MultiPoolMiner#1947]
Hello,

I'd like to disable "ClaymoreEthashKeccak-30-GPU" because after it runs for a while the machine becomes sluggish and the hashrate drops way below the benchmarks. I understand that it may need more memory than I have (4 GB RAM + 16GB pagefile). 

I don't understand which miner to exclude from the list in

https://multipoolminer.io/miners

to disable this one.

**Comment by UselessGuru** [comment]
-ExcludeMinerName ClaymoreEthashKeccak-30-GPU

**Comment by vhatzist** [comment]
@UselessGuru I tried that, it does not work. MPM still launches it. :(

**Comment by UselessGuru** [comment]
@vhatzist 

I see... we need the same code extension as for algorithms in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1903

For now you can either:
- Edit the stats file and set the hash rate to 0
- Edit the miner file and comment out the problematic algo

**Comment by UselessGuru** [comment]
Try https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1952

**Comment by paulpoco** [comment]
@vhatzist you really need more than 4G of RAM.  I have 16G of RAM never noticed a problem, it rarely uses more than 8G.
