### ISSUE TITLE
Disabling dual mining

### ISSUE THREAD

**Issue by jweber018** [MultiPoolMiner/MultiPoolMiner#1951]
Heya, as most of us know, dual mining has been losing precedence lately. Cards consume more power for a nearly negligible amount of coins / BTC. Would it be possible to add an argument like "NoDualMining" or something like that?

Thanks guys.

**Comment by UselessGuru** [comment]
See https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1953

You will have to manually add the parameter to the config file (or re-create an new one):

`  "DisableDualMining": "$DisableDualMining",`

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2094
