### ISSUE TITLE
Change config file handling #1954

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1962]
Config format has changed or I don't understand how it works.

Downloaded a current Master.

The default generated config.txt has no example anymore of miningpoolhub, miningpoolhubcoins,nicehash so I am unsure how to fill it in?  Where do I put my keys?  ID numbers?

**Comment by grantemsley** [comment]
The format hasn't actually changed.  If you have a recent config.txt file (recent enough that you've changed Type to DeviceName at least) it should work fine.

If you mine all to BTC (except miningpoolhub, where you use a username), you can just fill in the Wallet and Username sections.

If you want to configure each pool differently, or mine with payouts in other coins, you can use the settings documented in the readme under [Advanced Configuration for pools](https://github.com/MultiPoolMiner/MultiPoolMiner#advanced-configuration-for-pools)

**Comment by grantemsley** [comment]
Can you post your full config file, and which address you are expecting it to use for each pool?  I will test it out on one of my machines and see what's up.  If you list an address under wallet and a specific config for nicehash, it should use the wallet address for all the other pools.

**Comment by grantemsley** [comment]
Oh, also post the full JSON from http://localhost:3999/config - that will show how the script is interpreting whatever combination of command line params and config file you used.

**Comment by paulpoco** [comment]
Quick question about MPH API ID and keys?  I shouldn't post them?

**Comment by paulpoco** [comment]
Weird I put it back to how it was and now it is not showing the Pool balances from non MPH and Nicehash like it was before.

**Comment by grantemsley** [comment]
Censor the API key...I don't *think* anyone can do anything bad with that besides check your balance but not 100% certain.  Please don't sensor the addresses though, I will need those to check.

**Comment by paulpoco** [comment]
I cannot recreate the issue so I must of got it right now but in the original post I did grab a screenshot that show all those pools I don't use.



config.txt that seems ok now:

{
  "VersionCompatibility": "3",
  "Wallet": "$Wallet",
  "UserName": "$UserName",
  "WorkerName": "$WorkerName",
  "API_ID": "$API_ID",
  "API_Key": "$API_Key",
  "Interval": "$Interval",
  "Region": "$Region",
  "SSL": "$SSL",
  "DeviceName": "$DeviceName",
  "Algorithm": "$Algorithm",
  "MinerName": "$MinerName",
  "PoolName": "$PoolName",
  "ExcludeAlgorithm": "$ExcludeAlgorithm",
  "ExcludeMinerName": "$ExcludeMinerName",
  "ExcludePoolName": "$ExcludePoolName",
  "Currency": "$Currency",
  "Donate": "$Donate",
  "Proxy": "$Proxy",
  "Delay": "$Delay",
  "Watchdog": "$Watchdog",
  "MinerStatusUrl": "$MinerStatusUrl",
  "MinerStatusKey": "$MinerStatusKey",
  "SwitchingPrevention": "$SwitchingPrevention",
  "DisableAutoUpdate": "$DisableAutoUpdate",
  "ShowMinerWindow": "$ShowMinerWindow",
  "UseFastestMinerPerAlgoOnly": "$UseFastestMinerPerAlgoOnly",
  "IgnoreCosts": "$IgnoreCosts",
  "ShowPoolBalances": "$ShowPoolBalances",
  "ShowPoolBalancesExcludedPools": "$ShowPoolBalancesExcludedPools",
  "Pools": {
    "MiningPoolHub": {
      "User": "$UserName",
      "Worker": "$WorkerName",
      "API_ID": "xxxxxx",
      "API_Key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "MiningPoolHubCoins": {
      "User": "$UserName",
      "Worker": "$WorkerName",
      "API_ID": "xxxxxx",
      "API_Key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "NiceHash": {
      "BTC": "3MQi1VakFbySqc3J4yhBCc7yHQxxRuRcdY",
      "Worker": "$WorkerName"
    },
  },
  "Miners": {}
}

**Comment by paulpoco** [comment]
And pasting my config.txt above took out the leading spaces.

I not sure if there really is anything to test now.

So next time do I just copy my existing config.txt when I want to do a new Master Again?  What if something changes in the config.txt variables due to a code change and I am always copying the old one?

What if there was a user.txt that contained the pool info that you would want before starting a new Master?  Then when it is creating the config.txt it grabs the user.txt and appends it to the bottom of config.txt?

**Comment by paulpoco** [comment]
Figured from the log what caused the other Pools to list, it was doing a donation run.

Bin\CPU-JayDDee\cpuminer-avx2.exe -a lyra2z -o stratum+tcp://lyra2z.usa.nicehash.com:3365 -u
                                                                          1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb.multipoolminer -p x

So maybe when doing donation run don't show the donation BTC Pool balances?

**Comment by paulpoco** [comment]
[MultiPoolMiner_2018-07-07_14-23-58.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2173177/MultiPoolMiner_2018-07-07_14-23-58.txt)

Contains going from user mining to donation mining that shows the donation BTC Pool balances.

**Comment by grantemsley** [comment]
Hmm...those balances do seem to match up with the ones for the donation address.

But the balance checking NEVER uses the donation address, even when it changes the config for donation runs - balance checking uses the $UserConfig variable, which is a backup of your config before any donation changes.  I made sure of that when I added the balance checking, since I saw that behaviour when I first tried it.  And I just double checked, nothing to do with balance checking changed.

My guess would be that it was using parameters specified on the command line - perhaps you started it with start.bat, without editing anything in start.bat to your addresses?  The -wallet parameter there defaults to the donation address.  That's the only way I can see that happening.

One big reason for this particular PR is so that you CAN just copy config.txt from one revision to the next - any new parameters will either take their default value or values from the command line.  Occasionally we have to change the parameters, which results in having to change your config file, but we try to avoid that.

**Comment by paulpoco** [comment]
[Start.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2173191/Start.txt)

You can see I don't use the -wallet option.

**Comment by grantemsley** [comment]
Ok, I'll do some testing and see if I can figure out what's causing that.  It should keep displaying your balances, even when doing the donation runs.

**Comment by paulpoco** [comment]
There isn't an option for the MPH and MPHC to put the API ID/Key in start.bat?
There isn't an option for Nicehash BTC wallet only in start.bat?

If there was then I would never need to touch config.txt.

"MiningPoolHub" "MiningPoolHubCoins" could use the following variables:
-MPH_API_ID "ap ID"
-MPH_API_Key "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

"NiceHash" could use the following variables:
-NiceHashBTC "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

**Comment by grantemsley** [comment]
For miningpoolhub there is its the username parameter.

**Comment by paulpoco** [comment]
To get MPH balances does it only need the username or is it using the API ID/KEY?

The pending PR for the webui is picking up exacting the same donation balances too
![image](https://user-images.githubusercontent.com/801414/42415476-b99e5c30-8204-11e8-8159-0e0094e570bf.png)

**Comment by grantemsley** [comment]
For mph it needs the API key too, with the -api_key parameter.

The web UI will always show whatever the script does, so that's not surprising.
