### ISSUE TITLE
Cast-XMR-Vega miner not working with new algorithms

### ISSUE THREAD

**Issue by caniko2** [MultiPoolMiner/MultiPoolMiner#1964]
I have an RX 580 and an RX Vega 64. Note that the Vega 64 is overclocked by undervolting. I get this message when using cryptonightv7:
"[09:59:33] !Rejected by pool! Reason: Low difficulty share"

I have tried to reinstall drivers; solo mine with the Vega 64 card, and it still doesn't work. Is this because of MPM or Claymore? I have tried both cryptonight cast and claymore, so it seems like the issue is with mpm

[Uploading Cast-7777_2018-07-08_09-58-24.txt…]()

**Comment by UselessGuru** [comment]
I doubt that MPM is the culprit here. What happens if you run the excact command outside of MPM?
Same error -> What parameter needs changing until the error goes away?

**Comment by caniko2** [comment]
I am looking into changing parameters as we speak. I get this message no matter what:
"Blockchain Compute Driver NOT detected."
What does that mean? I know about this Blockchain driver that was released way back. I rather use the latest adrenaline driver. Am I doing it wrong?

**Comment by UselessGuru** [comment]
You are obviously using a driver which the miner does not like. Pls check with the miner developers.

**Comment by caniko2** [comment]
I looked into the driver issue. It is simply a warning statement, it should work.

**Comment by caniko2** [comment]
I figured it out, the version you are using in MPM is old:
http://www.gandalph3000.com/download/cast_xmr-vega-win64_110.zip

It worked with:
http://www.gandalph3000.com/download/cast_xmr-vega-win64_130.zip

I don't know how to implement this into MPM. Maybe the miner should have some recursive function that scans the page for the latest version. Just an idea.

**Comment by UselessGuru** [comment]
> in MPM is old:

Thanks for pointing this out.

The cryptonight ecosystem is changing wildly - new algos and hardforks happening everywhere :-)
I will re-write the miner file for this miner - the present code cannot deal with the new algorithms.

**Comment by UselessGuru** [comment]
@caniko2 

> "[09:59:33] !Rejected by pool! Reason: Low difficulty share"

I can reproduce the issue. It is NOT caused by MPM. It is an occasional issue between the pool (NiceHash in my case) and the miner software. There is nothing MPM can do about this.

Nevertheless does the miner file need updating. Thanks for the hint!

**Comment by caniko2** [comment]
MPM is not the cause, thought that was established. The issue is that the cryptonightv7 miners are outdated.

**Comment by caniko2** [comment]
What about Claymore?

**Comment by UselessGuru** [comment]
Not tested yet.
