### ISSUE TITLE
XMRig-CPU Fails for brand new install

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1965]
Apparently it cannot use the default config file from the package.

When used, it overrides the API PORT and other things.  Need to determine if a minimalist config file will allow it to launch so that command line parameters will work.

**Comment by Kettoch** [comment]
Deleted the directory while running and it downloaded the 2.6.3 version.  That version has a binary a JSON config file and a cmd file.
I copied JUST the binary and MPM ran
2018-07-08 16:53:43 INFO: Starting miner (XmrigCpu): 'C:\MultiPoolMiner\Bin\CryptoNight-CPU\xmrig.exe --api-port=3334 -a cryptonightV7 -o stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:20580 -u Kettoch.Alien -p x --keepalive --nicehash --donate-level 1'

I get the following error file.

[XmrigCpu-3334_2018-07-08_16-53-43.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2174122/XmrigCpu-3334_2018-07-08_16-53-43.txt)

**Comment by UselessGuru** [comment]
I see your point now... I've opened an issue with the miner developers:

https://github.com/xmrig/xmrig/issues/715

**Comment by UselessGuru** [comment]
Fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2007
