### ISSUE TITLE
Ethash2GB: MusiCoin has reached Epoch 96

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#1967]
PhoenixMiner and other Ethash miners can no longer mine MusiCoin.

So we will have to introduce Ethash3GB algorithm.

The following MPM miner files already support Ethash3GB:

- PhoenixMiner 3.0c (coming soon)
- ClaymoreEthash
- EthMiner

In addition to Ethash3GB-ready miners we'll also need to update the pool file (currently only MiningPoolHubCoins supports Ethash2GB).

I'll prepare a PR for this.

This makes interesting reading: https://investoon.com/tools/dag_size

**Comment by paulpoco** [comment]
I don't think I will still have a 1070 in the year 2028.
![image](https://user-images.githubusercontent.com/801414/42551034-0384b286-848a-11e8-96d0-2acaf1261641.png)

**Comment by UselessGuru** [comment]
See https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2001
