### ISSUE TITLE
PhoenixMinerAmd and PhoenixMinerNvidia don't work side by side

### ISSUE THREAD

**Issue by jweber018** [MultiPoolMiner/MultiPoolMiner#1968]
Heya guys. Trying out MPM in my mixed NVIDIA - AMD rig, and when PhoenixMiner runs on both AMD and NVIDIA platform, both instances of the miner work for ~1 minute and then one of them (random) closes. The logs show nothing happening, the miner just closes, which makes me think it's MPM closing it by mistake. The API ports for each miner are different, so the issue is not related to API. Let me know if you need further input.

As always, thanks in advance.

**Comment by jweber018** [comment]
Oh, sorry. I didn't see there was a new feature with PhoenixMiner. I don't get the same error running two instances of the miner, no. I'll try the new miner file and let you know. Thanks, mate.

**Comment by jweber018** [comment]
Hey, sorry to bring this up again. I merged #1971 and tried, but MPM (or something) keeps killing one instance of PhoenixMiner. It's like PhoenixMinerAmd and PhoenixMinerNvidia don't function together.

**Comment by UselessGuru** [comment]
@jweber018 

Do you have 'ShowMinerWindows' set to true?

**Comment by UselessGuru** [comment]
@jweber018 

Issue is known. We are working on it.

**Comment by UselessGuru** [comment]
Will be fixed with 3.1.0:
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/3.1.0
