### ISSUE TITLE
New 1070 Mining Rig Fresh Install Windows 10 wont benchmark 

### ISSUE THREAD

**Issue by izzledude** [MultiPoolMiner/MultiPoolMiner#1969]
So i have  new 1070 5 card rig with a fresh install of windows  im trying to run the benchmark but nothing is happening. ive done the exact same on two previous rigs with no issues and even went through the README file and followed that but no benchmarking  happens. Watching afterburner for usage and GPUs arent even heating up as the fans wont start spinning.   I pulled the latest release from 

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.2.7/MultiPoolMinerV2.7.2.7.zip still no luck.  any advice would be appriciated.

**Comment by UselessGuru** [comment]
Not that it mwtters, but the 'realease' version is outdated. Go with the latest zip file: 
https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

How about some logs?
How what about 
http://localhost:3999/devices ??? Does MPM detect all your devices properly?

**Comment by m-bosch** [comment]
Maybe try the nicehash software so see If iT starts. Maybe Some drivers arent available?

What Windows (screens) do You see Or what Windows(screens) are You missing?

**Comment by izzledude** [comment]
i did have nicehash legacy it worked just fine. Im trying that master zip now and see if that works.  will get back to you shortly

**Comment by izzledude** [comment]
ok so i tried it with a 1050ti  and it seems to be working  but one of the windows shows script like 

2018-07-11 10:02:35 INFO: Pinging monitoring server.
2018-07-11 10:02:35 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
2018-07-11 10:02:35 WARNING: Benchmarking in progress: 23 miners left to benchmark.
2018-07-11 10:02:35 INFO: Start waiting before next run.
2018-07-11 10:02:47 VERBOSE: CpuminerTpruvotCorei7: ["summary",{"value":[{"NAME":"cpuminer-multi"},{"VER":"1.3.1"},{"API
":"1.1"},{"ALGO":"cryptonight"},{"CPUS":"16"},{"KHS":"0.00"},{"SOLV":"0"},{"ACC":"0"},{"REJ":"0"},{"ACCMN":"0.000"},{"DI
FF":"400015.581168"},{"TEMP":"0.0"},{"FAN":"0"},{"FREQ":"0"},{"UPTIME":"11"},{"TS":"1531324966|\u0000"}],"Count":16}]
2018-07-11 10:02:48 VERBOSE: Ewbf: ["{\"id\":1,\"method\":\"getstat\"}",{"id":1,"method":"getstat","error":null,"start_t
ime":1531324955,"current_server":"equihash.usa.nicehash.com:3357","available_servers":1,"server_status":2,"result":["@{g
puid=0; cudaid=0; busid=0000:07:00.0; name=GeForce GTX 1050 Ti; gpu_status=2; solver=0; temperature=0; gpu_power_usage=0
; speed_sps=0; accepted_shares=0; rejected_shares=0; start_time=1531324956}"]}]
2018-07-11 10:02:59 VERBOSE: CpuminerTpruvotCorei7: ["summary",{"value":[{"NAME":"cpuminer-multi"},{"VER":"1.3.1"},{"API
":"1.1"},{"ALGO":"cryptonight"},{"CPUS":"16"},{"KHS":"0.00"},{"SOLV":"0"},{"ACC":"0"},{"REJ":"0"},{"ACCMN":"0.000"},{"DI
FF":"400015.581168"},{"TEMP":"0.0"},{"FAN":"0"},{"FREQ":"0"},{"UPTIME":"24"},{"TS":"1531324979|\u0000"}],"Count":16}]
2018-07-11 10:03:00 VERBOSE: Ewbf: ["{\"id\":1,\"method\":\"getstat\"}",{"id":1,"method":"getstat","error":null,"start_t
ime":1531324955,"current_server":"equihash.usa.nicehash.com:3357","available_servers":1,"server_status":2,"result":["@{g
puid=0; cudaid=0; busid=0000:07:00.0; name=GeForce GTX 1050 Ti; gpu_status=2; solver=0; temperature=0; gpu_power_usage=0
; speed_sps=0; accepted_shares=0; rejected_shares=0; start_time=1531324956}"]}]
2018-07-11 10:03:11 VERBOSE: CpuminerTpruvotCorei7: ["summary",{"value":[{"NAME":"cpuminer-multi"},{"VER":"1.3.1"},{"API
":"1.1"},{"ALGO":"cryptonight"},{"CPUS":"16"},{"KHS":"0.00"},{"SOLV":"0"},{"ACC":"0"},{"REJ":"0"},{"ACCMN":"0.000"},{"DI
FF":"400015.581168"},{"TEMP":"0.0"},{"FAN":"0"},{"FREQ":"0"},{"UPTIME":"36"},{"TS":"1531324991|\u0000"}],"Count":16}]
2018-07-11 10:03:12 VERBOSE: Ewbf: ["{\"id\":1,\"method\":\"getstat\"}",{"id":1,"method":"getstat","error":null,"start_t
ime":1531324955,"current_server":"equihash.usa.nicehash.com:3357","available_servers":1,"server_status":2,"result":["@{g
puid=0; cudaid=0; busid=0000:07:00.0; name=GeForce GTX 1050 Ti; gpu_status=2; solver=0; temperature=39; gpu_power_usage=
0; speed_sps=182; accepted_shares=0; rejected_shares=0; start_time=1531324956}"]}]


And the CPU wont benchmark even though i see utilization on it.

**Comment by izzledude** [comment]
So to make sure i understand correctly   do not use   

-username IzzleDude -workername GPC -region us -currency usd -type nvidia,cpu -poolname miningpoolhubcoins,zpool,nicehash

Should it be

-username IzzleDude -workername GPC -region us -currency usd -devicename nvidia,cpu -poolname miningpoolhubcoins,zpool,nicehash

**Comment by m-bosch** [comment]
thats what @UselessGuru says indeed. I prefer to use the config.txt instead of start.bat to set parameters.

if you use that it would be: `"DeviceName": ["NVIDIA","CPU"],`
