### ISSUE TITLE
ExcludeAlgorithm and ExcludeCoin not working

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#1970]
[config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2182260/config.txt)

I want to exclude CryptoNightV7 on MPH and MPHC right now but still use that on Nicehash.

**Comment by Kettoch** [comment]
There was a filter proposed at one point but it has not gone anywhere.

**Comment by paulpoco** [comment]
@Kettoch I did see PRs that they are working on so no hurry.

**Comment by UselessGuru** [comment]
ExcludeAlgorithm  is implemented, but it needs some tweaking, see https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1903
