### ISSUE TITLE
Excavator service window remains after change to other algorithm

### ISSUE THREAD

**Issue by thebeerbaron2018** [MultiPoolMiner/MultiPoolMiner#1980]
Whilst I understand this was a closed issue with resolution being "just minimize the window" it's causing me issues because after a while of mining 3 things happen:
1. Nicehash has my rigs "connected" under multiple algorithms making monitoring difficult
2. The log files become overly bloated with "new job" requests received from the service
3. 500mb+ of memory is taken - since I bare-bones my many rigs with only 4gb total - this is a big chunk to lose.

I propose the following solution - Just 4 lines added to the "Idle" switch command in SetStatus and one modification to the service start call to give the service an identifiable name.

```
    SetStatus([MinerStatus]$Status) {
        if ($Status -eq $this.GetStatus()) {return}

        if ($this.BeginTime.Ticks) {
            if (-not $this.EndTime.Ticks) {
                $this.EndTime = Get-Date
            }

            $this.Active += $this.EndTime - $this.BeginTime
            $this.BeginTime = 0
            $this.EndTime = 0
        }

        if (-not [Excavator]::Service) {
            $LogFile = $Global:ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(".\Logs\Excavator-$($this.Port)_$(Get-Date -Format "yyyy-MM-dd_HH-mm-ss").txt")


#######################################################
Following line -Name "ExcavatorService" has been added
#######################################################


            [Excavator]::Service = Start-Job -Name "ExcavatorService" ([ScriptBlock]::Create("Start-Process $(@{desktop = "powershell"; core = "pwsh"}.$Global:PSEdition) `"-command ```$Process = (Start-Process '$($this.Path)' '-p $($this.Port) -f 0 -fn \```"$($LogFile)\```"' -WorkingDirectory '$(Split-Path $this.Path)' -WindowStyle Minimized -PassThru).Id; Wait-Process -Id `$PID; Stop-Process -Id ```$Process`" -WindowStyle Hidden -Wait"))
        }

        if ($this.Service_Id -ne [Excavator]::Service.Id) {
            $this.Status = "Idle"
            $this.Workers = @()
            $this.Service_Id = [Excavator]::Service.Id
        }

        switch ($Status) {
            "Running" {
                $this.StartMining()
            }
            "Idle" {
                $this.StopMining()

#######################################################
# LINES ADDED HERE TO STOP AND TERMINATE THE SERVICE
                Stop-Job "ExcavatorService"
                Remove-Job "ExcavatorService"
                [Excavator]::Service = $null
#######################################################

            }
            Default {
                if ([Excavator]::Service | Get-Job -ErrorAction SilentlyContinue) {
                    [Excavator]::Service | Remove-Job -Force
                }

                if (-not ([Excavator]::Service | Get-Job -ErrorAction SilentlyContinue)) {
                    [Excavator]::Service = $null
                }

                $this.Status = $Status
            }
        }
    }
```

**Comment by thebeerbaron2018** [comment]
Actually this appears to still leave the powershell.exe open - I'm working on closing that down to to free the memory

**Comment by UselessGuru** [comment]
Excavator is meant to be used as a service. It is recommended to NOT close the window.
I you can afford to run a mining rig that constantly sends data over the internet then the few polling packets sent by Excavator should not be an issue. Keeping it open helps optimizing profit because it allows instant algorithm switching. Closing and re-launching Excavator will cause at least 10 seconds of idle time (that is how long it will take until Excavator is ready to start mining).

>> to free the memory

Unused memory is wasted memory :-)

**Comment by thebeerbaron2018** [comment]
Is there any reason for the Start-Sleep 10 in the API which obviously causes a delay of 10 seconds first time the service starts (and obviously if you called it each time as a process)?

If I remove that I can have the session shut down and restart in about 0.6 of a second - and that's on a slow ass dual celeron CPU.

Also I don't have unused memory - the problem I have is that between the open service and the other miners ALL my ram is used and the swap file is getting hit.  Before you advise me to get more ram (I know - simple eh? he he) I have over 200 rigs so that would be a little expensive!

Maybe If I can build a non service - shut and reopen PS1 file for excavator you could include both for people that wish to run it either way?  Would that be of interest?

**Comment by thebeerbaron2018** [comment]
Can you give my replacement a test?  For me it restarts Excavator in under 1 second.  I have left the miner window normalised (rather than minimized or hidden) for testing.

[ExcavatorNonService.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2190204/ExcavatorNonService.zip)

**Comment by thebeerbaron2018** [comment]
Oh now I see - occasionally the web server doesn't always start immediately - so there may need to be a delay until it's ready

**Comment by aaronsace** [comment]
@thebeerbaron2018 Are you actually getting low memory warnings???

If you are then it's about £10 per GB of ram; if you have a mining rig then that's nothing compared to the price of the graphics cards...

**Comment by thebeerbaron2018** [comment]
200 rigs ;) and they were built several years ago with DDR2 RAM - you know rocking horse sh*t is cheaper!  The only thing that have been upgraded across the rigs are the GFX cards :O

**Comment by aaronsace** [comment]
Seriously, WOW!

**Comment by thebeerbaron2018** [comment]
So what I have done here is start the excavator process and then make a request to the localhost server until the miner is up.  I allow 10 x 1 second intervals for the miner to open and respond.  In testing though the server always responds on my machines in under 1 second and they are slow as.

```

            $this.ExcavatorProcess = Start-Process -FilePath $($this.Path) -ArgumentList "-p $($this.Port) -f 0 -fn ""$($LogFile)""" -WorkingDirectory $(Split-Path $this.Path) -PassThru         

            $Server = "localhost"
            $Timeout = 1
            $Request = @{id = 1; method = "algorithm.list"; params = @()} | ConvertTo-Json -Compress
            $Response = ""
            for($waitforlocalhost=0; $waitforlocalhost -le 10; $waitforlocalhost++) {

                try {
                    $Response = Invoke-TcpRequest $Server $this.Port $Request $Timeout -ErrorAction Stop
                    $Data = $Response | ConvertFrom-Json -ErrorAction Stop
                    break
                }
                catch {
                }
            }
```


[ExcavatorNoService_v2.ps1.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2190270/ExcavatorNoService_v2.ps1.zip)

**Comment by thebeerbaron2018** [comment]
I can see how someone that only mines using Excavator would benefit from the service method - but if you're using lots of miners and the rig had been running a while and during that time has connected to 10 different algorithms at Nicehash - you've got the same worker still classed as "connected" 10 times on their servers - and you are receiving update packets for 10 algos which are stored into the logs and then the log viewer is bloating with many Nicehash messages about new blocks (although I understand there is no GPU power or mining directed at the idle workers).  The ram requirement really does step up with each idle connection though!  At one point they were using 3.8GB on my machine..... and I only have 4GB lol - wondered why my SSD's were getting hammered.

**Comment by aaronsace** [comment]
@thebeerbaron2018 It may be better fixing the issues causing Excavator to use up so much memory rather than closing the process. 

If it is simply because the connections are open then this can probably be fixed with a single line.

**Comment by thebeerbaron2018** [comment]
It's not Excavator.  It's the powershell objects because for each algorithm the log viewers open another powershell instance to read them because they are constantly receiving new work updates - and yes I could close the log viewers but then there is nothing pretty to monitor.  Also when you have many rigs it's really difficult to see your stats on Nicehash when you have 800-1000 "dead but connected" workers... plus I am sure Nicehash may not appreciate having the duplicates?  And finally when you have a lots of miners it's only on the odd occasion that it switches to the Excavator anyway - so having it pumping data and updates down to the miner 24/7 seems a little wasteful and although it's only a few K every second - multiply that up and you start getting into a fair chunk of data being bounced back and forth.....  The V2 file above has just benchmarked 10 algos against Nicehash closing and reopening excavator without error and the logs files are small and the memory is released and staying low.

**Comment by thebeerbaron2018** [comment]
Although it might be worth looking into removing all the workers which may have the same effect?  I can cope with the 500mb overhead if there wasn't a log viewer overhead and all data between excavator and Nicehash stops when the miner is switched away from.... maybe that's a better solution?

**Comment by aaronsace** [comment]
@UselessGuru Can you look at working this in at the end of `StopMining()`? 

Retrieve a list of algorithms/workers: 
```
$Request = @{id = 1; method = "algorithm.list"; params = @()} | ConvertTo-Json -Compress
Invoke-TcpRequest $Server $this.Port $Request $Timeout -ErrorAction Stop
```

If an algorithm has no workers then remove the algorithm: 
```
$Request = @{id = 1; method = "algorithm.remove"; params = @()} | ConvertTo-Json -Compress
Invoke-TcpRequest $Server $this.Port $Request $Timeout -ErrorAction Stop
```

**Comment by aaronsace** [comment]
If there is nothing left after removing the algorithms then the service could be closed if that does not reduce the memory enough.

**Comment by thebeerbaron2018** [comment]
I don't think it's Excavator that's using the ram - if you start the miner and open task manager and watch the instances of powershell, as Excavator switches between algorithms each algo spawns a new powershell cmdlet for the logging session - that seems to be the main hog of memory as each cmdlet is reading each different log file for the "idle" algorithms.  But closing the miners so no active connection to Nicehash should be sufficient to shut down the "idle" miners still showing as connected their end - I noticed that the logging only seemed to stop having entries added when excavator was closed from task bar.  So if leaving the service and web server running would make switching quicker then that would be desirable - but if that means all the logs stay open then not.  Easy way to see this in action is to start a fresh copy of the miner with just the excavator.ps1 and let it run the benchmarks and watch the powershell cmdlets and ram usage build up!

**Comment by thebeerbaron2018** [comment]
![image](https://user-images.githubusercontent.com/36641730/42662511-c72b4218-8629-11e8-806b-b8b71855827f.png)

**Comment by thebeerbaron2018** [comment]
This only occurs when the reader.ps1 window is open from this line in the bat file:

`start pwsh -noexit -executionpolicy bypass -command "& .\reader.ps1 -log 'MultiPoolMiner_\d\d\d\d-\d\d-\d\d\.txt' -sort '^[^_]*_' -quickstart"`

But I believe it's doing some form of compare on the file date/time/size to determine if it needs to display and then spawns a new session - obviously multiple open files to the different algos are constantly receiving "new work" information and so the reader keeps displaying them all!

**Comment by aaronsace** [comment]
@thebeerbaron2018 So your issue is nothing to do with Excavator??? 

I wouldn't run the log reader running on a rig... or at least not leave it open 24/7.

**Comment by thebeerbaron2018** [comment]
There are two parts to the problem - the first is the log reader chomping all the ram (which can be solved by closing the log reader I agree) - the second part is the workers staying connected at NiceHash which means with 200 rigs connected I can have 1100 or more workers that are "idle" on algorithms not in use - and those miners are still downloading the "new job" data to every rig for every idle algo! - it wouldn't be noticeable on one rigs - but as soon as you get to 5-10 plus it's a major PITA trying to manage the workers and also a waste of data back and forth.

**Comment by aaronsace** [comment]
I'm not sure that the log problem can be solved but it's a non-issue anyway. 

I'll wait and see if @UselessGuru can get that code above going.

**Comment by thebeerbaron2018** [comment]
Absolutely - the log viewer is only really for making sure the initial setup kicks off and benchmarks correctly - so I agree - no change needed - although - I might consider creating separate bat files with and without the reader.ps1 lines in?  maybe something like Start_Benchmarking_WithDisplayLogs.bat and Start_24-7_WithoutDisplayLogs.bat (with maybe an explanation).  The only reason I say this is that some people have rigs off site and if you can't easily get back to them quickly and they've run with logging - they'll come back to a very quickly crashed miner!

Am quite happy to cordon off a bunch of rigs and deploy any new code to test for you.

**Comment by thebeerbaron2018** [comment]
Yep, almost got it - basically at line 250 in excavator.ps1 API - I added an "algorithm.clear" block which did instead brute force close all my leftover worker threads that were idle.  However it's not best practice.  You're right on the old 1.4.4 API you need to call algorithm.list and then for the specific algorithm that is currently being deactivated check the number of remaining workers (it's already had all the workers from this miner disabled by lines  227-247).  If the number of workers is 0 then it's safe to also call algorithm.remove for that algo.  Spent ages playing with it wondering why it wasn't working and then realised their API is now 1.5.x and they separated the algorithm and worker functions! DOH!

**Comment by UselessGuru** [comment]
To get around the memory issue with the log reader it might be worth using an external program for tailing the logs. I am quite happy with snaketail:
https://github.com/snakefoot/snaketail-net

**Comment by thebeerbaron2018** [comment]
I just have my rigs reboot every 24 hrs and the reboot clears down the log folder for anything more than a day old on reboot.

**Comment by UselessGuru** [comment]
> If there is nothing left after removing the algorithms then the service could be closed

This might not be desirable. 

Possible scenario:
An algo swich happens for ALL running Excavator workers -> stop all workers -> remove all algorithms -> close Excavator (stop service) -> immediately Start Excavator with new algos.

**Comment by thebeerbaron2018** [comment]
@UselessGuru you already hold an array of workers started with this session of MPM - so you can stop all the workers in the array (which you do already) then do an algorithm.list and parse the data for the current algorithm.... if the worker count is now zero then it's safe to do algorithm.remove - if it's non zero then don't because another rig could be contributing workers to that algorithm.  But I can see how that could end up with race conditions and errors.  What's annoying is that the worker.free command doesn't actually free the worker from the algorithm - it only stops it receiving new jobs or actually working - it's still "connected" at their end and sat there idle which is really annoying when you're seeing 1000+ idle workers in the list haha

**Comment by UselessGuru** [comment]
@thebeerbaron2018 

The API code does not have access to the variables from the main routine. 
Unlinking/removing the algo is simple - it is in my core as we speak :-)

**Comment by UselessGuru** [comment]
>> if rig A had already algo.cleared it?

I don't know what algorithm.clear does on the pool side. I assume the described process should not any harm because the pool also recognizes the rig by other means (e.g. worker name, session id maybe).

**Comment by thebeerbaron2018** [comment]
Well in 1.4.4 apparently it clears all algorithms and any workers.... but in 1.5.x it only clears the algorithms - you still have to clear down the workers.  In 1.4.4 algorithm.remove = Removes algorithm. This method also clears all linked workers. Call this method when connection to remote pool is not needed anymore.  But the problem with this is that if you have 5 rigs pointed at the algo - it will remove all the workers from all the rigs.  You do have a list of the workers associated with this particular miner in $this.Workers so you can call the worker.free method to knock out each of the workers for that particular mining rig.  The only other solution I can think of since you can't guarantee what other rigs are doing when you issue the API commands - is to run as non-service for my needs and leave as a service for those who don't mind and have the spare ram!

**Comment by thebeerbaron2018** [comment]
Not yet.  I am currently away from my rigs - I'll deploy as soon as I get over there and see how it goes.  Am going to set 2 rigs aside.... connect with excavator on RIG B on say Neoscrypt and then connect RIG A to neoscrypt using MPM and the excavator file you made above.  Then I am going to have RIG A move to say Libry.... what I am hoping to see is RIG B's workers unaffected, RIG A's workers for Neoscrypt gone and then RIG A's workers re-appear under Libry.... then I want to move RIG A to ccminer and hoping to see then the log files contain no further updates from Nicehash about new jobs :)  Fingers crossed

**Comment by thebeerbaron2018** [comment]
OK tested like so : RIG B - set to mine Neoscrypt on Nicehash directly using excavator.  RIG A - benchmark Neoscrypt and Libry and DaggerHashimoto at Nicehash.  RIG B showed up.  RIG A showed Libry first and benched it.  When it switched to Neo, the Libry algo/worker was removed (CORRECTLY!), when it switched to Dagger the Neo algo/worker was removed but the RIG B worker remained (CORRECTLY!)... upon inspection of the logs once the neo algo/worker had been removed no further entries appeared in the log (CORRECTLY!).  Looks all good to me.  Excavator taking up 722MB but that leaves me plenty of the remaining 4gb for the other miners to play with.  I would say success all round - great work!

**Comment by thebeerbaron2018** [comment]
Also noticed that the algo unload now also frees the ram usage when excavator is just background idle - the ram use drops to 3-22mb which is great!
