### ISSUE TITLE
Issue using WorkerName from ConfigFile

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1992]
I have fully configured my config.txt and my batch file ONLY uses -configfile config.txt as parameters.

What I discovered, was that $WorkerName is set to multpoolminer as a default.  While this is ok when you are creating a config file, when a config file is created and WorkerName is set in the config file it is ignored.

Add the following lines:
`    #Pass Configuration File WorkerName to $Config
    $WorkerName = $Config.WorkerName
`
Just after the $Config file adds Pools and Miners near line 175 (or at least in my file it is).

**Comment by Kettoch** [comment]
Actually my config file has all the pools configured (even those I do not currently use) except the ymp or whatever it is because I just do not want to take the time to figure that one out.

I actually traced how WorkerName is used and $Config.WorkName is not the value used when the monitoring request happens.  It is using $WorkerName.

**Comment by UselessGuru** [comment]
> used when the monitoring request happens.

??? What monitoring request?

**Comment by Kettoch** [comment]
There is a line for reportstatus.ps1 and that is the line that uses, I believe, the wrong variable.
