### ISSUE TITLE
Suggestion:  Add a debug to the entire system

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1995]
I have been looking for a way to get more involved with this project and I think I will create a debug system for this.  
I am looking for suggestions for:

- how people would like to be able to debug
- what people want to debug
- where to set the levels of debug
- Should debugging cascade down from a setting as an override or to allow it to be set at various levels like the per miner/pool type locations.
- Do we anonymize any separate debug files for security when they are submitted?

@aaronsace and @UselessGuru After working through several times where I made changes and suddenly all my miners were missing, it made me think that something like this could also be enhanced to provide you a separate debug file for specific issues.  Potentially speeding up issue resolution.

I just need to figure out how to use GitHub to be able to create the PR.

**Comment by UselessGuru** [comment]
Kettoch: Don't get me wrong. I appreciate your will to contribute! A debugging tool is not needed IMHO. Adding debug code just adds extra cost at no value for the average user.

The API is a great trouble shooting tool. And the log has a lot information too.
If you break something and want troubleshoot then everyone has his own way. The code is open and you can set breakpoints or inspect variables at any time.

**Comment by Kettoch** [comment]
@uselessguru you make a good point.  Will leave it a is, then.
