### ISSUE TITLE
Pool out of Sync 2863 minutes

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1998]
I have zpool, nicehash and MPH.

What can I look for to correct this?

**Comment by tbergeron** [comment]
I have been having this for a while too, 2000+ mins.
Thought it was normal since it's still works but I'm curious now that I see somebody else mentioning it.

**Comment by Kettoch** [comment]
I have figured this out.
I had my config file configured for both MiningPoolHub AND MiningPoolHubCoins.

Apparently if you configure MiningPoolHub, then MiningPoolHubCoins is also configured.

There is no need to grab balances from both as it would give an erroneous answer.  I just removed the latter and no more error.
