### ISSUE TITLE
Excavator 1.4.4a does not appear to connect to NiceHash with Equihash

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#1999]
The Equihash algo seems to fail now on NiceHash.

Still looking more into this.

**Comment by paulpoco** [comment]
Not related but Keccak has lots of failed shares, nothing to do with MPM.  They fail on NHML too.

So not sure if Nicehash is having there own issues?

**Comment by UselessGuru** [comment]
@Kettoch 

If you prove logs and API dumps we can assist you better :-)

**Comment by Kettoch** [comment]
@UselessGuru what do you mean by API dumps?  I can get the MPM logs and the miner logs... but not sure that is what you mean.

[MultiPoolMiner_2018-07-15.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2196021/MultiPoolMiner_2018-07-15.txt)
[MultiPoolMiner_2018-07-15_15-13-48.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2196022/MultiPoolMiner_2018-07-15_15-13-48.txt)

**Comment by UselessGuru** [comment]
I can see that MPM is trying to benchmark Equihash. What do the Excavator logs say?

> what do you mean by API dumps

Something like: Is Equihash algo part of the available algorithms? -> http://localhost:3999/algorithms

**Comment by Kettoch** [comment]
[
  "Blake2s",
  "Blake2s-NHMP",
  "CryptoNightV7",
  "CryptoNightV7-NHMP",
  "DecredNicehash",
  "DecredNicehash-NHMP",
  "Equihash",
  "Equihash-NHMP",
  "Ethash",
  "Ethash2gb",
  "Ethash-NHMP",
  "Groestl",
  "Keccak",
  "Keccak-NHMP",
  "Lbry",
  "Lbry-NHMP",
  "Lyra2RE2",
  "Lyra2RE2-NHMP",
  "Lyra2z",
  "Lyra2z-NHMP",
  "NeoScrypt",
  "NeoScrypt-NHMP",
  "Pascal",
  "Pascal-NHMP",
  "Sib",
  "Sib-NHMP",
  "Skunk",
  "Skunk-NHMP"
]

**Comment by UselessGuru** [comment]
@Kettoch 
We can not really support your modified stuff. :-) 
Before posting make sure you are having the same issue with original code. Thank you!

FYI: I verified that the original code works with Equihash.
