### ISSUE TITLE
MultiPoolMiner/Balances/Zpool.ps1 can it check for other balances if LTC specified in config.txt?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2000]
MultiPoolMiner/Balances/Zpool.ps1 can it check for other balances if LTC specified in config.txt?

In my start.bat I don't have a -wallet BTC_address specified as I defined the wallets in config.txt.

In config.txt Zpool section I defined LTC instead of BTC.

**Comment by UselessGuru** [comment]
Correct. We currently calculate balances in BTC only (as stated in readme).
