### ISSUE TITLE
AMD-NVIDIA-Claymore-Ethhash\EthDcMiner64 miner fails a lot

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2005]
This miner dual mines with KC and ETH for me to Nicehash, unfortunately  many of the shares are rejected (like 80%). This way this one that should be most profitable isn't the most profitable by far....

I know this could be the miner with an issues instead of MPM but maybe someone has some advice for me.

Changed the region from 'Europe' to 'US' didn't help either.

**Comment by UselessGuru** [comment]
How about https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2004?

**Comment by m-bosch** [comment]
Sorry didn't check the pull requests, lets see when it will be merged, I will try it right away then!

Thanks a lot!

**Comment by m-bosch** [comment]
I will wait for the PR to be released to test it.

i see that @aaronsace needs to confirm it first right? many PR's open atm. all together a massive update. Good job all!

**Comment by UselessGuru** [comment]
@m-bosch 

This one is just a binary update - you can just DL and replace the ClaymoreDual miners.
