### ISSUE TITLE
Blazepool notification

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2008]
Just as a notice of this notification:

>  Notice
> 
> In 1 week, on 2018 July 14, we will be adjusting our API units for a few algos: lbry, nist5, skein, from mBTC/Mh/day to mBTC/Gh/day.
> 
> Most of the auto switching scripts' latest version already supports reading this from the API.
> 
> Please make sure you are running the latest version of NemosMiner / SniffDog / AwesomeMiner / Hashauger etc.

**Comment by UselessGuru** [comment]
This does not affect us anymore because ZergPool.s1 line 39 contains:

`    $Divisor = 1000000 * [Double]$Zpool_Request.$_.mbtc_mh_factor`

MPM retrieves the units automatcally from the pools API.
