### ISSUE TITLE
Inconsistency in lowercase / uppercase in start.bat

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2009]
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/d6a2b0c6c9b11b6432d8ad266b6981a41376dd15/Start.bat#L10

because of the new DeviceName-tag we have Inconsistency in naming, all are lowercase like worker name, but only the DeviceName is with capital D and N, is there a reason why?

I know we need to use the config.txt and I use it also, but just for the form (and the starting users), the start.bat is a point to start.

**Comment by UselessGuru** [comment]
All parameters are case-insensitive, except for wallet addresses (as stated in the readme).

> I know we need to use the config.txt 

You don't have to ;-) For basic operations you'll never need to touch config.txt at all ;-)

**Comment by m-bosch** [comment]
Thanks again!
