### ISSUE TITLE
How do I tell if a particular Algo is out of wack at Zpool? m7m?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2016]
![image](https://user-images.githubusercontent.com/801414/42850564-1224a028-89dd-11e8-862f-993d32d96911.png)
![image](https://user-images.githubusercontent.com/801414/42850596-336883ee-89dd-11e8-858b-5dff7f65ca1d.png)
![image](https://user-images.githubusercontent.com/801414/42850607-43870714-89dd-11e8-858a-02a34605fe05.png)

**Comment by paulpoco** [comment]
The 2nd line on the estimate never updates:
![image](https://user-images.githubusercontent.com/801414/42851216-5b1df6dc-89e0-11e8-8324-5bcab2654e88.png)

**Comment by grantemsley** [comment]
This is the pool's fault - see how it's current estimate is 0.19797, but 24 hour estimate is almost 50.  Something went wrong there.

You can run resetprofit.bat to fix it - that will clear all the historical profit data from the pools.  Normally this information is good and helps balance out huge spikes, but it doesn't always work.

**Comment by paulpoco** [comment]
Thanks
