### ISSUE TITLE
Silent error when starting multipool miner

### ISSUE THREAD

**Issue by caniko2** [MultiPoolMiner/MultiPoolMiner#2017]
Excerpt from the log:
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Miners\MultiPoolMiner\Include.psm1:241 char:87
+ ... le | Where-Object BaseName -EQ $Name | Get-Content | ConvertFrom-Json
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFro
   mJsonCommand

**Comment by UselessGuru** [comment]
This is from a broken stat file and should self-repair.
Did your system crash while running MPM?
