### ISSUE TITLE
Add Tab icon of MPM to web interface from #1976

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2021]
Add Tab icon of MPM to web interface from #1976

Add Tab icon for MPM Monitor https://multipoolminer.io/monitor

Somehow make the Tab Icons different?

**Comment by grantemsley** [comment]
Do you mean the folder icons on the left hand side of the web interface?

They come from fontawesome.  If you can find some more appropriate icons here I'd be happy to change them.  https://fontawesome.com/icons?d=gallery&m=free

**Comment by paulpoco** [comment]
![screenshot_20180721-115729_teamviewer](https://user-images.githubusercontent.com/801414/43039202-607ee80c-8cdd-11e8-86c9-1431ea01875e.jpg)
I mean the icon on the tab of the browser.  I think that is favicon?
