### ISSUE TITLE
Zergpool to use LTC

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#2025]
Decided to play around with the newest master and I need Zergpool using LTC.  see below bottom for what I put to try to use LTC, it is giving error saying config is not valid.  The version I've been using is setup differently than this new one so I"m not sure what I"m doing wrong.

{
    "VersionCompatibility":  "3",
    "Wallet":  "$Wallet",
    "UserName":  "$UserName",
    "WorkerName":  "$WorkerName",
    "API_ID":  "$API_ID",
    "API_Key":  "$API_Key",
    "Interval":  "$Interval",
    "Region":  "$Region",
    "SSL":  "$SSL",
    "DeviceName":  "$DeviceName",
    "Algorithm":  "$Algorithm",
    "MinerName":  "$MinerName",
    "PoolName":  "$PoolName",
    "ExcludeAlgorithm":  "$ExcludeAlgorithm",
    "ExcludeMinerName":  "$ExcludeMinerName",
    "ExcludePoolName":  "$ExcludePoolName",
    "Currency":  "$Currency",
    "Donate":  "$Donate",
    "Proxy":  "$Proxy",
    "Delay":  "$Delay",
    "Watchdog":  "$Watchdog",
    "MinerStatusUrl":  "$MinerStatusUrl",
    "MinerStatusKey":  "$MinerStatusKey",
    "SwitchingPrevention":  "$SwitchingPrevention",
    "DisableAutoUpdate":  "$DisableAutoUpdate",
    "ShowMinerWindow":  "$ShowMinerWindow",
    "UseFastestMinerPerAlgoOnly":  "$UseFastestMinerPerAlgoOnly",
    "IgnoreCosts":  "$IgnoreCosts",
    "ShowPoolBalances":  "$ShowPoolBalances",
    "ShowPoolBalancesExcludedPools":  "$ShowPoolBalancesExcludedPools",
    "Pools":  {
 "zergpool": {
"LTC" : "LeTUNYViANaPTypGuUpCKXihwghJyK1nE2",
"worker" : "$WorkerName"
              },

}   
 "Miners":  {

               }
}

**Comment by paulpoco** [comment]
Other than all the spaces are missing from pasting instead of uploading a .txt file version.

Change the } above Miners to },

**Comment by UselessGuru** [comment]
Use www.jsonblob.com to verify your config file. (or any other likeminded web page for that matter).

**Comment by paulpoco** [comment]
@UselessGuru that "}," that closes the Pool { section screwed me up at 1st.

**Comment by robl45** [comment]
okay, that seemed to work once I ran it through jsonblob
