### ISSUE TITLE
Miner-Algo specific exclusions

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2027]
Is there a way to do this?

I can see pools, or specific algos or pools, but can you specify either a pool-miner-algo specifically or at least a miner-algo?

**Comment by m-bosch** [comment]
Not possible yet as far as I know. Though I read about an idea about some extra features about this.

**Comment by UselessGuru** [comment]
> I can see pools, or specific algos or pools, but can you specify either a pool-miner-algo specifically or at least a miner-algo?

Miner-Algo can easily be done by disabling the algo in the miner file (just add a #)
