### ISSUE TITLE
Current ZergPool file only has BTC,LTC for currencies but ZergPool will also payout to DASH?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2029]
![image](https://user-images.githubusercontent.com/801414/43040257-2a8d4a4c-8cf4-11e8-8148-e533988d6e96.png)

Can I just change line 30 "$ZergPool_Currencies = @("BTC", "LTC") ....." to "$ZergPool_Currencies = @("BTC", "LTC","DASH") ...." ?

![image](https://user-images.githubusercontent.com/801414/43040266-81bf563e-8cf4-11e8-9c61-f173685f44b7.png)

At first I tried adding to config.txt:
	"ZergPool": {
	  "DASH": "XhNxxxxxxxxxxxxxxxxxx",
	  "Worker": "Workername"
	},
But when I ran it came back saying no Pool available.

For now I tried my LTC address to be the payout.

**Comment by UselessGuru** [comment]
@paulpoco 

> Can I just change line 30 "$ZergPool_Currencies = @("BTC", "LTC") ....." to "$ZergPool_Currencies = @("BTC", "LTC","DASH") ...." ?

This should work, assuming that you also change your config.txt as above.

I'll add DASH to ZergPool once we know if there are other changes to the pool file required for Equihash (so we can keep the number of changes down).

**Comment by UselessGuru** [comment]
Added DASH to ZergPool
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2049

**Comment by paulpoco** [comment]
It is in the PR and work fine.
