### ISSUE TITLE
Excavator 1.5.5a working for me

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2030]
I was able to get the version of 1.5.5a that @UselessGuru had posted earlier to work.  I have systematically put in the changes and do not see any instability.

I have noticed that there are newer versions of the miner since all this occurred but I am unsure if anyone wants to see these, so I am just putting out that I have it working and see if folks are interested.

I can post in the changes I made to make it work if anyone is interested.  I know 'I' am interested in updating to the newer version but I have not thought that process through, yet.

**Comment by nimbosa** [comment]
probably best to see a pull request for these changes? I'm interested to see this working

**Comment by UselessGuru** [comment]
See here
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2038
