### ISSUE TITLE
ShowPoolBalances on Blockmasters

### ISSUE THREAD

**Issue by david0815** [MultiPoolMiner/MultiPoolMiner#2033]
Please add `ShowPoolBalances` on Blockmasters. 
Thanks

**Comment by UselessGuru** [comment]
See if this one works for you 
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1805

Note: We do balances for BTC only

**Comment by paulpoco** [comment]
@UselessGuru is there a way to check for BTC but if a wallet is not provided, then check if another one like LTC was used in config.txt, then get that LTC balance from pool, then convert to equivalent BTC, then display that equivalant BTC balance with all the other pools?

**Comment by UselessGuru** [comment]
@paulpoco 

> hen get that LTC balance from pool, then convert to equivalent BTC, then display that equivalant BTC balance with all the other pools?

While it is technically an option, it is currently not implemented. BTC values only.

**Comment by UselessGuru** [comment]
Available here:
https://github.com/MultiPoolMiner/MultiPoolMiner/tree/UselessGuru_PoolBalancesMultiCurrrency
