### ISSUE TITLE
Help with Algorithm error

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#2035]
Can anyone tell me what is causing this?  The algorithm.txt file appears to be correct.  It appears to be happening from adding the extra equihash variants in.

[MultiPoolMiner_2018-07-22_17-59-32.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2217455/MultiPoolMiner_2018-07-22_17-59-32.txt)
[Algorithms.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2217456/Algorithms.txt)

**Comment by paulpoco** [comment]
First off not sure if you are allowed spaces after each "," in -algorithm part of start.bat?
![image](https://user-images.githubusercontent.com/801414/43050885-129fde82-8dc5-11e8-8550-420f284e50a5.png)
And you have duplicates also in start.bat.

And in your algorithms.txt you have duplicate entries.
![image](https://user-images.githubusercontent.com/801414/43050952-f70bfc36-8dc5-11e8-91d3-7e871e8e4a1b.png)

And in the start.bat only use the names on the right hand side of algorithms.txt.  I.e. do not use equihashbtg,equihash144,equihash192,equihash200,equihash2009,equihash96,equihashbtg and you have some of these twice

Not related but you have some algos that are not really good for GPUs anymore: CryptoNight,Scrypt,SHA256,X11, etc.

**Comment by robl45** [comment]
Problem is it only starts when adding in the extra equihash variants    maybe I'm getting some dupes that are causing issues?

**Comment by paulpoco** [comment]
What text editor are you using?  I use Notepad++.

**Comment by robl45** [comment]
I was using notepad.  Then I put it in powershell to see it lined up and fixed the algorithm on the same line.

**Comment by Kettoch** [comment]
I use MS Code.  When I launch it, I set the type to be JSON and then duplicates get high lighted.

**Comment by robl45** [comment]
Got that, and removed the duplicate equihash lines, still getting same errors.

**Comment by robl45** [comment]
Okay, so I took the algorithms.txt from the master and dropped it in and still the same errors popping up.  Works fine but its annoying getting all those errors.
[Algorithms.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2218917/Algorithms.txt)

Current algorithm.txt

**Comment by UselessGuru** [comment]
@robl

Algorithm.txt is broken (not just yours, also the one in master 👎 ) (Just checked using www.jsonblob.com)

I've updated the file in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2019
Use this (do not try to merge someting, just copy/paste) and report back! Thanks!

**Comment by robl45** [comment]
Tried new one, still getting same errors.  Here is my start.bat  I'm thinking it has something to do with the algorithms in there.  Is there an easy place to just get all the algorithms to put in the start.bat?
[Start1.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2221199/Start1.zip)

**Comment by UselessGuru** [comment]
> Is there an easy place to just get all the algorithms

 If you want ALL algorithms, then DO NOT specify -Algorithm at all (remove it from start.bat).

**Comment by robl45** [comment]
No and the multipoolminer.ps1 has changed a little bit, specifying different char on the line now.

[MultiPoolMiner_2018-07-24_06-30-36.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2223230/MultiPoolMiner_2018-07-24_06-30-36.txt)

**Comment by UselessGuru** [comment]
As long as you don't fix Algorithms.txt you will not make any progress.
You have hidden special characters in it.

**Comment by UselessGuru** [comment]
It is NOT the start bat. It is your broken Algorithms.txt as the error message clearly states.
[Algorithms.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2223297/Algorithms.txt)

**Comment by robl45** [comment]
Is the one you just listed here correct?  I took the one I'm using from the PR you mentioned and I even ran it through the jsonblob to make sure it was good.

**Comment by UselessGuru** [comment]
![capture](https://user-images.githubusercontent.com/30080938/43134392-3e79a28a-8f42-11e8-8db0-292012d23c80.PNG)

Yes, my one is correct.

**Comment by robl45** [comment]
Added it in.   Will see later when I get home.

**Comment by robl45** [comment]
[MultiPoolMiner_2018-07-24_18-05-48.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2225638/MultiPoolMiner_2018-07-24_18-05-48.txt)
[Algorithms.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2225639/Algorithms.txt)

Still same errors even with new algorithm.txt

**Comment by UselessGuru** [comment]
Algorithms.tst is now fine. 


PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."

Is most likely caused by a corrupt miner file - it does not say which one. Have you modified any of them?

Suggestion: Move all files from the folder 'MinersLegacy' to some other folder.
Start MPM & see if the error goes away. At some point it willsay 'No miners found'. That's OK.
Then move the miner files back one by one, check the logs.

**Comment by robl45** [comment]
Okay, this seems to be solved.  Apparently it didn't like the .zip that was in the miners folder from when I uploaded the EWBF2 file.  I had no idea it would do anything with that.

**Comment by UselessGuru** [comment]
Glad you found the cause.
