### ISSUE TITLE
DeviceName set to cpu only but GPU#01 still mines

### ISSUE THREAD

**Issue by Dewbs** [MultiPoolMiner/MultiPoolMiner#2039]
Wanted to temp stop gpu mining
localhost::3999/devices only contains cpu info (single)
GPU#01 listed in running miners (02 & 03 inactive) in main window
If I kill the miner it restarts on next cycle

edit:
if I start fresh it doesn't do this (i.e. it does only mine cpu) but when removing (in my case 'nvidia') the device from running config it still continues on 1 (first?) of 3 gpu's
Not a big deal but strange.

**Comment by UselessGuru** [comment]
Changing (adding/removing) devices in config during runtime is not supported.
