### ISSUE TITLE
HODL for cpu please 

### ISSUE THREAD

**Issue by jjziets** [MultiPoolMiner/MultiPoolMiner#2043]
Please add HODL for nicehash with cpu mining

**Comment by UselessGuru** [comment]
@jjziets 

Do you know of any available miner to do so? Links please - thank you!

**Comment by grantemsley** [comment]
https://github.com/nicehash/hodlminer-wolf/releases/tag/v2.4.3 is one, but people report cpuminer to be faster.

https://github.com/JayDDee/cpuminer-opt - which we already have says it supports HODL, so may just be able to enable that in the algoritms and miner file.

**Comment by UselessGuru** [comment]
Available with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2044
