### ISSUE TITLE
MiningPoolHub ethereum notification

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2051]
- Ethereum block height passed 6000000. If you are using old version of claymore your mining would be stopped due to epoch error. Please update to latest version. 

https://bitcointalk.org/index.php?topic=1433925.0

**Comment by UselessGuru** [comment]
Thank you - we are already on 11.9:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2004
