### ISSUE TITLE
Single card type - different miner per card?

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2053]
I suspect this has been investigated but I cannot find anything for this.

I have one system with a R9 290x and an RX 580 and generally under current code it is better for individual miners to run on these cards than to run one that will handle both.

But if you have one or more AMD or NVidia cards of the same type can the system test for individual speeds?  Many times, a just having an MSI vs a gigabyte 1080ti can cause performance differences.

I was just curious if the effort/reward has been talked about in enabling this.

**Comment by Kettoch** [comment]
well, I wasn't looking at fine-grained tuning, just that having them able to try single card benchmarks and let the chips fall where they lay.

**Comment by UselessGuru** [comment]
More coming:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2061
