### ISSUE TITLE
Web interface getting "Service Unavailable" message

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2063]
http://localhost:3999/
returns "Service Unavailable" message.

What do I need to check in my Network Setting to make sure localhost is not locked out for some reason?
Even http://localhost:3999/config doesn't work

It is reaching something because the message is different when MPM not running.

Well trying to delete anything with MPM in Windows Firewall, maybe a better way not to have millions of entries?

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/43619956-361f2638-9685-11e8-87e7-85e8f0cae0e6.png)

**Comment by paulpoco** [comment]
Ok got it working again by:
1) Resetting the Windows Firewall to original defaults.
2) Moving my working setup to a different Folder so that the security permissions get updated again.

Is there some kind of Script that can be included for resetting all the security permissions?

**Comment by UselessGuru** [comment]
> Ok got it working again by: ...

You should not need to to do any of this.
A simple reboot should do the trick.

> Is there some kind of Script that can be included for resetting all the security permissions?

No.
