### ISSUE TITLE
DisableAutoUpdate related to #1949

### ISSUE THREAD

**Issue by friendly-face** [MultiPoolMiner/MultiPoolMiner#2064]
I am having a problem with autoupdate closing MP because PowerShell launches and then determines that the installed version is the same or higher than the version that is being auto installed.  This problem only came up after I had successfully benchmarked and rebooted several times with CPU only mining and then added a single AMD GPU.  I have tried to follow the instructions provided for disableautoupdate but apparently I am too dense to be able to make it work as -disableautoupdate in the start.bat file does not work nor does adding the line "DisableAutoUpdate":  "$DisableAutoUpdate", to the config file.  I am attaching my logs.
[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2255232/Logs.zip)

**Comment by friendly-face** [comment]
I have also verified that the issue only occurs when I have a GPU plugged in to one of the slots.  Even if I have -type cpu,amd in the start.bat file as long as no GPU is installed the issue does not occur.

**Comment by UselessGuru** [comment]
@friendly-face

There are two types of auto update in MPM:
a) PWSH (Powershell core)
b) MPM (MultiPoolMiner code)

a) The PWSH (Powershell Core) will indeed close the running MPM processes.
Please:
1. Install PWSH (currenctly 6.0.3) manually (DL link: https://github.com/PowerShell/PowerShell/releases/download/v6.0.3/PowerShell-6.0.3-win-x64.msi), add the pwsh path to the path variable, then reboot.
This ensures that the latest PWSH version is found using the path variable
2. Uncomment the PWSH update line in your start bat. This will stop MPM from getting closed.

b) The MPM auto-update part is about to be removed: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2012
This can also be disabled by setting  -disableautoupdate in the start.bat
adding the line "DisableAutoUpdate": "$DisableAutoUpdate", to the config file DOES NOT WORK!
This update process just writes warning messages, but does not close MPM.

**Comment by friendly-face** [comment]
Thanks for your help.  My initial diagnosis was incorrect.
After commenting out the powershell update that no longer runs (thank you)
A short time after that I get a hourglass (swirl) like something is running, the script ends and I get press any key to continue and get kicked out of the script.
I then removed MPM, uninstalled PS 6.0.3 rebooted.
Reinstalled PS 6.03 into the default directory of c:\program files\powershell\That is already in the path after install.

Re-downloaded MPM 2.7.2.7 and ran start.bat without any changes and got the same behavior after I commented out the Powershell update - I didn't even change the username or minorname and it still kicks me out.
I updated to the path to also include the folder that MPM is extracted to.
Thanks again for all your help.
Let me know what files I can send you if they will help.
Tony





    On Friday, August 3, 2018, 2:02:20 AM EDT, Useless Guru <notifications@github.com> wrote:  
 
 
@friendly-face

There are two types of auto update in MPM:
a) PWSH (Powershell core)
b) MPM (MultiPoolMiner code)

a) The PWSH (Powershell Core) will indeed close the running MPM processes.
Please:
   
   - Install PWSH (currenctly 6.0.3) manually (DL link: https://github.com/PowerShell/PowerShell/releases/download/v6.0.3/PowerShell-6.0.3-win-x64.msi), add the pwsh path to the path variable, then reboot.   
This ensures that the latest PWSH version is found using the path variable
   - Uncomment the PWSH update line in your start bat. This will stop MPM from getting closed.

b) The MPM auto-update part is about to be removed: #2012
This can also be disabled by setting -disableautoupdate in the start.bat
adding the line "DisableAutoUpdate": "$DisableAutoUpdate", to the config file DOES NOT WORK!
This update process just writes warning messages, but does not close MPM.

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2094
