### ISSUE TITLE
Equihash 144 change with latest EWBF 0.5

### ISSUE THREAD

**Issue by pinpins** [MultiPoolMiner/MultiPoolMiner#2065]
This is announcement for Equihash 144 coins stratum setup change effective as of 06.08.2018 10:00 CET.
I am excided to annoucne that we managed to get personalized equihash coins profit switch without EWBF miner restart, as well as adding mc= functionality to equihash stratums.
Credits to EWBF developer supporting the change. We will group all Equihash 144 5 coins under one port equihash144.mine.zergpool.com:2146 making all Options(1,2,3) functionallity working with latest EWBF release 0.5.

More details
https://goo.gl/hejB5f

**Comment by UselessGuru** [comment]
All required changes are implemented in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2002

**Comment by paulpoco** [comment]
You have to wait till the notice.  Version 0.5 is fine but cannot use --pers auto until August 6 10CET
