### ISSUE TITLE
Zergpool has 3 guaranteed payout coins of BTC/LTC/DASH  .../Balances/ZergPool.ps1

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2067]
Zergpool has 3 guaranteed payout coins payout of BTC/LTC/DASH and .../Balances/ZergPool.ps1 does the balance.

I mine on ZergPool with a payout of DASH.  Right now MPM cannot handle non-BTC balances.

For myself I hard coded the .../Balances/ZergPool.ps1 to get the DASH balance from ZergPool.
Add a $Request2 = [PSCustomObject]@{}
Use https://min-api.cryptocompare.com/data/price?fsym=DASH&tsyms=BTC that returns {"BTC":0.02784} as a $Request2.
Then convert from DASH to BTC by using the:
"total" = $Request.unpaid * $Request2.BTC
which gives you the BTC value of your ZergPool DASH Balance.

Then on the main cmd.exe window for MPM you get a correct BTC - FIAT value at the bottom with the rest of the pools like Nicehash etc.

I am sure more talented than myself could adapt this to include the already used BTC and add LTC and DASH for balances for ZergPool?

[Balances-ZergPool.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2256179/Balances-ZergPool.txt)

![image](https://user-images.githubusercontent.com/801414/43627003-464ec67a-96a9-11e8-9b7e-dd6823948162.png)
At the time my DASH balance is 0.02634825 but it ends up being the same Fiat amount but calculated from BTC.
And when I see the ZergPool BTC getting close to 0.001 BTC then I know a tx will occur soon.

**Comment by UselessGuru** [comment]
Thank you for the input!

**Comment by UselessGuru** [comment]
@paulpoco 

We've started implementing multi-currency balances:
https://github.com/MultiPoolMiner/MultiPoolMiner/tree/UselessGuru_PoolBalancesMultiCurrrency

Any feedback is greatly appreciated.

**Comment by paulpoco** [comment]
-currency BTC,DASH,CAD
![image](https://user-images.githubusercontent.com/801414/43881043-b9b251ee-9b5f-11e8-9faa-2fcc6e71d405.png)
The "value in DASH" column is wrong, too small.

 

Will try just:
-currency BTC,CAD
![image](https://user-images.githubusercontent.com/801414/43881414-fa9a017e-9b60-11e8-9120-715fddab8b83.png)
This fine for me.

**Comment by UselessGuru** [comment]
@paulpoco 

I've updated and improved the code base. DASH is now calculated properly.

**Comment by UselessGuru** [comment]
> What if we added Exchange rates for currencies from the pools used?

Won't work - not all pools have exchange rates in their API. And we'd needed much more API calls. The present implementation does ***ONE*** API call for all rates :-)

@paulpoco 
> Ok here could be a way to eliminate the "Balance (BTC)" column

$ShowPoolBalancesDetails = $false should do the trick.

**Comment by UselessGuru** [comment]
> What if we added Exchange rates for currencies from the pools used?
Good idea! I'll see what I can do.

https://github.com/MultiPoolMiner/MultiPoolMiner/commit/f06d286c5c78920c885aca01cd55ae7f37008cc7

**Comment by paulpoco** [comment]
I'll get a chance later tonight to look at any other changes.

**Comment by paulpoco** [comment]
@UselessGuru it would be nice if a lot of the pending PRs get merged.  Making tough to test.

Tried your latest commit for the Pool Balances, not working for me as soon as I add the new "-ShowPoolBalances true -ShowPoolBalancesDetails true'.  This is a version with only your branch as merging all the old PRs is getting too hard.

C:\Users\pjb\Desktop\Mining Testing versions\MultiPoolMiner-UselessGuru_PoolBalancesMultiCurrrency f06d286\MultiPoolMiner-UselessGuru_PoolBalancesMultiCurrrency\MultiPoolMiner.ps1 : Cannot process argument transformation on parameter 'API_ID'. Cannot convert value "true" to type "System.Int32". Error: "Input string was not in a correct format."
At line:1 char:711
+ ... df3-078457830cd1 -ShowMinerWindow true -ShowPoolBalances true -ShowPo ...
+                                                              ~~~~
+ CategoryInfo          : InvalidData: (:) [MultiPoolMiner.ps1], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,MultiPoolMiner.ps1


[Start.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2279637/Start.txt)

**Comment by UselessGuru** [comment]
> it would be nice if a lot of the pending PRs get merged

I know. But there is nothing we can do for now. We need at least 2 people with write access to approve a PR. So until Aaron approves we will be stuck.

**Comment by UselessGuru** [comment]
> Cannot process argument transformation on parameter 'API_ID'. 

I did no change anything with API_ID... ???

I use TotalCommander to compare/merge stuff (select two files -> Files -> Compare by Content).

The multi currency balances have no dependencies except for:
- new balances files
- 
- https://github.com/MultiPoolMiner/MultiPoolMiner/compare/UselessGuru_PoolBalancesMultiCurrrency#diff-3a447b104ea55289de9757e0588b9862https://github.com/MultiPoolMiner/MultiPoolMiner/compare/UselessGuru_PoolBalancesMultiCurrrency#diff-69b5e62237d5f951ca1ac096869d0234

**Comment by paulpoco** [comment]
@UselessGuru config for now.
[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2279795/Config.txt)

I notice I get those errors when trying to set one of the -xxxxx true on my start.bat.

**Comment by UselessGuru** [comment]
@paulpoco

To start with your config.txt is broken :-( But that was not the reason...

Here is a fixed version with '$ShowPoolBalancesDetails' added:

https://jsonblob.com/fee3ab1e-9d39-11e8-a9e8-d1b0b1c30c02

```
C:\Users\pjb\Desktop\Mining Testing versions\MultiPoolMiner-UselessGuru_PoolBalancesMultiCurrrency f06d286\MultiPoolMiner-UselessGuru_PoolBalancesMultiCurrrency\MultiPoolMiner.ps1 : Cannot process argument transformation on parameter 'API_ID'. Cannot convert value "true" to type "System.Int32". Error: "Input string was not in a correct format."
At line:1 char:711
+ ... df3-078457830cd1 -ShowMinerWindow true -ShowPoolBalances true -ShowPo ...
+                                                              ~~~~
+ CategoryInfo          : InvalidData: (:) [MultiPoolMiner.ps1], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,MultiPoolMiner.ps1
```

Is caused by incorrect parameter syntax.
 > "ShowPoolBalances": "true",
> "ShowPoolBalancesDetails": "true",

This OK for the config file.
For command line switches you just need to add the parameter (e.g. ' -ShowPoolBalancesDetails'), but do NOT add any value (e.g. true/false).

**Comment by paulpoco** [comment]
@UselessGuru Managed to merge https://github.com/MultiPoolMiner/MultiPoolMiner/compare/UselessGuru_PoolBalancesMultiCurrrency#diff-69b5e62237d5f951ca1ac096869d0234 with all my other added PRs and it works now.  And used the corrected config.txt and put my correct API ID/Keys for MPM and MPMC.
![image](https://user-images.githubusercontent.com/801414/43994165-412e1f06-9d4d-11e8-83d6-b539a22dc29e.png)

I'll temporarily add back in zpool with LTC to see what it looks like.

**Comment by paulpoco** [comment]
Ok here is what a couple more pools with more currencies looks like:
![image](https://user-images.githubusercontent.com/801414/43994232-91c44066-9d4e-11e8-9026-e78caaf9b350.png)

This could be hard to read with may rows and columns, what if it had ascii characters to make it a table with lines like boxes?  There might need to be a limit across the width of the screen? If it is too much then that is ok too.

This a mock up with the cells:
![image](https://user-images.githubusercontent.com/801414/43994419-499cb00e-9d51-11e8-844b-3b202d4ef204.png)

**Comment by UselessGuru** [comment]
Glad you got it working... 👍 

> what if it had ascii characters to make it a table with lines like boxes?

AFAIK not possible. We use Format-Table which does not support what you are asking for.
