### ISSUE TITLE
Any issues with T-rex miner?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2068]
Any issues with T-rex miner?  Good?Bad? It is closed source.
Got it working in MPM.

Just one weird issue, is a double listing on the main screen:
![image](https://user-images.githubusercontent.com/801414/43668486-0b2bfa7a-9732-11e8-9a66-64f1ad510a5b.png)

https://github.com/paulpoco/MinerFiles/blob/master/NVIDIATrex.ps1

**Comment by UselessGuru** [comment]
None so far... :-)
I've modified to the code slightly so it matches MPM. Feel free to create a PR here, we can then approve it.

**Comment by paulpoco** [comment]
@UselessGuru I tried your modifications, work fine, just still see double entries for each Algo.
![image](https://user-images.githubusercontent.com/801414/43683064-61282ac2-9839-11e8-8637-a613473c50fe.png)

**Comment by paulpoco** [comment]
Only see doubles with T-rex.
[localhost3999devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2260790/localhost3999devices.txt)

**Comment by paulpoco** [comment]
Seeing it 2 times for each algo on CryptoDredge after updating to 8.2.
![image](https://user-images.githubusercontent.com/801414/43696302-2ef9d172-98f2-11e8-844d-21226f572ff1.png)

Updated 
[localhost3999devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2261137/localhost3999devices.txt)

**Comment by UselessGuru** [comment]
@paulpoco 

Problem found and fixed: https://github.com/paulpoco/MinerFiles/pull/2

BTW: CryptoDredge had the same error. Fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2006/commits/6e0c245bd48602c4753162f8fae26cc598284c3d

**Comment by UselessGuru** [comment]
Approved!
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2072

Feel free this issue to close if you are satisfied :-)
