### ISSUE TITLE
Phoenix Miner

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2069]
I have been doing some analysis of this miner and I have notice a couple of things.

- It seems benchmark very high
- It seems to maintain those numbers when running.
- But watching it seems to show Very few jobs actually coming in.

For all its speed there just doesn't seem to be the throughput of work that other miners seem to have.  Has anyone else noticed this?  It was so bad, I excluded the miner and my daily average seems to have risen because of it.  I am interested in any information that can help me tune this but I have found nothing so far to increase its throughput.

**Comment by UselessGuru** [comment]
For me PhoenixMiner is working and performing very well - no complaints in that department.
(I hve to confess I never really bother checking the hash rate at the pool).
