### ISSUE TITLE
Excavator 1.4.4a

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2070]
The way the miner currently runs, I see the following on the screen and in the log.

[[2018-08-04 12:11:22.834962] [thread=0x000031b0] [trace]]

	api | Received: {"params":["Worker [0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1&0&1] for miner Excavator-1-GPU#00-GPU#01 started. "],"id":1,"method":"message"}

I am not sure why this string seems to get longer and longer the more times it is stopped and started but it seems to happen with all of the miners.

**Comment by Kettoch** [comment]
I just validated that I am using the current code from the master, too.

**Comment by UselessGuru** [comment]
@Kettoch 

I'm on it.... seeing a similar issue with new excavator-nhmp too. Can you confirm?

**Comment by UselessGuru** [comment]
> I am also getting high levels of jobs not found after it has been running too long

This is a miner issue which has nothing to do with MPM's inner logic. I've not noticed anything like this.

**Comment by UselessGuru** [comment]
@Kettoch 

As I understand you correctly you are using ExcavatorNHMP in parallel with 'normal Excavator'.

I put me on the right track and I think I found the problem. Replace the ExcavatorNHMP files (the ExcavatorNHMP API file causes a class conflict):

https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2038

**Comment by Kettoch** [comment]
I was not getting a class conflict, just the on and on again growing worker name.  And the issue with the jobs.  I believe you might be right about it not being MPM, but could not tell with the other issue.

**Comment by UselessGuru** [comment]
> I was not getting a class conflict,

You would not see an error message, but the service IDs of both excavators got mixed up.

**Comment by Kettoch** [comment]
I will run this because I am certain it will reveal something.  But I was having a problem when just the old one ran.

**Comment by Kettoch** [comment]
I see the following line in the API.  Can it be that this array is never being reset?

`$this.Workers += "$($Data.worker_id)"`

**Comment by Kettoch** [comment]
@uselessGuru I am running this version but am not sure what I am looking for.,

**Comment by Kettoch** [comment]
@uselessguru I have found the issue.  It seems to apply to both the regular and NHMP excavator APIs.
`        if ($this.Workers) {`
`            if ([Excavator]::Service.Id -eq $this.Service_Id) {`
`                #Free all workers for this device`
`                $Request = @{id = 1; method = "workers.free"; params = $this.Workers}`
`                $Data = [Excavator]::InvokeRequest($this, $Request)`
`                #Clear all workers from variable`
`                [Array]$this.Workers = @()`
`            }`
`        }`

That one change (the last two lines) in BOTH APIs and the repeating string problem seems to disappear.  I have not seen any other ill effects yet.

**Comment by UselessGuru** [comment]
@Kettoch 

I have seen issues in that area. What I've seen before (but not anymore - and I cannot see the reason???) is that [Excavator]::Service.Id gets lost somehow.

`if ([Excavator]::Service.Id -eq $this.Service_Id) {` would then not match an no workers get cleared.

If you can reploduce the issue, what are the contents of `[Excavator]::Service.Id` and `$this.Service_Id` when this happens?

Your solution is not good because it does not stop the running workers, so you will continue mining.

A better workaround might be:

```
if ($this.Workers) {
    #Free all workers for this device
    $Request = @{id = 1; method = "workers.free"; params = $this.Workers}
    $Data = [Excavator]::InvokeRequest($this, $Request)
}
```

**Comment by Kettoch** [comment]
Well, What I have noticed when this happens is that the Array $this.Workers keeps growing in count.

I can reproduce the issue I have described, however, I have never seen it continue to mine when told to stop.  The behavior I see before my change is that the script continues to add the array $this.Workers.  This would cause the STOP script to increasingly try to stop more and more worker threads but only start the specified amount each time.

I have added API messages to various places and deleted the hashrate files for a couple of them a couple of times to show it occurring.  And all I see is what I describe.  I have never seen this run-on mining you are referring to.

Currently, I have backed out my change in Excavator and LEFT the change in ExcavatorNHMP but the additional logging is currently ONLY in the regular one.  I have some running around to do but when I get back, I will put the additional logging into both, run them... and post code and logs for you to review.

**Comment by Kettoch** [comment]
Actually, it is clearing the workers, because I have not touched that functionality.  But the screen keeps showing more and more workers in the variable.when it cycles through.  It isn't actually creating too many workers but the array to list them just keeps adding them.

Do you not see the string gain in size as it cycles through the same algo set each time?

So, $this.Workers should not have continue to add items to the end of the array every time it passes through a particular Algo.  For example neoscrypt for 2 cards with one worker per card should have $this.Workers.Count = 2 after starting both threads.  Theoretically either Stopmining, or the reset portion of Startmining should set that to 0 before the next time it starts.  My change resets the array to zero AFTER the free miner request is sent to the miner.

I am cleaning up a variable that does not seem to be maintained but I am not messing with anything that manages service ids or anything else.

Please let me know if I am missing what you are trying to tell me.

**Comment by Kettoch** [comment]
Here is a clean list and a test run of both miners three times by deleting the hashrate file each time.  The regular one has my change removed.  The NHMP one does not.  The functionality of both APIs is close enough to show what I mean.  Here is the MPM log, the two miner log files and both APIs I am using.
Timing didn't make for an exact back and forth but you should be able to follow it.
[MultiPoolMiner_2018-08-19.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2300785/MultiPoolMiner_2018-08-19.txt)

[Excavator-5401_2018-08-19_19-11-52.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2300786/Excavator-5401_2018-08-19_19-11-52.txt)
[Excavator-5400_2018-08-19_19-10-19.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2300787/Excavator-5400_2018-08-19_19-10-19.txt)
[MultiPoolMiner_2018-08-19_19-08-43.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2300788/MultiPoolMiner_2018-08-19_19-08-43.txt)
[Excavator.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2300789/Excavator.txt)
[ExcavatorNHMP.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2300790/ExcavatorNHMP.txt)

**Comment by UselessGuru** [comment]
@Kettoch 

I let your Excavator code run all day. Never did I see the issue you mention, so I cannot reproduce your issue. ???

Only once did a second instance of Excavator get launched, but it did not get any mining jobs assigned. This indicates an issue with the job handling created by Start-Process. I have seen this in other situations too. To get around that I am currently changing my code so it does no longer depend on the flaky job id and uses the process Id of each miner.

**Comment by Kettoch** [comment]
Do you have 2 nvidia's?  I am not sure if I ever saw an extra copy run.  How can I tell from the log?

**Comment by UselessGuru** [comment]
> Do you have 2 nvidia's? I am not sure if I ever saw an extra copy run

2x GTX 1080Ti

> How can I tell from the log?

You will see a second Excavator window sitting around idle.

**Comment by Kettoch** [comment]
Actually, no, I have never seen that.  As for the GPU config, that is what I have.

It is odd that we see two different set of symptoms.  If a second miner starts, would it create a new log file?  If so, neither miner created a second log file last night.

**Comment by Kettoch** [comment]
I have now run one way and the other with out the change and no ill effects and no lost or extra excavators other than when 1.4.4a is top when 1.5.x is up, albeit not mining simultaneously.

**Comment by Kettoch** [comment]
@UselessGuru are you planning on re-writing these like you said?  If not that two line change helps a lot.

**Comment by UselessGuru** [comment]
@Kettoch 

No, I will not re-write it because it works. Your code is not a fix as I already explained
