### ISSUE TITLE
Lots of the Pull Requests are still open?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2076]
I noticed @aaronsace hasn't approved anything in a month or so.  Is he away on vacation or ?

Just going to guess he is away for a break.
![image](https://user-images.githubusercontent.com/801414/43986550-4e425a8a-9cc7-11e8-997e-acda55f0b311.png)

**Comment by UselessGuru** [comment]
Don't know. But there is nothing we can do for now. We need at least 2 people with write access to approve a PR. 

So until Aaron approves all PRs from @UselessGuru and @GrantEmsley will be stuck. 
PR's from other people can be merged.

**Comment by Kettoch** [comment]
how many from your fork you just merged cover existing open PRs?

**Comment by UselessGuru** [comment]
@Kettoch 
 > how many from your fork you just merged cover existing open PRs?

Are you referring to https://github.com/MultiPoolMiner/MultiPoolMiner/tree/UselessGuru_PoolBalancesMultiCurrrency ?

I put in:
- Fixed Algorithms.txt (https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2019)
- Fixed Get-Stat (https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2037)
- Fixed Set-Stat (https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2040)

The rest is unchanged.

**Comment by paulpoco** [comment]
@UselessGuru I use the following without issue:
1903
1994
2001
2002
2006
2007
2012
2019
2020
2031
2032
2038
2046
2047
2049
2059
2060
2061
2066
2071
2075

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2094
