### ISSUE TITLE
couldnt find this issue by anyone else....

### ISSUE THREAD

**Issue by platinumdubs** [MultiPoolMiner/MultiPoolMiner#2079]
have a this going on everytime i start mpm and everytime it starts a run
[MultiPoolMiner_2018-08-12_09-29-14.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2281026/MultiPoolMiner_2018-08-12_09-29-14.txt)

**Comment by UselessGuru** [comment]
> PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\plati\Downloads\MultiPoolMiner-master\MultiPoolMiner-master\Stats\MiningPoolHubCoins_Electroneum_Profit.txt' because it does not exist."

This is a cosmetic error and is fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2040

**Comment by UselessGuru** [comment]
No, it is not.
But as it looks you are using very old code. There is no such line 289 in the current code base.

Please try this to start:
https://github.com/MultiPoolMiner/MultiPoolMiner/tree/MultipoolMiner_FullyMerged

**Comment by chabgood** [comment]
it is 2.7.2.7 which is the latest on the releases page.

**Comment by Kettoch** [comment]
@chabgood You may be technically correct but MPM is undergoing a fundamental change from what that version is.  There are no miners currently supported that work with that version in any reasonable way.

That being said, Please start with a fresh copy of that fully merged @UselessGuru speaks of.  It will go along way towards a stable system.  I make a personal habit of testing any new PRs that are floating around so I do not update to masters like he suggest very often.  Usually on weekend I have time to mess with it.
But start there, please.

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2094
