### ISSUE TITLE
Algo 1445 not benchmarking Miningpoolhub

### ISSUE THREAD

**Issue by Byrd1083** [MultiPoolMiner/MultiPoolMiner#2085]
I have implemented the upto date algo list which did get zergpol working on 1445 and 1927 thanks devs! However, miningpoolhub does not benchmark any 1445. It can be the most profitable at times on that pool and sucks that I can not mine it with MPM. I appreciate the fix for zergpool. Can we get a fix for MPH? Or is there one and I have missed it. I searched all through the list of issues and can't find anything on this specific problem I have run into. I have never been able to get this benched with MPH. Just a heads up the latest nemosminer does bench 1445 correctly for MPH. Maybe some code can be used to get working?

**Comment by grantemsley** [comment]
There is no need to benchmark each algorithm for each pool separately.
The most profitable pool is selected, then benckmarks and mining are done against that pool.

MiningPoolHub just isn't as profitable as zergpool at the moment.  I'm seeing zergpool at 3070 BTC/GH/Day and MPH at only 1653 BTC/GH/Day.

You can see this all in the web interface at http://localhost:3999/allpools.html

**Comment by Byrd1083** [comment]
That would explain it. Thanks for clarifying.
