### ISSUE TITLE
Keeps trying to download old version of Powershell

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#2088]
I'm having an issue with the latest master where it keeps trying to download Powershell every so often and says I have a newer version than it is downloading.  This pops up in a little window and all mining stops until I click okay on the window.  I thought I had taken care of this by uninstalling powershell and letting multipool miner download it again, but it happened again this morning.  I never ran into this issue previously.

**Comment by robl45** [comment]
I downloaded the master code like 2 weeks ago.   It's getting to install
6.0.2 when 6.0.4 is installed.

**Comment by UselessGuru** [comment]
> It's getting to install 6.0.2 when 6.0.4 is installed.

That's why you need these two PRs:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2066
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2012

**Comment by robl45** [comment]
Is there a complete master I can download with this in it to reduce the
chance of any issues?

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/tree/MultipoolMiner_FullyMerged

**Comment by robl45** [comment]
downloaded that link, same problem tonight.  Stopped with window popped up saying a newer version of powersheel is already installed.

**Comment by UselessGuru** [comment]
@robl45 

I checked all code of the fully merged branch - there are only references to version 6.0.4. and not other versions.

Make sure your PWSH installation is correct and the path variable includes the PWSH-directory (default would be (C:\Program Files\PowerShell\6.0.4\).

**Comment by robl45** [comment]
So this code should not update?

**Comment by UselessGuru** [comment]
>> So this code should not update?

Correct. Not if you have 6.0.4 installed

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2094

**Comment by robl45** [comment]
So this new master I'musing just tried to download 6.0.4 and got stuck with a window popping up.
