### ISSUE TITLE
Error when starting MPM red script 

### ISSUE THREAD

**Issue by izzledude** [MultiPoolMiner/MultiPoolMiner#2089]
I get an excavator error when starting MPM  the main CMD screen shows a ton of red script then will restart and go normal but ill get this error.  Red script goes to fast i cant copy  but it says something about an excavator error. Ive tried to re move and re install excavator but still same issue.  

[[2018-08-17 08:16:53.409614] [thread=0x00001950] [info]]
        Log started
[[2018-08-17 08:16:53.753693] [thread=0x00001950] [info]]
        core | Found CUDA device: GeForce GTX 1070
[[2018-08-17 08:16:53.950735] [thread=0x00001950] [info]]
        core | Found CUDA device: GeForce GTX 1070
[[2018-08-17 08:16:53.960737] [thread=0x00001950] [info]]
        core | Found CUDA device: GeForce GTX 1070
[[2018-08-17 08:16:53.972739] [thread=0x00001950] [info]]
        core | Found CUDA device: GeForce GTX 1070
[[2018-08-17 08:16:53.982742] [thread=0x00001950] [info]]
        api | Listening on 127.0.0.1:5100
[[2018-08-17 08:16:53.984742] [thread=0x00001950] [info]]
        core | Initialized!
[[2018-08-17 08:16:54.002746] [thread=0x00001950] [debug]]
        api | Accepted 127.0.0.1:50664
[[2018-08-17 08:16:54.028752] [thread=0x00001950] [trace]]
        api | Received: {"method":"algorithm.list","id":1,"params":[]}
[[2018-08-17 08:16:54.028752] [thread=0x00001950] [debug]]
        core | Command method: algorithm.list
[[2018-08-17 08:16:54.028752] [thread=0x00001950] [trace]]
        api | Sending: {"algorithms":[],"id":1,"error":null}
[[2018-08-17 08:16:54.035754] [thread=0x00001950] [debug]]
        api | Connection lost 127.0.0.1:50664
[[2018-08-17 08:16:55.082111] [thread=0x00001950] [debug]]
        api | Accepted 127.0.0.1:50666
[[2018-08-17 08:16:55.083111] [thread=0x00001950] [trace]]
        api | Received: {"method":"algorithm.list","id":1,"params":[]}
[[2018-08-17 08:16:55.083111] [thread=0x00001950] [debug]]
        core | Command method: algorithm.list
[[2018-08-17 08:16:55.083111] [thread=0x00001950] [trace]]
        api | Sending: {"algorithms":[],"id":1,"error":null}
[[2018-08-17 08:16:55.083111] [thread=0x00001950] [debug]]
        api | Connection lost 127.0.0.1:50666
[[2018-08-17 08:16:56.174478] [thread=0x00001950] [debug]]
        api | Accepted 127.0.0.1:50668
[[2018-08-17 08:16:56.175479] [thread=0x00001950] [trace]]
        api | Received: {"id":1,"method":"algorithm.add","params":["equihash","172.65.195.76:3357","32X9tGQaPsF1eexm6aortUcZqgQosfFohx.1070MRIG:x"]}
[[2018-08-17 08:16:56.175479] [thread=0x00001950] [debug]]
        core | Command method: algorithm.add
[[2018-08-17 08:16:56.175479] [thread=0x00001950] [trace]]
        api | Sending: {"id":1,"error":"Wrong number of arguments"}
[[2018-08-17 08:16:56.175479] [thread=0x00001950] [debug]]
        api | Connection lost 127.0.0.1:50668

**Comment by izzledude** [comment]
[Excavator-5100_2018-08-17_08-33-51.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2297823/Excavator-5100_2018-08-17_08-33-51.txt)

**Comment by UselessGuru** [comment]
Please upload 

- http://localhost:3999/devices
- zipped contents of the log folder

**Comment by izzledude** [comment]
[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2297878/Logs.zip)

I added all the logs

**Comment by UselessGuru** [comment]
Can you please try these files:

[Excavator.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2297955/Excavator.zip)

**Comment by izzledude** [comment]
It started mining. ill report back as i watch for errors.
