### ISSUE TITLE
Multipool Monitor Not Working

### ISSUE THREAD

**Issue by Byrd1083** [MultiPoolMiner/MultiPoolMiner#2097]
Any ideas why the multipool monitor will not work? About a week ago, I was getting monitor reports perfectly fine with green boxes on all. Nothing has changed in my start.bat and the key is identical yet all 3 of my rigs will not show up on the report anymore. Weird thing is they show they reported for a brief second when I restart MPM but then the report window goes pink as if all 3 are no longer reporting and will show last reported however many minuets ago I restarted MPM. I can walk up to all 3 and see they are running. No firewalls blocking either. All exceptions have been made. I'm stumped.

**Comment by skovesh** [comment]
Important fixes #2094 in Pull requests does the job OK now !

**Comment by skovesh** [comment]
Sorry, it worked but after deleting logs, benchmark and profit I get:
Write-Log : No wallet or username specified. Cannot continue.
At F:\MINE\MultiPoolMiner\MultiPoolMiner.ps1:377 char:9
+         Write-Log -Level Error "No wallet or username specified. Cann ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

**Comment by Byrd1083** [comment]
So, I let them run for 4 hours or so today after restarting all same time. I have all 3 rigs set to -interval 3600 (1 hour). Every time the miner switch happens, it quickly reports but then disappears so I would like to think I have the start.bat configured properly. However, when I check the key online it shows the last time miners were logged concurs with the miner switching 1 hour intervals. It just is not staying connected and shows pink. Not sure what to do at this point. I'm far from a java code expert. I double checked firewalls and all is open no blocks.

**Comment by Byrd1083** [comment]
Update, on another issue I was using switchingprevention 2 and interval 3600. Been trying to work that out. Today I removed the interval setting it back to stock 60 and now the report is working as expected.

**Comment by UselessGuru** [comment]
> skovesh 

> `Write-Log -Level Error "No wallet or username specified. Cann ...`

You are the second one report this.
Since I cannot reproduce it could you please upload your start batch file as well as the config file? TIA!

**Comment by skovesh** [comment]
sure, here they are - toggling the capital letters from the bat file, did it and now it's working
[Start-MiningPoolHub.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2317465/Start-MiningPoolHub.zip)

 !

**Comment by UselessGuru** [comment]
> did it and now it's working

What exactly did you change. Do you have old and new?

I run the code exactly as posted in 'Important fixes' and cannot reproduce the issue. Furthermore are the parameter names case insensitive, so it should not make a difference. ???

**Comment by UselessGuru** [comment]
> changing the capital letters did the job and currently running .

This I don't understand. In which files did you change what?

Of course the behaviour changes is you use a different multipoolminer.ps1.
We need to find out why the new code is causing issues for you, but neither for me nor grant.

**Comment by skovesh** [comment]
the change I did was only in Start-MiningPoolHub.bat: -wallet and not -Wallet, -username and not -Username, -workername and not -Workername, etc. I changed them all and haven't tried to change one at the time.

**Comment by skovesh** [comment]
well, I dled last multipoolminer.ps1 from mkirov0, renamed all in Start-MiningPool.bat with CAPital letters, and seems now all working. Have no idea what happened before. I can test whatever code you'll need.
Thanks a lot.

**Comment by Byrd1083** [comment]
In my start.bat I was using - interval 3600 -switchingprevention 2. Report stogie show when switch happens then back to pink immediately.

Changed interval to 60 and switchingprevention to 5. Now report stays green an upto date properly. No modification to codes anywhere.
