### ISSUE TITLE
Price degrades over time. Auto restart with timer feature request.

### ISSUE THREAD

**Issue by Byrd1083** [MultiPoolMiner/MultiPoolMiner#2103]
Hello again, I keep fighting the degration of price accuracy from pools. I can reset profits, Miner shows 100% on all and mining as it should. After 24 hours of mining the profits are all dropping below 90% and some as low as the 60%'s. From the reading I've done up here, I sounds like an issue from the pools side misreporting. That still doesn't really make much since why I can reset profits and restart and all profits are back to correct as if the pool is not the problem. Is this an issue with the program or the pool? I'm sure that there is some kind of algo doing this behind the scenes but it just doesn't make any sense why I have to reset profits, and restart the miner every morning to correct. Which brings me to my issue title. If this crazy pool price issue can not be worked out and I'm just told to reset everyday to correct, could we get some kind of work around similar to a stop and restart timer like this 

https://cryptomining-blog.com/2831-simple-script-to-restart-your-miner-software-after-a-given-period-of-time/

Only thing is if this were to work MPM would have to automatically force close all miners and windows running to restart with out building a million windows on top of each other. I asked about this in another support question.

**Comment by thebeerbaron2018** [comment]
As far as I understand it - the percentages shouldn't be all 100% - they start there and move down to the correct level over time.   The stats files record fluctuations in the pool prices and algorithms that vary wildly will get a much lower percentage than those that have a stable pay rate.  This should mean that after a period of running the more averaged stable prices will net you more than jumping on every spike for 2 minutes - it also assists with switching prevention so you spend more time mining and less time switching miners.

**Comment by Byrd1083** [comment]
No this makes more sense. Thank you for looking into it. I will just let them run as intended. I'm currently using switchingprevention 5. Is this okay or should I use just stock settings of 2? Was trying to get a switch only around an hour interval avg. I was adding interval manually but it messed up the mpm monitor report so I just deleted that line because the monitor is important for me being on the go.

**Comment by thebeerbaron2018** [comment]
If you only want to switch (or check) every hour then use "-interval 3600" in your batch file, switching prevention leave set to 2.  This means each cycle will last an hour before it checks and may still decide not to switch anyway.  The only problem with doing this is that the stats files are not updated as frequently so the counters won't be as accurate.  Personally I would set the interval to be 5 or 10 minutes (300 or 600).
