### ISSUE TITLE
Multiple pwsh instances.

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2105]
I am seeing a continuing increase in the number of pwsh instance running on both of my systems.

I do not see the windows start on one system but on the other I can see a window out of nowhere look to start and then hide.  However, I see many, many copies of them in task manager and the count keeps growing.

it seems like I get another copy running every time a miner is stopped and started.

Ran this every time a miner stopped and started and the count increases. (get-process -ea silentlycontinue 'pwsh').count

**Comment by Kettoch** [comment]
Where in the script ACTUALLY launches the miner.  I can see where the old one is stopped.

For some reason I cannot find it anywhere that makes (to me).

**Comment by Kettoch** [comment]
Well, I have a better idea how miners start but I still seem to collect a lot of extra pwsh.exe running processes.  Thought it might be the downloader but I do not see that now.

**Comment by Byrd1083** [comment]
I have the same problem plus it maxes out the memory causing system instability. I'm using Chrome remote desktop to manage. When I log in after running and keeping hundreds of windows open, chrome either won't open or crashes since no more memory. If I restart the miners every morning, it does not have enough time to run out of memory and lag is not as noticeable. I'm waiting for a response on fix as well. I proposed an automated timer restart for things like this but...

**Comment by UselessGuru** [comment]
@Kettoch 

This non-standard behaviour. I do not see this.
Could https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2070 be related to this?

What are the command lines that were executed with all these PWSH instances? (Task Manager -> Details -> Select columns -> tick 'Command line'

**Comment by Kettoch** [comment]
No this occurs on my amd only machine

**Comment by UselessGuru** [comment]
> as for what command lines, I have not figure it out.

Task Manager -> Details -> Select columns -> Right click, then tick 'Command line'

https://www.winhelponline.com/blog/configure-task-manager-to-display-full-path-of-running-processes/

**Comment by Kettoch** [comment]
"C:\Program Files\PowerShell\6.0.4\pwsh.exe" -s -NoLog -NoProfile, TONS of them.

**Comment by Kettoch** [comment]
I think it's the two log viewers.  If I do not run the current ones I have it does not happen.

**Comment by UselessGuru** [comment]
> I think it's the two log viewers. 

Still not sure about that.
It could as well be the hidden miner windows.
Does the error persists if you start MPM with `-ShowMinerWindows`?

**Comment by Kettoch** [comment]
Actually, on my AMD system (grabbing the new fully merged you just put up (thank you) does it but only when the miner log viewer window is up.  When I closed that and left other up, my process count is stable.
If I manually run it again using the command line, the process count increases again until I close the window and it resets back to the stable count.

**Comment by UselessGuru** [comment]
@Kettoch 

> miner log viewer window

I am confused. Is this 
- the miner windows (just as if you were the miners running stand alone) 

or 

- one of the two log reader windows?

Does the error persist if you start MPM with '-ShowMinerWindow'?

**Comment by Kettoch** [comment]
Well, I have not run showminerwindow.  I have, however, taken your lasted fullymergerd and put it in a new directory.  I put my batch file and my config file in it with a clean directory.  I then made a HOLD directory and moved ALL miners but claymoreethash into that hold directory.

Within in 10 minutes of starting the batch file and leaving every window open that the batch file starts, I had like 4 extra processes beyond what running the benchmarks it would run would create.

**Comment by UselessGuru** [comment]
This should no longer happen with 3.1.0:

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/3.1.0
