### ISSUE TITLE
No config.txt in latest master?

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#2108]
Downloaded the latest master as it was said to fix the updating powershell issue, but there is no config.txt.  Should I just copy it over from previous version or is there a new way to specify to use LTC for certain pools?

**Comment by Kettoch** [comment]
Copy your previous one unless you have something break.  Then run it without and let it create it.
Note that the default config does not give you the full scope of what you can do with the file.

**Comment by UselessGuru** [comment]
> but there is no config.txt. 

The config file is auto generated on first start of MPM.

>  is there a new way to specify to use LTC for certain pools?

Same as in older versions.
