### ISSUE TITLE
wrong #2094

### ISSUE THREAD

**Issue by skovesh** [MultiPoolMiner/MultiPoolMiner#2109]
getting errors and stop:

F:\MINE\MultiPoolMiner\MultiPoolMiner.ps1 : Missing an argument for parameter 'Algorithm'. Specify a parameter of type 'System.Array' and try again.
At line:1 char:280
+ ... h,zergpool -ExcludePoolName HashRefinery,BlazePool -Algorithm -Algori ...
+                                                        ~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [MultiPoolMiner.ps1], ParameterBindingException
+ FullyQualifiedErrorId : MissingArgument,MultiPoolMiner.ps1

**Comment by UselessGuru** [comment]
Please port the start batch file. 

`-Algorithm -Algori ...`

looks not OK.

**Comment by skovesh** [comment]
Thanks, stupid me, searched for hours.....
