### ISSUE TITLE
MiningPoolHub with 2 workers

### ISSUE THREAD

**Issue by gs1960** [MultiPoolMiner/MultiPoolMiner#2114]
Hi guys, it's possible run MPM for use un ID with 2 workers on MPH, one with NVIDIA and one with AMD?
MPM will run the 2 cards simultaneously and the hasrate will be double?  Or will run one card at a time?

Thank you!

**Comment by UselessGuru** [comment]
I am not sure if I understand you correctly.

MPM will use ALL available GPUs/CPUs for mininig (in default configuration).
So you will always get the maximim profit.

Lets assume you have 2x Nvidia 10790 and 2x AMD RX570 then MPM will run two miners/workers simultaneously, one for the Nvidia cards, and nother one for AMD.

**Comment by gs1960** [comment]
Hi dear, thank you.
I know that MPM  will can run two miners/workers simultaneously.
my doubt is if only one instance Start-MiningPoolHub.bat can execute a single ID with two workers (one AMD and one NVIDIA).
For example:
ID MPH: pippo
Worker1: AMD
Worker2: NVIDIA
Please check the picture....
![mph 2 workers](https://user-images.githubusercontent.com/37365706/44897810-476f9b00-acfd-11e8-96ee-66e17a13c227.png)

**Comment by UselessGuru** [comment]
Ahh... I've never thought of that... and never saw the need for it :-)

Out of the box MPM cannot do this. 

Just trying to understand ;-)
Why do you want to do this? What is the benefit?

**Comment by UselessGuru** [comment]
For what you have you don't need to :-)

One worker with MPH for all cards is fine. Frankly I've never quite understand MPH in that respect. This is how I understand it:

MiningPoolHub.ps uses ports 17xxx -> coin switching only, no algorithm switch
MiningPoolHubCoins.ps1 uses ports 20xxx -> no switching at all

So in both cases the worker settings are irrelevant (correcte me if I'm wrong)

**Comment by gs1960** [comment]
Honestly I do not know
So you say that in MPH i can keep only one worker called "multipoolminer" with AMD or NVIDIA, indifferently and MPM will run both cards simultaneously at the max performance?

**Comment by gs1960** [comment]
I'm testing what you said ....
In MPH I set AMD on the into the job of the "multipoolminer" worker, but I have an NVIDIA card on run and ... it seems to me that nothing has happened, so I would say that it works regardless of the job set.
If it's so, it's perfect!
