### ISSUE TITLE
HSR algorithm

### ISSUE THREAD

**Issue by Majorbafe** [MultiPoolMiner/MultiPoolMiner#2115]
Does anyone know what happened to the HSR algo?
I noticed that it disppeared from MPM and I cannot find it on any of the pools....

What the heck?!?!?

**Comment by UselessGuru** [comment]
An algo does not disappear from MPM. :-)

However if no pool is offering it then MPM cannot do anything about it.

**Comment by Majorbafe** [comment]
But do you know what happened to HSR? It is gone....

**Comment by mkirov0** [comment]
I looked around the pools and I don't see any pool offering HSR as a mining option. This is probably a good reason why MPM does not "offer" it. If you really want to mine HSR you can probably find other pools that run a node.

**Comment by Majorbafe** [comment]
But in the beggining of August there was HSR on Zpool and ZergPool, at least that I remember....

I know it's not a problem with MPM, I am just asking if there is any problem with this algo worldwide...
