### ISSUE TITLE
Move command customization to separate file excluded from git

### ISSUE THREAD

**Issue by Jaerin** [MultiPoolMiner/MultiPoolMiner#213]
Be nice if we could move the custom commands for difficulty setting and intensity out of the miner files so that we can still update them from git without having to manually hack in merges.  Also might make updating multiple mining rigs easier since they could each have their own custom files that don't need transferring.

**Comment by Jaerin** [comment]
Also might be nice to make that the location that we enabled/disable each miner and algos for each miner instead of deleting from the miners folder.  Only to keep everyone's installs a lot more consistent and upgradable.

**Comment by scaras** [comment]
you can see the history of a file and only copy the changed lines 
[example](https://github.com/aaronsace/MultiPoolMiner/commit/622485e717d35abf4cd60d7abccaa830123e612e)

**Comment by Jaerin** [comment]
Of course you can, it is simple to merge during a git pull as well.  Still would be nice if the user level customization wasn't in the definition files themselves.  Pretty standard programming practice.  Given that every user will have their own customizations to these files tuned to their mining rigs it seems logical to have a user's settings type of structure for easier manipulation.

**Comment by aaronsace** [comment]
The files in the 'miners' folder are meant to be the config files and preferably all moved to json. I would prefer more generic customizations and automatic detection in the main code so that it is not nessesary to do advanced customization.

**Comment by Jaerin** [comment]
I guess what I'm suggesting be changed is the idea that you delete the files to disable and modify them to add difficulty and intensity.  This means every time you go to pull from the git it wants to overwrite your changes or you have to stash and hope they merge after the pull.  First world problem since most likely won't be pulling from git, but it is annoying that these settings are embedded in the actual code is all I'm saying.

**Comment by scaras** [comment]
or make a txt file with the { "algo" = "commands" } line for the miners so you can copy/paste your own settings from there

**Comment by UselessGuru** [comment]
Possible solution: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1237
