### ISSUE TITLE
-ExcludePoolName function aint working

### ISSUE THREAD

**Issue by crypt0kzn** [MultiPoolMiner/MultiPoolMiner#2148]
I have been trying to modify start.bat and exclude/avoid some miners and pools; even though i followed the steps in readme file and set the only pool to ahashpool; i see the miners are running in hashrefinery? 

Same thing for the excluding miner command in the start bat file. Do I need to delete these things from the binders?

**Comment by paulpoco** [comment]
Other pools will run during donation run.

**Comment by UselessGuru** [comment]
@crypt0kzn 

Please provide more information:

Start batch file, config file & zip the contents of the logs folder. Thank you!
