### ISSUE TITLE
Issue: Scrypt error at startup

### ISSUE THREAD

**Issue by Byrd1083** [MultiPoolMiner/MultiPoolMiner#2149]
Been a way for a while. I've been using an older version that was working fine. I tried to update today to the latest master file and I now get scrypt errors at startup on new clean install.

![image](https://user-images.githubusercontent.com/42227809/44952751-4abd7080-ae3c-11e8-812b-c0c6f7dff9ff.png)

**Comment by Byrd1083** [comment]
My config and start.bat

[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2343004/Config.txt)

[Start.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2343006/Start.txt)

**Comment by UselessGuru** [comment]
This a known bug, I am working on it.

**Comment by UselessGuru** [comment]
Please try MultiPoolMiner.ps1 in this PR:

https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2120

And report back if the issue is fixed for good. Thank you!

**Comment by titvs** [comment]
Im having a similar issue with the latest commit. Running PS 6.0.4
![issue_startup](https://user-images.githubusercontent.com/31544730/44987781-4dc17980-af80-11e8-8b17-356e2c5d5287.jpg)

A previous commit (maybe from the beginning of August) that i have in another directory is working ok. Same BAT files.
Im struggling with GitHub to download the modified MultiPoolMiner.ps1 from the PR 2120... :P

**Comment by UselessGuru** [comment]
@titvs 

Your start bat file has an encoding problem. Look at the very first line... these funny characters were probably added when you modified the start bat file. With what editor did you edit it?

**Comment by titvs** [comment]
@UselessGuru ive noticed that... I edited with Notepad++ and there's nothing at the beginning… I even copy-pasted the same initial lines from the other bat file thats working and it gives the same error. Its very weird...

**Comment by UselessGuru** [comment]
With Notepad++ try setting the encoding to UTF-8 (without BOM)

**Comment by UselessGuru** [comment]
Titvs: Thank you for your positive feedback.
