### ISSUE TITLE
Blockmasters Pool Balances

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2151]
Is there a balances file that works with Blockmasters?  I am mining with my BTC address.

**Comment by UselessGuru** [comment]
Coming...

See https://github.com/MultiPoolMiner/MultiPoolMiner/tree/UselessGuru_PoolBalancesMultiCurrrency

**Comment by Kettoch** [comment]
thank you.  It appears that when I use Blockmasters, nearly everything switches over.  So it will be nice when I can see that, too.

**Comment by UselessGuru** [comment]
> thank you. It appears that when I use Blockmasters, nearly everything switches over. So it will be nice when I can see that, too.

I will soon bring some changes to correct the overoptimistic earnings reported by some pools. They all overestimate, but not to the same extent.

What are the factors you feel the we should reduce the over-optimistic projected earnigs?
0.4 = I get roughly about 40% of the projected earnings
 1 = the projected earnings as reported by the pool mach real world

e.g.: Nicehash 0.9 (real earning are about 90% of what MPM currently reports

Can you give estimates for each pool?

**Comment by Kettoch** [comment]
Well, you bring up an aspect of this I had not thought of and will need to look at it but will not have time before I go on vacation next week.  However, I was talking about the fact that using BlockMasters switches over and now I cannot see where my profit is going because it is not a pool that is queried.

**Comment by UselessGuru** [comment]
@Kettoch 

Try this file:
[BlockMasters_ps1.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2343867/BlockMasters_ps1.txt)

**Comment by Kettoch** [comment]
It sort of works, but I had to remove references to the currencies.   Apparently per the Blockmaster's admin says they do not turn that part on all that often.

**Comment by UselessGuru** [comment]
@Kettoch 
> It sort of works, but I had to remove references to the currencies. 

Please be more specific, or post your modified script so we learn to understand the issue.
