### ISSUE TITLE
Feature Request:  Add API address to config.txt

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2152]
I have several rigs and I use the new wonderful web interface to monitor my rigs from another machine.

I regularly edit the API to change the address as you guys correct or enhance the include.ps1.

**Comment by UselessGuru** [comment]
Do you mean the API port?

**Comment by Kettoch** [comment]
Well the port was ok, but maybe it should be is a configurable url for the API.  I originally was taking about the ip.

**Comment by UselessGuru** [comment]
The API is always localhost.

**Comment by Kettoch** [comment]
I know it is... but does it have to be.  The API and the Web UI use the same port right now.  I can understand the API staying on localhost, but then do we split up the Web UI and the API to two separate threads and ports (and potentially NOT localhost)?

**Comment by UselessGuru** [comment]
> The API and the Web UI use the same port right now.

Because they access the same data. As I see it this cannot be split. Maybe GrantEmsley can give a different answer.

**Comment by UselessGuru** [comment]
>I have a way that only prompts when you switch between localhost and public in my fork, but haven't ported it back to here yet. It can be done.

RemoteAPI and configurable port are implemented in 3.3.0 Beta 2
