### ISSUE TITLE
Enhancement: Separate stats folder with sub folders

### ISSUE THREAD

**Issue by Byrd1083** [MultiPoolMiner/MultiPoolMiner#2153]
Could we get an enhancement to separate the stats folder for cpu, amd, nvidia, and pools? It would make it faster to find a bad benchmark and delete it for 1 miner rebench. Similar to Rainbowminer feature.

**Comment by thebeerbaron2018** [comment]
If the naming convention is going to be changed so each miner starts with CPU-xxxx, NVIDIA-xxxx and AMD-xxxx this wouldn't be a problem?

**Comment by UselessGuru** [comment]
> CPU-xxxx, NVIDIA-xxxx and AMD-xxxx this wouldn't be a problem?
Any miner name change will require re-benchmarking. Technically this is no problem.

I think we should follow the convention as lined out here:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1931

In my personal build I have also changed the miner names from GPU#00,GPU#01 to 2xGTX1080 etc.

This way benchmarks remain valid even after a hardware change.

**Comment by UselessGuru** [comment]
> In my personal build I have also changed the miner names from GPU#00,GPU#01 to 2xGTX1080 etc.
> This way benchmarks remain valid even after a hardware change.

Would you consider this useful?

If we decide to rename the miners, then it needs to be done as big batch, so benchmarking only need re-done once.
I'd quite like to hear @aaronsace feedback on this.

**Comment by thebeerbaron2018** [comment]
I'd leave the GPU#00 etc... because in my rigs I have many GTX1070's all from MSI but some are identified differently (I assume they changed name slightly in BIOS) - since I use all the same card - I currently copy the config from a single benchmarked rig to the other identical rigs.  If you use naming strings instead of GPU#00 etc then those rigs with the different naming convention for the device will fail and have to re-benchmark.  The #1931 binary naming is a great idea though.

**Comment by UselessGuru** [comment]
>I'd leave the GPU#00 etc... because in my rigs I have many GTX1070's all from MSI but some are >identified differently (I assume they changed name slightly in BIOS) 
> If you use naming strings instead of GPU#00

The model type should be the same for all cards of the same model, even across manufacturers.

My code uses the naming like this:
Please check http://localhost:3999/devices -> for each listed device look for 'Model' and then convert it to the short name wich this code:

`Model_Norm = [String]$Device_OpenCL.Name -replace "[^A-Z0-9]" -replace "GeForce",""`

So 'GeForce GTX 1080 Ti' will become 'GTX1080Ti'.

In case of problems you could always the code in Include.psm1 (just 3 lines) :-)

**Comment by Byrd1083** [comment]
Here is even a more structured way that I have been working on with RainbowMiner.

Since, I've been benching and testing, I find myself in the stat folder a lot deleting bad benches to trigger a rebench. It would be an improvement to have these following 

stat sub folders:
- pools
- benchpass
    - cpu
    - nvidia
    - amd
- benchfail
    - cpu
    - nvidia 
    - amd

It would be great to have this folder structure for all pass/fail benchmarks so I do not delete a good bench on accident with them all crammed into one or get it confused with naming conventions. Plus would give a better understanding as to which miners need to be excluded or parameters adjusted.

**Comment by UselessGuru** [comment]
@Byrd1083 

Thank you for your suggestions. Feel fee to create a PR with the proposed changes.

**Comment by Byrd1083** [comment]
I wish I new java, always been a front end developer. I'm only worth my opinion. Wouldn't want to break things. It would be my guinea pig to slaughter 😈

**Comment by UselessGuru** [comment]
MPM is written in Powershell, no coffee cup software allowed here ;-)
