### ISSUE TITLE
almost all pool API's are failing according to MPM

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#2159]
I normally use Zergpool, Hashrefinery, and Miningpoolnub.  Yesterday they all started failing.  This happened once before and I set the interval longer and they worked again.  It appears they getting blocked maybe by Cloudflare, but they work fine when I just test the API in the browser.  I don't normally use ahashpool anymore, but currently it is the only one that the api is not failing.  Has anyone else had this problem and a solution?

**Comment by robl45** [comment]
Any ideas,  as of this morning.  zpool, hashrefinery, zergpool and miningpoolhub are all failing API's. Only one working is Ahashpool.

**Comment by robl45** [comment]
I set interval to 2 hours last night and still all are failing.

**Comment by UselessGuru** [comment]
No problems here at all.

**Comment by robl45** [comment]
I reset my router and cable modem, its working now.  Its happened before as well.  the multipoolminer site was getting blocked in the script too.  I believe  it has to do with the interval.  I've set it for 2 minutes instead of 1 minute.

**Comment by UselessGuru** [comment]
> since switching to the latest master.. ?

Nothing has change regarding the way the pools are getting polled.
