### ISSUE TITLE
MiningPoolHub - EWBF - Equihash 144,5 - wrong variable for pool passed

### ISSUE THREAD

**Issue by nimbosa** [MultiPoolMiner/MultiPoolMiner#2169]
Equiahash pool = `asia.equihash.equihash-hub.miningpoolhub.com:20595`

which is obviously wrong (duplicated .equihash, MUST remove `.equihash` after location),

should be: `asia.equihash-hub.miningpoolhub.com:20595`

I don't know when this bug was introduced and in what file exactly (variables get passed around wildly),  but I last updated my MPM 2018-09-09 (on the latest `master`), and before that it was last known working with EWBF 144,5 on Aug 10, 2018. Something changed between those dates that broke this.

```
+-------------------------------------------------+
|         EWBF's Eqihash CUDA miner. v0.5         |
+-------------------------------------------------+
15:29:35 INFO: Configured pools: 1
15:29:35 INFO: Selected pool: asia.equihash.equihash-hub.miningpoolhub.com:20595
15:29:35 INFO: Algorithm: 144_5 "BgoldPoW"
15:29:35 INFO: Devices: User defined.
15:29:35 INFO: Temperature limit: 90
15:29:35 INFO: Api: Listen on 127.0.0.1:4002
```

**Comment by UselessGuru** [comment]
@nimbosa: Thank you!

Problem was introduced with https://github.com/MultiPoolMiner/MultiPoolMiner/commit/8050815d25681f7bf5bf753b978a555144c600fd#diff-7e2af4d33b09268546779e173011567a

Fix available here:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2170
