### ISSUE TITLE
powershell trying to update stops mpm

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#2171]
So problem before was it was trying to update to older version. now it is trying to update to current version and pops up a window that stops the miner.  Using the somewhat latest master that was supposed to fix this issue.

**Comment by UselessGuru** [comment]
Jut edit your start file and remove the line that is updating PWSH.

There is NO code in MultiPoolMiner.ps1 that does any updates anymore.
