### ISSUE TITLE
Pause... Press any key to continue...

### ISSUE THREAD

**Issue by azianboi94** [MultiPoolMiner/MultiPoolMiner#2172]
has anybody had this problem before? I've downloaded the master branch of MultiPoolMiner and just changed the Start.bat file. Any help would be appreciated. Thanks!

https://imgur.com/rIFEyAJ

**Comment by azianboi94** [comment]
everytime I click Start.bat, nothing will mine or benchmark. It will just go to the screen where it says Pause.. Press any key to continue...

Here are my logs
[MultiPoolMiner_2018-09-12.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2381600/MultiPoolMiner_2018-09-12.txt)
[MultiPoolMiner_2018-09-12_02-24-40.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2381601/MultiPoolMiner_2018-09-12_02-24-40.txt)
[MultiPoolMiner_2018-09-12_02-24-54.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2381602/MultiPoolMiner_2018-09-12_02-24-54.txt)
[MultiPoolMiner_2018-09-13.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2381603/MultiPoolMiner_2018-09-13.txt)
[MultiPoolMiner_2018-09-13_21-03-02.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2381604/MultiPoolMiner_2018-09-13_21-03-02.txt)
[MultiPoolMiner_2018-09-13_21-03-23.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2381605/MultiPoolMiner_2018-09-13_21-03-23.txt)

**Comment by azianboi94** [comment]
I screen recorded to show you problem in more detail. let me know if you need anything else!

https://drive.google.com/file/d/18jWZqMTzCNzvQvK2pJUSrB5g-iKYH6mV/view?usp=sharing

**Comment by UselessGuru** [comment]
Very odd... this is definitely something new :-(
One thing that bothers me is that it wants to install PWSH new on each run...???

Try to install PWSH 6.0.4 manually, and ensure that $path includes the PWSH binary location. Do not forget to reboot!

Then try running each of the lines in start.bat one by one in a cmd window. Will you see any errors?
