### ISSUE TITLE
T-Rex/Watchdog

### ISSUE THREAD

**Issue by Dewbs** [MultiPoolMiner/MultiPoolMiner#2175]
I'm getting continuous watchdog timers on X16R & X17 with T-Rex.
How to disable watchdog? I don't have -watchdog in start & "watchdog": "False" in config.
T-Rex X16R timer is currently 1445 seconds ?

**Comment by Dewbs** [comment]
![image](https://user-images.githubusercontent.com/38868187/45586070-2a83bc00-b8e8-11e8-9da5-631ecf075571.png)

**Comment by UselessGuru** [comment]
> How to disable watchdog?

Either
- remove '-Watchdog' from start batch file
or
- add '"Watchdog": false' to the config file

**Comment by Dewbs** [comment]
um in my post I stated I don't have -watchdog in my start.bat and watchdog is set to false in config.
I also tries leaving "watchdog": "$watchdog" in config still without -watchdog in start.bat and it still runs watchdog

**Comment by Dewbs** [comment]
[MultiPoolMiner.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2386127/MultiPoolMiner.zip)

**Comment by UselessGuru** [comment]
Dewbs:

Please explicitly '"Watchdog": false' to the config file and report back.

**Comment by Dewbs** [comment]
Yes that's worked, thanks

**Comment by UselessGuru** [comment]
> Yes that's worked, thanks

@Dewbs 
Thank you - we've detected a bug.... 

@paulpoco 
Can you create a PR with the following change:
MultiPoolminer.ps1 line 629

From
            if ($Config.Watchdog -and $_.Profit -ne $null) {
to
             if ($Config.Watchdog -eq true -and $_.Profit -ne $null) {

TIA!

@Dewbs 
Can you please see if this change would fix your issue if you remove all watchdog settings from start bat and config file - TIA (I am currently away and do not have access to a test rig)

**Comment by grantemsley** [comment]
@uselessguru i think that true either needs a dollar sign in front or quotes around it, depending on what youre trying to do

**Comment by UselessGuru** [comment]
@grantemsley 
A possible cause is that all switch variable are not true or false, but rather ispresent... However in the config file as well as in the Code we expect a true or false

**Comment by UselessGuru** [comment]
Fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2187

**Comment by Dewbs** [comment]
Un-fixed in 3.0.1 possibly?

If I use '"Watchdog": "false"' then watchdog runs.

If I use '"Watchdog": false' as before I receive : 

ConvertFrom-Json : Conversion from JSON failed with error: Unexpected character encountered while parsing value: F. Path 'Watchdog', line 85, position 14.
At C:\MPM\MultiPoolMiner.ps1:127 char:41
+     $Config = Get-Content $ConfigFile | ConvertFrom-Json
+                                         ~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
