### ISSUE TITLE
MultiPoolMiner CMD gives warning about CUDA 9.2 not being updated

### ISSUE THREAD

**Issue by caniko2** [MultiPoolMiner/MultiPoolMiner#2176]
I get the following message in cmd message:
`
Requires CUDA version 9.2.00 or above (installed version is 10.0.150). Please update your Nvidia drivers.
`

CUDA 9.2 and 9.0 has their own env variable; I may therefore be wrong on the source of the warning. What do you think? Is it really a driver issue, or is it MPM?

**Comment by caniko2** [comment]
I have tested without CUDA 9.0 being installed, and the problem percists. I have also applied the patch update to CUDA 9.2, this had no effect on the situation.

**Comment by jakubsuchybio** [comment]
Exactly the same issue.
I have installed latest NVIDIA drivers. I also have installed CUDA (from README)
and I too get:
```
WARNING: Miner (CcminerKlaust) requires CUDA version 9.2.00 or above (installed version is 10.0.150). Please update your Nvidia drivers.
WARNING: Miner (CcminerPigeonCoin) requires CUDA version 9.2.00 or above (installed version is 10.0.150). Please update your Nvidia drivers.
WARNING: Miner (CcminerZealot) requires CUDA version 9.2.00 or above (installed version is 10.0.150). Please update your Nvidia drivers.
```

**Comment by UselessGuru** [comment]
I'll have a look at this issue next week (I am currently away from home)

**Comment by RANGERBEE** [comment]
if this was part of the latest build - Zip download, then the error persists.  I just downloaded latest build zip five minutes ago.    Same stdOut as @jakubsuchybio above..

**Comment by caniko2** [comment]
Still not working

**Comment by ChromaticProductions** [comment]
@UselessGuru  It appeared that #2185 (ccminerpigeoncoin) change wasn’t picked up in mpm v3.0.1, but the other two updates were?

**Comment by erikszewczyk** [comment]
I think there might be an issue with the way PowerShell is evaluating the versions
```
>$DriverVersion = "10.0.132"
>$RequiredVersion = "9.2.00"
>if ($DriverVersion -lt $RequiredVersion) { Write-Host "less than required" }
>less than required
```
My workaround for the moment was to set $RequiredVersion to 10.0.0

**Comment by erikszewczyk** [comment]
> @UselessGuru It appeared that #2185 (ccminerpigeoncoin) change wasn’t picked up in mpm v3.0.1, but the other two updates were?

Yeah, looks like this one wasnt included, I had to make this change manually

**Comment by UselessGuru** [comment]
@UselessGuru It appeared that #2185 (ccminerpigeoncoin) change wasn’t picked up in mpm v3.0.1, 

It's all in there now.... I don't know how to deal with Github Desktop sometimes.. :-(
