### ISSUE TITLE
Is the MPM monitor server down?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2177]
Is the MPM monitor server down?

My Miners are working fine.

![screenshot_20180920-061746_chrome](https://user-images.githubusercontent.com/801414/45821195-73978f80-bc9d-11e8-8b12-ec252fc07460.jpg)
![screenshot_20180920-061712_teamviewer](https://user-images.githubusercontent.com/801414/45821248-8e6a0400-bc9d-11e8-922f-5d44aa78eb14.jpg)

**Comment by grantemsley** [comment]
They seem to be working fine for me. Is that miner running really slowly and only doing the main loop once every 12 minutes or something?

**Comment by paulpoco** [comment]
Working now.
