### ISSUE TITLE
Per-device miners: per-device options?

### ISSUE THREAD

**Issue by Dewbs** [MultiPoolMiner/MultiPoolMiner#2178]
Any thoughts on setting, for example, intensity, per device, per miner?
device 0 use i 19
device 1 use i 20
or
workername with device number included

..that kind of thing

**Comment by UselessGuru** [comment]
This currently is not supported, It requires extra parsing of the algo parameters which is not currently implemented.
I'll see what I can do - but this will have to wait a few weeks.

**Comment by Dewbs** [comment]
Ok, thanks for taking a look!

**Comment by UselessGuru** [comment]
@Dewbs 
If you're experimantal you can look at my implementation for this in my (for now abandoned) fork here:
https://github.com/UselessGuru/MultiPoolMiner. 
I created a function called Get-CommandPerDevice in Include.psm1. I'll see how I can add it to the regular MPM - or maybe I'll port MPM to my fork. Time will tell.

**Comment by Dewbs** [comment]
This is actually more serious than I had first appreciated.
Because I use a 1060/1070Ti/10870Ti combo there is a spread of 'ability'.
MPM returns 'healthy' hashrates for all cards particularly on T-Rex miner.
Pool side this is very different.
1080 is something like, 1070Ti not so good and the 1060 is hardly getting any submitted shares.
Partially to do maybe with fixed intensity of T-Rex , but also forced to use same starting diff. with MPM currently.

**Comment by Dewbs** [comment]
Only noticed this mainly because for a while the miner windows have been hidden and I've only just started to show them again to work out why BCD was so bad on Zergpool (for me)

**Comment by Dewbs** [comment]
![image](https://user-images.githubusercontent.com/38868187/45907499-01838f80-bdf0-11e8-9d20-50a44e97229c.png)

**Comment by UselessGuru** [comment]
@Dewbs 

Get-CommandPerDevice is now already in Include.psm1 with 3.0.1. :-)
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/MultiPoolMiner_3.0.1/Include.psm1

**Comment by UselessGuru** [comment]
I'll add Get-CommandPerDevice to all miners in 3.0.2.
