### ISSUE TITLE
MPM always stopping

### ISSUE THREAD

**Issue by randycool279** [MultiPoolMiner/MultiPoolMiner#2182]
Hi,
  I’ve been having this issue with MPM where it starts to mine but few hours later, it completely stops mining. I can verify this because the gpu clocks are all at 100mhz after this happens. So I am forced to always check on my miner every 7-8 hours. Is there any fix for this?

**Comment by grantemsley** [comment]
We just launch the miner programs and they do their thing.  Are the miners running?  Look in task manager for them.

Issues like this almost always turn out to be hardware or driver issues.

Some things to try:

- check the logs if there is a specific miner that is always running when the issue happens. If so, disable that one.
- update drivers
- increase virtual memory size
- make sure PSU is sufficient
- check event viewer for errors about graphics driver resets or freezes. If those are there your cards are unstable
- undo any overclocking
- check for thermal throttling cards, make sure all fans working

**Comment by randycool279** [comment]
My virtual memory size is 20gbs right now. I believe my PSU is more than sufficient, its a 1200w psu on 5 gtx1060’s. The cards are never throttling because I run them at 75% fan speed and they will still be running when the miner stops. Though, I’ve never actually installed the gpu drivers. Windows just automatically recognized them and I just started mining. I’ll try to install some drivers tonight!

Thanks

**Comment by grantemsley** [comment]
Sounds like you have most of it covered.  So GPU drivers, event viewer logs (look for ones under System where the source is either Display or nvlddmkm), and check that the miner programs are actually running.

One more thing you can do to make it easier to diagnose:  Set -ShowMinerWindow in your .bat file or config file to true.  That'll make the miner windows pop up when they are launched, so you can see that they are running, and look at them for any errors.
