### ISSUE TITLE
Excavator Error

### ISSUE THREAD

**Issue by randycool279** [MultiPoolMiner/MultiPoolMiner#2183]
Hey,
   I just updated to the new version of MPH and I extracted excavator in the bin/excavator folder.  At the moment, it keeps saying “ Starting Miner (Excavator-2-GPU#01...) and so forth. Then it returns “Error returned by miner (Excavator-2-GPU#01...). I’m not sure if this is a problem but Right now I believe it is benchmarking. I will keep this thread updated if something does go wrong.

**Comment by grantemsley** [comment]
Make sure you are using excavator 1.4.4 - that's the last version that supports pools other than nicehash.

I think it should actually get downloaded automatically if you just leave the folder empty.
