### ISSUE TITLE
New Version not mining all algos

### ISSUE THREAD

**Issue by randycool279** [MultiPoolMiner/MultiPoolMiner#2184]
I recently updated to the new version of MPM. It’s been benchmarking only Equihash, Skein, Lyra2Z, and Lyra2Rev2. I want it to also benchmark ethereum but it is not. I have “ethash2g” as one of the algos listed in the start batch file. Any fix for this? Also, I wanted ti let people know that I am also getting the “ ccminer klaust... cuda error, please update your nvidia drivers”

**Comment by UselessGuru** [comment]
Please check your active configuration closely:

- do have a pool enabled that actually allows you to mine ethash?
- do you have an ethash miner, e.g Claymore or PhoenixMiner enabled?

As a temporary workaround you can start MPM without specifying -MinerName, -ExcludeMinerName, -ExcludePoolName or -PoolName (also make sure these are not defined in the config file) and it will mine all available algorithms at all available pools.

**Comment by UselessGuru** [comment]
If you do not specify the algoes it will use all availables.
But you should be able to specify ethash2gb and ethash3gb like any other algo.

> Do you think it will work fine?
What makes you think it will not work fine?
Feel free to post screen shots, config files or logs and I'll have a look.

**Comment by UselessGuru** [comment]
The download has been updated - maybe that was the problem.
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2189/commits/3a155b7eccf51db0f2dadd4d6b0541f6e7348b4a

For best results try the latest 3.0.1 master:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2189
