### ISSUE TITLE
30.1 red lines - Missing an argument for parameter 'MinerStatusUrl'

### ISSUE THREAD

**Issue by skovesh** [MultiPoolMiner/MultiPoolMiner#2190]
with version 3.01 getting:
Missing an argument for parameter 'MinerStatusUrl'. Specify a parameter of type 'System.String' and try again.

**Comment by UselessGuru** [comment]
@skovesh 

Nothing has changed in that respect with 3.0.1.

Could you please provide logs, config file amd start file. MAybe I can see what's wrong in your case. Thank you!

**Comment by skovesh** [comment]
sure, here are all. still seethe red lines, but after all pull requests, at least it doesn't stop!
[MultiPoolMiner_2018-10-07.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2454139/MultiPoolMiner_2018-10-07.txt)
[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2454140/Config.txt)
[Start-MiningPoolHub.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2454141/Start-MiningPoolHub.zip)
Thanks a lot !

**Comment by skovesh** [comment]
OK, fault was in NVIDIA-EWBF2Equihash.ps1 .
Once replaced with last version, all fine.
