### ISSUE TITLE
Excavator v1.5.x wrong number of arguments error

### ISSUE THREAD

**Issue by ChromaticProductions** [MultiPoolMiner/MultiPoolMiner#2191]
Receiving the following error with mpm v3.0x using any variation of 1.5.x excavator including 1.5.12a.  Running Nvidia 1080TI using 416.16 WQHL drivers and Powershell v6.1.  Excavator v1.4.4a works without issue.  

Write-Log : Error returned by miner (Excavator-1-GPU#00-GPU#01): Wrong number of arguments
At C:\MPM3\APIs\Excavator.ps1:101 char:33
+ ...             Write-Log -Level Error  "Error returned by miner ($($this ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

Write-Log : Failed to connect to miner (Excavator-1-GPU#00-GPU#01).
At C:\MPM3\APIs\Excavator.ps1:178 char:25
+ ...             Write-Log -Level Error  "Failed to connect to miner ($($t ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

Appreciate the support.

**Comment by Dewbs** [comment]
Ver > v1.4.4a does not support any other pools than NiceHash.
Please see NHMP verision included with V3.0.1 #2189

**Comment by Dewbs** [comment]
@UselessGuru yes that's why I was pointing the OP to the NHMP version

**Comment by ChromaticProductions** [comment]
@Dewbs Thank you for the quick response, I see that excavator v1.5.12a support is now included in MPM v3.0.1.

@UselessGuru Thank you, I see the three files you mention as a set already included in MPM v3.0.1.
