### ISSUE TITLE
Suggestion when renaming miners

### ISSUE THREAD

**Issue by Dewbs** [MultiPoolMiner/MultiPoolMiner#2199]
Would it be possible to include a process to rename benchmark files according to old>new miner names, particularly if the miner binary is unchanged?
i.e. if exist oldminername-GPU#00_Lyra2z_HashRate.txt then rename to newminername-GPU#00_Lyra2z_HashRate.txt
Would just save on some re-benching time.

**Comment by UselessGuru** [comment]
Not automatically - I don't have the time for all this.
I recommand TotalCommander. Its Multi-Rename tool is great for such a one time change.
Ideally you would also move to the new naming format that the new optional '-UseDeviceModelBenchmarkFileNaming' will bring. the new Stats naming format will allow for added HW of a different card model without having to benchmark / rename.
E.g. CcminerNevermore-GPU#00_Lyra2z_HashRate.txt -> NVIDIA-CcminerNevermore-1xGtx1080ti_Lyra2z_HashRate.txt

**Comment by grantemsley** [comment]
@UselessGuru putting the version in the miner name would accomplish this fairly easily, if we wanted to do that.

**Comment by UselessGuru** [comment]
@grantemsley 

> putting the version in the miner name would accomplish this fairly easily

I don't understand. Accomplish what?

**Comment by grantemsley** [comment]
Instead of naming the miner ccminernevermore, name it ccminernevermore402 or whatever the current version is, using 4.0.2 as an example.  Rename the PS1 file and set the folder in bin to be ccminernevermore402 as well.

Then when a new one comes out use ccminernevermore403 and it will appear as a new miner, download automatically, and create new stats.

**Comment by UselessGuru** [comment]
@Dewbs 

Would adding the version number to the miner file as suggested by grantemsley make sense?

**Comment by UselessGuru** [comment]
In the final 3.1.0 I'll add the version number to the miner file as usggested by Grantemsley.
The version number will be noted like

AMD_NVIDIA-PhoenixminerEthash__v3.5d_

**Comment by mkirov0** [comment]
I like it! It will save me the time to go hunt down and delete any old stat files that are left over from the previous version. Renaming will also will be a good reason to visit and update the miner file with any algos that may have been added with the latest version.

**Comment by UselessGuru** [comment]
Implemented in 3.1.0 Beta 2
