### ISSUE TITLE
errors for all miners

### ISSUE THREAD

**Issue by skovesh** [MultiPoolMiner/MultiPoolMiner#2202]
Get-CommandPerDevice : The term 'Get-CommandPerDevice' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At F:\MINE\MultiPoolMiner\MinersLegacy\CPU-XmrigCryptonight.ps1:56 char:23
+             $Params = Get-CommandPerDevice $Params $Miner_Device.Type ...

**Comment by UselessGuru** [comment]
@skovesh 

You need an updated Include.psm1.
What did you do that the problem started? What version Are you running?

**Comment by skovesh** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Using last beta version from 3.10 beta 2.Thanks!                                                                                                                                                                        Inviato tramite BlackBerry Hub per Android                                                                                                                                                                           Da: notifications@github.comInviato: 18 ottobre 2018 08:05A: MultiPoolMiner@noreply.github.comRispondi a: reply@reply.github.comCc: marcello.segal@gmail.com; mention@noreply.github.comOggetto: Re: [MultiPoolMiner/MultiPoolMiner] errors for all miners (#2202)  @skovesh
You need an updated Include.psm1.
What did you do that the problem started? What version Are you running?

**Comment by UselessGuru** [comment]
> Using last beta version from 3.10 beta 2

There is no beta 2.
When using the Beata version please install it into a new directory.

**Comment by UselessGuru** [comment]
There is now Beta 3:
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/3.1.0/MultiPoolMiner_3.1.0_Beta_3.zip

If the error persists please report here:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2203
