### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by aarona907** [MultiPoolMiner/MultiPoolMiner#2206]
I get the Blockmasters has failed error.  In the logs it says 503 service temporarily unavailable.  If I run the code manually from Power Shell, or from a browser it returns the results from Blockmasters just fine.  I know this is something wrong with my environment because the code has not changed.  I get the same error on the old version and both beta versions of MPM.  I've been having this issue on and off for a while, now it seems to be permanent.  Any ideas?

**Comment by paulpoco** [comment]
I cannot get Blockmasters to work either

**Comment by mkirov0** [comment]
Lets hope its a server side upgrade 😃 I have been having issues with their API for a few days now.

**Comment by UselessGuru** [comment]
> I put a 10s delay between the blockmasters and blockmastercoins requests and that seemed to solve it. 

With Beta 5 there will be an improved pool API polling routine that should reduce all the 'Pool is not responding' messages.

**Comment by Dewbs** [comment]
Since updating to 3.1 it has been unable to get any info from blockmasters via api

**Comment by Dewbs** [comment]
I have contacted Blockmasters discord - they say they may loosen the restrictions on api calls

**Comment by aarona907** [comment]
Since modifying the code mine has been working fine.  In the BlockMasters.ps1 file, in between lines 16 and 17, put start-sleep 10.

**Comment by Dewbs** [comment]
Ok thank you I will try. I have contact with BMDev at the moment so he has my connection details and will check. If no joy then I will try your mod.

**Comment by Majorbafe** [comment]
Yep.... the "start-sleep 10" works. I wonder if this 10 second delay is cpu cycle based, i.e., is it leaving the cpu available for mining? 
I'd prefer for MPM to have its calculations done loosely over time and not in a batch... It takes over one of the threads completely.
Any thoughts on this?

**Comment by Dewbs** [comment]
Well I have started to receive data without the mod so I guess they may have relaxed the restrictions

**Comment by UselessGuru** [comment]
> Since updating to 3.1 it has been unable to get any info from blockmasters via api

There are no changes up to 3.1.0 Beta 4 in that respect. So the problem must be on the pool side.

**Comment by aarona907** [comment]
Must be pool side.  I get the same response from the api with Beta 5, even with the 10 second delay between calls.
