### ISSUE TITLE
ethash equihash gone missing

### ISSUE THREAD

**Issue by cblim** [MultiPoolMiner/MultiPoolMiner#2209]
hi,

i'm testing the beta 7a. and while i'm doing the benchmarking, it was all fine, i get good results etc etc etc...
i was only benchmarking a few algo. mainly ethash, equihash, cryptonight,.

started fine. but towards the end of the benchmark, my results for ethash and equihash GONE MISSING.
i only left with cryptonight.

**Comment by Dewbs** [comment]
Maybe benched as zero?
Check on http://localhost:3999/minerstats.html and reset 0H/s
Do they re-bench?

**Comment by gs1960** [comment]
This also happens to me with version 8a.
During the benchmark there are, but then they disappear.

**Comment by UselessGuru** [comment]
Please try Beta 11 and report in this thread if still happens:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2236
