### ISSUE TITLE
What is "Import Torrent Library" for?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2210]
What is "Import Torrent Library" for?

**Comment by UselessGuru** [comment]
Good point, I would like to know too.

**Comment by mkirov0** [comment]
Maybe future support for Tron? 😛

**Comment by paulpoco** [comment]
Maybe it was supposed to go here?
https://github.com/mono/monotorrent/graphs/contributors

**Comment by paulpoco** [comment]
@aaronsace is the Torrent stuff a future way to keep MPM up to date?

**Comment by paulpoco** [comment]
What is "Import Torrent Library" for?

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2212#issuecomment-435366956
