### ISSUE TITLE
"Import Torrent Library" breaks Downloader

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2212]
As per title

**Comment by aaronsace** [comment]
What do you mean? How are they related?

**Comment by paulpoco** [comment]
How can I now trust MPM with a "MonoTorrent.Client" that no one knows what it is for?

Will it hijack my internet connection to spread torrents?

**Comment by aaronsace** [comment]
@paulpoco Nothing is implemented.

**Comment by aaronsace** [comment]
@UselessGuru I don't understand as to why but "-ErrorAction Stop" is not working on PowerShell 5 but does work on PowerShell 6 so I will swap the try/catch around.

**Comment by aaronsace** [comment]
@UselessGuru Support for Magnet URLs is coming with Webseed support.

**Comment by paulpoco** [comment]
What is "MonoTorrent.Client" for?

**Comment by UselessGuru** [comment]
Fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/blob/2e3aeea554ca259bba7730338a6ceb08afb52b3a/Include.psm1
