### ISSUE TITLE
Request: Add https://www.ravenminer.com and https://eu.ravenminer.com , Ravencoin(RVN) Pools

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2226]
I have created pool, balance, and Readme files borrowing from @rainbowminer 's earlier ps1 files:

#2216 
#2217 
#2218 
#2219 
#2220 
#2221 

You need to add a Ravencoin(RVN) wallet address in the config.txt under Pools.  And add Ravenminer or RavenminerEu to your start.bat but not both.  The 2 different Pools are not connected and if you do both Pools they will build a balance separately.
![screenshot_20181107-065152_chrome](https://user-images.githubusercontent.com/801414/48138701-b87d8280-e259-11e8-87fd-63c6b5a4e9d3.jpg)

**Comment by skovesh** [comment]
[MultiPoolMiner_2018-11-06_08-07-47.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2558211/MultiPoolMiner_2018-11-06_08-07-47.zip)
Have all update files in the right directories and still get:
The property 'Price' cannot be found on this object. Verify that the property exists and can be set.
At F:\MINE\MultiPoolMiner-BETA\MultiPoolMiner.ps1:375 char:56
+ ...        $_.Price = [Double]($_.Price * $Config.Pools.$($_.Name).PriceP ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : PropertyAssignmentException

The property 'StablePrice' cannot be found on this object. Verify that the property exists and can be set.
At F:\MINE\MultiPoolMiner-BETA\MultiPoolMiner.ps1:376 char:68
+ ... ablePrice = [Double]($_.StablePrice * $Config.Pools.$($_.Name).PriceP ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : PropertyAssignmentException

**Comment by paulpoco** [comment]
@skovesh not sure how to help you right now?  Which one are you using?
Raveminer or RavenminerEu?

Myself I have the "Ravenminer " running fine for days now.  I only briefly tested the "RavenminerEu" one just quickly to see if it worked.

Maybe the stays query is failing?

**Comment by paulpoco** [comment]
> @skovesh not sure how to help you right now? Which one are you using?
> Raveminer or RavenminerEu?
> 
> Myself I have the "Ravenminer " running fine for days now. I only briefly tested the "RavenminerEu" one just quickly to see if it worked.
> 
> Maybe the status query is failing?
> 
> I noticed for the last day or so Nicehash paid more than "Ravenminer Pool", so it hasn't run lately.

I tried both again and have no issue.

**Comment by skovesh** [comment]
Just one question: all 4 files have to end with ps1 or txt ? in both POOLS and BALANCES directories? Tried both versions, Ravenminer and RavenminerEU separatly....

**Comment by UselessGuru** [comment]
These are all *.ps1 files.

**Comment by paulpoco** [comment]
Sorry about that.

**Comment by UselessGuru** [comment]
Both pools will bei in 3.2.0 Beta 1:

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/Beta3.2.0
