### ISSUE TITLE
3.0.1 hashing 470s and 480s separately on the same pool at only half the hash rate.

### ISSUE THREAD

**Issue by aaronsta1** [MultiPoolMiner/MultiPoolMiner#2227]
i have 2 480s and 3 470s in the same rig.
some reason they are separated and the 480s arent being counted.

worker monitor shows this
`ClaymoreEthash-GPU#00-GPU#02-GPU#03		MiningPoolHubCoins	.\Bin\AMD_NVIDIA-Claymore-Ethash\EthDcrMiner64.exe	00 Days 18 Hours 37 Minutes	Ethash	72.79 MH/s	72.24 MH/s		0.00020140
ClaymoreEthash-GPU#01-GPU#04		MiningPoolHubCoins	.\Bin\AMD_NVIDIA-Claymore-Ethash\EthDcrMiner64.exe	00 Days 18 Hours 29 Minutes	Ethash	43.86 MH/s	43.69 MH/s		0.00012181`

and the log shows this
`ETH - Total Speed: 72.455 Mh/s, Total Shares: 791, Rejected: 0, Time: 13:16
ETH: GPU0 24.477 Mh/s, GPU1 24.855 Mh/s, GPU2 23.123 Mh/s
GPU0 t=65C fan=60%, GPU1 t=59C fan=50%, GPU2 t=50C fan=66%
ETH: 11/07/18-19:07:56 - New job from us-east.ethash-hub.miningpoolhub.com:20535`

the the pool only shows the hash for the 470s. the 480s arent mining, perhaps because they have the same worker name?

**Comment by UselessGuru** [comment]
@aaronsta1 

Please post the output of http://localhost:3999/config (when MPM is running.
You seem to have a rether complex HW config ;-) I cannot test this my self but I'll see what I can do.

**Comment by aaronsta1** [comment]
its not that complicated, i have 2 rx 480s, and 3 rx 470s.. all amd.
the start.bat is unedited except my username and bitcoin address. i also took out nicehash and added -disabledualmining

just some reason its seeing the 2 cards separate.
` Device: {GPU#00, GPU#02, GPU#03}

Miner[Fee]                                                Algorithm      Speed    BTC/Day Accuracy BTC/GH/Day Pool[Fee]
----------                                                ---------      -----    ------- -------- ---------- ---------
ClaymoreEthash-GPU#00-GPU#02-GPU#03[1.00%]                Ethash    72.21 MH/s 0.00020220      98% 0.00280002 MiningPoolHubCoins-Ethereum[0.00%]
ClaymoreEthash-3gb-GPU#00-GPU#02-GPU#03[1.00%]            Ethash3gb 72.67 MH/s 0.00016036      98% 0.00220663 MiningPoolHubCoins-Musicoin[0.00%]
AMD_NVIDIA-PhoenixminerEthash-GPU#00-GPU#02-GPU#03[0.65%] Ethash    50.68 MH/s 0.00014191      98% 0.00280002 MiningPoolHubCoins-Ethereum[0.00%]
ClaymoreEthash-2gb-GPU#00-GPU#02-GPU#03[1.00%]            Ethash2gb 72.72 MH/s 0.00013770      97% 0.00189352 MiningPoolHubCoins-Expanse[0.00%]
AMD_NVIDIA-PhoenixminerEthash-GPU#00-GPU#02-GPU#03[0.65%] Ethash3gb 50.68 MH/s 0.00011183      98% 0.00220663 MiningPoolHubCoins-Musicoin[0.00%]
AMD_NVIDIA-PhoenixminerEthash-GPU#00-GPU#02-GPU#03[0.65%] Ethash2gb 50.72 MH/s 0.00009604      97% 0.00189352 MiningPoolHubCoins-Expanse[0.00%]


   Device: {GPU#01, GPU#04}

Miner[Fee]                                         Algorithm      Speed    BTC/Day Accuracy BTC/GH/Day Pool[Fee]
----------                                         ---------      -----    ------- -------- ---------- ---------
ClaymoreEthash-GPU#01-GPU#04[1.00%]                Ethash    43.68 MH/s 0.00012229      98% 0.00280002 MiningPoolHubCoins-Ethereum[0.00%]
ClaymoreEthash-3gb-GPU#01-GPU#04[1.00%]            Ethash3gb 43.88 MH/s 0.00009682      98% 0.00220663 MiningPoolHubCoins-Musicoin[0.00%]
AMD_NVIDIA-PhoenixminerEthash-GPU#01-GPU#04[0.65%] Ethash    30.69 MH/s 0.00008592      98% 0.00280002 MiningPoolHubCoins-Ethereum[0.00%]
ClaymoreEthash-2gb-GPU#01-GPU#04[1.00%]            Ethash2gb 43.89 MH/s 0.00008311      97% 0.00189352 MiningPoolHubCoins-Expanse[0.00%]
AMD_NVIDIA-PhoenixminerEthash-GPU#01-GPU#04[0.65%] Ethash3gb 30.70 MH/s 0.00006775      98% 0.00220663 MiningPoolHubCoins-Musicoin[0.00%]
AMD_NVIDIA-PhoenixminerEthash-GPU#01-GPU#04[0.65%] Ethash2gb 35.12 MH/s 0.00006649      97% 0.00189352 MiningPoolHubCoins-Expanse[0.00%]
`

**Comment by aaronsta1** [comment]
here is the config altho i dont see anything wrong with it.
`{
  "Algorithm": [
    "Blake2s",
    "CryptonightV7",
    "CryptonightHeavy",
    "Decrednicehash",
    "Ethash",
    "Ethash2gb",
    "Ethash3gb",
    "Equihash",
    "Keccak",
    "Lbry",
    "Lyra2RE2",
    "Lyra2z",
    "m7m",
    "Neoscrypt",
    "Pascal",
    "Sib",
    "Skein",
    "Skunk",
    "X16R"
  ],
  "API_ID": 0,
  "API_Key": "",
  "CreateMinerInstancePerDeviceModel": false,
  "Currency": [
    "BTC",
    "USD"
  ],
  "Delay": 0,
  "DeviceName": "amd",
  "DisableDualMining": true,
  "Donate": 10,
  "ExcludeAlgorithm": null,
  "ExcludeDeviceName": null,
  "ExcludeMinerName": null,
  "ExcludePoolName": null,
  "IgnoreCosts": false,
  "Interval": 60,
  "MinerName": null,
  "MinerStatusKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "MinerStatusUrl": "https://multipoolminer.io/monitor/miner.php",
  "PoolName": [
    "miningpoolhubcoins",
    "zpool"
  ],
  "Proxy": "",
  "Region": "US",
  "ShowMinerWindow": false,
  "ShowPoolBalances": false,
  "ShowPoolBalancesDetails": false,
  "ShowPoolBalancesExcludedPools": false,
  "SSL": true,
  "SwitchingPrevention": 2.0,
  "UseFastestMinerPerAlgoOnly": false,
  "UserName": "username",
  "Wallet": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
  "Watchdog": true,
  "WorkerName": "multipoolminer",
  "Pools": {
    "AHashPool": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "BlazePool": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "BlockMasters": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "Hashrefinery": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "MiningPoolHub": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "MiningPoolHubCoins": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "NiceHash": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "YiiMP": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "ZergPool": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    },
    "Zpool": {
      "BTC": "BTCXXXXXXXXXXXXXXXXXXXXXXXX",
      "User": "username",
      "Worker": "multipoolminer",
      "API_ID": 0,
      "API_Key": ""
    }
  },
  "Miners": {},
  "VersionCompatibility": "3.0.0"
}`

**Comment by aaronsta1** [comment]
hmm, it seems it could be this

-CreateMinerInstancePerDeviceModel
    Newer miner files can create separate instances for each card model. This increases profit. Not all miners currently support this feature (more coming). 
    By default this feature is turned off. To enable add '-CreateMinerInstancePerDeviceModel' to your start batch file.
    Note that this will trigger some benchmarking.

altho its turned OFF by default and should not be an issue.

**Comment by UselessGuru** [comment]
@aaronsta1 

-CreateMinerInstancePerDeviceModel is in deed off in your config, but it still created two miner instances (one for the 470's, and one for the 480's). I hope I can find the root cause with the output of http://localhost:3999/devices.

Can you also post http://localhost:3999/devices - thank you!

**Comment by aaronsta1** [comment]
`[
  {
    "Index": 0,
    "PlatformId": 0,
    "PlatformId_Index": 0,
    "Type_PlatformId_Index": 0,
    "Vendor": "Advanced Micro Devices, Inc.",
    "Vendor_ShortName": "AMD",
    "Vendor_Index": 0,
    "Type_Vendor_Index": 0,
    "Type": "Gpu",
    "Type_Index": 0,
    "OpenCL": {
      "AddressBits": 64,
      "Available": true,
      "CompilerAvailable": true,
      "DoubleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma",
      "EndianLittle": true,
      "ErrorCorrectionSupport": false,
      "ExecCapabilities": "ExecKernel",
      "Extensions": "cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash ",
      "GlobalMemCacheSize": 16384,
      "GlobalMemCacheType": 2,
      "GlobalMemCachelineSize": 64,
      "GlobalMemSize": 4294967296,
      "ImageSupport": true,
      "LocalMemSize": 32768,
      "LocalMemType": 1,
      "MaxClockFrequency": 1192,
      "MaxComputeUnits": 32,
      "MaxConstantArgs": 8,
      "MaxConstantBufferSize": null,
      "MaxMemAllocSize": 4026531840,
      "MaxParameterSize": 1024,
      "MaxReadImageArgs": 128,
      "MaxSamplers": 16,
      "MaxWorkGroupSize": 256,
      "MaxWorkItemDimensions": 3,
      "MaxWorkItemSizes": "256 256 256",
      "MaxWriteImageArgs": 64,
      "MemBaseAddrAlign": 2048,
      "MinDataTypeAlignSize": 128,
      "Name": "Ellesmere",
      "ClVersion": "OpenCL C 2.0 ",
      "Platform": "@{Profile=FULL_PROFILE; Version=OpenCL 2.0 AMD-APP (2442.12); Name=AMD Accelerated Parallel Processing; Vendor=Advanced Micro Devices, Inc.; Extensions=System.Object[]}",
      "PreferredVectorWidthChar": 4,
      "PreferredVectorWidthShort": 2,
      "PreferredVectorWidthInt": 1,
      "PreferredVectorWidthLong": 1,
      "PreferredVectorWidthFloat": 1,
      "PreferredVectorWidthDouble": 1,
      "Profile": "FULL_PROFILE",
      "QueueProperties": "ProfilingEnable",
      "SingleFpConfig": "FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "VendorId": 4098,
      "Version": "OpenCL 2.0 AMD-APP (2442.12)",
      "DriverVersion": "2442.12"
    },
    "Model": "Ellesmere4GB",
    "Model_Norm": "Ellesmere4GB",
    "Name": "GPU#00"
  },
  {
    "Index": 1,
    "PlatformId": 0,
    "PlatformId_Index": 1,
    "Type_PlatformId_Index": 1,
    "Vendor": "Advanced Micro Devices, Inc.",
    "Vendor_ShortName": "AMD",
    "Vendor_Index": 1,
    "Type_Vendor_Index": 1,
    "Type": "Gpu",
    "Type_Index": 1,
    "OpenCL": {
      "AddressBits": 64,
      "Available": true,
      "CompilerAvailable": true,
      "DoubleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma",
      "EndianLittle": true,
      "ErrorCorrectionSupport": false,
      "ExecCapabilities": "ExecKernel",
      "Extensions": "cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash ",
      "GlobalMemCacheSize": 16384,
      "GlobalMemCacheType": 2,
      "GlobalMemCachelineSize": 64,
      "GlobalMemSize": 8589934592,
      "ImageSupport": true,
      "LocalMemSize": 32768,
      "LocalMemType": 1,
      "MaxClockFrequency": 1236,
      "MaxComputeUnits": 36,
      "MaxConstantArgs": 8,
      "MaxConstantBufferSize": null,
      "MaxMemAllocSize": 4244635648,
      "MaxParameterSize": 1024,
      "MaxReadImageArgs": 128,
      "MaxSamplers": 16,
      "MaxWorkGroupSize": 256,
      "MaxWorkItemDimensions": 3,
      "MaxWorkItemSizes": "256 256 256",
      "MaxWriteImageArgs": 64,
      "MemBaseAddrAlign": 2048,
      "MinDataTypeAlignSize": 128,
      "Name": "Ellesmere",
      "ClVersion": "OpenCL C 2.0 ",
      "Platform": "@{Profile=FULL_PROFILE; Version=OpenCL 2.0 AMD-APP (2442.12); Name=AMD Accelerated Parallel Processing; Vendor=Advanced Micro Devices, Inc.; Extensions=System.Object[]}",
      "PreferredVectorWidthChar": 4,
      "PreferredVectorWidthShort": 2,
      "PreferredVectorWidthInt": 1,
      "PreferredVectorWidthLong": 1,
      "PreferredVectorWidthFloat": 1,
      "PreferredVectorWidthDouble": 1,
      "Profile": "FULL_PROFILE",
      "QueueProperties": "ProfilingEnable",
      "SingleFpConfig": "FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "VendorId": 4098,
      "Version": "OpenCL 2.0 AMD-APP (2442.12)",
      "DriverVersion": "2442.12"
    },
    "Model": "Ellesmere8GB",
    "Model_Norm": "Ellesmere8GB",
    "Name": "GPU#01"
  },
  {
    "Index": 2,
    "PlatformId": 0,
    "PlatformId_Index": 2,
    "Type_PlatformId_Index": 2,
    "Vendor": "Advanced Micro Devices, Inc.",
    "Vendor_ShortName": "AMD",
    "Vendor_Index": 2,
    "Type_Vendor_Index": 2,
    "Type": "Gpu",
    "Type_Index": 2,
    "OpenCL": {
      "AddressBits": 64,
      "Available": true,
      "CompilerAvailable": true,
      "DoubleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma",
      "EndianLittle": true,
      "ErrorCorrectionSupport": false,
      "ExecCapabilities": "ExecKernel",
      "Extensions": "cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash ",
      "GlobalMemCacheSize": 16384,
      "GlobalMemCacheType": 2,
      "GlobalMemCachelineSize": 64,
      "GlobalMemSize": 4294967296,
      "ImageSupport": true,
      "LocalMemSize": 32768,
      "LocalMemType": 1,
      "MaxClockFrequency": 1192,
      "MaxComputeUnits": 32,
      "MaxConstantArgs": 8,
      "MaxConstantBufferSize": null,
      "MaxMemAllocSize": 4026531840,
      "MaxParameterSize": 1024,
      "MaxReadImageArgs": 128,
      "MaxSamplers": 16,
      "MaxWorkGroupSize": 256,
      "MaxWorkItemDimensions": 3,
      "MaxWorkItemSizes": "256 256 256",
      "MaxWriteImageArgs": 64,
      "MemBaseAddrAlign": 2048,
      "MinDataTypeAlignSize": 128,
      "Name": "Ellesmere",
      "ClVersion": "OpenCL C 2.0 ",
      "Platform": "@{Profile=FULL_PROFILE; Version=OpenCL 2.0 AMD-APP (2442.12); Name=AMD Accelerated Parallel Processing; Vendor=Advanced Micro Devices, Inc.; Extensions=System.Object[]}",
      "PreferredVectorWidthChar": 4,
      "PreferredVectorWidthShort": 2,
      "PreferredVectorWidthInt": 1,
      "PreferredVectorWidthLong": 1,
      "PreferredVectorWidthFloat": 1,
      "PreferredVectorWidthDouble": 1,
      "Profile": "FULL_PROFILE",
      "QueueProperties": "ProfilingEnable",
      "SingleFpConfig": "FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "VendorId": 4098,
      "Version": "OpenCL 2.0 AMD-APP (2442.12)",
      "DriverVersion": "2442.12"
    },
    "Model": "Ellesmere4GB",
    "Model_Norm": "Ellesmere4GB",
    "Name": "GPU#02"
  },
  {
    "Index": 3,
    "PlatformId": 0,
    "PlatformId_Index": 3,
    "Type_PlatformId_Index": 3,
    "Vendor": "Advanced Micro Devices, Inc.",
    "Vendor_ShortName": "AMD",
    "Vendor_Index": 3,
    "Type_Vendor_Index": 3,
    "Type": "Gpu",
    "Type_Index": 3,
    "OpenCL": {
      "AddressBits": 64,
      "Available": true,
      "CompilerAvailable": true,
      "DoubleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma",
      "EndianLittle": true,
      "ErrorCorrectionSupport": false,
      "ExecCapabilities": "ExecKernel",
      "Extensions": "cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash ",
      "GlobalMemCacheSize": 16384,
      "GlobalMemCacheType": 2,
      "GlobalMemCachelineSize": 64,
      "GlobalMemSize": 4294967296,
      "ImageSupport": true,
      "LocalMemSize": 32768,
      "LocalMemType": 1,
      "MaxClockFrequency": 1192,
      "MaxComputeUnits": 32,
      "MaxConstantArgs": 8,
      "MaxConstantBufferSize": null,
      "MaxMemAllocSize": 4026531840,
      "MaxParameterSize": 1024,
      "MaxReadImageArgs": 128,
      "MaxSamplers": 16,
      "MaxWorkGroupSize": 256,
      "MaxWorkItemDimensions": 3,
      "MaxWorkItemSizes": "256 256 256",
      "MaxWriteImageArgs": 64,
      "MemBaseAddrAlign": 2048,
      "MinDataTypeAlignSize": 128,
      "Name": "Ellesmere",
      "ClVersion": "OpenCL C 2.0 ",
      "Platform": "@{Profile=FULL_PROFILE; Version=OpenCL 2.0 AMD-APP (2442.12); Name=AMD Accelerated Parallel Processing; Vendor=Advanced Micro Devices, Inc.; Extensions=System.Object[]}",
      "PreferredVectorWidthChar": 4,
      "PreferredVectorWidthShort": 2,
      "PreferredVectorWidthInt": 1,
      "PreferredVectorWidthLong": 1,
      "PreferredVectorWidthFloat": 1,
      "PreferredVectorWidthDouble": 1,
      "Profile": "FULL_PROFILE",
      "QueueProperties": "ProfilingEnable",
      "SingleFpConfig": "FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "VendorId": 4098,
      "Version": "OpenCL 2.0 AMD-APP (2442.12)",
      "DriverVersion": "2442.12"
    },
    "Model": "Ellesmere4GB",
    "Model_Norm": "Ellesmere4GB",
    "Name": "GPU#03"
  },
  {
    "Index": 4,
    "PlatformId": 0,
    "PlatformId_Index": 4,
    "Type_PlatformId_Index": 4,
    "Vendor": "Advanced Micro Devices, Inc.",
    "Vendor_ShortName": "AMD",
    "Vendor_Index": 4,
    "Type_Vendor_Index": 4,
    "Type": "Gpu",
    "Type_Index": 4,
    "OpenCL": {
      "AddressBits": 64,
      "Available": true,
      "CompilerAvailable": true,
      "DoubleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma",
      "EndianLittle": true,
      "ErrorCorrectionSupport": false,
      "ExecCapabilities": "ExecKernel",
      "Extensions": "cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash ",
      "GlobalMemCacheSize": 16384,
      "GlobalMemCacheType": 2,
      "GlobalMemCachelineSize": 64,
      "GlobalMemSize": 8589934592,
      "ImageSupport": true,
      "LocalMemSize": 32768,
      "LocalMemType": 1,
      "MaxClockFrequency": 1236,
      "MaxComputeUnits": 36,
      "MaxConstantArgs": 8,
      "MaxConstantBufferSize": null,
      "MaxMemAllocSize": 4244635648,
      "MaxParameterSize": 1024,
      "MaxReadImageArgs": 128,
      "MaxSamplers": 16,
      "MaxWorkGroupSize": 256,
      "MaxWorkItemDimensions": 3,
      "MaxWorkItemSizes": "256 256 256",
      "MaxWriteImageArgs": 64,
      "MemBaseAddrAlign": 2048,
      "MinDataTypeAlignSize": 128,
      "Name": "Ellesmere",
      "ClVersion": "OpenCL C 2.0 ",
      "Platform": "@{Profile=FULL_PROFILE; Version=OpenCL 2.0 AMD-APP (2442.12); Name=AMD Accelerated Parallel Processing; Vendor=Advanced Micro Devices, Inc.; Extensions=System.Object[]}",
      "PreferredVectorWidthChar": 4,
      "PreferredVectorWidthShort": 2,
      "PreferredVectorWidthInt": 1,
      "PreferredVectorWidthLong": 1,
      "PreferredVectorWidthFloat": 1,
      "PreferredVectorWidthDouble": 1,
      "Profile": "FULL_PROFILE",
      "QueueProperties": "ProfilingEnable",
      "SingleFpConfig": "FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt",
      "Type": "Gpu",
      "Vendor": "Advanced Micro Devices, Inc.",
      "VendorId": 4098,
      "Version": "OpenCL 2.0 AMD-APP (2442.12)",
      "DriverVersion": "2442.12"
    },
    "Model": "Ellesmere8GB",
    "Model_Norm": "Ellesmere8GB",
    "Name": "GPU#04"
  }
]`

**Comment by aaronsta1** [comment]
i wonder if it has something to do with this.
"Model": "Ellesmere4GB" and "Model": "Ellesmere8GB"
something you have coded is making it think those are 2 different cards even tho they are the same card with different memory.

**Comment by aaronsta1** [comment]
yep

**Comment by UselessGuru** [comment]
@aaronsta1 

I've found something.
Can you change MultipoolMiner.ps1 so that line

`        Get-ChildItemContent "MinersLegacy" -Parameters @{Pools = $Pools; Stats = $Stats; Config = $Config; Devices = $Devices} | ForEach-Object {$_.Content | Add-Member Name $_.Name -PassThru -Force} | `


becomes

`        Get-ChildItemContent "MinersLegacy" -Parameters @{Pools = $Pools; Stats = $Stats; Config = $Config; Devices = $DevicesTmp} | ForEach-Object {$_.Content | Add-Member Name $_.Name -PassThru -Force} | `

$Devices > $Devices**Tmp**

**Comment by UselessGuru** [comment]
aaronsta: Another question: 
Do you get the same issue with all miners, or only with ClaymoreEthash as reported?

**Comment by aaronsta1** [comment]
it was all the miners i posed up about an hour ago. ^

so i made the change and its working.. that was it. the true or false statement was showing the same result because you made it device = device lol.

i do have an error tho but it still works.
`Exception calling "CreateDecryptor" with "2" argument(s): "Specified initialization vector (IV) does not match the block size for this algorithm.
Parameter name: rgbIV"
At C:\Users\user\Documents\MultiPoolMiner_3_0_1\MinersLegacy\Excawator.ps1:149 char:1
+ $g = $f.CreateDecryptor($e, $dd);
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : ArgumentException

Exception calling "Read" with "3" argument(s): "Object reference not set to an instance of an object."
At C:\Users\user\Documents\MultiPoolMiner_3_0_1\MinersLegacy\Excawator.ps1:152 char:1
+ $r = $j.Read($h, 0, $h.Length);
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NullReferenceException

Exception calling "Close" with "0" argument(s): "Object reference not set to an instance of an object."
At C:\Users\user\Documents\MultiPoolMiner_3_0_1\MinersLegacy\Excawator.ps1:154 char:1
+ $j.Close();
+ ~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NullReferenceException

Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
At C:\Users\user\Documents\MultiPoolMiner_3_0_1\MinersLegacy\Excawator.ps1:163 char:19
+ Invoke-Expression $Wallet
+                   ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.InvokeExpressionCommand`

**Comment by UselessGuru** [comment]
Delete Excawator.ps1 - it is rubbish (it should never have made it into MPM 3.0.1)

Can you see what happens if you set CreateMinerInstancePerDeviceModel to true? Does ist count and store the correct hash rates?

**Comment by aaronsta1** [comment]
ok putting -CreateMinerInstancePerDeviceModel in start.bat put it back how it was.. so its working now.

thanks
