### ISSUE TITLE
Feature Request: change Pools/Excluded pools to just Pools and use "-"

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#2233]
Feature Request: change Pools/Excluded pools to just Pools and use "-" in front of the Poolname to exclude, no more cutting and pasting to the 2 different settings?

-PoolName nicehash,miningpoolhubcoins,miningpoolhub,Ravenminer -ExcludePoolName RavenminerEu,BlockMasters,NLPool,zpool,AHashPool,BlazePool,HashRefinery,yiimp

Vs

-PoolName nicehash,miningpoolhubcoins,miningpoolhub,Ravenminer,-RavenminerEu,-BlockMasters,-NLPool,zpool,-AHashPool,-BlazePool,-HashRefinery,-yiimp

**Comment by aaronsace** [comment]
Custom syntax is to be avoided unless absolutely necessary.

**Comment by UselessGuru** [comment]
> -PoolName nicehash,miningpoolhubcoins,miningpoolhub,Ravenminer -ExcludePoolName RavenminerEu,BlockMasters,NLPool,zpool,AHashPool,BlazePool,HashRefinery,yiimp

Why this?

If you just have the pools you want in 'PoolNames' then your're set already. There is no need for 'ExcludePoolNames'
