### ISSUE TITLE
MultiPoolMiner 3.1.0a is released (cleaned as of 15/11/2018 17:40 CET)

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2239]
We go hacked:  https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2241

A cleaned version has been upped as 3.1.0a

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/v3.1.0a_release

**Comment by FruitFace** [comment]
I'm seeing that Excawator.PS1 in the MinersLegacy folder...

**Comment by UselessGuru** [comment]
Thank you for the information!

This means that the attacker still has access to the repo!
Delete the file immediately.

**Comment by FruitFace** [comment]
Sure thing.  I deleted the folder the moment I saw it.
I didn't see Excawator in the new beta, so it seems they've only been targeting the major releases...

**Comment by UselessGuru** [comment]
I'll re-upload the clean original 3.1 release as 3.1.0a

**Comment by paulpoco** [comment]
Why is there still "Torrent" files in this release?  No one will say what that is for @aaronsace 
![screenshot_20181115-092358_solid explorer](https://user-images.githubusercontent.com/801414/48570310-f3666280-e8b8-11e8-90a7-57c2c988b7ea.png)

**Comment by UselessGuru** [comment]
@FruitFace 

Did you already run any of the start files???? They have been tampered with too!!!

The following files have been tampered with:

![image](https://user-images.githubusercontent.com/30080938/48570443-a7410f80-e904-11e8-93de-88fa6c09dd41.png)

and need to be deleted / replaces with the clean code from the updated master:

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/v3.1.0a_release

**Comment by UselessGuru** [comment]
@paulpoco 

Because Aaron says:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2212#issuecomment-435366956

**Comment by aaronsace** [comment]
@UselessGuru What the heck, again!? How? This makes no sense.

**Comment by FruitFace** [comment]
@UselessGuru 
I may have saved myself.  I overwrote the start file with my own, from the previous verison, so I wouldn't have to set all the details again. Then saw the excawator errors.  I immediately deleted files, rebooted, scanned etc...

Since I overwrote the tampered start file & excawator errored, the payload appears to  not have been delivered.

> 
> 
> @FruitFace
> 
> Did you already run any of the start files???? They have been tampered with too!!!
> 
> The following files have been tampered with:
> 
> ![image](https://user-images.githubusercontent.com/30080938/48570443-a7410f80-e904-11e8-93de-88fa6c09dd41.png)
> 
> and need to be deleted / replaced with the clean code from the updated master:
> 
> https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/v3.1.0a_release

**Comment by paulpoco** [comment]
> @paulpoco
> 
> Because Aaron says:
> [#2212 (comment)](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2212#issuecomment-435366956)

I read that, it does say what it is for.  What does Mining have to do with Torrents?

**Comment by aaronsace** [comment]
@paulpoco It will eventually form part of Downloader.ps1 and will enable 'magnet:' support as well as 'http:'. Mega link support will hopefully be added at a later date.

**Comment by grantemsley** [comment]
> @UselessGuru What the heck, again!? How? This makes no sense.

@fonyo @aaronsace According to github's logs, it appears to have been done from fonyo's account.  I recommend removing his access to the project until we can be sure he's secured his account.  His account changed the release on 2018-11-14 from an IP address assigned to the czech republic.

**Comment by aaronsace** [comment]
I've now taken write access away from all members unless given specific access.

**Comment by mtbor** [comment]
@aaronsace Time for some minimum security standards for those with access.
