### ISSUE TITLE
Miner not used

### ISSUE THREAD

**Issue by Djago** [MultiPoolMiner/MultiPoolMiner#2240]
I was mining solely XMR and then I've discovered this great project. I'm trying it right now and trying to understand it. My primary concern right now is the miners used.
I have a Ryzen 1700 and a Vega 56. Previously I was using XMRig (for CPU) and CAST-XMR (for AMD) mining. I've failed using some other combinations (like XMR-Stak for AMD, or SRB miner).
Now I see that MPM has successfully configured SRB, but I can't see any trace of CAST-XMR the one that was giving me the best results. I've checked in BIN, Downloads, Logs, Stats, but nothing about CAST there...
How can I see if there's a problem with CAST? How can I see if there's a problem with ANY OTHER miner?

EDIT: I've checked the file AMD-CastXmrVegaCryptonight_v1.50.ps1 and it's referring to an old release. Current release is 1.6.
EDIT2: I've tried renaming to AMD-CastXmrVegaCryptonight_v1.60.ps1 and modifying the URI ($Uri = "http://www.gandalph3000.com/download/cast_xmr-vega-win64_160.zip") and the HASH256 ($HashSHA256 = "ecc857c039dabf648fe6e823069cfcaa3988a20ba41e35057a3ee47640f04b9a") in a NEW installation (clean, only STATS folder copied), but the downloader didn't download it either. Also in the log there isn't any mention to the cast-xmr miner. I'm suspecting that there may be more miners download problems.

**Comment by UselessGuru** [comment]
>  and then I've discovered this great project. I

Thank you!

> I've failed using some other combinations (like XMR-Stak for AMD, or SRB miner).

If you post the log files I might be able to assist better. My crystal ball is currently in well deserved maintenance :-)

> it's referring to an old release. Current release is 1.6.

Thank you for the information. I've updated the miner file to version 1.60, see here:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/MinersLegacy/AMD-CastXmrVegaCryptonight_v1.60.ps1

> I'm suspecting that there may be more miners download problems.

MPM will only download miner if there is a pool & algo combination for the miner. I suspect either a config error, or a broken OpenCL installation. 
Would you mind posting the output of http://localhost:3999/config and http://localhost:3999/devices (save both t a separate file and upload them here.

**Comment by Djago** [comment]
> > I've failed using some other combinations (like XMR-Stak for AMD, or SRB miner).
> 
> If you post the log files I might be able to assist better. My crystal ball is currently in well deserved maintenance :-)

No, that's not what I meant. Previously I (by my own, downloading the miners and trying to mine with them) tried to use those combinations without success. MPM has succesfully configured some of those combinations (for example SRB!)

> > it's referring to an old release. Current release is 1.6.
> 
> Thank you for the information. I've updated the miner file to version 1.60, see here:
> https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/MinersLegacy/AMD-CastXmrVegaCryptonight_v1.60.ps1

So, I download it, put it in the miners legaxcy folder and... what? When I relaunch it will automagically download it or do I need to force it?
 
> > I'm suspecting that there may be more miners download problems.
> 
> MPM will only download miner if there is a pool & algo combination for the miner. I suspect either a config error, or a broken OpenCL installation.
> Would you mind posting the output of http://localhost:3999/config and http://localhost:3999/devices (save both t a separate file and upload them here).

Yes, right now I'm away, but as soon as I can, I'll upload them!

**Comment by UselessGuru** [comment]
> So, I download it, put it in the miners legaxcy folder and... what? 

MPM will do all for you, incl. all the necessary downloads.. 
Just start MPM and let is run for at least 2 minutes (1 loop takes approx. 1:20),

**Comment by Djago** [comment]
Sorry for the delay. Due to the tamper of the previous release, I've decided it was time to format/reinstall...
After clean installation and only copying stats folder plus putting your Cast1.6 file, still cast is missing from my bin folder...

Here are the files

[config.json.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2592434/config.json.txt)
[devices.json.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2592435/devices.json.txt)

**Comment by UselessGuru** [comment]
Can you have another go?


[AMD-CastXmrVegaCryptonight_v1.60.ps1.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2593326/AMD-CastXmrVegaCryptonight_v1.60.ps1.txt)

**Comment by Djago** [comment]
This time, MPM downloaded the file and put it in the bin folder! But the reported speed is very low (898H/s). I know that in this setup can get easily to 1700H/s so there's something odd here. And I don't see a cast-1 and cast-2 here so I suppose it's not the same work mode as SRB...
Now I've checked the downloads (and bin) folder and I don't see xmr-stak! Same problem here? How can I know if the other miners (that I'm not fond of because I've only mined XMR so far) have the same problem?

**Comment by UselessGuru** [comment]
> And I don't see a cast-1 and cast-2 here 

Where? What exactly did you expect to see? Please try to describe your issues as clearly as possible (screenshots sometimes help, and so do the MPM log files)

>  But the reported speed is very low (898H/s). 
> Now I've checked the downloads (and bin) folder and I don't see xmr-stak!

How can the miner run, but you don't have the binary installed? Maybe your virus scanner removed it?

**Comment by Djago** [comment]
> > And I don't see a cast-1 and cast-2 here
> 
> Where? What exactly did you expect to see? Please try to describe your issues as clearly as possible (screenshots sometimes help, and so do the MPM log files)

In the main MPM PowerShell window I have:

![image](https://user-images.githubusercontent.com/34612740/48713792-faaaaa80-ebef-11e8-8f33-c9b50df40cdc.png)

The sum of both SRB miners give aproximately what I get in terms of hashrate when I run SRB miner (I mean, when I run by myself, not via MPM).
The hashrate reporte for Cast is very low, almost half what I get when I run Cast by myself, so I thought that *maybe* I should expect 2 Cast miners (in the same way I have 2 SRB miners).

> > But the reported speed is very low (898H/s).

This report is regarding Cast. I can get 1700H/s for Cast when running it by myself.

> > Now I've checked the downloads (and bin) folder and I don't see xmr-stak!
> 
> How can the miner run, but you don't have the binary installed? Maybe your virus scanner removed it?

XMR-Stak is another miner, I'm not talking about SRB nor Cast anymore! I'm having the same issue that bring this post (that being Cast is not present), but talking about XMR-Stak. My question is: why XMR-Stak is not present? Maybe is the same problem that Cast has?
But XMR-Stak is a all-in-one so it should be present for mining via CPU and AMD.

**Comment by UselessGuru** [comment]
> The hashrate reporte for Cast is very low, almost half what I get when I run Cast by myself, 

Please assist me in finding out what is causing the difference and provide the configuration files. Thank you!

> but talking about XMR-Stak

From: 3.1.0 release notes:
_Temporarily removed FireIce XmrStak [AMD only] - Support for version 2.5.1 will be re-added soon_

XmrStak does not work with $CreateMinerInstancePerDeviceModel and has been removed. I am working on it but it is not as easy as I thought it would be.

**Comment by Djago** [comment]
> > The hashrate reporte for Cast is very low, almost half what I get when I run Cast by myself,
> 
> Please assist me in finding out what is causing the difference and provide the configuration files. Thank you!

There is no configuration file in Cast. The original zip consist of 3 files. The miner itself cast_xmr-vega.exe, another executable switch-radeon-gpu.exe and a simple run.bat you can use as a template to launch the miner with your wallet/pool/config. But if I launch that default bat (with the programmer's wallet), I get 1700H/s.
Now, I've discovered something (very bad). If I leave the PC alone for a couple of minutes and re-run cast, I get 1100H/s. I have to restart or suspend/resume the PC to get 1700H/s.
It's not the 898H/s reported in MPM but it's low, way lower than I can get from restarting the PC.
Is there a way to re-benchmark only one miner? I think that AMD driver can be a probelm... do you know a way to reset it without restarting or suspending/resuming? Maybe that can help.

> > but talking about XMR-Stak
> 
> From: 3.1.0 release notes:
> _Temporarily removed FireIce XmrStak [AMD only] - Support for version 2.5.1 will be re-added soon_
> 
> XmrStak does not work with $CreateMinerInstancePerDeviceModel and has been removed. I am working on it but it is not as easy as I thought it would be.

I see... I overlooked that on the notes. You said "[AMD only]" but I assume that this is a problem with CPU and nVidia, right?

**Comment by UselessGuru** [comment]
> Is there a way to re-benchmark only one miner?

Delete the stat file.

> FireIce XmrStak [AMD only]

That is a mistake. FireIce is currently not available for any platform.

**Comment by Djago** [comment]
Great, so this issue is fixed, at least for this miner. Is there a way to check if there's other miner that doesn't works as expected?

**Comment by Djago** [comment]
I mean like what happened to cast that it wasn't being downloaded. Before I came to MPM I only played with Cast, XMR-Stak, XMRing, SRBMiner, Claymore, monerospelunker and, on a PC that has a CPU without AES, JCE. So there are lots of miners available on MPM that I don't know. If something like what happened to cast happens to one of the miners I don't know, I have no way of knowing it. In fact, I only discovered the bug about Cast because incidentaly it's the one I was using and that puzzled me.
So I was wondering if there's a place where I can see why each possible miner is not available in my MPM setup.
Currently I have 19 files on my Download folder (and 19 sub folders on my Bin folder so there seems to be no problem in this regard). 5 files are AMD_NVIDIA-xxx, 11 files are AMD-xxx, 3 files are CPU-xxx.
But in the Miners Legacy folder I have 7 files AMD_NVIDIA-xxx, 18 files AMD-xxx and 16 files CPU-xxx, for a total of 68 files.
In the Stats folder I have: 5 are AMD_NVIDIA-xxx files (referring to the same miner), 10 files are AMD-xxx (referring to the same miner; there are more files refering to the same miner but different algo or a second thread), 19 files are CPU-xxx but only 3 different miners (strangely I have stats and bin for CryPly but I don't have the downloaded file!)
That means that MPM has determined that lots of miners are not suitable for my system. If there are more miners with the same problem as Cast, I would love to know it in order to inform you.
I'm uploading the 3 listings!
[stats.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2605897/stats.txt)
[Bin.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2605898/Bin.txt)
[Downloads.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2605900/Downloads.txt)
I suppose you need some of the log files, or wish me to generate some or whatever. Just ask me!

**Comment by Djago** [comment]
> > (strangely I have stats and bin for CryPly but I don't have the downloaded file!)
> 
> This absolutely makes no sense.

I totally agree with you. But you can check it with the files I've uploaded. Also I've checked the antivirus (Windows Defender) and it didn't remove anything. MPM should redownload it, should I do it manually  or it's not necessary?

> > it is OK to download the new ps1 files that are appearing in GitHub referring to new MinersLegacy? Like I did with Cast. I see 4 new files
> 
> Yes, if you know what you are doing. Otherwise you are better off downloading the ZIP file.

Yes, I'm ok with that. I'm experienced with computers since.... well, long time ago... My first computer was a Commodore 64 back in the '80s and I work as IT solution provider since 20 years ago.

Regarding other miners, do you think it's ok the miners I have or do I need to check something (maybe in the logs?
