### ISSUE TITLE
We got hacked again!!!

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2241]
## Release 3.1.0 got again tampered with.  The attacker obviously still has access to the repository. Investigations are underway.

**The hacked package has been removed from GitHub.**
It contained the following modifications:

![image](https://user-images.githubusercontent.com/30080938/48570708-4239e980-e905-11e8-8454-3a0e8856981b.png)

## What does the hack do?

The hack unpacks and executed an execuable named '[MPM Dir]\web\parts\cpufeaturedetector.exe' with the icon for zsnes'.

It appears to all sorts of bad things:

https://www.hybrid-analysis.com/sample/68c8962be93bd2f606715eaab98ed38abd7ca25244b0e5fa7006a10efbd6f6f4/5bedae3f7ca3e125800561ea

**Note: MPM contains also a file named '\cpufeaturedetector.exe' in the [MPM root folder], this file is OK and should be left alone**) 

#### I have re-uploaded a **clean package again as 3.1.0a** here:

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v3.1.0a_release/MultiPoolMiner-3.1.0a_release.zip

## What should you do???

- delete all affected files (including '[MPM Dir]\web\parts\cpufeaturedetector.exe')
- reboot your rig
- then follow general cleanup procedures after possible virus infections. e.g. boot from CD or clean media, scan your hard drive for viruses & malware.

**Comment by grantemsley** [comment]
The background.jpg file in the release is actually an encrypted zip file.  After finding the password I found it contains a file named cpufeaturedetector.exe, with the icon for ZSNES.  Analysis reveals it does bad things: https://www.hybrid-analysis.com/sample/68c8962be93bd2f606715eaab98ed38abd7ca25244b0e5fa7006a10efbd6f6f4/5bedae3f7ca3e125800561ea

If there's any chance that ran on your system, it'd be a very good reason to wipe the machine and reinstall windows fresh.

**Comment by mtbor** [comment]
What is the checksum of the infected package?

**Comment by mtbor** [comment]
What are the chances that if this file were executed it would then clean up after itself?  I haven't found any of the files in question.
I downloaded: "MultiPoolMiner-3.1.0_release" on ‎Tuesday, ‎November ‎13, ‎2018, ‏‎10:27:42 PM.
sha256: 5d70b200c7513658f9c7d8ee8b40daec2df728cec083310b65bc1ed88e49b7dd
Does not appear to have been infected at that time.

**Comment by UselessGuru** [comment]
@mtbor 

> What is the checksum of the infected package?

Sha256 hash: d94e08d100cfe421683a422131d14cf87cd1ad213e06fc639ca328fb0f80d439

> What are the chances that if this file were executed it would then clean up after itself?

Don't know, but I doubt it because I did not allow the malware to do it's magic.

If the attacker wanted to be undetected for a long time then he'd have to reverse his changes automatically. Since the hack also included modified start files he'd have keep the changes you'd made.
