### ISSUE TITLE
Pool fee does not populate automatically.

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2243]
Every pool shows 0% fee, how can I edit this?

**Comment by UselessGuru** [comment]
> Every pool shows 0% fee, how can I edit this?

The pools have different fees based on algo, protocol etc. Editing would not get you anywhere.
Enhanced pool files that support pool files are part of 3.2.0 Beta:

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/Beta3.2.0

These are compatible with 3.1.

**Comment by UselessGuru** [comment]
@mtbor 

>  I'll happily post whatever info / log files/ configs that help.

Would you mind posting the output of http://localhost:3999/config and http://localhost:3999/devices (save both t a separate file and upload them here).

> FYI, user editable fees is not a bad idea... For instance, does nicehash API advertise it's nearly 5%

That is what ProfitPenaltyFactor is for.

**Comment by mtbor** [comment]
Here they are:
[devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2591469/devices.txt)
[config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2591470/config.txt)

**Comment by UselessGuru** [comment]
Thank you

The devices look ok (3x1070ti, 1x1070) 👍 

But I cannot see any wallet information in your config. Did you remove this for confidentiality?

If not then make sure your config file contains **$Wallet**
```
  "Wallets": {
    "BTC": $Wallet
  }
```
Like this the wallet address specified in the start batch file will be inherited to all pools:
Note: You do not need a separate configured section per pool unless you want to override default  setting (as set by the command line).
You can also override the wallet address for each pool as shown for NiceHash below:

> For instance, does nicehash API advertise it's nearly 5% withdrawal fee? I doubt it does. I think it's lower if I use their wallet... but how annoying is that?

For NiceHash I recommend you to set `"IsInternalWallet":  true`

```
    "NiceHash":  {
        "Wallets":  {
            "BTC":  "<YOUR_NICEHASH_INTERNAL_WALLET>"
        },
        "IsInternalWallet":  true
    }

```
You need to edit the config file manually for this setting.

Attached the config file as I'd use for your system.

[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2591585/Config.txt)
