### ISSUE TITLE
Correct way to exit

### ISSUE THREAD

**Issue by Djago** [MultiPoolMiner/MultiPoolMiner#2245]
I'm using latest (3.1.0a) with snaketail "mod". When I need to stop MPM I can't find the right sequence for quitting ALL the threads/shells/programs/miners... running and I have to manually stop them in the Task Manager. Is there a QUIT/PAUSE/STOP/??? command/sequence?

**Comment by UselessGuru** [comment]
Just close the main MPM window. This will stop all miners and running processes.

For snaketail you need to close the minimized PWSH window and Snaktail.

**Comment by Djago** [comment]
Thanks!
