### ISSUE TITLE
SRBMiner1.7.0-1&2?

### ISSUE THREAD

**Issue by Djago** [MultiPoolMiner/MultiPoolMiner#2246]
In the list I have
AMD-SRBMinerCryptonight_v1.7.0-2-GPU#00[0,85 %]    CryptonightV8 997,00  H/s 0,00008136     97 % 82,30043110 MiningPoolHub-Monero[0,00 %]
AMD-SRBMinerCryptonight_v1.7.0-1-GPU#00[0,85 %]    CryptonightV8 898,00  H/s 0,00007328     97 % 82,30043110 MiningPoolHub-Monero[0,00 %]
Why 2?
Also hashrate is very low, I can get 1850H/s running it by myself (I mean, I've downloaded to a separate folder and run it with my own config), but I noticed that Hashrate of 1+2 gives aprox. the same result that I get by myself. Is this related?

**Comment by UselessGuru** [comment]
1 & 2 are the number of miner threads.
-1 runs the miner with one mining thread, -2 with two. One of the other might get better results under certain circumstances.

Can you please post the contents of both folders . I am interested in the config files the miners created.

**Comment by Djago** [comment]
I have 2 miners:

![image](https://user-images.githubusercontent.com/34612740/48673537-1bf09580-eb21-11e8-8aca-402ebb14442d.png)

But I have only one folder!

![image](https://user-images.githubusercontent.com/34612740/48673509-e9469d00-eb20-11e8-8813-bfaf40fa1b20.png)

**Comment by UselessGuru** [comment]
> But I have only one folder!

Of course. Same miner, two different miner objects, one with 1miner threads, the other one with 2.

I ask for the original MPM folder, and  "(I mean, I've downloaded to a separate folder and run it with my own config)"

**Comment by Djago** [comment]
Sorry, I misunderstood!
My folder doesn't have a json file nor any special configuration. I've simply modified the pools.txt with my data and run the start.bat. But I can send you the log that seems to have some info about it.
[2018_11_17_02_27_29.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2593040/2018_11_17_02_27_29.txt)

Also I'm uploading MBM's json files.
[GpuConf_1xgfx9007.984375GB-CryptonightV8-1-4000-djago.GO-x.json.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2593042/GpuConf_1xgfx9007.984375GB-CryptonightV8-1-4000-djago.GO-x.json.txt)
[GpuConf_1xgfx9007.984375GB-CryptonightV8-2-4000-djago.GO-x.json.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2593043/GpuConf_1xgfx9007.984375GB-CryptonightV8-2-4000-djago.GO-x.json.txt)
[PoolConf_MiningPoolHub-CryptonightV8.json.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2593044/PoolConf_MiningPoolHub-CryptonightV8.json.txt)

**Comment by UselessGuru** [comment]
> I mean, I've downloaded to a separate folder and run it with my own config), 

You did NOT download the miner binary to a new directory? What else do you want to say with this?

> but I noticed that Hashrate of 1+2 gives aprox. the same result that I get by myself. 

With what config do you get that speed?

Please understand that I cannot recreate your exact issue because I do not own a VEGA card. With both me AMD cards (560 & 570) it works well.

**Comment by Djago** [comment]
> > I mean, I've downloaded to a separate folder and run it with my own config),
> 
> You did NOT download the miner binary to a new directory? What else do you want to say with this?

What I meant is that I used SRB by myself, downloading it to a different folder and running it by myslef, not via MPM. I have two scenarios: running it by myself and running it (automatically) via MPM. 

> > but I noticed that Hashrate of 1+2 gives aprox. the same result that I get by myself.
> 
> With what config do you get that speed?
> 
> Please understand that I cannot recreate your exact issue because I do not own a VEGA card. With both me AMD cards (560 & 570) it works well.

Default SRB config. I simply download SRB, put my pool data on the pools.txt and then run the miner. The configuration is the one that SRB has as default. I thought that the log file attached could bring you some light as to what is the config auto-generated.

**Comment by Djago** [comment]
> > I thought that the log file attached could bring you some light
> 
> The log you have posted does not show the command lines used to run the miner.

I'm not using any special configuration/modification to the original config that came in the zip file. If I unzip the srb1.7 zip file and run it with start.bat I get 1850H/s

> > to what is the config auto-generated.
> 
> Please provide the configuration files so I can find out where the difference in speed might be coming fro.

The only modified file in my setup is the pools.txt where I put my pool+wallet+password. The other files are untouched.
I think that there's a problem regarding the driver (I've mentioned that in the issue #2240). If my conclusions are correct, this method of changing from miner to miner can be a problem. At least, without reseting/restarting something that's dragging miners.
I've confirmed that this is happening with SRB and Cast.

**Comment by Djago** [comment]
I've changed AMD driver to an older release. Now it's more stable but after a while of using MPM hashrate drops for AMD mining. I'm still looking for a solution to this problem.
Meanwhile, Cast seems to be working ok. But! Now it has replaced SRB and as far as I can tell, it shouldn't be so.
![image](https://user-images.githubusercontent.com/34612740/48881217-eda9d900-edf2-11e8-9145-b466a19cce93.png)
Correct me if I'm wrong, but SRB 1+2 vs Cast is: a) giving more H/s; b) has a lower fee, so why is MPM using Cast instead of SRB?
![image](https://user-images.githubusercontent.com/34612740/48881266-2fd31a80-edf3-11e8-9f30-fcb94b50768d.png)

**Comment by UselessGuru** [comment]
> But! Now it has replaced SRB and as far as I can tell, it shouldn't be so.

Why should this not be that way?

MPM reads the reported speed from the miner and saves it in the stat file. Check the recorded speed. If you feel this is off then just delete the stat file and let it re-benchmark.

I can see that SRB only has half the hash rates. Why? What hash rate does it report on the miner screen when benchlarking (use 'ShowMinerWindow' to see the miner output)

For each algo MPM calculates the best miner as recorded_hashrate * miner_fee_factor (1- n%).

> MPM hashrate drops for AMD mining.

This is not OK. You should get consistant hash rates. Check your rig for proper cooling.

**Comment by Djago** [comment]
> > But! Now it has replaced SRB and as far as I can tell, it shouldn't be so.
> 
> Why should this not be that way?
> 
> MPM reads the reported speed from the miner and saves it in the stat file. Check the recorded speed. If you feel this is off then just delete the stat file and let it re-benchmark.
> 
> I can see that SRB only has half the hash rates. 

SRB has two threads: 904+898=1802H/s. Cast has 1,73KH/s. Also the fee for SRB is 0,85% and for Cast is 1,5%. The effective hash is 1786H/s for SRB and 1704H/s for Cast, so I think that MPM should use SRB because it's ~5% higher.

>  Why? What hash rate does it report on the miner screen when benchlarking (use 'ShowMinerWindow' to see the miner output)
> 
> For each algo MPM calculates the best miner as recorded_hashrate * miner_fee_factor (1- n%).
> 
> > MPM hashrate drops for AMD mining.
> 
> This is not OK. You should get consistant hash rates. Check your rig for proper cooling.

SRB and Cast both reports Temp + RPM for the cooler and ther're both OK. Seems to be a Adrenaline+VEGA problem. I'm looking for a fix, or at least something that can reset the driver without the need for restarting the computer

**Comment by UselessGuru** [comment]
> SRB has two threads: 904+898=1802H/s.

I think you misunderstand something.

1 and 2 Threads are miner-internal threads.
SRB...-1 & -2 are each complete miners. The cannot run together -> You must not add the hash rates.

Wee need to figure out why MPM records such low speed for SRB.

What speed does SRB...-1 and ...-2 report on the screen when you are benchmarking them? Approx  900 or 1800/Hs?

**Comment by Djago** [comment]
I've deleted the stat file and retested and now I have 1.87kH/s and 1.86KH/s in SRB 1 and 2. So the problem is (again) this annoying problem that I have to restart the PC in order to get full values 👎 
I'm doing a re-benchmark of all AMD miners, but I'm not sure that between one and the next, hashrate won't drop.
