### ISSUE TITLE
Currency switch doesn't give XMR

### ISSUE THREAD

**Issue by Djago** [MultiPoolMiner/MultiPoolMiner#2247]
I've put -Currency btc,usd,xmr (on MPH) and always get 0,00000 on the XMR column (it work ok for BTC and USD)

**Comment by Djago** [comment]
![image](https://user-images.githubusercontent.com/34612740/48673480-ad133c80-eb20-11e8-80ab-18a24091bba9.png)

**Comment by UselessGuru** [comment]
Thank you!

MPM queries "https://api.coinbase.com/v2/exchange-rates?currency=BTC" for exchange rates. Unfortunately XMR is not available -> you see zero. What currencies are available is outside of MPM's control.
