### ISSUE TITLE
Run different algos on different cards. 

### ISSUE THREAD

**Issue by jeremiahtenbrink** [MultiPoolMiner/MultiPoolMiner#225]
Would it be difficult to run different algos on different cards. Say you had a amd and a nvida graphics card hooked up. Instead of having them both run the sam algo, could one run one algo and another run a different algo. I think this would be benifical even within the same card types. Sometimes the 970 will run one algo better than the 980 or vise versa.

**Comment by aaronsace** [comment]
It's a bit laborious to configure them all that way but now claymore supports GPU ordering you can create a file in the miner folder per GPU slot. 

Example text file name 'Claymore4.txt' for use with the 4th GPU: 
```
[
    {
        "Type":  ["AMD","NVIDIA"],
        "Path":  ".\\Bin\\Ethash-Claymore\\EthDcrMiner64.exe",
        "Arguments":  "-epool $($Pools.Ethash.Host):$($Pools.Ethash.Port) -ewal $($Pools.Ethash.User) -epsw $($Pools.Ethash.Pass) -esm 3 -allpools 1 -allcoins 1 -di 4",
        "HashRates":  {"Ethash":  "$($Stats.Claymore4_Ethash_HashRate.Week)"},
        "API":  "Claymore",
        "Port":  "43333",
        "Wrap":  false,
        "Device":  "GPU#04"
    }
]
```

**Comment by Jaerin** [comment]
Ondalf has a fork that was spawning miners on a per card basis.  Not sure if that could be adapted to work in the main branch.  That benchmarked each card individually and spawned separate miners.  I found that all the processes getting started and killed seemed to get out of sync at times though.

**Comment by aaronsace** [comment]
I will try and add card detention first. It is possible already though because I did it with excavator.

**Comment by aaronsace** [comment]
This looks like a good starting point: https://community.spiceworks.com/topic/1543645-powershell-get-wmiobject-win32_videocontroller-multiple-graphics-cards

**Comment by UselessGuru** [comment]
You might have a look at [my fork hosted here](https://github.com/UselessGuru/MultiPoolMiner). Note it is curently NVIDIA only.
