### ISSUE TITLE
New XMRig-AMD

### ISSUE THREAD

**Issue by Djago** [MultiPoolMiner/MultiPoolMiner#2250]
XMRig AMD has a new release 2.8.6:
Improved cn-heavy, cn-heavy/xhv perfomance up to 8% since v2.8.5 and up to 16% since v2.8.4
Improved cn-heavy/tube perfomance up to 6% and cn/2 perfomance up to 1%.

Is it ok to report new miner versions here?

**Comment by UselessGuru** [comment]
Yes - thank you!
