### ISSUE TITLE
New miner version SRBMiner 1.7.1

### ISSUE THREAD

**Issue by Djago** [MultiPoolMiner/MultiPoolMiner#2252]
There's a new version of SRB miner (1.7.1) with:

- Added new algo FreeHaven
- Small OpenCL optimisations
- Added 3 different modes for heavy algos (Heavy, Haven, BitTube, Italo, FreeHaven)
- Added value '9999' for fragments, that sets internally to the value it was in previous 1.6.8 version
- Fixed benchmarking mode + startup monitor bug
- Fragments, aes, bralock and heavy_mode can be set now outside gpu_conf, so it applies to every GPU

**Comment by UselessGuru** [comment]
Will be in 3.2.0 Beta 3
