### ISSUE TITLE
Update: NVIDIA-CcminerKlaust_v8.23.modr1.ps1

### ISSUE THREAD

**Issue by nemosminer** [MultiPoolMiner/MultiPoolMiner#2255]
Update: NVIDIA-CcminerKlaust_v8.23.modr1.ps1

to

NVIDIA-CcminerKlausT.ps1

New Compile (yesterday) 
updated cuda 9.2 to cuda 10.0
add yescryptR32 algo support ( -i 12.5 intensity recommended)
small speed increase to other supported algos thanks to latest drivers and cuda 10 mostly

https://github.com/nemosminer/ccminerKlausTyescrypt/releases

Best Regards
Nemo

**Comment by UselessGuru** [comment]
Thank you. This will be part of 3.2.0 Beta 5
