### ISSUE TITLE
Another miner?

### ISSUE THREAD

**Issue by Djago** [MultiPoolMiner/MultiPoolMiner#2256]
Please, can you look at JCE Miner?
https://bitcointalk.org/index.php?topic=3281187.0

**Comment by Majorbafe** [comment]
I'm also interested in having this miner on mpm...

**Comment by UselessGuru** [comment]
Thank you for the hint - here you go:

[AMD-JCECryptonote_v0.33b6.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2613414/AMD-JCECryptonote_v0.33b6.zip)

**Comment by Majorbafe** [comment]
Why is it that is starts under as "attrib.exe" name that ecists on windows/system32 folder?
Is it supposed to do that?

**Comment by Djago** [comment]
New version of the CPU version (33g):

> Online is the 0.33g CPU Windows re-released undercover with the said regression fixed.
> * With normal mode, kill the parent, the child attrib suicides, and vice-versa.
> * With --elevate, four processes are started, two jce and two attrib, one of each normal, one of each elevated. Kill any, the three other suicide.
> * With --elevate-and-quit, the parent suicide at the beginning, hence the name, so the attrib remains in all cases, on purpose. Don't use this mode if you want to grab the parent process-id to kill JCE from an external tool.

**Comment by UselessGuru** [comment]
Miner is available in 3.2.0 Beta 5

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/Beta3.2.0
