### ISSUE TITLE
I try the new 3.2.0 Beta 5a it won't work.

### ISSUE THREAD

**Issue by JakeloWang** [MultiPoolMiner/MultiPoolMiner#2261]
Since i try to start the 3.2.0 beta 5a version now even my old version won't work even the one i didn't touch.
It keep saying no open cl found but my version 3.0.1 was running before why it stop.
Now i can't use any of them how can i deactivate that open cl i remove every mention of amd or opencl' copy file from 3.0.1 which worked but still same issue.

**Comment by UselessGuru** [comment]
> It keep saying no open cl found but my version 3.0.1 was running before why it stop.

Nothing has changed in terms of OpenCL.
To assist you I need more information, e.g. logs, screenshots.

**Comment by JakeloWang** [comment]
Thx for the reply it work finally, i re-install my Nvidia drivers, removed the miner folder unzip it again. Then it work after a few restart.
