### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by nemosminer** [MultiPoolMiner/MultiPoolMiner#2263]
NVIDIA-CcminerKlaust_v8.23.modr1.ps1

NVIDIA-CcminerKlausT_vYescryptR16R32.V7.ps1

you should be able to replace both of these with the latest Version.. let know if you have any troubles 

ccminerKlausT v10: https://github.com/nemosminer/ccminerKlausTyescrypt/releases

**Comment by nemosminer** [comment]
Also updated Alexis78 recently with cuda10.0 now supports RTX cards best miner for skein available atm

ccminerAlexis78v1.4:  https://github.com/nemosminer/ccminerAlexis78/releases

**Comment by nemosminer** [comment]
and i updated TpruvoT to if you want it.. I compliled latest linux source code along with cuda10.0 

add support for exosis algo
 
ccminerTpruvot2.3 cuda10.0 : https://github.com/nemosminer/ccminerTpruvot/releases

**Comment by UselessGuru** [comment]
@nemosminer 

Thank you! Please let me know if when I can contribute something to your code base ;-)

**Comment by nemosminer** [comment]
had this Issiue open since March 2017 : ) https://github.com/nemosminer/NemosMiner/issues/399

**Comment by UselessGuru** [comment]
> have had this Issue open since March

I had implemented this for NVIDIA in my own old repo - I'll see what I can do :-)

**Comment by UselessGuru** [comment]
All 3 miners are updated in 3.2.0 Beta 7
