### ISSUE TITLE
Selected OpenCL device index <id> doesn't exist.

### ISSUE THREAD

**Issue by caniko2** [MultiPoolMiner/MultiPoolMiner#2269]
[12:13:17] Initializing GPU, loading kernel ...
Detected OpenCL Platform: OpenCL 2.1 AMD-APP (2686.5)
Fast job switching mode enabled.
[12:13:18] Selected OpenCL device index 2 doesn't exist.

I have two cards, each on PCI 16x

**Comment by UselessGuru** [comment]
@caniko2 

Can you please post the output of http://localhost:3999/devices.html

Please also give some more information, e.g. with what miner does this happen (one or many), what are the exact command lines that MPM created to launch the miner(s)?

**Comment by UselessGuru** [comment]
@caniko2 

> I am not sure I understand the question. Where can I find these commands?
For example (MultipoolMiner_YYYY-MM-DD.log)

> Do you know why?
No, but your OpenCL installation is broken. If you have only two cards then MPM should only see 2 cards. You have two options:
- either fix the broken OpenCL installation (I don't know how). This is the proper fix
- Exclude the two extra cards using the 'ExcludeMinerName' command (workaround). See the readme for more information.

**Comment by caniko2** [comment]
I am on a dead end here, I don't know where to even start. I did a DDU clean install, and it doesn't help. Maybe a windows 10 hard reset?

**Comment by caniko2** [comment]
Did you mean -ExcludeDeviceName?

**Comment by UselessGuru** [comment]
> Did you mean -ExcludeDeviceName

Yes - I've updated my post accordingly.

Add this to your start,bat file:

` -ExcludeDeviceName GPU#02,GPU#03` (use the device names as shown in your screenshot, separated by commas, no spaces between the values)

**Note: You'll need [3.20 Beta 9b](https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/Beta3.2.0/MultiPoolMiner_3.2.0_Beta9b.zip) for this to work!** (just replace include.psm1)

**Comment by UselessGuru** [comment]
BTW: Beta 10 is available:
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/Beta3.2.0/MultiPoolMiner_3.2.0_Beta10.zip

**Comment by UselessGuru** [comment]
> What is a system array?

A variable type - see: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-6
