### ISSUE TITLE
Feature Request Be able to run a custom command prior to launching miner

### ISSUE THREAD

**Issue by Jaerin** [MultiPoolMiner/MultiPoolMiner#227]
Would it be possible to integrate a method specifying a custom command that could be executed prior to launching a miner for a particular algorithm?  This could be used to set custom overclock settings or things prior to the miners launch.  It could also be used to write information out to logs or other custom things without having them integrated fully into the script.

Something similar to how you can specify custom difficulty or intensity settings, but perhaps you could specify a batch script or something that gets called prior to the miner being launched.

**Comment by aaronsace** [comment]
Yes, definitely. It had been mentioned, on my todo. #75

**Comment by UselessGuru** [comment]
This is implemented in version 3.4.0 and later
