### ISSUE TITLE
nlpool added  LiteBitcoin (LBTC) 

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2273]
just as notice

**Comment by UselessGuru** [comment]
MPM handles all algos / coins added by the pool automatically (a miner for the added algo is required of course). No further action is required.

The only thing that requires a MPM code change is the addition/removal of guaranteed payout currencies.

For NLPool these are currently (according to the information on their web page) BTC & LTC
