### ISSUE TITLE
console fires up powershell ok, but then eventually follows to pause command

### ISSUE THREAD

**Issue by rvaughn666** [MultiPoolMiner/MultiPoolMiner#2274]
my rig had been run  very stable on the version of 3.1.0a, but console started going to showing log info as normal, both pwsh fire off, but after a while one powershell console starts as normal, but then it says I am missing miners, which is true, and it says starting downloader, but that doesn't happen. with a minute or two bat console goes to pause which then stops all further running. Second powershell console never displays anything. I  have done a clean install of 3.1.0a and 3.2 beta 11 with same results.  Any thoughts on what might be the cause or steps to troubleshoot would be appreciated.

Thanks
Below is bat file that I use. 

@cd /d %~dp0

@if not "%GPU_FORCE_64BIT_PTR%"=="1" (setx GPU_FORCE_64BIT_PTR 1) > nul
@if not "%GPU_MAX_HEAP_SIZE%"=="100" (setx GPU_MAX_HEAP_SIZE 100) > nul
@if not "%GPU_USE_SYNC_OBJECTS%"=="1" (setx GPU_USE_SYNC_OBJECTS 1) > nul
@if not "%GPU_MAX_ALLOC_PERCENT%"=="100" (setx GPU_MAX_ALLOC_PERCENT 100) > nul
@if not "%GPU_SINGLE_ALLOC_PERCENT%"=="100" (setx GPU_SINGLE_ALLOC_PERCENT 100) > nul
@if not "%CUDA_DEVICE_ORDER%"=="PCI_BUS_ID" (setx CUDA_DEVICE_ORDER PCI_BUS_ID) > nul

REM @set "command=& .\multipoolminer.ps1 -Wallet 1A1r6gmFPwrJyWmuFWEApM1AHoPTwRy3jc -UserName raven66619 -WorkerName multipoolminer -Region US -Currency btc,usd,eur -DeviceName amd,nvidia -PoolName miningpoolhub,zpool -Algorithm cryptonightv7,cryptonightv8,cryptonightheavy,ethash,ethash2gb,ethash3gb,equihash,lyra2re2,lyra2z,neoscrypt,skein -Donate 24 -Watchdog -MinerStatusURL https://multipoolminer.io/monitor/miner.php -SwitchingPrevention 2"
@set "command=& .\multipoolminer.ps1 -wallet 1A1r6gmFPwrJyWmuFWEApM1AHoPTwRycJ3 -username raven66619 -workername krytoniteRig1 -CreateMinerInstancePerDeviceModel -region US -currency usd -DeviceName amd,nvidia -poolname miningpoolhub,zpool,nicehash  -algorithm blake2s,cryptonightV7,cryptonightV8,cryptonightheavy,decrednicehash,ethash,ethash2gb,ethash3gb,equihash,keccak,lbry,lyra2re2,lyra2z,m7m,neoscrypt,pascal,sib,skein,skunk,x16r -donate 10 -watchdog -minerstatusurl https://multipoolminer.io/monitor/miner.php -switchingprevention 3 "
start pwsh -noexit -executionpolicy bypass -command "& .\reader.ps1 -log 'MultiPoolMiner_\d\d\d\d-\d\d-\d\d\.txt' -sort '^[^_]*_' -quickstart"
start pwsh -noexit -executionpolicy bypass -command "& .\reader.ps1 -log '^((?!MultiPoolMiner_.+\.txt).)*$' -sort '^[^_]*_' -quickstart"

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
cd

pause

**Comment by UselessGuru** [comment]
Could this be the reason:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/547#issuecomment-354163216
???

> Second powershell console never displays anything. 

Try my alternate log reader:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2222

If this does not help then please post the log files (they are in the '[MPM-Dir]\Logs' folder.

**Comment by rvaughn666** [comment]
Thanks I will give both a try I do have both quick edit and insert mode on, lazy long time dos /windows/linux guy ;)
