### ISSUE TITLE
WARNING: Miner Status (https://multipoolminer.io/monitor/miner.php) has failed. 

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2275]
The SSL certificate on the monitoring web site has expired. Only Aaronsace can fix this.

Mining is NOT affected by this warning message.

As a temporary workaround I suggest you change your configuration so that MPM does not attempt to report to the monitoring site (see README).

**Comment by aaronsace** [comment]
Dam, it renewed recently; it should have just updated itself. Maybe I have to do something on Cloudflare as well... I'll have a look in a few minutes.

**Comment by aaronsace** [comment]
Changed Cloudflare to less strict so that the website is back up and I can access cPanel now. Will fix the SSL cert on cPanel properly later.

**Comment by UselessGuru** [comment]
I can confirm that it is working again. Thank you!

**Comment by aaronsace** [comment]
I've now updated the cert on the webserver and reenabled strict mode on Cloudflare. It should now work until the year 2033.
