### ISSUE TITLE
PS  WriteErrorException

### ISSUE THREAD

**Issue by gwthomp500** [MultiPoolMiner/MultiPoolMiner#2279]
Getting the following errors.

PS>TerminatingError(Invoke-RestMethod): "Unable to connect to the remote server"
Write-Log : Failed to connect to miner (AMD-SRBMinerCryptonight_v1.7.0-2-GPU#00-GPU#01) [ProcessId: 9968]. 
At C:\Users\gwtho\Downloads\MultiPoolMiner-3.1.0a_release\MultiPoolMiner-3.1.0a_release\APIs\SRBMiner.ps1:71 char:77
+ ... onds(30))) {Write-Log -Level Error "Failed to connect to miner ($($th ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
Write-Log : Miner (CPU-XmrigCryptonight_v2.8.3-CPU#00 {CryptonightV8@MiningPoolHubCoins}) has failed. 
At C:\Users\gwtho\Downloads\MultiPoolMiner-3.1.0a_release\MultiPoolMiner-3.1.0a_release\MultiPoolMiner.ps1:902 char:17
+ ...             Write-Log -Level Error "Miner ($($Miner.Name) {$(($Miner. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
Write-Log : Miner (CPU-XmrigCryptonight_v2.8.3-CPU#00 {CryptonightV8@MiningPoolHubCoins}) has failed.
At C:\Users\gwtho\Downloads\MultiPoolMiner-3.1.0a_release\MultiPoolMiner-3.1.0a_release\MultiPoolMiner.ps1:902 char:17
+ ...             Write-Log -Level Error "Miner ($($Miner.Name) {$(($Miner. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

**Comment by UselessGuru** [comment]
These errors happen when the miner binary dies (some miners are more stable than others).

If it happens regularly then try executing the miner binary outside of MPM using the exact same parameters (can be found in the log file).
I bet you'll get the same error. If so then please check with the miner developer.
