### ISSUE TITLE
Koto miner

### ISSUE THREAD

**Issue by Majorbafe** [MultiPoolMiner/MultiPoolMiner#2280]
I found this Koto miner for cpu that deals with yescrypt and yespower. I get good hashrates but the thing is that it does not support api links.
Is there any way to go around this and include it in mpm?

**Comment by UselessGuru** [comment]
@ Where did you find it? And is is really faster?

**Comment by Majorbafe** [comment]
I found it on github.
But when I was trying to acess it's behaviour on the comand prompt, I found out that though it had higher hashrate (2kH/s yespower and yescrypt) it came out with 100% rejected shares for yespower.
Maybe it's not worth the effort because for yescrypt there is already a good alternative for the same hashrate (Cryply version, and an others I found ,eg: cpuminer-easy-binarium-win_x64).
Yespower algo it's giving me good performance on Zpool but if the KotoMiner developer does not fix this rejected shares problem, it's not worth it.

**Comment by UselessGuru** [comment]
Link please.

**Comment by Majorbafe** [comment]
https://github.com/KotoDevelopers/cpuminer-yescrypt

**Comment by Majorbafe** [comment]
So... The Koto miner developer stated that it only supported Koto coin.
I was expecting that the miner would support any yespower algo based coin. This seems to not be true....
