### ISSUE TITLE
2 powershell calls on start script?

### ISSUE THREAD

**Issue by NightOwlCoder** [MultiPoolMiner/MultiPoolMiner#2289]
Hey guys,
I'm trying this project, and so far, I cant understand this 2 calls on the sample start scripts:

```
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
```

I noticed the exchange rare and miner key being printed twice on my window:
```
Exchange rates: 1 BTC = USD 3,613.76
Your miner status key is: 1EB7LcqAsdfFDFsdfsdfsdqNiEya3wjaJ78H65
```

And so after investigating, I found the 2 powershell calls, one for 6 and the other for 5.
I ended up commenting the powershell 5 call, and so far, I can't see if I did something bad...

Can someone help me understand it?

**Comment by UselessGuru** [comment]
> I cant understand this 2 calls on the sample start scripts:

This is OK:
The first line works for systems that have PWSH 6.x installed. In this case the 2. line will never get executed
The second line is for all other systems.

> I can't see if I did something bad...

There is no need to change this.

> I noticed the exchange rare and miner key being printed twice on my window:

Under rare circumstances this might happen upon first start, but not after the first few miner binaries have been downloaded. In any case this is nothing to worry about and is not related to the two pwsh / powershell calls.

**Comment by NightOwlCoder** [comment]
@UselessGuru my rig has both installed, and somehow `pwsh` crashed, and then the second line run.
Anyway, I just deleted the second line and looped the script around to account for these possible crashes.
Thanks for the reply!
