### ISSUE TITLE
Mono torrent error

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2290]
```
The process cannot access the file '[...]MultiPoolMiner-Test\MonoTorrent\MonoTorrent.Client\Encryption\EncryptedSocket.cs' because it is being used by another process.
+ CategoryInfo          : InvalidOperation: ([...]...st\include.psm1:String) [], RuntimeException
+ FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.AddTypeCommand
+ PSComputerName        : localhost
```

Maybe we should create a separate .psm1 for MonoTorrent only. 
Added benefit: Slimming down the Include.psm1 will increase overall performance.

**Comment by aaronsace** [comment]
@UselessGuru I don't think that error is related to MonoTorrent as it is a System IO error. Is the file open somewhere?

**Comment by aaronsace** [comment]
It may be related to `Start-Job` because no matter how many times you run `using module Include.psm1` with the same process it should only ever load the first time.

**Comment by aaronsace** [comment]
I think if `Add-Type` was in the `-InitializationScript` instead of `-ScriptBlock` then `Start-Job` should not import them in parallel. 

Also, this seems like it would work but doesn't; not sure as to why: 

```
Set-Location (Split-Path $MyInvocation.MyCommand.Path)
Add-Type -Path .\OpenCL\*.cs -OutputAssembly OpenCL.dll
Add-Type -Path .\OpenCL.dll
[OpenCl.Platform]::GetPlatformIDs()
```

**Comment by aaronsace** [comment]
It was a simple file name conflict; works now  
```
Set-Location (Split-Path $MyInvocation.MyCommand.Path)
Add-Type -Path .\OpenCL\*.cs -OutputAssembly ~OpenCL.dll
Add-Type -Path .\~OpenCL.dll
[OpenCl.Platform]::GetPlatformIDs()
```

**Comment by aaronsace** [comment]
@UselessGuru Does that solve the file lock issues and increase the speed slightly: 

c77ed765cfaef4c47e1a2c99d4d2404821b8c502

**Comment by UselessGuru** [comment]
@aaronsace 

Testing.... I'm doing a 'best of both world' version. Still doing the Pre-Load, but I'll load the pools as batch, and also load the balances as job. This will force many parallel loadings of the problematic routines.

Q: Why do you delete the dll on each start?
