### ISSUE TITLE
Beta 3.3.0 4a Is stopping and restarting the miner at every interval.

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2292]
Title says it all.

**Comment by mtbor** [comment]
I started fresh, the issue seems to have gone.

**Comment by mtbor** [comment]
still having this issue on one machine.

**Comment by mtbor** [comment]
![image](https://user-images.githubusercontent.com/34407962/51548686-1156c300-1e26-11e9-88b9-4d28e533eb53.png)

**Comment by mtbor** [comment]
[logexample.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2783623/logexample.txt)

**Comment by UselessGuru** [comment]
It should not do this.... try 3.30 Beta 5

**Comment by mtbor** [comment]
Two attempts with 3.30 Beta 5 resulted in the same behavior.  In this instance I changed only the wallet, machine name, pools, and algorithms in the start.bat file...  As well as deleted a few miner files that are a waste of time.   Everything else is exactly as packaged.
[MultiPoolMiner_2019-01-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2794477/MultiPoolMiner_2019-01-24.txt)

**Comment by mtbor** [comment]
Here's a graphical look from MSI Afterburner, inefficiency running high here.
![minerstartstopgraph](https://user-images.githubusercontent.com/34407962/51722514-da91d000-2012-11e9-8c0e-b2ffef52ac56.jpg)

**Comment by UselessGuru** [comment]
I found an issue in all 3.30 betas that cause MPM to not always select the most profitable algorithm.
This might be related to this issue.
Please stay tuned for 3.30 Beta 6 (hopefully coming today)

**Comment by UselessGuru** [comment]
Please report all issues in the new thread https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2303
