### ISSUE TITLE
Price penalty factor

### ISSUE THREAD

**Issue by Majorbafe** [MultiPoolMiner/MultiPoolMiner#2294]
Does anyone have any good "PricePenaltyFactors" for all the supported pools that give us realistic values?
I find that Blockmasters needs to be around 0.3 so it gives a good profit comparing to Zpool...
Any ideas?

**Comment by mkirov0** [comment]
I am working on something just regarding that issue. I hope I can finish and post soon. On BlockMasters specifically I found that they exchange at at least 20% lower than market value. I know its a bold statement, but I have been investigating them  for some time now😁

**Comment by mtbor** [comment]
For blockmasters -Excludepool is probably a more useful feature.

**Comment by Majorbafe** [comment]
And what do you think are the best factors for the pools?

Also, what's the most realistic pool, in your opinion?

**Comment by mkirov0** [comment]
@Majorbafe I am running 0.75 for BlockMasters and 0.85 for NL, but these are just numbers I like, not based on any data or science 😄. I can try and post the code I am working on, but unlike UGuru who is kicking butt posting betas every other day, I am not even in alfa; I am still in the process of inventing the Euclidean alphabet...

**Comment by mkirov0** [comment]
I got lucky and was able to capture this screenshot which explains my statement from a few days ago. The exchange is Bittrex (a fairly big and reputable exchange) and I got lucky to mine close to 1 XVG on BlockMasters, so the comparison is easier. Exchange buy/sell at 184 and 185 respectively and the pool evaluates at 154.
<img width="1275" alt="screen shot 2019-01-21 at 2 56 47 pm" src="https://user-images.githubusercontent.com/28104701/51476167-55e25000-1d8d-11e9-8f25-f75323e25c8d.png">

**Comment by mtbor** [comment]
@mkirov0  That's a very telling nugget of information you dug up.  Have you looked into other pools to see if they're stealing in a similar fashion?

I know pools dump coin, so if there's an arbitrage gap, everyone in the pool is contributing to some day traders profit...  I've always figured when people talked about pools taking a cut at exchange that was all that was going on...  but this, this just looks like pure theft.

**Comment by mtbor** [comment]
I did some checks on zpool payouts, my findings are they are taking 8-12% at exchange!!!   Please investigate your own findings...    My method was looking up the price in BTC, multiplying 1000 to get mBTC, then multiplying the quantity of that specific coin I was paid out.  This gives the amount I should see paid out, but in all cases that I checked it they paid out at least 8% less.

Good news is Zergpool was very near exact.
