### ISSUE TITLE
In memory powershell objects grow forever

### ISSUE THREAD

**Issue by codeknox** [MultiPoolMiner/MultiPoolMiner#2295]
I was wondering if I need to restart MPM every day?
Right now, all those in memory objects you can inspect through the API are huge!

I have a bash script to show some basic information, the the json parsing is taking a long time, because of those never ending objects.

For instance:
`runningminers` is 4.7Mb right now.
`activeminers` is 4.1Mb right now.

Is there a plan to clean them up every now and then? Or is it expected we restart MPM often?

Anyway, thank you for the great tool.

**Comment by aaronsace** [comment]
Mb is tiny, your system has Gb. Close the log reader, that uses the most memory.

**Comment by codeknox** [comment]
I guess you guys missed the point here.

I was not talking about process memory.
I'm talking about the size of the JSON object.

>I have a bash script to show some basic information, the the json parsing is taking a long time, because of those never ending objects.

because the:
```
Data: ["@{Date=01/23/2019 23:27:54; Raw={\"id\":1,\"jsonrpc\":\"2.0\",\"result\":[\"PM 4.0b\", \"0\", \"96708;0;0\", \"48517;48190;0\", \"0;0;0\", \"off;off;off\", \"37;0;40;0;42;0\", \"us-east.ethash-hub.miningpoolhub.com:17020\", \"0;0;0;0\"]}; HashRate=; PowerUsage=; Device=System.Object[]}","@{Date=01/23/2019 23:28:02; Raw={\"id\":1,\"jsonrpc\":\"2.0\",\"result\":[\"PM 4.0b\", \"0\", \"144511;0;0\", \"48518;48192;47801\", \"0;0;0\", \"off;off;off\", \"37;0;40;0;42;0\", \"us-east.ethash-hub.miningpoolhub.com:17020\", \"0;0;0;0\"]}; HashRate=; PowerUsage=; Device=System.Object[]}","@{Date=01/23/2019 23:28:12; Raw={\"id\":1,\"jsonrpc\":\"2.0\",\"result\":[\"PM 4.0b\", \"0\", \"144591;0;0\", \"48522;48192;47877\", \"0;0;0\", \"off;off;off\", \"44;0;46;0;47;0\", \"us-east.ethash-hub.miningpoolhub.com:17020\", \"0;0;0;0\"]}; HashRate=; PowerUsage=; Device=System.Object[]}","@{Date=01/23/2019 23:28:20; Raw={\"id\":1,\"jsonrpc\":\"2.0\",\"result\":[\"PM 4.0b\", \"0\", \"144528;1;0\", \"48520;48187;47821\", \"0;0;0\", \"off;off;off\", \"44;0;46;0;47;0\", \"us-east.ethash-hub.miningpoolhub.com:17020\", \"0;0;0;0\"]}; HashRate=; PowerUsage=; Device=System.Object[]}","@{Date=01/23/2019 23:29:04; Raw={\"id\":1,\"jsonrpc\":\"2.0\",\"result\":[\"PM 4.0b - ETC\", \"1\", \"144780;3;0\", \"48521;48187;48070\", \"0;0;0\", \"off;off;off\", \"48;0;51;0;51;0\", \"us-east.ethash-hub.miningpoolhub.com:17020\", \"0;0;0;0\"]}; HashRate=; PowerUsage=; Device=System.Object[]}","@{Date=01/23/2019 23:29:13; Raw={\"id\":1,\"jsonrpc\":\"2.0\",\"result\":[\"PM 4.0b - ETC\", \"1\", \"144802;3;0\", \"48521;48187;48093\", \"0;0;0\", \"off;off;off\", \"48;0;51;0;51;0\", \"us-east.ethash-hub.miningpoolhub.com:17020\", \"0;0;0;0\"]}; HashRate=; PowerUsage=; Device=System.Object[]}","@{Date=01/23/2019 23:29:21; Raw={\"id\":1,\"jsonrpc\":\"2.0\",\"result\":[\"PM 4.0b - ETC\", \"1\", \"144838;5;0\", \"48520;48187;48130\", \"0;0;0\", \"off;off;off\", \"48;0;51;0;51;0\", \"us-east.ethash-hub.miningpoolhub.com:17020\", \"0;0;0;0\"]}; HashRate=; PowerUsage=; Device=System.Object[]}","@{Date=01/23/2019 23:29:30; Raw={\"id\":1,\"jsonrpc\":\"2.0\",\"result\":[\"PM 4.0b - ETC\", \"1\", \"144857;5;0\", \"48519;48187;48150\", \"0;0;0\", \"off;off;off\", \"49;0;52;...........................
```
field keeps growing indefinitely, after 2 days my bash script takes forever to run...

So my question is:

Is this intentional or should I just close/restart *MPM* every 24h?

**Comment by aaronsace** [comment]
> Is this intentional or should I just close/restart MPM every 24h?

You don't need to parse all the parameters but ,no, of course an ever expanding variable is not intentional. 

Why do you think it's indefinite anyway; is it not limited to 10000 lines? If there are more than 10000 lines then there is a bug. 

https://github.com/MultiPoolMiner/MultiPoolMiner/blob/6ef1c2141cc9a58a0b686e3ac91b7a79b1f05cb4/Include.psm1#L1048

**Comment by aaronsace** [comment]
If there is a bug or not, off the top of my head, something like this would help you: 
`$ActiveMiners | Select-Object - Property * -ExcludeProperty Data | ConvertTo-Json -Depth 10`

**Comment by codeknox** [comment]
@aaronsace thanks man, I actually saw that 10000 number yesterday.
Issue is that I'm running my _monitor_ script from a Mac with bash though the `API`, so no powershell love for me there.
Anyway, that is an awesome idea (exclude `Data`) and I will find a similar command on the bash side.

Again, thank you all for the great tool and wonderful support.
