### ISSUE TITLE
Beta static config file fails.

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2296]
Everytime I copy the currently running config.txt (from http://localhost:3999/config), and put it into the config.txt file so I can make changes, multipoolminer fails.   It fails even using the previously accepted config with no changes.

**Comment by UselessGuru** [comment]
>> Everytime I copy the currently running config.txt (from http://localhost:3999/config), and put it into the config.txt file so I can make changes

You are doing someting wrong... I just tried and there is no problem. To verify the config file use a web service like www.jasonblob.com.

But why do you want to do this??? 

If you want to start with a clean config then remove the existing config file and start MPM. It will create a new config file with all the supported options.

To verify the config file use a web service like www.jasonblob.com.

**Comment by mtbor** [comment]
[staticconfiglog.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2777208/staticconfiglog.txt)
Notably, it doesn't seem to like the wallets, but they are there, but the formatting is different than typical.
Here's an example pool config:
""ZergPool": {
      "Wallets": "@{BTC=1LwDUKh8REWJ4JRgYhLTAtMqfobabF1sKi}",
      "Worker": "puter",
      "PricePenaltyFactor": 1.0,
      "MinPoolWorkers": 0"

**Comment by mtbor** [comment]
As far as having a static configuration file, I find it extremely useful for keeping high difficulty algorithms mining on pools that have enough hashrate to reliably hit blocks, and for pools that will mine on say X16R when the profitability is running high for something like say Ravencoin, but then pay your percentage on some cheap coin (zpool for instance).  Zergpool is back, but mining BCD with 10 other people seems silly when I can do it with 300 elsewhere, so until hits the configs and everyone starts mining there again, I'll exclude BCD from zergpool.

**Comment by aaronsace** [comment]
Sure @UselessGuru will be able to work out what is wrong if you post the config that is not working. 

> To assume that just because it works on your system that it won't break on a different configuration doesn't seem accurate, does it?

Oh, I wish that wasn't the case... 90% of the queries at my workplace consist of the user repeatedly doing it wrong and insisting it's not working. ☹

**Comment by mtbor** [comment]
[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2777218/Config.txt)

**Comment by UselessGuru** [comment]
> but mining BCD with 10 other people seems silly when I can do it with 300 elsewhere

That's what the 'MinWorkers' parameter is for.... it can be set per pool too.

**Comment by UselessGuru** [comment]
@mtbor 

There is a bug in the web GUI which breaks the wallet information (java script function 'JSON.stringify' in web\JSON.stringify cannot handle single values [PSCustomObject] inside a [PSCustomObject]).

I will implement a fix in the coming 3.30 Beta 5 version.
As a temporary workaround use the result of 'http://localhost:3999/config'.

**Comment by mtbor** [comment]
Minworkers seems cool, maybe a setting like 10 would be good for some
things, but very easy algorithms my rig can mine solo...  So it doesn't
really suit me.

**Comment by UselessGuru** [comment]
> maybe a setting like 10 would be good for some
things, but very easy algorithms my rig can mine solo... 

Would a per-algo setting for MinWorker be more appropriate, e.g. '-MinAlgorithmWorker'?

If both, '-MinPoolWorker' AND '-MinAlgorithmWorker' are configured for a miner, which value should be used?

**Comment by mkirov0** [comment]
IMHO if someone has this very specific reason to have both of them enabled -MinPoolWorker should take priority, since it will represent a very specific type of feeling towards specifically this pool.

**Comment by mtbor** [comment]
MinAlgorithmWorker would be very useful for me.  X22I, BCD, BITCORE, X16R (Ravencoin), even X17 (VERGE)...  those types of algorithms would greatly benefit.

**Comment by UselessGuru** [comment]
@mtbor & @mkirov0 

Please try 3.30 Beta5. It contains a new implementation for '-MinWorker' (see readme).

**Comment by UselessGuru** [comment]
Please report all issues in the new thread https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2303
