### ISSUE TITLE
Changelog Version 3.3.0 Beta 5

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2297]
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/Beta3.3/MultiPoolMiner_3.3.0_Beta5.zip

Please also report if all is working fine - only so I can know that we get rid of all the bugs :-)

#### Core changes
- Added parameter '-IgnorePowerCost'
- Backport code from coming 3.2.0 release
- Web GUI: Added columns for 'Earning', 'PowerUsage' & 'Workers'
- Web GUI: Fixed 'Wallet' information in 'Running Miners'
- Changed parameter '-MinPoolWorker' to '-MinWorker', configurable per algorithm and pool (see readme)

#### Miner changes
- Added NVIDIA-TTMiner_v2.1.6; support for PROGPOW, UBQHASH & MTP
- Updated AMD_NVIDIA-BMiner_v12.0.1; support for Grin
- Updated AMD-XmrigCryptonight_v2.9.1; support for Cryptonight/half
- Updated CPU-XmrigCryptonight_v2.9.1; support for Cryptonight/half
- Updated NVIDIA-ExcavatorNHMP_v1.5.15a; support for Skunk
- Updated NVIDIA-GminerEquihash_v1.20; support for Equihash 150,5 (Beam) & Cuckaroo29 (Grin)
- Updated NVIDIA-XmrigCryptonight_v2.9.4; support for Cryptonight/half

#### Pool changes
- Changed NLPools* URL to https://
- Fixed Ethash algo (regression of 3.3.0 Beta 3)
- MiningPoolHub(Coins): Change message 'no wallet address specified' to 'no username specified'
- Re-Added ZergPool & ZergPoolCoins

#### New Algorithms in Algorithms.txt
- Cuckaroo29

#### Core changes
- Balances: Currency order matches '-Currency' values
- Made column widths in miner overview dynamic
- Removed requirement for CpuFeatureDetector.exe, replaced with Get-CpuId (Include.psm1), backport from 3.2.0 release

#### Miner changes
- Updated AMD_NVIDIA-PhoenixminerEthash_v4.1c
- Updated NVIDIA-CryptoDredge_v0.16.1

#### Pool changes
- Fixed MiningPoolHub / MiningPoolHubCoins; Ethash algo not working, regression from 3.3.0 Beta 3

#### Core changes
- Added fault tolerance counter to stat files; if value is out of tolerance mor than 3 times the stat file will be forcefully updated
- Added EthashDAGSize.txt (Get-EthashDAGSize -CoinName), used in pool files
- Make '-ShowminerWindow' dynamic: Hide / show miner when parameter gets changed while MPM is running
- Optimze code for $BestMiners selection

#### Miner changes
- Updated AMD-WildRig_v0.15.1.2.beta; support for Sha256q & Sha256t
- Updated AMD_NVIDIA-EthminerEthash_v0.16.2
- Updated AMD_NVIDIA-BMiner_v11.4.0; support for Aeternity & Beam (AMD Beam only)
- Updated NVIDIA-CcminerTrex_v0.9.1; support for Sha256q
- Updated NVIDIA-CryptoDredge_v0.16.0; support for Lyra2zz & X16rt
- Updated NVIDIA-GminerEquihash_v1.18; support for Equihash 150,5 (Beam)

#### Pool changes
- Changed *Coins pools; added support for Ethash2gb/3gb variants
- Fixed MiningPoolHubCoins; invalid check for $Config.UserName, fixed stat file naming

#### New Algorithms in Algorithms.txt
- Beam
- Equihash1505
- Lyra2zz
- SHA256q

#### Core changes
- Fixed UnprofitableAlgorithms; regression of 3.3.0 Beta 2a

#### Core changes
- Added folder 'AlternateLogViewer'; experimental log viewer based on SnakeTail.exe
- Fixed start batch files back to old log viewer (files were accitially taken from AlternateLogViewer)

#### Miner changes
- Updated AMD-SRBMinerCryptonight_v1.7.6

#### New features
- API port is configurable, default is 3999 ('-APIPort' [Int])
- Better control over benchmark loops, number of hashrate samples per inveral is now configurable ('-HashRateSamplesPerInterval:10' [Int])
- Global miner warmup time parameter ('-WarmupTime:30' [seconds]). During the first loop MPM will ignore non-responding API calls for the configured duration. An example for this are some miners that need time to compile the binaries
- Invalid share detection; miner get marked failed if the configured ration of accepted / bad shares is exceeded ('-AllowedBadShareRatio:0' [Float])

#### Core changes
- Added parameter '-VerboseOutput' for extra information
- Fixed parameters '-MinerName' and '-ExcludeMinerName' (regression of miner naming change introduced in 3.1.x)
- Fixed unprofitable algorithms for '*-NHMP' and '*-NiceHash' algo names

#### Miner changes
- Added AMD-MkxminerLyra2z_v4.20
- Fixed AMD_CPU_NVIDIA-FireiceCryptonight_v2.7.1: disabled 2 threads on NVIDIA (miner error 'NVIDIA Invalid Result GPU ID n')
- Removed AMD-SgminerLyra2RE2_v5.1.0; miner was incorrectly named, it was for Lyre2RE only which is an unprofitable algo
- Removed AMD-MkxminerLyra2RE2_v3.10; it was for Lyre2RE2 only which is an unprofitable algo
- Updated AMD-WildRig_v0.15.0.12beta
- Updated AMD_NVIDIA-ClaymoreEthash_v12.0
- Updated NVIDIA-BMiner_v11.2.0, support for Aeternity & BEAM
- Updated NVIDIA-CcminerSuprMiner_v2.0.7; support for X16Rt
- Updated NVIDIA-CryptoDredge_v0.15.2
- Updated NVIDIA-GminerEquihash_v1.14

#### New Algorithms in Algorithms.txt
- Beam
- X16Rt

#### UnprofitableAlgorithms.txt
- Lyre2RE2

#### New features
- Ability to set a minimum profit threshold, do not mine if mining earns less ('-ProfitabilityThreshold:n')
- Make power usage and cost part of the calculation (optional), see README; requires separate installation and configuration of HWiNFO64 (see ConfigHWinfo64.pdf)

#### Core changes
- Changed storage location for stat files, separate directories for 'HashRate', 'PowerUsage' and 'Profit' files

**Comment by mtbor** [comment]
It appears you added a by default the launch of the log reader snaketail.exe.  I went ahead and got it and it seems pretty cool.  Changelog worthy?

**Comment by mtbor** [comment]
Never starts the downloader, doesn't recognize miners even after copying Bin directory from previous version.   Not ready to go.

**Comment by UselessGuru** [comment]
@mtbor 

Please re-download 3.30 Beta.

> Deleting the .dll files, running a snaketrail with a comment line to delete two config lines on mining rigs
This is intentional: https://github.com/MultiPoolMiner/MultiPoolMiner/blob/c77ed765cfaef4c47e1a2c99d4d2404821b8c502/Start.bat

>running a snaketrail
This is an error - fixed.

**Comment by mtbor** [comment]
Much better...  I'll report back anything else I find.

**Comment by zerofool** [comment]
Hi, I switched to 3.3b5 from an older version and I need a little help configuring it properly.
I can't understand how "PowerPrices" should be set in the Config.txt. The example in the readme didn't work. I managed to stop it from throwing errors at start-up, but I'm not sure it works as it should - I get negative power cost calculations in the corresponding column. Also, in what currency are the prices for KWh expected? USD? mBTC?
Here's what I have now in my Config.txt:

  "PowerPrices": [
    {
      "00:00" : 0.114,
      "06:00" : 0.118,
      "22:00" : 0.114
    }
  ],
  
Another thing that's bothering me is the benchmarking process - there are so many new parameters, and I can't understand their effect on each other.
Can you please explain the meaning of each one of these in regards to the benchmarking phase:

BenchmarkInterval
HashRateSamplesPerMinute
Interval
MinHashRateSamples
and also the "BenchmarkIntervals" in the miner files. Previously it worked as I expected, but now it only benchmarks the miner for a single "interval" (showing 1/5, for example) but then moves on to the next miner.


And a few other things - the readme has info on HashRateSamplesPerInterval (deprecated?) but lacks HashRateSamplesPerMinute.
Also, the ADVANCED CONFIGURATION section where payout currency per pool is explained appears to be outdated. It took me some time to track the change and make it work (by looking at Config.txt files posted by other users from the earlier 3.3 beta tickets).

Anyhow, I'm glad to see so much progress, keep it up!

**Comment by UselessGuru** [comment]
Please report all issues in the new thread https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2303
