### ISSUE TITLE
Warning Miner has Failed Errors (Beta3.3V5)

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2298]
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4002""
>> TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4002""
WARNING: Miner (NVIDIA-CcminerTrex_v0.9.1-1xGTX1070Ti {GltAstralHash@ZergPool}) has failed.

**Comment by UselessGuru** [comment]
> PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4002""

This happens when MPM queries the miner API, but the API is not (yet) responsive. This is just a cosmetic issue.

**Comment by mtbor** [comment]
When you say (yet) is it your understanding that this issue goes away?  Because it doesn't...  Since MPM cannot read the miner API, won't watchdog kick the miner?

**Comment by UselessGuru** [comment]
>This happens when MPM queries the miner API, but the API is not (yet) responsive

> won't watchdog kick the miner?

Depending on miner it can take quite some time until the API gets responsive. For each miner there is a property 'WarmupTime' that defines the grace period where MPM does not fail the miner if the API does not response in time. 

As long a MPM manages to get at least one hash rate sample watchdog will stay away. Nothing to worry.

**Comment by mtbor** [comment]
Doesn't seem to be happening with t-rex at all.   Seems like something is broken.

**Comment by UselessGuru** [comment]
> Doesn't seem to be happening with t-rex at all. 

Because the T-Rex API is operational immediately after the miner was launched.

**Comment by UselessGuru** [comment]
Please report all issues in the new thread https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2303
