### ISSUE TITLE
similar speed to CryptoDregde but has 0% fee

### ISSUE THREAD

**Issue by nemosminer** [MultiPoolMiner/MultiPoolMiner#2299]
@UselessGuru try this : ) https://github.com/nemosminer/ccminerMTP/releases very similar speed to CryptoDregde but has 0% fee   just finshed  testing it

**Comment by nemosminer** [comment]
lol

**Comment by UselessGuru** [comment]
> More profitable to pay the 2% fee

That depends. You don't know when the dev mining periods starts.

For an example assume this - it holds true for most minerswith dev fee:

- Communicated dev fee is 1 minute per hour (1.666%)
- MPM runs the miner on average 5 minutes befor swithing to another miner/algo, but no longer than 59minutes

If the miner starts dev mining 1 minute after the miners starts (and runs on the dev pool for one 1 minute) you will be mining 20% dev fee (one minute per average 5 minute run).
On the other hand if the miner starts dev minig on the 59th minute then the miner get 0% fee.

Just my two cents.

**Comment by nemosminer** [comment]
well said

**Comment by mtbor** [comment]
Need some optimization on multi-gpu rigs.  At -i 22 the GPU usage is all over the place and one card runs at about 60%.  At -i 23 all cards crash.

**Comment by mtbor** [comment]
A subsequent launch seemed to work fine, weird.

**Comment by nemosminer** [comment]
tested with 6x 1070ti and 6x 2080 

4gb ram
win 10
celeron pro 
all is well

**Comment by UselessGuru** [comment]
Miner is included in 3.30 Beta 6a
