### ISSUE TITLE
TTminer command line formatting - Erroneous worker name and payout.

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2301]
This is what I'm seeing poolside with TTminer...  should say "rig,c=BTC"
![ttminer](https://user-images.githubusercontent.com/34407962/51723706-6dcd0480-2017-11e9-8b95-a0ecc072d7f0.jpg)

**Comment by UselessGuru** [comment]
Thank you for your report. This will befixed in 3.30 Beta 6

Attached the fixed version - rename it to .ps1

[NVIDIA-TTMiner_v2.1.7.ps1.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2794846/NVIDIA-TTMiner_v2.1.7.ps1.txt)

**Comment by UselessGuru** [comment]
Please report all issues in the new thread https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2303
