### ISSUE TITLE
Feature Request: Pre- / post miner launch commands

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#2305]
I don't know how hard or easy it is to implement and/or what the potential pitfalls may be, but it would be awesome if I could use Afterburner's ( or any other GPU tweaker) saved clock presets and assign them to each algo or at least group of algos and have MPM switch profiles when it switches algos.

**Comment by UselessGuru** [comment]
@mkirov0 

This is not such an easy task - but it is also on my to-do list.

**Comment by UselessGuru** [comment]
MPM 3.3.0 Beta 18 (and) later will include enhancements to launch custom commands on either of these events:

- before a miner gets started (PreStopCommand)
- after a miner got startet (PostStartCommand)
- before a miner gets started (PreStopCommand)
- after a miner got stopped (PostStopCommand)
- after miner failure got detected (PostFailureCommand)

For details see the README file in the 303.0 Beta 19 ZIP file.
