### ISSUE TITLE
Reports of bitcore's demise greatly exaggerated?

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2309]
While some grumblings were heard about an ASIC for bitcore, it remains a profitable algorithm as far as I can tell.  Perhaps it should come off of the unprofitable algorithms file?

**Comment by Majorbafe** [comment]
I have always removed bitcore's entry from the UnprofitableAlgos...

**Comment by UselessGuru** [comment]
Will be back in 3.30 Beta 8: 
- Removed 'Bitcore' from UnprofitableAlgorithms.txt

Thank you for the suggestion

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2316
