### ISSUE TITLE
ReportStatus.ps1 not getting called

### ISSUE THREAD

**Issue by erikszewczyk** [MultiPoolMiner/MultiPoolMiner#2311]
I first noticed with 3.3.0 beta 6a and waited to start fresh with beta 7 - ReportStatus.ps1 doesnt seem to be getting called so status reports arent coming in.

In the log it looks like it goes strait from Start Waiting to Finish Waiting which is where (from how I read the code) it's supposed to get called:
2019-02-01 14:41:46 INFO: Start waiting before next run. 
2019-02-01 14:41:48 INFO: Finish waiting before next run. 

From the look of the if statements on the monitoring my guess would be one of the variables arent what it's expecting so it's skipping the section but I dont know how to debug (else I'd provide further detail).

I have 2 rigs that I'm running beta7 on that both exhibit this behavior.

**Comment by erikszewczyk** [comment]
A few additional observations as I noticed one of my rigs was checking in occasionally.  It looks like while running CcminerZealot for X16R reporting does occur, however when running GminerEquihash for Nicehash Beam (Equihash1505) reporting does not occur per above.

These are the only miners that have run in the last week, so I cant confirm if the issue is exclusive to Gminer

NVIDIA-GminerEquihasn_v1.25

**Comment by UselessGuru** [comment]
@erikszewczyk 

> It looks like while running CcminerZealot for X16R reporting does occur, however when running GminerEquihash for Nicehash Beam (Equihash1505) reporting does not occur per above.

Thank you for reporting your findings.
I will look into it.

There is no dependency between algo / miner and the reporting. It is just a timing thing.

**Comment by erikszewczyk** [comment]
@UselessGuru just wanted to say thanks for taking a look at this.  Not sure if you've been able to reproduce, but if you need me to gather any detail/logs/etc. just let me know.

**Comment by UselessGuru** [comment]
I moved ReportStatus to a background job:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2316
