### ISSUE TITLE
Support for zergpool solo mining.

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2312]
You can now solo mine on zergpool.
Here's the banner on their site: " SOLO and PARTY mining now available at Zergpool. Set m=solo, or m=party.YourPartyPassword to your password field to use this feature. No extra fees"

**Comment by UselessGuru** [comment]
Thank you for your input. While technically possible to implement I don't think that this is something that  MultiPoolMiner should support. I cannot see a valid case in this project.

**Comment by mkirov0** [comment]
Maybe I'm not smart enough to understand it, but I don't see the point use a pool to solo mine... To it sounds like an oxymoron. I see people doing it, so I'm sure someone has found a reason.

**Comment by mtbor** [comment]
Multipoolminer continuously scans for profitability on supported pools, as
such my miner is often one of the first on scene when a cyclical algorithm
starts trending toward profitability.  My miner finds lots of astralhash,
jeonghash, pawelhash...  All globaltoken.  On low difficulty algorithms, it
seems as though my profitability might be higher if I we're solo mining...
As it is, part of my low difficulty mining is shared with those whose
miners were slow to react when the difficulty was run back up.

The infrastructure is there, if it could be implemented on a per algorithm
or per coin basis...  I think the software is capable of "sniping" these
blocks.

Please consider it.

**Comment by borzaka** [comment]
@mkirov0 Technically you don't mine solo, the pool just records your shares as solo ones, and if the pool finds a block, and your share was the lucky one, you earn the whole block reward.
If you don't enable solo mode, you can still see the blocks founded by your miner on some pool. But you don't get the whole block reward, just a fair percentage by your contribution.

**Comment by mtbor** [comment]
Adding it to the password field works if you want to solo mine everything.  I only want to solo mine the easy stuff...

Zergpool is PPLNS, so jumping in and mining an easy coin when the difficultly is low should maximize my profitablity....  But at current, I'm sharing reward for blocks my miner finds with all the people that have been mining that coin at high difficulty....  If it were PPS it would be different, but PPLNS coddles the people that are doing it all wrong by sharing the easy pie with them for several minutes...

So yeah, solo support per coinname and/or algorithm???   Pretty please?

**Comment by UselessGuru** [comment]
@mtbor 

> So yeah, solo support per coinname and/or algorithm??? Pretty please?

Try the attached pool files (use at you own risk).

[Pools_ZergPool.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3026500/Pools_ZergPool.zip)

Config.txt like this:

```
    "ZergPool": {
          "PasswordSuffix": {
            "Algorithm": {
                "*": "",
                "Equihash": ",m=solo"
            }
        }
    },
    "ZergPoolCoins": {
      "PasswordSuffix": {
        "Algorithm": {
            "*": "",
            "Equihash": ",m=solo"
        },
        "CoinName": {
            "*": "",
            "Digibyte": ",m=solo"
        }
      }
    },
```

IPlease feel free to put together some descriptive information to be included in the README. 👍

**Comment by mtbor** [comment]
As far as I can tell this works without a hitch, thanks a bunch!  I'm going to give it a good long test drive.

**Comment by UselessGuru** [comment]
@mtbor 

Still fine?
Do you have some descriptive information to be included in the README? That would be helpful.

**Comment by mtbor** [comment]
Are you looking for a use justification?

"Due to swings in difficulty, your rig will probably spend short durations
of time mining coins with easy to find blocks while the difficulty is at
it's easiest.  This is good, your chance of finding a block during these
times is at it's highest point; however, you might find the payout system
of the pool you mine to rewards you for your proportion of the last group
of shares (PPLNS).  The downside to PPLNS in easy coins with large
difficulty swings is that it has a profitability averaging effect, your
block reward is shared with less accurate miners.

The solution is to enable solo mining for low difficulty coins.  This will
increase the variability of reward, but will improve long term
profitability."

**Comment by UselessGuru** [comment]
> Are you looking for a use justification?

No, for someone writing the text for the [README](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md) describing the new feature and config details.... ;-)

**Comment by mtbor** [comment]
I'll have a look at the Readme and see if I can type something up that fits.

**Comment by UselessGuru** [comment]
Support for solo / party mining is added in 3.3.0 Beta 17:

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/Beta3.3
