### ISSUE TITLE
Bminer issues

### ISSUE THREAD

**Issue by Levanclif** [MultiPoolMiner/MultiPoolMiner#2313]
Good day everyone. I am facing a problem with Bminer on Awesome Miner. I have been working with it it's been a year and 1/2 now. last month it started showing as you can see on the screen with an error. 
 I don't really understand what is happening there. Your assistance is highly appreciated.

Thank you
![josb4](https://user-images.githubusercontent.com/47324290/52213241-412aaf80-2897-11e9-9dda-ab6d17c203b0.png)

**Comment by UselessGuru** [comment]
> Good day everyone. I am facing a problem with Bminer on Awesome Miner.

This site is about MultiPoolMiner and not Awesome Miner. 
Maybe we can assist you if you post the command line that is executed to run Bminer.
