### ISSUE TITLE
Error in NVIDIA-TTMiner_v2.1.7.ps1

### ISSUE THREAD

**Issue by chairmanfaust** [MultiPoolMiner/MultiPoolMiner#2314]
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Version".
At C:\Temp\MultiPoolMiner_3_3_0_Beta7\MinersLegacy\NVIDIA-TTMiner_v2.1.7.ps1:24 char:5
+ if ([System.Version]$DriverVersion -ge "10.0") {
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : ConvertToFinalInvalidCastException

**Comment by UselessGuru** [comment]
Will be fixed in the next version

**Comment by UselessGuru** [comment]
Fixed verstion from upcoming 3.3.0 Beta 8:

[NVIDIA-TTMiner_v2.1.9.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2863594/NVIDIA-TTMiner_v2.1.9.txt)

(Rename to .ps1 and put in 'MinersLegacy' folder)

**Comment by chairmanfaust** [comment]
Thanks!
