### ISSUE TITLE
Cannot download PhoenixMiner.exe

### ISSUE THREAD

**Issue by chairmanfaust** [MultiPoolMiner/MultiPoolMiner#2322]
I'm getting the error:
WARNING: Cannot download PhoenixMiner.exe.
WARNING: Cannot find C:\MultiPoolMiner_3_3_0_Beta12\Bin\AMD_NVIDIA-PhoenixminerEthash_v4.2b\PhoenixMiner.exe.

I have the folder excluded from windows defender.. not sure where to download this manually from

**Comment by UselessGuru** [comment]
> WARNING: Cannot download PhoenixMiner.exe.

4.2b is just a beta from the miners developers. The miner file should not have been included in the 3.3.0 Beta 12 (my bad).
Just delete the [MPM Folder]\MinersLegacy\AMD_NVIDIA-PhoenixminerEthash_v4.2b.ps1 file.
You can instead try AMD_NVIDIA-PhoenixminerEthash_v4.2c (rename it to.txt):

[AMD_NVIDIA-PhoenixminerEthash_v4.2c.ps1.txt]
(https://github.com/MultiPoolMiner/MultiPoolMiner/files/2995210/AMD_NVIDIA-PhoenixminerEthash_v4.2c.ps1.txt)

**Comment by chairmanfaust** [comment]
Thanks! that fixed it... I also had the error with cast_xmr-vega-win64_166 but was able to manually download and place that in the correct folder... I think the download link no longer works
