### ISSUE TITLE
Possible enhancement

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2325]
I'm not sure what data the current accuracy value is pulled from, but it seems there may be a way to further the profitability of MPM.

It hinges on this question, does the API supply 24hr profitability data?  If it does, MPM could become much more autonomous than it already is.

For instance, MTP on zergpool....  just not enough miners, 24 hour profitability is almost always much less than the estimate.  Another example, X16R on nlpool, estimated profitability hovers around .008-.009 mBTC/MH/day....  Actual 24 hour performance is usually around .002.  That's like 25%.  Veil on NLpool is the same, lousy.

The current accuracy feature, while I believe it is the best there is, would be amazing if this could be considered....  You could pretty much load all pools/algos and MPM would be spot on.

**Comment by UselessGuru** [comment]
> I'm not sure what data the current accuracy value is pulled from,

It is a function based on fluctuation (pricing information proviced by the pool) and time.

> does the API supply 24hr profitability data

What API?

> is the same, lousy.

MPM is using the data that the pool provides. The pool again depends on the prices that are paid on the exchanges.
Are you familiar with what MrPlus is doing with Nemos Miner? Is that what you are refering to?

**Comment by mtbor** [comment]
So MPM measures the accuracy of the real time data, but not actual performance.

The 24 hour profitability data is readily available on every YIIMP based pool I've seen, so my question is, do YIIMP pools make that data available through their API?

I'm familiar with exchanges and variables that effect ultimate profitability.  What I'm talking about are pools that have algorithms that consistently underperform.  Some of these algorithms probably earn 25% of what the calculations show they should.  I do not know whether this is due to poor wallet connection to the network of those specific coins or not enough hash, but it's a way bigger deal than the fluctuation is.

I'm not familiar with what MrPlus is doing, but I'll check it out, thanks.

**Comment by mtbor** [comment]
If you're referring to the brain plus thing nemosminer has been doing for a long time, I don't think that's the same.  My proposition is keeping track of 24 hour earnings actual vs 24 earnings estimated as a simple percentage.  The mBTC/MH/Day would be multiplied by this decimal value to give proper valuation to algorithms and coins that actually find the blocks they say they should... and therefore actually pay.

**Comment by aaronsace** [comment]
@mtbor I implemented that but it never made it into version 1 on GitHub because MiningPoolHub wouldn't implement the stats so I stripped it out. `PricePenaltyFactor` has appeared in the code from somewhere but it is no good because you have to type the figures manually.

**Comment by mtbor** [comment]
@aaronsace It's a great feature, I don't even mine to MPH...  Could the feature be implemented YIIMP only?

**Comment by aaronsace** [comment]
It worked for all yiimp derived pools like Zpool. Will look into the possibility of adding it.

**Comment by UselessGuru** [comment]
Why not just use the actual_last24h price info instead of estimate_last24h as it is implemented in the current pool code?

**Comment by mtbor** [comment]
Uselessguru..  would it be a tremendous amount of work to include something like "Useactualprofit": true/false.

So the end user could make their choice?

**Comment by aaronsace** [comment]
Neither of these statements sound correct. Live stats aren't actuals. @mtbor you were on the right track earlier.

**Comment by UselessGuru** [comment]
@aaronsace 

> Will look into the possibility of adding it.

When?

**Comment by aaronsace** [comment]
@UselessGuru After I've finished the current items. Don't worry, I've not forgotten.

**Comment by NadirTennci** [comment]
Hi @aaronsace can I ask you where the summary data is coming from? the data that has the ACC and REJ?

**Comment by aaronsace** [comment]
@NadirTennci Wasn't that discussed here? https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2342

**Comment by NadirTennci** [comment]
Oh, my bad bro, I didnt receive any notification from github, thank you so much, much love

**Comment by UselessGuru** [comment]
>  The mBTC/MH/Day would be multiplied by this decimal value to give proper valuation to algorithms and coins that actually find the blocks they say they should... 

This is implemented in version 3.4.5:
https://github.com/UselessGuru/MultiPoolMiner/releases/tag/3.4.5
