### ISSUE TITLE
Globaltoken handling

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#2326]
So globaltoken is running on Gltjeonghash,Gltpawelhash,Gltastralhash, and Gltpadihash...  All four of these algorithms behave differently, but they're all fed into the same stats file.

Frequently this shows a negative value under accuracy.

Does the accuracy calculation take an absolute value, or does having a negative value in the "run" cause erroneous results?

Is there a fix, or are we better off not mining these algorithms?

**Comment by UselessGuru** [comment]
@mtbor 

Thank you for your input! According to https://globaltoken.org/ it is 30 algorithms...
This is constellation that MPM cannot deal with as is.

> Is there a fix, or are we better off not mining these algorithms?

Probably yes.

**Comment by UselessGuru** [comment]
A fix will be in the upcoming 3.3.0 Beta 15

**Comment by UselessGuru** [comment]
Pool files have been modified to fix this issue:
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/Beta3.3/MultiPoolMiner_3.3.0_Beta15.zip
