### ISSUE TITLE
3.3.0 beta 16 "Cannot find path 'C:\windows\system32\hal.dll' because it does not exist."

### ISSUE THREAD

**Issue by chairmanfaust** [MultiPoolMiner/MultiPoolMiner#2329]
After a fresh install and upon starting the miningpoolhub.bat I get this:

`Cannot find path 'C:\windows\system32\hal.dll' because it does not exist.
+ CategoryInfo          : ObjectNotFound: (C:\windows\system32\hal.dll:String) [Get-ItemProperty], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
+ PSComputerName        : localhost

You cannot call a method on a null-valued expression.
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
+ PSComputerName        : localhost

Cannot find path 'C:\windows\system32\hal.dll' because it does not exist.
+ CategoryInfo          : ObjectNotFound: (C:\windows\system32\hal.dll:String) [Get-ItemProperty], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
+ PSComputerName        : localhost

You cannot call a method on a null-valued expression.
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
+ PSComputerName        : localhost

Cannot find path 'C:\windows\system32\hal.dll' because it does not exist.
+ CategoryInfo          : ObjectNotFound: (C:\windows\system32\hal.dll:String) [Get-ItemProperty], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
+ PSComputerName        : localhost

You cannot call a method on a null-valued expression.
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
+ PSComputerName        : localhost`

everything appears to work though

**Comment by UselessGuru** [comment]
@chairmanfaust 

What OS version are you running? What is you boot drive letter?

The message is cause be the following three miners:
- AMD_NVIDIA-BMiner_v15.4.0.ps1
- AMD_NVIDIA-GminerEquihash_v1.36
- NVIDIA-NBMiner_v21.3
Hal.dll is accessed to determine the amount of VRAM available depending on the OS version.

The path to Hal.dll is hard coded in the miner files. I will change the hard coded path with something more flexible.

**Comment by UselessGuru** [comment]
@chairmanfaust 

Could you please see if the attached files fix the error - 
[MinersLegacy.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3036995/MinersLegacy.zip)
thank you!

**Comment by chairmanfaust** [comment]
I tried the new files but received the same error... I'm using Windows 10 and my boot drive is C: I can see the files there (hal.dll) I'm wondering if maybe its a permissions problem... I tried running the miningpoolhub batch file as admin but got the same results.. This problem only seemed to start manifesting with release beta 14, prior to that I didn't see this error

**Comment by UselessGuru** [comment]
> This problem only seemed to start manifesting with release beta 14, prior to that I didn't see this error

The code exists longer than that, but I is well possible that the code (in the tree affected miner files) only got relevant due to the appearance of the Cockatoo31 algorithms

```
        #Cuckatoo31 on windows 10 requires 3.5 GB extra
        if ($Main_Algorithm -eq "Cuckatoo31" -and (Get-ItemProperty -Path "$ENV:SystemDrive\Windows\system32\hal.dll").VersionInfo.FileVersion.Split(".")[0] -ge 10) {$MinMemGB += 3.5}
```

Can you try these files:
[MinersLegacy.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3038852/MinersLegacy.zip)

**Comment by chairmanfaust** [comment]
That appears to have worked, no more error messages... Thanks!

**Comment by UselessGuru** [comment]
I will include the new file in the next release. Thanks for testing!

**Comment by chairmanfaust** [comment]
Happy to help, I appreciate all the work you put into this.
