### ISSUE TITLE
Windows could not find the file "pwsh".

### ISSUE THREAD

**Issue by ctmb520** [MultiPoolMiner/MultiPoolMiner#2330]
3.3.0 beta 16

Hint after running Start.bat

Windows could not find the file "pwsh". Please make sure that the file name is correct and try again.

The server is win2012

**Comment by UselessGuru** [comment]
@ctmb520 

Please install PowershellCore. (https://github.com/PowerShell/PowerShell)
If PowerShell Core is not installed, MPM will fall back to legacy porwershell and print the warning..
