### ISSUE TITLE
Excavator hasher interrupted

### ISSUE THREAD

**Issue by caniko2** [MultiPoolMiner/MultiPoolMiner#2331]
I keep getting new jobs, and get this printed each time:
[[2019-04-07 12:03:13.606966] [thread=0x00004060] [debug]]
        wrkr0-0 | Hasher interrupted

2019-04-07 12:03:58 VERBOSE: NVIDIA-ExcavatorNHMP_v1.5.13a-1-GPU#00: ["{\"id\":1,\"method\":\"worker.list\",\"params\":[]}",{"id":1,"error":null}]

**Comment by caniko2** [comment]
I do get some of the jobs accepted, but it happens rarely.

**Comment by UselessGuru** [comment]
Sounds like a NiceHash internal error.

BTW: Excavator is no longer supported by NiceHash (development is stoppedI)

To get actual miners I recommend you always use the latest MPM beta:
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/Beta3.3
