### ISSUE TITLE
Wild Rig Miner 0.15.7 Not Available - Download Fails

### ISSUE THREAD

**Issue by firrae** [MultiPoolMiner/MultiPoolMiner#2338]
Looks like Wild Rig 0.15.7 is no longer on their releases so it fails to download.

**Comment by UselessGuru** [comment]
Thank you for reporting. DL link will be fixed in upcoming 3.30 Beta 23

**Comment by UselessGuru** [comment]
Fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2339
