### ISSUE TITLE
Technical Question

### ISSUE THREAD

**Issue by NadirTennci** [MultiPoolMiner/MultiPoolMiner#2342]
Hi, 

I'm wondering how the "Data" attribute in Miner class is being filled, I noticed that it's not UpdateMinerData function that is doing it, is it the process?

Thank you.

**Comment by UselessGuru** [comment]
> I'm wondering how the "Data" attribute in Miner class is being filled

Yes, it is the UpdateMinerData function indeed. Each miner class has it's own implementation of the function. Check the ps1 files in the APIs folder.
