### ISSUE TITLE
MultiPoolMiner no longer works as it used to?

### ISSUE THREAD

**Issue by Skyrid3r** [MultiPoolMiner/MultiPoolMiner#2346]
So after around a year / over a year I come back in attempts to use MultiPoolMiner again, and I seem to fail miserably. Last time I used it, it was working fine with no issues what so ever. But running it over night does it appear it "does" something, but no actual balance is given out.

I run MultiPoolMiner in combination with miningpoolhub. Last time I ran this, miningpoolhub balances area was piling up with different kind of currencies that I mined (though low amounts) but again, just from 1 night of mining and nothing in the balance area..

![image](https://user-images.githubusercontent.com/6794064/60382582-5df19a80-9a65-11e9-9cd0-c1549e66a548.png)

According to that, I mined at least a bit of BTC today. But haven't received anything on my wallet thus far. Not sure why the NVIDIA shows undefined though, running a NVIDIA GTX 1060 (Yes, installed the packages as instructed, but I already have all the vcredist installed). 

This is my current start settings:

```set "command=& .\multipoolminer.ps1 -Wallet xxx-UserName xx -WorkerName xx -Region europe -Currency btc,usd,eur -DeviceName nvidia,cpu -PoolName miningpoolhubcoins -Algorithm blake2s,cuckaroo39,cuckatoo31,cryptonightR,cryptonightV8,cryptonightheavy,decrednicehash,ethash,ethash2gb,ethash3gb,equihash,equihash1445,equihash1505,keccak,lbry,lyra2re3,mtp,mtpnicehash,neoscrypt,pascal,sib,skein,skunk,sonoa,timetravel10,x16r,x16rt,x16s,x17,x22i -Donate 24 -Watchdog -MinerStatusURL https://multipoolminer.io/monitor/miner.php -MinerStatusKey xx -API_Key xxx -SwitchingPrevention 2"```

While I know the wallet part isn't needed/required, the console was asking for it when I was running it with the zpool poolname included. (not currently there).

So, am I doing something wrong here? And why can't I check out miningpoolhub what my worker(s) are exactly doing in a global view rather than going to each pool and check out the workers there? 

Help is appreciated, as I'm rather stuck.

**BTW**.. Running the least release Version 3.4.0 final which is waiting for approval.

I had to go to the latest release, because the older versions (including the beta) constantly gave a Europe miningpoolhub connection error (like it was connecting to an older URL)

**Comment by mkirov0** [comment]
@Skyrid3r when mining only to MiningPoolHub, a wallet is not required, but if you had Zpool on at some point it is absolutely necessary. With the settings you mention above technically you should be OK without listing a wallet. As far as MPM asking for a wallet when only mining to MiningPoolHub, I'm sure UselessGuru can fix this in no time. 
In the mean time if you are set on not using Zpool or any of the other pools MPM provides, just give it some random wallet address (if you don't want to give it yours), but keep in mind that if you decide to mine to any other pools than MPH you will start mining to this address, so you will have to change it to an address you have control over if you change your mind.

**Comment by UselessGuru** [comment]
> I had to go to the latest release, because the older versions (including the beta) constantly gave a Europe miningpoolhub connection error (like it was connecting to an older URL)

The 'offical' release is really old and has a lot of stuff that is outdated or now defunct.
That is why I am pushung Aaron (he's the owner of the MPM repo) to create a new release ;-). 

> And why can't I check out miningpoolhub what my worker(s) are exactly doing in a global view rather than going to each pool and check out the workers there?

Valid point, but not something MPM can do anything about it. Please redirect this issue to the MiningPoolHub crew.

> According to that, I mined at least a bit of BTC today. But haven't received anything on my wallet thus far. 

From what I can see has MPM not been able to gather valid hash rate information from the miner.
I recommend:
1. enable the miner windows (parameter '-ShowMinerWindow'),
2. enable the snaketail viewer. 
This will give you much better insight :-)

**Comment by UselessGuru** [comment]
>  As far as MPM asking for a wallet when only mining to MiningPoolHub, I'm sure UselessGuru can fix this in no time.

It should not ask 
- for the wallet if a user name is configured
 or 
- for the username if a wallet is configured.

Only ONE config item is required.
