### ISSUE TITLE
Version 3.4.2 waiting for release

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2348]
The master branch has been updated with all the latest changes.

https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

Changelog:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/ChangeLog.txt

If all goes well I'll make this a release within the next few days.

**Comment by Kettoch** [comment]
Just loaded this and it did not update to t-rex 12.1

**Comment by UselessGuru** [comment]
> did not update to t-rex 12.1

Try again - I fixed the sources...

**Comment by Kettoch** [comment]
Thank you.

**Comment by Kettoch** [comment]
Also i get this a lot....
PS>TerminatingError(Invoke-RestMethod): "A parameter cannot be found that matches parameter name 'MaximumRetryCount'."
This is on my other rig (AMD) though i was getting it on the current one.  The other rig was a fresh configuration of 3.4.2 from the ground up.

**Comment by smarcello** [comment]
Mine system on 3.4.2 is getting:
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At F:\MINE\MultiPoolMiner\MultiPoolMiner.ps1:933 char:130
+ ... pare-Object ($_.Combination | Select-Object -ExpandProperty DeviceNam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

**Comment by UselessGuru** [comment]
> PS>TerminatingError(Invoke-RestMethod): "A parameter cannot be found that matches parameter name 'MaximumRetryCount'."

What miners are running when you are seeing these messages?

**Comment by UselessGuru** [comment]
> P.S. did you ever figure out the crashing that was occurring when miner windows were hidden?

Not yet.

**Comment by Kettoch** [comment]
> PS>TerminatingError(Invoke-RestMethod): "A parameter cannot be found that matches parameter name 'MaximumRetryCount'."
> 
> What miners are running when you are seeing these messages?

This was because I was not on the correct Pwsh.  I was on 6.0.2 not 6.2

**Comment by Kettoch** [comment]
> P.S. did you ever figure out the crashing that was occurring when miner windows were hidden?
> 
> Not yet.
> Edit: Yes, I did find the cause. All miners that create separate config files are affected. I'll upload a fix soon.
> As a temporary workaround I recommend to enable the miner windows (which should be the default IMHO) by adding ' -ShowMinerWindow' to the start files.

I agree with the default but it is nice to go back and look at the logs of the miners when there are stability issues.  Can you have windows AND logs?

**Comment by UselessGuru** [comment]
> Can you have windows AND logs?

No, not in the current code base. But I am sure it can be added in a later version.

**Comment by UselessGuru** [comment]
> This was because I was not on the correct Pwsh. I was on 6.0.2 not 6.2

Thank you for reporting - Then I'll also have to change something in the code. I thought that 'MaximumRetryCount' was supported beginning with 6.0.0

**Comment by UselessGuru** [comment]
To be continued in
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2350
