### ISSUE TITLE
Multi GPU Type miner collision

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2349]
I have two cards in my AMD rig.
Hawaii4GB ( a 290X ) PCI ID 6
Ellesmere8GB ( a 580x ) PCI ID 0

What I get a lot of are Cross device mining or two devices trying to min the same one.
Trying to fix them, i have done the following.  I have tried isolating them and using the mapping.

The hwinfo part is to show from that side what I am calling them all the way through.

`  "ExcludeDeviceName": "GPU#00",
  "DevicePciOrderMapping": {
    "GPU#00": "1",
    "GPU#01": "6"
  },
  "HWiNFO64_SensorMapping": {
    "CPU#00": "CPU Power CPU#00",
    "GPU#00": "GPU Chip Power 580 GPU#00",
    "GPU#01": "GPU Chip Power 290 GPU#01"
  },
`
I am at a loss as to how to configure this so the miners will stop colliding.  Every time it does, I get a driver restart (for obvious reasons).

**Comment by Kettoch** [comment]
Oh and interestingly enough, one is being referred to as an "AMD Radeon 290" and the other as a "Radeon 580X"  and are being listed alphabetically as device 0 and 1. when the PCI order is backwards from that.

This would seem silly, but it is almost like I should take them both out and swap their slots.

**Comment by UselessGuru** [comment]
> What I get a lot of are Cross device mining or two devices trying to min the same one.
Trying to fix them, i have done the following. I have tried isolating them and using the mapping.

This may happen if the device ID reported by OpenCL idoes not match the device order by PCI bus ID.

Try remapping your devices with DevicePciOrderMapping (see readme).
Unfortunately there is  no way to automate this proces (at least not for now)
