### ISSUE TITLE
New nicehash platform

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2352]
info: https://www.nicehash.com/news/new-nicehash-platform-now-live-updates

people should register to new platform,
also api endpoints change:  stratum+tcp://ALGO.LOCATION-new.nicehash.com:PORT

old platform was btc wallet only,

new platform is BTC/LTC/ETX/XRP/BCH AND ZEC

**Comment by UselessGuru** [comment]
Thanks - I am already working on it. Will you be using anything else than BTC? I need someone to test ;-)

**Comment by m-bosch** [comment]
Many of the pools i use LTC, so if i can help in one way or another let me know.

**Comment by UselessGuru** [comment]
@m-bosch 

As far as I can see are all mining payouts still in BTC, you can just have other wallets for trading?P
Or did I miss something?

**Comment by m-bosch** [comment]
hi @UselessGuru i am making the same conclusion, so i think only a parameter for `newNicehashPlatofrm: true` would be enough to switch the api endpoints right. I have noticed that the region has other urls, but i dont know how that was on the old platform

**Comment by UselessGuru** [comment]
@m-bosch 

> think only a parameter for newNicehashPlatofrm: 

Try attached files. They work only you keep mining with the same BTC address on both platforms.

The'll use the new v2 API for the pricing information.
Balances will be listed as OldNicehash & Nicehash (new platform)

[NewNicehash.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3396805/NewNicehash.zip)

**Comment by m-bosch** [comment]
When You register to the new platform You get a new BTC address for the new platform. I dont know If You Can use the OLD address on the new platform

**Comment by UselessGuru** [comment]
> I dont know If You Can use the OLD address on the new platform

You can, I know because I get balances on both platforms, but I never did anything regarding BTC wallet on the new one.

**Comment by UselessGuru** [comment]
NH v2 is implemented in Version 3.4.5:

https://github.com/UselessGuru/MultiPoolMiner/releases/tag/3.4.5
