### ISSUE TITLE
Error in Config.txt not

### ISSUE THREAD

**Issue by mato777** [MultiPoolMiner/MultiPoolMiner#2353]
I made a git clone of master (over a clean folder)
I run the start.bat with my BTC address and my user in mininpoolhub.  
I get an error that my config.txt file is not valid and version problem.  
I've never touched the default config.txt.
My rig does not start mining.

**Comment by UselessGuru** [comment]
Could be this:

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2351#issuecomment-509907266

**Comment by UselessGuru** [comment]
To be continued here:

https://github.com/UselessGuru/MultiPoolMiner/releases/tag/3.4.5
