### ISSUE TITLE
Version 3.4.5 is released

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2356]
# MultiPoolMiner Version 3.4.5 is released

Download link:
https://github.com/MultiPoolMiner/MultiPoolMiner/archive/3.4.5.zip

#### Core changes
- Added config parameter '-DisableEstimateCorrection'; reduce the algo price by a correction factor (actual_last24h / estimate_last24h) to counter pool overestimated prices
- Changed funtion Get-EquihasPers to Get-AlgoCoinPers & EquihashPers.txt to AlgoCoinPers.txt
- List pool names being queried for pricing information
- Use only configured devices when API becomes available
- Workround when module 'ThreadJob' cannot be loaded: use normal 'Start-Job'

#### Miner changes
- Added AMD-SgminerFancyIX_v0.6.0.0; support for Allium, Argon2Ddyn, Lyra2v3, Lyra2z, Lyra2zz, MTP, Phi2, X22i & X25x
- Added NVIDIA-CcminerBMW512; support for BMW512
- Fixed AMD-SgminerFancyIX_v0.6.0.0; algorithm Argon2d was broken
- Fixed AMD_NVIDIA-PhoenixminerEthash_v4.2c, does not work with AMD driver versions 2841.5, 2841.19 or 2906.8
- Fixed AMD-TeamRed_v0.5.5; enabled detection of failed GPUs
- Fixed NVIDIA-CcminerMTP_v1.1.23; requires CUDA 10.1.00 or higher
- Fixed WarmupTime for Sgminer*; allow up to 90 seconds to build binaries
- Updated AMD_CPU_NVIDIA-NanoMiner_v1.5.2; support for Cuckarood29 and RandomHash (CPU only), added Ethash binaries for AMD Radeon RX 5700 and AMD Radeon RX 5700 XT cards
- Updated AMD_NVIDIA-BMiner_v15.7.2; support for Cuckarood29
- Updated AMD_NVIDIA-Gminer_v1.52; support for Cuckarood29
- Updated AMD_NVIDIA-lolMiner_v0.85; removed 'Equihash' from its name 'cause it does non Equihash algos as well
- Updated AMD-SRBMinerCryptonight_v1.9.1
- Updated AMD-WildRig_v0.18.0; suppport for GltGlobalHash
- Updated CPU-Jayddee_v3.9.6.1; crash mining Hodl with aes-sse42
- Updated NVIDIA-CcminerKlausT_v8.25
- Updated NVIDIA-CcminerZenemy_v2.1
- Updated NVIDIA-NBMiner_v23.3; support for Cuckarood29
- Updated NVIDIA-TTMiner_v2.2.6; support for Cuckarood29

#### Pool changes
- Fixed BlockMasters; did not return any objects
- Implement workaround for Zpool(Coins) anti-DDoS protect (pool allows only 6 API calls per minute)
- Nicehash: Use API v2 (new Nicehash)
- Support for new config parameter '-DisableEstimateCorrection'

#### Balances changes
- Implement workaround for Zpool(Coins) anti-DDoS protect (pool allows only 6 API calls per minute)
- Nicehash: Request API v1 (old Nicehash) & v2 (Nicehash)

**Comment by m-bosch** [comment]
Thanks again for the update, installing  and benchmarking the new miners as we speak.

To bad to hear you cant continue here. internal issues in the team?

for the nacehash, is it better to set the new btc address according to new nicehash or better to keep the old address (that i cant see in new nicehash).

**Comment by aaronsace** [comment]
@UselessGuru I have moved everything over to the branch called 'dev'. You should have full access. Let me know if you have any issues.

**Comment by aaronsace** [comment]
Also, please check if you still have access to make releases.

**Comment by UselessGuru** [comment]
> So you push to 'dev' then submit a pull request to 'master' once ready.

Does not work. All PRs need approvals, I can no longer override it.

> Also, please check if you still have access to make releases.

That still seems to work.

**Comment by aaronsace** [comment]
Now that GitHub have released the new 'maintainer' privilege, I no longer need to hand out 'admin' rights. It should only remove the 'override' feature on pull requests so they get they go through the proper approval. 

Submit pulls from 'dev' to 'master' for feature additions. 
Submit pulls from temporary branches to fix bugs or update miner binaries.

**Comment by UselessGuru** [comment]
> should only remove the 'override' feature on pull requests 

Which it did. I can no longer override.

Unless you find a way to to let me update the master directly without approval I will not maintain code here. Waiting for your approvals does not make sense to me, as it slows everything down.

**Comment by aaronsace** [comment]
I’m a bit shocked, I certainly don't want to see you go as you have been great here. 
I have lots of commits to make but it’s hard not to override everything without the master being updated in an orderly fashion. I’m quite sure the users are fine to wait for me or another member of MultiPoolMiner to approve the pull requests. 
You can still make releases directly from the 'dev' branch for fast builds and should make it a lot easier for me and others to work on this. 
Do you understand what I’m trying to do? You should find the ‘dev’ branch quite useful for pushing daily commits and weekly releases.

**Comment by UselessGuru** [comment]
> Do you understand what I’m trying to do? You should find the ‘dev’ branch quite useful for pushing daily commits and weekly releases.

OK, I see now. I'll just keep updating the dev channel then.
I just created a 3.4.5 release from the dev channel.

**Comment by UselessGuru** [comment]
Superseded by https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2363
