### ISSUE TITLE
Limit resources?

### ISSUE THREAD

**Issue by Lohanness** [MultiPoolMiner/MultiPoolMiner#2360]
Would love to run this on the PC I work from, but I would need to limit the usage to around 50% of the total resources on my PC. Is there any way to do this currently?

Thanks!

**Comment by UselessGuru** [comment]
> Would love to run this on the PC I work from, but I would need to limit the usage to around 50% of the total resources on my PC. Is there any way to do this currently?

What resources? CPU?

**Comment by Lohanness** [comment]
Sorry for not clarifying, but I am trying to make multipoolminer use only 50% of my CPU and 50% of my GPU, to free up resources for stuff for browsing the web, checking email, etc.

**Comment by UselessGuru** [comment]
> Sorry for not clarifying, but I am trying to make multipoolminer use only 50% of my CPU and 50% of my GPU, to free up resources for stuff like browsing the web, checking email, etc.

No, there is no way to do this.

I use my everyday computer for mining and 'normal' stuff simultaneously without problems (except for the odd miner crashing the graphics driver).
