### ISSUE TITLE
with 3.4.6

### ISSUE THREAD

**Issue by smarcello** [MultiPoolMiner/MultiPoolMiner#2362]
getting:

The term 'Get-MinerVersion' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
+ CategoryInfo          : ObjectNotFound: (Get-MinerVersion:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
+ PSComputerName        : localhost

**Comment by UselessGuru** [comment]
> The term 'Get-MinerVersion' is not recognized as the name of a cmdlet, function, script file, or operable program.

Did you install the new version to a new directory? You cannot keep existing miner files from older versions.
I double checked, and I cannot find any reference to this function anywhere  in the code.

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thanks, in fact I overwritten. Will move to a new directory.                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 28 luglio 2019 09:59A: MultiPoolMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; author@noreply.github.comOggetto: Re: [MultiPoolMiner/MultiPoolMiner] with 3.4.6 (#2362)  
The term 'Get-MinerVersion' is not recognized as the name of a cmdlet, function, script file, or operable program.

Did you install the new version to a new directory? You cannot keep existing miner files from older versions.
I double checked, and I cannot find any reference to this function anywhere  in the code.
