### ISSUE TITLE
NuGet prompt showing up every time MPM is launched

### ISSUE THREAD

**Issue by Lohanness** [MultiPoolMiner/MultiPoolMiner#2368]
Every time I launch multipoolminer, I have to accept the nuget download again and again. This is not a huge issue, but a minor inconvenience as I just want to click and leave my pc. Anyone know a fix for this?

**Comment by aaronsace** [comment]
It will be removed on future releases. This is the line to take out: 
`Install-Module ThreadJob -Scope CurrentUser -SkipPublisherCheck -Force -ErrorAction Stop`
