### ISSUE TITLE
MultiPoolMiner Version 3.5.0a is released

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2373]
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/3.5.0a

**Comment by smarcello** [comment]
3.5.0.a why does it still look for PhiPhiPool ??
2019-08-15 20:20:02 VERBOSE: Cannot get balance on pool (PhiPhiPool) - no wallet address specified.

**Comment by UselessGuru** [comment]
> 3.5.0.a why does it still look for PhiPhiPool ??

Because you still may have money there. ;-)
Just remove the the file in the 'Balances' folder...

**Comment by UselessGuru** [comment]
To be continued in https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2375
