### ISSUE TITLE
VERBOSE: Pool Balance API (MiningPoolHub) has failed - no API key specified

### ISSUE THREAD

**Issue by Rlorentzen** [MultiPoolMiner/MultiPoolMiner#2376]
Each Rig is nunning Nvidia cards with MiningPoolHub, Zpool, and Nicehash.  How do I fix this, and which of the standard files do I fix it in?

**Comment by UselessGuru** [comment]
You need to add your MPH API key to either the start file or the config file.

I will add the following information to the README file.

**-API_Key**
Required only if you are mining at MiningPoolHub. Adding this parameter / key pair allows MPM to gather the balances at the pool. 
The API_Key can be found in the MiningPoolHub Account detail page.

**Comment by smarcello** [comment]
-API_Key
Required only if you are mining at MiningPoolHub. Adding this parameter / key pair allows MPM to gather the balances at the pool.

What about NiceHash? They have too the same parameters.

**Comment by UselessGuru** [comment]
> What about NiceHash? They have too the same parameters.

Not needed.
Look at the paramtes for each pool in http://localhost:3999/runningconfig.html

BTW: Aaronsace is changing the code (https://github.com/MultiPoolMiner/MultiPoolMiner/commit/202a7b56f8a6f2ebff0c6fad01864cec0d86a7d5#diff-69b5e62237d5f951ca1ac096869d0234R337) so that ALL pools will always contain ALL parameters. Something which I feel is more confusing than necessary. :-)

**Comment by Rlorentzen** [comment]
> You need to add your MPH API key to either the start file or the config file.
> 
> I will add the following information to the README file.
> 
> **-API_Key**
> Required only if you are mining at MiningPoolHub. Adding this parameter / key pair allows MPM to gather the balances at the pool.
> The API_Key can be found in the MiningPoolHub Account detail page.

I am just not sure where in the start file or the config file to put the MPH API Key,  usually there is a field I change that was once ArronSace's info

**Comment by UselessGuru** [comment]
Either add the parameter to the line that looks like this in your start file:

`set "command=& .\multipoolminer.ps1 -Wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -UserName aaronsace -WorkerName multipoolminer -Region europe -Currency btc,usd,eur -DeviceName amd,nvidia,cpu -PoolName miningpoolhub,miningpoolhubcoins -Donate 24 -Watchdog -MinerStatusURL https://multipoolminer.io/monitor/miner.php -SwitchingPrevention 2"`

e.g.:

`set "command=& .\multipoolminer.ps1 -Wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -UserName aaronsace -WorkerName multipoolminer -Region europe -Currency btc,usd,eur -DeviceName amd,nvidia,cpu -PoolName miningpoolhub,miningpoolhubcoins -Donate 24 -Watchdog -MinerStatusURL https://multipoolminer.io/monitor/miner.php -SwitchingPrevention 2 -API_KEY 28328accdd4306c631a881bd8130f0d258a94b0e3356ae42eef7gga123773d018c98"`

or edit your config file (nomally config.txt).

Change it from this:

`  "API_Key": "$API_Key",  `

to something like this

`  "API_Key": "28328accdd4306c631a881bd8130f0d258a94b0e3356ae42eef7gga123773d018c98",`

Both options are fine.

**Comment by Domaily** [comment]
from where do I get the API key
