### ISSUE TITLE
No pools available when mining MiningPoolHub

### ISSUE THREAD

**Issue by aarondpriest** [MultiPoolMiner/MultiPoolMiner#2405]
I'm getting "WARNING: no pools available" when I use -PoolName miningpoolhub. I've had it working before, but fired it up tonight after updating to 3.5.2 and it just isn't working for me. Down for anyone else?

**Comment by sionprawn** [comment]
Alternativly in the "Start-MiningPoolHub.bat" file change the "PoolName" switch to "-miningpoolhub-Algo", if that BAT file is what you use to start your mining.

**Comment by smarcello** [comment]
hey,
getting: 2019-09-21 10:00:23 WARNING: Cannot determine balance for currency (unknown) - cannot convert some balances to BTC or other currencies. 
Above, MPM shows zero, in confront with other miners:
MultiPoolMiner 0,00000 ±0% (0,00000-0,00000) 0,00000 ±0% (0,00000-0,00000) 0,00000 ±0% (0,00000-0,00000)
-               ±0% (0,00000-)                ±0% (0,00000-)                ±0% (0,00000-)

**Comment by sionprawn** [comment]
Hello,
Yea, I get that, but would raise it as a seperate issue.  Just so these guys can close one at a time.

**Comment by imrecsoka** [comment]
This is awesome , so now what should we or should we not rename?
I mean cant this just be what it should be in the original file we download?

**Comment by sionprawn** [comment]
Hello,
This has been raised as an issue, so presumably the coders solve them, when they've solved a bunch, they bring out a new 5.x.xxxxx version and close the issues they've solved.  

I personally have just changed the "Pool name" in the "Start-MiningPoolHub.bat" file switch to "miningpoolhub-Algo", as it's the only one I've ever used.

It seems to be the only issue on this particular subject if you just use that BAT file.

**Comment by UselessGuru** [comment]
See here:

https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2410

**Comment by UselessGuru** [comment]
> Above, MPM shows zero, in confront with other miners:
MultiPoolMiner 0,00000 ±0% (0,00000-0,00000) 0,00000 ±0% (0,00000-0,00000) 0,00000 ±0% (0,00000-0,00000)

Problem seen. I am working on it.
