### ISSUE TITLE
No Mining Devices Found

### ISSUE THREAD

**Issue by imrecsoka** [MultiPoolMiner/MultiPoolMiner#2407]
This is a portion of my command line in the start.bat file

......"-DeviceName amd -PoolName miningpoolhub-coin -Algorithm equihash"........

If i insert nvidia like so:

......"-DeviceName amd,nvidia -PoolName miningpoolhub-coin -Algorithm equihash"........
I get message "no mining devices found". 
I have an nvidia card in my 1 pci-e slot (screen attached) and an amd card in my cpi-e slot 2

JUST TO CONFIRM :- if it is now called miningpoolhub-coin and not miningpoolhub ?
I notice the command line says miningpoolhub-coin not sure why.
I have been away from mining for 6 months or more.

**Comment by sionprawn** [comment]
Hello,
As far as I'm aware (and don't quote me on this) using the -PoolName mininpoolhub-coin is if you only want to mine a specific coin, and if that's what you're doing then "mininpoolhub-coin" is correct, but if you want to use the Auto profit switching function then I'd use "mininpoolhub-Algo".  They've added -coin, -algo to a lot of file names.

Also, Equihas seems to keep splitting, there are now several different Algos already, and it seems to have done so again.  Quote form top of login page;

" - Zclassic hardforked again to fix the high difficulty issue. Now it's much easier to mine than before.
  Please download new miner and mine with new algo and port. (Previous 20575 equihash port is routed to mine Zencash instead)"

This might be why it can't find a miner.

In the "Algorithms.txt" file you'll find lots of new names for the split coins and they're new algos. Check them by selecting the Coin in the list of coins on the MPH website.

Though as to how you download a new minger and integrate it into the MPH system, I've never quite figured out yet.  My guess is, they might add the appropriate miner in some future release.

**Comment by imrecsoka** [comment]
God it's confusing.
I used to edit the start.bat file put my username and run it.
I am happy to mine against miningpoolhub only who h is fine. So on this case I don't know what I should be doing.
It sounds like a hack to have rename files or entries in files.
I am happy to do this search replace and massive renames but I need to know what exactly.
It takes ages to run the benchmarks as it is
I am happy to donate 1 hour to Aaron don't rest care so long as this PowerShell coded tool makes it all easier for me.
As for further steps like allowing mining on nicehash etc... It looks interesting also.
Any suggestions for me to start with what I have , version of mpm and what to edit or change?
I have a setup of 1 and and 1 Nvidia at the moment.
No integration APU stuff
I usually have 1 flavour of cards on the case but since I have relocated and trying to mine again I thought I would just try have 1 Nvidia and 1 and GPU on the board.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sionprawn** [comment]
Yea, it is confusing, especially for a none coder like me, but slowly figuring things out.  

Anyway, I’ve attached a TXT file I use (I always leave the original alone, so I can remember what I’ve changed, hence the “-copy” at the end).  Just change the .TXT to .BAT, pop it in the main folder, Short-Cut it to your Desktop and should be fine (just change any xxx stuff to what's yours).  

This is for my Nvidia based machine, but it doesn’t hurt to leave the “amd” in the script.

Also I’ve put the Algo Equihash1927 ready in the hope they’ll include a new miner for ZClassic, in the main download .zip file, because there isn’t one currently and I certainly don’t know how to download and integrate one into the “MinersLegacy” folder.

I think they've got a fair few things on their hands to do.
Good luck

[Start-MiningPoolHub - copy.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3639698/Start-MiningPoolHub.-.copy.txt)

**Comment by UselessGuru** [comment]
> Also I’ve put the Algo Equihash1927 ready in the hope they’ll include a new miner for ZClassic ... because there isn’t one currently

Yes, there are:

![image](https://user-images.githubusercontent.com/30080938/65393761-2e60de80-dd85-11e9-884a-b0f0730766ad.png)

The problem is a missing entry in Algorithms.txt to get Equihash1927 to work with MPH. Try this:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/484ee9868c3351841f88b7e4865f83e5987b774f/Algorithms.txt

**Comment by sionprawn** [comment]
Cheers for your reply,

I got that Algo to work on it's own - LolMiner-v0.8.8, but the main MPM .zip file only includes lolMiner-v0.8.7, not V...8.

I created a lolMiner-v0.8.8.psi, which downloaded the correct LOLMinere and I configured it to the correct port in the BIN folder.  

It worked fine just own if I used the "C:\MultiPoolMiner\MultiPoolMiner-3.5.2\Bin\lolMiner-v0.8.8\lolMiner.exe" But when I tired it with Alog switching it kept changing the Port.  My wiled guess, is it over-wrote the port by getting an old one from the Website.

**Comment by sionprawn** [comment]
Also, Gminer V1.65 is not included in the MPM main .zip file.  I had tried that one as well with the same results as the above.

**Comment by UselessGuru** [comment]
> I created a lolMiner-v0.8.8.psi, which downloaded the correct LOLMinere and I configured it to the correct port in the BIN folder.

You do not need to manually download or install anything but the MPM zip file.
MPM will automagically download all required miner binaries.

> But when I tired it with Alog switching it kept changing the Port
The port is defined by the pool, not the miner.

>  I copied and over-wrote the Algorithms.txt folder back to it's original state
You should use the new FILE as linked.

> I got that Algo to work on it's own - LolMiner-v0.8.8, but the main MPM .zip file only includes lolMiner-v0.8.7, not V...8.
v.0.8.8 is in the code wating to be released:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/MinersLegacy/lolMiner-v0.8.8.ps1

> Gminer V1.65 is not included in the MPM main .zip file
True, that is another pending PR:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/d3822b32e236afee392951622d5789d15dc17ee0/MinersLegacy/Gminer-v1.65.ps1

To update the miners just download the new files and replace the similar named files in the MinersLegacy folder.

**Comment by imrecsoka** [comment]
Guys please help me here, I'm really confused , this thread started off questioning a mining device not found and now we talking about lolminer I don't know what to do here... I'm happy to start from fresh.... Delete my files and download the zip again.... I don't know whether to use the attached file here ....must I change my setup and just put 2 Nvidia cardda or 2 AMD's instead of 1 of each....I'm really just curious to see what software miners actually work here and don't just do nothing. Because I have had a real headache with sgminer against and cards live tried verbose and -T for debug and it tells me just absolutely nothing except that I successfully connect to a pool and then it just doesn't start fkijg mining. anyways for the good part though I've had good experience with megamijer miningpoolhub and nicehash.
I wish to now try resume what I have stopped 8 months ago more or less.
Forgive the bad Grammer I used to cell phone for this .
So again I'm just trying to determine which miners actually work and use the benefit of automatic profit switching.
I just can't stand it when there are errors everywhere and I've just downloaded and run the pack for the first time .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by UselessGuru** [comment]
> questioning a mining device not found

Check your GPU driver installation. Proper OpenCL config is essential.
You can use GPU-Z to verify the OpenCL status for each card:

![image](https://user-images.githubusercontent.com/30080938/65438704-3e7cca80-de26-11e9-9789-24f4a423b72e.png)

**Comment by imrecsoka** [comment]
HI, okay well this is the first time and  you ar the first person to ever ask me to check that, so thank you.
I can confirm that i have no issues minning Xevan using SGminer and also I have Mined using an older nihashminer back in the day , cryptonight - i think it was - i really wish i do remember exactly ... buti think it was.... and anyways that SGminer that nicehash miner at the time used for Cryptonight - i belive it was monero... anyways that worked. I can also confirm that i have mined Skein algo for coin Digibyte - but this is where my mystery and hating SGMiner more came from....
It connected fine to a pool and started mining...
It connected fine to a pool and u can see it is checking something with block height or whatever.... as verbose as i could go, but it quit and gio back to the prompt.
So example when the benches run for mpm and nicehash, i can see its trying to check the hashrate but it does not get that far... caue i bet u SGMiner is not even statrting to mine, 
really strange one.
I tried (previously ) , on windows 7 and 10 and single card and fresh drivers using driver display removal tool.

I have always been meaning to ask somebody to maybe hop on and check my machine.

anyways  *sigh*



Anyways here are the screen shots i want to share with you. I have also left msi afterburner stuff as default:
![image](https://user-images.githubusercontent.com/25494601/65439895-7e5da500-de5a-11e9-99f9-03ab90e37da4.png)

![image](https://user-images.githubusercontent.com/25494601/65439552-eeb7f680-de59-11e9-818f-5c2e8bb926e1.png)

I am using an AMD board MSI G43 A88X with an AMD CPU only X4 860K  10GB ram which i believe should be enough.

But of course Windows 10 which i cant stand:

Microsoft Windows [Version 10.0.17134.1006]
(c) 2018 Microsoft Corporation. All rights reserved.


![image](https://user-images.githubusercontent.com/25494601/65439853-6554f400-de5a-11e9-9c3c-4a873fa2c2ca.png)

**Comment by UselessGuru** [comment]
@imrecsoka 

Please fix your GPU driver installation. OpenCL is not available for NVIDIA as your screen shot shows.

Then start MPM again, wait for the web GUI to come up, then post the output of 

http://localhost:3999/devices

**Comment by imrecsoka** [comment]
Silly question, do i just remove and re-install the latest driver for nvidia?
I also didnt know this clearly, but i thought opencl was for amd only.

**Comment by UselessGuru** [comment]
See here:

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2339#issuecomment-495994112

**Comment by UselessGuru** [comment]
> as for starting mpm - please tell me what i should do ...
brand new download? and edit the start.bat remove CPU only keep nvidia,amd and update my username . worker .....not sure if i need to include a btc address.
I used to mine only miningpoolhub before....
now its confussing with miningpoolhub coin and what not i dont really know

See here:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2410
