### ISSUE TITLE
CPU mining does not work in new release

### ISSUE THREAD

**Issue by fonyo** [MultiPoolMiner/MultiPoolMiner#241]
CPU: AMD Phenom II X6 1100t Black Edition @4GHz || MPM v2.5.3.2
I see newer version of various cpu miner software are being used but even though my processor supports  SSE/SSE2/SSE3/SSE4a, none of the SSE2 miner variants would work. They launch fine but close after receiving stratum job. Not that I really want to mine with my CPU but was just testing the new release and wanted to point it out here.

_EDIT: MPM v2.5.1.2-2.5.2 versions work just fine with tpruvot's cpuminer-multi v1.3_

**Comment by somidax** [comment]
I am having same issue mostly with xmr stak application, I hope he can fix
it; cheers

**Comment by fonyo** [comment]
I think it is related to the new miners not supporting or recognising older or some processors. Same thing happened to the nicehash miner when they updated their miners. The new miners seem to be very picky what they considers to be SSE2 support. Including the older generation of miner software with MPM would possibly be a short-term solution (at least for now).

**Comment by scaras** [comment]
works fine with i7 6700k 

didn't test newest release on the fx 8350 system (with 1050 ti)

**Comment by grantemsley** [comment]
Closing outdated issue.  If this is still a problem (and there currently isn't an open issue for it) please open a new one.
