### ISSUE TITLE
Not critical...

### ISSUE THREAD

**Issue by smarcello** [MultiPoolMiner/MultiPoolMiner#2418]
WARNING: Cannot determine balance for currency (unknown) - cannot convert some balances to BTC or other currencies. 

have no idea why is that happening. Thanks !

**Comment by UselessGuru** [comment]
> WARNING: Cannot determine balance for currency (unknown)

Do you get this all the time?
This usually happens when MPM cannot retrieve all exchange rates from https://min-api.cryptocompare.com/data/pricemulti

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Very often I got this. Thanks!                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 28 settembre 2019 10:36A: MultiPoolMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; author@noreply.github.comOggetto: Re: [MultiPoolMiner/MultiPoolMiner] Not critical... (#2418)  
WARNING: Cannot determine balance for currency (unknown)

Do you get this all the time?
This usually happens when MPM cannot retrieve all exchange rates from https://min-api.cryptocompare.com/data/pricemulti

**Comment by UselessGuru** [comment]
@smarcello 


Does the attached file fix your issue?
[MiningPoolHub.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3666551/MiningPoolHub.zip)

**Comment by smarcello** [comment]
@UselessGuru - yes the new MiningPoolHub.zip seems to work, the warning did not repeat!
Thanks !

**Comment by smarcello** [comment]
Hello,
Still big differences between updates of the balances of various pools: BlockMasters (BTC) 4 hours, MiningPoolHub (BSTY) 3 minutes, MiningPoolHub (BTG) 4 min., MiningPoolHub (ETC) 23 min., MiningPoolHub (ETH) 4 min., MiningPoolHub (LTC) 15 min., MiningPoolHub (MAX) 27 min., MiningPoolHub (VTC) 25 min., MiningPoolHub (XMR) 20 min., ZCL 15 min, MiningPoolHub (ZEC) 7 min, NicehashExternal (BTC) 5 min, NLPool (BTC) 5 min, Ravenminer (RVN) 30 min, ZergPool (DASH) 27 min, Zpool (LTC) 3 hours ago....

**Comment by UselessGuru** [comment]
> Still big differences between updates of the balances of various pools

Nothing to worry. MPM 3.5.2 by default only updates balances every 15 minutes or when new pool data got detected.
It does this to limit the number of API calls

**Comment by UselessGuru** [comment]
[Fixed with 3.5.3](https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/v3.5.3)
