### ISSUE TITLE
adding "mininum profit" threshold?

### ISSUE THREAD

**Issue by aelias27** [MultiPoolMiner/MultiPoolMiner#242]
Hi,
Seeing the recent dip in crypto, would it be possible to implement a threshold in the start.bat file under which MPM would stop and wait patiently for profitability to rise again?
I don't have enough knowledge to add it myself :/

**Comment by UselessGuru** [comment]
I will tackle that. Will require an optional config param

**Comment by UselessGuru** [comment]
Implemented in 3.3.0 (currently in  Beta)

https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/Beta3.3
