### ISSUE TITLE
Support for Equihash-ZCL?

### ISSUE THREAD

**Issue by IronCraftMan** [MultiPoolMiner/MultiPoolMiner#2420]
I noticed that MultiPoolMiner won't mine Equihash-ZCL for miningpoolhub (https://zclassic.miningpoolhub.com/). It seems like all 3 miners from MPH are also on MPM, they just don't mine the right algo.

**Comment by UselessGuru** [comment]
This is fixed in https://github.com/MultiPoolMiner/MultiPoolMiner/commit/484ee9868c3351841f88b7e4865f83e5987b774f
