### ISSUE TITLE
Support for x16rv2?

### ISSUE THREAD

**Issue by IronCraftMan** [MultiPoolMiner/MultiPoolMiner#2427]
According to https://ravencoin.miningpoolhub.com/, the only supported miner for nvidia cards is t-rex miner, and MPM doesn't seem to have it. Will this be added in the future?

**Comment by UselessGuru** [comment]
> Will this be added in the future?

Look here:
https://github.com/MultiPoolMiner/MultiPoolMiner/tree/dev/MinersLegacy

Or here:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2425
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2416
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2413
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2428
