### ISSUE TITLE
Errors in ResetPowerUsage.bat

### ISSUE THREAD

**Issue by tarvcode** [MultiPoolMiner/MultiPoolMiner#2429]
Just noticed ResetPowerUsage.bat isn't working.

Type-o in the variable name in the if statement.
`IF /I "%powerusagereset= %"=="Y" (`
vs
`IF /I "%powerusagereset%"=="Y" (`

Having "&" in echo command causes error.
`ECHO Success. You need to measure the power consumption for all required miners & algorithms to continue using MultiPoolMiner.`
vs
`	ECHO Success. You need to measure the power consumption for all required miners and algorithms to continue using MultiPoolMiner.`

**Comment by UselessGuru** [comment]
Will be fixed in 3.5.3:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2381/commits/6eaf0f92e4118b69f099193886e4849573709d56
