### ISSUE TITLE
Donate issue

### ISSUE THREAD

**Issue by sionprawn** [MultiPoolMiner/MultiPoolMiner#2432]
Hello,

I have Donate turned on, on both the Website and the 'Start-MPH" BAT file.

Whenever the donate reaches it's time to donate to MPM, **and** if it considers Lyrera2v3 as the best donate algo, (to Aaronsace's BTC address), it just goes into a loop, and does nothing until I notice that my machine is making no noise.

It does this for hours, or as I say above, until I realize my machine is making no noise.

Also, I seem to get an attempted connection to an un-known (at least to me) website (screen-shot attached)

![Donate](https://user-images.githubusercontent.com/49675617/66781532-70d09380-eecb-11e9-846d-5c2e9b6801c4.PNG)

![Donate 2](https://user-images.githubusercontent.com/49675617/66781551-775f0b00-eecb-11e9-83d0-f5c6f17e2127.PNG)

**Comment by UselessGuru** [comment]
>  I seem to get an attempted connection to an un-known (at least to me) 

The URL in the screen shot has nothing to do with MPM. I am puzzled.

> and if it considers Lyrera2v3 as the best

When donating MPM uses ALL available pools, also the ones you have not explicitly configured/excluded. MPM starts benchmarking Lyra2V3 to Aaronsace's address because it is an 'new' algorithm (from one of the other pools enabled during donation) which has not been benchmarked.

> it just goes into a loop, and does nothing

As for the stalling please replace the pools folder with this one:
[Pools.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3727492/Pools.zip)

Please let me know if this helps - thank you!

**Comment by sionprawn** [comment]
Thanks, I will start testing now.

I will look into that Web address and see if I can find the cause.

**Comment by sionprawn** [comment]
Hello, thanks I tired the test "Pool.zip"

At 1st I thought is had worked due to 6.jpg, but then realized it wasn't, please see other Jpegs.

I've attached the Jpegs + Logs I did for testing.

![6](https://user-images.githubusercontent.com/49675617/66922332-c1a4d100-f01e-11e9-913f-83add9d790bb.JPG)
![7](https://user-images.githubusercontent.com/49675617/66922333-c1a4d100-f01e-11e9-8636-83932b25e0a6.JPG)
![4](https://user-images.githubusercontent.com/49675617/66922334-c1a4d100-f01e-11e9-8a21-9fae5a5eae6e.jpg)

[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3734438/Logs.zip)

I will be looking into that strange URL later, but got to go out now.  I don't like strange URLs on my PC, so now I know you are unfamiliar with it I will be spending the rest of my time on that.  I don't use that particular PC for anything other than mining and testing + gave it good wipe recently but it had that URL before the wipe as well, so has me even more curious.

**Comment by UselessGuru** [comment]
@sionprawn 

Lyre2RE3 is failing as[ posted here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2421#issuecomment-536410547) already and you will also find the workaround there.
Alternatively you can edit the config file and exclude the Lyra2RE3 algorithm for MiningPoolHub (see readme for details). OR you can remove  the MiningPool hub files altogether.
This is a pool error. MPM cannot really fix it.

**Comment by sionprawn** [comment]
Cheers, no worries, thought it was probably something still to do with the L3 issue, but was worth trying your 'Pools" download suggestion.  Especially when L3 showed up in my 1st Jpeg after trying your Pools suggestion.

I'm in no hurry, just thought more info on a matter is better than less (even if the info is redundant)  

Please feel free to close this, or ping me if I'm the one who has to close it (not much experience on this website).
