### ISSUE TITLE
Progress development

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2437]
Hi there,

I see there are no updates for the last 2months while i assume some miners will have new version etc.

I do see there are 21 PR's....most of them from @UselessGuru. Does @aaronsace need to aprove these PRs?

What is the reason for no new releases?

**Comment by UselessGuru** [comment]
>  What is the reason for no new releases?

@aaronsace  ???
@m-bosch Thank you for asking und keeping your patience! 👍 

> I do see there are 21 PR's....most of them from @UselessGuru. Does @aaronsace need to aprove these PRs?

Unfortunately yes... I wish AaronSace was more active. 👎 
You can either copy / paste the raw file contents of the individual PRs.

Also I'l try to put together a new BETA containing all the changes of the proposed 3.5.3 version that is still pending.

**Comment by m-bosch** [comment]
I see many PRs are done. But when will the new version be released?

**Comment by UselessGuru** [comment]
> I see many PRs are done. But when will the new version be released?

When @aaronsace thinks that its time, there's nothing I can do on my own.

**Comment by m-bosch** [comment]
Maybe its a good time to hand over this repository when the core-maintainer isnt around anymore? Or give @UselessGuru the right he needs for keep it all up to date...

**Comment by tbergeron** [comment]
Agreeing with @m-bosch, at this point it's getting ridiculous having to wait months to get hotfixes. And then we get told by the project owner: update it yourself! That's what we want to do but nobody accepts the PRs! This project needs to switch hands.

Here's a graph showing this project's current state:
![Annotation 2019-11-07 085131](https://user-images.githubusercontent.com/70296/68394433-d1a26300-013b-11ea-8f62-f5d3f09b681e.png)

@UselessGuru has been maintaining the project for so long, if it wasn't for him this project would be **dead**.

/2cents

**Comment by m-bosch** [comment]
@aaronsace its time to take action, in any kind, 

- handover  the project

- being more active in project

- archive this project

-

**Comment by tbergeron** [comment]
If @aaronsace don't want to pass the project at least, there's a few dozen ways it could be improved: better collaboration guidelines, accepting more PR from newcomers, being more pro-active with PRs and issues, having some group chat or forums of any sort, having more project maintainers that have access to repo admin features, cleaning the old issues and milestones and more. 

It's sad because as of right now most people use: NiceHash miner (or shitty clones a-la minergate) OR MPM OR AwesomeMiner. What I'm trying to say is: most options suck! MPM is really the only via option long-term because it is open source and community-driven.

FYI: running the latest `dev` branch with a tweak I mentioned in the PR #2381 seems to work fine.

**Comment by m-bosch** [comment]
I am only running release version to narrow down the bugs that could occur... probably i should change to the dev branch instead indeed.

@aaronsace maybe you should REALLY make a new release after 3.5 months, the dev is now 300commits ahead....

**Comment by mkirov0** [comment]
Reading this thread an idea hit me... I have created a Discord server for MPM if you guys are interested the link is https://discord.gg/wpAq33Q. If @UselessGuru or @aaronsace join I will transfer the admin rights to them.

**Comment by aaronsace** [comment]
If all goes well then the release will be ready this weekend. Once the required info is sent over on the development branch then I will push a fix, wait for someone to tsst, merge the branch then mark a release.

**Comment by m-bosch** [comment]
Did it work out to make a new release?

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/v3.5.3

**Comment by m-bosch** [comment]
Hi @UselessGuru @aaronsace what about some new updates? before it was weekly, now not even monthly?

**Comment by UselessGuru** [comment]
@m-bosch 

Thank you for your comment.

@Aaronsace is completely changing the inner structure of MPM, but I don't know when he will be done and what features he will eventually remove. I just see a lot of 'to be removed' or 'to check' comments in the code.

In the current state the 'dev' branch is utterly broken, and lots of stuff is unfinished and I have no codebase to build on.

So right now for me there is no point in contributing any code changes cause 
Aaronsace might just revert it or the underlying code base is no longer compatible.

**Comment by aaronsace** [comment]
Raise any pull requests to the master branch then I'll merge and release in the new year.

**Comment by UselessGuru** [comment]
> Raise any pull requests

@aaronsace 
As I said there is no point for me to contribute as long as 'dev' is non-working. I have no grounds to build on. 

As of lately I do not have the feeling that my contribution was really of any help. I add features, and your redesign breaks it just days later (e.g. updates to the web gui). To make matters worse I see / suspect you will be removing a lot of great features, e.g. filters like -MinWorkers or -ExcludeCoinName. 

I understand the changes you are making, and they are for the good. But on my end it is frustrating to see lots of working stuff being removed or ignored (e.g. power usage and profitability calculation).

Finish the rebuild and I'll see where I see the need to contribute.

**Comment by aaronsace** [comment]
No worries, I'll start updating the miner links if neither of you raise a pull request before the new year.

**Comment by UselessGuru** [comment]
@aaronsace 

Any set plans on fixing the dev branch and restoring all the great features of the previous versions?
As it stands now this project is dead (from my point of view).

**Comment by aaronsace** [comment]
Master branch has now been updated. I'll check it this afternoon then mark as a release.

**Comment by aaronsace** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/latest

**Comment by aaronsace** [comment]
All miner binaries are now up-to-date as of today and is listed under v3.5.5

@m-bosch Feel free to post any new issues or pull requests for review.
