### ISSUE TITLE
MultiPoolMiner-3.5.3 won't start

### ISSUE THREAD

**Issue by carlo0000** [MultiPoolMiner/MultiPoolMiner#2451]
hi
i was doing an update on multipool
but got into problem
1 computer all fine  last version run and then i copy it to the second computer but it won't start
the older version was running fine (i say "was" because  now it also has problem when i start it says WARNING: No activeminers available.)

& : At C:\miner\multipoolminer\Include.psm1:1072 char:64
+                 $Global:Devices += $Device = [PSCustomObject]@{
+                                                                ~
Missing closing '}' in statement block or type definition.
At C:\miner\multipoolminer\Include.psm1:1077 char:21
+                     Vendor = $(
+                     ~~~~~~
Unexpected token 'Vendor' in expression or statement.
At C:\miner\multipoolminer\Include.psm1:1114 char:14
+             }
+              ~
The Try statement is missing its Catch or Finally block.
At C:\miner\multipoolminer\Include.psm1:1127 char:49
+                     $Device = [PSCustomObject]@{
+                                                 ~
Missing closing '}' in statement block or type definition.
At C:\miner\multipoolminer\Include.psm1:1138 char:25
+                         Vendor = $(
+                         ~~~~~~
Unexpected token 'Vendor' in expression or statement.
At C:\miner\multipoolminer\Include.psm1:1208 char:14
+             }
+              ~
The Try statement is missing its Catch or Finally block.
At C:\miner\multipoolminer\Include.psm1:1231 char:5
+     }
+     ~
Unexpected token '}' in expression or statement.
At C:\miner\multipoolminer\Include.psm1:1241 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
At line:1 char:3
+ & .\multipoolminer.ps1 -Wallet 1CEb3f8DgcBDCfRap4nrPeFtm7mYwxFYPY -Us ...
+   ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (C:\miner\multipoolminer\Include.psm1:String) [], RuntimeException
+ FullyQualifiedErrorId : MissingEndCurlyBrace

PS C:\miner\multipoolminer>

i don't know why the errors, on the other computer exact same files and it works
powersell, netframwaok it update, but windows 10 is on 1709

**Comment by UselessGuru** [comment]
@carlo0000 

You appear to be running powershell version 5.1. MPM did have a problem with that, but that has been fixed since. Try re-downloading the zip package from
https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip

**Comment by carlo0000** [comment]
hi thanks for fast answer, but i update powershell to 6.2.3  it, was 6.1 

ok this one is working
