### ISSUE TITLE
3.5.4 beta1

### ISSUE THREAD

**Issue by smarcello** [MultiPoolMiner/MultiPoolMiner#2457]
errors:
Exception setting "EstimateCorrection": "The property 'EstimateCorrection' cannot be found on this object. Verify that the property exists and can be set."
At C:\EFFE\MPMbeta\MultiPoolMiner.ps1:1031 char:76
+ ... or $_.EstimateCorrection -gt 1) { $_.EstimateCorrection = [Double]1 }
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
+ FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by UselessGuru** [comment]
@smarcello 

There is no such line 1031 in MultipoolMiner.ps1:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/MultiPoolMiner.ps1

Are you sure you have the latest code?

**Comment by smarcello** [comment]
probably not.
Won't it be a good idea to remark each file with date/hour of release?
