### ISSUE TITLE
with last updates in var

### ISSUE THREAD

**Issue by smarcello** [MultiPoolMiner/MultiPoolMiner#2460]
Add-Member : Cannot add a member with the name "BaseName" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.
At C:\EFFE\MPMbeta\Convert-LegacyMiners.ps1:19 char:26
+ ... _.Content | Add-Member BaseName ($_.Name -split '-' | Select-Object - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (@{Name=XmrigCrypton\u2026c-win64.zip; Fees=}:PSObject) [Add-Member], InvalidOperationException
+ FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

Add-Member : Cannot add a member with the name "Version" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.
At C:\EFFE\MPMbeta\Convert-LegacyMiners.ps1:21 char:26
+ ... _.Content | Add-Member Version ($_.Name -split '-' | Select-Object -I ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (@{Name=XmrigCrypton\u2026c-win64.zip; Fees=}:PSObject) [Add-Member], InvalidOperationException
+ FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

and....
MPM miner is zeroed as the confrontation miner.

**Comment by smarcello** [comment]
sorry, intended DEV

**Comment by UselessGuru** [comment]
@smarcello 

There is is no 
```
Convert-LegacyMiners.ps1:19 char:26

... .Content | Add-Member BaseName ($.Name -split '-' | Select-Object - ...
```

It is `$AllMinerPaths = $AllMinerPaths | Sort-Object -Unique`

???
