### ISSUE TITLE
Benchmarking get stuck on first benchmark

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#2461]
The first benchmarking get stuck, and is there for over 50 minutes.

it says:
`
2020-01-05 21:19:04 WARNING: Benchmarking miner (CcminerSuprMinerSP-v13-3xGeForceGTX10708GB {X16R@NLPool}) requires extended benchmark duration (Benchmarking interval 2/5) [Attempt 1 of max. 3]. `

but still, cant imagine that benchmarking will take over an hour each. then next week we will be done benchmarking.

**Comment by aaronsace** [comment]
@m-bosch I recommend deleting 'CcminerSuprMinerSP-v13.ps1' if you are having issues with it on your machine.

**Comment by m-bosch** [comment]
I removed that one, but only 4 succeed all the other were marked failed....

**Comment by aaronsace** [comment]
Can you upload your logs?
