### ISSUE TITLE
Further deployment

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2462]
@aaronsace 

Any set plans on fixing the dev branch and restoring all the great features of the previous versions?
Dev is non-working for more than 4 weeks, and development has stalled completely for almost 3 weeks.

It is great that you try to restructure the inner life of MPM, but I feel you are forgetting the real needs of the average user:
- most up to date miners
- support for new algorithms
- flexible configuration options

None of the current changes in dev are improving any of the points listed above.

For me it does not make sense to develop code for old MPM versions, e.g. master, knowing that the fundamental changes in dev will eventually break compatibility.

So:
- either fix / restore dev to a working state,
or
- I'll no longer contribute and sell may mining hardware

**Comment by aaronsace** [comment]
Sorry, I only need a code maintainer at the moment that has a rig to test on; specifically while I work on the development branch. 

If anyone else is interested then let me know and I'll add you to the organization.

**Comment by Minerx117** [comment]
very sad @UselessGuru is a Legend in the community
