### ISSUE TITLE
355 and past several issues do not produce profit

### ISSUE THREAD

**Issue by smarcello** [MultiPoolMiner/MultiPoolMiner#2463]
Don't understand, but several last issues do not produce profit on my PC, vice versa, after 2-3 hours PC stops working and it' stucks.
Is it only me complaining ?
Thanks !

**Comment by aaronsace** [comment]
I'm struggling to understand what you are saying but if if post the error you are getting and/or upload the logs folder then I can have a look into it.

**Comment by smarcello** [comment]
Here the log:
[MultiPoolMiner_2020-01-17.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/4082323/MultiPoolMiner_2020-01-17.txt)

**Comment by aaronsace** [comment]
@smarcello There is no errors in that log; have you go any others? Without an error, there isn't much I can do to help.

**Comment by smarcello** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  That's the bad thing! I do not get a specific error, pc just shuts down!?                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 20 gennaio 2020 14:28A: MultiPoolMiner@noreply.github.comRispondi a: reply@reply.github.comCc: semel13@gmail.com; mention@noreply.github.comOggetto: Re: [MultiPoolMiner/MultiPoolMiner] 355 and past several issues do not produce profit (#2463)  @smarcello There is no errors in that log; have you go any others? Without an error, there isn't much I can do to help.

**Comment by aaronsace** [comment]
PC turning off is BSOD due to hardware failure relating to too much heat building up, too much power being drawn or buggy GPU drivers.

Some miners push your PC harder than others so you can try removing the ones that your PC is failing on. Otherwise, your hardware problems need sorting.

**Comment by smarcello** [comment]
Removed a GPU and it seems to work now. Thank you very much!
