### ISSUE TITLE
Numerous errors after GPU hang

### ISSUE THREAD

**Issue by mjmeans** [MultiPoolMiner/MultiPoolMiner#247]
Sometimes a system will hang or crash due to GPU errors. When that happens, and the system is rebooted, MPM will display dozens of Convert-From-Json errors and then display info that it is benchmarking all types again.

This is a feature request... When updating HashRate and Profit files, use a write caching mechanic: write-new the data to a *.new file first; delete any previous *.bak file; rename the *.txt file to *.bak; rename the *.new file to *.txt. This mechanism should keep the *.txt files free from any disk corruption when there is a system crash and prevent the need to re-benchmark, which results in a loss of up to an hour or more of mining time.

**Comment by mjmeans** [comment]
Should be done for *.json files too.

**Comment by fonyo** [comment]
My comment also applies here.
https://github.com/aaronsace/MultiPoolMiner/issues/249#issuecomment-317719717

**Comment by fonyo** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/278
> If your system doesn't crash or fail at all then the resets aren't needed. I will add a file check on start-up that restores bad files with backups at some point.
