### ISSUE TITLE
Feature request: Safely stop the script

### ISSUE THREAD

**Issue by mjmeans** [MultiPoolMiner/MultiPoolMiner#249]
Rather than just exit the window, or when Windows exits and reboots for whatever reason, the script should safely shut down without leaving corrupt json or txt files. The script should monitor the windows shutdown event (and other events) and attempt to safely exit when appropriate. It should also allow "Q" (or ESC or Ctrl+D or whatever) to signal when it should exit and shut down that way as well. A safe shutdown of the script will allow it to quickly recover and be back up mining, particularly if the shut down was automated due to Windows Updates being installed.

**Comment by fonyo** [comment]
I second this. Not much to be done about system crashes but I have all my rigs set to to reboot twice a day and the latest version of MPM is showing a tremendous amount of errors already at launch and during run just after one day of use.
