### ISSUE TITLE
Readme/Documentation on new commands?

### ISSUE THREAD

**Issue by SS2006** [MultiPoolMiner/MultiPoolMiner#278]
Hi There. Downloaded newest version and I see there is now a
'reset profit'
'reset benchmark'
'start'
and 'start2gb'

These are new to me, and I can't find documentation on what they do, would you kindly explain them? Reset benchmark seems self explanatory, and start is what I always used. But what does reset profit and 'start2gb' do?

**Comment by papampi** [comment]
Some times if windowsshell close before it create all the profit files it cant start again and gives error.
in that case you should run reset profit to remove all profit files and start again.
Although its better to remove all old profit files at startup and start clean so it wont give that error.
start2gb is for 2gb cards ...

**Comment by aaronsace** [comment]
If your system doesn't crash or fail at all then the resets aren't needed. 
I will add a file check on start-up that restores bad files with backups at some point.

**Comment by fonyo** [comment]
@aaronsace BTW what happened to the start2gb batch file? Is this a thing that is no longer supported or moved to somewhere else? I was just updating the FAQ and noticed the new structure.

**Comment by aaronsace** [comment]
I merged them together as everyone can benefit by the speed improvement.

**Comment by fonyo** [comment]
Does this mean we don't mine certain coins at all?

**Comment by aaronsace** [comment]
No, I mean it has both APIs and both algorithms: 
miningpoolhub and miningpoolhubcoins
ethash and ethash2gb

**Comment by fonyo** [comment]
Nice. I need to have a look at it. Was busy with the project board and the issues and faq today.

**Comment by fonyo** [comment]
So what is now the difference between "miningpoolhub" and "miningpoolhubcoins"?

**Comment by aaronsace** [comment]
They use different APIs and ports. The coins one connects to each individual coin.

**Comment by fonyo** [comment]
And you are filtering to ethash 2GB coins with the miningpoolhubcoins command? I seem to be getting all of them with both (tested separately). The order of the miner files seems only different, which doesn't make sense for me as they should be listed by profitability? Sorry for the lots of question marks here.

**Comment by aaronsace** [comment]
The main difference is the ports: 
Simple coin mining (Port 20XXX)
Algo switch mining (Port 17XXX)

'ethash2gb' is just the same as 'ethash' put without 20535 and 20555.
