### ISSUE TITLE
Disable Dual Mining

### ISSUE THREAD

**Issue by Dangerous-Mind** [MultiPoolMiner/MultiPoolMiner#295]
Is there a option to disable dual mining?

Some times there no profit in dual mining or the PSU does not support the extra charge...
It would be nice to have that option.

I added -mode 1 to the claymore txt files but probably the application is considering both profits and might not switch pools because of that. 

PS: Deleted the claymoreXXX.txt files. Problem solved :)
But it would be nice to have that option.

**Comment by aaronsace** [comment]
You can select specifically what miners you want to use be using '-minername' but it's easier deleting them. I would need to implement the ability to exclude as well as include otherwise it would take you ages listing them all. 

If dual mining isn't working then I think that is highlighting a problem with your system though. Your system should never crash if working correctly.

**Comment by aaronsace** [comment]
I'll look at supporting expressions/wildcards.

**Comment by UselessGuru** [comment]
> I'll look at supporting expressions/wildcards.
Or use filters to disable selectex minres / pools.
I have modified include.ps1 like this to ignore all miners/pools beginning with an '_'. - this is better than deleting them:
```
    $ChildItems = Get-ChildItem $Path `**-Exclude "_*"` | ForEach-Object {
        $Name = $_.BaseName
        $Content = @()
        if ($_.Extension -eq ".ps1") {
            $Content = &$_.FullName
        }
        else {
            $Content = $_ | Get-Content | ConvertFrom-Json
        }
        $Content | ForEach-Object {
            [PSCustomObject]@{Name = $Name; Content = $_}
        }
    }
```

**Comment by lmlim** [comment]
for disabling  dual mining, i just deleted sia,pascal,lbry,decred and all their variants in 
-algorithm option. and it works.

**Comment by UselessGuru** [comment]
You could also modify the miner files of the dual miner capable miners. Not sexy, but ;-)

**Comment by fonyo** [comment]
Enhancement label is removed due to this has been implemented in a way. I will add this to FAQ to clarify what to do to achieve this.

**Comment by fonyo** [comment]
Added as FAQ#22
