### ISSUE TITLE
Feathercoin

### ISSUE THREAD

**Issue by Dangerous-Mind** [MultiPoolMiner/MultiPoolMiner#314]
For time to time feathercoin starts mining in all of my rigs.
Calculating the reward its about 7€ a day on all of them.

Somehow the price pumps to a high value.
Then it comes back to normal about 30 mins or more.

**Before**
Miner        Algorithm         Speed BTC/Day  BTC/GH/Day Pool
-----        ---------         ----- -------  ---------- ----
Gatelessgate NeoScrypt     3,98 MH/s 0,00353     0,88511 MiningPoolHub-Feathercoin
Claymore       Ethash      165,94 MH/s 0,00266      0,01603 MiningPoolHub-Ethereum

SgminerNeoscrypt NeoScrypt     1,04 MH/s 0,00092     0,88511 MiningPoolHub-Feathercoin

**After**
Gatelessgate NeoScrypt     3,53 MH/s 0,00067     0,18917 MiningPoolHub-Feathercoin
SgminerNeoscrypt NeoScrypt     1,04 MH/s 0,00020     0,18917 MiningPoolHub-Feathercoin
I managed to be the first in the list of Feathercoin mining pool. Nobody is mining it. :)

Can you check?

**Comment by spider703** [comment]
on my GTX-1060 Gatelessgate no working

**Comment by Dangerous-Mind** [comment]
Started again right now.

Gatelessgate NeoScrypt     3,98 MH/s 0,00337     0,84637 MiningPoolHub-Feathercoin

Gatelessgate NeoScrypt     3,40 MH/s 0,00288     0,84637 MiningPoolHub-Feathercoin

Gatelessgate NeoScrypt     3,53 MH/s 0,00299     0,84637 MiningPoolHub-Feathercoin

**Comment by aaronsace** [comment]
The price went up then down for 30 minutes? 
This is an issue with the @MiningPoolHub api.

**Comment by Dangerous-Mind** [comment]
I think its a bug some were. In Polinex the only changes have been down.
It has been happening for some days.

Made 41 Coins today and 10 yesterday.
2017-08-28 (UTC) | 41.47940497
2017-08-27 (UTC) | 10.58043228

Can you check if your rigs mine feather also?

I deleted the Gatelessgate miner.

**Comment by Dangerous-Mind** [comment]
Feather in second place on the site again. Some minutes ago it was Maxcoin.
Do you have a special contact with them so they can check?

API
    {
      "algo": "NeoScrypt",
      "current_mining_coin": "feathercoin",
      "host": "hub.miningpoolhub.com",
      "all_host_list": "hub.miningpoolhub.com",
      "port": 12012,
      "algo_switch_port": 17012,
      "multialgo_switch_port": 12012,
      "profit": 0.45623196,
      "normalized_profit_amd": 0.22309743,
      "normalized_profit_nvidia": 0.23952178
    },
![image](https://user-images.githubusercontent.com/31196073/29860688-bb8baafc-8d5e-11e7-8a59-c831afdafcfe.png)

**Comment by aaronsace** [comment]
@MiningPoolHub just needs to update the cache rate on the API from 30 minutes to about 5. I have no special contact, just have to wait until the API is sorted.

**Comment by coreshift** [comment]
He's using cloudflare to cache. Minimum is 30 minutes, apparently.

https://bitcointalk.org/index.php?topic=472510.msg19907622#msg19907622

**Comment by aaronsace** [comment]
Thanks for the information @coreshift. 
Zpool and NiceHash use cloudflare but obviously must but using it differently. @MiningPoolHub needs to review the implementation.

**Comment by coreshift** [comment]
He's probably paying for business class. I'm sure enterprise is a lot pricier.

https://support.cloudflare.com/hc/en-us/articles/200168376-What-does-edge-cache-expire-TTL-mean-

**Comment by aaronsace** [comment]
Yes, that will be why. 

Currently the stats are only good for creating a daily average. 

@MiningPoolHub will either need to discuss a custom enterprise price plan or look at a different approach for the API.

**Comment by Dangerous-Mind** [comment]
You can use whattomine.com json to make the calculations. 
https://whattomine.com/coins.json

Mined another coin without profit today. 
Groestlcoin

**Comment by aaronsace** [comment]
@Dangerous-Mind That has it's limitations; it is something that I'm considering as an addition. 

I'll wait to see if @miningpoolhub sorts the API. 

As a temporary measure, I will have to change it to a daily average and remove it as the default pool in the coming release.

**Comment by Dangerous-Mind** [comment]
hmmm!!! 
I just saw Feathercoin on the second and  place and Groestlcoin on some top places in whattomine.com

The Feathercoin jumped 10% in 1 hour. Going down again.

**Comment by fonyo** [comment]
I don't think we have requested MPH to lower the update rate of the coin API. I shall drop him a message and post on bitcointalk about this.

**Comment by aaronsace** [comment]
@fonyo awesome. The problem seems to be directly linked to MiningPoolHub moving to cloudflare.

**Comment by fonyo** [comment]
As you have probably seen, MPH stated he would look for alternatives regarding the frequency of API updates. The cloudflare caching and its update rate just doesn't cut it (one of the reasons a I also moved away from cloudflare in the past). I will keep bugging him so he doesn't forget.
