### ISSUE TITLE
[Feature Request] Mine according to Profit

### ISSUE THREAD

**Issue by Dangerous-Mind** [MultiPoolMiner/MultiPoolMiner#316]
There are coins, like Monero, that use much less power and so it saves us money.
As a example, at this time ETH gives more money per hash but it is less profitable compared to Monero.

The power draw off Monero is about 20% less then Ethereum. And since power is expensive in some countries (my is 0.23 USD with a 12% discount) this it would be a good feature to implement.

**Comment by aaronsace** [comment]
This feature will be added in the future.
