### ISSUE TITLE
Add all algos if no algos specified in start cmd

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#321]
Early in main routine I put
```
# No algo passed on startup. Load all available algorithms, do not include if preficed with _ (underscore, note: # does not work in lists)
if ($Algorithm -notmatch ".+") {
    (Get-Content "Algorithms.txt" | ConvertFrom-Json).PSObject.Properties.Name | ForEach {if ($_ -notmatch "^_.*") {[Array]$Algorithm += $_}}
}

```
Instead of removing algorithms in 'algorithm.txt' I prefix them with an _ to exclude them from the list

**Comment by aaronsace** [comment]
Not sure why you are editing 'algorithms.txt'; I just use it as an auto-correct dictionary. 

What's the aim of what you are doing with this?

**Comment by UselessGuru** [comment]
> I just use it as an auto-correct dictionary.

Assuming I am to lazy to specify 50+ algorithms in my start.cmd. I simply want to mine any algo that is available (except for the off exclusion I am not interested in, then I could exclude them with _). In this scenario I don't need the auto-correct and _ flagging does not hurt.

**Comment by aaronsace** [comment]
It will mine on all algorithms if non specified. 
I will add the ability to exclude pools, miners and algorithms.

**Comment by UselessGuru** [comment]
> It will mine on all algorithms if non specified.

You are right (found the problem on my side, here it did not :-( )
> I will add the ability to exclude pools, miners and algorithms; it's on my to-do.

Quick-win: I exclude unwanted miners / miners by prefixing them with \_
In 'Get-ChildItem' I changed
`    $ChildItems = Get-ChildItem $Path | ForEach-Object {`
to
`    $ChildItems = Get-ChildItem $Path -Exclude "_*" | ForEach-Object {`

**Comment by crazybrker** [comment]
In the main MPM.ps1 I added these lines just under the param around line 45

`#Exclude Underscore 
$Algorithm = $Algorithm -notmatch "^_.*"
$PoolName = $PoolName -notmatch "^_.*"
`

Then I can just do the underscore exclusion inside the start.bat thanks for the idea @UselessGuru
