### ISSUE TITLE
Feature Request - Centralized Monitoring

### ISSUE THREAD

**Issue by Imaminer** [MultiPoolMiner/MultiPoolMiner#340]
MPH does not show the individual miners like Zpool.
I was wonder if MPM could have a monitoring website.
Local site on local network.
Need some sort of service to run on each Windows rig. 
Any thoughts about that?
Currently using Teamviewer but would love to see all rigs on one screen

**Comment by aaronsace** [comment]
Yes, will come.

**Comment by UselessGuru** [comment]
Does the newly added [Reporting ans Monitoring ](https://github.com/MultiPoolMiner/MultiPoolMiner#reporting-and-monitoring) satisfy your needs?
If yes then plese close this thread - TIA

**Comment by grantemsley** [comment]
This has been implemented through the website, as well as https://github.com/MultiPoolMiner/mpm-monitor for a host it yourself solution.
