### ISSUE TITLE
Excavator and AMD Admin Rights - Possible Solution

### ISSUE THREAD

**Issue by Imaminer** [MultiPoolMiner/MultiPoolMiner#361]
Looks like the author has provided a solution. Please look under the amd folder and you will see a file called start-admin.bat

I have been trying to figure out a way to use this in your script but my skills are lacking. 
I think if you could figure it out then AMD will finally work with Excavator.

Mind looking? 

Thanks

**Comment by aaronsace** [comment]
Just run MultiPoolMiner miner in admin mode to activate the AMD specific speed improvements. I tend to get BSOD though.

**Comment by Imaminer** [comment]
I need a different way. Windows crashes. A lot. So I have the MPM batch in my startup folder so it can auto start after a crash.
Cannot auto start a file with admin rights.

**Comment by aaronsace** [comment]
I don't think the Excavator driver is stable enough yet. 

It's possible to auto start PowerShell in admin mode though; it's achieved through Windows Task Scheduler. I could add a script to add/remove it from start-up using PowerShell commands ('New-ScheduledTaskTrigger').

**Comment by Imaminer** [comment]
That would be beneficial with or without excavator

**Comment by crazybrker** [comment]
You can use scheduled tasks to launch it as admin without the the UAC bother
https://superuser.com/questions/770420/schedule-a-task-with-admin-privileges-without-a-user-prompt-in-windows-7
![image](https://user-images.githubusercontent.com/13236046/33593326-d8356a3c-d9c9-11e7-8218-6945eb0f086f.png)
Schedule it to launch 30 second or a minute after the user logs in.

Then to auto-login on reboot, try this:
https://www.tekrevue.com/tip/skip-windows-10-login-screen/

**Comment by UselessGuru** [comment]
Excavator does no longer support AMD cards.
