### ISSUE TITLE
User-friendliness

### ISSUE THREAD

**Issue by fonyo** [MultiPoolMiner/MultiPoolMiner#370]
## 1. Display

While I was working on reviewing and organising the requests and enhancements for MPM V3, I came across a few things that reminded me when my friend was new to MPM then I realised I felt the same about it after the first glance. While lots information is great to have on display, this could also be organised so it is clean and relevant and NOT overwhelming (or truncated by lack of cmd width). I will sketch up a few things and try to modify MPM accordingly. Some things need to either be compacted or replaced with readable content or omitted completely such as the following column:
```
Pool
----
{MiningPoolHub-Ethereum, MiningPoolHub-Siacoin}
```
I consider myself young but my eyes are getting quite tired at looking at Consolas font size 12 which is manually set just to see the whole picture while not running full screen so I can also monitor the miner. This is an important matter that is mostly overlooked by many people.

Some beatification and (helpful, moderate amount of) colours would also be great (probably one of the reasons Claymore's miner is so popular.) but I don't want to lose focus on the higher priority tasks.

## 2. Documentation

Writing proper documentation is on my to-do but things are changing so rapidly it is difficult to see where to even start and catch up with the issues and questions daily. That is why the FAQ was created in the first place as a "quick & dirty" alternative. Needless to say, I am definitely updating the FAQ before documentation can even be thought about.

Just thought I would let everyone know here and write it down for myself so I can pin it to V3 board. 
https://github.com/aaronsace/MultiPoolMiner/projects/1

**Comment by crazybrker** [comment]
Suggestion: Add an option to limit the profitability display to only miners making more than x BTC/DAY. Do we need to see the algos making .00000001 BTC? ( Some of us really want to see it all )

Maybe shorten pool names to MPH and NH for better visibility on the dual miners.

**Comment by fonyo** [comment]
https://gallery.technet.microsoft.com/scriptcenter/Format-Table-Colors-in-e0a4beac
