### ISSUE TITLE
miner for cryptonight, hmq1725,timetravel,lyra2z,c11, keccak, myr-gr, sib, skein

### ISSUE THREAD

**Issue by spider703** [MultiPoolMiner/MultiPoolMiner#384]
Added a miner on which the speed is higher for the listed algorithms, ftp://radio.r41.ru/FTP/CcminerHMQ1725.ps1

**Comment by cbracht** [comment]
Is not faster for 1080 TIs in the following: lyra2z, timetravel (didn't test others).

**Comment by spider703** [comment]
2 1060 and 1 1080 on them faster than on CcminerTpruvot in programm

**Comment by fonyo** [comment]
Anyone tested this on a 1070 rig?

**Comment by alucard20724** [comment]
I'll test it next week on a 5x1070 rig against Tpruvot if no one has done it by then.

**Comment by spider703** [comment]
2x1060 and 1x1080 
Tpruvot miner
lyra2z - 0 Mh
hmq1725 - 10.71 Mh
timetravel - 0 Mh
cryptonight - 1.58 kh
nist5 -96.45 Mh
HMQ1725 miner
lyra2z - 3.92 Mh
hmq1725 - 10.74 Mh
timetravel - 63.41 Mh
cryptonight - 1.61 kh
nist5 -109.28 Mh

**Comment by Pititul** [comment]
3x1070
Tpruvot miner
lyra2z - 4.68 Mh
hmq1725 - 11.17 Mh
timetravel - 55.18 Mh
cryptonight - 2.05 kh

HMQ1725 miner
lyra2z - 2.53 Mh
hmq1725 - 19.71 Mh
timetravel - 62.36 Mh
cryptonight - 1.41 kh

**Comment by spider703** [comment]
add to my ftp://radio.r41.ru/FTP/CcminerAlexis78cuda8.0.ps1 high speed on algoritm c11, keccak, myr-gr, sib, skein 
Taken from NemosMiner-v2.1-Zpool
need to test on your rigs

**Comment by somidax** [comment]
can any one help out with this miner

HMQ1725 miner so as to test my new rig?


Also will want to know if any have tryied using Quadro nvdia cards for
mining.

thanks
