### ISSUE TITLE
Show Switching Value

### ISSUE THREAD

**Issue by viatoro** [MultiPoolMiner/MultiPoolMiner#394]
#Display mining information
    
    $Miners | Where-Object {$_.Profit -ge 1E-5 -or $_.Profit -eq $null} | Sort-Object -Descending Type, Profit | Format-Table -GroupBy Type (
        @{Label = "Miner"; Expression = {$_.Name}}, 
        @{Label = "Algorithm"; Expression = {$_.HashRates.PSObject.Properties.Name}}, 
        @{Label = "Speed"; Expression = {$_.HashRates.PSObject.Properties.Value | ForEach-Object {if ($_ -ne $null) {"$($_ | ConvertTo-Hash)/s"}else {"Benchmarking"}}}; Align = 'right'}, 
        @{Label = "BTC/Day"; Expression = {$_.Profits.PSObject.Properties.Value | ForEach-Object {if ($_ -ne $null) {$_.ToString("N5")}else {"Benchmarking"}}}; Align = 'right'}, 
        @{Label = "SW/Cost"; Expression={if($_.Profit_Bias -ne $null){$_.Profit_Bias.ToString("N5")}else{"Benchmarking"}}; Align='right'}, 
        @{Label = "BTC/GH/Day"; Expression = {$_.Pools.PSObject.Properties.Value.Price | ForEach-Object {($_ * 1000000000).ToString("N5")}}; Align = 'right'}, 
        @{Label = "Pool"; Expression = {$_.Pools.PSObject.Properties.Value | ForEach-Object {if ($_.Info) {"$($_.Name)-$($_.Info)"}else {"$($_.Name)"}}}}
    ) | Out-Host

**Comment by aaronsace** [comment]
What are you showing?

**Comment by viatoro** [comment]
add line     @{Label = "SW/Cost"; Expression={if($_.Profit_Bias -ne $null){$_.Profit_Bias.ToString("N5")}else{"Benchmarking"}}; Align='right'}, 
 to #Display mining information

**Comment by viatoro** [comment]
Kuy


   Type: NVIDIA

Miner            Algorithm           Speed BTC/Day SW/Cost BTC/GH/Day Pool
-----            ---------           ----- ------- ------- ---------- ----
CcminerPalgin    Sib            48.04 MH/s 0.00372 0.00228    0.07739 Zpool
CcminerTpruvot   Sib            37.17 MH/s 0.00288 0.00177    0.07739 Zpool
CcminerPalgin    X17            43.49 MH/s 0.00265 0.00204    0.06101 Zpool
CcminerSib       Sib            32.16 MH/s 0.00249 0.00153    0.07739 Zpool
CcminerSkunk     Skunk         118.32 MH/s 0.00247 0.00238    0.02090 Zpool
CcminerPalgin    Veltor        123.65 MH/s 0.00227 0.00223    0.01833 Zpool
CcminerTpruvot   Skunk         106.37 MH/s 0.00222 0.00214    0.02090 Zpool
CcminerNanashi   Lyra2z          6.62 MH/s 0.00212 0.00212    0.32093 Zpool
ExcavatorNvidia2 Lbry            1.22 GH/s 0.00201 0.00173    0.00165 Zpool
CcminerTpruvot   Lyra2z          6.11 MH/s 0.00196 0.00196    0.32093 Zpool
CcminerTpruvot   Lbry            1.15 GH/s 0.00190 0.00164    0.00165 Zpool
ExcavatorNvidia2 Blake2s        14.75 GH/s 0.00171 0.00167    0.00012 Zpool
ExcavatorNvidia2 Lyra2RE2      159.98 MH/s 0.00170 0.00148    0.01064 Zpool
CcminerLyra2z    Lyra2z          5.28 MH/s 0.00169 0.00169    0.32093 Zpool
CcminerPalgin    Blake2s        14.56 GH/s 0.00169 0.00165    0.00012 Zpool
CcminerTpruvot   Bitcore        62.74 MH/s 0.00168 0.00168    0.02675 Zpool
EWBF0            Equihash        1.83 KH/s 0.00167 0.00157  910.96000 Zpool
EWBF1            Equihash        1.83 KH/s 0.00167 0.00157  910.96000 Zpool
ExcavatorNvidia3 Lbry          995.89 MH/s 0.00164 0.00142    0.00165 Zpool
EWBF2            Equihash        1.80 KH/s 0.00164 0.00155  910.96000 Zpool
CcminerTpruvot   Blakecoin      17.78 GH/s 0.00163 0.00162    0.00009 Zpool
ExcavatorNvidia3 Lyra2RE2      151.07 MH/s 0.00161 0.00139    0.01064 Zpool
CcminerPalgin    Lyra2RE2      149.75 MH/s 0.00159 0.00138    0.01064 Zpool
CcminerTpruvot   Veltor         86.34 MH/s 0.00158 0.00155    0.01833 Zpool
ExcavatorNvidia3 Equihash        1.69 KH/s 0.00154 0.00145  910.96000 Zpool
CcminerTpruvot   Lyra2RE2      143.87 MH/s 0.00153 0.00133    0.01064 Zpool
CcminerLyra2RE2  Lyra2RE2      141.53 MH/s 0.00151 0.00131    0.01064 Zpool
ExcavatorNvidia2 Equihash        1.65 KH/s 0.00150 0.00142  910.96000 Zpool
CcminerTpruvot   HMQ1725        19.01 MH/s 0.00148 0.00114    0.07775 Zpool
CcminerKlaust    Groestl       159.09 MH/s 0.00147 0.00134    0.00923 Zpool
CcminerTpruvot   Blake2s        12.54 GH/s 0.00145 0.00142    0.00012 Zpool
CcminerSp        Skein           2.19 GH/s 0.00145 0.00134    0.00066 Zpool
CcminerPalgin    Skein           2.17 GH/s 0.00143 0.00133    0.00066 Zpool
ExcavatorNvidia3 Blake2s        12.20 GH/s 0.00141 0.00138    0.00012 Zpool
CcminerTpruvot   Groestl       150.68 MH/s 0.00139 0.00127    0.00923 Zpool
CcminerSp        C11            54.85 MH/s 0.00134 0.00123    0.02434 Zpool
CcminerTpruvot   C11            51.11 MH/s 0.00124 0.00115    0.02434 Zpool
CcminerKlaust    MyriadGroestl 271.82 MH/s 0.00123 0.00111    0.00454 Zpool
CcminerKlaust    NeoScrypt       4.57 MH/s 0.00123 0.00084    0.27006 Zpool
CcminerTpruvot   MyriadGroestl 256.83 MH/s 0.00117 0.00105    0.00454 Zpool
CcminerPalgin    Nist5         175.24 MH/s 0.00115 0.00094    0.00657 Zpool
CcminerTpruvot   Timetravel     89.50 MH/s 0.00114 0.00114    0.01272 Zpool
CcminerTpruvot   Nist5         164.04 MH/s 0.00108 0.00088    0.00657 Zpool
CcminerNanashi   NeoScrypt       3.98 MH/s 0.00107 0.00073    0.27006 Zpool
CcminerTpruvot   NeoScrypt       3.96 MH/s 0.00107 0.00073    0.27006 Zpool
CcminerTpruvot   JHA            57.63 MH/s 0.00102 0.00097    0.01768 Zpool
CcminerNanashi   JHA            57.35 MH/s 0.00101 0.00097    0.01768 Zpool
CcminerPalgin    MyriadGroestl 221.84 MH/s 0.00101 0.00090    0.00454 Zpool
CcminerPalgin    Lbry          589.95 MH/s 0.00097 0.00084    0.00165 Zpool
CcminerTpruvot   Decred         10.91 GH/s 0.00093 0.00093    0.00009 Zpool
CcminerD         Decred         10.57 GH/s 0.00090 0.00090    0.00009 Zpool
CcminerTpruvot   Skein           1.27 GH/s 0.00084 0.00077    0.00066 Zpool
CcminerPalgin    X11evo         54.12 MH/s 0.00079 0.00071    0.01456 Zpool
CcminerPalgin    Keccak          2.59 GH/s 0.00078 0.00055    0.00030 Zpool
CcminerTpruvot   X11evo         52.83 MH/s 0.00077 0.00070    0.01456 Zpool
CcminerTpruvot   Keccak          2.19 GH/s 0.00066 0.00046    0.00030 Zpool
CcminerSp        X17             9.47 MH/s 0.00058 0.00044    0.06101 Zpool
ReorderNvidia    Keccak          1.41 GH/s 0.00042 0.00030    0.00030 Zpool
CcminerTpruvot   Tribus        162.16 MH/s 0.00034 0.00023    0.00208 Zpool
NsgminerNvidia   NeoScrypt     870.00 KH/s 0.00023 0.00016    0.27006 Zpool
ReorderNvidia    Skein         197.03 MH/s 0.00013 0.00012    0.00066 Zpool
CcminerTpruvot   Qubit          80.50 MH/s 0.00006 0.00005    0.00069 Zpool
CcminerTpruvot   Quark          82.68 MH/s 0.00005 0.00004    0.00058 Zpool
CcminerTpruvot   X11            54.34 MH/s 0.00004 0.00004    0.00077 Zpool
CcminerTpruvot   Scrypt          1.89 MH/s 0.00002 0.00002    0.00978 Zpool


   Type: {AMD, NVIDIA}

Miner      Algorithm      Speed BTC/Day SW/Cost BTC/GH/Day Pool
-----      ---------      ----- ------- ------- ---------- ----
Excavator3 Equihash   1.72 KH/s 0.00157 0.00148  910.96000 Zpool
Excavator2 Equihash   1.65 KH/s 0.00151 0.00142  910.96000 Zpool
Prospector Skunk     52.73 MH/s 0.00110 0.00106    0.02090 Zpool




   Status: Running

     Speed Active                      Launched Command
     ----- ------                      -------- -------
48.79 MH/s 00 Days 00 Hours 20 Minutes 3 Times  Bin\NVIDIA-Palgin\ccminer.exe -a sib -o stratum+tcp://sib.mine.zpool.ca:5033 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC


   Status: Idle

    Speed Active                          Launched Command
    ----- ------                          -------- -------
0.00 PH/s 00 Days 00 Hours 15 Minutes     4 Times  Bin\NVIDIA-TPruvot\ccminer-x64.exe -a hmq1725 -o stratum+tcp://hmq1725.mine.zpool.ca:3747 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 14 Minutes     4 Times  Bin\NVIDIA-Palgin\ccminer.exe -a veltor -o stratum+tcp://veltor.mine.zpool.ca:5034 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 01 Hours 39 Minutes     12 Times Bin\NVIDIA-KlausT\ccminer.exe -a neoscrypt -o stratum+tcp://neoscrypt.mine.zpool.ca:4233 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 20 Minutes     3 Times  Bin\Skunk-NVIDIA\ccminer.exe -a skunk -o stratum+tcp://skunk.mine.zpool.ca:8433 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 22 Minutes     3 Times  Bin\NVIDIA-SP\ccminer.exe -a skein -o stratum+tcp://skein.mine.zpool.ca:4933 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 05 Minutes     Once     Bin\Excavator\excavator.exe -p 23456 -c Zpool_Lbry_2_Nvidia.json -na
0.00 PH/s 304420 Days 15 Hours 34 Minutes 8 Times  Bin\NVIDIA-Palgin\ccminer.exe -a x17 -o stratum+tcp://x17.mine.zpool.ca:3737 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 09 Minutes     2 Times  Bin\NVIDIA-Palgin\ccminer.exe -a nist5 -o stratum+tcp://nist5.mine.zpool.ca:3833 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 27 Minutes     2 Times  Bin\NVIDIA-SP\ccminer.exe -a c11 -o stratum+tcp://c11.mine.zpool.ca:3573 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 08 Minutes     2 Times  Bin\NVIDIA-Nanashi\ccminer.exe -a lyra2z -o stratum+tcp://lyra2z.mine.zpool.ca:4553 -u 3B3uQUKrR4EHNpd56zkrkQFAWB6Erq3bTB -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 16 Minutes     3 Times  Bin\Excavator\excavator.exe -p 23456 -c Zpool_Lyra2RE2_2_Nvidia.json -na
0.00 PH/s 00 Days 00 Hours 32 Minutes     3 Times  Bin\Excavator\excavator.exe -p 23456 -c Zpool_Blake2s_2_Nvidia.json -na


MultiPoolMiner is between 0% and 57% more profitable than the fastest miner:

Miner             BTC                             USD                                EUR
-----             ---                             ---                                ---
MultiPoolMiner    0.00341 ±24 % (0.00276-0.00423) 14.03561 ±24 % (11.32966-17.38783) 11.83551 ±24 % (9.55373-14.66227)
CcminerPalgin-Sib 0.00266 ±32 % (0.00201-0.00351) 10.92319 ±32 % (8.26456-14.43708)  9.21097 ±32 % (6.96908-12.17405)

**Comment by UselessGuru** [comment]
Done, column 'Accuracy' in later builds is exactly this.
