### ISSUE TITLE
Feature request: Dual wallets to account for variable NiceHash fees

### ISSUE THREAD

**Issue by mjmeans** [MultiPoolMiner/MultiPoolMiner#430]
According to the current fees, NiceHash fee when mining to an external wallet is 4% for balances less than 0.1 BTC. Payouts are once per week for balances less than 0.1 BTC and greater than 0.01 BTC.

People mining to NiceHash wallet have a lower mining fee of 2%, but also have a withdrawal fee if you want it to take your BTC to GDAX or wherever. The withdrawal fee is 0.0005 BTC. For people wanting to transfer their BTC out of NiceHash wallet as fast as possible, at the minimum transfers of 0.001 this comes to a whopping 52% in fees. So obviously not what anyone wants to do. The breakeven point is comes if you only withdraw amounts greater than 0.025 BTC which works out to total 4% in mining and withdrawal fees; and 0.05 BTC works out to a total of 3%.

I think most people will want to be mining to an external wallet as it would take somewhere near 10 rigs mining constantly on NiceHash to get over 0.1 BTC per week and drop to the 2% miming payout fee. And with MPM auto switching between NiceHash, MPH and ZPOOL, balances on NiceHash will be lower and randomly up or down each week.

And people don't want to use a NiceHash wallet to receive mining payouts from other pools. NiceHash has additional fees for small deposits into a NiceHash wallet, the most severe is that for a deposit of 0.0005 BTC or less the fee is the entire deposit, 100%. You get nothing. And when using MPM you will not be able to predict your periodic payout amounts which may be small from time to time.

Requests:

1. Set the default mining feel for this pool to 4% for the profitability calculation and add in MPM instructions to always specify an external wallet as the main wallet (not a NiceHash wallet) if using NiceHash.

2. If running a larger mining setup or if you who want to accumulate BTC in NiceHash before withdrawing for other reasons you will need to specify a second wallet to use only on NiceHash. In this case we can assume a default best case minimum fees of 2.2% for profitability calculation. MPM should then switch to the NiceHash wallet address when mining on NiceHash.

3. (optional) When could allow the user to specify a different profitability factor when mining on NiceHash to a NiceHash wallet. For example if the user expects to always withdraw 0.05 BTC whenever they have enough, then then can set it to 3%.

**Comment by nimbosa** [comment]
somewhat RELATED: HashRefinery pool, by default, mines using NiceHash wallet input!!! this totally doesnt make sense, zpool and hashrefinery could be using the same address, but definitely not a nicehash address, right?

**Comment by Braintelligence** [comment]
I would like to be able to mine to my internal NiceHash wallet while mining NiceHash but mine to another wallet while mining for AHashPool. Is that possible somehow?

**Comment by aaronsace** [comment]
@Braintelligence You can try hacking the files in the pools folder...

Seriously though, just mine to an external wallet; it works great and is better value.

**Comment by Braintelligence** [comment]
@aaronsace I want to use the new Coinbase feeless feature of NiceHash but from what I know you need to mine to their internal wallet for this.

**Comment by aaronsace** [comment]
Interesting, I wonder if Coinbase are storing their Bitcoins now...

No native support for this at the moment, go ahead and edit the NiceHash pool file: 
`User          = "$Wallet.$WorkerName" -replace "old wallet address", "new wallet address"`

**Comment by Braintelligence** [comment]
Thanks, will do :+1:

**Comment by UselessGuru** [comment]
Support for NH internal is available:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1080

**Comment by mrfhenix** [comment]
Feature Request:  Multiple Internal wallets same account 
for multiple unit support on different wallets
