### ISSUE TITLE
XMG M7M CPU mining

### ISSUE THREAD

**Issue by jjziets** [MultiPoolMiner/MultiPoolMiner#466]
Will you be adding M7M ? https://bitcointalk.org/index.php?topic=859820.0

**Comment by aaronsace** [comment]
Is it profitable?

**Comment by spider703** [comment]
this algo working on miner CPU-JayDDee, i add in file CpuminerJayddeeAesavx.ps1 line "m7m" = "" #M7M and he working, lately, m7m is more profitable than cryptonight (usually work m7m or cryptonight)

**Comment by fonyo** [comment]
I've been testing it for a few days now with 3 different CPUs (6-core AMD, 4-core APU, dual core Intel. Apart from the fact the pool went down for more than a day, it is actually quite good for CPU mining if you have free electricity. My estimates are around 15-25 pounds a month before power costs. Tested with optiminer 2.4 and the latest 3.7. The latter is a bit faster.

**Comment by fonyo** [comment]
AesAvx would not work on all CPUs, I use SSE2 in all my cases.

**Comment by VeggieVampire** [comment]
If you add XMG mining to the pool, I'll defiantly switch. This would allow SBC(Single Board Computer) Crypto Mining to the miningpoolhub. In other worlds adding clusters of Raspberry Pi s using the Wolf0 m7m cpuminer.

----Steps to get the Crypto miner running on the pi----
cd ~
wget www.thelwall.org/novaspirit_installer
chmod +x ./novaspirit_installer
./novaspirit_installer

---start miner---
./minerd  -o stratum+tcp://pool_url:pool_port -u pool_user.worker -p password -t thread_numbers -e cpu_efficiency
