### ISSUE TITLE
support for Hodl cpu coin?

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#486]
https://github.com/HOdlcoin/HOdlcoin/releases/

it's available to be mined on nicehash..  I just started looking into it, but it looks pretty profitable for cpu mining.

stratum+tcp://hodl.LOCATION.nicehash.com:3352

**Comment by dvwzj** [comment]
you can use CPU miner by JayDDee (cpuminer-opt v. 3.7.2 is supported *Only CPUs with AES are supported.*)

sry for my bad english

**Comment by alucard20724** [comment]
yeah.. figured it out... just need to add hodl to algorithms.txt and to the miners file for JayDDee... i think all my cpu have AES support..

**Comment by aaronsace** [comment]
Any better than FireIce's Cryptonight CPU Miner?

**Comment by spider703** [comment]
on what pool the hold is digging?
на каком пуле добывается холд?

**Comment by alucard20724** [comment]
Nicehash has hodl

**Comment by UselessGuru** [comment]
MPM uses any algos & coins for which it has:

- received information from the pool
- a working miner for these algos

What miner supports 'hodl'?
