### ISSUE TITLE
Optimized Lyra2rev2 miner for AMD 

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#495]
Looks like it gets double the speed of the current sgminer for Lyra2RE2

https://bitcointalk.org/index.php?topic=2360168

I can get it to work stand alone, just can't get it to work with mpm.

**Comment by fonyo** [comment]
This is huge. Someone beats Vertcoin's own dev team to the punchline. I've been crying out loud for AMD support for years.

**Comment by aaronsace** [comment]
WTF, NiceHash only... even NiceHash miners support other pools.

**Comment by aaronsace** [comment]
If anyone out there is using this miner, please can you do a pull request?

**Comment by alucard20724** [comment]
there's a new released version.. haven't tried messing with it yet

https://bitcointalk.org/index.php?topic=2360168.0

**Comment by fonyo** [comment]
We really need this one.

**Comment by lmlim** [comment]
just checking, any progress for this addition for AMD yet?

**Comment by fonyo** [comment]
The supported pools are very limited (Nicehash and Suprnova)

**Comment by romulus2k4** [comment]
Incorrect.

[img]https://i.imgur.com/qV84Zdm.jpg[/img]

**Comment by alucard20724** [comment]
doesn't benchmark.. .just keeps closing out

**Comment by romulus2k4** [comment]
Try manually setting the GPU platform to the appropriate value applicable for your PC/card within Miners/MkxminerAmd.txt and It should work.

I have had the weird experience of Mkxminer refusing to work on an RX 580. This is how I was able to solve it. An update is available for this miner too, which bumps the version to 3.01.

If all fails, then switch to AMD's Blockchain driver.
