### ISSUE TITLE
Nvidia XMRig "out of memory"

### ISSUE THREAD

**Issue by czjlj** [MultiPoolMiner/MultiPoolMiner#506]
Same error as 1080ti and 1070.

**Comment by UselessGuru** [comment]
You will have to post this on the miner support site.
This is a miner issue. MPM has no influence on this.

**Comment by aaronsace** [comment]
MultiPoolMiner will detect the failure and is all that can be done.

**Comment by UselessGuru** [comment]
The default memory settings for XMRig are far too over-optimistic.
Try changing '--cuda-launch'
The max I can use:
GTX1080ti: --cuda-launch=64x72
GTX1070: --cuda-launch=53x64
GTX1060 3GB: --cuda-launch=17x77

**Comment by fonyo** [comment]
*Adding awareness for future use. Please don't close this.*

**Comment by UselessGuru** [comment]
BTW: I have reported this issue with the XMRig developers.
