### ISSUE TITLE
Setting intensity parameter in the start.bat file

### ISSUE THREAD

**Issue by Niduin** [MultiPoolMiner/MultiPoolMiner#511]
Is it possible to set a optional intensity parameter in the start.bat file for each miner?
Or would it possible to add this parameter as a optional feature?

Because iam using my pc for mining and working/playing in the same time, so the gpu do not always work on 100% only for mining.

Sorry for my bad english ;-)

**Comment by aaronsace** [comment]
You would have to do it manually for each miner file. 

All the miners are different so it is difficult to have one generic setting but it will be added in the future.

**Comment by UselessGuru** [comment]
Continued here, basically a duplicate: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1143
