### ISSUE TITLE
ccminer - GPU #0: an illegal memory access was encountered

### ISSUE THREAD

**Issue by lukiifaz** [MultiPoolMiner/MultiPoolMiner#526]
`Bin\Lyra2z-NVIDIA\ccminer_cuda9.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:17025 -u  xxxx.xxxx -p x`
Sys: Win 10 
CPU: i7-7700
GPU: GTX 1060 
Drivers:  v388.31 15-11-2017

**Comment by aaronsace** [comment]
Not sure what could be causing that. MultiPoolMiner will skip past the issue. 

I think you are best posting the issue here: 
https://github.com/nicehash/ccminer-nanashi/releases/download/1.7.6-r6/ccminer.zip

**Comment by lukiifaz** [comment]
Miner did not restart himself. It would be helpful to detect this type of error and to automatically restart the miner. During the problem, the value of 12GH / s, normally 1142.52 kH / s. Multipoolminer did not detect the problem.

**Comment by aaronsace** [comment]
Please can you post the log?

**Comment by lukiifaz** [comment]
[2017-11-22_22-33-58.txt](https://github.com/aaronsace/MultiPoolMiner/files/1499222/2017-11-22_22-33-58.txt)

**Comment by aaronsace** [comment]
The speed is 1140KH/s all over our log; where does it say 12000KH/s?

**Comment by aaronsace** [comment]
The figures you pasted at the end are because of this: #525

**Comment by lukiifaz** [comment]
Yes in log is ok but when i have error "GPU #0: an illegal memory access was encountered" miner show  12GH /s.

**Comment by aaronsace** [comment]
So what happens in MultiPoolMiner? 
I can't see 10GH/s...

**Comment by lukiifaz** [comment]
MultiPoolMiner not detect error and i have to restart miner.

**Comment by aaronsace** [comment]
What does it say under "Status: Running"?

**Comment by lukiifaz** [comment]
> 
   Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0,00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\CPU-JayDDee\cpuminer-sse2.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:17025 -u lukii.legion -p x
0,00 PH/s 00 Days 00 Hours 15 Minutes Once     Bin\CPU-JayDDee\cpuminer-sse2.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:20581 -u lukii.legion -p x
0,00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\CPU-JayDDee\cpuminer-aes-avx.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:20581 -u lukii.legion -p x
0,00 PH/s 00 Days 00 Hours 24 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:20581 -u lukii.legion -p x


   Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0,00 PH/s 00 Days 00 Hours 05 Minutes 2 Times  Bin\CPU-JayDDee\cpuminer-aes-avx2.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:17025 -u lukii.legion -p x
0,00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\CPU-JayDDee\cpuminer-aes-avx2.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:20581 -u lukii.legion -p x
0,00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-JayDDee\cpuminer-aes-sse42.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:20581 -u lukii.legion -p x

**Comment by chabgood** [comment]
Are you overclocking?

**Comment by lukiifaz** [comment]
chabgood
"Are you overclocking?"

Yes, but for test i'm back to default settings.

**Comment by chabgood** [comment]
Sure, I have gotten the same error when you overclock too much for your card.

**Comment by aaronsace** [comment]
Ok, so the reading is too high, correct? "452MH/s"
That wasn't in your log...

Does MultiPoolMiner say this? 
"WARNING: Stat file was not updated because the value is outside fault tolerance."

Can you send the stat files?

**Comment by UselessGuru** [comment]
> Oc  Gpu \+200 Mem \+ 950

seems way to high.
My 1060 can do Gpu \+185-160 (curve) and  Mem \+ 650 PL 85%

**Comment by lukiifaz** [comment]
Lenovo legion y720 Im use Oc Gpu+200 Mem + 950 and dont have problem with other miners and games, temperature is stable 69C. But i'm change thermal paste and thermopads.  
UselessGuru what is yours brand  1060 ?

**Comment by UselessGuru** [comment]
> UselessGuru what is yours brand 1060 ?

Gigabyte GeForce GTX 1060 WindForce OC 3G
Too high an overclock actually reduces performance. You may not notice over-overclocking by just checking for artifacts. The gpu will spend lots of cycles fixing memory errors, so that they go unnoticed but eat performance.
Some algorithms are more prone to crashes when overclocked than others. E.g cryptonight or Lyr22z crash sooner.

**Comment by fonyo** [comment]
Clock +200 is not necessary for most algos, a bit of a bump is all you need and mem +950 is way too high, I am surprised you are not experiencing screen tearing and artifacts or a complete blackout every now and then!

**Comment by lukiifaz** [comment]
fonyo but i have this problem without OC. Tomorow i try difrend drivers.

**Comment by fonyo** [comment]
Try the cuda 8 version, cuda 9 compiled ccminers only work with driver version 384.xx or later so please bear that in mind when switching to another driver.

**Comment by aaronsace** [comment]
Ccminer seems to throw masses of errors and a huge haserate when there are other issues also. 
Note to self: check the stat value error checking is working correctly.

**Comment by Lagarinhos** [comment]
I got exactly the same error. My hashrate was near to 300gb/s. I had to remove the algo from my bat.

**Comment by scaras** [comment]
Try to set a manual intensity a little lower then the default on that miner. This is also a fault that occurs if the intensity is set to high by the miner.
