### ISSUE TITLE
Blank cmd window, only cursor blinking

### ISSUE THREAD

**Issue by Pikatju** [MultiPoolMiner/MultiPoolMiner#547]
Once in a while, the overview window will go blank and only have a blinking cursor left. It will stop switching and leave the last used mining program running. 

I have attached the log for that event.
[2017-11-29_20-22-13.txt](https://github.com/aaronsace/MultiPoolMiner/files/1513886/2017-11-29_20-22-13.txt)

**Comment by AdrianAcala** [comment]
@Pikatju,

Can you try right clicking on the top bar, and go to "Defaults" then uncheck "Quick Edit Mode" and "Insert Mode" and try again?

**Comment by UselessGuru** [comment]
Is this still an issue? If not then please close - TIA

**Comment by m-bosch** [comment]
Didn't experience this issue either. probably the edit mode indeed. when you hit the escape-button the window will continue.
