### ISSUE TITLE
prospector.exe has stopped working

### ISSUE THREAD

**Issue by tonymorella** [MultiPoolMiner/MultiPoolMiner#549]
get a popup say "prospector.exe has stopped working"

run command is:
Bin\Prospector\prospector.exe -c MiningPoolHub_CryptoNight.toml

Test in root folder get:
06:44:44 - WARN   Configuration file in default location does not exist. creating it.
06:44:44 - WARN   run prospector.exe --help gen-config to see extended options for generating configuration
06:44:44 - WARN   run prospector.exe --config <file> to specify different configuration
06:44:44 - WARN

Test in Bin\Prospecto works as expected 

the config file had to be full path to work:
bin\Prospector\prospector.exe -c C:\MultiPoolMiner.aaronsace\bin\Prospector\MiningPoolHub_Ethash.toml

**Comment by lee-aaron** [comment]
Could you also attach your logs?

**Comment by UselessGuru** [comment]
Please re-open if this is still a problem.
