### ISSUE TITLE
Cast XMR missing parameters for multigpu systems / Updated to version 0.8.1

### ISSUE THREAD

**Issue by alucard20724** [MultiPoolMiner/MultiPoolMiner#556]
Cast XMR only runs on the first card unless you add the parameter -G 0,1,2 etc etc in the miner file for how ever many cards you are running.

**Comment by chasik** [comment]
+1 It`s right for me.

**Comment by UselessGuru** [comment]
Please test - I don't have AMD hardware to test myself (AMD hardware donations would be very welcome!)

**Comment by borzaka** [comment]
I was unable to test for the first time with this options:
`-username borzaka -workername vegaworker -region europe -currency btc,usd,ltc -type amd -poolname miningpoolhub -algorithm cryptonight -interval 300 -minername Cast -donate 24 -watchdog -switchingprevention 2`

The result:
`WARNING: No miners available.`

After the second run there was an error:
```
C:\Users\Attila\Downloads\MultiPoolMiner-master\ReportStatus.ps1 : Cannot bind argument to parameter 'Address' because it is an empty string.
At C:\Users\Attila\Downloads\MultiPoolMiner-master\MultiPoolMiner.ps1:580 char:64
+ ... Config.MinerStatusURL) {& .\ReportStatus.ps1 -Address $Wallet -Worker ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [ReportStatus.ps1], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,ReportStatus.ps1
```

But the benchmark started:
```
   Type: AMD

Miner Algorithm          Speed btc/Day Accuracy   btc/GH/Day BTC/GH/Day Pool
----- ---------          ----- ------- --------   ---------- ---------- ----
Cast  CryptoNight Benchmarking Unknown      94% 190,54862590  190,54863 MiningPoolHub-Monero

   Status: Running

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 00 Minutes Once     Bin\CryptoNight-Cast\cast_xmr-vega.exe --remoteaccess -S europe.cryptonight-hub.miningpoolhub.com:17024 -u borzaka.vegaworker -p x --nicehash --forcecompute --fastjobswitch --opencl 0 --gpu 0,1,2
```

And after 5 minutes it's looks like the benchmark was successfull:
```
   Type: AMD

Miner Algorithm       Speed    btc/Day Accuracy   btc/GH/Day BTC/GH/Day Pool
----- ---------       -----    ------- --------   ---------- ---------- ----
Cast  CryptoNight 5,93 KH/s 0,00113033      97% 190,54862590  190,54863 MiningPoolHub-Monero
```

The error keeps coming back every interval cycle, and the window is not cleared, it just appends the text.

I have commented on the related [commit](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/12a71085812b314ee3cfca8e66c54004a28c46f1), that there is no `--nicehash` option in Cast XMR, only `--nonicehash`.

> --nonicehash option to disable nicehash support

And why need the `--opencl 0` option?
> openCL platform is auto detected if --opencl is not specified

**Comment by UselessGuru** [comment]
@borzaka Thanks for the feedback

> I was unable to test for the first time with this options:
-username borzaka -workername vegaworker -region europe -currency btc,usd,ltc -type amd -poolname miningpoolhub -algorithm cryptonight -interval 300 -minername Cast -donate 24 -watchdog -switchingprevention 2
The result:
WARNING: No miners available.

You do not have a wallet configured. 

> And why need the --opencl 0 option?

I left it in because of the previous config

[Update to 0.8.1](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/6d909aa1f29f1f2f872a400f7ae11aec6ea1ac25)

**Comment by borzaka** [comment]
> You do not have a wallet configured.
That's true, because I only have a NiceHash internal BTC wallet, which I only include if I'am not testing ;)

**Comment by UselessGuru** [comment]
Is this still an issue? If not then please close - TIA.
