### ISSUE TITLE
Zpool removes Ahash Pool

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#570]
If I add Zpool to list of pools, it removes AHASH pool, if I remove Zpool, it adds Ahash and seems to remove Zpool.  Can you only mine with one or the other?

**Comment by fonyo** [comment]
Thank you for the report, however, ahashpool is not officially supported yet.

**Comment by robl45** [comment]
Honestly, I'm brand new to this.  Its mining away on Ahash now.  The point
is, if I add Zpool multipoolhub and nicehash, it will basically use all
Zpool.  If I remove Zpool it will use almost exclusive Ahash instead of
Zpool.  And if I add in Ahashpool which I found looking in the pools folder
than again it appears to override Zpool.

**Comment by fonyo** [comment]
Please post a log file.

**Comment by robl45** [comment]
Here is log file.  You can see all pools are selected.  If I were to remove ahashpool, the top 3 or so would say Zpool.  If I were just to leave mining pool hub in for pool it would also say Ahash instead of Zpool.  Ahash is 0% right now so I'm happy to use that, but it would seem that it should show Ahash and Zpool instead of just switching between one or another with no option to show both.

[2017-12-07_11-29-15.txt](https://github.com/aaronsace/MultiPoolMiner/files/1539997/2017-12-07_11-29-15.txt)

**Comment by aaronsace** [comment]
@robl45 You seem to simply be misunderstanding what's going on. It does not show every pool; in fact, all pools are always available regardless of you set. PoolName simple prioritizes those pools over the other pools.

**Comment by robl45** [comment]
Fair enough.  But still.  If zpool and a hash pool are listed.  It will
prefer a hash.  If neither zpool and ahash are listed.  It will prefer
ahash.

**Comment by aaronsace** [comment]
Then ahash is more profitable... Or at least at this pint in time.

**Comment by robl45** [comment]
to add to this, I've been running this for a few days now and I am using pools miningpoolhub ahashpool and nicehash set with all algorithms.  It has been mining almost exclusively on ahashpool noting the highest bitcoin value.  I've watched it throughout the day today and after I watched a movie just now and came back to check, it was showing mining pool hub with the top bitcoin rate and not showing anything with ahashpool at all.  They basically all switched to showing Zpool again as I stated above.  I had not restarted the program all day.  I then went and restarted the program just now and Ahash pool is showing again throughout instead of Zpool and is also at the top of the list and it is now mining again on Ahash pool.  I understand that Ahash pool apparently isn't fully implemented yet so I wanted to let you know of the apparent strange things going on.

**Comment by robl45** [comment]
Just to mention, this just happened again now.  for no reason, it switch almost everything to zpool and removed ahashpool.  I restarted and its back to using ahashpool again.  Are the two pools incompatible?

**Comment by robl45** [comment]
Happened again now.  I believe what is happening is multipool miner is removing ahashpool because it thinks it is dead when clearly it is still functioning.  Is there a way to make it less aggressive?

**Comment by jayntguru** [comment]
Ahashpool has been having issues of some sort. I wonder if their profit data is wrong. It looks like all they have is 24 hour actual vs zpool seems to be working off the estimate. I'm not sure if something changed or what.

**Comment by robl45** [comment]
I'm sure the profit figures are inflated, but I've been mining it for over a week now.  It clearly is working and restarting multipool miner gets it going again so its something I believe with watchdog cutting off the pool.

**Comment by UselessGuru** [comment]
Have you tried turning off watchdog?
It could be watchdog kicking the pool after a series of connectivity problems during each loop.
On each loop for each pool the watchdog counter is incremented. If the poll for price info from the pool is successful the counter is reset. 
If the counter reaches 9 (3 x $strikes) the pool will be removed from the list of available pools.
The same happens for miners too.
