### ISSUE TITLE
9 GPU Setup

### ISSUE THREAD

**Issue by repnos** [MultiPoolMiner/MultiPoolMiner#597]
Can I please have a guide how to set this up with 9 gpu rig please? Kinda new and clueless here.

**Comment by aaronsace** [comment]
#522

**Comment by fonyo** [comment]
Drop some info here, what your current start.bat is, what algos are you looking to mine and so on...

**Comment by aaronsace** [comment]
I'll increase the number of Excavator works above 6 in the default configuration but the other than that miners 'should' just run.

**Comment by paulpoco** [comment]
If I go from 1 GPU to 2 GPU of the same kind is there anything special I need to do?  Do reset Benmarking?

**Comment by UselessGuru** [comment]
@paulpoco 

> If I go from 1 GPU to 2 GPU of the same kind is there anything special I need to do? Do reset Benmarking?

Yes. Every time you change something in your system that changes the resulting hashrates (e.g adding GPU's, change OC levels, new intensities) you should run the benchmarks again.
