### ISSUE TITLE
Starting miners without stealing focus?

### ISSUE THREAD

**Issue by garyng** [MultiPoolMiner/MultiPoolMiner#599]
The newly launched miners will always steal the focus even though they are started minimized, it's quite annoying tho.

Any workaround for this?

PS: Some googling lead me to this: [PowerShell Start-Process without taking focus](http://www.daveamenta.com/2013-08/powershell-start-process-without-taking-focus/), is this possible?

Thanks!

**Comment by aaronsace** [comment]
Very messy... I've looked into it before. I'll maybe add the option to hide/consume the miners instead.

**Comment by garyng** [comment]
Yeah... I think at this moment I have to hide them instead...

**Comment by garyng** [comment]
Tried modifying `Minimized` to `Hidden` in `Inlcude.psm1`, but it seems that the script wasn't unable to properly terminate the miners before launching other miners...

**Comment by garyng** [comment]
![image](https://user-images.githubusercontent.com/4453664/33797949-ac3e4b4e-dd4b-11e7-960c-fe70ebffc14e.png)

**Comment by fonyo** [comment]
Due to most miners are having dedicated rigs for mining, I find it annoying that all miner sw are started minimised.

**Comment by grantemsley** [comment]
Mine are all systems that mine when not being used, or lightly used.  Not dedicated.

So the focus stealing is kind of an issue for me.  It's definitely something I will be working on in my own fork.

Making it configurable - normal window, minimized or hidden might satisfy everyone.

But some miners may have issues with their windows being hidden.

**Comment by UselessGuru** [comment]
@garyng 

> Tried modifying Minimized to Hidden in Inlcude.psm1, but it seems that the script wasn't unable to properly terminate the miners before launching other miners...

This does not work because the created process will not have a window handle (hwnd) which is required to kill the process on miner switch. :-(

As @aaronsace has already said - very messy. Powershell does not have a known way of cleanly run a new process minimized, but NOT stealing focus.
I have changed the code in my system to use a custom function 'Invoke-CreateProcess' to create miners WITHOUT losing focus:

`$_.Process = Invoke-CreateProcess -Binary $_.Path -Args (" $($_.Arguments)") -CreationFlags CREATE_NEW_CONSOLE -ShowWindow SW_SHOWNORMAL -StartF STARTF_USESHOWWINDOW -Priority BelowNormal -WorkingDirectory (Split-Path $_.Path)`

```
enum CreationFlags {
    NONE = 0
    DEBUG_PROCESS = 0x00000001
    DEBUG_ONLY_THIS_PROCESS = 0x00000002
    CREATE_SUSPENDED = 0x00000004
    DETACHED_PROCESS = 0x00000008
    CREATE_NEW_CONSOLE = 0x00000010
    CREATE_NEW_PROCESS_GROUP = 0x00000200
    CREATE_UNICODE_ENVIRONMENT = 0x00000400
    CREATE_SEPARATE_WOW_VDM = 0x00000800
    CREATE_SHARED_WOW_VDM = 0x00001000
    CREATE_PROTECTED_PROCESS = 0x00040000
    EXTENDED_STARTUPINFO_PRESENT = 0x00080000
    CREATE_BREAKAWAY_FROM_JOB = 0x01000000
    CREATE_PRESERVE_CODE_AUTHZ_LEVEL = 0x02000000
    CREATE_DEFAULT_ERROR_MODE = 0x04000000
    CREATE_NO_WINDOW = 0x08000000
}

enum ShowWindow {
    SW_HIDE = 0
    SW_SHOWNORMAL = 1
    SW_NORMAL = 1
    SW_SHOWMINIMIZED = 2
    SW_SHOWMAXIMIZED = 3
    SW_MAXIMIZE = 3
    SW_SHOWNOACTIVATE = 4
    SW_SHOW = 5
    SW_MINIMIZE = 6
    SW_SHOWMINNOACTIVE = 7
    SW_SHOWNA = 8
    SW_RESTORE = 9
    SW_SHOWDEFAULT = 10
    SW_FORCEMINIMIZE = 11
    SW_MAX = 11
}

enum STARTF {
    STARTF_USESHOWWINDOW = 0x00000001
    STARTF_USESIZE = 0x00000002
    STARTF_USEPOSITION = 0x00000004
    STARTF_USECOUNTCHARS = 0x00000008
    STARTF_USEFILLATTRIBUTE = 0x00000010
    STARTF_RUNFULLSCREEN = 0x00000020 #ignored for non-x86 platforms
    STARTF_FORCEONFEEDBACK = 0x00000040
    STARTF_FORCEOFFFEEDBACK = 0x00000080
    STARTF_USESTDHANDLES = 0x00000100
}

enum Priority {
    Idle
    BelowNormal
    Normal
    AboveNormal
    High
    RealTime
}

function Invoke-CreateProcess {

    param (
        [Parameter(Mandatory = $True)]
		[string]$Binary,
        
        [Parameter(Mandatory = $False)]
		[string]$Args=$null,
        
        [CreationFlags]
        [Parameter(Mandatory = $True)]
		$CreationFlags,

        [ShowWindow]
        [Parameter(Mandatory = $True)]
		$ShowWindow,

        [StartF]
        [Parameter(Mandatory = $True)]
		$StartF,

        [Priority]
        [Parameter(Mandatory = $True)]
        $Priority,
        
        [Parameter(Mandatory = $False)]
        [String]$WorkingDirectory = ""
	)  
    
    Add-Type -TypeDefinition @"
	using System;
	using System.Diagnostics;
	using System.Runtime.InteropServices;
	
	[StructLayout(LayoutKind.Sequential)]
	public struct PROCESS_INFORMATION
	{
		public IntPtr hProcess; public IntPtr hThread; public uint dwProcessId; public uint dwThreadId;
	}
	
	[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
	public struct STARTUPINFO
	{
		public uint cb; public string lpReserved; public string lpDesktop; public string lpTitle;
		public uint dwX; public uint dwY; public uint dwXSize; public uint dwYSize; public uint dwXCountChars;
		public uint dwYCountChars; public uint dwFillAttribute; public uint dwFlags; public short wShowWindow;
		public short cbReserved2; public IntPtr lpReserved2; public IntPtr hStdInput; public IntPtr hStdOutput;
		public IntPtr hStdError;
	}
	
	[StructLayout(LayoutKind.Sequential)]
	public struct SECURITY_ATTRIBUTES
	{
		public int length; public IntPtr lpSecurityDescriptor; public bool bInheritHandle;
	}
	
	public static class Kernel32
	{
		[DllImport("kernel32.dll", SetLastError=true)]
		public static extern bool CreateProcess(
			string lpApplicationName, string lpCommandLine, ref SECURITY_ATTRIBUTES lpProcessAttributes, 
			ref SECURITY_ATTRIBUTES lpThreadAttributes, bool bInheritHandles, uint dwCreationFlags, 
			IntPtr lpEnvironment, string lpCurrentDirectory, ref STARTUPINFO lpStartupInfo, 
			out PROCESS_INFORMATION lpProcessInformation);
	}
"@

    # StartupInfo Struct
	$StartupInfo = New-Object STARTUPINFO
	$StartupInfo.dwFlags = $StartF # StartupInfo.dwFlag
	$StartupInfo.wShowWindow = $ShowWindow # StartupInfo.ShowWindow
	$StartupInfo.cb = [System.Runtime.InteropServices.Marshal]::SizeOf($StartupInfo) # Struct Size
	
	# ProcessInfo Struct
	$ProcessInfo = New-Object PROCESS_INFORMATION
	
	# SECURITY_ATTRIBUTES Struct (Process & Thread)
	$SecAttr = New-Object SECURITY_ATTRIBUTES
	$SecAttr.Length = [System.Runtime.InteropServices.Marshal]::SizeOf($SecAttr)
	
	if (-not $WorkingDirectory) {
        # CreateProcess --> lpCurrentDirectory
    	$WorkingDirectory = (Get-Item -Path ".\" -Verbose).FullName
    }
	
	# Call CreateProcess
	[Kernel32]::CreateProcess($Binary, $Args, [ref] $SecAttr, [ref] $SecAttr, $true, $CreationFlags, [IntPtr]::Zero, $WorkingDirectory, [ref] $StartupInfo, [ref] $ProcessInfo) | Out-Null

	$Process = Get-Process -Id $ProcessInfo.dwProcessId
    $Process.Handle | Out-Null
    $Process
    
    $Process.PriorityClass = "$Priority"
}

```

**Comment by Vxrl** [comment]
@garyng I made a pull request that stops the miners from stealing focus.

https://github.com/aaronsace/MultiPoolMiner/pull/609

**Comment by garyng** [comment]
I am using `Stop-Process` instead of `.CloseMainWindow()` to stop a `Hidden` miners for now...

**Comment by HaTaX2** [comment]
Personally I prefer seeing the miner windows and I am picky about having them always on my 2nd monitor. On top of that I really don't like the windows stealing focus when it's switching, so I made a few modifications.

I added a few lines into Start.bat and MultiPoolMiner.ps1 to use a utility called 'cmdow'.  It's purpose is to move, resize, restore, etc. windows from the command line. (cmdow's github page: https://ritchielawrence.github.io/cmdow/ ) I'm using this to put the main window on my second screen before it expands, and also to check the currently active window before starting a mining process, and then return focus back to it after the miner has been started and moved on the screen. (In this case since they're minimized I restore them, move them, and then re-activate the previously focused window)

It's not an elegant solution, but it works like a charm for me.  Probably not something that would be useful for everyone, but I could share what I've done if people are interested.

**Comment by crazybrker** [comment]
Can we find the application that is currently in focus with this: 

`Add-Type @"
using System;
using System.Runtime.InteropServices;
public class UserWindows {
[DllImport("user32.dll")]
public static extern IntPtr GetForegroundWindow();
}
"@            
try {            
$ActiveHandle = [UserWindows]::GetForegroundWindow()
$Process = Get-Process | ? {$_.MainWindowHandle -eq $activeHandle}            
$Process | Select ProcessName, @{Name="concentr.exe";Expression=    {($_.MainWindowTitle)}}            
 } catch {            
 Write-Error "Failed to get active Window details. More Info: $_"            
 }`

Feed that to a variable, then launch the miner and then bring the original app back into focus. With something like this:

`param([string] $proc="chrome", [string]$adm)

Add-Type @"
  using System;
  using System.Runtime.InteropServices;
  public class WinAp {
     [DllImport("user32.dll")]
     [return: MarshalAs(UnmanagedType.Bool)]
     public static extern bool SetForegroundWindow(IntPtr hWnd);

     [DllImport("user32.dll")]
     [return: MarshalAs(UnmanagedType.Bool)]
     public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
  }
"@

$p = Get-Process |where {$_.mainWindowTItle }|where {$_.Name -like "$proc"}
$h = $p.MainWindowHandle
[void] [WinAp]::SetForegroundWindow($h)
[void] [WinAp]::ShowWindow($h,3);
`
(2 snips from unrelated scripts)
It's not perfect and you might lose focus for a half a second on each miner swap, but it might be easier to do than to hide it completely.

**Comment by UselessGuru** [comment]
@crazybrker 

If in powershell you start a process hidden then there will be no hwnd available for this process.
Your ideas will unfortunately fail because they require hwnd (=MainWindowHandle) to be available :-(
