### ISSUE TITLE
pull config file from remote source

### ISSUE THREAD

**Issue by theeddie** [MultiPoolMiner/MultiPoolMiner#611]
I have over 40 miners, I hate having to go into each one and change the start file. 

Anyway I can cause it to read the file from a remote site ?

**Comment by fonyo** [comment]
I totally get your point @theeddie. That would actually be a pretty awesome feature. @aaronsace

**Comment by fonyo** [comment]
However, if I think about it, that would create another issue such as all your rigs having the same worker name which is annoying but not a huge problem. The bigger issue is that it would also load the same algorithm list and device type that could cause more serious problems/downtime.

**Comment by aaronsace** [comment]
@theeddie I don't think this is necessary and you can already achieve what you require. 

Put MultiPoolMiner on OneDrive. 

Set only the basic launch parameters that will not change:  
`-wallet [wallet] -username [user] -workername $env:COMPUTERNAME -region europe -currency btc,usd,gbp -donate 24 -watchdog`

Add/remove/edit the files in the pools or miners folders and they are dynamically loaded every 60 seconds.

**Comment by aaronsace** [comment]
If you change any other files then it would require you to close and reopen MultiPoolMiner. This design flaw needs to be fixed if I implement auto updates. The loop from the main miner ps1 file would be moved into a separate script.

**Comment by Kaoz99** [comment]
I'm trying to set this up with OneDrive, how do you go about dealing with the Stats folder? I need different benchmarks per rig.

**Comment by aaronsace** [comment]
@Kaoz99 I just created a folder on OneDrive for each machine then set that to start on system boot.

**Comment by Kaoz99** [comment]
I tried using a single config file with $env:COMPUTERNAME as the worker name but it doesn't seem to work with all miners or pools?

**Comment by Kaoz99** [comment]
I think I found the problem, onedrive is syncing all the json files so all the machines are using the same one. I was hoping to have a single onedrive folder that can easily be modified for all the rigs and just turn off sync for the stats folder but it looks like you really need one folder per rig which isn't ideal?
