### ISSUE TITLE
Mining lyra2rev2 and equihash with excavator

### ISSUE THREAD

**Issue by winnal** [MultiPoolMiner/MultiPoolMiner#646]
Is it possible to make excavator mine and autoswitch between lyra2rev2 and equihash without restarting excavator?

**Comment by aaronsace** [comment]
I've not implemented that yet.

**Comment by borzaka** [comment]
In my case, Excavator is the fastest miner in the following algorithms:
NeoScrypt, Lyra2RE2, Keccak, Nist5

**Comment by UselessGuru** [comment]
Implemented with this:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/a0857c0757ac2577df7c2631e31d746383d5a442
