### ISSUE TITLE
Multiminer around 50% of actual btc earned on MPH

### ISSUE THREAD

**Issue by Korennya** [MultiPoolMiner/MultiPoolMiner#695]
As requested here is the last log file.  As a note, I tried Nemos just now, and its near finished benchmarking, but it's btc/day estimates are 1/2 of MPM, which much more closely mirrors what I"m seeing as payouts from MPH over the past 4 days.

[2017-12-15_15-31-44.txt](https://github.com/aaronsace/MultiPoolMiner/files/1564071/2017-12-15_15-31-44.txt)

**Comment by aaronsace** [comment]
Is this your missing funds? 

http://zpool.ca/?address=1EvnaarQbMmhVg8qaNdUG97MeGZMTQYq3S

**Comment by aaronsace** [comment]
This is the list that you are supposed to use for MiningPoolHub only: 
cryptonight,ethash,ethash2gb,equihash,groestl,lyra2re2,lyra2z,neoscrypt,siaclaymore

**Comment by aaronsace** [comment]
Please note there have been reports of problems with the reported hash rates for these algorithms: 
lyra2re2
lyra2z

**Comment by Korennya** [comment]
No, I'm aware of the funds on zpool and those added with those on MPH are still not over 50%

**Comment by aaronsace** [comment]
Try removing lyra2re2.

**Comment by Korennya** [comment]
Remove that algo and look for what?

**Comment by aaronsace** [comment]
Nothing, just try removing it. Should fix your discrepancy.

**Comment by Korennya** [comment]
Lyra2re2 removed, 

![capture](https://user-images.githubusercontent.com/34586054/34063264-00f11db6-e1bf-11e7-9347-38de24ebfe16.PNG)

**Comment by Korennya** [comment]
Total estimated earnings by MPM is .00166 between two rigs.  Last 24 hour earnings on MPH are 0.00068126.  Zpool's entire earnings over 4 days is 0.00061531.  4 days of zpool, plus one 24 hour period on MPH still doesn't equal what MPM estimates for 1 day.  Even with lyra2v2 off.   Lyra2v2 off isnt' a long term solution either, as it's a resonable algo for nvidia cards.

**Comment by aaronsace** [comment]
There are many reports that the speed that the Lyra2v2 does not match the pool by a huge amount.

**Comment by Korennya** [comment]
So, it's a pool side issue then, not a MPH issue?  I can live with the discrepancy so long as I know why it's there and what to expect in reality.

**Comment by aaronsace** [comment]
I've honestly not got to the root of the problem; you have time test then there are many miner versions. 

CcminerNanashi has been reported to work better but I can't confirm. 

Try removing the hashtag next to lyra2v2 in 'CcminerNanashi.ps1'. 
`#"lyra2v2" = "" #Lyra2RE2`
`"lyra2v2" = "" #Lyra2RE2`

**Comment by Korennya** [comment]
I can do that.. how long would you say is a reasonable amount of time to see the estimate change?

**Comment by aaronsace** [comment]
It maybe as simple as checking the hash rate on the pool matches in which only need 3 hours to form a graph on the pool. There is also two coins (Vertcoin and Monacoin) so you'll have to make sure they are tested separately. 

Another algorithm to check is Lyra2z which has one coin (Zcoin). 

If you are checking payouts then it's probably very hard as PPLNS pays out even after you stop mining. 

If you can get some definitive answers then it would help everyone.

**Comment by JhonJhonny** [comment]
Actually i found a problem with lyra2z in zpool, Lyra2v2 sharing hashes was
almost perfect if it could be helpful. Had some serious problem with mph
and switching to zpool has done the trick

Il 16 Dic 2017 12:38 AM, "aaronsace" <notifications@github.com> ha scritto:

**Comment by komer83** [comment]
Don't mine in Zpool, the pool is "bugged" (no, it's not, it's just the operator playing and take your hash)

**Comment by aaronsace** [comment]
@komer83 As much as I hate Zpool, it is working enough to the point that you will see real profits.

**Comment by joesixpack** [comment]
I've had issues with Lyra2v2 but its bugs in Tpruvot and Ti cards.

What is the exact issue here?  MPM is overestimating what is actually paid out at MPH?

**Comment by Korennya** [comment]
2 issues.  MPM shows about double the actual btc profit per day if lyra2v2 is cycling in the mix.  2nd is that pools are showing significantly lower hash rate than the miner.   I ran excavator lyra2v2 on mph for 3 hours.  Excavator shows 100mh/s while the pool reported back 48mh/s

**Comment by Korennya** [comment]
Also.  During that time.   MPM showed an expected btc per day of .0089.  Where according to pool expectations it should be @.0050 give it take with fluctuations

**Comment by lmlim** [comment]
this may/may not be related to question.
For MPH, I  just mine ethash, equihash, and cryptonight in my option list, at least for now.
this is based on whattomine for 24h profit and 24h difficulty, and NOT current revenue. (THIS IS VERY IMPORTANT)
and i increase interval to 1 hour. (this, also reduce jumping and minimize first 15min devfee)

after change my config to this i was able to earn ~25$-30$/day, before this i set MPM to all available coins and all pools, resulted actually in lower earnings ~15-20/day. around 30-50% loss because you jump too many times.

neoscrypt and lyra2re2 looks tempting at first, but the prices are not stable, you end up jumping too many times, and penalize your earnings.

i suggest check whattomine regularly to change your mining option list.

that's my 0.000001BTC :)

**Comment by UselessGuru** [comment]
Whatever discrepancies between projected and effective profits anyone might see on any pool:
MPM is just using the numbers provided by the pools - if you are not getting what you are being promised then please discuss this with the pool operators. MPM is not the culprit here :-)

**Comment by Korennya** [comment]
Well.. part of the problem is that even what to mine shows that I should be making .00045 btc/day on L2v2, which is more or less in line with actual profits, yet MPM shows that with only l2v2 running that estimates are .0008-.0009 btc per day.

**Comment by lmlim** [comment]
@Korennya i mostly compare my real earnings rather than stats from miners.

@UselessGuru yes, the exchange part is very crucial too, that's why i recommend mine more of stable price algos than "hi price" algos. ie: advertised price != exchanged price. 
also some coins in zpool for example, will not pay you until several days.

I can see now why Aaronsace did not put all available algos in his start.bat.

I missed the NH simplicity, yet effective.

**Comment by mikepartin333** [comment]
I have noticed this issue as well, primarily with Monacoin in MPH.  The problem is that my miner does well with Monacoin, but only half what does is shown.  That coin has been the most profitable multiple times per day, thus leading to the obviousness of the problem.  I have temporarily removed it and expect to see higher profit, but I would like to see a functioning version in MPM.

Has there been any studies on -interval increase in relation to profit in MPM?  I have been playing around, but not long enough to see changes.

I have been interested in mining for many years, but just know have been able to start.  I have been on the steep learning curve for exactly 11 days now. I have very much enjoyed looking at MPM, and using it as a learning tool.  You guys are doing a great job!

**Comment by 3zero2** [comment]
@aaronsace Why is the list of algos recommended for MPH restricted to cryptonight,ethash,ethash2gb,equihash,groestl,lyra2re2,lyra2z,neoscrypt,siaclaymore?

For example there is Keccak, X11 and other algos that can be included and that are supported by MPH.

**Comment by aaronsace** [comment]
@3zero2 They're common and _profitable_.

**Comment by 88plug** [comment]
Guys MPH is NOT your friend.  Too many hours spent on this problem -  Switch to Coinotron for accurate reporting for Lyra2v2.

**Comment by carlo0000** [comment]
so i have build a 1080i ring  but the display  earning in multipool is far from the real earning
i puted my ring on a separate btc address to  test    i earned  0,0019509  it s far from the 
MultiPoolMiner    0,00673 ±58 % (0,00426-0,01063) 90,58002 ±58 % (57,36473-143,02762)

i reset the profit couple of time and each time multipool tells me earning more than 50$ up to 90 lol
it s even less than what whattomine says

definitely someting not right  or some pool steels a lot from us

**Comment by Coin-Digger** [comment]
@lmlim 
I would like to follow your instruction to earn more, and will choose the algos according to WhatToMine , but could you give a advice where to increase jump interval to 1 hour?

**Comment by lmlim** [comment]
@Coin-Digger 
for MPM older version, i used to bumped up "-interval" only to 120 or 300, bec MPM has shortcomings.
or else just download the current version, and play with "-preventswitching". (3 or 4 maybe)
i have not test this option thoroughly... for MPH pool you really need only top 3 algos. 

the trick is dont switch too many times.

**Comment by Coin-Digger** [comment]
@lmlim 
So if I use old version, I just put parameter "-interval 120” or "-interval 300” in the file "Start-MiningPoolHub.bat", is it correct?

**Comment by UselessGuru** [comment]
> jump interval to 1 hour?

There is no such thing as jump interval.

MPM loops in intervals (variable -Interval in start.bat - see the readme).
If at the start of the loop another algo became the most profitable it will switch.

SwitchingPrevention (the name might be slightly misleading but captures the idea) tells MPM how 'bouncy' a price information can be until it is considered a reliable price for choosing the miner. The higher this number, the more stable prices (accuracy) are preferred.

@aaronsace: Correct me if I am wrong

**Comment by carlo0000** [comment]
anyway it s not the switch problem  i already had interval at 220
i think it just mine some not profitable algo (i put all algo on my nvida ring)
gonna back to old start.bat with only selecting some algo
on my amd ring the earning looks realistic but not on nvidia
the earning is  even worse than i stick to 1 algo (example verge iyra2r2 on whattomine) 
i notice it mined a lot on x17 & veltor

**Comment by UselessGuru** [comment]
> (i put all algo on my nvida ring)

BIIIIIIIIIIIIIIIIIIIIIIG mistake... :-( Stick to the algos recommended in the [readme](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.txt). Then you can start experimenting.
Also do not use all pools. Trying to always jump on the fastest bandwagon (= supposedly best paying miner) will not help.

lyra2r2 is dodgy - see [readme](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.txt)

**Comment by carlo0000** [comment]
ok
