### ISSUE TITLE
2.7.1 not displaying info at the bottom

### ISSUE THREAD

**Issue by jayntguru** [MultiPoolMiner/MultiPoolMiner#711]
2.7.0.2 displayed a total at the bottom like this. 2.7.1 doesn't seem to do this. Is this intentional or am I missing something?

Miner                         USD                            BTC
-----                         ---                            ---
MultiPoolMiner                4.00934 ±13% (3.56302-4.51158) 0.00021 ±13% (0.00019-0.00024)
ClaymoreAmdLbry40-Ethash/Lbry 4.42200 ±10% (4.00369-4.88400) 0.00023 ±10% (0.00021-0.00026)

**Comment by migdiluca** [comment]
It's not displaying here either.

**Comment by feernandobraga** [comment]
I'm having a different issue, where the value that is being shown is quite off from reality.
Unfortunately, I'm not making 5k a day. Any idea on how to fix it?
I know that Lyra2RE2 has been reported for showing a wrong value, but this scenario is happening with different algos as well.
I guess that this issue will also impact on the "most profitable" decision, right? So I'm probably not mining the best algo for me.

![img_3795](https://user-images.githubusercontent.com/20088768/34079274-d8fa392a-e37e-11e7-877f-693a75292850.JPG)

**Comment by migdiluca** [comment]
I stop cpu mining and now I can see it, I guess mining with the cpu is what cause it.

**Comment by aaronsace** [comment]
Can you post the logs?

**Comment by thericeking** [comment]
I can confirm that this was happening to me earlier. Didn't show for a few hours. I restarted the mining a few times before I started to see it again. I like it to remain there until it switches to a different algo. Thank you

**Comment by jayntguru** [comment]
[2017-12-17_01-37-47.txt](https://github.com/aaronsace/MultiPoolMiner/files/1565998/2017-12-17_01-37-47.txt)

Here's one where it's in there sometimes and sometimes it isn't.

-JS

**Comment by jayntguru** [comment]
[2017-12-17_15-01-18.txt](https://github.com/aaronsace/MultiPoolMiner/files/1566000/2017-12-17_15-01-18.txt)

Here's one where it doesn't work out of the gate.

-JS

**Comment by FabianGabor** [comment]
Having similar issue. Income stats at the bottom not showing all the time. Sometimes it appears and after the next refresh it disappears then reappears again after some time.

**Comment by feernandobraga** [comment]
Here is my log. It started to happen after resetting the benchmark. So must be something related but I couldn't spot exactly what is causing this astronomic values.
Since I'm not on my computer I had to upload the log file to my google drive. I apologize for that
https://drive.google.com/open?id=1XIKJA-n8pv3_1t-xycFXNldwCxqr8wp2

**Comment by ChriscomIT** [comment]
Same for me as for @feernandobraga but with lyra2z on ccminerlyra2z_cuda9. Will upload logs later.

**Comment by r1rider01** [comment]
any updates on this?

**Comment by nichenke** [comment]
I'm no expert in PowerShell, but limited debugging here shows that the Downloader is still Running -- it looks to be the miner downloads. Not sure how to triage why the GC and things cleaning up that background task aren't cleaning up the state.

**Comment by nichenke** [comment]
Following up -- the script (Downloaders.ps1) is taking 3-4 seconds to run. Adding a sleep 5 (oldest programmer trick) before the check allows it to finish. No idea what takes so long, but localized hack works and perhaps this info gives the guys with Powershell knowledge enough to fix.

**Comment by fonyo** [comment]
@feernandobraga run resetprofit.bat
