### ISSUE TITLE
MPM not mining most profitable algo

### ISSUE THREAD

**Issue by Cuddl3z** [MultiPoolMiner/MultiPoolMiner#713]
As title says, profitablility chart says that ccminer for Neoscrypt is more profitable  but MPM chose to mine equihash with excavator.

Noticed that it was doing this as I got up this morning.  It was mining lyra at 0.00037BTC/day when equihash was at 0.00040 BTC/day.  Restarted MPM with only equihash algo and was getting 0.00040 BTC/day.

Now I restarted MPM with all algos and it chooses the 2nd most profitable...  am I doing something wrong??

```
Type: NVIDIA

Miner                  Algorithm                                    Speed            BTC/Day         BTC/GH/Day Pool
-----                  ---------                                    -----            -------         ---------- ----
CcminerKlaust          NeoScrypt                                1.65 MH/s            0.00043            0.25961 MiningPoolHub-Feathercoin
ExcavatorNvidia3       Equihash                               697.65  H/s            0.00042          603.40360 MiningPoolHub-Zencash
ExcavatorNvidia2       Equihash                               693.00  H/s            0.00042          603.40360 MiningPoolHub-Zencash



   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 23456 -c MiningPoolHub_Equihash_3_Nvidia.json -na
```

**Comment by UselessGuru** [comment]
@Cuddl3z 

See my comment [here](https://github.com/aaronsace/MultiPoolMiner/issues/712)

**Comment by Cuddl3z** [comment]
Thanks for that.

As I understand it, the miner MPM give instant price/profitability readings and the pool MPH take a 24hr price point.  

Since I am mining based on MPH value, there is a disconnect.

Would it be possible for MPM to display the MPH values in that case?

Thanks for all this great work!

**Comment by fonyo** [comment]
*Time to update the README to clarify this new behaviour in 2.7*

**Comment by fonyo** [comment]
Added, query re NH to be resolved or omitted as per https://github.com/aaronsace/MultiPoolMiner/issues/712#issuecomment-352441381

**Comment by UselessGuru** [comment]
@Cuddl3z 
>the miner MPM give instant price/profitability readings

On first run MPM cannot determine the stability of the pricing info received by the pool (it has no comparison data available). So whatever price it receives will be used to determine the best profit. Over time - as MPM re-reads pricing information - it can slowly determine price stability and will find the best algo in the longer run.

**Comment by Horsetoothless** [comment]
Have noticed this too checking MPH payout stats page and what miner is doing, added Skein to my algos,
Have had several HARD CRASHES of my system! Rolled back GPU drivers as Nicehack not implemented YET! Several seem to occur right after MPM switches to skein, still digging for more information on exact cause.

**Comment by fonyo** [comment]
Added to the README, Logic section.
