### ISSUE TITLE
ccminer with build in vcruntime140.dll

### ISSUE THREAD

**Issue by somidax** [MultiPoolMiner/MultiPoolMiner#74]
After testing the new version on pre-lunched, I notice that my ccminer refused to start as it crashes due To vcruntime140.dll

Several attempt to reinstall vc x64 2015 to power it up, ccminer still won't start. 

A further investigation trying to download and run trupvot 2.0 to run it directly, it works perfectly.

I will appreciate if you can build or integrate the vcruntime140.dll so that the ccminer that runs with your application operates like a standalone system needing less interference. By doing this, the ccminer can call up the vcruntime140.dll which is required to start it.

Kindly look into doing this as I really appreciate your works and will be sending some BTC. Note"this normally occure using Lyra2z algorithm for the rest is perfect👍🏿

**Comment by somidax** [comment]
Find attached evidence of failed ccminer. "PFA screen short as well as log files"
[2017-04-16_07-53-30.txt](https://github.com/aaronsace/MultiPoolMiner/files/924270/2017-04-16_07-53-30.txt)
![failed ccminer](https://cloud.githubusercontent.com/assets/23489369/25071230/a3fa28d4-22a9-11e7-808b-f33d0907096c.JPG)
![failed ccminer-1](https://cloud.githubusercontent.com/assets/23489369/25071231/a4581b1a-22a9-11e7-94e1-8c1c14b4a5e3.JPG)
![new issue - multipoolminer](https://cloud.githubusercontent.com/assets/23489369/25071232/a48abb6a-22a9-11e7-90f1-09479a0cd2dd.jpg)

**Comment by somidax** [comment]
kindly check new observed errors as pro-released 
[2017-04-18_05-59-23.txt](https://github.com/aaronsace/MultiPoolMiner/files/927375/2017-04-18_05-59-23.txt)
software experience failure when relaunched. find attached new log for details

**Comment by grantemsley** [comment]
Closing outdated issue.  If this is still a problem in the latest version (and there currently isn't an open issue for it) please open a new one.
