### ISSUE TITLE
-switchingprevention possible bug

### ISSUE THREAD

**Issue by AymanEG** [MultiPoolMiner/MultiPoolMiner#758]
Hello again,

I traced using the new command parameters with default value of "10"
-switchingprevention 10

I believe it doesn't recalculate the best to mine before switching.

Example : Mining x17 now, then blakecoin become more profitable ,so the miner will queue to mine blakecoin ,but before the end of the 10 mins Lyra2RE2 become more profitable than blakecoin ,but when the miner switch it will switch to blakecoin not Lyra2RE2.

Example Proof : Here the miner switched to the wrong algorithm
![miner-9-1](https://user-images.githubusercontent.com/23207050/34181635-b3df7ae4-e51b-11e7-9d3c-41d33363eb49.PNG)
![miner-9](https://user-images.githubusercontent.com/23207050/34181636-b400c988-e51b-11e7-9b9a-67c09dd8fcf3.PNG)
![miner-9-2](https://user-images.githubusercontent.com/23207050/34181753-281c5bc0-e51c-11e7-9f48-9b1986fc589e.PNG)

**Comment by AymanEG** [comment]
Bug update :
Also it appears it have to complete the time for all algos even if it is not the most profitable right now. Please fix it

**Comment by jpmckearin** [comment]
@AymanEG please don’t create an issue pertaining to an open source project exclaiming “Please fix it”. If this issue is a priority for yourself then feel free to submit a pull request with a fix.

**Comment by AymanEG** [comment]
@jpmckearin As title explained "-switchingprevention possible bug" I was suspecting it was bug , in the second comment I confirmed the bug. If I know how to fix I would, I participate by submitting bugs and that count as help as well for open source projects not only coding speaking with 3+ years on wordpress open source projects ,so I believe I helped with the 2 previous comments unlike you. Your comment did not confirm the bug issue instead commenting on my comments

**Comment by Lagarinhos** [comment]
U download the master version. What do you expected? Use the released version instead and this "bug" wont exist. ;)

**Comment by robl45** [comment]
I appear to have a bug with this as well.  When starting it keeps going to bitcore even though bitcore is way down in the list on profitability and then switches to the profitable one.  Has happened multiple times on multiple starts.

**Comment by AymanEG** [comment]
@Lagarinhos  and how @aaronsace will know about bugs ?! lol

**Comment by AymanEG** [comment]
@robl45  you mean like this :
![miner-9-3](https://user-images.githubusercontent.com/23207050/34234736-8fef4df0-e5f5-11e7-9514-62711a628a4a.PNG)

**Comment by robl45** [comment]
Yes exactly like that.

**Comment by angelics** [comment]
switching prevention should apply only to pplns pools - miningpoolhub. just my suggestion

**Comment by AymanEG** [comment]
@angelics Can you explain more please ?!

@aaronsace Update #3 : 
I think when the software do benchmark it logs the time,then to check with switchingprevention and must complete the minimum time for all, I just added phi and hsr after ur last update and now the miner is mining them even they are not the best one

**Comment by angelics** [comment]
zpool pays for everyshare submitted when a block is found. while miningpoolhub is pplns pool, u'll need to stay for a bit more to get paid for what u submitted.

**Comment by Lagarinhos** [comment]
The way u said.. like demanding a fix. If it is a bug on the master, dev will know that need to be fixed ;) u dont need "Please fix it!"

**Comment by robl45** [comment]
Now it was just mining bitcore again which is half way down my list for no apparent reason and now has switched back to a profitable algorithm just about at the top.  This has been running since this morning so it wasn't restarted.

**Comment by aaronsace** [comment]
This is the code branch guys not a release.  

Please update to todays build then post logs.

**Comment by AymanEG** [comment]
@angelics 

`zpool pays for everyshare submitted when a block is found. while miningpoolhub is pplns pool, u'll need to stay for a bit more to get paid for what u submitted.`

So as I understand and please feel free to correct me : zpool I can switch as much as I want once the block is found as I will get paid but I should never switch before finding the block ,but I can switch at miningpoolhub as much as I can ?!

I a mining at zpool x17 wich find a block every 5 minutes so with switching after 10 min I should find 12 at least 2 blocks and I lose the 3rd block share only, correct ?!

**Comment by AymanEG** [comment]
The new accuracy thing is mysterious 

[2017-12-21_02-17-01.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581576/2017-12-21_02-17-01.txt)
[2017-12-21_02-23-55.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581577/2017-12-21_02-23-55.txt)
[2017-12-21_02-28-29.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581578/2017-12-21_02-28-29.txt)
[2017-12-21_02-34-18.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581579/2017-12-21_02-34-18.txt)
[2017-12-21_07-09-37.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581580/2017-12-21_07-09-37.txt)
[2017-12-21_08-25-06.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581581/2017-12-21_08-25-06.txt)
[2017-12-21_21-33-45.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581582/2017-12-21_21-33-45.txt)
[2017-12-21_21-50-53.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581583/2017-12-21_21-50-53.txt)
[2017-12-21_21-51-31.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581584/2017-12-21_21-51-31.txt)
[2017-12-22_07-25-01.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581585/2017-12-22_07-25-01.txt)

**Comment by robl45** [comment]
I gave up on it for now. Removed switching prevention and now it mines profitable coin instead of Bitcore.

**Comment by AymanEG** [comment]
@robl45 yea same here

**Comment by aaronsace** [comment]
@AymanEG Your log is spot on; I'll push this in the next release unless anyone else has any logs from the _latest_ commits with a longer runtime.

**Comment by robl45** [comment]
So testing now with interval at 2 minutes and no switching prevention, currently I'm doing like 5 dollars a day.  Before I made the switch, I could barely get to 3 dollars a day.

**Comment by aaronsace** [comment]
@robl45 Are you looking at actual profits or what MultiPoolMiner is reporting?

**Comment by robl45** [comment]
I am taking a point in time on ahash pool and then subtracting that from the current earnings amount to get actual profit.

**Comment by ChriscomIT** [comment]
With the latest master, all is running pretty well for me. Despite some slight inaccuracies which are smoothing out pretty fast after a bunch of seconds after start. As I understand and as I discovered this is the purpose of the "-switchingprevention" so for me MPM did choose the most profitable algorithm in combination/regards to the biggest accuracy which in the end gave me the most income and far less switching.
