### ISSUE TITLE
New Algos?

### ISSUE THREAD

**Issue by tboy1337** [MultiPoolMiner/MultiPoolMiner#759]
Any plan to add xevan, hsr, phi, polytimos from zpool?

**Comment by FabianGabor** [comment]
You can add it manually by editing the Start-Zpool.bat file and the miner ps1 files.

**Comment by robl45** [comment]
I was going to ask about HSR on Ahashpool.  It works very well on my card.  How would you add an algorithm that is not currently supported?

**Comment by paulpoco** [comment]
I think you need to edit Start.bat and add them there.

I think Start-Zpool.bat has the info for the Dev to mine their 24min

**Comment by paulpoco** [comment]
Looking at Algorithms.txt - phi and hsr are not included.

**Comment by UselessGuru** [comment]
@tboy1337 
> Any plan to add xevan, hsr, phi, polytimos from zpool

Polytimos and Xevan are already there, just add them to the start.bat
HSR & Phi are coming, see 
https://github.com/aaronsace/MultiPoolMiner/pull/764
https://github.com/aaronsace/MultiPoolMiner/pull/763

@paulpoco 
> Looking at Algorithms.txt - phi and hsr are not included.

Not all supported algos need to be in Algorithms.txt.

**Comment by tboy1337** [comment]
I'm just going on what the readme says, I don't have time to try random things to see if they work xD

**Comment by FabianGabor** [comment]
CCminerTrupot works for hsr, phi, polytimos

**Comment by UselessGuru** [comment]
@FabianGabor 

>> CCminerTrupot works for hsr, phi, polytimos

Yep, but CcminerHSR and CcminerPolytimos are faster alternatives for these two algorithms
