### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by tboy1337** [MultiPoolMiner/MultiPoolMiner#760]
Do you take pool fees into consideration when choosing most profitable coin? Also do you plan to make the miner into a full install-able program in the future?

**Comment by UselessGuru** [comment]
> Do you take pool fees into consideration when choosing most profitable coin? 

No, Currently not

**Comment by tboy1337** [comment]
Any plans to?

**Comment by fonyo** [comment]
@tboy1337 Yes, planned feature for V3.
