### ISSUE TITLE
zpool yescrypt hashrate 

### ISSUE THREAD

**Issue by nova-ace** [MultiPoolMiner/MultiPoolMiner#761]
It appears that zpool reports yescrypt hasrate and profitability in kh/s. This is an easy fix in the zpool.ps1 if you are interested in running yescrypt.

**Comment by paulpoco** [comment]
The zpool website shows MH/s

**Comment by UselessGuru** [comment]
With which miner are you mining yescrypt?

**Comment by nova-ace** [comment]
I was just playing with Jaddee cpuminer. I noticed that the profitability on Hashrefinery was 3 orders of magnitude different than zpool. It looks like the zpool charts are using mBTC/kH/day even though their footnote claims everything is in MH/day. 
![zpool](https://user-images.githubusercontent.com/4156269/34221212-76c0828a-e574-11e7-9e8a-3c8d3945b63a.PNG)

**Comment by fonyo** [comment]
Please post this bug on zpool's BTCtalk page if it is not yet fixed.
