### ISSUE TITLE
Ethash benchmarking when not included in algorithms

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#767]
My current card cannot do ethash.  I only have ethash 2gb in algorithms yet it tries to benchmark ethash anyway along with ethash 2gb

**Comment by komer83** [comment]
You can delete Ethash from the miner configuration files.

**Comment by robl45** [comment]
I suppose I could, but it shouldn't be using it at all if the algorith only has ethash2gb listed.

**Comment by UselessGuru** [comment]
See https://github.com/MultiPoolMiner/MultiPoolMiner/commit/be739cbad99aa52a0403fc28ca4f8585f2ba6945

Please test and report back - thank you!

**Comment by borzaka** [comment]
Tested with AMD (3x Vega 64), only `ethash2gb` algorithm was added.

Fist run, only warnings, nothing happened:
```
WARNING: Cannot download C:\Users\Attila\Downloads\MultiPoolMiner-master\Bin\Ethash-Claymore\EthDcrMiner64.exe.
WARNING: Searching for C:\Users\Attila\Downloads\MultiPoolMiner-master\Bin\Ethash-Claymore\EthDcrMiner64.exe.
WARNING: Cannot find C:\Users\Attila\Downloads\MultiPoolMiner-master\Bin\Ethash-Claymore\EthDcrMiner64.exe.
```
And the missing wallet error:
```
C:\Users\Attila\Downloads\MultiPoolMiner-master\ReportStatus.ps1 : Cannot bind argument to parameter 'Address' because it is an empty string.
At C:\Users\Attila\Downloads\MultiPoolMiner-master\MultiPoolMiner.ps1:580 char:64
+ ... Config.MinerStatusURL) {& .\ReportStatus.ps1 -Address $Wallet -Worker ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [ReportStatus.ps1], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,ReportStatus.ps1
```


Second run:
- Eminer benchmarked successfully.
- Prospector miner had errors:
```
   Status: Running

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 00 Minutes Once     Bin\Prospector\prospector.exe -c _Ethash2gb_.toml
```
```
21:28:57 - INFO   prospector 0.0.13-ALPHA starting
Could not load  cuda library dll/so
21:28:57 - ERROR  Could not load CUDA: Unknown error - Unknown error
21:28:57 - INFO   OpenCL Initialized
21:28:57 - WARN   Configuration file in default location does not exist. creating it.
21:28:57 - WARN   run prospector.exe --help gen-config to see extended options for generating configuration
21:28:57 - WARN   run prospector.exe --config <file> to specify different configuration
21:28:57 - WARN
21:28:57 - INFO   Generated configuration saved in config.toml
21:28:57 - INFO   Configuration successfuly loaded from config.toml
21:28:57 - INFO   Not launching CPU miner
21:28:57 - INFO   Miner starting on gpu 0-0 - gfx901
21:28:57 - INFO   Miner starting on gpu 0-1 - gfx901
21:28:57 - INFO   Miner starting on gpu 0-2 - gfx901
21:28:57 - INFO   Device 0-3 disabled
21:28:57 - INFO   Starting api server on localhost:42000/api/v0/
21:28:57 - ERROR  Signatum: network client disconnected, Trying to reconnect
```
Had to exclude to continue testing.
- EthminerAmd benchmarked successfully.

No more algorithm or miner started to benchmark.

**Comment by UselessGuru** [comment]
@borzaka 

Please do not mix different errors in the same issue - thanks! It makes issues very difficult to track.

As I see it is EthminerAmd working successfully. The download error messages are 'normal'. MPM is faster than your download. Nothing to worry about.

Missing $wallet:
Please post your start.bat

Regarding the prospector issue:
Please create a new issue and upload logs. Thank yo.

**Comment by borzaka** [comment]
My start.bat:
`-username borzaka -workername vegaworker -region europe -currency btc,usd,ltc -type amd -poolname miningpoolhub -algorithm ethash2gb -interval 60 -donate 24 -watchdog -switchingprevention 2`

I have opened a new issue regarding the Prospector miner error. See referenced issue.

**Comment by UselessGuru** [comment]
[You did not specify your wallet](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#sample-usage)

**Comment by borzaka** [comment]
That's true, but what if I don't have a wallet address, or I don't need one to specify, because my username is enough. For example in Mining Pool Hub.

Quote from the README:
> -wallet Your Bitcoin payout address. Required when mining on Zpool, Hash Refinery and Nicehash.

I was mining to miningpoolhub.

**Comment by UselessGuru** [comment]
[The missing wallet error has been fixed](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/dca820cc5d94e93b89379912a9ccb8fff8172c73)
