### ISSUE TITLE
Profit not appearing at the bottom

### ISSUE THREAD

**Issue by Lagarinhos** [MultiPoolMiner/MultiPoolMiner#769]
With the new changes implemented with Profit Switching prevention, the profit at the bottom no longer is displayed, at least here. I just replaced the multipoolminer.ps1 and added the paramater at the bat. Should I benchmark again or is it a bug? 
The -switchingprevention 10 means 10minutes? 
thks

**Comment by jayntguru** [comment]
Duplicate. https://github.com/aaronsace/MultiPoolMiner/issues/711

**Comment by Lagarinhos** [comment]
Thks. But not the case. It was ok on this last release at least for me. I just updated to test the last change about profit switching prevention and that was when stoped showing it.

**Comment by fonyo** [comment]
It is duplicate indeed
