### ISSUE TITLE
No Pool Available Error on command prompt

### ISSUE THREAD

**Issue by orhnctnr** [MultiPoolMiner/MultiPoolMiner#773]
My bat file is working well for a long time but in last few days i am getting " no pool available " error in main cmd page after it works for 1-2 hours. Whats the matter ?

**Comment by aaronsace** [comment]
Please post logs.

**Comment by orhnctnr** [comment]
This is the log file for today. I have also getting some other errors. It says "status failed" and some other warnings like ; "WARNING: Stat file (NsgminerAmd_NeoScrypt_HashRate) was not updated because the value (40000) is outside fault tolerance "
[2017-12-20_20-46-57.txt](https://github.com/aaronsace/MultiPoolMiner/files/1576857/2017-12-20_20-46-57.txt)

**Comment by aaronsace** [comment]
Your hash rates are dropping on all the miners and you have no backup pools. 

Why are your hash rates dropping?

**Comment by orhnctnr** [comment]
Backup Pools ? 

I dont know , i am not doing anything on pc when its working.

**Comment by aaronsace** [comment]
Try turning CPU mining off.

**Comment by aaronsace** [comment]
I've just noticed, you're earning more on the CPU than the GPU. Do you actually have a graphics card?

**Comment by aaronsace** [comment]
The hash rates are so low, you could just turn watchdog off and you'll never get this problem again. 

The watchdog timer is the mining rigs really.

**Comment by orhnctnr** [comment]
lol , yeah but a shit one  r9 270x 2gb. 

So should i make it -watchdog 0  ?

**Comment by aaronsace** [comment]
Just remove the command.

**Comment by orhnctnr** [comment]
Okay , i will try for an hour than post the log again . Ty

**Comment by orhnctnr** [comment]
@aaronsace 
[2017-12-21_00-57-25.txt](https://github.com/aaronsace/MultiPoolMiner/files/1578420/2017-12-21_00-57-25.txt)
This is the last log file. It seems my gpu's hashrate is incredibly lower than my cpu , why ? I couldnt optimize it. Is that hashrate possible for and graphic card ? 

And also what are these errors ; 
WARNING: Stat file (ClaymoreAmd_CryptoNight_HashRate) was not updated because the value (61) is outside fault tolerance.
WARNING: Stat file (XmrigCpu_CryptoNight_HashRate) was not updated because the value (274) is outside fault tolerance.

**Comment by UselessGuru** [comment]
@orhnctnr 
> WARNING: Stat file (ClaymoreAmd_CryptoNight_HashRate) was not updated because the value (61) is outside fault tolerance.
WARNING: Stat file (XmrigCpu_CryptoNight_HashRate) was not updated because the value (274) is outside fault tolerance.

This means the current hashrate is considerably lower (or higher) then the initial hashrate measured during initial benchmark. It might be caused by CPU mining slowing down interaction with the GPU miner.

I suggest you stop mining on you CPU - if you are taking electricity costs into account it won't be profitable anyway (unless someone else is paying your electricity bill that is).

**Comment by orhnctnr** [comment]
Okay , i ll try it. Just deleting -cpu from bat file

**Comment by orhnctnr** [comment]
Just a quick question , can it be related with psu ?

**Comment by orhnctnr** [comment]
[2017-12-21_12-17-00.txt](https://github.com/aaronsace/MultiPoolMiner/files/1578707/2017-12-21_12-17-00.txt)
Logs for only Gpu mining for 30 mins.

**Comment by UselessGuru** [comment]
> Just a quick question , can it be related with psu ?

You mean power supply?
Most likely not. If power is unstable then the computer will restart automatically.
