### ISSUE TITLE
NetFirewallApplicationFilter - Invalid Class

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#779]
Hi everyone,

Ive searched through the issues here and i didnt found the error im getting:

> Get-NetFirewallApplicationFilter : Invalid class 
> At C:\Users\satan\Desktop\MULTIPOOLMINER\MultiPoolMiner.ps1:253 char:59
> + ... eq $null) {$MinerFirewalls = Get-NetFirewallApplicationFilter | Selec ...
> +                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : MetadataError: (MSFT_NetApplicationFilter:root/standardci...plicationFilter) [Get-NetFirewallApplicationFilter], CimException
> + FullyQualifiedErrorId : HRESULT 0x80041010,Get-NetFirewallApplicationFilter

Im running the "Start-MiningPoolHub.bat" from a folder on the desktop, in Admin mode. Oddly, ive tried MPM on another machine with Windows 10 and this error doesnt popup...

As far as i can tell, the benchmarking goes through and the miners dont report connection issues.

There's also a download issue with a miner:

WARNING: Cannot find C:\MPM\Bin\NVIDIA-Palgin\ccminer.exe distributed at https://github.com/palginpav/ccminer/releases/download/1.1.1/palginmod_1.1_x64.zip

The file does not exist on GitHub.

I've attached the Log:
[2017-12-21_09-54-53.txt](https://github.com/aaronsace/MultiPoolMiner/files/1578764/2017-12-21_09-54-53.txt)

**Comment by UselessGuru** [comment]
Are you using a 3party firewall software (non microsoft)?

**Comment by titvs** [comment]
No... Running W10 normally.
I didnt mention but Ive also added the folder to the Defender exclusion list. Since this error doesnt popup on the other W10 machine im thinking its maybe related to somekind of MSFT update...

**Comment by boredazfcuk** [comment]
+1, I have same issue.

Thanks.

**Comment by UselessGuru** [comment]
@boredazfcuk 
Are you using a 3party firewall software (non microsoft)?
If yes try my proposed change https://github.com/MultiPoolMiner/MultiPoolMiner/pull/754
```
    if (Get-Command "Get-MpPreference" -ErrorAction SilentlyContinue) {
        if ((Get-Command "Get-MpComputerStatus" -ErrorAction SilentlyContinue) -and (Get-MpComputerStatus -ErrorAction SilentlyContinue)) {
            if (Get-Command "Get-NetFirewallRule" -ErrorAction SilentlyContinue) {
                if ($MinerFirewalls -eq $null) {$MinerFirewalls = Get-NetFirewallRule | Where-Object DisplayName -EQ "MultiPoolMiner" | Get-NetFirewallApplicationFilter | Select-Object -ExpandProperty Program}
                if (@($AllMiners | Select-Object -ExpandProperty Path -Unique) | Compare-Object @($MinerFirewalls) | Where-Object SideIndicator -EQ "=>") {
                    Start-Process (@{desktop = "powershell"; core = "pwsh"}.$PSEdition) ("-Command Import-Module '$env:Windir\System32\WindowsPowerShell\v1.0\Modules\NetSecurity\NetSecurity.psd1'; ('$(@($AllMiners | Select-Object -ExpandProperty Path -Unique) | Compare-Object @($MinerFirewalls) | Where-Object SideIndicator -EQ '=>' | Select-Object -ExpandProperty InputObject | ConvertTo-Json -Compress)' | ConvertFrom-Json) | ForEach {New-NetFirewallRule -DisplayName 'MultiPoolMiner' -Program `$_}" -replace '"', '\"') -Verb runAs
                    $MinerFirewalls = $null
                }
            }
        }
    }
```
Your feedback is greatly appreciated.

**Comment by boredazfcuk** [comment]
Hi,

No, only the built in Windows 10 firewall. I usually have outgoing traffic blocked by default, but even with the Windows firewall disabled, I get the same issue.

**Comment by titvs** [comment]
Hi everyone,

The issue resolved itself after i updated the problematic machine with the latest Windows 10 Fall Creators Update.
Maybe the problem was the same as stated by boredazfcuk.
Working without issues now.
