### ISSUE TITLE
Can you have CPU only mine MiningPoolHub?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#783]
Can you have CPU only mine MiningPoolHub?  Is there an option to add to start.bat?

GPU is fine with whatever is the most profit.

**Comment by komer83** [comment]
in start.bat just remove Nvidia and AMD in -type

**Comment by aaronsace** [comment]
CPU rarely ever switches. Post your logs if you are having problems.

**Comment by paulpoco** [comment]
This morning CPU has stayed on Zpool.
https://pastebin.com/2A9BZPb0

**Comment by paulpoco** [comment]
Komer83 that doesn't solve anything, I still want GPU too.  And if I did "-type cpu" only I would it would still do Zpool.

**Comment by paulpoco** [comment]
I took out Lyra2z for now.

**Comment by paulpoco** [comment]
Well that made it worse now still Zpool but Veltor algo at 0.00001 BTC/day, even though MPH is 0.00013.

I did add the profit listing  accuracy percentage.  I looks like it is using that to pick.

Maybe I should undo that.

**Comment by paulpoco** [comment]
Well that didn't work either.

Can I copy the start.bat to start2.bat.
Then make start.bat GPU only.
Then make start2.bat CPU only without Zpool.

So can I run those 2 start(2).bat at the same time?

**Comment by symalla** [comment]
I have never tried it with the two sharing the files, but I have done it by unzipping twice and configuring one for CPU and one for GPU.

**Comment by paulpoco** [comment]
It is basically to get MPH above BTC withdrawal, make the mistake of picking BTC for Auto exchange.

**Comment by robl45** [comment]
just switch your autoexchange coin to something else.  I started with Ethereum and changed to litecoin.  Then you can just click autoexchange transfer on the bitcoin wallet.

**Comment by paulpoco** [comment]
MPH raised the min withdraw from 0.002 to 0.0023.

So did zpool, now 0.0025

**Comment by fonyo** [comment]
@paulpoco have separate copies of the entire MPM folder. Stat files can get messed up.
