### ISSUE TITLE
Profit Lost from Bitcoin Fees?

### ISSUE THREAD

**Issue by zaptrem** [MultiPoolMiner/MultiPoolMiner#784]
Do the profit calculations count potential profit lost from Bitcoin payout transaction fees? I currently have MiningPoolHub set to Ethereum, but I left all of the Bitcoin wallet pools enabled in the miner. Would it be financially prudent to disable them?

**Comment by aaronsace** [comment]
No fees are included and is something you would have to assess yourself.

**Comment by fonyo** [comment]
The yiimp pools and nicehash will have to incorporate alternative payout coins if bitcoin stays congested. Last 24h block reward was 1,650+1258 BTC. The fees are nearing the block release amount slowly and are currently at over 75%.

**Comment by zaptrem** [comment]
I wonder why more people aren’t updating to SegWit supported clients to
benefit from the lower fees?

**Comment by fonyo** [comment]
Core has segwit support surely, isn't that the case?
