### ISSUE TITLE
Error upon starting MultiPoolMiner

### ISSUE THREAD

**Issue by Dobleman** [MultiPoolMiner/MultiPoolMiner#785]
![image](https://user-images.githubusercontent.com/24636666/34268193-6b95f47c-e645-11e7-8bed-fc75acae3613.png)

This error is also mixed in a few times: 

PS>TerminatingError(Invoke-Expression): "Exception calling "GetPlatformIDs" with "0" argument(s): "Unable to load DLL 'opencl.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)""

This spams about 1000 times and then the miner starts to work, but it eventually stops for no reason.

**Comment by aaronsace** [comment]
Install the drivers from AMD/NVidia that include OpenCL.

**Comment by resp3ct** [comment]
@Dobleman 
I had the same error with the software running at e:\MultiPoolMiner\...
I also have the latest OpenCL Nvidia driver installed already.

I moved the software to c:\users\<myusername>\appdata\local\MultiPoolMiner\... and no further issues with the error "...DifferenceObject..."
