### ISSUE TITLE
Duel mining issue

### ISSUE THREAD

**Issue by tboy1337** [MultiPoolMiner/MultiPoolMiner#787]
When duel mining zpool lbry is down but it doesn't switch to nicehash as backup.

**Comment by tboy1337** [comment]
Is there any way to set lbry pool manually as main pool so i can actually mine lbry or dcr?

**Comment by aaronsace** [comment]
If you haven't deleted the NiceHash file then MultiPoolMiner will use it.

**Comment by tboy1337** [comment]
Haven't changed a thing since nicehash went down

On 21 Dec 2017 23:24, "aaronsace" <notifications@github.com> wrote:

If you haven't deleted the NiceHash file then MultiPoolMiner will use it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aaronsace/MultiPoolMiner/issues/787#issuecomment-353482901>,
or mute the thread

**Comment by aaronsace** [comment]
Please post the logs.

**Comment by tboy1337** [comment]
Strange its using nicehash now, just took a couple of restarts and a couple of changes to what im mining lol.

**Comment by tboy1337** [comment]
[2017-12-21_23-11-37.txt](https://github.com/aaronsace/MultiPoolMiner/files/1581040/2017-12-21_23-11-37.txt)

**Comment by tboy1337** [comment]
it is using it now, guess it just takes a while and a few restarts to change
