### ISSUE TITLE
New user of Multipool miner

### ISSUE THREAD

**Issue by d0n4ald** [MultiPoolMiner/MultiPoolMiner#788]
Hi - i edited the start mining pool hub file and then double clicked it.  I wasnt sure which auto switching algos to mine, so i just used the top 5 profitable ones; is that a good idea or should I just put all algos in there?
Screenshot of whats running-What is happening now, do i just wait for benchmarking to finish? how do i know when it's done and actually mining?  Does the yellow text mean i have to download something?

![untitled3](https://user-images.githubusercontent.com/34756410/34279539-6f8fbede-e67f-11e7-9ddd-7d818c4c76ab.jpg)

**Comment by aaronsace** [comment]
It says that it's benchmarking. 

Also, delete CcminerPalgin.ps1 as that miner has been discontinued.

**Comment by 3zero2** [comment]
@aaronspace in that case should ccminer Palin.ps1 be removed from the next release. it's still being downloaded and used in 2.7.1.1.

**Comment by d0n4ald** [comment]
so i added a few more algos to the miningpoolhub.txt - skein,ethash,cryptoknight,groestl.

what are the red error messages below and what if anything do i need to do?

![untitled4](https://user-images.githubusercontent.com/34756410/34283518-29cab294-e69a-11e7-9417-a371da9f3cc2.jpg)

**Comment by d0n4ald** [comment]
also i got a message "prospector.exe" has stopped working. In the command screen, i also saw the message "failed to communicate with prospector miner"

**Comment by fonyo** [comment]
@d0n4ald Having the top 5 algos only is good way to start. Less benchmarking time, less amount of confusing data is thrown at you first. You can add more as you go.

The error excavator is showing makes me wonder whether your 1050s have 2 or less GB of memory. Try adding the ethash2gb parameter instead of ethash if that is the case.

**Comment by fonyo** [comment]
Prospector is not working for everyone, it is there for a smaller percentage of the user base to use. You can simply remove it by removing its config file from the /Miners folder.

**Comment by fonyo** [comment]
Closing this issue for now, please post a new thread if you are still having issues.
