### ISSUE TITLE
Monitoring for rejected shares

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#791]
I had a few rigs run all night working hard but getting nothing but rejected shares.  Could be caused by bad or incompatible hardware, a bad miner, a broken pool, whatever.

I know the number of accepted and rejected shares is available in most miner's APIs, but its not tracked at all by MultiPoolMiner.

Has any thought been given to tracking accepted/rejected shares for the active miners, and failing them if they have too many rejected?

**Comment by UselessGuru** [comment]
Not all miners expose info for rejected shared. This makes it kinda difficult to implement.

**Comment by aaronsace** [comment]
Not sure how to handle them yet; will give it some further thought and look at implementing something.
