### ISSUE TITLE
Log File Size

### ISSUE THREAD

**Issue by i3fe-at-work** [MultiPoolMiner/MultiPoolMiner#792]
It seems like the logs go on forever. Is there a possibility they can be cut off at a certain size and a new log started? I dislike looking to see what has been going on and finding that I need to search through a gigantic log file. Something along the lines of 2MB would be nice.

**Comment by Dulanic** [comment]
This should be relatively easy to do, especially since we're using PS. You can even scrript it yourself for now.

PowerShell - Update paths and date -

```
Get-ChildItem -Path c:\install path\Logs\* -Recurse -Include *.txt | Where-
Object CreationTime –lt (Get-Date).AddDays(# of Days, use - 90 to go back 90 days) | Remove-Item
```

**Comment by grantemsley** [comment]
Logs are rotated to different files based on time/date stamps now.
