### ISSUE TITLE
24hour pool?

### ISSUE THREAD

**Issue by gak45** [MultiPoolMiner/MultiPoolMiner#793]
First let me say I love your program.
Just one small thing, can you add in 24hr pools (ahash, hashrefinery, zpool) options instead of real time numbers it uses to switch coin mining? I love that about nemosminer, as it is more stable with a LOT less switching, but am not sure if Nemos uses a 'watch dog' to catch errors and restart a miner if it fails. Rather mining on a less stable coin to no mining at all, but that would give the best of both worlds.

**Comment by aaronsace** [comment]
It's a lot less switching but 24 hour stats should not be used to assume current profits. I've managed to reduce switching on the unreleased code and it successfully follows the trend.

**Comment by jayntguru** [comment]
sniffdog has this and it's just one part of one line that has it. If you really wanted it shouldn't be too hard.
https://github.com/Sniffdog/Sniffdogminer/blob/3.1/Pools/ahashpool.ps1#L35

**Comment by gak45** [comment]
thanks for the quick response! Ive tried the unreleased code, and understand it is 'unrefined', but the new switching 10 code... forks the dog... hard. Did if for a day on two dif rigs and it spent most of its time on crapcoins like bitcore. Actually always starts out in the middle of the pack on bitcore or lbry or even groestl and stays there for 10minutes or more. Looking over the stats the next day it was, well, way off. IE Profit went down by 20 percent. Would setting it to 5 or even 1 make it switch faster but be more stable?

If you have the code needed I can hack it into the proper ps1 files. But I think more options are better than fewer. Its too bad pools dont offer 1hr stats. Less switching while still catching waves faster. :(

And let me just be clear. Not shitting on what you have done. It is amazing. Awesome work. Seriou sly. Great program. Just think it might be a nice option. Or not. Its cool either way :)

**Comment by robl45** [comment]
I ended up dropping the switching 10 flag for now and just set interval to 2 minutes to reduce the constant swapping.  Like you I had the same issue, starts out every time on bitcore and randomly just goes to bitcore when it feels like it.

**Comment by fonyo** [comment]
I know this is not the best answer and what you are really looking for but please try to decrease the amount of algos included to only the top few profitable ones and add the worse ones in as you go later on. There is no real reason to have the problematic, frequently spiking algorithms/coins in your mix. I know you don't want to miss out on anything but that's just not good practice nor a good reason to have them included at all.

**Comment by fonyo** [comment]
***keeping this thread on watch list for now***

**Comment by gak45** [comment]
No, that makes sense. In your opinion what coins are problematic and how many alogs would you recommend using?

**Comment by jayntguru** [comment]
What do different numbers for switchprevention do? In the code it looks like a multiplier, so lower numbers would be less switch prevention I assume?

**Comment by aaronsace** [comment]
Zero will switch most intervals and increasing it will prevent switching and more specifically switching to unstable coins.

**Comment by gak45** [comment]
So if '10' is wonky and 0 is too.. active. Would 2-5 make more sense, especially for non-PPLNS pools like ahashpool, hashrefinery, etc? IE keep it from chasing a short term bump but not keep it on crapcoins that never are at the top (like bitcore, lbry, etc)?

Basically can you explain what the multiplier does? Is it minutes, seconds? Any info on this VERY cool addition would be awesome. That way peeps like me can make up our minds on what to set it at. For the record I have it set to 0 right now and profits are back to where they were pre non-release levels. 10 was just too... restrictive for lack of a better term. :)

**Comment by UselessGuru** [comment]
> telling the program if its PPLNS or not pool so that the code can react differently based on pools being used? Now that would be very cool. :)

Sounds very reasonable to me.

**Comment by fonyo** [comment]
Please have a close look at the charts (list) on whattomine.com and sort results for your rigs by average profit of *7 days*. That will give you a rough idea of which algorithms to use.
