### ISSUE TITLE
Any interest in back-porting my web monitoring interface?

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#794]
I've created a very basic web interface for monitoring my workers at https://github.com/grantemsley/mpm-monitor, so I can monitor them all from one place.

It requires some small additions to the script, adding a reporting URL parameter for where you have the monitor running and a section to send a web request to the server.

So far, it reports the time the worker last reported in, the estimated BTC/day for the system, and info on which miners are running.
![untitled](https://user-images.githubusercontent.com/669579/34306976-f3d9fd0a-e713-11e7-8886-7fc5b1a1a64f.png)

I'm not quite done yet (the way I'm getting the pool name is wrong), but if you are interested in adding it I'm happy to make it into a pull request when I'm done.  Just didn't want to go through the effort to separate it into a PR without checking if you want it first.

**Comment by jayntguru** [comment]
Neat.

**Comment by aaronsace** [comment]
Would like to see this, please can you submit a pull request showing the changes?

**Comment by grantemsley** [comment]
PR #801
