### ISSUE TITLE
Error 404 Dead Links (Unable to automatically download miner) Script needs update :(

### ISSUE THREAD

**Issue by thericeking** [MultiPoolMiner/MultiPoolMiner#803]
Dead links :(

Are we screwed here? Can't even manually download them. Is it because the developers don't want you to use a script to download their work in to your MultiPoolMiner? I don't think that's illegal.

Sorry I'm useless at programming, if not I would help fix this.

WARNING: Cannot download C:\Users\Crypto\Desktop\MultiPoolMinerV2.7.1.1\Bin\NVIDIA-Palgin\ccminer.exe distributed at https://github.com/palginpav/ccminer/releases/download/1.1.1/palginmod_1.1_x64.zip.
WARNING: Cannot find C:\Users\Crypto\Desktop\MultiPoolMinerV2.7.1.1\Bin\NVIDIA-Palgin\ccminer.exe distributed at https://github.com/palginpav/ccminer/releases/download/1.1.1/palginmod_1.1_x64.zip.
WARNING: Cannot download C:\Users\Crypto\Desktop\MultiPoolMinerV2.7.1.1\Bin\Excavator\excavator.exe distributed at https://github.com/nicehash/excavator/releases/.
WARNING: Searching for C:\Users\Crypto\Desktop\MultiPoolMinerV2.7.1.1\Bin\Excavator\excavator.exe.

**Comment by komer83** [comment]
Have the same issue with the same miner.

**Comment by unze** [comment]
Workaround: Delete "CcminerPalgin.ps1" file in "Miners" folder

**Comment by paulpoco** [comment]
I have a copy from a few days ago.  Do we still use that one?

**Comment by paulpoco** [comment]
Q: Why did you move from free software to devfee?
A: The situation I'm currently in made me to do so, donation scheme didn't work at all, also my employer informed me that he closes his business and doesn't need my services anymore, with all this I have high load on my family budget (need to cover over 80k$/year bills) which I won't be able to cover without extra income. Freelance don't give me much money without stable employer. So yes, it's money question, also I have another dev working on the project who wants to be paid for his work.

Q: Who's alexkap?
A: It's my ex-colleague who worked on the same employer, this summer we just decided to work together in crypto-field.

Q: hsrminer looks quite like ccminer...
A: True, in early builds it really was ~30% ccminer code (especially monitoring), but now only data output is quite the same. Also we'll migrate to new frontend after algo coverage.

Q: What other algos are you planning to add?
A: At the release time we'll try to cover at least 3-4 popular ones, HSR choice was just for a good base for faster implementation of other algos.

Q: Will you provide any support for your miner?
A: Yes, all support will be provided in this topic.

**Comment by UselessGuru** [comment]
Excavator must be downloaded and copied to the miner directory manually. The special EULA (licence) does not allow automatic downloads.
Source: [https://github.com/nicehash/excavator/releases/](url)

**Comment by iwtym** [comment]
Palgin worked well for hashrates but loaded cards quite heavily and thus crashed my rigs often - sometimes hardcrashed and sometimes softcrashed.

**Comment by UselessGuru** [comment]
@aaronsace 

Should we provide a copy of CcminerPalgin_Nist5 here and update the miner file?

**Comment by thericeking** [comment]
@paulpoco Where did you get that Q&A from?

**Comment by thericeking** [comment]
@iwtym @unze Don't I need Palgin to mine certain crypto?

**Comment by UselessGuru** [comment]
@thericeking 

> Don't I need Palgin to mine certain crypto?

Nope. There is no algo that only palgin could mine. It was just faster on some, e.g. nist5

**Comment by thericeking** [comment]
@aaronsace @UselessGuru I knew already about the separate need for downloading Excavator but I was asking about the ones on my first post.  
Is there a new version release soon? I am look at this site a few times a day and I see you guys made tons of changes since last release. I was going to try to use the master but I saw the post were you guys discourage people to not use the master. I thank you guys for your hard work. This project has changed my life by helping me add a little bit of side income for my family. This software if very effective at what it does compared to the rest like AwesomeMiner and NiceHash. Currently I'm investing in more crypto mining hardware because of it. This is a lot of fun.

**Comment by ChriscomIT** [comment]
I have the latest version which was downloadable and just copied it manually to the bin folder like with Excavator. Works flawlessly for me.

**Comment by thericeking** [comment]
@ChriscomIT What exactly do you mean? I know how to manually install Excavator and make that work. You mean manually installing the rest of the miners that used to download automatically when launching the MultiPoolMiner the first time? Those no longer automatically download because the developers for those miners killed the link (404 error) Forgive me if I cannot intelligently explain my self well enough yet. I'm trying to catch up and learn as fast as I can.

**Comment by ChriscomIT** [comment]
I can provide you the binaries of the latest Ccminer_palgin which was available for download before the link went dead if you want. You need to put it in MPM /bin folder like you do with Excavator.  For me personally, its way faster on skein as all the other miners. Just hit me up if you need the file. And remember that with the next release version you need to copy over the binary files and the Ccminer_Palgin.ps1 to make it work again.

**Comment by thericeking** [comment]
@ChriscomIT I appreciate you offering to help however, long story short.... The problem happened when I did exactly what you advice but from a different mining rig that was already working fine. What I think happen when I tried to copy the folder to the new mining rig I'm building was that Windows Defender blocked some miners and I didn't catch on it until I tried again. Now is working again on two other machines but it took manual trickery to get Windows Defender to not block them. I hate the false positive virus... but maybe these things do have viruses. Who knows... I hate it.

**Comment by isuelt** [comment]
@ChriscomIT 
> I have the latest version which was downloadable and just copied it manually to the bin folder like with Excavator. Works flawlessly for me.

> I can provide you the binaries of the latest Ccminer_palgin which were available for download before the link went dead if you want.

Can I get a those binaries from you as well ?  How can I PM contact you ?
