### ISSUE TITLE
Cannot bind argument to parameter 'DifferenceObject' because it is null.

### ISSUE THREAD

**Issue by ailocha** [MultiPoolMiner/MultiPoolMiner#804]
i deleted and reinstalled the multipoolminer.  still getting the error.
[2017-12-23_11-46-37.txt](https://github.com/aaronsace/MultiPoolMiner/files/1584287/2017-12-23_11-46-37.txt)

i

**Comment by aaronsace** [comment]
You don't need to install MultiPoolMiner. I think you're missing is OpenCL that's included in AMD/NVidia drivers.

**Comment by BigW2016** [comment]
What about -type [AMD,NVIDIA,CPU] parameters in you *.bat file?
