### ISSUE TITLE
"-donate" switch not working??

### ISSUE THREAD

**Issue by ChriscomIT** [MultiPoolMiner/MultiPoolMiner#805]
Hi, 

firstly I understand this is a free project which needs donations to keep up the development. But I am that kind of person which likes to directly donate from time to time rather than mine some time for others every day.

However, my problem is that I have set `-donate 0` (doesn't matter if I add it or not at all) but still the miners starting from time to time with @aaronsace or @fonyo pool login. Can you please look into this or is this expected behavior (not very transparent then)?

![donate_li](https://user-images.githubusercontent.com/2799553/34322656-c6d8915c-e82d-11e7-9cb3-d2fd88abca3d.jpg)

**Comment by grantemsley** [comment]
The code has a minimum of 10 minutes per day donated.  If you set it lower than that, it reverts to 10 minutes.

Nothing stops you from editing the code, except that it would be kind of rude to do that after all their hard work.

**Comment by ChriscomIT** [comment]
@grantemsley Thanks for the answer. Can u tell me if it's in multipoolminer.ps1? Yeah, I know what you mean but I would be up for a discussion if this is rude. I am very for transparency and this all other than transparent. And as I elaborated before I am more that kind of person who likes to directly donate and have some control and transparency. I thought about donating 15€ today or tomorrow. But saw this yesterday and I don't know what to say. It feels wrong.

**Comment by grantemsley** [comment]
@ChriscomIT I'd agree it should probably be added to the instructions that the minimum for donate is 10.  The code isn't hard to find, but I wouldn't feel right helping you do it.  Sorry.

**Comment by aaronsace** [comment]
@fonyo will update the readme.

**Comment by ChriscomIT** [comment]
@grantemsley No problem I deleted my question about the code already before you answered ;-) . I will see I think I have to go into an ethical discussion with myself and see what I am coming up with that. I figure it out myself then or just run it as it is. BUT at least it should be documented in the instruction or readme or FAQ. This behavior is not transparent and same as betraying imo. As much as I like open source, donations and this very very nice project I cannot accept this approach of undocumented donations personally. Thanks again for the answer. 

@Fonyo Ok!

**Comment by ChriscomIT** [comment]
@aaronsace If I directly donate do you share these with the other guys in some percentage or do they get only the mining donations? No, offend in any way just to transparently figure this out for me. Thanks for your hard work. Appreciate the fast response from you guys!

**Comment by fonyo** [comment]
We are opening up a website soon where it is already highlighted that MPM has a less than 0.7% minimum fee. My apologies, my focus was on the website in the last few days when I had some free time and should have added this earlier. I was going to add this to the README as well tomorrow to show transparency but please bear in mind this has only been changed recently. I am well aware (and also made aware the not so kind way on Twitter) that this could mean relatively larger sums per annum if a user has a mining farm.

Well, my respond to that is that using MPM will increase profits by at least 5% but usually by 10-20% or more also time and gives you failover options (preventing downtime). If the huge effort and time put into this are not worth someone to buy us an alcoholic ginger beer from time to time then I think the world is more screwed than I thought and please feel free to edit out the code and deploy MPM without it. Thank you.

**Comment by thericeking** [comment]
@fonyo I also looked all over for documentation in the acceptable minimum but didn't find any and I put only 1 minute. You mentioned you have a website and a Twitter handle? Can you please share the web address and Twitter handle? Thanks

**Comment by ChriscomIT** [comment]
@fonyo Thanks for the in-depth reply. As said before much appreciate it. As well its good to see that you are serious about things like that and we are having the same opinion about transparency. I am 100% compliant with your arguments and really appreciate your hard work and your continuous development. Wish you all the best with the new website. Fully understand that this needs time and focus. Love to see this project evolves!

Would like to get that twitter too.

**Comment by fonyo** [comment]
@ChriscomIT 
Cheers, I appreciate the kind words!

@thericeking 
The website is still in draft on my dev server. Aaron has seen it but I want him to have a proper look at it and once everything is agreed on, it will be deployed on a domain I insisted on and he kindly provided (it is a very cool domain in my opinion!) as MultiPoolMiner.com was snitched away by people who wanted to gain user base through the established name and fame. Also, Aaron wants to use wordpress and I shall obey. At some point in the near future, I will be migrating the site to wp but I really want to get it up and running as quickly as possible so I can use it for other support and documentation purposes.

@both
Twitter handle is on my list, will be introduced in the upcoming days. We have a reddit page: reddit.com/r/MultiPoolMiner

I find it amazing the reddit page is slowly gaining subscribers and posts even though it is not advertised at all.

I sincerely hope you will understand the reason and forgive for the delay in updating the README.

Thank you for your support.

**Comment by fonyo** [comment]
Oh, and Happy Christmas by the way ![e20798eb-5b9a-4c04-9d29-ce2d55c25583](https://user-images.githubusercontent.com/10072275/34323199-d1625010-e835-11e7-814c-21feff0b1604.jpeg)

**Comment by fonyo** [comment]
https://multipoolminer.io
@multipoolminer on Twitter

**Comment by ChriscomIT** [comment]
@fonyo Thanks!
