### ISSUE TITLE
Nicehash requires me to use their wallet address, but can't use multiple addresses

### ISSUE THREAD

**Issue by hapklaar** [MultiPoolMiner/MultiPoolMiner#806]
How can I configure the NiceHash specific address in start.bat, when it's also used for Miningpoolhub for instance?

**Comment by aaronsace** [comment]
No they don't...

**Comment by grantemsley** [comment]
Nicehash does NOT require you to use their wallet address.  You can mine to external wallets.  And I don't know why anyone wouldn't use an external wallet after the recent events.

In any case, mining is only supported to one address right now.  You might be able to modify the pool file for nicehash to use a hard-coded address, but I would recommend just using a real wallet.

**Comment by hapklaar** [comment]
Ok, thanks for taking the time to respond. After logging in to NiceHash they presented me with their address and no way to specify my own. I'll try and figure out how this is supposed to work with my own address.

And many thanks for creating your tool free of charge!

**Comment by Braintelligence** [comment]
@hapklaar You can hack the NiceHash.ps1 to achieve this.
