### ISSUE TITLE
Is it possible to add ewbf-miner for equihash?

### ISSUE THREAD

**Issue by zoglun** [MultiPoolMiner/MultiPoolMiner#808]
ewbf-miner isn't the fastest miner. But it can achieve 4.4 Sol/Watt, while the DSTM currently came with MultiMiner only get 4.05 with same OC settings. (using GTX 1070 Ti)

My concern is that MultiPoolMiner been wrote to value hashrate out put more than efficiency. Therefore ewbf-miner might not been picked by the program.

**Comment by aaronsace** [comment]
@zoglun Both miners are included and their speeds are close to identical: 
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/Ewbf.txt
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/Dstm.txt

**Comment by zoglun** [comment]
I see. Will delete the DSTM miner.
Thank you!
