### ISSUE TITLE
No pools available

### ISSUE THREAD

**Issue by krewintheminer** [MultiPoolMiner/MultiPoolMiner#809]
Any idea why suddenly why pools are not available? also it says the miner is out of date but I'm already using the current version? thanks.

WARNING: Pool API (AHashPool) returned nothing.
WARNING: Pool API (Hashrefinery) returned nothing.
WARNING: Pool API (MiningPoolHub) returned nothing.
WARNING: Pool API (MiningPoolHubCoins) returned nothing.
WARNING: Pool API (NiceHash) returned nothing.
WARNING: Pool API (Zpool) returned nothing.
WARNING: No pools available.
WARNING: MultiPoolMiner is out of date; there is an updated version available at https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.1.1/MultiPoolMinerV2.7.1.1.zip.

**Comment by fonyo** [comment]
Are you using the latest master?

**Comment by bizarrefishfry** [comment]
I have the same issue. 
It seems to be related to Cloudflare Capatcha. 

I only mine at MPH, but when I run the start.bat I get the same error as OP. 
If I manually download this file: http://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics and host it somewhere else (and point the "MiningPoolHub.ps1" file to it, I have no problems at all.

**Comment by i3luefire** [comment]
i have had the same problem recently but only on one of my 2 machines

**Comment by titvs** [comment]
Same here and exactly as i3luefire: only in 1 of 2 machines...
