### ISSUE TITLE
Stupid Question - using Start-MiningPoolHub.bat and removed some Algos, but still Nicehash/AHashpool/Zpool mining

### ISSUE THREAD

**Issue by mrcodeine** [MultiPoolMiner/MultiPoolMiner#810]
Hi, this is likely a stupid question as I know its "MultiPoolMiner" for a reason, but I only have a small 6-GPU rig and I'm being spread thin over Zpool/Ahashpool, etc where I'm likely to rarely get a withdrawal.  I tried using Start-MiningPoolHub.bat and removed Algos not available on that pool to ensure I only minine on MiningPoolHub however I'm still getting allocated a lot of mining time to Zpool/AHashPool, etc.

I thought about searching the dir for Zpool etc and just deleting files but am wondering if there is a textbook way of achieving MiningPoolHub only mining.

Cheers

**Comment by symalla** [comment]
You can delete the pools you don't want from the Pools/ directory. Each one as its own ps1 file.

**Comment by mrcodeine** [comment]
symalla, thank you so much for the answer.  Deleting the files for non-miningpoolhub pools worked perfectly!  Really appreciate your quick help.  Case closed.
