### ISSUE TITLE
Two possible issues

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#811]
I've been running with 2 minute interval with no switching prevention for at least 24 hours.  About an hour or so ago I came home and noticed that it was no longer using the top profit algorithm.  It was using something about 3 or 4 from the top. I figured it was a fluke and waited and then it chose another one that wasn't the top one or top two.  I finally restarted and it went back to normal behavior.

Another thing I noticed and maybe it has more to do with my machine that anything else is randomly it stops updating completely.  Powershell will no longer show up using cpu in task manager and updates just stop.

**Comment by fonyo** [comment]
Regarding the second issue: 
Is your PC also frozen when that happens? Have you checked whether any selection is made in the command prompt window?

**Comment by robl45** [comment]
No, PC is just fine.  I'm not sure what you mean by selection is made in command prompt window.

**Comment by fonyo** [comment]
Like with your cursor. It is quite common someone clicks inside the MPM window creating a selection which stops the script.

**Comment by robl45** [comment]
That is very possible and I think that is when it happens.  How do you unselect?

**Comment by tooviral** [comment]
just right click in the window

**Comment by gatistaabb** [comment]
Or press escape

**Comment by fonyo** [comment]
Closing this now, please open a new thread if you are still having issues.
