### ISSUE TITLE
clarification about -algorithms please

### ISSUE THREAD

**Issue by komer83** [MultiPoolMiner/MultiPoolMiner#814]
For my understanding, the configuration files in /pools fetch all the algorithms supports by he pool and only benchmark these four this specific pool. (lets say nicehash) and the -algorithms is only for algorithms I want to mine (lets say nicehash support 1-0 and I only want to mine 3-6)

therefore (for my understanding) I can just remove this flag from that bat file if I want everything supported by that pool.

Am I correct?

**Comment by fonyo** [comment]
No, it is exactly the opposite. As per [README](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#command-line-options)

See sections regarding -poolname and -algorithm 

You pick the algorithms you want to mine and set the preferred pool. Preferred pool will only be used if there is an overlap in availability of the selected algorithms across pools.

Eg. If you only set decrednicehash as algorithm and pick miningpoolhub as poolname, it will never mine on MPH.

**Comment by fonyo** [comment]
I know it is often just too much information but please do go through the README. 

https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md
