### ISSUE TITLE
Nicehash Ethash fault

### ISSUE THREAD

**Issue by BigW2016** [MultiPoolMiner/MultiPoolMiner#816]
DaggerHashimoto - stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 not connected. Job timeout.
Profit regularly updated, but the miner is idle. (ClaymoreAmdDecred40 = Ethash+lbry)
solution for me:
in NiceHash.ps1 

```
    $Divisor = 1000000000
	$Stat = Set-Stat -Name "$($Name)_$($NiceHash_Algorithm_Norm)_Profit" -Value ([Double]$_.paying / $Divisor) -Duration $StatSpan -ChangeDetection $true

```

to 

```

    $Divisor = 1000000000

    if ($NiceHash_Algorithm_Norm -eq "daggerhashimoto" -or $NiceHash_Algorithm_Norm -eq "Ethash") {
		[Double]$_.paying = 0
	}
	
	$Stat = Set-Stat -Name "$($Name)_$($NiceHash_Algorithm_Norm)_Profit" -Value ([Double]$_.paying / $Divisor) -Duration $StatSpan -ChangeDetection $true

```
Maybe it's just me. i don't know.

**Comment by aaronsace** [comment]
Not sure what you referring to... 

Ethash is working though: 

![image](https://user-images.githubusercontent.com/21113644/34329195-fa0bb9da-e8ed-11e7-9c46-bb70ce9b6527.png)

**Comment by BigW2016** [comment]
Hm... 2 days of pain. You are Wizard :) Thank you for answer. it was not your problem originally.

**Comment by fonyo** [comment]
Nicehash was misbehaving originally when they came back, their "pools" were up and down constantly.
