### ISSUE TITLE
Hashrefinery API returned nothing

### ISSUE THREAD

**Issue by piitchyy** [MultiPoolMiner/MultiPoolMiner#817]
WARNING: Pool API (Hashrefinery) returned nothing.

**Comment by aaronsace** [comment]
Not sure why people are posting this; it's just warning you that HashRefinery didn't return anything when it was polled. 

@piitchyy Out of interest, what do did you think this meant and what does it need to say?

**Comment by piitchyy** [comment]
Its been like this for 2 days. so its probably an API string thats changed? Their site is functional. Just wanted to let you know

**Comment by romulus2k4** [comment]
I can confirm that MPM isn't touching anything from HashRefinery probably because it can't poll from it.

**Comment by UselessGuru** [comment]
I can NOT confirm this. I just downloaded the latest Hashrefinery pool file and made it the only file in my pools folder -> working nicely.

**Comment by jweber018** [comment]
Can confirm, can't mine on Hashrefinery, even when deleting every other pool file.

**Comment by fonyo** [comment]
Can you all provide what version of MPM you used when experienced the above?

**Comment by jweber018** [comment]
Latest version, just cloned from master branch.

**Comment by slavajacobson** [comment]
Getting the same error. Also: WARNING: Failed to connect to miner (Cast) during Benchmarking... Related?

**Comment by Nimroth01** [comment]
I can confirm getting the same issue intermittently. As it seems to work sometimes, I assume it might be the hashrefinery API being overloaded and not returning anything. just a guess though.

**Comment by UselessGuru** [comment]
Hashrefinery API is very unstable. More often than not it does not return anything and that's what's causing the yellow warnings.
Two choices:
a) live with it
b) remove the pool file

**Comment by romulus2k4** [comment]
I'll remove the pool file, thank you.

**Comment by bviktor** [comment]
This warning wouldn't bother me so much if I actually **wanted** to use Hash Refintery. The question here is, why does MPM print this message even if I only enable Mining Pool Hub? Here's my command line:

~~~
set "command=& .\multipoolminer.ps1 -username foobar -workername multipoolminer -region europe -currency btc,eth,usd -type nvidia -poolname miningpoolhub -algorithm equihash,lyra2re2,lyra2z,neoscrypt -watchdog -switchingprevention 2"
~~~

**Comment by bviktor** [comment]
Hmm, I think it only happens when you run ccminer miner **and** neoscrypt algo.
