### ISSUE TITLE
error downloading palginpav/ccminer

### ISSUE THREAD

**Issue by snappjay** [MultiPoolMiner/MultiPoolMiner#818]
<img width="1278" alt="screen shot 2017-12-24 at 3 37 09 pm" src="https://user-images.githubusercontent.com/31112881/34329300-b4d5d9fe-e8c0-11e7-8041-845262cfbe64.png">
Hey all!

The only error I'm getting is when it attempts to download the ccminer from the plaginpav github.  I believe it's trying to get the 1.1.1 version.  I've attempted to get the program itself from its own github, bit I'm having some problems finding it ... maybe that's the issue with MPM trying to download it?  The file changed?

My trouble shooting has included completely turning off firewall and virus protection.

Thanks!

EDIT:  managed to get a screenshot

**Comment by WinMinerGMX** [comment]
I have the same issue but for multiple miners. Seems like the script is trying to download the miners over and over again even though they're already downloaded, extracted and installed.

**Comment by UselessGuru** [comment]
Duplicate:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/803
