### ISSUE TITLE
MPM real profitability

### ISSUE THREAD

**Issue by giust** [MultiPoolMiner/MultiPoolMiner#819]
Hello,

I'm just wondering if the profitability that MPM gives is a good guide to follow the algo to mine. I'm seeing every day that the top algo theoretically gives around 0,001 btc/day for my gtx 1080, but then I see that real profitability is something more like 0,0003, that's around 70% lower. I understand that there must be variability, but that would mean that one day I would get 0,0015 btc/day and the next 0,0001 btc/day and this is not the case, I always get way lower. I don't know if I should remove some algos (I have added them all). One example is x17 that almost always shows higher than 0,001 btc/day but real profit is something like 0,0003 btc/day.

What is the real profitability I should be getting with a GTX 1080? How can I improve it?

I'll be happy to read your opinions.

Thanks!

**Comment by ChriscomIT** [comment]
Which miner, which algorithm and some logs maybe? Thanks.

**Comment by giust** [comment]
[2017-12-23_15-55-42.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1585735/2017-12-23_15-55-42.txt)

**Comment by giust** [comment]
That is my most recent log. I checked how much btc I earned during a 24h period, starting 24h from now (the log starts before that time period). In 24h I got around 0,00025 btc in zpool and 0,00035 btc in hashrefinery. So a total of around 0,0006 btc which is not bad at all for a GTX 1080, but just wondering why profitability almost always shows higher than 0,001 btc per day.

Some people say that some algos are not profitable and should be removed, but if profit calculator works well I think it's best to just leave them there and let MPM choose the best. Maybe I'm missing something here.

Thanks!

**Comment by fonyo** [comment]
Having all available algorithms added is not particularly a good idea due to pool luck factor and the various PPLNS(++) payout methods. It is highly recommended to mine on one pool and add the algos accordingly. Please see [README](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#command-line-options) and https://multipoolminer.io/algorithms.php

**Comment by giust** [comment]
Thanks @fonyo but how can I decide which pool and algos to mine?

**Comment by jakewarren81** [comment]
For NVIDIA cards, if all you want is BTC as payment, zpool as primary with ahashrefinery as a secondary.

Current best algorithms are Neoscrypt and lyra2v2 with others popping up occasionally.
