### ISSUE TITLE
How to generate log of ccminer?

### ISSUE THREAD

**Issue by gatistaabb** [MultiPoolMiner/MultiPoolMiner#820]
ccMiner has no log option. I tried "> output.txt" at additional options under "Miners/ccminerVersion.ps1" and it gives an error.

If I run the .bat from the ccminer folder directly with the > file.txt it generates a log file.

Is there any way to achieve this?

**Comment by UselessGuru** [comment]
Add the command to the section 'Arguments' after '$($Commands.$_)'. Do not forget the space before your command.

```
[PSCustomObject]@{
    Type = "NVIDIA"
    Path = $Path
    Arguments = "-a $_ -o $($Pools.(Get-Algorithm $_).Protocol)://$($Pools.(Get-Algorithm $_).Host):$($Pools.(Get-Algorithm $_).Port) -u $($Pools.(Get-Algorithm $_).User) -p $($Pools.(Get-Algorithm $_).Pass)$($Commands.$_)"
    HashRates = [PSCustomObject]@{(Get-Algorithm $_) = $Stats."$($Name)_$(Get-Algorithm $_)_HashRate".Week}
    API = "Ccminer"
    Port = 4068
    Wrap = $false
    URI = $Uri
}
```

**Comment by gatistaabb** [comment]
@UselessGuru idk if I can reopen this but i've tried this like I said above.

It gives an error:
[ccminer mpm log.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1586231/ccminer.mpm.log.txt)

**Comment by fonyo** [comment]
I need to look into this another time, please don't forget and double-check whether you have the space after the quotation mark before the additional commands you want to add.
Please see [FAQ#15](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md#q15-how-do-i-customise-miners-to-better-work-with-my-cards)

**Comment by gatistaabb** [comment]
I had tried both the way the FAQ#15 says and the way @UselessGuru said before I openned this issue. With the space after the first ".

Thank you alot for your time! Loving the support - it will reflect on future donations.
