### ISSUE TITLE
Profitable bug, I'm pretty sure.  

### ISSUE THREAD

**Issue by komer83** [MultiPoolMiner/MultiPoolMiner#822]
![screen shot 2017-12-25 at 11 40 02](https://user-images.githubusercontent.com/20399230/34337506-65c1d036-e968-11e7-99a1-fe8056b2a66d.png)

**Comment by komer83** [comment]
[2017-12-25_11-31-18.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1585682/2017-12-25_11-31-18.txt)

**Comment by UselessGuru** [comment]
Are you using the latest pool files? The has been a change in units for some algos resulting in incorrect (factor 10^3) higher earnings.

**Comment by komer83** [comment]
I haven't changed anything in the pool files, so can't really answer that.

**Comment by UselessGuru** [comment]
> so can't really answer that

How about re-downloading the latest pool files. 'Cause then you could answer 'yes' :-)

**Comment by biesbjerg** [comment]
I'm seeing the same thing. I've downloaded the latest pool files from the repo and replaced the ones in my install - still showing crazy profits:

![image](https://user-images.githubusercontent.com/230182/34466903-5c6c6976-eee3-11e7-9c55-78b8a01238b3.png)

**Comment by aaronsace** [comment]
It's not the same, please start a new issue and upload the log files.
