### ISSUE TITLE
Could mining in pools AHashPool and Hashrefinery be disabled?

### ISSUE THREAD

**Issue by Coin-Digger** [MultiPoolMiner/MultiPoolMiner#824]
It is possible that only mine coins in Zpool, Nicehash and Miningpoolhub?  AHashPool and Hashrefinery are not in the pool name list of the file "start.bat" and why are they still mined?

**Comment by UselessGuru** [comment]
Remove the unwanted pool files - done!

**Comment by fonyo** [comment]
***Note to self, add to FAQ***

**Comment by robl45** [comment]
Will that do it?  I"m trying to mine on just ahashpool right now as with one card currently, I'll never get paid with it mining on multiple pools.

**Comment by jayntguru** [comment]
@robl45 I would try a pool with a smaller payout. ahashpool is .008 now and that took me about a week with a 1080ti and two fury's. zpool and mph have lower payouts.

**Comment by robl45** [comment]
I know, but it wasn't before and unfortunately I've mined quite a bit on it.  taking out the pool files caused it to error out on me.  renaming them works, but causes tons  of errors in the script every time it updates

**Comment by UselessGuru** [comment]
> taking out the pool files caused it to error out on me. renaming them works, but causes tons of errors in the script every time it updates

Does not make sense. 
Remove the pool file (not the API!). Restart MPM. You will not see any errors/warnings - if you do then  there is something else wrong.

**Comment by robl45** [comment]
I did, I deleted the pool file , the .ps1 files  didn't want.  then it wouldn't load.  put them back in renamed and it works.

**Comment by UselessGuru** [comment]
>I did, I deleted the pool file , the .ps1 files didn't want. then it wouldn't load. put them back in renamed and it works.

Does not make sense at all. 
Delete the files. Renamed files will cause problems! Do not even attempt to put them in a subdirectory!

**Comment by robl45** [comment]
I did delete files, did not work.  kept terminated with error that argument was invalid.

**Comment by i3luefire** [comment]
Sounds like you may have broken something. I suggest that you unzip a new folder for the miner and copy your bat file into the new one then delete the files for the pools you don't want from the pools folder

**Comment by robl45** [comment]
I did, I got it work now. got rid of the pool files.  biggest problem is even though the hashrefinery pool is just fine, I guess its api doesn't respond that often and half the time it takes 3 tries to start otherwise it says there are no pools.

**Comment by fonyo** [comment]
Ahashpool and hashrefinery are smaller pools, their servers cannot really handle the load they are receiving lately. There is nothing can be done on our end.
