### ISSUE TITLE
please add new miner

### ISSUE THREAD

**Issue by ALLMINER** [MultiPoolMiner/MultiPoolMiner#825]
mkx 28-35mh lyra2v2 rx 470-rx 580

https://bitcointalk.org/index.php?topic=2360168

**Comment by fonyo** [comment]
It only supports Suprnova.

**Comment by fonyo** [comment]
#495

**Comment by lmlim** [comment]
also, please add some new coins that shows up in zpool, ahashpool and hash refinery please...
phi, hsr, polytimos,...... 
at least i would like to know if they are profitable (AMD n Nvidia). 

thanks

**Comment by ChriscomIT** [comment]
@lmlim They are already added to the latest master. If u cant wait for release just get the master.

**Comment by fonyo** [comment]
We generally advise against using the latest master as it usually contains experimental code with limited testing. I just want to make you aware, please fire away if you are fine with that.

**Comment by nicolasdanelon** [comment]
What about Suprnova? Suprnova it's a mpos, just like MPH, right? should MPM support it?

**Comment by jayntguru** [comment]
I keep reading "Suprnova is going away"

**Comment by fonyo** [comment]
I cannot say for sure but I don't think it does. It is now one of the oldest and largest pools.

**Comment by fonyo** [comment]
I keep reading Suprnova is also stealing hash. Well, the fact it is stated somewhere does not make it true (until it is proven).

**Comment by nicolasdanelon** [comment]
The way I see is. MPM use two _"types of pool"_ yiimp and mpos, right?
I think you (MPM devs) could write two interfaces and 4 implementations in order to give freedom to users to add pools or something like that?

**Comment by fonyo** [comment]
It is definitely not black and white, all pools have their own customisation to yiimp, APIs, ports etc. which would make this not feasible to do so.

**Comment by UselessGuru** [comment]
> I think you (MPM devs) could write two interfaces and 4 implementations in order to give freedom to users to add pools or something like that?

It is all yours. MPM is written in powershell - for the very reason of easy customization.
Implement support for a new pools is quite easy. Just analyze its API and then derive the pool file from an existing one.
Please note: The devs can only support / maintain a limited number of pools (the ones included in the distribution).

The same is true for new miners. It it mostly just a matter of copy&paste.

>  MPM use two "types of pool" yiimp and mpos, right?

Not quite. It just uses data from the pool API, reagrdless of the type.

**Comment by nicolasdanelon** [comment]
roger that @UselessGuru thanks!
