### ISSUE TITLE
Miners Hang Restart PC

### ISSUE THREAD

**Issue by Razalka** [MultiPoolMiner/MultiPoolMiner#828]
is there any way to auto restart the pc when the miners hang from MPM ?
Somethimes the miners hang after 10-15 hours mining, and i have to restart the pc or the MPM manually.
The watchdog timer from MPM show 1000-2000 second from all the loaded miners and try to load all the possible miner, and mining nothing because it hang stuck in the black screen from the miner.

![mpm miner](https://user-images.githubusercontent.com/25100730/34344035-32bc0d7c-ea13-11e7-937a-6677d264fcd9.PNG)

**Comment by fonyo** [comment]
Try to restart your PC periodically by setting up a reboot task using Task Scheduler

**Comment by CptanPanic** [comment]
What exactly does this list mean?  On my cpu mining setup, I have a similar list of 5 miners, even though only one is actually running.  I checked TaskManager also, and they are not running.  Why do they not get removed?
