### ISSUE TITLE
miner restart after failure

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#829]
If a miner ends up in the failed section, will it ever restart?  One of my miners is ended up in there even though it runs fine.  Will it eventually work its way back.?

**Comment by robl45** [comment]
I'm watching CCMINER Palgin hash on X17 and the watchdog timer keeps moving up in seconds.  What causes that?  It now dropped back to 0 seconds but got up to around 2600 seconds last time when it was kicked out yet I've watched it on and off and its always working.

**Comment by robl45** [comment]
How do I stop the watchdog from taking out CC Palgin  X17 miner?  Its my best miner and the system keeps knocking it out even though it works fine.

**Comment by robl45** [comment]
I'm seeing yellow errors on a number of them saying they are not updated because value is outside fault tolerance.  happened just now on Nist5 and I've seen it happen a number of times on x17.  How can I stop that from happening?  I'm guessing thats what is causing them to stop?

**Comment by UselessGuru** [comment]
@robl45 
>How can I stop that from happening? 

Your stored hashrate values for the 'yellow' algorithms are too high or too low.
Fix: Delete the hashrate file. MPM will then benchmark this algo again.
Note: With some miners the reported hashrate on X17 increases over time (very low soon after start). So depending on how fast the hasrates are read (during benchmark, but also before switching miners) the readout may vary and causing 'yellow messages'.

>I'm guessing thats what is causing them to stop?
Nope. X17 puts high stress on the GPU/CPU and might cause more system instabilities (same here).

**Comment by robl45** [comment]
I upped the fault tolerance, it seems to be doing the job now.

**Comment by robl45** [comment]
So I upped the tolerance and it seemed to be fine, but just now I saw both X17 miners were gone, I restarted the program and they are back but with accuracy of -110%.  What does this mean and how do I stop it from getting rid of X17?

**Comment by lmlim** [comment]
same here. 
seems like x17 algo slower at first start and took a while to reach max. watchdog can't detect this.

for now, i just disable watchdog completely until there is a fix.

**Comment by lmlim** [comment]
@aaronsace 
any advise to this falsely kicked out miners yet?
