### ISSUE TITLE
Latest Master not putting highest miners first

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#831]
![capture](https://user-images.githubusercontent.com/34346751/34357419-ef9fd3b4-ea14-11e7-8803-b8e6642539f7.JPG)

Am I missing something here?  Shouldn't highest BTC per day be at the top?

**Comment by jayntguru** [comment]
I've seen that a couple of times too. It's odd.

**Comment by UselessGuru** [comment]
> Shouldn't highest BTC per day be at the top?

Not necessarily. Accurate prices are also important. Some algos produce high spikes which in the end (once they make it to the exchange to be sold) will will have fallen in price are not be very profitable at all.
The higher accuracy the less 'bouncy' the resulting earnings will be.

**Comment by thericeking** [comment]
Oh so it's OK to use Master? Here I am anxiously waiting for a new release with latest fix.

**Comment by grantemsley** [comment]
I've noticed this happening as well.

First screenshot:  It picked ccminerPalgin Veltor @ 0.00012 BTC/day 75% accuracy.  Right below another is 0.0050 @ 68% accuracy, and a few lines below that is PalginNvidia Neoscript 0.00040 BTC/day 90% accuracy.  Better profit and accuracy...so from what that table shows, I can't see how it would have been sorted that way, even if it is giving some weight to the accuracy.

![first](https://user-images.githubusercontent.com/669579/34369987-87359c80-ea8e-11e7-96bb-17ab9eb2e01e.png)

On the next loop is corrected itself and switched to a different miner, ccminerPalgin X17 for 0.00050 BTC/day 69% accuracy.

![second](https://user-images.githubusercontent.com/669579/34370014-b2641cc4-ea8e-11e7-91dd-14e08ba18bcc.png)

I expect there is some legitimate reason for it happening...I still don't understand everything the profitability calculations code is doing.  But if it's not a bug, it's not being reported in a very use friendly way.  If the most profitable miner is being calculated based on historical trends from the stats files, it would be nice to show that info in the table as well.

**Comment by thericeking** [comment]
@UselessGuru I understand your logic however, Isn't it in the best interest of MPH to exchange the coins ASAP to get the most. I know it still takes time to exchange but I think that losing money mining other coins is impossible to predict. I thin MPM should constantly mine the most profitable no matter what in the 17XXX pools of MPH. I don't like the idea of MPM to stick with the less profitable coin just because is guesstimating that the top coin at the moment is just a fluke. I think that it should mine most profitable no matter what. Let MPH do their job.

**Comment by thericeking** [comment]
@grantemsley Can you explain the screen shots in English? I don't have the intelligence to understand what you just posted but I am very interested to learn your findings. Thank you

**Comment by robl45** [comment]
I notice that sometimes it has them listed correctly and other times they are all over the list.  I believe its BTC/DAY times accuracy for the final number.  I do notice that regardless where they are in the list it seems to be picking the one that pretty much lines up with that.  Not sure what Pascal did to get -75000 accuracy on my system.  I have switchingprevention set at 3 minutes and interval set at 2 minutes right now,  seems to be working decently.

**Comment by thericeking** [comment]
Where does MPM knows which coin is most profitable for autoswitching MPH? Is it talking directly to MPH API or WhatToMine API?

**Comment by grantemsley** [comment]
It gets profitability information from each of the pools.

**Comment by thericeking** [comment]
@grantemsley Thank you sir

**Comment by UselessGuru** [comment]
@thericeking 
>  I don't like the idea of MPM to stick with the less profitable coin just because is guesstimating that the top coin at the moment is just a fluke. I think that it should mine most profitable no matter what. Let MPH do their job.

I have created a pull request that has a switch to force highest paying algprithm:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/845

>  guesstimating

Each time MPM reads date from the pool it also refines an internal price stability database (e.g. how much does actual price diverge from avg. price) -> Accuracy

The spiky algos are not really profitable, The high profit spike lures the miner away from a steady profitable algo. Until the block is verified (takes sometimes many hours) and sold on the exchange the price will have fallen and you get paid much less.
For me it works best to mine on a busy pool with a lot of miners on the same algo. Such a pool will find mor blocks and can therefor sell them at an overall more stable price. In my build I ignore any coin/algo that has less than 10 active miners

**Comment by aaronsace** [comment]
Mining the highest coin is not profitable and nobody switches like that.
