### ISSUE TITLE
Log width

### ISSUE THREAD

**Issue by Dim0N22** [MultiPoolMiner/MultiPoolMiner#832]
Hello.

I have a problem with log width. On AMD rigs default resolution is 640x480 and it's impossible to change. 
Could something be done with the problem?

Log is attached.

[2017-12-26_14-40-38.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1587770/2017-12-26_14-40-38.txt)

**Comment by fonyo** [comment]
I think you can remedy that by launching MPM, right click the title bar and changing the width in properties on one of the tabs.

**Comment by fonyo** [comment]
Closing this, please open a new issue if you are still having trouble.
