### ISSUE TITLE
It gets these errors because the Benchmarking is not done yet, right?  Powershell Window disappears before you can read the error.

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#833]
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\MultiPoolMiner-master Dec 26 11am\Stats\CcminerKlaust_Groestl_HashRate.txt' because it does not exist."

I know I see the Powershell window pops up from time to time with a red error that goes away too fast to read.  Do those error show up in the logs?.

**Comment by fonyo** [comment]
Probably not due to being a separate window/process. Please use the latest release for an error-free operation.
