### ISSUE TITLE
full screen app problem

### ISSUE THREAD

**Issue by carlo0000** [MultiPoolMiner/MultiPoolMiner#835]
hi is it possible that miner stay in background ?
it s not a problem on mining ring  but on my personal computer it s a problem each time i have an app running  in fullscreen   it get out because of miner restart or switch or so
definitely big problem when playing a game

**Comment by fonyo** [comment]
Change

    -windowstyle maximized

To

    -windowstyle minimized

and see if it helps.

**Comment by robl45** [comment]
He talking about the miners themselves, I don't think can fix that problem, happens to me too, you are in the middle of something and it changes miners and loses focus on the app you are working on.

**Comment by grantemsley** [comment]
There is a way of fixing it that was posted before, but it requires injecting some C# code which isn't cross platform compatible so it wasn't added - PR #609 

I've added it in my own branch and it works quite well.  I'm still hoping someone finds a more acceptable method of doing it, but I'm not sure that it's possible using only native powershell commands.

**Comment by fonyo** [comment]
Oh yeah, not much you can do about the miners.

My solution on my 3-card AMD workstation is to launch Claymore-Cryptonight 10.2 without MPM when I am running more GPU-intensive tasks. You just cant mine the normal intensive way when GPU resources are needed by your applications.
