### ISSUE TITLE
CPU usage pwsh.exe hurting hashrate Lyra2z

### ISSUE THREAD

**Issue by hapklaar** [MultiPoolMiner/MultiPoolMiner#838]
When running MultiPoolMiner on my i3-7100, I see a drop in hashrate compared to running ccminer alone. It seems the refresh MPM does every minute uses so much CPU, it affects GPU a lot.

If I CTRL-C MPM, hashrate returns and graphs shows the same. Stopping MPM gives me about 12% more hashrate for this algorithm. (6500kH/s instead of 5700kH/s)

With MPM running. CPU spikes are from pwsh.exe:
![image](https://user-images.githubusercontent.com/7703320/34383473-b11a9de8-eb15-11e7-9beb-2a50a47be9b5.png)

Without MPM running:
![image](https://user-images.githubusercontent.com/7703320/34383574-53243c0c-eb16-11e7-8512-5cdc00e42f70.png)

I already upgraded from G3900 to i3-7100 to see if that would help. It did, a bit, but MPM still has a large impact.

PS. It's happening with some other algo's like skunk as well, but not all. For example neoscript is not affected at all.

PS2. this might be a duplicate of #821

**Comment by grantemsley** [comment]
I'm assuming you've disabled CPU mining, right?

**Comment by gatistaabb** [comment]
I've already asked on #820 how I can generate a log of the miner that MPM runs. I couldnt figure it out alone, as you can see my tries on the issue.

If we could manage to log directly the miner, we could see the problem right away on the hash rates displayed there.

**Comment by carlo0000** [comment]
if you cpu mine you should run the miner separately   and put it in idle in task manager or keep a free core

**Comment by hapklaar** [comment]
I don't do CPU mining.

**Comment by grantemsley** [comment]
Couple things I would try:

- Set the powershell process for MPM to a lower priority.  This might cause other issues though.
- Delete any miners in the Miners directory that you aren't going to be using.  You can definitely delete "Cpuminer*.ps1" and XmrigCpu.txt since those are only for CPU mining.  Delete any other ones you don't use/aren't profitable on your system as well.  Also delete any Pools files for pools you don't use.

Removing the miners you aren't going to be using should make it use less CPU power since it doesn't have to load and sort them on every cycle.

**Comment by carlo0000** [comment]
it s a mono core ?  so it use 100% cpu when multipoolminer is buzy?

then decrease multipoolminer priority to lower than normal or idle in task manager
so the miner get cpu priority  and multipoolminer just gonna be buzy longer time but use less cpu

**Comment by grantemsley** [comment]
@carlo0000 Both those processors they listed are at least dual core.

**Comment by carlo0000** [comment]
than it's strange, if cpu don't hit 100%  it should not lower the gpu's
ram to slow?  i don't think so

i m using fx cpu on all my computers, with all core -1 mining,  did not see gpu hash drop like that
excepted  some ring have 1 gpu hash slower (and without screen connected)

**Comment by grantemsley** [comment]
@carlo0000 Depends on the miner.  As I understand it (and I could very well be wrong), some GPU miners still require a fair bit of CPU resources to run efficiently.  Sometimes in a way that won't actually show up in task manager, since they require a lot of the CPU's L1/L2 cache but not much actual processing is done on the CPU.

**Comment by hapklaar** [comment]
@grantemsley removing pool and and miner files definitely helped a bit and gave around 300H/s extra hashrate for Lyra2z. Still 500 less than without mpm running though. Will try lowering prio and carlo's suggestion about interval as well. 

This problem might be hitting many miners, as most buy cheaper CPU's to build their rig.

**Comment by paulpoco** [comment]
@carlo0000 how do you set the CPU Miner not to use all the CPU when the GPUs might need some of the CPU?

Using Ryzen 5 1600 and 2 x 1070.

Right now I do not know if CPU mining is ruining the GPU hashrates?

**Comment by UselessGuru** [comment]
@paulpoco 
> how do you set the CPU Miner not to use all the CPU

does the CPU miner (you don't tell us which one you are using) have a command line switch to run at lower priority? 
If yes, then add this command to command section in the miner file.
If not, then you will ahve to resort to [3rd party tools to 'lock' cpu priority for a given executable](https://www.askvg.com/how-to-permanently-set-process-priority-in-windows-task-manager/)

**Comment by thericeking** [comment]
This is why I don't CPU mine. I need my CPU to be ready to serve my GPU's request demands and not be busy with other stuff. GPU requests and other demands are always priority to my CPU.

**Comment by carlo0000** [comment]
if you put your cpu miner on idle priority  theoretically  it should only use the cpu what is not in use  and have 0 impact on the rest  but look like in real life it s bit different on some system

**Comment by carlo0000** [comment]
@paulpoco 
don't know what miner you use
i run xmr-stak-cpu with 7 thread  on a 8 core  and i launch it with task scheduler (start at login, it start it with lower than normal priority

**Comment by aaronsace** [comment]
Some GPU miners require more CPU power than others. Should be getting Quad Core (not Dual Core) when building multi GPU rigs if you want flexibility over miners/algorithms.
