### ISSUE TITLE
hsrminer neoscrypt -Share Rejected, duplicate share 

### ISSUE THREAD

**Issue by lukiifaz** [MultiPoolMiner/MultiPoolMiner#839]
"PalginNvidia           NeoScrypt                                8,83 MH/s            0,00097        61%            0,10955 MiningPoolHubCoins-Feathercoin"
"INFO : [15:45:49] : Share Accepted, overall speed is 8120.19kH/s, efficiency 90.31%" and  "INFO : [15:45:57] : Share Rejected, duplicate share"

"   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0,00 PH/s 00 Days 00 Hours 06 Minutes 2 Times  Bin\NeoScrypt-Palgin\hsrminer_neoscrypt.exe -o stratum+tcp://europe.hub.miningpoolhub.com:20510 -u lukii.legion -p x
0,00 PH/s 00 Days 00 Hours 06 Minutes 2 Times  Bin\CPU-JayDDee\cpuminer-4way.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:20581 -u lukii.legion -p x"

Miner : MultiPoolMiner
PLN   : 35,67704 ±82% (19,58461-64,99242)
USD   : 10,12610 ±82% (5,55864-18,44659)
BCH   : 0,00364 ±82% (0,00200-0,00664)
BCT   : 0,00000 ±82% (0,00000-0,00000)

Miner : {PalginNvidia-NeoScrypt, CpuminerJayddee4way-Lyra2z}
PLN   : 105,44890 ±75% (60,27222-184,48750)
USD   : 29,92923 ±75% (17,10688-52,36251)
BCH   : 0,01077 ±75% (0,00615-0,01884)
BCT   : 0,00000 ±75% (0,00000-0,00000)

MiningPoolHub show 0 Feathercoin.

**Comment by UselessGuru** [comment]
Please report this to the miner developer. MPM has no control over this.

**Comment by titvs** [comment]
Same issue. Had to remove the miner since it frooze powershell and the machine...

**Comment by titvs** [comment]
After reading the developer thread on bitcointalk, the miner developed by Palgin doesnt support GTX 9xx.
