### ISSUE TITLE
Skein benchmark never starts

### ISSUE THREAD

**Issue by Nexworks** [MultiPoolMiner/MultiPoolMiner#840]
Im able to mine all algos just fine except Skein. It never benchmarks CCminerSp, a window appears and almost immediately closes. Eventually it flashes up again and closes. This repeats forever.

**Comment by UselessGuru** [comment]
Does CCminerSp run any other algo successfully?
If not - re-download it
If yes - what happens if you run the same command manually (just copy it from the MPM console)

**Comment by Nexworks** [comment]
Its not used for the other two algos I mine. I have redownloaded it, no difference. If I delete the ps1 file associated with that miner everything else works fine

**Comment by fonyo** [comment]
Not all miners work with all set-ups. That is why we have benchmarking and watchdog in place. Please feel free to delete any miner config files that are causing trouble.
