### ISSUE TITLE
Dev fee not working when mining other coin

### ISSUE THREAD

**Issue by Nimroth01** [MultiPoolMiner/MultiPoolMiner#842]
I use MPM to mine XVG by editing the hashrefinery.ps1 to contain c=XVG instead of c=BTC and using a XVG address in the batch file.
Works like a charm, but doesn't play well with the way the dev fee is handled as it always uses the BTC address.
Maybe the c=<SYMBOL> part of the miner config could be set as a parameter in the batch file, which would allow the dev fee address to be set appropriately? 
Another way would be to make sure c=BTC is used when mining the dev fee.

**Comment by UselessGuru** [comment]
Even better: Edit the pool file and add a line '$Wallet="[put your XVG address here]"' near the top

**Comment by fonyo** [comment]
Out of scope and dangerous to do so as per pool warning of no payout if insufficient coins are in pool's coin circulation. Moreover, if implemented, potentially thousands of users can jump on this function causing massive havoc re pool payouts. Please edit this for yourself and do it at your own risk.
