### ISSUE TITLE
Profit readout mishap

### ISSUE THREAD

**Issue by platinum4** [MultiPoolMiner/MultiPoolMiner#844]
Can you inspect this screenshot and see which math function provided the error?

https://i.imgur.com/OeDLFQz.png

**Comment by UselessGuru** [comment]
Not enough information... can you reproduce the issue? If you can please post the log file.

**Comment by platinum4** [comment]
It happened here:

PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\MultiPoolMiner-master\Stats\Profit.txt' because it does not exist."

Miner              BTC                             USD
-----              ---                             ---
MultiPoolMiner     0.00000 ±100% (0.00000-0.00000) 0.00000 ±100% (0.00000-0.00000)
CcminerTpruvot-X17 0.00071 ±100% (0.00035-0.00141) 11.13508 ±100% (5.56754-22.27016)


WARNING: Stat file (XmrigNvidia_CryptoNight_HashRate) was not updated because the value (1336) is outside fault tolerance (0 ... 0).


   Type: NVIDIA

Miner                  Algorithm                                 Speed            BTC/Day     Accuracy         BTC/GH/Day Pool
-----                  ---------                                 -----            -------     --------         ---------- ----
CcminerLyra2z          Lyra2z                                2.90 MH/s            0.00064         100%            0.22211 AHashPool
PalginNvidia           NeoScrypt                             2.18 MH/s            0.00080          85%            0.36584 AHashPool
CcminerNanashi         Lyra2z                                2.68 MH/s            0.00060         100%            0.22211 AHashPool
CcminerKlaust          Skein                               866.39 MH/s            0.00070          89%            0.00081 AHashPool
CcminerKlaust          NeoScrypt                             2.03 MH/s            0.00074          85%            0.36584 AHashPool
CcminerTpruvot         Lyra2z                                2.33 MH/s            0.00052         100%            0.22211 AHashPool
ClaymoreNvidiaPascal40 {Ethash, Pascal}      {56.53 MH/s, 753.68 MH/s} {0.00036, 0.00013}  {100%, 99%} {0.00639, 0.00017} {MiningPoolHub-Ethe...
CcminerTpruvot         NeoScrypt                             1.72 MH/s            0.00063          85%            0.36584 AHashPool
Dstm                   Equihash                            859.31  H/s            0.00048         100%          556.85320 MiningPoolHubCoins-...
CcminerNanashi         NeoScrypt                             1.70 MH/s            0.00062          85%            0.36584 AHashPool
CcminerTpruvot         Skein                               697.96 MH/s            0.00057          89%            0.00081 AHashPool
ExcavatorNvidia2       Equihash                            819.08  H/s            0.00046         100%          556.85320 MiningPoolHubCoins-...
Ewbf                   Equihash                            799.00  H/s            0.00044         100%          556.85320 MiningPoolHubCoins-...
ExcavatorNvidia3       Lyra2RE2                             67.77 MH/s            0.00044         100%            0.00644 MiningPoolHubCoins-...
CcminerTpruvot         Bitcore                              29.06 MH/s            0.00052          89%            0.01780 AHashPool
CcminerLyra2RE2        Lyra2RE2                             65.56 MH/s            0.00042         100%            0.00644 MiningPoolHubCoins-...
CcminerNanashi         Skein                               631.22 MH/s            0.00051          89%            0.00081 AHashPool
ClaymoreNvidiaSia40    {Ethash, SiaNiceHash} {58.83 MH/s, 784.40 MH/s} {0.00038, 0.00004}  {100%, 99%} {0.00639, 0.00005} {MiningPoolHub-Ethe...
CcminerTpruvot         Equihash                            740.00  H/s            0.00041         100%          556.85320 MiningPoolHubCoins-...
ClaymoreNvidiaSia40    {Ethash, SiaClaymore} {58.83 MH/s, 784.31 MH/s} {0.00038, 0.00003} {100%, 100%} {0.00639, 0.00004} {MiningPoolHub-Ethe...
NsgminerNvidia         NeoScrypt                             1.47 MH/s            0.00054          85%            0.36584 AHashPool
ClaymoreNvidiaLbry40   {Ethash, Lbry}         {57.29 MH/s, 66.84 MH/s} {0.00037, 0.00004}  {100%, 84%} {0.00639, 0.00066} {MiningPoolHub-Ethe...
ClaymoreNvidiaSia30    {Ethash, SiaNiceHash} {57.68 MH/s, 576.85 MH/s} {0.00037, 0.00003}  {100%, 99%} {0.00639, 0.00005} {MiningPoolHub-Ethe...
ClaymoreNvidiaSia20    {Ethash, SiaNiceHash} {59.16 MH/s, 353.86 MH/s} {0.00038, 0.00002}  {100%, 99%} {0.00639, 0.00005} {MiningPoolHub-Ethe...
ClaymoreNvidiaSia20    {Ethash, SiaClaymore} {59.16 MH/s, 394.42 MH/s} {0.00038, 0.00002} {100%, 100%} {0.00639, 0.00004} {MiningPoolHub-Ethe...
PalginNvidia           HSR                                  24.12 MH/s            0.00052          85%            0.02170 Zpool
ClaymoreNvidiaDecred40 {Ethash, Decred}      {56.73 MH/s, 756.34 MH/s} {0.00036, 0.00004}  {100%, 94%} {0.00639, 0.00005} {MiningPoolHub-Ethe...
ClaymoreNvidiaLbry20   {Ethash, Lbry}         {57.97 MH/s, 43.47 MH/s} {0.00037, 0.00003}  {100%, 84%} {0.00639, 0.00066} {MiningPoolHub-Ethe...
CcminerKlaust          Nist5                                74.24 MH/s            0.00051          85%            0.00683 AHashPool
ClaymoreNvidiaDecred20 {Ethash, Decred}      {58.01 MH/s, 386.73 MH/s} {0.00037, 0.00002}  {100%, 94%} {0.00639, 0.00005} {MiningPoolHub-Ethe...
CcminerNanashi         Nist5                                73.69 MH/s            0.00050          85%            0.00683 AHashPool
ClaymoreNvidia         Ethash                               59.46 MH/s            0.00038         100%            0.00639 MiningPoolHub-Ethereum
CcminerKlaust          Groestl                              70.80 MH/s            0.00038         100%            0.00534 MiningPoolHub-Groes...
CcminerTpruvot         Nist5                                72.10 MH/s            0.00049          85%            0.00683 AHashPool
EthminerNvidia         Ethash                               58.00 MH/s            0.00037         100%            0.00639 MiningPoolHub-Ethereum
ClaymoreNvidiaSia30    {Ethash, SiaClaymore}   {57.68 MH/s, 0.00 PH/s} {0.00037, 0.00000} {100%, 100%} {0.00639, 0.00004} {MiningPoolHub-Ethe...
CcminerTpruvot         Groestl                              68.43 MH/s            0.00037         100%            0.00534 MiningPoolHub-Groes...
CcminerHsr             HSR                                  21.21 MH/s            0.00046          85%            0.02170 Zpool
CcminerTpruvot         Sib                                  17.70 MH/s            0.00045          85%            0.02540 AHashPool
CcminerTpruvot         PHI                                  30.43 MH/s            0.00046          82%            0.01518 AHashPool
ExcavatorNvidia3       Pascal                                1.96 GH/s            0.00032          99%            0.00017 NiceHash
FireiceNvidia          CryptoNight                           1.34 KH/s            0.00032         100%          237.84880 MiningPoolHubCoins-...
CcminerTpruvot         Tribus                               89.93 MH/s            0.00042          85%            0.00466 AHashPool
CcminerTpruvot         Lyra2RE2                             47.17 MH/s            0.00030         100%            0.00644 MiningPoolHubCoins-...
CcminerNanashi         Sib                                  15.05 MH/s            0.00038          85%            0.02540 AHashPool
CcminerTpruvot         X11evo                               22.65 MH/s            0.00036          87%            0.01578 Zpool
CcminerTpruvot         CryptoNight                           1.19 KH/s            0.00028         100%          237.84880 MiningPoolHubCoins-...
CcminerNanashi         X11evo                               21.90 MH/s            0.00035          87%            0.01578 Zpool
ExcavatorNvidia2       Pascal                                1.67 GH/s            0.00028          99%            0.00017 NiceHash
ExcavatorNvidia2       Lbry                                560.89 MH/s            0.00037          84%            0.00066 AHashPool
CcminerPolytimos       Polytimos                            39.87 MH/s            0.00034          87%            0.00847 Zpool
CcminerTpruvot         Lbry                                539.62 MH/s            0.00036          84%            0.00066 AHashPool
ExcavatorNvidia2       DecredNiceHash                        4.74 GH/s            0.00025          99%            0.00005 NiceHash
CcminerTpruvot         X17                                  15.15 MH/s            0.00053          66%            0.03472 AHashPool
CcminerKlaust          X17                                  14.80 MH/s            0.00051          66%            0.03472 AHashPool
ExcavatorNvidia3       Lbry                                465.15 MH/s            0.00031          84%            0.00066 AHashPool
CcminerTpruvot         C11                                  25.57 MH/s            0.00035          77%            0.01363 AHashPool
CcminerTpruvot         Decred                                5.08 GH/s            0.00024          94%            0.00005 Zpool
CcminerKlaust          C11                                  24.60 MH/s            0.00034          77%            0.01363 AHashPool
CcminerTpruvot         Polytimos                            29.40 MH/s            0.00025          87%            0.00847 Zpool
CcminerNanashi         Tribus                               51.17 MH/s            0.00024          85%            0.00466 AHashPool
ExcavatorNvidia2       Blake2s                               7.05 GH/s            0.00042          64%            0.00006 AHashPool
CcminerTpruvot         Skunk                                48.39 MH/s            0.00029          73%            0.00605 AHashPool
CcminerNanashi         Skunk                                48.35 MH/s            0.00029          73%            0.00605 AHashPool
ExcavatorNvidia3       SiaNiceHash                           3.37 GH/s            0.00017          99%            0.00005 NiceHash
CcminerSkunk           Skunk                                47.90 MH/s            0.00029          73%            0.00605 AHashPool
CcminerNanashi         Blake2s                               6.14 GH/s            0.00036          64%            0.00006 AHashPool
CcminerTpruvot         Blake2s                               6.13 GH/s            0.00036          64%            0.00006 AHashPool
CcminerNanashi         X17                                   9.57 MH/s            0.00033          66%            0.03472 AHashPool
ExcavatorNvidia2       SiaNiceHash                           2.96 GH/s            0.00015          99%            0.00005 NiceHash
ExcavatorNvidia3       Blake2s                               3.35 GH/s            0.00020          64%            0.00006 AHashPool
CcminerKlaust          Keccak                                1.26 GH/s            0.00005         100%            0.00004 MiningPoolHub-Maxcoin
CcminerNanashi         Timetravel                           44.94 MH/s            0.00065          43%            0.01450 AHashPool
CcminerTpruvot         Timetravel                           43.57 MH/s            0.00063          43%            0.01450 AHashPool
ReorderNvidia          Keccak                                1.12 GH/s            0.00005         100%            0.00004 MiningPoolHub-Maxcoin
CcminerTpruvot         Keccak                                1.09 GH/s            0.00005         100%            0.00004 MiningPoolHub-Maxcoin
CcminerTpruvot         MyriadGroestl                       128.46 MH/s            0.00008          70%            0.00064 AHashPool
CcminerKlaust          MyriadGroestl                       118.87 MH/s            0.00008          70%            0.00064 AHashPool
CcminerNanashi         Keccak                              934.79 MH/s            0.00004         100%            0.00004 MiningPoolHub-Maxcoin
CcminerKlaust          X14                                  17.81 MH/s            0.00001          97%            0.00057 Zpool
CcminerTpruvot         X14                                  17.57 MH/s            0.00001          97%            0.00057 Zpool
CcminerTpruvot         X15                                  17.02 MH/s            0.00001          52%            0.00086 ItalYiiMP
CcminerNanashi         X15                                  16.35 MH/s            0.00001          52%            0.00086 ItalYiiMP
CcminerKlaust          X15                                  15.64 MH/s            0.00001          52%            0.00086 ItalYiiMP
CcminerKlaust          Blakecoin                             7.44 GH/s            0.00016          39%            0.00002 Zpool
CcminerNanashi         Blakecoin                             7.32 GH/s            0.00016          39%            0.00002 Zpool
CcminerTpruvot         Blakecoin                             7.27 GH/s            0.00016          39%            0.00002 Zpool
CcminerNanashi         Veltor                               36.01 MH/s            0.00018          37%            0.00497 Zpool
CcminerTpruvot         Veltor                               46.65 MH/s            0.00023          37%            0.00497 Zpool
CcminerXevanPalgin     Xevan                                 5.53 MH/s            0.00013          29%            0.02400 AHashPool
CcminerXevan           Xevan                                 5.96 MH/s            0.00014          29%            0.02400 AHashPool


   Type: {AMD, NVIDIA}

Miner      Algorithm            Speed BTC/Day Accuracy BTC/GH/Day Pool
-----      ---------            ----- ------- -------- ---------- ----
Excavator1 Equihash       799.00  H/s 0.00044     100%  556.85320 MiningPoolHubCoins-Zcash
Excavator2 Equihash       784.00  H/s 0.00044     100%  556.85320 MiningPoolHubCoins-Zcash
Prospector Ethash          57.07 MH/s 0.00036     100%    0.00639 MiningPoolHub-Ethereum
Eminer     Ethash          56.24 MH/s 0.00036     100%    0.00639 MiningPoolHub-Ethereum
Excavator1 Ethash          54.74 MH/s 0.00035     100%    0.00639 MiningPoolHub-Ethereum
Excavator2 Ethash          52.06 MH/s 0.00033     100%    0.00639 MiningPoolHub-Ethereum
Prospector CryptoNight      1.26 KH/s 0.00030     100%  237.84880 MiningPoolHubCoins-Monero
Excavator2 Pascal           1.67 GH/s 0.00028      99%    0.00017 NiceHash
Excavator1 Pascal           1.60 GH/s 0.00027      99%    0.00017 NiceHash
Excavator2 DecredNiceHash   4.72 GH/s 0.00024      99%    0.00005 NiceHash
Excavator1 DecredNiceHash   4.64 GH/s 0.00024      99%    0.00005 NiceHash
Excavator2 SiaNiceHash      2.95 GH/s 0.00015      99%    0.00005 NiceHash
Excavator1 SiaNiceHash      2.91 GH/s 0.00015      99%    0.00005 NiceHash
Prospector Skunk           29.59 MH/s 0.00018      73%    0.00605 AHashPool




   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Lyra2z-NVIDIA\ccminer_cuda9.exe -a lyra2z -o stratum+tcp://lyra2z.mine.ahashpool.com:4553 -u
                                               16GM2SwAnM7dciaHxJeShGGtVWrJ3HjsLy -p z97g7,c=BTC


   Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
1.34 KH/s 00 Days 00 Hours 01 Minutes Once     Bin\CryptoNight-NVIDIA\xmrig-nvidia.exe --api-port 3335 -a cryptonight -o
                                               stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:20580 -u platinum4.z97g7 -p x
                                               --keepalive --nicehash --donate-level 1



Miner         Pool      Algorithm Watchdog Timer
-----         ----      --------- --------------
CcminerLyra2z AHashPool Lyra2z         0 Seconds



Miner                  BTC                                                                    USD
-----                  ---                                                                    ---
MultiPoolMiner         0.00064 ±6,434,714,385,338,500,000% (0.00000-41,405,549,220,882.30000) 10.14111 ±6,434,714,385,338,500,000% (0.00000-6...
PalginNvidia-NeoScrypt 0.00080 ±15% (0.00070-0.00091)                                         12.56988 ±15% (10.96119-14.41466)

**Comment by fonyo** [comment]
Please run the ResetProfit.bat file.

**Comment by platinum4** [comment]
Yeah I had ran the ResetProfit and this was the results.  Kinda why I was just interested and asking.  I don't mind making trillions of percent in profit...

**Comment by platinum4** [comment]
Yeah see, ran it, after closing all processes entirely.

https://i.imgur.com/il99mws.png

Same results
