### ISSUE TITLE
Help wanted: how-to run '$Miner.GetHashRate' in start-job

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#846]
In my code I am running three miner instances (one for each card type: 1 x GTX1080, 1 x GTX1070 1 x GTX10603GB. I want to parallelize the following line
`$Miner_HashRate = $Miner.GetHashRate($Miner.Algorithm, ($Miner.New -and $Miner.Benchmarked -lt $Strikes))`
in  following code snipped:
```
#Save current hash rates
    $ActiveMiners | ForEach-Object {
        $Miner = $_
        $Miner.Speed_Live = 0
        $Miner_HashRate = [PSCustomObject]@{}

        if ($Miner.New) {$Miner.Benchmarked++}

        if ($Miner.Process -and -not $Miner.Process.HasExited) {
            $Miner_HashRate = $Miner.GetHashRate($Miner.Algorithm, ($Miner.New -and $Miner.Benchmarked -lt $Strikes))
            $Miner.Speed_Live = $Miner_HashRate.PSObject.Properties.Value

            $Miner.Algorithm | Where-Object {$Miner_HashRate.$_} | ForEach-Object {
                $Stat = Set-Stat -Name "$($Miner.Name)_$($_)_HashRate" -Value $Miner_HashRate.$_ -Duration $StatSpan -FaultDetection $true

                #Update watchdog timer
                $Miner_Name = $Miner.Name
                $Miner_Algorithm = $_
                $WatchdogTimer = $WatchdogTimers | Where-Object {$_.MinerName -eq $Miner_Name -and $_.PoolName -eq $Pools.$Miner_Algorithm.Name -and $_.Algorithm -eq $Miner_Algorithm}
                if ($Stat -and $WatchdogTimer -and $Stat.Updated -gt $WatchdogTimer.Kicked) {
                    $WatchdogTimer.Kicked = $Stat.Updated
                }

                $Miner.New = $false
            }
        }

        #Benchmark timeout
        if ($Miner.Benchmarked -ge ($Strikes * $Strikes) -or ($Miner.Benchmarked -ge $Strikes -and $Miner.Activated -ge $Strikes)) {
            $Miner.Algorithm | Where-Object {-not $Miner_HashRate.$_} | ForEach-Object {
                if ((Get-Stat "$($Miner.Name)_$($_)_HashRate") -eq $null) {
                    $Stat = Set-Stat -Name "$($Miner.Name)_$($_)_HashRate" -Value 0 -Duration $StatSpan
                }
            }
        }
    }
```
This what I tried so far without any success:

```
$Miner_HashRate = Start-Job -ArgumentList $Miner, $Strikes -ScriptBlock {
    param($Miner, $Strikes)
    $Miner.GetHashRate($Miner.Algorithm, ($Miner.New -and $Miner.Benchmarked -lt $Strikes))
}
```

**Comment by aaronsace** [comment]
I've thought about parallelizing this a long time ago but it does add a bit a complexity. 

The issue maybe because you are passing an 'object' and it's starting a new separate PowerShell process.

**Comment by UselessGuru** [comment]
> you are passing an 'object' and it's starting a new separate PowerShell process

Does not make me any smarter :-)

I assume that with the old 'non-miner class' include.ps1 Get-Hashrate function it would have been much easier.
I still have not understood why you moved to the miner class thingy in the first place.

**Comment by grantemsley** [comment]
Sharing variables between separate threads (which start-job creates) is...tricky.  Multithreaded processing in powershell will hurt your brain.

I haven't really looked at that part of the code yet, but let me take a peak and see what I can see.

When you do try it that way, any idea what does happen (besides "it didn't work"?)

**Comment by UselessGuru** [comment]
>  When you do try it that way, any idea what does happen (besides "it didn't work"?)

It completes in no time, no error, no return value.

**Comment by grantemsley** [comment]
Ah...yeah, I see it now.  That's how job processing works.  It returns immediately.  Then your scriptblock runs separately and waits patiently for you to retrieve the results.  I tested it in a debugger, and it's not an issue with it being a separate thread, just that you aren't waiting to receive the data.

You're setting ```$Miner_HashRate``` to be a pointer to the job you created.  So you could do ```Wait-Job $Miner_HashRate``` and ```Receive-Job $Miner_HashRate```.

Take a look at include.psm1, likes 268-295
It starts a job, sleeps for a second, then uses Receive-Job to get the response.

You'll need to do something similar, but waiting until all your jobs have finished.  You won't want to wait a set amount of time, but rather loop over all the jobs you've created waiting for them to all exit.

So you could create an array to hold all your jobs, run the loop that kicks off the jobs, run another loop that waits for them all to finish, and run yet another loop that receives the data.  Or I'm sure someone has written a decent powershell module for job handling somewhere you could add.  But unless you have a lot of miners running, I'm not sure it's worth the effort.  Starting jobs requires another instance of powershell to spin up, which takes time.  In the ideal case where all the miners are returning stats almost instantly, it could actually end up being slower.  Runspaces are faster, but even harder to wrap your brain around.

I wonder though...is that even necessary to wait for their results?  The API files should be able to update ```$Miner.Speed_Live``` all on their own, and do the Set-Stat call and everything.  I'm not sure that you could update the watchdog timer from there though.  But if you can, then maybe you wouldn't even have to wait, they could just update the stats in the background.

**Comment by UselessGuru** [comment]
> Ah...yeah, I see it now. That's how job processing works. It returns immediately

I know all that.

But in this scenario the **completes** immediately (I can see all job properties. Status = Complete). But there is no return value.$ Miner_HashRate  remains $null

**Comment by grantemsley** [comment]
And if you do

```
Wait-job $miner_hashrates
Recieve-job $miner_hashrates
```
Then you should see the output.  You are starting a job but never trying to receive its output.

**Comment by UselessGuru** [comment]
Wait-job $miner_hashrate
Receive-job $miner_hashrate

Nada - try for yourself - returns immediately:
```
Wait-job $miner_hashrate
Receive-job $miner_hashrate

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command                  
--     ----            -------------   -----         -----------     --------             -------                  
31     Job31           BackgroundJob   Completed     True            localhost            ...    

Method invocation failed because [Deserialized.Wrapper] does not contain a method named 'GetHashRate'.
    + CategoryInfo          : InvalidOperation: (GetData:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : localhost

```
$Miner_HashRate | fl
```
HasMoreData   : False
StatusMessage : 
Location      : localhost
Command       : 
                    param($Miner, $Strikes)
                    $Miner.GetHashRate($Miner.Algorithm, ($Miner.New -and $Miner.Benchmarked -lt $Strikes))
                
JobStateInfo  : Completed
Finished      : System.Threading.ManualResetEvent
InstanceId    : 3edae413-979f-41f6-96d0-7449b39d6e2d
Id            : 31
Name          : Job31
ChildJobs     : {Job32}
PSBeginTime   : 28.12.2017 07:34:15
PSEndTime     : 28.12.2017 07:34:15
PSJobTypeName : BackgroundJob
Output        : {}
Error         : {}
Progress      : {}
Verbose       : {}
Debug         : {}
Warning       : {}
Information   : {}
State         : Completed
```

**Comment by grantemsley** [comment]
Hmm...ok then.  It's saying the method doesn't exist. I did test it, but in a debugger.

That error hints that it's not passing the actual miner object, but a deserialized copy of it which doesn't include methods. That's why the member doesn't exist.

Now I'm real curious...why did it work for me?  It shouldn't have. I'll test it again in the morning.

**Comment by UselessGuru** [comment]
> I did test it, but in a debugger.

So do I, in good old PowerGui

**Comment by grantemsley** [comment]
Alright, I don't know what I screwed up testing before, but its not working now.

To get the actual miner class back, you'd have to do everything the script does to create it inside your script block.

So something like (completely untested) this for your scriptblock:

```
using module .\Include.psm1
param($Miner, $Strikes)
Get-ChildItem "APIs" | ForEach-Object {. $_.FullName}

$MinerObject = New-Object $Miner.API -Property @{
                Name                 = $Miner.Name
                Path                 = $Miner.Path
                Arguments            = $Miner.Arguments
                Wrap                 = $Miner.Wrap
                API                  = $Miner.API
                Port                 = $Miner.Port
                Algorithm            = $Miner.HashRates.PSObject.Properties.Name #temp fix, must use 'PSObject.Properties' to preserve order
                Type                 = $Miner.Type
                Index                = $Miner.Index
                Device               = $Miner.Device
                Device_Auto          = $Miner.Device_Auto
                Profit               = $Miner.Profit
                Profit_Comparison    = $Miner.Profit_Comparison
                Profit_MarginOfError = $Miner.Profit_MarginOfError
                Profit_Bias          = $Miner.Profit_Bias
                Speed                = $Miner.HashRates.PSObject.Properties.Value #temp fix, must use 'PSObject.Properties' to preserve order
                Speed_Live           = $Miner.Speed_Live
                Best                 = $Miner.Best
                Best_Comparison      = $Miner.Best_Comparison
                Process              = $Miner.Process
                New                  = $Miner.New
                Active               = $Miner.Active
                Activated            = $Miner.Activated
                Status               = $Miner.Status
                Benchmarked          = $Miner.Benchmarked
}

$MinerObject.GetHashRate($Miner.Algorithm, ($Miner.New -and $Miner.Benchmarked -lt $Strikes))
```
Something like that should create a new miner object inside your job with all the same information, and that object will have the GetHashRate method.  But since it requires importing all the APIs and Include.psm1, it's not going to be very fast.

**Comment by UselessGuru** [comment]
@grantemsley 

Getting there - thank you for your help!

Next challenge

I am doing a loop:

```
        #Save current hash rates
        $ActiveMiners | ForEach-Object {
            $Miner = $_
            $Miner.Speed_Live = 0
            $Miner_HashRate = [PSCustomObject]@{}

            if ($Miner.New) {$Miner.Benchmarked++}
            if ($Miner.Process -and -not $Miner.Process.HasExited -and $Miner.Port) {
                "Saving stats for $($Miner.Device)... " | Out-Host

                $Miner.Miner_HashRate =  Start-Job ([scriptblock]::Create("
                    Set-Location('$(Get-Location)')
                    . 'APIs\$($Miner.API).ps1'")) -ArgumentList ($Miner, $Strikes) -ScriptBlock {
                    param($Miner, $Strikes)
                    $MinerObject = New-Object $Miner.API -Property @{
                        Name                 = $Miner.Name
                        Path                 = $Miner.Path
                        Arguments            = $Miner.Arguments
                        Wrap                 = $Miner.Wrap
                        API                  = $Miner.API
                        Port                 = $Miner.Port
                        Algorithm            = $Miner.HashRates.PSObject.Properties.Name #temp fix, must use 'PSObject.Properties' to preserve order
                        Type                 = $Miner.Type
                        Index                = $Miner.Index
                        Device               = $Miner.Device
                        Device_Auto          = $Miner.Device_Auto
                        Earning              = $Miner.Earning
                        Profit               = $Miner.Profit
                        Profit_Comparison    = $Miner.Profit_Comparison
                        Profit_MarginOfError = $Miner.Profit_MarginOfError
                        Profit_Bias          = $Miner.Profit_Bias
                        Speed                = $Miner.HashRates.PSObject.Properties.Value #temp fix, must use 'PSObject.Properties' to preserve order
                        Speed_Live           = $Miner.Speed_Live
                        Best                 = $Miner.Best
                        Best_Comparison      = $Miner.Best_Comparison
                        Process              = $Miner.Process
                        New                  = $Miner.New
                        Active               = $Miner.Active
                        Activated            = $Miner.Activated
                        Status               = $Miner.Status
                        Benchmarked          = $Miner.Benchmarked
                        PowerDraw            = $Miner.PowerDraw # Power consumption of all cards for this miner
                        PowerCost            = $Miner.PowerCost # = Total power draw * $PowerPricePerKW
                        ComputeUsage         = $Miner.ComputeUsage
                        Pool                 = $Miner.Pool
                    }
                    $MinerObject.GetData($Miner.Algorithm, ($Miner.New -and $Miner.Benchmarked -lt $Strikes))
                }
            }
        }
```
How can I retrive the data returned by each job and feed it back to the correct miner object?

**Comment by UselessGuru** [comment]
Solved.
Start-Job -Name ... Get-Job -Name ...helps :-)

**Comment by grantemsley** [comment]
@UselessGuru glad I could help.  Once you'd done I'm quite curious if it's actually faster doing it that way.

**Comment by UselessGuru** [comment]
> Once you'd done I'm quite curious if it's actually faster doing it that way.

It is indeed much faster and scales well.
Hashrate readout during benchmark takes longer than 6*5=30 seconds.
I have 3 different card types in my box.. So 3 loops will take close to 120 seconds which might even trigger the wachdog stage 1,
Running the GetHashrate in parallel takes only little longer than a single readout (< 50 seconds).
