### ISSUE TITLE
All Lyra2z using 44% of power

### ISSUE THREAD

**Issue by Luffy-2** [MultiPoolMiner/MultiPoolMiner#847]
CCMinerLyra2z, CCMinerNanashi, CCMinerTPruvot. All of them use only 44% of power of my NVIDIA card, and they are the only Lyra2z miners available, which is a nice algorithm to mine. What are the options here?

**Comment by grantemsley** [comment]
Add "-i <some number between 8-25>" to the arguments in the files in the Miners directory.  That will adjust the intensity.

**Comment by Luffy-2** [comment]
Thanks. Your comment and edit solved it for me.

**Comment by FabianGabor** [comment]
I asked about this on djm34/ccminer-msvc2015 page and the dev's response was that ["it is limited by shared memory capacity" ](https://github.com/djm34/ccminer-msvc2015/issues/18#issuecomment-334820631)
