### ISSUE TITLE
how can I limit algorithm for just cpu when using type amd,cpu

### ISSUE THREAD

**Issue by CptanPanic** [MultiPoolMiner/MultiPoolMiner#851]
Hello,
I want to enable CPU mining in addition to CPU. But running benchmark takes forever. Let's say I only want to allow crytonight algo for CPU, but all of them for gpu. How to do this?

**Comment by UselessGuru** [comment]
> allow crytonight algo for CPU, but all of them for gpu. How to do this?

I don't really understand why you think this is desirable :-)
Out of the box there is no such feature.
But: Edit all CPU miner files and disable all unwanted algos.

**Comment by fonyo** [comment]
You can run two instances of MultiPoolMiner, one for GPU and one for CPU. Extract the .zip package twice, eg. MPM2.7.1.1GPU and MPM2.7.1.1CPU. Set your start.bat with the CPU only version as below:
    [...config...] -type cpu -algorithm cryptonight [...rest of the config...]

**Comment by CptanPanic** [comment]
@fonyo, perfect thanks.

**Comment by UselessGuru** [comment]
> **Extract the .zip package twice**

Very important! Do not attempt to run two instances in parallel from the same source.
