### ISSUE TITLE
In stats display what is meant by MultiPoolMonitor profit?

### ISSUE THREAD

**Issue by CptanPanic** [MultiPoolMiner/MultiPoolMiner#856]
I don't see it listed anywhere, but what does this type of message mean "... more profitable" and what is mean by MultiPoolMiner vs. the actual miner execuble? 

```
MultiPoolMiner is between 0% and 6% more profitable than the fastest miner:

Miner                USD
-----                ---
MultiPoolMiner       2.62024 ±9% (2.39849-2.86250)
CcminerLyra2z-Lyra2z 2.54633 ±8% (2.35786-2.74986)
```

**Comment by aaronsace** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner#q5-multipoolminer-is-xx-more-profitable-what-does-this-mean

**Comment by CptanPanic** [comment]
Thanks
