### ISSUE TITLE
prospector using cpu when just amd is selected.. 

### ISSUE THREAD

**Issue by aaronsta1** [MultiPoolMiner/MultiPoolMiner#857]
i noticed today that mining with prospector is using the cpu at 100%.. 
i have version 2.7.1.1 i noticed there is a newer version but im not sure this has been addressed?

**Comment by aaronsace** [comment]
I don't think so: 
https://github.com/semtexzv/Prospector/releases

**Comment by aaronsta1** [comment]
i disabled it for now, but it says it finds amd on 0:0 and 0:1 and the 1 is my cpu..
