### ISSUE TITLE
Start.bat attached. Questions. 

### ISSUE THREAD

**Issue by cmbconcretefire** [MultiPoolMiner/MultiPoolMiner#859]
[Start-Zpool.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1592511/Start-Zpool.txt)

1) Since I'm using zpool, I believe I can delete the '-username drog1' part, correct? Isn't all that matters at zpool is the workername? 

2) If I have already installed powershell 6, Can I delete this section > 'msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc.2/PowerShell-6.0.0-rc.2-win-x64.msi -qb!' 

3) If I add the word 'start' before > 'powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%" ------ it still doesn't start the powershell

Yes, I'm donating 30 min cause I don't think these guys like me very much. But I'm trying to learn so I can help others and take some of the weight off of them. I like this project and have plenty of free time to help.

**Comment by aaronsace** [comment]
Yes but MiningPoolHub will be disabled for use as a backup pool. 
Yes. 
'Start' will open in a new window.
