### ISSUE TITLE
Increased bandwidths usage from multipoolminer

### ISSUE THREAD

**Issue by LSTOMAR** [MultiPoolMiner/MultiPoolMiner#860]
I have been using the miner for around 3 days now and it has used alone around 35 gigs of internet bandwidth. I have been mining before and usually i would use around 4-6 gigs for the same period. I have a 16 mbps down 1 mbps up internet but with limited bandwidth. is there a way to limit bandwidth usage ? should i limit internet speed if it is linear with the usage of bandwidth?

**Comment by UselessGuru** [comment]
> is there a way to limit bandwidth usage ? should i limit internet speed if it is linear with the usage of bandwidth?

MPM is the parent process launching all miners. The miners themselvse generate a lot of traffic.
Are you sure it is MPM using this bandwith? Or does your measurement tool just cumulate all data consumption for all processes that were launched by MPM?

**Comment by LSTOMAR** [comment]
![usage data](https://user-images.githubusercontent.com/11030734/34432569-1b95a2fa-ec81-11e7-86a5-ec9166225d97.jpg)

I doubt its actually MPM eating up bandwidth but maybe how MPM handles the miners, i have attached a screenshot of the powershell using around 39 gigs , i dont use powershell myself directly and it had never reached this amount of bandwidth before . So the only explaination is MPM does something that am not seeing. Also when i used to mine with direct pool or nicehash as i said i only use a fraction of this amount. Idk what to do now

**Comment by UselessGuru** [comment]
Where do you get this screenshot from?

**Comment by LSTOMAR** [comment]
data usage in windows 10 settings

**Comment by UselessGuru** [comment]
Understood.
I just reset my stats. Let's see what eats bandwith, so far it's not powershell

**Comment by LSTOMAR** [comment]
Nice. I would also appreciate if you could update the thread if you reach same results. I would love to resume mining but at this rate my internet quota would end  in less than two weeks.

**Comment by jayntguru** [comment]
I just checked a w10 system. Nowhere near that use.

**Comment by lukiifaz** [comment]
I have 346MB + 2500MB (30 days) miners trafic.

**Comment by aaronsace** [comment]
PWSH is PowerShell so it's not necessarily MultiPoolMiner.

**Comment by LSTOMAR** [comment]
>  i dont use powershell myself directly and it had never reached this amount of bandwidth before .

Tho, i will test MPM tonight again and see if data usage increases significantly overnight. If it does then something must be wrong.

**Comment by aaronsace** [comment]
FYI, I have 417mb over 30 days.

**Comment by platinum4** [comment]
1.13GB so far, this seems like an outlier

**Comment by LSTOMAR** [comment]
Reset everything, re-installed and tested for 24 hours. Usage is around 120 mb, not like the ones u suggested but way lower than previous results. Thanks for the help guys . I will close the thread now.
