### ISSUE TITLE
keep getting api hashrefinery returned nothing

### ISSUE THREAD

**Issue by aaronsta1** [MultiPoolMiner/MultiPoolMiner#863]
but when i go to the url http://pool.hashrefinery.com/api/status it works just fine? 
neoscrypt on hashrefinery should be number 1 for me with almost twice as much profit, yet it never chooses it :(

**Comment by UselessGuru** [comment]
The code that polls the API is fine.
The API itself is flaky. You can get lucky and might get an answer, but if not you see yellow.
2 solutions:
a) live with it
b) remove the pool file
