### ISSUE TITLE
Question : -switchingprevention 2

### ISSUE THREAD

**Issue by lmlim** [MultiPoolMiner/MultiPoolMiner#865]
Hi,

Sorry if this has been asked/talked about, but I can't find documentation of this option in readme.
what are the numbers accepted and their effects?

thanks

**Comment by platinum4** [comment]
I think it's a minute barrier, with '2' being 2 minutes.

He first tried '10' but it wasn't really switching at all then.  For NVIDIA with lots of algos you want lower switching prevention.  For AMD with 2/3 algos only you prolly want higher switching prevention.  This is setting tailored to what you have and what you want to do.

**Comment by grantemsley** [comment]
It's not in minutes at all.  It affects the Price_Bias.  The actual code is on line 153 of MultiPoolMiner.ps1:

```Add-Member Price_Bias ($Pools.$_.Price * (1 - ($Pools.$_.MarginOfError * $SwitchingPrevention * [Math]::Pow($DecayBase, $DecayExponent))))```

What exactly does that mean?  I don't know...aaronsace is a wizard, and that is part of his magic.  But it certainly isn't minutes.

**Comment by platinum4** [comment]
Ah, well SP 2 still launches a shit load of miners pretty frequently.  Like literally every 2-5m for 2x 1070s  my other 6 card rigs i dont stare at but i notice this one often

**Comment by platinum4** [comment]
https://github.com/nemosminer/NemosMiner-v2.3/issues/40

**Comment by thericeking** [comment]
I'm glad I am not the only one that was wondering the same thing. Can we get an answer? We need a wiki for this project. I'll be happy to contribute to a wiki for the few things I know and understand.

**Comment by fonyo** [comment]
#877
