### ISSUE TITLE
A bunch of miners don't seem to work...

### ISSUE THREAD

**Issue by Mystere** [MultiPoolMiner/MultiPoolMiner#866]
So I keep having problems with a lot of miners.  Mostly they just crash a few seconds into benchmarking.   I have 6x1080Ti and this works pretty well with Excavator, ccminer (usually.. x11gost seems to kill my drivers from time to time), and 

Reorder/cgminer, xmrig, prospector are the worst.  cgminer says something about failing to init error -2, before crashing.  prospector just seems to only start 1 or 2 threads then fails.  xmrig fails almost right away.

Anything I can look at?  I have plenty of virtual memory (80GB) configured, and i'm running windows 10 fall creators update with the latest NVidia drivers.

**Comment by platinum4** [comment]
Nope these usually fail or have shitty hashrates anyway.  There are a bunch of miners but not all are great and some are better for some cards.  Don't worry about reorder/cgminer, xmrig, prospector(skunk) but excavator is kinda shitty with overclocks so if you are doing Blake2s or something else on that you will probably lose a card if OC'd

Once the miners fail or if they fail during mining the results end up making the miners get discarded so-to-speak, so if you it keeps driving cards to sick or something then the hashrate in the Stats file will go down and then it won't be profitable, and you won't end up using that miner.

That happens with me and nsgminer

**Comment by thericeking** [comment]
All the miners work for me perfectly fine since day one. Never a single one of them fail for me. I've only been using this miner for a little over a month. I have it installed in five miners and yes I closely monitor the miner during bench marking and I get zero errors. Make sure you installed all the lastest GPU drivers and all dependencies listed. Also not having too much crap running in Windows background during PC startup.

**Comment by platinum4** [comment]
He's prolly running CPU miners on a dual core celeron that just lets a miner boot and thats it

**Comment by thericeking** [comment]
Well FML. @Mystere today while working on a new rig I'm building I get CGMINER crashes :(

**Comment by fonyo** [comment]
@Mystere are you still having issues?
