### ISSUE TITLE
Wildly different payouts between cards, any thoughts on this?

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#867]
I'm running a GTX 950 and a GTX 1060 on two different machines both using the same version of multipool miner with same options.

The gtx1060 is running on ahashpool and the 950 is running on hashrefinery just so I can keep track of the numbers for each.  The gtx1060 has twice the hashrate or better of the GTX950 yet in the past day or so, the GTX950 is doing like 2.20 and the GTX1060 is doing like 2.90 or so when it should be doing double.  The only algorithm that is different between the two is blake2s because hashrefinery doesn't run that one.    I removed blake2s from the 1060 on ahashpool however its run only like an hour and change the past day so I don't know that it really is making a difference.  Is hashrefinery that much of a better pool?

Also, when I was just running all pools, it would almost always default to ahashpool as the most profitable one which doesn't make too much sense if hash refinery is more profitable.  I suppose I could try swapping the pools between the two cards as well to see the difference.

**Comment by platinum4** [comment]
I don't know but if you're judging autoexchange profitability on a down-trend market day I wouldn't be surprised.  AHashpool is on 0% fee right now for a week because of an X17 chain split so I'd expect them to be the most profitable.

**Comment by robl45** [comment]
Yes.  Ahash should be more profitable yet hash refinery is beating it badly.   I'm using flat 14000 for exchange rate when I do the calculations.

**Comment by platinum4** [comment]
Neither of those GPUs do X17 well which is what is mined most on AHash

**Comment by robl45** [comment]
Still both GPU's have been doing a lot of X17 and the GTX950 was doing 2.20 a day on hashrefinery and the 1060 2.88 on Ahashpool.  The GTX1060 should be doing 4.40 if gtx950 doing 2.20.  I switched the pools now between the cards to test.  if Ahash has no fee now, it should do even better.  Plus,  Ahash will all pools included will almost always be the one that is mined as most profitable which clearly at this point doesn't seem to be the case.
