### ISSUE TITLE
PowerShell Core 6 has stopped working

### ISSUE THREAD

**Issue by ConwayHsieh** [MultiPoolMiner/MultiPoolMiner#869]
I have hit this issue where PowerShell keeps crashing for no apparent reason. There's nothing of importance in the logs; also, when it tries to reinstall PowerShell 6, which I've already installed, it gives an error as well.

Screenshots and logs are below. Any help is appreciated!

[2017-12-29_22-27-20.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1594204/2017-12-29_22-27-20.txt)
[2017-12-29_22-30-31.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1594205/2017-12-29_22-30-31.txt)
[2017-12-29_22-33-39.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1594206/2017-12-29_22-33-39.txt)

![powershell_core6_hasstoppedworking](https://user-images.githubusercontent.com/7256862/34451879-8f20dae8-ece8-11e7-8dbb-18db8541a3cd.PNG)
![windows_powershellhasstoppedworking](https://user-images.githubusercontent.com/7256862/34451880-8f4db1ee-ece8-11e7-8ec4-a9a0ec8f4da2.PNG)
![3](https://user-images.githubusercontent.com/7256862/34451881-8f616e5a-ece8-11e7-960c-79834e2f7d63.PNG)

**Comment by richardg867** [comment]
Bit of a long shot, but try running Memtest86 on your rig.

**Comment by UselessGuru** [comment]
> Bit of a long shot, but try running Memtest86 on your rig.

I fear this is about the best help you will get on this issue.

MPM is running fine on lots of boxes, so it rather NOT the MPM code.
Just note, the PowerShell 6 is still in rc (release candidate) status, so there may be errors.

**Comment by aaronsace** [comment]
@ConwayHsieh PowerShell 5 still works if you want to try that. I'm thinking memory problems too though.

**Comment by UselessGuru** [comment]
Is this still happening?
If yes then I suggest you update to the [latest powershell core version](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.1) (uninstall all other versions).
Pleases close if you no longer have this issue - TIA

**Comment by grantemsley** [comment]
Closing outdated issue.  If this is still a problem in the latest version (and there currently isn't an open issue for it) please open a new one.

**Comment by Kettoch** [comment]
I am running into this issue as well.  In fact, I just completely reinstalled the affected system from scratch and it is happening again.  It may run fine with powershell 5, but when the script makes references to PWSH, then it requires 6, now.
