### ISSUE TITLE
Do not use localized number format for reporting api

### ISSUE THREAD

**Issue by tarioch** [MultiPoolMiner/MultiPoolMiner#870]
I really like the new reporting.

One thing I encountered is, that it seems to use the localized number format when posting, this can lead to some issues when posting from machines with different locales (e.g. some machines send profit with a , instead of a . as separator).

@grantemsley Maybe you can help? I'm a total powershell newbie.

**Comment by grantemsley** [comment]
What kind of issues does it cause?  Can you post a screenshot?

**Comment by tarioch** [comment]
I have my own listener to react to the post request. I currently have a workaround there, but it would be nicer if the wire format of the message would be something that's always the same, independent of how numbers are represented on the client.

**Comment by aaronsace** [comment]
@grantemsley I think using numbers (not strings) then converting them to JSON would solve this.

**Comment by grantemsley** [comment]
@aaronsace That might help with the thousands separators...but some locales use comma for decimal point, others use period.  Even just using unformatted numbers, powershell will automatically format them to your locale.  I went into region settings and changed decimal symbol to # just to test it, and:

```
PS C:\> $x = 10000.12345
PS C:\> $x
10000#12345
PS C:\>
```

I'm sure there's a way to force which locale it formats the numbers as, without changing the system settings.  Looking into it.

**Comment by aaronsace** [comment]
This should output standard JSON string that is not localized: 
`10000.12345 | ConvertTo-Json`

**Comment by grantemsley** [comment]
Hmm...it does...but then I can't use ConvertTo-Hash, because that converts it to a string with the locale specific decimal point.

I suppose it doesn't *need* to convert them, that could be done on the webpage as well.
