### ISSUE TITLE
Ability to select specific coins not just algorithms

### ISSUE THREAD

**Issue by smaugfm** [MultiPoolMiner/MultiPoolMiner#872]
I will explain using MiningPoolHub but I believe the idea stays the same over all similar pools. Some coin jumps to the profitability top, you mine but exchange takes time and by the time pool actually sells mined coin it can be no longer profitable. I see that people tend to restrict algos to 2 or 3 that usually stay on top of the profitability chart and stick with them to avoid this spikes. For example, for Nvidia it can be lyra2z and equihash for now.
However, for example equihash has 4 coins on MPH and while the algo stays profitable almost all the time coins tend to gain and lose profitability much and we have the same problem as above.

So I suggest to add a feature to calculate profitability and mine coins and not just the algos. I believe its fairly important feature

**Comment by fonyo** [comment]
There is the -switchingprevention feature built for this. #877 

If you use -poolname miningpoolhub, there is nothing you can do to control this as switching coins within the same algorithm is controlled by the pool itself. Use miningpoolhubcoins instead and a higher -switchingprevention number such as 10 to remedy this problem.

Just as an example: If you are not using miningpoolhub as a pool at all, then setting a higher number for -switchingprevention will do the trick.

All suggestions above will only work if you have reasonable mining time done with MultiPoolMiner (at least a week) as it needs to accumulate enough coin data to evaluate and prevent spikes accurately using -switchingprevention.
