### ISSUE TITLE
System locks up, can't detect the reason

### ISSUE THREAD

**Issue by komer83** [MultiPoolMiner/MultiPoolMiner#873]
Attaching the last log.
The issue: the system sometimes hangs without any reason, something that doesn't happens with NHM. I can't see anything in the logs that suggests an error (Am I missing something?) 

At first I was sure it was a CPU issue during benchmarks, so I disabled it and still no change.
I after that decided to force all CCminers to power limit 95% (not in the logs I believe) and still no change. 
As it's completely random, I tried to see if there's any connection in the algorithms, and saw nothing special. 
I don't think it's OC issue, I only OC the card (both 1080ti) to +100 GPU and memory both with power target of 100%, temperatures are in the safe limits and there's no overheating alerts. I don't know if it's a specific miner fault it happens during the switching, perhaps the experts can look at the logs and connect the dots?

[2017-12-30_13-05-14.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1594425/2017-12-30_13-05-14.txt)

**Comment by grantemsley** [comment]
If you are having issues with crashes while switching, add ```-delay 5``` to your switches in start.bat

That will make it wait 5 seconds between stopping the miners and starting new ones.

**Comment by komer83** [comment]
I'm checking it now, will post if anything new happens.

**Comment by UselessGuru** [comment]
Any news?

**Comment by komer83** [comment]
Last night it crashed again and no error in log, for now I reduced the OC to +75 and kept the intensity same as before. For now everything runs again since 6am (it's now 3pm here) 

it might be unspecified launch failure from CCminer, but power limit didn't changed anything but lowering the OC did.

https://github.com/nicehash/NiceHashMiner/issues/171

**Comment by komer83** [comment]
24 hours and no crush, it was the unspecified launch failure.

**Comment by fonyo** [comment]
Closing this as resolved. Please be mindful with OC settings when using MPM. Some algorithms will make your rig unstable with too high OC due to their higher power consumption or their inefficient miner code.

**Comment by Noirad** [comment]
I'm having the same issue, not OC any settings.

I'm using a 1080ti, 1080 and 1070.

When use MPM, at some point the 1080TI will drop off –– this doesn't happen with the other tools. 

If I use CC miner to direct mine on zpool, no issues.

I don't experience any issues using the Legacy NH miner either.
