### ISSUE TITLE
Why do the include-module lines in Include.psm1 use the full path?

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#875]
Include.psm1 starts with:
```
Import-Module "$env:Windir\System32\WindowsPowerShell\v1.0\Modules\NetSecurity\NetSecurity.psd1" -ErrorAction Ignore
Import-Module "$env:Windir\System32\WindowsPowerShell\v1.0\Modules\Defender\Defender.psd1" -ErrorAction Ignore
```

This causes errors on some systems - specifically Windows Server 2012R2 with Powershell 5.1 installed.  The Defender module does not exist on Windows server.

When I run the script, I get:
```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
At line: 1 char: 1
+ .\MultiPoolMiner.ps1
```

Turns out, its from trying to load that module - commenting on the second line of Include.psm1 makes it work perfectly.  Doesn't make any sense, right?  Import-Module should just fail gracefully and carry on.  But it doesn't.

If there isn't any particular reason for using the full path to the module, then it should probably be:
```
Import-Module NetSecurity -ErrorAction Ignore
Import-Module Defender -ErrorAction Ignore
```

If there is a reason, then the paths need to be tested to make sure they exist before trying to import.

Also, for performance sake, would it make sense to move those includes into the main script instead of Include.psm1?  Include gets imported for pretty much every new powershell subprocess, but none of them use the firewall or defender stuff.

**Comment by aaronsace** [comment]
Was trying to just fix the issues compatibility with PowerShell 6 and Windows 7 and this worked. 

What you've put sounds great; if it doesn't cause any problems, do a Pull Request.
