### ISSUE TITLE
Odd issue with include.p(m)s1

### ISSUE THREAD

**Issue by gak45** [MultiPoolMiner/MultiPoolMiner#876]
For whatever reason X17 always is a touch wonky on a couple of my rigs. Its variance always is +/- 20 percent. It still is highly profitable. In the past I just go into the include.ps1 file and mod the min and max fault tolerances. BUT with the latest release it errors out saying there is an error on line 262(IIRC) of ps1 file and crashes. Put it back to .1 from .2 and it works fine. 

Sooo what was changed, how do a I mod the tolerance levels (especially min levels), and can you update the FAQ to the new way? That or is it just a gremlin in this system (as this mod works perfect on my other rigs)?

**Comment by UselessGuru** [comment]
Exact error message, screenshots and logs please.

**Comment by gak45** [comment]
The log is just a repeating of this:
Transcript started, output file is .\Logs\2018-01-02_00-16-40.txt
PS>TerminatingError(ForEach-Object): "You cannot call a method on a null-valued expression."
ForEach-Object : You cannot call a method on a null-valued expression.
At C:\MultiPoolMiner-master\Include.psm1:174 char:61
+ ...              ($_ | Get-Content | ConvertFrom-Json) | ForEach-Object {
+                                                          

Then it seems to work but then as it start it crops up:
WARNING: Stat file (Profit) is corrupt and will be reset.

THEN it starts working.

**Comment by UselessGuru** [comment]
> THEN it starts working
Does the error come back when you restart MPM?

If not then please close this issue. Thank you.

**Comment by gak45** [comment]
Every time I try and mod the fault tolerance it happens. If I leave it alone it works. Thus the question on if something was changed and the FAQ needs to be updated or not. ;)

**Comment by fonyo** [comment]
Nothing was changed regarding how fault tolerance works. We cannot currently provide support or troubleshoot alternated code.
