### ISSUE TITLE
switching prevention

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#877]
Correct me as maybe I'm wrong, but switching prevention means it should not switch for the specified time right?  I'm using 3 for the time now which I'm assuming means 3 minutes yet I've seen many times that it will switch after 1 minute.  Many of those times are right when it starts up it will do an algo for a minute and then switch, but just now I watched it do tribus and switch after a minute just in the middle.

**Comment by aaronsace** [comment]
No, it's an intensity from 0 to infinity.

**Comment by robl45** [comment]
what does that mean exactly?  What does switching prevention 3 mean versus 10 ?

**Comment by aaronsace** [comment]
It's not a finite scale; SwitchingPrevention has been set to 1 long before this option was made available. 

Higher the value means it is less likely to switch until the negative value that's based on the accuracy decays.

**Comment by gak45** [comment]
Roughly speaking what does this translate into minutes. For example X17 is say 90 accurate right now and is at the top of the list (and is being mined). The next is Blake2S at say 83 percent. Say blake2s goes to the top on next refresh... but its accuracy is down to 80 percent. With it set to '2' how long would Blake2s have to be 'more profitable' before it will switch to it from X17?

Basically any details you can give us would be greatly appreciated as it will make it easier to decide if 2 is good for say A Hash Pool that is PPLNS (like Multi Pool Hub)... or would 5 or even the original 10 be... more optimal.

**Comment by aaronsace** [comment]
If: 
SwitchingPrevention = 2
Accuracy = 90%

Then: 
NegativeValue = -20%

The negative value then decays by 10% every minute.

**Comment by gak45** [comment]
Just want to make sure I 'got it' as that is pretty damn ingenious
So if:
SwitchingPrevention = 4
Accuracy = 90%

Then:
NegativeValue = -40%

So at 4 its 24 min to reduce to 10% vs 6 min at 2?

**Comment by aaronsace** [comment]
13 minutes not 24: 
0.9 ^ 13 * 40 = 10

**Comment by gak45** [comment]
Awesome. Thanks for the clarification! Will bump up my donation a wee bit to 30 as y'all are great peeps and well worth investing in / donating to / etc etc. :)

**Comment by fonyo** [comment]
*Note to self, add to README.*

**Comment by gak45** [comment]
It would make for a very cool 'examples' chart on the MPM.io website.. as this is a major 'selling feature'. That way peeps could visually see the dif without grabbing a calculator ;)

**Comment by fonyo** [comment]
@aaronsace 

Can you please include here a simplified formula that I can use to create an understanding and use-cases for the users in the README? I am more interested in what happens if the accuracy is 80% or below. Cheers.

**Comment by aaronsace** [comment]
```
[Price] x (1 - ([Fluctuation] x [Switching Prevention] x 0.9^[Intervals Past]))
i.e. 123 x (1 - (0.2 x 2 x 0.9^5)
```

**Comment by fonyo** [comment]
Added to the README. 

@aaronsace I noticed the README files are not included with the releases. Is there any reason for that?

**Comment by platinum4** [comment]
This has a feature request here: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/911

**Comment by UselessGuru** [comment]
SwitchingPrevention has been changes to [Double] in the[ latest code.](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/873bfedc8c3532b358c40b97af8271427f6e9099)
