### ISSUE TITLE
Excavator don't start

### ISSUE THREAD

**Issue by wizmanza** [MultiPoolMiner/MultiPoolMiner#878]
0,00 PH/s 00 Days 00 Hours 00 Minutes 3 Times  Bin\Excavator\excavator.exe -p 23456 -c NiceH
Hi, all the bencmarking using excavator does not start thus failing 3 times. There is now window started when test happens but looks like is wants to start but nothing comes up. Very weird as previous version i had no issues with excavator

**Comment by platinum4** [comment]
Those aren't correct parameters passed to excavator

**Comment by wizmanza** [comment]
I did not copy all the parameters. What is called is whatis done by the multiminer..

**Comment by aaronsace** [comment]
@wizmanza I can't do anything if it won't start. Just check that you've downloaded it correctly from here: https://github.com/nicehash/excavator/releases

**Comment by wizmanza** [comment]
i have indeed. My previous version of multi worked all fine...it really weird. Maybe I'll redo multi install from scratch again. i see your startup file still calls powershell 5.0? 
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc.2/PowerShell-6.0.0-rc.2-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

**Comment by wizmanza** [comment]
ok i have re-downloaded all and benchmarking is begining. will keep you posted

**Comment by wizmanza** [comment]
Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0,00 PH/s 00 Days 00 Hours 00 Minutes 3 Times  Bin\Excavator\excavator.exe -p 23456 -c MiningPoolHubCoins_Equihash_wizmanza.digger_3_Nvidia.json -na
Just does not want to start !

**Comment by aaronsace** [comment]
If the settings are wrong then I can change them but I can't make it start if you can't start it. There are plenty of other miners included that should work on your system.

**Comment by wizmanza** [comment]
reverted back to previous version. All working fine there...very weird indeed

**Comment by wizmanza** [comment]
previous version of multiminer that is

**Comment by aaronsace** [comment]
Post the Excavator command line.

**Comment by wizmanza** [comment]
0,00 PH/s 00 Days 00 Hours 00 Minutes 3 Times Bin\Excavator\excavator.exe -p 23456 -c MiningPoolHubCoins_Equihash_wizmanza.digger_3_Nvidia.json -na

**Comment by wizmanza** [comment]
Busy benchmarking still...

   Type: NVIDIA

Miner            Algorithm        Speed      BTC/Day Accuracy BTC/GH/Day Pool
-----            ---------        -----      ------- -------- ---------- ----
CcminerTpruvot   Lyra2z       3,12 MH/s      0,00060     100%    0,19124 MiningPoolHub-Zcoin
Dstm             Equihash   761,00  H/s      0,00052      96%  683,88802 MiningPoolHubCoins-Zclassic
Ewbf             Equihash   745,00  H/s      0,00051      96%  683,88802 MiningPoolHubCoins-Zclassic
CcminerKlaust    NeoScrypt    1,55 MH/s      0,00045      97%    0,29444 NiceHash
CcminerTpruvot   NeoScrypt    1,03 MH/s      0,00030      97%    0,29444 NiceHash
CcminerKlaust    Groestl     68,00 MH/s      0,00014      76%    0,00200 MiningPoolHubCoins-Groestlcoin
ExcavatorNvidia2 Lyra2RE2  Benchmarking Benchmarking     100%    0,00641 MiningPoolHubCoins-Vertcoin
ExcavatorNvidia2 Lbry      Benchmarking Benchmarking      97%    0,00086 NiceHash
ExcavatorNvidia2 Equihash  Benchmarking Benchmarking      96%  683,88802 MiningPoolHubCoins-Zclassic
ExcavatorNvidia2 NeoScrypt Benchmarking Benchmarking      97%    0,29444 NiceHash
ExcavatorNvidia3 NeoScrypt Benchmarking Benchmarking      97%    0,29444 NiceHash
ExcavatorNvidia3 Lyra2RE2  Benchmarking Benchmarking     100%    0,00641 MiningPoolHubCoins-Vertcoin
ExcavatorNvidia3 Lbry      Benchmarking Benchmarking      97%    0,00086 NiceHash
NsgminerNvidia   NeoScrypt Benchmarking Benchmarking      97%    0,29444 NiceHash
CcminerTpruvot   Lbry      Benchmarking Benchmarking      97%    0,00086 NiceHash
CcminerTpruvot   Groestl   Benchmarking Benchmarking      76%    0,00200 MiningPoolHubCoins-Groestlcoin
CcminerTpruvot   Lyra2RE2  Benchmarking Benchmarking     100%    0,00641 MiningPoolHubCoins-Vertcoin
CcminerNanashi   NeoScrypt Benchmarking Benchmarking      97%    0,29444 NiceHash
CcminerLyra2z    Lyra2z    Benchmarking Benchmarking     100%    0,19124 MiningPoolHub-Zcoin
CcminerNanashi   Lyra2z    Benchmarking Benchmarking     100%    0,19124 MiningPoolHub-Zcoin

**Comment by aaronsace** [comment]
I meant post the working command line, not the failed one.

**Comment by wizmanza** [comment]
Bin\Excavator\excavator.exe -p 23456 -c NiceHash_Lyra2RE2_2_Nvidia.json -na - like this?

**Comment by aaronsace** [comment]
Run ExcavatorNvidia2.ps1 with algorithm Lyra2RE2.

**Comment by wizmanza** [comment]
ok you mean run it manualy from command line? -

**Comment by aaronsace** [comment]
No, with the latest MultiPoolMiner release.

**Comment by wizmanza** [comment]
ok please help how i tell multipoolminer to run just that 1?

**Comment by wizmanza** [comment]
thanks for help by the way, appreciate

**Comment by aaronsace** [comment]
`-minername ExcavatorNvidia2 -algorithm Lyra2RE2 `

**Comment by wizmanza** [comment]
sorry aaronsace....don't understand...where do i put that in?

**Comment by aaronsace** [comment]
Just edit the start.bat file.

**Comment by wizmanza** [comment]
OMG...im struggling....do i just add that -minername command at the back of the current command line? or do i need to replace some stuff on that line?

**Comment by wizmanza** [comment]
set "command=& .\multipoolminer.ps1 -wallet 1VvrFJT2BFkgxGAuomU8b78RFs36H1JxJ -username wizmanza -workername digger -region europe -currency btc,usd,eur,zar -type nvidia -poolname miningpoolhub,miningpoolhubcoins,nicehash -algorithm equihash,groestl,lyra2re2,lyra2z,neoscrypt -donate 24 -watchdog -switchingprevention 2"
where do i add the -miner part?

**Comment by wizmanza** [comment]
ok nothing happens...the seperate window that normally starts does not come up...the one when a miner gets started...all i get is 

   Type: NVIDIA

Miner            Algorithm        Speed      BTC/Day Accuracy BTC/GH/Day Pool
-----            ---------        -----      ------- -------- ---------- ----
ExcavatorNvidia2 Lyra2RE2  Benchmarking Benchmarking      99%    0,00646 MiningPoolHubCoins-Vertcoin




   Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0,00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 23456 -c MiningPoolHubCoins_Lyra2RE2_wizmanza.digger_2_Nvidia.json -na

**Comment by aaronsace** [comment]
Upload both these files: 
MiningPoolHubCoins_Lyra2RE2_wizmanza.digger_2_Nvidia.json
NiceHash_Lyra2RE2_2_Nvidia.json

**Comment by wizmanza** [comment]
don't find the NiceHash_Lyra2RE2_2_Nvidia.json - not in exavator directory?

[MiningPoolHubCoins_Lyra2RE2_wizmanza.digger_2_Nvidia.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595017/MiningPoolHubCoins_Lyra2RE2_wizmanza.digger_2_Nvidia.zip)

**Comment by aaronsace** [comment]
If this was the working command then that file will exist: 
`Bin\Excavator\excavator.exe -p 23456 -c NiceHash_Lyra2RE2_2_Nvidia.json -na`

**Comment by wizmanza** [comment]
just had look at log files....think that one came from previos version. If i loo at log file i see
   Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0,00 PH/s 00 Days 00 Hours 00 Minutes 3 Times  Bin\Excavator\excavator.exe -p 23456 -c MiningPoolHubCoins_Equihash_wizmanza.digger_3_Nvidia.json -na
[MiningPoolHubCoins_Equihash_wizmanza.digger_3_Nvidia.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595024/MiningPoolHubCoins_Equihash_wizmanza.digger_3_Nvidia.zip)

**Comment by wizmanza** [comment]
i wonder if not some shell issue? looks like from console that it flashes very quickly as if it want to start the miner and then it's gone...in milliseconds .... and then show as failed on console...

then again, on previous version the excavator starts no problem.....if there a way perhaps to clean install powershell?

**Comment by aaronsace** [comment]
Have you actually finished the benchmark?

**Comment by wizmanza** [comment]
must i just leave it and let it fail 3 times and move onto next?

**Comment by igneb** [comment]
Hi, I have problem with new version of multipoolminer as well... I'm using AMD. It loads normally, is digging for some time and then... This is what I get:


=========================== www.nicehash.com =========================
           Excavator v1.3.8a_nvidia GPU Miner for NiceHash.
           Copyright (C) 2017 NiceHash. All rights reserved.
                              Developed by
               djeZo, zawawa, dropky, voidstar, and agiz
                   with help and contributions from
           pallas, Vorksholk, bitbandi, ocminer, and Genoil.
=========================== www.nicehash.com =========================

Build time: 2017-11-24 13:38:37
Build number: 3734
Provided startup commandline:
        "C:\Users\user\Desktop\MultiPoolMinerV2.7.1.1\Bin\Excavator\excavator.exe" -p 3456 -c NiceHash_Decred_1MyHE1Y3twYHn9QFecDEbvseP7vnFoQszk.PC3_1.json

[17:36:18][0x00001f4c][info] Log started
[17:36:20][0x00001f4c][error] core | No compatible devices found!

----------

Excavator and jason file is there.
