### ISSUE TITLE
Hashhate but no balance

### ISSUE THREAD

**Issue by andregm3** [MultiPoolMiner/MultiPoolMiner#879]
![1cfd31a2-b5bb-41f9-9fd8-6faf8dc8a2ad](https://user-images.githubusercontent.com/4154732/34457905-d3d83c30-eda6-11e7-8dbd-cc31c7a83acc.jpg)

GPUs are still mining but the balance is still zero after hours of working

**Comment by aaronsace** [comment]
@andregm3 Nothing to do with MultiPoolMiner but you can see that it hasn't found a block yet and is at 326% over the estimated time.
