### ISSUE TITLE
1070 gpu error

### ISSUE THREAD

**Issue by danangfebrian** [MultiPoolMiner/MultiPoolMiner#880]
![image](https://user-images.githubusercontent.com/30223151/34458445-d0ee6bf2-ee05-11e7-82e3-a77d68d41c89.png)

several minutes running then get this error, help pls.

**Comment by aaronsace** [comment]
Is it causing any problems?

**Comment by danangfebrian** [comment]
after get this error, the fan speed turn on 100% then system crash can't mining.
its normaly?

**Comment by aaronsace** [comment]
No idea, either fix the system issue or remove that miner from the folder called 'miners'.

**Comment by platinum4** [comment]
I'd remove all overclocking first.

**Comment by danangfebrian** [comment]
but im not yet oc. 

anyone using zotac 1070 ext amp here?

**Comment by paulpoco** [comment]
I am using 2 x Asus Dual 1070 OC 8Gb cards fine.

Uninstall your Nvidia drivers and reinstall?

Did you install the Cuda drivers?

**Comment by kevharper** [comment]
I had a similar issue.  Was resolved by updating to the latest Nvidia Driver as a clean install.  I also had 2 of my 5 1070's running on a PSU that was suspect.  

 I would start with uninstalling/reinstalling drivers and then try a different PSU or put one or both of the cards on a dedicated PSU if the issues is still not resolved.  Check youtube for power supply paperclip trick mod.  

https://www.youtube.com/results?search_query=power+supply+paperclip+trick

**Comment by fonyo** [comment]
Closing this as resolved. Please post a new issue if you are having multipoolminer related issues.
