### ISSUE TITLE
Pool going crazy after donation period. 

### ISSUE THREAD

**Issue by komer83** [MultiPoolMiner/MultiPoolMiner#882]
After donation period, the miners all go crazy and switch to other pools when -poolname is set to zpool 

[2017-12-31_09-46-08.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595076/2017-12-31_09-46-08.txt)

**Comment by UselessGuru** [comment]
All I can see are these three miners crashing:

```
   Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-corei7.exe -a sib -o stratum+tcp://x11gost.eu.nicehash.com:3359 -u
                                               1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb.multipoolminer -p x -t 5
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-corei7.exe -a groestl -o stratum+tcp://europe.hub.miningpoolhub.com:20486 -u
                                               Lumikor.Lumikor -p x -t 5
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\Skunk-NVIDIA\ccminer.exe -o stratum+tcp://skunk.eu.nicehash.com:3362 -u
                                               1GhcVobvFPB9odReep3Nn7UHgbB8Z7Nxnt.Lumikor -p x
```
Does your problem re-occur when you restart MPM?

BTW: Unless you have free (or extremely cheap) power CPU mining is unprofitable. Disable CPU mining ;-)

**Comment by komer83** [comment]
Yes, it won't switch normally after donation period. here's an example from the same log, there's no reason in the world to mine in miningpoolhub unless it's donation.

Also, about CPU, I know, it's still a testing phase to see where MPM crush, so I stress the system.

      Speed Active                      Launched Command
      ----- ------                      -------- -------
  0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 23456 -c
                                                 NiceHash_Lyra2RE2_1GhcVobvFPB9odReep3Nn7UHgbB8Z7Nxnt.Lumikor_3_Nvidia.json -na
822.26 KH/s 00 Days 00 Hours 05 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a groestl -o stratum+tcp://europe.hub.miningpoolhub.com:20486 -u
                                                 Lumikor.Lumikor -p x -t 5

**Comment by thericeking** [comment]
Woke up this morning to see my rig mining Skein for 14 hours straight :( I'm using master

**Comment by aaronsace** [comment]
This thread is nonsense; start a fresh issue and upload log files.

**Comment by UselessGuru** [comment]
> there's no reason in the world to mine in miningpoolhub unless it's donation.

The code for donations just switches BTC addresses and username. It does not affect the configured pools or algorithms.

**Comment by komer83** [comment]
too bad you closed it so fast. Still not switching back to zpool after donation mining, will just remove donation until you fix it.

**Comment by aaronsace** [comment]
The log doesn't match what you're describing; it's just failed miners.

**Comment by harssh** [comment]
@komer83 Check if you have any algorithm which is not supported via your pool.
It happened with me yesterday on master by mistake I had Blake2s added while using MPH and it ran on donations address for more than 7 hrs in single day. Than I removed that algo and it has not behaved that way.
