### ISSUE TITLE
Configure the wallet addresses for each currency

### ISSUE THREAD

**Issue by marcofranssen** [MultiPoolMiner/MultiPoolMiner#883]
It is unclear from the docs how to configure each miner and wallet addresses from the README docs. Is there someone who can clarify where to configure what regarding the wallet addresses where the payouts of coins should be sent. Currently I see only one wallet address to be set, but how does this work with multi curreny mining?

**Comment by UselessGuru** [comment]
> [...]but how does this work with multi curreny mining?

multi currency mining is not supported out-of the box. 

Can you describe your use case a little bit more in detail - thanks!

**Comment by fonyo** [comment]
We can only support what pools make available to us. Paying out in anything else than BTC is only supported by MiningPoolHub which has a registration scheme hence the username option in the start.bat file. You can configure your various payout options on their website.
