### ISSUE TITLE
Support for 13GPU

### ISSUE THREAD

**Issue by wizmanza** [MultiPoolMiner/MultiPoolMiner#884]
Hi, 

I'm running 13 Nvidia and mainly do equihash,groestl,lyra2re2,lyra2z,neoscrypt algo's.
Will multiminer work with all 13 GPU?

Thanks for the help

**Comment by aaronsace** [comment]
Yes.

**Comment by wizmanza** [comment]
Thanks man, really like the miner. What is default fee built-in and how do i increase if i decisde to do so?

**Comment by aaronsace** [comment]
Default is 10 minutes per day. 

'Donate' is the option to increase. 🙂

**Comment by wizmanza** [comment]
see value is set to 24? is that = 10 minutes?

**Comment by wizmanza** [comment]
busy benchmarking on 13 GPU

**Comment by aaronsace** [comment]
That's 24 minutes; start.bat is an example configuration; you have to set your own wallet etc. 

The default in the actual code is 10 minutes.

**Comment by wizmanza** [comment]
ok thanks

**Comment by wizmanza** [comment]
so seems excavator only uses 6 GPU although  picking up all 13

**Comment by wizmanza** [comment]
![excavator](https://user-images.githubusercontent.com/34969068/34461429-6afe968c-ee32-11e7-89ca-6cfb3be423f5.jpg)
![inspector](https://user-images.githubusercontent.com/34969068/34461431-70f6548a-ee32-11e7-8171-607e62966f29.jpg)

miner show picking up all 13...yet nvidia shows only 6 GPU getting work
any suggestions?

**Comment by wizmanza** [comment]
![all 13 working with ccminer](https://user-images.githubusercontent.com/34969068/34461443-e9239a44-ee32-11e7-8f9f-52c8b28d7d9e.jpg)
 here is what inspector looks like with all 13 working under ccminer

**Comment by wizmanza** [comment]
bench done...excavator is running but only with 6 GPU. Wonder if i can edit the json files and add more workers? seems to only specofy 6...or am i reading it wrong?

**Comment by wizmanza** [comment]
ok seems the json files in Excavator directory is created dynamically. I made a change to test but when i restart multiminer if resets back to the 6 devices. What file is used as base to create these json files?

**Comment by UselessGuru** [comment]
> What file is used as base to create these json files?

It is one of the excavator files in the miner folder:
ExcavatorNvidia2.ps1
ExcavatorNvidia3.ps1

They are only configured for 6 cards (0 - 5). So you'll have to edit them to include more cards. Look to change it like this

```
...
            if ((Test-Path (Split-Path $Path)) -and $Pools.$(Get-Algorithm $_).Host) {
                [PSCustomObject]@{time = 0; commands = @([PSCustomObject]@{id = 1; method = "algorithm.add"; params = @("$_", "$([Net.DNS]::Resolve($Pools.$(Get-Algorithm $_).Host).AddressList.IPAddressToString | Select-Object -First 1):$($Pools.$(Get-Algorithm $_).Port)", "$($Pools.$(Get-Algorithm $_).User):$($Pools.$(Get-Algorithm $_).Pass)")})},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "0") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "1") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "2") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "3") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "4") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "5") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "6") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "7") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "8") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "9") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "10") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "11") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "12") + $Commands.$_}) * $Threads},
                [PSCustomObject]@{time = 10; loop = 10; commands = @([PSCustomObject]@{id = 1; method = "algorithm.print.speeds"; params = @("0")})} | ConvertTo-Json -Depth 10 | Set-Content "$(Split-Path $Path)\$($Pools.$(Get-Algorithm $_).Name)_$(Get-Algorithm $_)_$($Pools.$(Get-Algorithm $_).User)_$($Threads)_Nvidia.json" -Force -ErrorAction Stop
            }
...
```

**Comment by wizmanza** [comment]
thanks, i just traced is to that point. :-)
will make changes and test to see and let you know

**Comment by wizmanza** [comment]
think we on right track....json file is now create with all the workers...
BUT...excavator starts up but crashes (just closes) very quickly....there must be something else....
I'll add GPU at a time and see where is fails....tried to add to 9 thinking it might be the 10,11,12 that might have offset issue...I'll keep digging

**Comment by wizmanza** [comment]
ok 7 gpu running ok...onto next

**Comment by wizmanza** [comment]
0-7 ok...so 8 GPU now

**Comment by UselessGuru** [comment]
I assume excavator does not like 2 digit device id numbers. Other miners are/were booged by the same problem.
In these cases there is not much that can be done.

**Comment by wizmanza** [comment]
not that, seem workers now appear twice in the jason file....so upto 8 cpu working for some reason...will let you know

**Comment by UselessGuru** [comment]
Could you please post your modified miner files and the resulting json file?

**Comment by UselessGuru** [comment]
BTW: Is this related to https://github.com/MultiPoolMiner/MultiPoolMiner/issues/878?

Then could we close one case? TIA

**Comment by wizmanza** [comment]
we can close #878 please...not related

**Comment by UselessGuru** [comment]
#878 closed.

**Comment by UselessGuru** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/1c2ea6321bae137d911452c22895f9bd1cf45967

**Comment by Braintelligence** [comment]
@wizmanza @UselessGuru 

Those are the miners that I had problems with on 12+ 1070 Ti rigs, even without OC (I don't know how many GPUs would work, tho. I only have 6 and 12+ rigs):

- XMR-STAK (works if you adjust bfactor from 6 to 8 for all GPUs, I still don't get why it is initialized at bfactor 6 for 1070 Tis, it didn't work on any manufacturer yet and I have 4 different ones)
- nvidiaSP
- deactivated anything but DTSM for Equihash due to performance
- KlausT and TPruvot needed deactivation of some algos
- hsrminer needs a crapton of swap file size on such rigs, don't use anything smaller than a 240GB SSD and provide at least VRAM = swap file size
- nvidia Skunk didn't work for me on 1070 Ti

Maybe this can help you guys.
