### ISSUE TITLE
Red error messages while benchmarking

### ISSUE THREAD

**Issue by rtom098** [MultiPoolMiner/MultiPoolMiner#885]
Hey,
I'm newbie, just installed the miner today, followed a tutorial video on how to setup with mininpoolhub.

**my settings are (XX > inserted my date):**
set "command=& .\multipoolminer.ps1 -username XX-workername XX-region europe -currency usd,eur -type amd -poolname miningpoolhub -algorithm cryptonight,ethash,ethash2gb,equihash,groestl,neoscrypt,siaclaymore -donate 24 -watchdog -switchingprevention

**I get this error message while doing the benchmark. It shows up 59x in a row:**

`Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.

At D:\Mining\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:143 char:77
... rithm.Count -eq 0 -or (Compare-Object $Algorithm $_.Algorithm -Includ ...
                                                      ~~~~~~~~~~~~
CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand`

**Comment by aaronsace** [comment]
Try the original start.bat

**Comment by rtom098** [comment]
Tried original start.bat - but get the same error message on start and every few minutes while mining.

**Comment by aaronsace** [comment]
Upload the full log.

**Comment by rtom098** [comment]
here is the last log, always same message no matter what bat file (original or modified).

[2017-12-31_13-24-49.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595167/2017-12-31_13-24-49.txt)

**Comment by UselessGuru** [comment]
The error originates frum dodgy data when loading the pool information.
From the log we cannot see which pool is causing it. So please do the following:
- re-download all pool files
if the problem persists:
- remove the pool files one by one until the problem is gone. 
Then we can further analyze the cause.

**Comment by rtom098** [comment]
Thanks for your help!

I deleted all pool files - except the two for mininpoolhub. Actual start error message seems gone. Doing new benchmarks now and hope it doesn't appear again.
