### ISSUE TITLE
Donate time set properly?

### ISSUE THREAD

**Issue by SennaWM** [MultiPoolMiner/MultiPoolMiner#886]
I have my - donate 10 set in the .bat file. Watching the running miner for aaronsace exceeds this time twice since I started using program yesterday night. As I type, mining is running for aaronsace ( thank you for this program btw Aaron) 24 minutes. Approx. 8 hrs. ago it went for 18 minutes. Is this working as intended?

**Comment by aaronsace** [comment]
Upload the full log please.

**Comment by SennaWM** [comment]
[2017-12-31_08-08-50.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595255/2017-12-31_08-08-50.txt)

**Comment by SennaWM** [comment]
[2017-12-30_23-27-08.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595261/2017-12-30_23-27-08.txt)

**Comment by jayntguru** [comment]
I have seen the same thing. Looks like maybe interval & switchingprevention are factors here.

**Comment by aaronsace** [comment]
It's _exactly_ 24 minutes because you have put a comma at the end of the algorithms.

**Comment by SennaWM** [comment]
Many thanks for your quick response. I'll leave it at 24 for another 24 hr cycle for taking the time to help me.

**Comment by aaronsace** [comment]
No problem, you got me worried for a sec.
