### ISSUE TITLE
"WARNING: Pool API (MiningPoolHub) failed" and update prompt

### ISSUE THREAD

**Issue by dposse** [MultiPoolMiner/MultiPoolMiner#887]
Constantly get the above warning, along with the other pools. The other pools don't matter as they are disabled in the start.bat, but I am using mining pool hub. Not sure how to reproduce this or diagnose the issue, but the warning does show within an hour of starting to mine.

Every now and then it shows the prompt to update to the newest version. I can clean installed MPM twice just in case.

Leaving MPM on overnight still mines and sends to miningpoolhub at least some of the time. Not experienced enough to know whether it's getting the whole balance it should or not. What logs would be useful to diagnose?

**Comment by UselessGuru** [comment]
> Pool API (MiningPoolHub) failed

There is nothing MPM can do about this. The pool does not answer the API request. If this happens MPM will just use the pricing information from the last successful read. Just ignore the message.
 
> to know whether it's getting the whole balance

From my experience you will never see the same profit at the pool than what MPM reports. However this is not MPMs fault. MPM just multiplies the hash rate reported by the miner with the pricing read from the pool. Don't ask me where the difference goes ;-)
a) the hash rate reported by the miner is too high
b) the pool does not account all sent shares
I am not blaming either one. Unfortunately this happens with many miner/pool combinations.

> What logs would be useful to diagnose?

Look for the log file in the log directory. If there are no errors then it is mining non-stop.

**Comment by dposse** [comment]
ok thank you! Is the "No pools available" message ignorable too then?

**Comment by UselessGuru** [comment]
> Is the "No pools available" message ignorable too then?

Not on first start... MPM needs some information to start with.
On subsequent loops yes.
As I said, it is the pools not answering the API call. MPM will tell you this (yellow) and use what ever information it retrieved in the past.

The high number of requests directed at the pools API is just overloading their API. Its the pool owners that need to increase their availabiliy.

**Comment by dposse** [comment]
I see, thank you very much.
