### ISSUE TITLE
Excavator uses only 6 GPU

### ISSUE THREAD

**Issue by mmmikhailov** [MultiPoolMiner/MultiPoolMiner#888]
Hi! Is it my problem or is it Excavator problem? The matter is that it uses only 6 of my 8 1070 cards. How can i fix this?
Thanx!

UPD: Found https://github.com/MultiPoolMiner/MultiPoolMiner/issues/884 Will report on result!

UPD 2: Did not work for me. Still in a need of a solution!

**Comment by UselessGuru** [comment]
This will help:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/1c2ea6321bae137d911452c22895f9bd1cf45967
Happy New Year and all the Best for 2018!

**Comment by mmmikhailov** [comment]
Thanx! Best wishes!
