### ISSUE TITLE
Miner PalginNvidia (hsrminer) issue

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#889]
I'm having the following issue with the Palgin Nvidia (hsrminer) that i dont know if someone got it:

PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\MPOOLMINER\Wrapper\23333.txt' because it does not exist."
WARNING: Failed to connect to miner (PalginNvidia).

Im running MPM on a GTX1050 Ti. The miner starts ok on the wrapper and mines normally. It seems to be a connection issue with MPM...

**Comment by UselessGuru** [comment]
The problem is the miner. Because it does not have an API we must resort to the wrapper, The wrapper basically reads the screen output of the miner and scans it for keywords that indicate hasrates.
Palgin sometimes does not print the hash rate for minutes which will cause all sorts of problems (e.g. the wrapper not creating the missing 23333.txt).

We will have to wait for palgin to release a version with API (he is working on it). For now just ignore the error.

**Comment by titvs** [comment]
Thanks. Let’s wait for a new release then.
I must remember other users that Palgin Nvidia miner does NOT support GTX 9xx GPUs. The ability to select which gpus use which miners will be a great addition to MPM. ;)

**Comment by UselessGuru** [comment]
> gpus use which miners will be a great addition to MPM. ;)

Not something MPM can do right now, but surely a good enhancement. 👍 
For now it is at your hands. Edit the miner files... Per miner (syntaxes vary) find the commands needed to select individual devices. Then add this command to the 'arguments' line.

**Comment by UselessGuru** [comment]
PalginNvidia needs proper API to fix this issue.

**Comment by Braintelligence** [comment]
@UselessGuru Did you hear anything new about a possible release date for hsrminer with API?

**Comment by trinitron79** [comment]
Can we increase the watchdog timer to help work around this problem?

**Comment by Braintelligence** [comment]
@trinitron79 Yeah, that would be a neat workaround, though a too high timer would defeat the purpose of the watchdog.

**Comment by trinitron79** [comment]
Agree but maybe bumping it up to say 75-90 sec might be good enough.

**Comment by aaronsace** [comment]
'Interval' is the used for everything including the watchdog.

**Comment by trinitron79** [comment]
Oh!  Awesome didn't know!  Thanks for the insight!
