### ISSUE TITLE
Red erro rmessages. cant seem to find a fix

### ISSUE THREAD

**Issue by mavlevypaul** [MultiPoolMiner/MultiPoolMiner#890]
this was working completely fine until this morning after a reboot. I have tried deleting and redownloading all the files for MPM

here is the log please help:

red code appears over and over again:
[2017-12-31_14-43-26.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595510/2017-12-31_14-43-26.txt)

Invoke-Expression : Exception calling "GetPlatformIDs" with "0" argument(s): "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"
At C:\Users\goliathmk2\Desktop\MPM\MultiPoolMiner-master\Include.psm1:179 char:44
+ ...                        $Item.$_ = Invoke-Expression "`"$($Item.$_)`""
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
+ FullyQualifiedErrorId : BadImageFormatException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\goliathmk2\Desktop\MPM\MultiPoolMiner-master\MultiPoolMiner.ps1:179 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

**Comment by UselessGuru** [comment]
The error is probably caused by a corrupt file in one of these three directories:
\stats
\pools
\miners

What to do try:
- Remove the pools and miners directory, Then re-download the miners and pools. Problem gone?
- Rename the stats folder

**Comment by mavlevypaul** [comment]
ok I have tried redownloading pools and miner. no fix.

what shall I rename the stats folder?

**Comment by mavlevypaul** [comment]
What do you mean rename the stats folder

**Comment by newcombio** [comment]
Having the same error. 

Things I've tried: 

- Re-downloaded latest multipoolminer bin files for re-install as mentioned in another Issue.
- Removed some other stats pages as they were not loading successfully
- Full re-install with no configuration edits and it still fails with the error. 

Here is my log file: https://pastebin.com/dxHB7sdL
Here is log file of default config (no changes) :https://pastebin.com/2WZFmN05

**Comment by aaronsace** [comment]
Get the latest drivers from AMD/NVidia.

**Comment by aaronsace** [comment]
Also check .net is installed: 
https://www.microsoft.com/en-us/download/details.aspx?id=40773

**Comment by aaronsace** [comment]
If you have no GPUs then you may need this: 
https://software.intel.com/en-us/articles/opencl-drivers

**Comment by newcombio** [comment]
Thanks for the help! I just downloaded the latest Nvidia drivers (388.71) and verified that the latest .net package was installed and were good there. 

Still getting the error for this.

```
PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\HashyMcHashface\Documents\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:177 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...

+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\HashyMcHashface\Documents\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:177 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...

```

**Comment by aaronsace** [comment]
You got the full log? (BTW you can upload files to GitHub posts)

**Comment by newcombio** [comment]
[2017-12-31_20-51-55.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595586/2017-12-31_20-51-55.txt)

**Comment by mavlevypaul** [comment]
I'm still also getting the error.
[2017-12-31_18-15-52.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1595604/2017-12-31_18-15-52.txt)

I have tried everything I can think of...

**Comment by UselessGuru** [comment]
@newcombio

Your error is caused by one of your miner files (the log does not tell which one).
`At C:\Users\HashyMcHashface\Documents\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:177 char:71` (here MPM is retrieving all available miners)
Please remove (make a backup) all the miner files. The punt them back in the miners folder one by on and see which one is causing it. If found please upload it here.

**Comment by almothafar** [comment]
I tried many solutions and tried many times, almost reinstalled everything, nothing was helpful 😞 

```
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\MultiPoolMiner\Stats\MiningPoolHubCoins_Electroneum_Profit.txt' because it does not exist."
PS>TerminatingError(Invoke-Expression): "Exception calling "GetPlatformIDs" with "0" argument(s): "OpenCl error -1001: -1001.""
>> TerminatingError(Invoke-Expression): "Exception calling "GetPlatformIDs" with "0" argument(s): "OpenCl error -1001: -1001.""
>> TerminatingError(Invoke-Expression): "Exception calling "GetPlatformIDs" with "0" argument(s): "OpenCl error -1001: -1001.""
Invoke-Expression : Exception calling "GetPlatformIDs" with "0" argument(s): "OpenCl error -1001: -1001."
At C:\MultiPoolMiner\Include.psm1:179 char:44
+ ...                        $Item.$_ = Invoke-Expression "`"$($Item.$_)`""
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
+ FullyQualifiedErrorId : OpenClException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
Invoke-Expression : Exception calling "GetPlatformIDs" with "0" argument(s): "OpenCl error -1001: -1001."
At C:\MultiPoolMiner\Include.psm1:179 char:44
+ ...                        $Item.$_ = Invoke-Expression "`"$($Item.$_)`""
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
+ FullyQualifiedErrorId : OpenClException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\MultiPoolMiner\MultiPoolMiner.ps1:179 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\MultiPoolMiner\MultiPoolMiner.ps1:179 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

```

**Comment by newcombio** [comment]
@UselessGuru I've downloaded the files multiple times from latest, the error is because a variable is not being assigned properly and breaking the code. 

This script is broken 'MultiPoolMiner.ps1:177 char:71' and I've tried multiple computers. I don't believe this to be a file corruption issue but a scripting issue. 'NULL' is reported multiple times in the debug info.

**Comment by UselessGuru** [comment]
> I've downloaded the files multiple times

Please make sure that you remove ALL FILES and SUBFOLDERS in the folders
\Stats, \Miners, \Pools
before re-installing MPM.
One possible reason for these errors cound be *.bak files or other non-original MPM files in these folders.

**Comment by jake-g** [comment]
I dont think thiss issue is 'closed'  it keeps coming up and gets closed with nio solution. I have a similar issue here, WIndows 10, latest Nvidia drivers (390.77), CUDA 9.1, all the visual c drivers and stuff. I had to move OpenCL.dll from nvidia folder to System32 to get rid of my original missing openccl error.

I've tried multiple versions of this project with a fresh install each time and end up with the same issue (see attached log)

thanks

```
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\Mining\MultiPoolMinerV2.7.2\MultiPoolMiner.ps1:284 char:85
+ ... fig.Type.Count -eq 0 -or (Compare-Object $Config.Type $_.Type -Includ ...
+                                                           ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

Exception calling "GetPlatformIDs" with "0" argument(s): "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"
At D:\Mining\MultiPoolMinerV2.7.2\Miners\Sgminer.ps1:45 char:258
+ ... -platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : BadImageFormatException
```

**Comment by jake-g** [comment]
to add to my above comment, i went in and tried slowly adding miners back to Miners/ and found that by excluding the following miners (see attached file) all my errors went away. 

[failed_miners.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1715290/failed_miners.txt)

**Comment by jake-g** [comment]
very helpful, thanks for getting back to me. Unfortunately, Intel is telling me i have to wait 2 business days to get the OpenCL SDK so yeah... 

For those who end up here... before installing OpenCL sdk this what i get following @UselessGuru steps, I'll report back after i get the intel sdk:

```
Exception calling "GetPlatformIDs" with "0" argument(s): "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"
At line:1 char:1
+ [OpenCl.Platform]::GetPlatformIDs()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : BadImageFormatException
```

**Comment by jake-g** [comment]
Yep! all good now, thanks. here is the output after installing the intel opencv sdk package

```
Profile    : FULL_PROFILE
Version    : OpenCL 1.2 CUDA 9.1.84
Name       : NVIDIA CUDA
Vendor     : NVIDIA Corporation
Extensions : {cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics,
             cl_khr_local_int32_base_atomics, cl_khr_local_int32_extended_atomics...}

Profile    : FULL_PROFILE
Version    : OpenCL 2.0
Name       : Intel(R) OpenCL
Vendor     : Intel(R) Corporation
Extensions : {cl_khr_icd, cl_khr_global_int32_base_atomics,
             cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics...}

Profile    : FULL_PROFILE
Version    : OpenCL 2.1
Name       : Experimental OpenCL 2.1 CPU Only Platform
Vendor     : Intel(R) Corporation
Extensions : {cl_khr_icd, cl_khr_global_int32_base_atomics,
             cl_khr_global_int32_extended_atomics, cl_khr_local_int32_base_atomics...}


```
