### ISSUE TITLE
Set to only use zpool using the ExcludePoolName and it is still using nicehash?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#891]
-poolname zpool -ExcludePoolName nicehash,miningpoolhub,miningpoolhubcoins,hashrefinery,ahashpool

https://pastebin.com/9jAi2ECq is the log.

I am using code current to about Dec 27 9pm.  I don't want it to ever use Nicehash.  I currently wanted to only mine zpool today to hopefully get a withdrawal still in 2017

   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CryptoNight-FireIce\xmr-stak.exe -c NiceHash_CryptoNight_1LA867GKG2VGxZS2iAtGab1WPFDJ3XnPtU.multipoolminer_Cpu.txt --noUAC --noAMD --noNVIDIA
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a veltor -o stratum+tcp://veltor.mine.zpool.ca:5034 -u 1LA867GKG2VGxZS2iAtGab1WPFDJ3XnPtU -p multipoolminer,c=BTC
                                               --submit-stale

**Comment by grantemsley** [comment]
zpool doesn't support cryptonight, so if that's profitable it will use whatever pool supports it.

If you absolutely never want to mine at nicehash, delete it from the pools directory.  If you only want to use nicehash if everything else is down, only mine algorithms that are supported by your desired pools.

**Comment by paulpoco** [comment]
I wish there was separate Nvidia or CPU pool setup.

**Comment by grantemsley** [comment]
How would that make any sense to do?  The only reason for NOT mining at a particular pool is if you don't like that pool, or don't want to spread your profits out.  There's no reason to choose pools based on what devices you have.

**Comment by paulpoco** [comment]
Type: CPU

Miner                   Algorithm         Speed BTC/Day Accuracy BTC/GH/Day Pool
-----                   ---------         ----- ------- -------- ---------- ----
FireiceCpu              CryptoNight 357.68  H/s 0.00010      97%  281.02518 NiceHash
CpuminerJayddee4way     Lyra2z      447.43 KH/s 0.00007      97%    0.15398 Zpool
CpuminerJayddeeAessse42 Lyra2z      298.66 KH/s 0.00005      97%    0.15398 Zpool
CpuminerJayddeeSse2     Lyra2z      290.31 KH/s 0.00004      97%    0.15398 Zpool
CpuminerTpruvotCorei7   Veltor      883.88 KH/s 0.00001      99%    0.01292 Zpool
CpuminerTpruvotAvx2     X17         199.54 KH/s 0.00001      49%    0.05895 Zpool

I put exclude nicehash and there was an option for CPU to do  Lyra2z at zpool

**Comment by paulpoco** [comment]
What good is mining at Nicehash if you will never take it out?

**Comment by grantemsley** [comment]
So turn off CryptoNight, because zpool doesn't support it.  Has nothing to do with which type of device it is.  If your nvidia card was good at mining cryptonight, it'd choose nicehash too.

**Comment by paulpoco** [comment]
Ok so take out algo CryptoNight for now and it should use CPU on zpool with Lyra2z.

**Comment by grantemsley** [comment]
If you want to mine primarily at zpool, choose only the algorithms zpool supports.  They are listed here:  https://multipoolminer.io/algorithms

If you really absolutely never want to mine at nicehash, and would rather turn off your mining rig than mine there - then delete NiceHash.ps1 from the pools directory.  I did.

**Comment by paulpoco** [comment]
"then delete NiceHash.ps1 from the pools directory. I did." cool will do that, thanks

**Comment by aaronsace** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner#q4-i-only-want-to-mine-certain-algorithms-even-if-they-are-not-the-most-profitable-i-want-to-exclude-algorithms-how-do-i-do-that

**Comment by paulpoco** [comment]
For the Devs, is it bug if you put -ExcludePoolName nicehash and it still uses Nicehash?

Isn't the simplicity idea is to change something in start.bat than hunting down files to delete?

I did go and delete  NiceHash.ps1 from the pools directory for now.

**Comment by aaronsace** [comment]
@paulpoco No, you need to pick the correct algorithms. Zpool doesn't support every algorithm, no pool does. There is a Start-Zpool.bat example included.
