### ISSUE TITLE
ZPool Question

### ISSUE THREAD

**Issue by wizmanza** [MultiPoolMiner/MultiPoolMiner#892]
Hi, sorry to post this here. I read some stuff that ZPool takes like 20% hashrate. Is that still the case or is it better to exclude ZPool from MultipoolMiner?
Cheers,

**Comment by UselessGuru** [comment]
> is it better to exclude ZPool from MultipoolMiner?

Up to you :-)
The trouble is that with all pools (so my experience) you will never see the real profit as projected by MPM. if someone finds the holy grail he may post it here :-)

Please note that this is NOT MPM's fault as written elsewhere here.

**Comment by wizmanza** [comment]
Thanks, appreciate...Happy 2018 BTW :-)

**Comment by UselessGuru** [comment]
@wizmanza 

Happy 2018 BTW 👍 U2
