### ISSUE TITLE
Is there anyway  to make the profit figures more accurate?

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#894]
I've been using this for a number of weeks now and I"m finding that what MPM reports for expected profit versus reality at the pool is wildly different.  Is there anyway to make that more accurate?  My main concern is that some algorithms are getting much more weight for profitability than maybe they should be.  Example,  My 1060 will basically mine X17 for most of the day now and does maybe just about 3 dollars before power costs while MPM is calculating it should be doing 4-6 dollars.  Maybe there is something better it should be mining instead.  I admit I don't understand all the profit calculations as I haven't really had the time to delve into that throughly, I'm just thinking that steady profit each day is better than complete unknowns.

**Comment by komer83** [comment]
Do you take pool & miner fees? I'm not sure MPM takes it into account.

**Comment by robl45** [comment]
I take calculation at x point in time and then calculation 24 hours later, subtract difference and multiply by bitcoin price or rather average bitcoin price.    MPM saying I should make 4-6 dollars right now.  Likely that will end up as 3 dollars again or so.

**Comment by UselessGuru** [comment]
> Do you take pool & miner fees? I'm not sure MPM takes it into account.

Nope. The are not part of the calculation.
There is a big discrepancy between calculated and received profit for most miner/pool configurations. 
But this is NOT MPM's fault. If there was a known factor (and reliable) for each pool available then this could easily implemented into MPM. But who dares to give this number? I bet it's about 40%. Give or take a few %. Since all pools are affected about the same I just see the reported values as an overoptimistig guideline. MPM still finds the highes profit for you.

**Comment by robl45** [comment]
yes, the point is, it seems like some get overstated.  example as stated above, X17 will basically mine all day on the pools.  It was mining this morning for almost 4 of the 4 hours I watched and my 1060 was on track for 2.26 over 24 hours.  I removed that algorithm and now 7 hours after starting its up to 3.12.  So if an algorithm is getting overstated for profit, and it mines that one almost constantly, we lose profit.

**Comment by UselessGuru** [comment]
Maybe this helps a little bit:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/7afeb030ae8e27c122eca5b4c048a27d02cbd05d

**Comment by robl45** [comment]
what does case insensitive bitcoin address have to do with it.

**Comment by aaronsace** [comment]
Wrong commit but try the latest code branch it has a fix for Zpool. 

To answer the original question though, no, I can't make them more accurate; there is no concise measurement.
