### ISSUE TITLE
no compatible device found

### ISSUE THREAD

**Issue by cblim** [MultiPoolMiner/MultiPoolMiner#899]
Hi,

i do found this problem. i'm a first timer using your software and i'm on AMD GPU.
when this issue happen, the whole progress just halt there and doesn't move on.
anyway to disable it totally ?

![image](https://user-images.githubusercontent.com/35016922/34472638-4eb73126-efa1-11e7-9eae-8391049074d0.png)

**Comment by richardg867** [comment]
Download the old Excavator version 1.2.11 which still supports AMD cards.

**Comment by fonyo** [comment]
If you are using AMD, just delete the excavator files from the /Miners folder.
