### ISSUE TITLE
Powershell 6

### ISSUE THREAD

**Issue by xfactor8383** [MultiPoolMiner/MultiPoolMiner#900]
Quick question on the PS 6 requirement...

1) Does PS 6 have to be installed to a particular location?  I clicked the link provided and installed PS 6 into C/Programs.

2) PS 5.1 is still on my machine in a different location, do I have to uninstall PS 5.1 or do  just leave it be? Where in the code does MPM pull up PS 6? 

Thanks! Love MPM!

**Comment by borzaka** [comment]
Just install to the default location.

I think you don't need to uninstall PS 5.x. You only have to uninstall prev version, if you are updating to a new version from the same main version. For example there is a final version of the [PS 6.0](https://github.com/PowerShell/PowerShell/releases), so if you have any installed 6.0 RC version, you should uninstall that first.

**Comment by platinum4** [comment]
This is an informational question and likely has been [answered to satisfaction above](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/900#issuecomment-357203268)

Please close if this has been answered and is no longer an issue.
