### ISSUE TITLE
Excavator and Prospector Miner

### ISSUE THREAD

**Issue by thel3lue** [MultiPoolMiner/MultiPoolMiner#902]
[https://imgur.com/a/iot29](url)
anyway to disable this 2 miner?
use -type amd but still show this 2 miner 
try delete this 2 miner but when restart will download again

**Comment by cmbconcretefire** [comment]
yes. Go to your MultiPoolMinerV2.7.1.2 folder then open the folder "Miners" and delete all 4 of the Excavator files and then the prospector file. Restart miner. Problem solved.

**Comment by thel3lue** [comment]
Problem solved.
Thx for the help

**Comment by cmbconcretefire** [comment]
Just in case anyone is paying attention...... I helped. :) @UselessGuru @aaronsace @fonyo can't do everything around here. And as much as I am a pain in the ass .....I truly want to help lighten the load for those guys so they can concentrate on improving MPM.
