### ISSUE TITLE
Regarding issue #866, I can help with that. 

### ISSUE THREAD

**Issue by cmbconcretefire** [MultiPoolMiner/MultiPoolMiner#903]
The problem is, sometimes Nvidia GPU's are 'lost' or drop offline. MANY people immediately say "turn down your OC, update your drivers, etc....and even after doing all of that, the GPU will still get lost or drop out. I complained and complained about this to the Nice Hash people and in a recent - ish release, someone actually came up with a "fix" for this issue via a script. Credit here: 

Option to run a script when a CUDA device is lost (thanks @sebeksd)

I do not know who that person is, but I can rip out the script / and the directions and put them here so that @aaronsace or who ever can look at it and APPLY IT to MPM. I'm not a coder, or I'd just do it myself and submit it to MPM for review. Take a look. 
Two things though:
1) The script has 2 options. 1 option is to simply have the whole rig restart and msi afterburner settings will load from a saved OC. < I did not like this option. 
2) The 2nd option requires the freeware > nvidiainspector and when a gpu is lost, nvidiainspector will attempt to restore the lost Gpu without restarting the whole rig. < I liked this option and it worked. 

Here is the ".bat" file that I have changed to a ".txt" file to be able to load here. 
[OnGPUsLost.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1596925/OnGPUsLost.txt)

**Comment by fonyo** [comment]
This looks good, need to test it.

**Comment by cmbconcretefire** [comment]
It works. I know it works. Could it be this simple? > (from the script "you need to place "NvidiaInspector" in NHML directory under "NV_Inspector\nvidiaInspector.exe", this will set GPU profile (OC etc.) to default so it will also select MSI Afterburner profile

Ok, so why cant you simply "place Nvidiainspector" in MPM main directory in a new folder named "NV_Inspector\nvidiaInspector.exe"......... How the hell does this simple script "know" it's not running in NH? In theory, it wouldn't know. Then from there, it should be just a simple matter of going through the rest of the script and changing everything labeled "NHML" to "MPM". I mean, it really should be that simple. But again, I'm not a coder. :)

**Comment by thericeking** [comment]
I don't have any issues with GPUs dropping but this a great safety net to have. You never know.

**Comment by newcombio** [comment]
Its a decent way to get the miner back up and working, but that doesn't really fix the root cause of your gpu's dropping. I do like the idea of using nvidiainspecter to restart the cuda service though, that is a known software glitch. Just not a fix all for gpus dropping offline.

**Comment by borzaka** [comment]
I saw this [OnGPUsLost.bat](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/OnGPUsLost.bat) in NiceHashMinerLegacy. It has 2 options:
1. restart your entire rig
2. use nvidiaInspector to restart display drivers

Probably related issue: #956
