### ISSUE TITLE
Reported profits seem inflated

### ISSUE THREAD

**Issue by biesbjerg** [MultiPoolMiner/MultiPoolMiner#905]
This is for a rig using only two gpus (1070 + 1070TI) using the latest `v2.7.1.2`. I wish the numbers were true ;-)

Example:
```
MultiPoolMiner is between 1839% and 2020% more profitable than the fastest miner:


Miner : MultiPoolMiner
BTC   : 0,01496 ±174 % (0,00547-0,04093)
USD   : 203,19197 ±174 % (74,26154-555,96709)
EUR   : 178,49500 ±174 % (65,23543-488,39208)
DKK   : 1.255,29965 ±174 % (458,78040-3.434,70913)

Miner : Dstm-Equihash
BTC   : 0,00074 ±7 % (0,00069-0,00079)
USD   : 10,01068 ±7 % (9,34883-10,71939)
EUR   : 8,79394 ±7 % (8,21253-9,41650)
DKK   : 61,84500 ±7 % (57,75614-66,22334)
```

I ran `ResetProfit.bat` and `ResetBenchmark.bat` and ran `Start.bat` again, to recalculate the numbers, but I'm still seeing inflated numbers. Any idea what might be going on?

Log:
[2018-01-01_11-16-44.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1597162/2018-01-01_11-16-44.txt)

**Comment by aaronsace** [comment]
CcminerPolytimos has crashed, delete it from the folder called 'miners'.

**Comment by biesbjerg** [comment]
How did you determine that CcminerPolytimos is crashing/has crashed, and is removing a crashed miner generally what you want to do in that case?

Deleting it, resetting profits and running `Start.bat` indeed seemed to fix it. Just trying to understand how/why/what went wrong.

It seems about right for my setup now:

```
MultiPoolMiner is between 0% and 43% more profitable than the fastest miner:


Miner : MultiPoolMiner
BTC   : 0,00109 ±36 % (0,00080-0,00149)
USD   : 16,36395 ±36 % (12,00991-22,29651)
EUR   : 13,71226 ±36 % (10,06376-18,68348)
DKK   : 100,99610 ±36 % (74,12350-137,61103)

Miner : ExcavatorNvidia2-Blake2s
BTC   : 0,00090 ±27 % (0,00071-0,00114)
USD   : 13,45793 ±27 % (10,58279-17,11420)
EUR   : 11,27715 ±27 % (8,86791-14,34093)
DKK   : 83,06053 ±27 % (65,31554-105,62649)
```

**Comment by aaronsace** [comment]
The hashrate is huge!

If you watch whilst it benchmarks then there is most likely streams of errors and is spewing out hashrate.

**Comment by fonyo** [comment]
Not all miners work for all cards, there are even significant stability discrepancies between a 1080 and 1070 with some of the miners. Please don't be afraid to remove these completely, there are plenty of alternatives for all algorithms.
