### ISSUE TITLE
"-region" flag with "hk" option doesn't work with nicehash

### ISSUE THREAD

**Issue by felix920506** [MultiPoolMiner/MultiPoolMiner#906]
region set to hk and it connects to servers in other regions.
seen:
japan
britian
india

**Comment by aaronsace** [comment]
NiceHash have too many regions, MultiPoolMiner has US, Europe and Asia; thinking of replacing/complementing this with server ping. 
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/528

**Comment by fonyo** [comment]
@felix920506 Please see README.

**Comment by felix920506** [comment]
I'm in Taiwan which nicehash doesn't have a local server.
I pinged the servers with results below:
Region | Ping
--------|--------
HK | 27ms
JP | 76
IN | 88
BR | 341
