### ISSUE TITLE
problem with phi algo

### ISSUE THREAD

**Issue by JhonJhonny** [MultiPoolMiner/MultiPoolMiner#907]
every now and then the tpruvot miner give me this error, close the miner and after like a minute mpm reopen it and work flawlessly for the 5 minute after, then this error again.
from what i can tell its like the miner fail to recognize the gpus, but i kinda exclude it is a overclock problem cause is stable with every other algo even with this same miner, actually this screenshot explain it all, @aaronsace what do u think about it? just removing the algo?
![immagine](https://user-images.githubusercontent.com/30692674/34482083-1aa9320c-efb6-11e7-9d90-d7bf9701737a.png)

**Comment by JhonJhonny** [comment]
in the graph u can see the temp are going down at the end but like 5 min ago it happened the same thing

**Comment by UselessGuru** [comment]
You are overclocking. Try stock speeds.
If it the error still happens then discuss your issue with the miner developer.
MPM has no control over this. It just launches miners with command parameters.
