### ISSUE TITLE
windows 10 reboot randomly

### ISSUE THREAD

**Issue by JhonJhonny** [MultiPoolMiner/MultiPoolMiner#908]
don't know what else to say, just happen..
i noticed an error like "could not validate on cpu" in the miner and something like "not uploding results, hashrate out of the value of tolerance" in the mpm, then rebbot.
any clue?

**Comment by aaronsace** [comment]
Check systems issues; i.e. hardware, drivers, overclock. 

If you are having an issue with one miner then delete it from the folder called 'miners'.

**Comment by JhonJhonny** [comment]
actually haven't had this issue with mpm 2.7.1.1, yesterday i tried the 2.7.1.2 and this problem occurred.
now i'm double checking trying for a while the 2.7.1.1 again and let's see if reboot again

**Comment by JhonJhonny** [comment]
actually in the 2.7.1.1 it seems i cant find phi in the list but i've added it in the bat, this previous version does not support it or anything or am i missin something?

**Comment by JhonJhonny** [comment]
@aaronsace update: my toughts were correct, tried the 2.7.1.1, gone through all the algo benchmark i wrote in the .bat file, no error, mining for about 45 minutes and no reboot, no shutdown, and no crash for now. the only thing is that i cannot benchmark the "phi" algo (that i can in the 2.7.1.2) even if it's wrote in the .bat file

**Comment by UselessGuru** [comment]
If you really need the PHI algorithm then manually download the latest CcminerTpruvot miner.
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/CcminerTpruvot.ps1
