### ISSUE TITLE
Dual mining configuration

### ISSUE THREAD

**Issue by tboy1337** [MultiPoolMiner/MultiPoolMiner#909]
Any way to duel mine on normal pool and keep the currency rather than using zpool etc?

**Comment by UselessGuru** [comment]
????

**Comment by fonyo** [comment]
I believe you mean dual-mine and not two of your cards fighting each other (duel).

Try miningpoolhub, it supports a few ethash coins but the limitation is you can only dual-mine Sia as the secondary coin. No LBRY, Decred or Pascal support. If you include any of those MultiPoolMiner will start mining on other pools. Relevant commands and parameters:

    -poolname miningpoolhub -algorithm ethash,ethash2gb,siaclaymore

**Comment by tboy1337** [comment]
Thats not what i mean in both ways lol, what i mean is when ethash/whatever is most profitable i would like to actually mine lbry or pasc or whatever on an non-conversion pool like suprnova so i can keep the altcoins
