### ISSUE TITLE
Support more currencies for viewing profits

### ISSUE THREAD

**Issue by r0dn0r** [MultiPoolMiner/MultiPoolMiner#913]
Because I'm getting my payouts in DigiBytes on zpool i would like to also see my current earnings in DGB in MPM, but the coinbase API doesn't report DGB to BTC.
Maybe you could see into using cryptocompare's API (https://www.cryptocompare.com/api/).

**Comment by mic4rd** [comment]
this! I'd like to see profitability of the miners not hardcoded in BTC but in the currency(s) specified in the bat file

**Comment by UselessGuru** [comment]
@mic4rd 
This has been implemented here:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/2deeccf9b91f9555e7a052211c010699a41b0236
Or
