### ISSUE TITLE
Add option to weight algorithms or deduct profitability by power consumption

### ISSUE THREAD

**Issue by tavenger5** [MultiPoolMiner/MultiPoolMiner#914]
I realized after fine tuning my rig a little more, undervolting, and benchmarking again that my power meter was definitely showing different wattage depending on the algorithm, especially when dual mining. 

For example, when mining Cryptonight my rig consumes around 800w, but when dual mining ethash and lbry it consumes around 1200w. Right now the dual mining shows as more profitable, but Cryptonight may be more profitable, because it consumes 300 less watts.

I think it would be very useful to add a feature that takes power consumption into account, either by adding a weight to the algorithm, or a deduction to the profitability. I'm not sure exactly how this could be accomplished, but I'm guessing it would have to be a manually set feature since getting the actual power consumption per GPU would probably be difficult.

**Comment by Lagarinhos** [comment]
Project
https://github.com/MultiPoolMiner/MultiPoolMiner/projects

**Comment by paulpoco** [comment]
Just some example only mining MultiPoolHubCoin and miningpoolhub

2 x ASUS Dual OC GeForce GTX 1070 Video Cards OC to 110%
Ryzen 5 1600

2 GPUs Bin\Equihash-DSTM\zm.exe | Equihash | 17023
CPU Bin\CPU-JayDDee\cpuminer-4way.exe | lyra2z | 17025	
434w to 475w

2 GPUs Bin\NVIDIA-Nanashi\ccminer.exe | lyra2z | 17025
CPU Bin\CPU-JayDDee\cpuminer-4way.exe | lyra2z | 17025
330w

2 GPUs Bin\Excavator\excavator.exe | Lyra2RE2 
CPU Bin\CPU-JayDDee\cpuminer-4way.exe | lyra2z | 17025
430w to 444w

**Comment by paulpoco** [comment]
Is there a TP-link 110 API?

**Comment by UselessGuru** [comment]
> I think it would be very useful to add a feature that takes power consumption into account, either by adding a weight to the algorithm, or a deduction to the profitability.

My fork (very experimental) does exactly this: (NVIDIA only)
https://github.com/UselessGuru/MultiPoolMiner/commits/master

**Comment by paulpoco** [comment]
Beyond my knowledge right now.
[https://npm.runkit.com/tplink-cloud-api](url)

**Comment by paulpoco** [comment]
'True profit calculation. Will take power costs into account. Effective power consumption is read directly from hardware on each loop' this is cool

**Comment by fonyo** [comment]
It's in the pipeline for version 3. Power consumption matters for some users but not everyone hence why this has not been priority but will surely come by V3.

**Comment by tavenger5** [comment]
@fonto Great thanks!  

@paulpoco using the tp-link would be a great idea. Id love to use that api to tie into a watchdog to reset things if they stop responding too.
