### ISSUE TITLE
Profitability Readout Disappears after 1st 'Refresh'

### ISSUE THREAD

**Issue by riznarf** [MultiPoolMiner/MultiPoolMiner#915]
Apologies in advance, I am not a dev, so this may not be super "technical"  But the profitability readout appears when first launching MPM (it's not benchmarking) and then when the screen refreshes (presumably to get updated conversion rates?) it disappears.

Check out the log, you'll see it appear in the first readout, and then disappear for all following

![image](https://user-images.githubusercontent.com/35058534/34512045-4aefb870-f068-11e7-8cde-13beb3d5574f.png)
[2018-01-03_08-09-00.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1599650/2018-01-03_08-09-00.txt)

**Comment by zzup** [comment]
I am seeing the same thing on 3 of my machines.

**Comment by drcrimzon** [comment]
For me it appears the downloader is running when it goes to display the profit, so it does not display the profit.

I tried adding a sleep before displaying the profit, but it was not reliable, so I ended up just removing the downloader check before displaying profit.

**Comment by papacheal** [comment]
From reading the main PowerShell code, it appears that the profitability display will only appear when MPM is actually more profitable than the fastest standalone miner. Based on how MPM gets smarter about mining decisions over time, I would expect the display to appear more often the longer MPM runs.

**Comment by riznarf** [comment]
@drcrimzon can you paste exactly what code needs to removed from which file please? (<- not a dev)

@papacheal not sure how MPM would be *less* profitable than any single miner....otherwise wouldn't MPM just run that miner and be 0% more profitable than the fastest miner?

**Comment by drcrimzon** [comment]
Line 513 (latest code):
    if (($BestMiners_Combo | Where-Object Profit -EQ $null | Measure-Object).Count -eq 0 -and $Downloader.State -ne "Running") {

changed to:
    if (($BestMiners_Combo | Where-Object Profit -EQ $null | Measure-Object).Count -eq 0) {

**Comment by nichenke** [comment]
Skipping the downloader check and/or a sleep & Receive-Job before that stanza is what works here too.

**Comment by cmbconcretefire** [comment]
I followed this too. Works like a champ now. I have my 'little yellow bar' back giving me my profit stuff. Good find.

**Comment by aaronsace** [comment]
7b933d72135d68e34d7d28f560ddc841aa201b0c
