### ISSUE TITLE
Start-Nicehash eventualy mines to unknown wallet

### ISSUE THREAD

**Issue by AndrewB5za** [MultiPoolMiner/MultiPoolMiner#916]
Notice my worker disappearing on nicehash when using start-nicehash.bat
MPM start fine mines for awhile then switches to this wallet 
In the MPM window I see its running to a different wallet.

output in MPM window

 Bin\Equihash-Claymore\ZecMiner64.exe -r -1 -mport 13333 -zpool stratum+tcp://equihash.eu.nicehash.com:3357 -zwal 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb.multipoolminer -zpsw x
                                                 -allpools 1

This is with donate 0 so why is it still mining to another wallet ?

**Comment by aaronsace** [comment]
Check the readme: https://github.com/MultiPoolMiner/MultiPoolMiner

**Comment by AndrewB5za** [comment]
this has nothing to do with the start file or mysettings.
It start mining fine to my nicehash wallet then eventually starts mining to this wallet.
If there is something in readme I missed other than editing coin address in Start-nicehashbat please explain what it is.

**Comment by aaronsace** [comment]
Please post the log if your behaviour differs from the readme.

**Comment by AndrewB5za** [comment]
[2018-01-03_08-33-46.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1599740/2018-01-03_08-33-46.txt)

Batch file is started with donate 0

**Comment by aaronsace** [comment]
It matches both the [readme ](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md)and the [website](https://www.multipoolminer.io/). 

0.7% = 10 minutes

**Comment by AndrewB5za** [comment]
so setting it to donate 0 for testing no longer works ?
