### ISSUE TITLE
Remove miners from download package - grab from source

### ISSUE THREAD

**Issue by zzup** [MultiPoolMiner/MultiPoolMiner#917]
One problem i have been having is due to the package having multiple miners in it, it is always flagged by every antivirus and browser addon.  What if the miners were hosted and downloaded only if needed by what the person is mining?  This would cut down on having to gather them all in the folder for install and only download what ones you need.  This would also cut down on what files people have to flag as ok.

**Comment by aaronsace** [comment]
@zzup That's what it already does...?

**Comment by papacheal** [comment]
I believe the concern is over the pre-bundled miners (i.e. ones you've included in the release that are not easy to retrieve via HTTP). Having those binaries in the ZIP immediately flags the archive as "bad" to most AV engines and doesn't offer the user a way to exclude the target MPM bin folder from AV scanning after initial install. Making all of the miner binaries downloadable after-the-fact would help this, but I'm not sure all of the listed miners could be retrieved (e.g. Google Drive downloads).

**Comment by zzup** [comment]
Yes it is the pre packaged ones that flag the download.  Also many of those i do not use.  Could they be stored on the project git page and retrieved only if needed?  This would make the download easier to allow through AV.

**Comment by UselessGuru** [comment]
> and retrieved only if needed?

That is how it works already. MPM will only download the required miners. E.g. if you mine NVIDIA only no AMD or CPU miner will ever find it's way to your box.
Basically for each miner file (folder \MINERS) there is  miner executable that will be downloaded. What else would you like?

**Comment by aaronsace** [comment]
Honestly, any virus checker that blocks Claymore and DSTM should be taken to court and certainly shouldn't have any users. All the other miners are downloaded dynamically and on demand. 

For anyone that wants to tackle it, this is what needs including to download Claymore miners: 
https://github.com/meganz/sdk/releases

**Comment by titvs** [comment]
I solved this by adding the MPM folder to the Windows Defender exclusion list. I guess the same can be made with any AV soft...

**Comment by zzup** [comment]
One of the big ones is EWBF.  That one always hits AV.

**Comment by papacheal** [comment]
On that note, updated version of DSTM is out (0.5.8), newer than bundled version in MPM v2.7.1.2.

https://bitcointalk.org/index.php?topic=2021765.0

**Comment by UselessGuru** [comment]
> Is there anyway to remove the requirement for it? I love DSTM so much better.

There is NO requirement. If you don't want it then delete the \miner\EWFB.ps1 file. Done.

**Comment by zzup** [comment]
Strange.  There is no EWFB.ps1 only a txt file.  The problem is that when i deleted the miner off my computer the MPM would give an error stating it has to have EWFB as it is required by DTSM too.

**Comment by UselessGuru** [comment]
> EWFB.ps1 only a txt file.

Same. All files in \Miners\ work the same, If the variable $URI is set the miner will be downloaded.

> it has to have EWFB as it is required by DTSM too

???
