### ISSUE TITLE
Infinite "socket closed remotely(by pool)" errors when using nicehash

### ISSUE THREAD

**Issue by felix920506** [MultiPoolMiner/MultiPoolMiner#918]
Works perfectly when using nicehash miner from another computer.
I don't know what's wrong.
![image](https://user-images.githubusercontent.com/25688628/34520787-51e691a0-f0c5-11e7-8c2d-f41ac0b61195.png)

**Comment by aaronsace** [comment]
Try 'US' instead or use one of the other pools.

**Comment by UselessGuru** [comment]
NH was doing some maintenance work. Should be fine again.
