### ISSUE TITLE
CPU Errors

### ISSUE THREAD

**Issue by NCarter84** [MultiPoolMiner/MultiPoolMiner#919]
Hey Guys, Noob here.... Been using Awesome Miner and wanted to give this a try and see the difference.

I have the Start.bat file edited down to what I need (Old hardware, so just running Equihash/Cryptonite)

I'm getting several off/on errors...

1. XMRig will be just chugging away, then all the sudden it will go to switch the main CMD Info Screen will flash and a whole bunch of red font info will scroll through and close... Here is preview of what I'm seeing.

>  Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 35 Minutes Once     Bin\CryptoNight-CPU\xmrig.exe
                                               --api-port 3334 -a cryptonight
                                               -o stratum+tcp://us-east.crypton
                                               ight-hub.miningpoolhub.com:17024
                                                -u NCarter84.SSI9020GPU -p x
                                               --keepalive --nicehash
                                               --donate-level 1

Miner               Pool          Algorithm   Watchdog Timer
-----               ----          ---------   --------------
XmrigCpu            MiningPoolHub CryptoNight    507 Seconds
ClaymoreAmd         MiningPoolHub Equihash         1 Seconds
CpuminerJayddee4way MiningPoolHub CryptoNight    172 Seconds

PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\Test\Desktop\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:355 char:170
+ ... s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ...
+                                                         ~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\Test\Desktop\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:355 char:170
+ ... s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ...
+                                                         ~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

>> TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\Test\Desktop\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:355 char:170
+ ... s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ... 

+                                                         ~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\Test\Desktop\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:355 char:170
+ ... s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ...
+                                                         ~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

>> TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\Test\Desktop\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:355 char:170
+ ... s | Where-Object {(Compare-Object $Miner_GPU.Device $_.Device | Measu ...
+                                                         ~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\Users\Test\Desktop\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:355 char:170

>

**Comment by grantemsley** [comment]
Closing outdated issue.  If this is still a problem in the latest version (and there currently isn't an open issue for it) please open a new one.
