### ISSUE TITLE
ForEach Object Error

### ISSUE THREAD

**Issue by mplunkett5** [MultiPoolMiner/MultiPoolMiner#920]
I have just updated to the latest version of MPM (v2.7.1.0) and I am getting the following error when running and occasionally whilst mining:

`ForEach-Object : You cannot call a method on a null-valued expression.
At C:\Users\Mark\Desktop\MultiPoolMiner - v2.7.1.0\Include.psm1:174 char:61
+ ...              ($_ | Get-Content | ConvertFrom-Json) | ForEach-Object {
+                                                          ~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.ForEachObjectCommand`

Screenshot: https://www.dropbox.com/s/zps6uobnixddpwx/error.PNG?dl=0

**Comment by IDontKnow-YouTube** [comment]
Had the same issue on a fresh install that I interrupted during benchmarking. Ran ResetBenchmark and it cleared the issue.

**Comment by almothafar** [comment]
Got the same issue, ResetBenchmark not worked for me, I followed all important notes but was not helpful.

**Comment by UselessGuru** [comment]
Please try after deleting ALL files in the stats folder.

**Comment by almothafar** [comment]
@UselessGuru I really tried that many times, and even with a fresh version, by removing all files, extract the files again and modifying .bat files and run it again.

**Comment by UselessGuru** [comment]
@almothafar 

Does the error occur already on first start, or after subsequent runs?

The error comes from reading one of the files in one of the following directories:
\Stats
\Pools
\Miners

We have to find out which file is causing it. Can you do a fresh install (yes - once more). Do NOT edit any files!

Then BEFORE you start:
- remove all miner files (stats folder is still empty)
- Run MPM -> error still here? You might get 'no miners available' - that expected
- If yes, remove all stats files, remove all but on pool files
- Run MPM -> Error still here? -> If yes than I am puzzled
- if not (you will see no miners available, but that's expected), then add another pool file, delete all stats, run MPM again. Loop until you find the Pool file causing problems
-If all pools are working then:
- Put the miner files back one by one, alwas deleting all the stat before each try.

Also could you please upload the logs for the problematic run.

Please note that future releases will include extra functionality to aid debugging this like this.

**Comment by almothafar** [comment]
@UselessGuru actually the issue was happening with any Miner, without miners, I get no issues but the warning.

[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1624154/Logs.zip)

**Comment by aaronsace** [comment]
There is something wrong with your opencl.dll that is needed for the AMD miner files like sgminer.

**Comment by almothafar** [comment]
@UselessGuru 

I have the version of nVidia driver is 388, currently, I'm updating it t 390

Anyway, this is the log file for just extract and run, nothing changed:
[2018-01-11_23-38-58.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1624206/2018-01-11_23-38-58.txt)

**Comment by aaronsace** [comment]
Same error; OpenCL. Delete the miner files for now.

**Comment by aaronsace** [comment]
This is the function that the AMD miner files use that's not working: 

```
public static Platform[] GetPlatformIDs()
{
	ErrorCode error;
	uint count;

	error = NativeMethods.clGetPlatformIDs(0, null, out count);
	if (error != ErrorCode.Success) {
		throw new OpenClException(error);
	}

	var ids = new IntPtr[count] ;
	error = NativeMethods.clGetPlatformIDs(count, ids, out count);
	if (error != ErrorCode.Success) {
		throw new OpenClException(error);
	}

	var res = new Platform[count];
	for (var i=0; i<count; i++) {
		res[i] = new Platform(ids[i]);
	}
	return res;
}
```

**Comment by almothafar** [comment]
Why it is AMD I got Intel here, is it normal?

**Comment by aaronsace** [comment]
There has been 23 commits to the wrapper that I'm using, maybe it's been fixed: 
https://github.com/aaronsace/opencl-sharp

@almothafar Does this fix any of the OpenCL issues?
[OpenCL.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1624291/OpenCL.zip)

**Comment by aaronsace** [comment]
@almothafar You have NVidia not Intel.

**Comment by almothafar** [comment]
Oh nvm, I thought it is CPU not GPU, anyway, I tried new OpenCL files and have no logs, only the following errors:

```

WARNING: (2110) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2123) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2136) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2147) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2158) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2169) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2180) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2194) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2203) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2247) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

WARNING: (2252) : 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'

& : (373) : A using clause must precede all other elements defined in the namespace except extern alias declarations
At line:1 char:3
+ & .\multipoolminer.ps1 -username almothafar -workername mariam -regio ...
+   ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (D:\MultiPoolMiner\Include.psm1:String) [], RuntimeException
+ FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by aaronsace** [comment]
Fixed compilation issues, try now: 
[OpenCL.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1624577/OpenCL.zip)

**Comment by aaronsace** [comment]
Try running the test bat as an admin; do you get the same output? 

Are you using remote desptop? 

Have you tryed completly uninstalling the driver then downloading and installing the new one?

**Comment by aaronsace** [comment]
I've found an official NVidia test example: 
[oclDeviceQuery.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1629534/oclDeviceQuery.zip)

If that works then I know it's something wrong with what I'm doing. 
If that doesn't work then I know there is something wrong with your system.

**Comment by almothafar** [comment]
I was always doing run as administrator.
No, I'm on the machine.
Yes, many times, and I tried to see if any of those drivers software can fix driver issues (if found any), like Device Doctor, Driver Booster and so on.

For the Device Query, it seems not working, so it is my system?
[oclDeviceQuery.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1629618/oclDeviceQuery.txt)

**Comment by aaronsace** [comment]
Must be, as it says here that OpenCL is included in that drivers link and has the example usage below: 
https://developer.nvidia.com/opencl

From the perspective of getting MultiPoolMiner to run, delete any files in the folder called 'miners' that contain the word 'opencl'.

**Comment by almothafar** [comment]
Thanks for your efforts, I started the benchmark now and it seems going without any error as initial run, not completed the run yet it is ongoing now
