### ISSUE TITLE
Algos config for 1080 not TI

### ISSUE THREAD

**Issue by Tyserie** [MultiPoolMiner/MultiPoolMiner#921]
Hi, I would like to ask what is best algo and pool setting for 4x GTX 1080 on MPM. Thank you and srry for silly question :)

**Comment by Tyserie** [comment]
and if anyone can suggest also algos and pool for 4 RX 580 on MPM. Thx a lot

**Comment by UselessGuru** [comment]
There is no perfect recommendation. Profitablility reported by MPM  is always higher (MPM displays correct profit based on info sent by pool btw!) than what you will actually get paid regardless of pool or algo. Just the extent of the mismatch differs from pool to pool.

My suggestion:
Algos: Use defaults in start.bat in master. DO NOT choose ALL algos.
Let it run against one pool for a few hours. Note effective earnings, then do the same with the next pool. Then choose your pool.
