### ISSUE TITLE
Intel CPU Design Flaw - For Your General Knowledge

### ISSUE THREAD

**Issue by lee-aaron** [MultiPoolMiner/MultiPoolMiner#922]
If you haven't heard about this yet, I think this affects us all especially for mining and other daily purposes. I'm not very knowledgeable in CPU architecture but here's a short summary of what the problem is.

**For the non-technical readers:**
Recently, there's been hot news about Intel's CPU design flaw as attackers can access the memory used by your programs. This means that attackers have a way to launch malware, steal data, etc. from your laptop/desktop. Since this flaw is built into the CPU, the only solution at the moment will be redesigning the OS for Windows and Linux etc. This will mean a slowdown in your daily activities such as browsing, checking your email, etc.

**For the technical readers:**
In the CPU, there are two memory spaces: one allocated to the kernel and one to the user. Users shouldn't be able to access other user memory spaces due to protection but the flaw in the design allows them to override that protection. (Perhaps more technically oriented readers can explain this more.) This bug can compromise individual computers and even server networks. Looking at AWS and GCP, that's a huge issue. You can expect a slowdown in your performance whether it be mining or simple computer usage. 

Well yeah thanks for reading! This is just a fyi. There is plenty of [news](https://www.reuters.com/article/us-cyber-intel/design-flaw-found-in-intel-chips-fix-causes-them-to-slow-report-idUSKBN1ES1BO) and [articles](https://www.theregister.co.uk/2018/01/02/intel_cpu_design_flaw/) about this on the internet. I just summed it up a bit for you guys :)

**Comment by platinum4** [comment]
This issue has been resolved by Windows 10 1709 patch 16299.192 and an appropriate BIOS upgrade from your motherboard's OEM.  This issue is old news at this point and can be closed as it is unrelated to the coding of MPM.
