### ISSUE TITLE
Can we get a version of MPM that is optimized for Nvidia miners only? Like NemosMiner

### ISSUE THREAD

**Issue by thericeking** [MultiPoolMiner/MultiPoolMiner#923]
Can we get a version of MPM that is optimized for Nvidia miners? Forgive me if I am out of place for saying this but NemosMiner is so much more simple to deploy. No errors downloading the miners it needs and no Windows Defender issues. It just works. I am not sure how much faster or slower NemosMiner is but feels a hell of a lot more simpler and stable. I've been using MPM for more than a month now and there hasn't been any new updates recently that corrects the errors that MPM generates when it can't download the miners. I don't mind downloading Excavator and drag and dropping it to the bin folder but now I get so many miners just suddenly stop working during benchmark even without no overclocking at all. I am not a programmer but I've been building computers since 2000 and I work in the IT industry. I know what I'm doing in regards to building a machine from start to finish and optimizing the OS by decrapifying it from all the bloatware. Just getting tire of the time wasting I am doing recently troubleshooting MPM. I'm not ranting. I am grateful for this project but this project should also be grateful that I am donating 10 minutes every 24 hours for each of my 3 mining rigs which have 6 GPUs each.  That's 70 minutes of "donated" (mandatory donation) hash power per week. None of us is getting this software for free. We are all paying. So can we please get a new version that just works. I mean this respectfully and I hope I didn't offend any of the developers and you guys can understand. Thank you

**Comment by UselessGuru** [comment]
What for? You will gain close to no performance benefit. Just delete all AMD & CPU miners. Done!

> stop working during benchmark even without no overclocking
If the miner stops working (=crach) then this has nothing to do with MPM.

**Comment by 3zero2** [comment]
No offense intended; I'm genuinely curious: So why not use NemosMiner instead?

**Comment by aaronsace** [comment]
NemosMiner is literally my code but with the AMD miners deleted. I have run the benchmark again and again till the cows come home. The code is open; if anyone can do anything better or if there is something wrong then point it out. Anyone in IT can grasp a bit of PowerShell. 

I'm going to close this as it could easily turn into a rambling thread. Post bugs and feature requests in the issues section. Post code changes as pull requests. 

If anyone feels they are compitent enough to work on this and has enough free time then skype and we can come to an arrangement. User: aaronsace
