### ISSUE TITLE
Msvcr120.dll is missing even if it is installed properly

### ISSUE THREAD

**Issue by fonyo** [MultiPoolMiner/MultiPoolMiner#924]
This is from reddit by /u/dwaynemoore, I am having the same issue on two nvidia rigs.
Post can be found at https://www.reddit.com/r/multipoolminer/comments/7nxrlp/multipoolminerv2712binnvidiasp_problems/

> MultiPoolMinerV2.7.1.2\Bin\NVIDIA-SP\ccminer.exe fails to run because there is no msvcr120.dll to be found. "Fine." I say, "I've seen this before.", and I copied one from one of the other subdirectories to the MultiPoolMinerV2.7.1.2\Bin\NVIDIA-SP directory. Now MultiPoolMinerV2.7.1.2\Bin\NVIDIA-SP\ccminer.exe fails with "The application was unable to start correctly (0xc000007b)." Does anyone have that compiler working?

**Comment by JhonJhonny** [comment]
its not a copy and paste to do there, you need to install the windows visual studio 2013 and 15 if i remember correct (i installed both the x64 and x86 to be sure)

**Comment by aaronsace** [comment]
Try this, does that this the issue? 
 
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/1f46e26643b98a74ab0f0eb2cacbe6fc7f143f33/Miners/CcminerSib.ps1#L21-L22

**Comment by Kaoz99** [comment]
Also have this exact issue on 2 of my 10 rigs. Running 2.7.1.4 and its when trying to run CCminer Lyra2Re2Nvidia.

I rebooted, reinstalled the redistributable and no go.

**Comment by UselessGuru** [comment]
Maybe this could help:
https://support.microsoft.com/en-us/help/249873/how-to-use-the-regsvr32-tool-and-troubleshoot-regsvr32-error-messages

As admin:
`%systemroot%\System32\regsvr32.exe %systemroot%\System32\msvcr120.dll`

**Comment by Kaoz99** [comment]
Getting same error on both : 
The module "C:\Windows\System32\msvcr120.dll" was loaded but the entry-point DllRegisterServer was not found.
Make sure that "C:\Windows\System32\msvcr120.dll" is a valid DLL or OCX file and try again.

**Comment by UselessGuru** [comment]
Make sure you install [32bit AND 64bit runtimes](https://www.microsoft.com/en-us/download/details.aspx?id=40784):
