### ISSUE TITLE
set intensity on miner when launched by mpm

### ISSUE THREAD

**Issue by JhonJhonny** [MultiPoolMiner/MultiPoolMiner#925]
as the title, can i change the intensity of an algo (x17 for example) in the ccminer tpruvot? because if i go in the folder of the miner, in his bat file i kinda cant cause the placeholder are clearly pointing to suprnova pool, but when the miner got launched by mpm it point at zpool (and thats what i want) so is using, i believe, another bat to doing that.
the post will sound a little confuse, i'm sorry

**Comment by aaronsace** [comment]
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/12f376f2a3717fceb5f8d25bf89a22aa3d24aacb/Miners/CcminerTpruvot.ps1#L36

Set it like this (include the space at the front): 
`"x17" = " -i 20"`

**Comment by UselessGuru** [comment]
If you have multiple cards and you want to set a different intensity per card you will have to set it like " -i 20,20,17" (one value per card). Note the space.

**Comment by JhonJhonny** [comment]
thaks a lot for understanding the mess i wrote up there xD

**Comment by UselessGuru** [comment]
> thaks a lot for understanding the mess i wrote up there xD

You're welcome :-)
