### ISSUE TITLE
How do I use the "-excludeminername" command?

### ISSUE THREAD

**Issue by thericeking** [MultiPoolMiner/MultiPoolMiner#926]
I want to exclude both miners listed below because what it says on your official website: https://multipoolminer.io/doc

KNOWN ISSUES

There are known issues with the following miners not submitting shares or show higher hashrate than what they actually do:

CcminerLyra2z
CCminerLyra2RE2

It says: "Use the -excludeminername command to exclude certain miners you don't want to use. A full list of available miners and parameters used can be found here: https://multipoolminer.io/miners"

In which order in the bat file (start script) do I place the "-excludeminername" command?

Why are these miners included if they have such serious flaw?

P.S. CCminerLyraZ (the one listed with the flaw) is not listed in https://multipoolminer.io/miners but CcminerLyra2z is. Are they both the same but the person writing the documentation forgot to add the number 2 to the name of the miner?

**Comment by UselessGuru** [comment]
> In which order in the bat file (start script) do I place the "-excludeminername" command?

Any order is fine. If in doubt just add it at the end.

> Why are these miners included if they have such serious flaw?

If we didn't include them people what ask for them.

**Comment by fonyo** [comment]
Yes, it is the same miner.

To give you perspective on where to place it, you could put it after the algorithm command.

    -algorithm [......] -ExcludeMinerName ccminerlyra2re2,ccminerLyra2z

There are other miners that show higher hashrate than what they actually produce, they are just not that noticeable. A solution to counter these issues is being worked on.
