### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Pititul** [MultiPoolMiner/MultiPoolMiner#928]
I have been using KlasusT 8.14-8.18 for Neoscrypt through all version of MPM. But for the last few weeks, with the new MPM (master or releases), KlausT is the only ccminer that reboot my computer when it launches. Any idea why? Didn't happen on older MPM . I even roll-backed to 8.15.

Using Alexis78 as the next best thing now.

**Comment by UselessGuru** [comment]
Miner crashes and MPM code are not related.
Think of MPM being someone who constantly monitors price information on many sites, then calculates the best option (miner), Then it looks up the necessary parameters needed (e.g. pool url, wallet etc.) and starts the miner.
You will find that the miner will crash exactly the same if you start it with the same parameters from within a powershell session,
-> please direct your requests regarding miner crashes at the miner developer site. We cannot assist in these cases. Thank you,
