### ISSUE TITLE
Ask For Daily

### ISSUE THREAD

**Issue by yihaaz** [MultiPoolMiner/MultiPoolMiner#929]
HEllo want to ask. 

My Mining Rig use 5pcs 1080ti + 3pcs 1060 6gb
and i use ahaaspool 
and perday  its  around 70 - 80 USD
But if i check ahashpool. 1 day i only got 0.0028++ BTC. are around 55-60 dollar

are this is mean i got problem or ?

if i see mybe this is the problem ?
![whatsapp image 2018-01-04 at 8 23 49 pm](https://user-images.githubusercontent.com/35103834/34565753-a3469ec2-f18e-11e7-9c38-0595508b9f36.jpeg)
![whatsapp image 2018-01-04 at 8 25 21 pm](https://user-images.githubusercontent.com/35103834/34565754-a376da60-f18e-11e7-8a1e-47e81e8ba5c5.jpeg)

**Comment by UselessGuru** [comment]
This is very normal.

MPM multiplies the recorded hashrates (from benchmarks) with the price information received from the pool -> projected profit.

Reality:
- Miner reports hashrates too high (MPM readout)
- Stale / invalid shares
- Hashrate reported at pool is lower than what the miner says.
- Pool, miners & MPM take fees

Result: See your screenshots :-)

Just accept it as a fact

**Comment by aaronsace** [comment]
@yihaaz Why is your username 'm'???

Post your logs.

**Comment by yihaaz** [comment]
@aaronsace 
this is my log 
[2017-12-31_08-08-50.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1605171/2017-12-31_08-08-50.txt)
[2018-01-05_01-49-49.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1605172/2018-01-05_01-49-49.txt)

**Comment by aaronsace** [comment]
You have a comma after 'skein'; get rid of it and it should actual work then. 
Also, make sure that you are an the latest release.

**Comment by yihaaz** [comment]
@aaronsace    skein in the start batch ? or where . btw thanks you very much, for your reply

**Comment by aaronsace** [comment]
Yes, in the batch file.

**Comment by yihaaz** [comment]
@aaronsace  
but i think my start batch are okay

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 1MmjLgMYEKMAJcjNomvNsfaGM66icrSDQm -username yihaaz -workername AmponDJ -ssl -region asia -currency usd -type nvidia -poolname ahashpool -algorithm lyra2v2,skunk,blake2s,equihash,lbry,neoscrypt,keccak,sia,ethash,x11gost,groestl,pascal,skein,nist5 -watchdog"

**Comment by platinum4** [comment]
Your batch specifies ahashpool only but your screenshot shows a miner connecting to hashrefinery

**Comment by robl45** [comment]
it will connect to any pool that the algorithm can do if the pool files are there.  you need to remove pool files or exclude the pool to stop that behavior.  Really remove the pool files because even exclude pool will mine the pool if the algorithm specified doesn't work on the pool you want to mine.

**Comment by yihaaz** [comment]
@robl45  nah already delete all pool.
@aaronsace 
but when its running 

its like this , are they normal running without wallet address? 
![inkedwhatsapp image 2018-01-05 at 11 10 21 am_li](https://user-images.githubusercontent.com/35103834/34609185-38ef9b44-f24e-11e7-9316-3362ebff0fc1.jpg)

**Comment by aaronsace** [comment]
@yihaaz Are you actually using the latest release?

**Comment by yihaaz** [comment]
@aaronsace  i dont use the latest release.
because the profit perday decrease so big. so i dont use it.
i use  7.02 version

**Comment by aaronsace** [comment]
@yihaaz I'm going to close this, you need to use the latest release.
