### ISSUE TITLE
MPM out of date even when completely deleting and redownloading

### ISSUE THREAD

**Issue by dposse** [MultiPoolMiner/MultiPoolMiner#930]
Title... have completely deleted all mpm files and redownloaded a couple times, still get "WARNING: No pools available." and "WARNING: MultiPoolMiner is out of date; there is an updated version available at https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.1.2/MultiPoolMinerV2.7.1.2.zip"

Started last night, any ideas?

**Comment by aaronsace** [comment]
Made a mistake, 6.1 should say v2.7.1.3; non-issue though as it doesn't actual do anything: 
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/c6a644e25c584b4333fe0595e1535801b55f30da/MultiPoolMiner.ps1#L87
