### ISSUE TITLE
Cannot bind argument to parameter 'DifferenceObject' because it is null. problem

### ISSUE THREAD

**Issue by bebekaleyo** [MultiPoolMiner/MultiPoolMiner#931]
hey guys

i have a problem suddenly but i still can mining
idk if its a serious problem or not
but heres what it say from the log

ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At E:\MultiPoolMinerV2.7.1.2\MultiPoolMiner.ps1:177 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

PS>TerminatingError(Invoke-Expression): "Exception calling "GetPlatformIDs" with "0" argument(s): "Unable to load DLL 'opencl.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)""

i'm noob in coding and i dont know what to do

thanks

**Comment by UselessGuru** [comment]
See [Important Notes](https://github.com/MultiPoolMiner/MultiPoolMiner)
