### ISSUE TITLE
WARNING: Stat file (CcminerTpruvot_X17_HashRate) was not updated because the value (22566670) is outside fault tolerance (24181411 ... 30255085).

### ISSUE THREAD

**Issue by JhonJhonny** [MultiPoolMiner/MultiPoolMiner#932]
what does this "WARNING: Stat file (CcminerTpruvot_X17_HashRate) was not updated because the value (22566670) is outside fault tolerance (24181411 ... 30255085)." mean?
cause after displaying this error 3 times mpm put the x17 algo on failed

**Comment by UselessGuru** [comment]
This means that the miner reported 22566670 h/s, where as during benchmark approx 270000000 (tolerance +-/10%) was recorded.

This may happen if your card is slowing down (heat, changed OC).

If the messages persists then delete the stat file \Stats\CcminerTpruvot_X17_HashRate.txt. MPM will the run the benchmark for this algorithm again.

See [Readme Q18](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.txt)

**Comment by JhonJhonny** [comment]
which file i have to open to modify that limit?
