### ISSUE TITLE
Donation times for individual miners?

### ISSUE THREAD

**Issue by paulpoco** [MultiPoolMiner/MultiPoolMiner#934]
I know MPM is 10 or is it 24 min.

The individual miners does anyone know what amount of time is donated to them?

I have been averaging about $8 CAD a day but MPM estimates $16 or so.

Trying Nicehash again.  In 6.5hrs up to 0.00023982 BTC or 4.57 CAD now.  So if it stays same rate it would be about $18/day.

Mining Ryzen 5 1600 & 2 x Asus dual  GTX 1070 OC 8Gb cards.

The MPM estimate is about the same as Nicehash possible.

**Comment by UselessGuru** [comment]
> The individual miners does anyone know what amount of time is donated to them?

Check the respective developer websites for more info on their fees.
Nicehash and MPM use the same miner, so the same fees will apply

**Comment by paulpoco** [comment]
15hrs into mining on Nicehash at 0.00047926 BTC, never got that on MPH during a 24hr period.
