### ISSUE TITLE
ETHDCRMiner64.exe can not download

### ISSUE THREAD

**Issue by RANGERBEE** [MultiPoolMiner/MultiPoolMiner#935]
After running successful benchmark, find that I have the yellow text indicating a "Warning" that it can not download or find ETHDCRMiner64.exe.

Currently it is sitting idle after this warning. Should there be further processing or benchmarking at this point?

Thx.

**Comment by RANGERBEE** [comment]
I hit enter  - it has lots of red PS errors object not founds and some opencl errors.

This process repeats for a few miners like excavator and the one by equihash as well.

Is this all part of the benchmarking process for each miner?

Could I avoid most of this by removing these error-prone miners from a list somewhere?

Thanks!

**Comment by RANGERBEE** [comment]
Update - Found Q9/A9 in readme. Trying to apply logic now.

**Comment by UselessGuru** [comment]
There is something seriously wrong with your installation.

Could you please post logs & screenshots - TIA

**Comment by aaronsace** [comment]
#936

**Comment by RANGERBEE** [comment]
I figured it out guys... I just removed the miners that I did not want to use because of failure or just not relating to my hardware/needs.  Then found that my GPU's were not powered correctly. Once all was sorted I am now mining,  Thanks.   31.938Mh/s ea. ETH  on Claymore dual...
