### ISSUE TITLE
Scheduled Task

### ISSUE THREAD

**Issue by i3luefire** [MultiPoolMiner/MultiPoolMiner#938]
will having the batch program run at windows startup as a scheduled task work?
![image](https://user-images.githubusercontent.com/3527233/34591677-e6b4dde0-f184-11e7-886d-5ae36a7381d6.png)

**Comment by TVanAusdall** [comment]
You can easily set up a .bat to run at startup by following this :-)

https://www.computerhope.com/issues/ch000322.htm

**Comment by aaronsace** [comment]
You can ruN MultiPoolMiner miner without a batch file if you launch it through task scheduler. 

A bat in the start up folder is easier though.

**Comment by i3luefire** [comment]
So, I need to run it without the batch file if I use the task scheduler? I think that the startup folder way requires a person to be logged in. And the task scheduler can run things before anyone logs in.

**Comment by i3luefire** [comment]
And if that is true what file would I schedule to run the powershell command that the batch file would normally run?

**Comment by TVanAusdall** [comment]
@i3luefire 
I took a round about but ultimately easy route to accomplish what you are looking for.

I installed winner when easy hash went down, in winner settings it has an option for setting the system to auto login at boot. I later killed winminer but retained the auto login.

I then put the link to start.bat into the startup folder as described earlier and everything works great.

Even when the damn system auto reboots from a software update it comes right back up running aaronsace's MPM :-)

**Comment by i3luefire** [comment]
I do not want to have the computer auto login. I already know how to do that but I want to have the miner start without anyone being logged in.

**Comment by fonyo** [comment]
You can schedule to launch the start.bat directly but make sure to set the "start in" to the path of MPM.

**Comment by i3luefire** [comment]
thank you.

**Comment by platinum4** [comment]
This issue is resolved and a .bat file can be pointed to by Task Scheduler in Windows.  Please close this.

**Comment by i3luefire** [comment]
Do not run MPM version 2.7.1.4 from the task scheduler. It causes problems with background processes not closing properly. There may or may not be some way to fix this but as of 2.7.1.4 you should not run MPM this way.

**Comment by platinum4** [comment]
Oh.  I use it like this so when the rig crashes and resets it just runs MPM after being booted for 5 minutes.  I don't ever have an issue with downtime like that since it continuously will run itself if it ever crashes the rig softly.
