### ISSUE TITLE
ParameterBindingValidationException

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#939]
Hi everyone,

Updated today the files of MPM to the last commit on my test machine and im getting a ParameterBindingValidationException...
Started getting this error only this morning and i think was after a MS update to Windows 10:

https://support.microsoft.com/pt-pt/help/4056892/windows-10-update-kb4056892

Also there are some errors related to SgminerLyra2z... Ive included the log file.

[2018-01-05_10-12-47.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1606267/2018-01-05_10-12-47.txt)

**Comment by titvs** [comment]
Ive deleted the MPM contents, re-downloaded everything and it seems to be working again. Any thoughts why it did pop up?
What do you recommend to do with updated files from latest commit?

Keep up the great work.

**Comment by UselessGuru** [comment]
> What do you recommend to do with updated files from latest commit?

They should all be compatible. Use them if you thing they will be benefical to, e.g updated miners or added pools.

**Comment by UselessGuru** [comment]
Any news?

If the problem no longer exists please close this thread.

**Comment by titvs** [comment]
The error didn’t pop up again, so everything is working ok. I’m gonna close the thread.
