### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by ark02** [MultiPoolMiner/MultiPoolMiner#94]
Hey there,

Thanks for the awesome work. Is it possible to add some docs going over things like syntax, things to look out for, lists of options, config file conventions, adding pools/miners? 

Thanks

**Comment by fonyo** [comment]
Yes please, I second the above.

**Comment by jjziets** [comment]
Also please add an explanation on how this works.

**MultiPoolMiner is 12% more profitable than conventional mining!

Miner          btc     usd
-----          ---     ---
MultiPoolMiner 0.01286 22.78671
Reorder-Skein  0.01148 20.34525**


It took me awhile. but now I think that MultiPoolMiner income is an average. Not sure if it is for all time or just 24h.  That Reorder-Skein is the one that is running now at current profitability bast on hashrate, difficulty and value of unit.

**Comment by ark02** [comment]
Also how to do diagnostic/debug things such as forcing re-benchmark of all algorithms, etc.

**Comment by aaronsace** [comment]
Delete the stats files in the stats folder that you wish to reset. 
They are plain text so you can check them.

**Comment by fonyo** [comment]
@aaronsace Do you need help with the documentation? If not, at least let me reconcile all the open and closed issues and create an FAQ for the readme? Let me know whether I should go ahead.

**Comment by aaronsace** [comment]
Oh, yes please. Do you have access to start putting some documentation together?

**Comment by fonyo** [comment]
OK, cool. Yes, I do have access but i will probably run the proposed changes through you regardless. I already started organising and clearing up the issues. Not quite finished yet.
