### ISSUE TITLE
CcminerTpruvot hanging and/or restarting PC

### ISSUE THREAD

**Issue by jesgatt** [MultiPoolMiner/MultiPoolMiner#941]
I am having an issue with the CcminerTpruvot. Most of the time when it runs, especially on the X17 algo, it reboots and/or freezes the PC. I asked a friend of mine that is also running the same MPM version and he also has the same problems. The GPU I am using is the GTX 1080 Ti and he is using Titan XP GPU. Has anyone encountered this problem, if yes, have you managed to solve it? Thanks

**Comment by papacheal** [comment]
I'd check your CPU usage while mining X17. That algorithm has a tendency to peg most entry-level CPUs, especially on multi-CPU rigs.

**Comment by komer83** [comment]
Lower the OC, solved it for me.

**Comment by jesgatt** [comment]
I lowered the core clock to +170MHz and the memory clock to 0MHz but I am still getting the same issues. The driver version I am using is Ver. 23.21.13.8871. I have just one GPU on my rig and the CPU is an Intel Celeron G1840. I am just mining with the GPU only. Thanks

**Comment by komer83** [comment]
I had these crushes at +100, so try to lower to +75.

**Comment by jesgatt** [comment]
Komer83 and what about the memory clock? thanks

**Comment by komer83** [comment]
+75 for both GPU and CPU

**Comment by jesgatt** [comment]
I will set both to +75 and see what will happen. Thanks

**Comment by TVanAusdall** [comment]
I am having the same problem but only on my rig that has 6 1080s, a rig with 6 1060s never has a problem.

None of the cards are overclocked.

Both rigs have the same amount of MLB RAM but the 1080 rig is based on the lowest power Celeron that I could get while the 1060 rig is based on a Ryzen 7 (sp?)

Is it the underpowered MLB CPU causing the trouble?

**Comment by TVanAusdall** [comment]
I tried using the suggested " -i 20" and increased the virtual memory but it really didn't help

**Comment by papacheal** [comment]
What does your CPU usage look like in Task Manager while trying to mine X17? A Celeron is likely to get slammed by 6 x 1080's. I started with a Pentium, then an i3 and ended up with an i7 to keep CPU usage under 100% for X17 specifically. I run 4 x 1080Ti + 1070.

**Comment by JhonJhonny** [comment]
it actually depends from the miner for me, to be honest. i had the same problem without even overclocking (yes i have a cheap celeron) my 4 1080 and tpruvot continue crashing randomly, tried lower the intensity to 19 and it helped, it halved the number of the crashes but sometimes still happened, so i tried using ccminer alexis78 by importing it and even overclocking the cards and using an intensity of 21 i've mined for 2 hour straight (just for testing) and no crashes whatsoever and cpu usage max on 65%
this was just my experience, it may vary

**Comment by 3zero2** [comment]
TPruvot has a tendency to restart my machine quite often, so I ended up disabling it.

**Comment by jesgatt** [comment]
Update: Tested with OC of +75MHz for both GPU and VRAM but it kept hanging and/or rebooting. Reduced the settings to 0 for both and again I got the same problem. It seems that it is not taking care of the OC settings because it exceeds these values by far. Is there a way to edit the TPruvot miner to reduce the GPU allocation % cos it is probably a bit higher than 100%.

**Comment by jesgatt** [comment]
As for the intensity " i xx" I am trying to find what does the number indicate i.e. if it is a % of usage because I opted for i 20 and the #rate went down by 5MHz. thanks
