### ISSUE TITLE
CCMiner TPruvot 2.2.4 x64 build released

### ISSUE THREAD

**Issue by papacheal** [MultiPoolMiner/MultiPoolMiner#942]
I'd create a pull request for this, but am still learning the ropes as a GitHub n00b. Got as far as cloning the repo and making the necessary changes, but couldn't figure out how to translate that into a pull request.

As per notes in https://github.com/tpruvot/ccminer/releases, the updated download URI for CCMinerTPruvot.ps1 would be:

https://github.com/tpruvot/ccminer/releases/download/2.2.4-tpruvot/ccminer-x64-2.2.4-cuda9.7z

Offers improved Lyra2v2 and keccak performance.

**Comment by UselessGuru** [comment]
[Fixed](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/d53be8522764ed206947b7326867c98a0706c596)
