### ISSUE TITLE
Accuracy column seems to be inaccurate. 

### ISSUE THREAD

**Issue by mtbor** [MultiPoolMiner/MultiPoolMiner#943]
Most algorithms the miner has benchmarked are either 80-100% or 1-5%. For instance x17 shows 5% accurate, when I know from experience this algorithm is above 60% for me.  Is the miner dropping a decimal point for some algorithms?

**Comment by papacheal** [comment]
From my experience, assuming you're using the latest release of MPM, it's best to run ResetProfit to zero out all the numbers from all the pools you use and get a clear baseline. The accuracy should then start at 0% for all algorithm-pool combos you've enabled and gradually increase at each interval unit (default 60 seconds). As more intervals pass (at least 24h worth), MPM will gain a better understanding of each algorithm-pool combo price fluctuation and the accuracy displayed will approach its true value. This can take many days (based on interval setting), but MPM only gets smarter over time, so your patience is rewarded. The new "switchingprevention" logic also helps during this period of learning, but it will take some time for MPM to gather info to make smart decisions.

**Comment by mtbor** [comment]
This is from a fresh install, blank stats.  I just noticed that miningpoolhub shows all of the high accuracy ratings, all of the low ones are from zpool.  Seems like a bug of some sort.

**Comment by mtbor** [comment]
I did just run resetprofit, I will report back with results, thanks!

**Comment by papacheal** [comment]
I had the same mixed accuracy issues with some previous versions of MPM. Once I did a clean install of the latest version (nothing was copied from previous version, including benchmarks), everything started from 0.

**Comment by mtbor** [comment]
After resetprofit, everything on miningpoolhub is populated with high accuracy, and everything from zpool is populated with low accuracy...  Again.

**Comment by papacheal** [comment]
And you're 100% sure you didn't copy the /Stats folder over from the previous version? Also, are you adding/removing pools from your /Pools folder? Until a pool is polled, it doesn't gather any stats. You may want to double-check your actual /Stats folder to make sure the non-benchmark files are purged when you run ResetProfit and it isn't some permissions issue.

I'm currently using 2.7.1.3 release (+a few commits released since then) and this solved my similar issue.

**Comment by UselessGuru** [comment]
Highly variable accuracy after clearing the profit stats (e.g. re-install or ResetProfit.bat) is absolutely normal and nothing to worry about.
The numbers will get more stable with each loop as more samples are being collected.
Accuracy solely compares received prices from the pool during current loop with the collected price info from the past.

**Comment by mtbor** [comment]
I believe the issue probably stems from the fact that I am using a different payout coin that bitcoin on zpool and other yiimp pools.  It's comparing my payout of digibytes vs profitability shown as BTC.

If I am correct, this is very unfortunate, because the fees associated with using bitcoin are stupid.

**Comment by UselessGuru** [comment]
> If I am correct, this is very unfortunate, because the fees associated with using bitcoin are stupid.

Nope, Accuracy and payout currency do not interact.

**Comment by mtbor** [comment]
So the miner gets no actual feedback on earnings from the pool API?  It's simply a conversion of estimated profitability vs 24 actual?

**Comment by mtbor** [comment]
I downloaded the compressed v.2.7.1.4, copied my start.bat, and left stats completely alone, the problem persists...  Basically all yiimp pools are rendered useless for me at the moment.

**Comment by mtbor** [comment]
Here's something I pulled from the logs so you can see what I'm looking at:
"ClaymoreNvidia      Ethash                                Benchmarking                 Benchmarking        97%            0.00737 NiceHash
ClaymoreNvidiaSia20 {Ethash, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {97%, 88%} {0.00737, 0.00006} {NiceHash, MiningPoolHub-Siacoin}
ClaymoreNvidiaSia30 {Ethash, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {97%, 88%} {0.00737, 0.00006} {NiceHash, MiningPoolHub-Siacoin}
ClaymoreNvidiaSia40 {Ethash, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {97%, 88%} {0.00737, 0.00006} {NiceHash, MiningPoolHub-Siacoin}
Dstm                Equihash                              Benchmarking                 Benchmarking         1%          521.31000 Zpool
EthminerNvidia      Ethash                                Benchmarking                 Benchmarking        97%            0.00737 NiceHash
Ewbf                Equihash                              Benchmarking                 Benchmarking         1%          521.31000 Zpool
CcminerTpruvot      X17                                   Benchmarking                 Benchmarking         0%            0.01385 Zpool
NsgminerNvidia      NeoScrypt                             Benchmarking                 Benchmarking         1%            0.37100 Zpool
CcminerTpruvot      Equihash                              Benchmarking                 Benchmarking         1%          521.31000 Zpool
CcminerTpruvot      Blakecoin                             Benchmarking                 Benchmarking         1%            0.00005 Zpool
CcminerLyra2RE2     Lyra2RE2                              Benchmarking                 Benchmarking         1%            0.00732 Zpool
CcminerLyra2z       Lyra2z                                Benchmarking                 Benchmarking        90%            0.14009 MiningPoolHub-Zcoin
CcminerNanashi      Lyra2z                                Benchmarking                 Benchmarking        90%            0.14009 MiningPoolHub-Zcoin"

**Comment by UselessGuru** [comment]
> So the miner gets no actual feedback on earnings from the pool API? 

The miner no. It just sends shares (parts of the work to find the next block)
MPM (the 'wrapper' that reads price information from the pool, benchmarks and start the miners) just multiplies the price received from the pool (BTC/h/s) with the hashrate read from the miner. MPM cannot now how much you get credited at the pool.
MPM also does not know how much BTC you're effectively gettinge credited.
In any case you will see much less BTC in your wallet than what MPM projects.

> It's simply a conversion of estimated profitability vs 24 hour actual?

pretty much

**Comment by mtbor** [comment]
Well it's a great added feature...  Hopefully I can get it working.

**Comment by mtbor** [comment]
It seems the accuracy of YIIMP pools slowly creeps up.  Any reason why the accuracy is so immediate on mining pool hub and the YIIMP pool start from 0% and fight their way up?

**Comment by aaronsace** [comment]
v2.7.1.4 is working correctly.
