### ISSUE TITLE
no pools available

### ISSUE THREAD

**Issue by jackson74** [MultiPoolMiner/MultiPoolMiner#944]
when starting up with miningpool hub i get no coin base available, also no pools available with miningpoolhub

**Comment by UselessGuru** [comment]
Then MPM can not access the internet.
Contacting Coinbase it the first web request on each loop. Coinbase usually never fails (in contrast to some pool which are not all that reliable).

Please check your internet & proxy settings.

**Comment by jackson74** [comment]
internet is working can pull up coinbase on the computer.  just started after the windows update last night

**Comment by jackson74** [comment]
i can run all miners on nanopool with no issues, however like MPM with MPH better

**Comment by UselessGuru** [comment]
> internet is working

But powershell is not allowed to access the internet. Do you use a 3rd party firewall?

**Comment by jackson74** [comment]
Nope just the windows one.  All 4 of my rigs are having this issue.

**Comment by aaronsace** [comment]
@jackson74 Post logs.

**Comment by jackson74** [comment]
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is .\Logs\2018-01-05_12-06-01.txt
PS>TerminatingError(Invoke-RestMethod): "
  
     
     
  

Attention Required! | Cloudflare








body{margin:0;padding:0}







  
    Please enable cookies.
    
      
        One more step
        Please complete the security check to access api.coinbase.com
      
      
      
        
          
            
            
              
                
  
  
  
    
      
        
      
      
        
        
      
    
  


              
            

            
              
              
                
              
              
            
          
        
      

      
        
          
            Why do I have to complete a CAPTCHA?
            
            Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
          

          
            What can I do to prevent this in the future?
            

            If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.

            If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.
            
          
        
      
      

      
  
    Cloudflare Ray ID: 3d88b67caf65211a
    &bull;
    Your IP: 65.153.79.66
    &bull;
    Performance &amp; security by Cloudflare
    
  



    
  

  
  window._cf_translation = {};
  
  




"
WARNING: Coinbase is down.
PS>TerminatingError(Invoke-RestMethod): "
  
     
     
  

Attention Required! | Cloudflare








body{margin:0;padding:0}







  
    Please enable cookies.
    
      
        One more step
        Please complete the security check to access miningpoolhub.com
      
      
      
        
          
            
            
              
                
  
  
  
    
      
        
      
      
        
        
      
    
  


              
            

            
              
              
                
              
              
            
          
        
      

      
        
          
            Why do I have to complete a CAPTCHA?
            
            Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
          

          
            What can I do to prevent this in the future?
            

            If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.

            If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.
            
          
        
      
      

      
  
    Cloudflare Ray ID: 3d88b68143ff77e4
    &bull;
    Your IP: 65.153.79.66
    &bull;
    Performance &amp; security by Cloudflare
    
  



    
  

  
  window._cf_translation = {};
  
  




"
WARNING: Pool API (MiningPoolHub) has failed.
PS>TerminatingError(Invoke-RestMethod): "
  
     
     
  

Attention Required! | Cloudflare








body{margin:0;padding:0}







  
    Please enable cookies.
    
      
        One more step
        Please complete the security check to access miningpoolhub.com
      
      
      
        
          
            
            
              
                
  
  
  
    
      
        
      
      
        
        
      
    
  


              
            

            
              
              
                
              
              
            
          
        
      

      
        
          
            Why do I have to complete a CAPTCHA?
            
            Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
          

          
            What can I do to prevent this in the future?
            

            If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.

            If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.
            
          
        
      
      

      
  
    Cloudflare Ray ID: 3d88b682745b77e4
    &bull;
    Your IP: 65.153.79.66
    &bull;
    Performance &amp; security by Cloudflare
    
  



    
  

  
  window._cf_translation = {};
  
  




"
WARNING: Pool API (MiningPoolHubCoins) has failed.
WARNING: No pools available.

**Comment by jackson74** [comment]
Transcript started, output file is .\Logs\2018-01-05_12-06-01.txt
PS>TerminatingError(Invoke-RestMethod): "
WARNING: Coinbase is down.
PS>TerminatingError(Invoke-RestMethod): "
  
     WARNING: Pool API (MiningPoolHub) has failed.
PS>TerminatingError(Invoke-RestMethod): "
  
     
     
  

Attention Required! | Cloudflare








body{margin:0;padding:0}







  
    Please enable cookies.
     
  

Attention Required! | Cloudflare








body{margin:0;padding:0}








  
     
     
  

Attention Required! | Cloudflare








body{margin:0;padding:0}

**Comment by aaronsace** [comment]
Enable cookies?

**Comment by UselessGuru** [comment]
> What is the logic like for subsequent checks?

From [readme](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/README.md):
_-watchdog Include this command to enable the watchdog feature which detects and handles miner and other related failures. It works on a unified interval that is defaulted to 60 seconds. Watchdog timers expire if three of those intervals pass without being kicked. There are three stages as to what action is taken when watchdog timers expire and is determined by the number of related expired timers.

Stage 1: when 1 timer expires relating to one miner/algorithm combination, the one miner/algorithm combination is kicked
Stage 2: when 2 timers expire relating to one miner file, the one miner file is kicked
Stage 3: when 3 timers expire relating to one pool, the pool is kicked
Watchdog timers reset after three times the number of seconds it takes to get to stage 3._

When internet stops (like in your case), then MPM starts disabling pools ( because they were not kicked).

**Comment by mmcmullen** [comment]
> When internet stops (like in your case)

I noted that in my case, the internet never actually goes down - it has some hiccups, it might drop a request here and there, but it's online the entire time. I find it hard to accept that ONLY MPM is failing 3 checks, 60 seconds apart, while the miners themselves and the rest of the PC are still 100% connected and having a fine time of it.

There's some sort of resilience issue. I'm sure the answer will be "fix your internet" which is a huge cop out, but I understand if they wouldn't want to put time into reviewing that logic to figure out why some of us see this behavior.

**Comment by aaronsace** [comment]
Doesn't have to be anything wrong with the internet connection. 

Upload logs please.

**Comment by haxshaan** [comment]
I am having exactly same issue. I can ping each pool addresses manually but the start.bat process can't connect to any pool. Error: _WARNING: Pool API (Hashrefinery) has failed_
Together with other pool names. 
One more confusion: I added -poolname argument but mph still checks for every pool apis.

**Comment by aaronsace** [comment]
Post a new issue with logs.
