### ISSUE TITLE
X17 algo using NVIDIA-TPruvot fails

### ISSUE THREAD

**Issue by biesbjerg** [MultiPoolMiner/MultiPoolMiner#946]
According to the output in the main window, `NVIDIA-TPruvot` fails. Howeve, as far as I can see, the miner is running properly without errors (no errors in window, pool shows my worker submitting `X17`-shares).

```
   Status: Running

 Speed Active                      Launched Command
 ----- ------                      -------- -------
0  H/s 00 Days 00 Hours 01 Minutes 2 Times  Bin\NeoScrypt-Palgin\hsrminer_neoscrypt.exe -o stratum+tcp://neoscrypt.mine.zpool.ca:4233 -u 39yqcnWjcH5aU2m34Dx
                                            D9Nwx5kQzww2wsP -p miner1,c=BTC

   Status: Failed

     Speed Active                      Launched Command
     ----- ------                      -------- -------
37,23 MH/s 00 Days 00 Hours 04 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a x17 -o stratum+tcp://x17.mine.zpool.ca:3737 -u 39yqcnWjcH5aU2m34DxD9Nw
                                                x5kQzww2wsP -p miner1,c=BTC --submit-stale



Miner          Pool  Algorithm Watchdog Timer
-----          ----  --------- --------------
CcminerTpruvot Zpool X17          279 Seconds
PalginNvidia   Zpool NeoScrypt      0 Seconds
```

Any idea what's going on?

[2018-01-05_21-13-37.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1607837/2018-01-05_21-13-37.txt)

**Comment by aaronsace** [comment]
Speed is nowhere near the benchmark: 
`WARNING: Stat file (CcminerTpruvot_X17_HashRate) was not updated because the value (37229060) is outside fault tolerance (43311721 ... 55316133).`

Reset that one benchmark by deleting it in the 'stats' folder.

**Comment by biesbjerg** [comment]
Would an abnormal hashrate result in a `Status: Failed`?

Original benchmarks is less than 24 hours old, so not sure why that would happen. Deleted file and are benchmarking the miner/algo combo again. Will report back.

**Comment by aaronsace** [comment]
The warn itself is fine; the issue is if it continues and causes the watchdog to kick it. 

Either fix any heat/oc issues with the cards and/or turn watchdog off.

**Comment by biesbjerg** [comment]
Aha. So it might be because the GPUs are throttling because of heat issues?

Maybe it would make sense to change the warning to reflect that and/or tell the user to reset the stats file if he changed OC or added/removed a GPU?

**Comment by UselessGuru** [comment]
> Aha. So it might be because the GPUs are throttling because of heat issues?

Very likely, especially if you are running the same algo continuously. When benchmarking it will only run for a short time therefor not generating as much heat.
You could also have been executing something that generated high GPU usage affecting the hashrate.

**Comment by papacheal** [comment]
I make it a habit that when I clear out my benchmarks with ResetBenchmarks, I also set the interval to 300 temporarily to guarantee at least a 5 minute run on the baseline benchmarks. This sets the initial hashrate values to be closer to the actual average hash rate for the algorithm/miner combo and allows the miners to "warm up" first (or "cool down" in the case of Excavator which starts too high). Once the benchmarks are done, I switch the interval back to default. 

Just a thought.

**Comment by UselessGuru** [comment]
> I also set the interval to 300 temporarily to guarantee at least a 5 minute run on the baseline benchmarks

Suggestion to the devs: Add a new command line option $BenchmarkInterval. If set use this during benchmark.

**Comment by biesbjerg** [comment]
@papacheal Good idea, I'll give it a go!

**Comment by gak45** [comment]
Better still would be BenchmarkInterval AND a watchdog interval AND a CheckPoolStats interval (as HR for example pukes out with an api call every 60sec). That way we could tweak each setting individually instead of an 'one for all settings' interval.

**Comment by nichenke** [comment]
Is there a way to get logs from the miners themselves? Diagnosing historic watchdog failures for miners is a bit difficult -- hard to know if pool went away, stalled watchdog (no shares accepted, stratum pushed difficulty too high, etc), or miner failure w/OC issues.

**Comment by platinum4** [comment]
This is a similar problem in Excavator re: BenchmarkInterval being too short.
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/971

**Comment by Braintelligence** [comment]
@aaronsace I've got a question: Would it be possible to not have watchdog kill the miner, but instead adapt to the new hash rate and perhaps choose another algo due to the maybe less income generated this way?

**Comment by UselessGuru** [comment]
> but instead adapt to the new hash rate and perhaps choose another algo due to the maybe less income generated this way

It works already like this. MPM updates the stats for the running miner on each loop as long as the hash rate is within limits (yello warning). It will also recalculate the projected earnings based on the current hash rate.

If the hash rate is constantly out of limit then watchdog kicks the miner.

Some algos/miner combination are notorious for unreliable hash rate reports, e.g. X17 always reports hash rate too high during benchmark because the time for the benchmark loop is on the short side.

**Comment by Braintelligence** [comment]
@UselessGuru My point was that maybe watchdog tolerance could be adjusted by a factor? Like -watchdogTolerance 5 (5 times bigger interval of tolerance)

**Comment by UselessGuru** [comment]
Enhancements are currently being implemented which should lead to faster and more stable hash rate detection.
