### ISSUE TITLE
release notes seem to be lagging behind a bit

### ISSUE THREAD

**Issue by i3luefire** [MultiPoolMiner/MultiPoolMiner#951]
![image](https://user-images.githubusercontent.com/3527233/34633597-b66e5242-f242-11e7-8e60-27298646f53a.png)
these release note have not been updated for quite a while.

**Comment by i3luefire** [comment]
Also, why is there no readme.txt file in the release zips?

**Comment by aaronsace** [comment]
I don't update the date for minor fixes and miner updates. The up-to-date readme is on GitHub and the website and is maintained by Fonyo.
