### ISSUE TITLE
Change log for versions?

### ISSUE THREAD

**Issue by gak45** [MultiPoolMiner/MultiPoolMiner#952]
Any chance of change log included in each minor revision? For example going from 2.7.1.1 to 2.7.1.2 was massive... but no idea if its worth dl'ing .1.4 and re-benching IF a rig is humming along fine on .1.2 or .1.3! Kinda confusing as the only details given is 'changes from 0.2" list.

Also as a note it is hard to keep up with changes / latest releases when the latest shows its been out for 21 days but really is only a day or two old. For peeps who just log in once a week to check if something _new_ is released its a bit tedious to see if anything really _is_ new or the same without checking installed version first.

**Comment by i3luefire** [comment]
I second that

**Comment by aaronsace** [comment]
No, minor revisions will not be documented.
