### ISSUE TITLE
Type includes NVIDIA when only AMD is called in BAT file

### ISSUE THREAD

**Issue by DivideOverflow** [MultiPoolMiner/MultiPoolMiner#953]
Although only -type AMD is set in the BAT file, the program includes Type:  {AMD, NVIDIA} and tries to D/L NVIDIA based miners.

![image](https://user-images.githubusercontent.com/35158456/34636199-15c23264-f251-11e7-9880-964124a6ca00.png)

**Comment by fonyo** [comment]
That just indicates those miners support both types of cards. This is normal behaviour.
