### ISSUE TITLE
NVIDIA hsrminer 1.0.1 for Neoscrypt algo by palgin & alexkap - Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club

### ISSUE THREAD

**Issue by lukiifaz** [MultiPoolMiner/MultiPoolMiner#955]
`Bin\NeoScrypt-Palgin\hsrminer_neoscrypt.exe -o stratum+tcp://neoscrypt.mine.blockmunch.club:4233 -u 17iBXKtaUCESY5YpgRZvB8rk8dc6NHBusR -p legion,c=BTC`

I```
NFO : [07:53:35] : Securing devfee mining...
 INFO : [07:53:36] : Dev_Main OK.
 INFO : [07:53:36] : Dev_Backup OK.
 INFO : [07:53:36] : Dev pools checked, at least 1 accessible, continue...
 INFO : [07:53:36] : POOL: stratum+tcp://neoscrypt.mine.blockmunch.club:4233
 INFO : [07:53:36] : Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club
 INFO : [07:53:36] : Next connection attempt in 10 seconds
 INFO : [07:53:36] : Checking for NVML...
 INFO : [07:53:36] : NVML monitoring enabled, continue...
 INFO : [07:53:36] : 1 GPU found/specified, initializing miner...
 INFO : [07:53:46] : Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club
 INFO : [07:53:46] : Next connection attempt in 10 seconds
 INFO : [07:53:56] : Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club
 INFO : [07:53:56] : Next connection attempt in 10 seconds
 INFO : [07:54:06] : Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club
 INFO : [07:54:06] : Next connection attempt in 10 seconds
 INFO : [07:54:16] : Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club
 INFO : [07:54:16] : Next connection attempt in 10 seconds
 INFO : [07:54:26] : Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club
 INFO : [07:54:26] : Next connection attempt in 10 seconds
 INFO : [07:54:36] : Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club
 INFO : [07:54:36] : Next connection attempt in 10 seconds
 INFO : [07:54:46] : Connection failed: Could not resolve host: neoscrypt.mine.blockmunch.club
 INFO : [07:54:46] : Next connection attempt in 10 seconds
```

**Comment by UselessGuru** [comment]
Fixed in [Fix HOST](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/793b290dec2b5f79c59f69b4e236ca717fc7d6e6)

If OK then please close this issue. Thanks!

**Comment by UselessGuru** [comment]
Also see https://github.com/MultiPoolMiner/MultiPoolMiner/commit/26bee6cc63c440ff6e70a6642d135023a2670d78
