### ISSUE TITLE
Really trying to be involved guys. Pictures and info RE: #866

### ISSUE THREAD

**Issue by cmbconcretefire** [MultiPoolMiner/MultiPoolMiner#956]
Regarding Nvidia GPU's dropping out. Some ppl have the problem, others do not. After a TON of research, I am convinced only certain Nvidia GPU models are afflicted. YES, I concede that sometimes a GPU will drop out because of too high of an OC. People not knowing what they're doing, etc. YES, it happens. 

I am trying to say that for me, and I'm sure many others, it does not matter what we do.....a GPU will drop out, even if it's not OC'd at all. With Fresh Drivers installed. Doing everything 100% correct. 

Some of us are afflicted with this. And I am closing in on finding an answer but I need help. I want to post 2 pics. 1 pic actually shows GPU 0 is actually "lost" (compare to usage of GPU 2, etc) and 1 pic I spent all night last night looking for. It seems to be "the code" (or at least the basic heart of the code) to fix when Nvidia GPU's drop out. And then, I'm going to post the link to the code I found, so you can look back at upper levels and figure stuff out. 
![capture](https://user-images.githubusercontent.com/23691069/34638200-cf3f8e24-f294-11e7-93cd-841a6bb87c52.PNG)
![capture22](https://user-images.githubusercontent.com/23691069/34638204-d6b6e148-f294-11e7-9909-8dd3bac60a0a.PNG)

https://github.com/sebeksd/NiceHashMinerLegacy/blob/85049a85b6940b774da1afbab354c193e2d440ce/NiceHashMiner/OnGPUsLost.bat

**Comment by UselessGuru** [comment]
Are you forcing your cards to use P0 state?

http://cryptomining-blog.com/tag/p2-power-state-in-compute/

During computing (mining) Nvidia drops memory clock to P-State 2 (e.g. for my GTX 1080 11GHz -> 10GHz). When exiting a miner or during some specific operations the driver will spike to P-state 0 and therefor increase mem clock to 11GHz.

Now here is what happens to many people:
During benchmark the GPU operates in P-State 2. They will crank up mem OC to the roof. All seems stable.
Until some call requests P-State 0. This will add an extra 500MHz (in my above case) to the already OCd memory -> bang, dead GPU

The solution: [Use NvidiaDriverInspector to nail the GPU to P-State 2](https://www.reddit.com/r/gpumining/comments/6rhfnv/how_do_you_force_p0_state_on_nvidia_gpus/) (Do NOT use nvidia-smi.exe, this will NOT work on Win10!)

Important: Stop all mining BEFORE applying this setting or it WILL NOT stick! 
Note: You will have to re-apply this setting after each driver update

**Comment by JhonJhonny** [comment]
What do you mean by nail the gpu to p-state 2, to keep it in the p2 state and not forcing it in to p0? (Not a native English speaker so I don't understand everything)

**Comment by UselessGuru** [comment]
Typo, I meant P-State 0. Force it to p0 for best performance. Working nicely here.

**Comment by cmbconcretefire** [comment]
@UselessGuru . yes, in the past week or so I used NvidiaDriverInspector to force P-State 0 on both my rigs. 

And the way you explained the problem closely resembles what I have learned as well. So, it seems we're in agreement. However, and this is critical......my GPU's have been dropping out randomly for MONTHS now, no matter what I do. No OC, Restart PC, make sure No OC, fire up (xyz miner) and everything seems fine until I have to manually check to see if they are all running. 

What I am trying to accomplish with this 'helpful addition' to MPM is to implement the script that I posted so that if a NVIDIA gpu is lost, the script kicks in and fires that GPU back to life. Immediately. Without shutting down the whole rig. Then when you wake up in the morning, you can simply check the "logs" of the script, and see if one of the gpus' was lost, at what time, and how many times it was repaired. 

Through that info, hopefully a pattern emerges where you can tell which GPU is dropping, what it was mining, etc....and REALLY fix the problem. It's a band-aid, but it does work on NHML, and I see no reason why we can't implement it to MPM as well. PS......the screenie I took with GPU 0 lost - was from yesterday morning and I can assure you those cards have been in PS-0 for over a week now. It still dropped. 

Point being, even if it's in PS 2 or PS 0, sometimes they just drop out, and a band aid to get them cranked back up immediately could not be a "neat" feature, but an actual useful one as well. Hope we agree there too.

**Comment by UselessGuru** [comment]
> Hope we agree there too.

Not really. If your hardware has issues, then this is a general problem that need to be adressed. I don't believe in 'hacking' around the issue in such a manner.

Have you tried updating the BIOS of your cards. There were issues with GTX1070:
https://www.kitguru.net/components/graphic-cards/matthew-wilson/firmware-updates-begin-rolling-out-to-fix-gtx-1070-memory-issues-2/

**Comment by cmbconcretefire** [comment]
My bios is confirmed to be the correct version for my cards. All 6 = Micron Memory.  The fixed bios. 
GV-N1070WF2OC-8GD | 2017-02-08 00:00:00 | 86.04.50.00.AB

If I'm not OC, and PS = 0 and it mines fine for days at a time without any GPU's dropping out, and then for some random reason, one of them drops out, the solution I'm proposing could be looked at as a 'hack.' I don't see it that way. That 'hack' provides logs......so you can get more info to diagnose the problem and fix the REAL issue, instead of guessing at a million different things it could be. The logs provide facts, and eliminates a whole lot of guess work.

**Comment by thericeking** [comment]
It seems like I learned something from here that I didn't know however, in the link for Nvidia inspector the suggestion is the Reddit post is to turn it off. So my question is... Turn P0 on or off using Nvidia inspector? I am Googleing what the heck is P0 state.

**Comment by thericeking** [comment]
Can I keep max power down to %70 on my 1070 and still benefit from P0 state or do I need to set power to %100+ or more? Please someone confirm. I'm trying to save electricity and see if I can get away with this P0 state thing. Thank you

**Comment by UselessGuru** [comment]
> Can I keep max power down to %70 

Yes

**Comment by fonyo** [comment]
You are rigorously chasing this @cmbconcretefire which is not a problem at all, I just wanted to ask whether you tried different risers and swapping power cables. 10 out of 10 times, this solves the issues for me. Could also be the PCI-E slot misbehaving on the motherboard. Some of them are too loose and the pins won't connect when thermodynamics kick in.

**Comment by UselessGuru** [comment]
> you tried different risers and swapping power cables.

Also try reducing PCI-E speed in BIOS from 3x to 1x

**Comment by borzaka** [comment]
There is a more sophisticated [OnGPUsLost.bat](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/OnGPUsLost.bat) from NiceHashMinerLegacy with 2 options:
1. restart your entire rig
2. use nvidiaInspector to restart display drivers

P0 power state for Pascal (10 series) GPUs makes no difference:
[Question: Is the NVIDIA P0 State worth enabling?](https://github.com/nicehash/NiceHashMinerLegacy/issues/25)

**Comment by UselessGuru** [comment]
> P0 power state for Pascal (10 series) GPUs makes no difference:

Wrong. It has a big effect cause memory is faster. Just make sure it is really in P0 state.
Try for yourself.

**Comment by Renegade5399** [comment]
Force P2 state should ALWAYS be off for maximum mining performance.

See pic for what to turn Off in NVPI.

[https://imgur.com/qDI3ivv](url)
