### ISSUE TITLE
remove-job error

### ISSUE THREAD

**Issue by FPGA-Computer** [MultiPoolMiner/MultiPoolMiner#959]
Found this in my log file:
Remove-Job : The command cannot remove the job with the job ID 3 because the job is not finished. To remove the job, first stop the job, or use the Force parameter. Parameter name: Job
At MultiPoolMiner\Include.psm1:294 char:12
+     $Job | Remove-Job

That line can be changed to the following to remove further error messages:
$Job | Remove-Job -force

**Comment by aaronsace** [comment]
I think you're using an old version.
