### ISSUE TITLE
DDOS/Pool down miner ideal

### ISSUE THREAD

**Issue by jjziets** [MultiPoolMiner/MultiPoolMiner#96]
With the DDOS on miningpoolhub, it would be great if your helper can detect that the miner is ideal and try other algo.

**Comment by aaronsace** [comment]
I will implement failover pools to prevent this.

**Comment by jjziets** [comment]
Miningpoolhub.com has Europe US and Asia servers. First step would be to have them as fall over pools before switching to other algorithms.

**Comment by imrecsoka** [comment]
Yeh i saw huge attack news again for Europe.

**Comment by jjziets** [comment]
Not sure if this is a good idea but safe-hub.miningpoolhub.com: could be a good fail over for the coins that dont have other servers
