### ISSUE TITLE
No zpool

### ISSUE THREAD

**Issue by Imaminer** [MultiPoolMiner/MultiPoolMiner#963]
Trying zpool only.
Cannot connect to zpool api
latest version of MPM
Is this a powershell permissions thing? I did have to load the new version 6
thanks

**Comment by Warkdev** [comment]
No, it's zpool api issues. It doesn't return anything.

**Comment by RANGERBEE** [comment]
yeah i keep getting the api returns null also...

**Comment by aaronsace** [comment]
https://twitter.com/_zpool_?ref_src=twsrc%5Etfw&ref_url=http%3A%2F%2Fzpool.ca%2F
