### ISSUE TITLE
Wrapper not working if MPM is run from a path containing spaces

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#969]
Can anyone confirm this?

**Comment by BeardlessDuck** [comment]
Wow thanks!  I think this was my problem.  I couldn't get 2.7.1.4 working with ccminer/skein after previously using 2.7.1.2 and putting MPM in a folder in the root of my C: drive worked!

**Comment by UselessGuru** [comment]
@BeardlessDuck 

Thank you -root cause found. I'll try to fix if.

**Comment by UselessGuru** [comment]
@BeardlessDuck

[Fix Wrapper.ps1 so allows spaces in path](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/00f3c8feaa17b5d8215400d808f92cce4da5f61c)
Can you see if this fixes it? It does for me :-)
