### ISSUE TITLE
Excavator can't reach the maximum hashrate in 1 minute.

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#971]
1 minute is not enough to Excavator to reach some algorithms maximum hashrate during benchmarks.

I don't know why, but Excavator is very slow to react to realtime overclocks as well.

**Comment by UselessGuru** [comment]
> I don't know why

MPM will adjust hash rates over time. There is no need to worry.

Other miners/algos show the same behaviour. 
However it is NOT the miner which gets faster. It is just the hashrate being reported that is increasing over time. The miner will internally operate at a more or less constant rate.

**Comment by nichenke** [comment]
This is mostly true :trollface: , however for slow aglorithms or slow stratum difficulty ramps, the low hash rate can 'stick' and that miner/algo will be 'slow' to ever be chosen by MPM for a real production run. x17 on Nvidia of late is a good example.

I'm finding better luck running MPM with `-interval 180` for the initial benchmarks, as that allows the miners to ramp up a bit more. It is always worth a sanity check against Whattomine calculators for the expected hash rates as well, making sure the achieved rates make sense. 

MPM isn't magic... still need to put in the hard work pruning down algos, tweaking settings (hello neoscrypt difficulty caps to avoid false positive watchdogs), etc.

**Comment by borzaka** [comment]
Thanks for the heads up about the `-interval`, I will definitely use this.

**Comment by UselessGuru** [comment]
@nichenke 

To my understanding difficulty and hash rate are not related.
Hash rate is more or less the constant on any given miner.

But: the higher the difficulty the more hashes it takes until the miner finds a valid share;
some miners only report hash rate when they find a valid share.
