### ISSUE TITLE
Please any help for this problem.  Thanks in advance if anyone looks this over. 

### ISSUE THREAD

**Issue by davidbbb** [MultiPoolMiner/MultiPoolMiner#972]
**********************
PowerShell transcript start
Start time: 20180107110218
Username: XXXXXXXX\XXXXXXX
RunAs User: XXXXXXX\XXXXXXX
Configuration Name: 
Machine: XXXXXXXXX (Microsoft Windows NT 6.2.9200.0)
Host Application: C:\Program Files\PowerShell\6.0.0-rc.2\pwsh.dll -noexit -executionpolicy bypass -windowstyle maximized -command & .\multipoolminer.ps1 -username XXXXXXX -workername XXXXXXX -region us -currency usd -type nvidia,cpu -poolname miningpoolhub -algorithm cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,siaclaymore -donate 10 -watchdog -switchingprevention 2
Process ID: 7316
PSVersion: 6.0.0-rc.2
PSEdition: Core
GitCommitId: v6.0.0-rc.2
OS: Microsoft Windows 10.0.17025 
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is .\Logs\2018-01-07_11-02-18.txt
Get-Content : Cannot find path 'C:\Users\XXXXXXXXXX\Desktop\New folder (2)\Regions.txt' because it does not exist.
At C:\Users\XXXXXXXXXX\Desktop\New folder (2)\Include.psm1:399 char:16
+     $Regions = Get-Content "Regions.txt" | ConvertFrom-Json
+                ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\rumpls...(2)\Regions.txt:String) [Get-Content], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
Get-Content : Cannot find path 'C:\Users\XXXXXXXXX\Desktop\New folder (2)\Regions.txt' because it does not exist.
At C:\Users\XXXXXXXXX\Desktop\New folder (2)\Include.psm1:399 char:16
+     $Regions = Get-Content "Regions.txt" | ConvertFrom-Json
+                ~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by hapklaar** [comment]
You're missing files. Redownload and extract the mulipoolminer zip, then try again.

**Comment by davidbbb** [comment]
Thanks hapklaar.  Now the cmd window isn't full of red script!  :) Just waiting for a pool to be available and I'll be mining.
