### ISSUE TITLE
Stop.bat

### ISSUE THREAD

**Issue by BioRunner** [MultiPoolMiner/MultiPoolMiner#973]
Hello,
I have a question that maybe this community can help me with. I did some searching on this and did not really find a straight forward answer.

Can we get a Stop.bat file to cleanly stop MPM? I would like to run MPM from Task Scheduler in Windows and it would be nice to just schedule a task to stop (Stop.bat) MPM cleanly. I'm not sure how to stop MPM through Task Scheduler now, except for killing the command process, which I'm not totally clear on how I would kill the correct command window process. And I don't want residual miners running after the main MPM window has been closed.

Thank you for any help!

**Comment by RANGERBEE** [comment]
Im a nix guy, but the way I would do it is find the PID with grep and kill -9 it all from a .sh script.  ;)

Thats the logic anyway...

**Comment by aaronsace** [comment]
There will no longer be residual miners: c768136c5caf893cba9b8a1c02b7f2040186a763
