### ISSUE TITLE
Mining on 1 GPU on multi-GPU rig

### ISSUE THREAD

**Issue by xGravy** [MultiPoolMiner/MultiPoolMiner#976]
Hello.
I cannot find out how, if possible, to use MPM to mine from only 1 of my GPU's while leaving the other GPU available for use.
eg. gaming while mining.
When the computer is not in use, all GPU's will be used, but that's the easy part. ;)

If anyone knows how to do this with MPM please let me know.
I can do it with Awesome Miner but I would rather use MPM

Cheers

**Comment by grantemsley** [comment]
It's not an available feature yet.

**Comment by xGravy** [comment]
darn.
ok thank you very much for the reply

**Comment by evanvz** [comment]
Hi xGavy

Maybe disbale the one card and run your benchmark.

Create a copy of your MPM folder and re-benchmark all your cards.

Switch between the two as needed.

Just an idea. Not sure if it willl work.

**Comment by UselessGuru** [comment]
You could edit all miner files manually to define only the GPU's you want. This requires understanding of the parameters for each miner type, e.g. Ccminer, Claymore etc.

For the Ccminer type you need to add ' -d 1,2,3' (if you were to ignore card 0, but want to mine with cards 1,2,3 only) to the line that looks like 

` Arguments = "-a $_ -o $($Pools.(Get-Algorithm $_).Protocol)://$($Pools.(Get-Algorithm $_).Host):$($Pools.(Get-Algorithm $_).Port) -u $($Pools.(Get-Algorithm $_).User) -p $($Pools.(Get-Algorithm $_).Pass)$($Commands.$_)"`

to look like  

`Arguments = "-a $_ -o $($Pools.(Get-Algorithm $_).Protocol)://$($Pools.(Get-Algorithm $_).Host):$($Pools.(Get-Algorithm $_).Port) -u $($Pools.(Get-Algorithm $_).User) -p $($Pools.(Get-Algorithm $_).Pass)$($Commands.$_) -d 1,2,3"`

Note the spaces!

**Comment by UselessGuru** [comment]
[See this](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1237)
