### ISSUE TITLE
WARNING:Stat file...

### ISSUE THREAD

**Issue by d0n4ald** [MultiPoolMiner/MultiPoolMiner#977]
Whats the meaning of this error? Do i have to take action? So far it's still mining from dtsm

![untitled14](https://user-images.githubusercontent.com/34756410/34655705-1867faf8-f3dc-11e7-8075-4f36a0458bb0.jpg)

**Comment by UselessGuru** [comment]
See https://github.com/MultiPoolMiner/MultiPoolMiner/issues/932

You could apply https://github.com/MultiPoolMiner/MultiPoolMiner/commit/daad24605f6576ec4f7f76bdbc6b30e6c5d7f0d6#diff-3a447b104ea55289de9757e0588b9862
