### ISSUE TITLE
MiningPoolHub pool broken

### ISSUE THREAD

**Issue by grantemsley** [MultiPoolMiner/MultiPoolMiner#982]
@UselessGuru #957 broke MiningPoolHub. MiningPoolHubCoins still works though.

That API doesn't return a hashrate property, so all the pools get filtered out of it.

**Comment by UselessGuru** [comment]
Reverted with
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/e0fbb873f928bac5c9ffa4fb2372d508221aa898
