### ISSUE TITLE
MPM switches off of fastest skein miner randomly

### ISSUE THREAD

**Issue by Powaful3000** [MultiPoolMiner/MultiPoolMiner#984]
For me ccminer sp has 720MH/s and NVIDIA-TPruvot has 550MH/s but MPM always switches off of sp to use NVIDIA-TPruvot.  If I disable skein in NVIDIA-TPruvot it stays on sp, however.

This happens on al three of my boxes.

**Comment by UselessGuru** [comment]
Turn watchdog off, that should help.

> sp has 720MH/s and NVIDIA-TPruvot has 550MH/

Have you verified the it is lso that much faster at the pool?

**Comment by Powaful3000** [comment]
It shows sp faster on the pool aswell

**Comment by hiewliwen** [comment]
It is something to do with CcminerSP's hashrate reporting. It isn't using API and MPM have to use a PS wrapper. At times, CcminerSP does not output its hash and MPM think it hung and terminate.

**Comment by UselessGuru** [comment]
Can you try with this:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/3603eef3c8d9ae725a919a1510172f2d78450111

Please close if this fixes your issue.

**Comment by hiewliwen** [comment]
I confirm that it works for me.

**Comment by UselessGuru** [comment]
Does this issue still exist?
