### ISSUE TITLE
Start-MiningPoolHub.bat

### ISSUE THREAD

**Issue by d0n4ald** [MultiPoolMiner/MultiPoolMiner#985]
I noticed this is new in v2.7.1.4, wheras it was in 2.7.1.1
-switchingprevention 2

what does it do? do i need to change anything?

**Comment by UselessGuru** [comment]
leave it as it is. -switchingprevention 2 is fine

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/877
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/968
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/831

**Comment by d0n4ald** [comment]
thanks
