### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by tomasfil** [MultiPoolMiner/MultiPoolMiner#988]
[2018-01-08_20-25-02.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1615867/2018-01-08_20-25-02.txt)
Why is that? Was working fine, but suddenly this started to happen. Tried to redownload, but nothing. After this error, it goes through and keep working.

**Comment by UselessGuru** [comment]
Looks like broken stats

Try this:
- stop MPM
- rename stats folder to some other name
- start MPM
Problem gone? That would prove my suspicion :-)

**Comment by tomasfil** [comment]
For some reason MPM crashes my rig, doesnt matter which miner it is and then they become corrupt. Its not problem of my rig, xmr-stak on another pool runs even week without problem. I want to switch to MPM, but it crashes like in 5 mins to 12 hours max. I cant find anything in logs. In logs it start new miner and then its over. 
I have rig with 3x vega 64

**Comment by UselessGuru** [comment]
Are you overclocking? Reset everything to stock first. You MAY belive your OCd system is stable, but maybe it isn't :-)
MPM runs other algos apart from xmr-stak that are more susceptible towards a weak system (e.g. thermal problem, weak power supply, overclocking).

[Try using the latest build](https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip). This one writes a more detailed log file that lists all miner starts including parameters.

Run the latest run miner standalone and it will most likely crash your system!

**Comment by tomasfil** [comment]
Well but strangely, in MPM bin I did set fierce (xmr-stak) amd settings to same I was running and even like that it crashes. It shouldnt be problem with my HW.

I am trying lower overclock now. Then if it crashes again, I will try the latest build.

**Comment by tomasfil** [comment]
![vystrizek](https://user-images.githubusercontent.com/34779382/34742057-2acf13b6-f585-11e7-8e3d-9fef41debcf6.PNG)
Heh lol, on my gaming PC. I quess this one is  broken. (The latest build you sent me and GTX 970)
