### ISSUE TITLE
Download only option 

### ISSUE THREAD

**Issue by Nickfost** [MultiPoolMiner/MultiPoolMiner#990]
please add an option to download binaries and not mine

**Comment by aaronsace** [comment]
Why?

**Comment by Nickfost** [comment]
People who are bandwidth impaired (me) have a hard time getting all the
binaries.



Nick Foster
-----------------
me@nickfost.com

**Comment by UselessGuru** [comment]
> People who are bandwidth impaired (me) have a hard time getting all the
binaries.

Feel free to download it on another machine and copy the bin folder. But you WILL NEED all miners for profitable mining. If you know of some miners you don't want to mine with then delete them from the miner directory.

**Comment by Nickfost** [comment]
I don’t understand the reasoning for closing the issue. It would be really nice to have a download only feature so I can download the binaries on a system that’s not a miner.



Nick Foster
-----------------
me@nickfost.com

**Comment by aaronsace** [comment]
@Nickfost I don't understand why you would have issues downloading the miners. The downloader is quite robust and wont give up until it succeeds in acquiring the miners; all while it continues mining.

**Comment by Nickfost** [comment]
Takes about 6 days to download all the miners. GitHub kills http connections once they reach a certain age.


If I were to use a separate system that had a better connection i wouldn’t want it to mine.



Nick Foster
-----------------
me@nickfost.com

**Comment by garyng** [comment]
I have the same problem too... It keeps on download and retry and download and retry...
So instead I edited the `Downloader` script to dump all of the downloads links, then manually download with `aria2c` and unzip with `7z`

![image](https://user-images.githubusercontent.com/4453664/34912606-7ecbbba6-f920-11e7-8359-1a23e6306a35.png)
