### ISSUE TITLE
MPM failed to connect to miner (PalginNvidia)

### ISSUE THREAD

**Issue by FruitFace** [MultiPoolMiner/MultiPoolMiner#991]
The new PalginNvidia miner does run, and accepts shares, etc, but MPM gives the error in the title.  Eventually, the watchdog fails it out.

[2018-01-09_21-16-03.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1617516/2018-01-09_21-16-03.txt)

It does complain about a wrapper file, not existing in the wrapper subfolder.  I did copy the whole directory to a folder off the root of C, (path with no spaces) to try and see if it was related to the wrapper path bug, but it still complained.

**Comment by UselessGuru** [comment]
For this miner you will have to use one reliably you need to disable the watchdog.

Reason: PalginNvidia does not have API so MPM must attempt to read the hash rate from the screen output (that's what wrapper is for). However PalginNvidia sometimes takes ages to report hash rates. Watchdog kicks it out of the list of available miners.

BTW: Palgin has announced that API implementation is in the works :-)

**Comment by cmbconcretefire** [comment]
Just what I was looking for cause from my research tonight, I believe this Palgin-Nvidia miner for neoscrypt blows the other neoscrypt miners out of the water. I did some testing and it's fast.

**Comment by cmbconcretefire** [comment]
Hey @UselessGuru , I disabled watchdog, restarted MPM, and I'm still getting the failed to connect to PalginNvidia. Am I missing something?

**Comment by Braintelligence** [comment]
@UselessGuru And I thought my swap file size was too small <_>. Good to know it's not my fault then.

**Comment by UselessGuru** [comment]
>  I disabled watchdog, restarted MPM,

Disabling WD will prevent that pools or miners are removed from the list.
WD has no impact on the timing loops built into the API files (wrapper included). You will still see the errors. Live with it :-(

**Comment by cmbconcretefire** [comment]
@UselessGuru , where are you from? I'm in the US. Just curious. So, are you saying I will still see the errors but that it will actually report to the pools correctly? To be honest, I can't even get it to finish 'benchmarking'.....or get it to report to zpool.

**Comment by UselessGuru** [comment]
> where are you from?

Switzerland

> it will actually report to the pools correctly

yes, it sends hashes to the pool.

> or get it to report to zpool?

??? Do you see any errors in the miner windows? If not then yes.

> I can't even get it to finish 'benchmarking'....

As written before Palgin takes ages to report a usable hash rate on screen that the wrapper can read.

**Comment by titvs** [comment]
The API implementation and the support for GTX 9xx would be great. Have a machine with a GTX 980 that cant be wasted... ;P

**Comment by FruitFace** [comment]
@UselessGuru Thanks for the detail.  Disabling the watchdog did the trick.  The PalginNvidia is the best performer for me, now, that the original Palgin miner is no longer available.  I get about 45-57MH more than CCminerKlaust on Neoscrypt, the next best Neoscrypt miner, at least for me.

I'm mining to NH, running 3x 1070s and 1x 1080, and Neoscrypt is generally my most profitable algo, followed by Lyra2rev2, Equihash and recently, Nist5.

The miner is stable as well, as Klaust would sometimes crash one of my 1070's, if i was using firefox, despite the 1070 being one of the three using a PCI extender.  The 1080ti is my main vid card, as this is a multi-use system  Go figure...

**Comment by torsrex** [comment]
I noticed that in the latest release of PalginNvidia they changed the way the hashrate is printed to this
``` INFO : [20:00:40] : GPU#0 - GeForce GTX 1050 Ti, speed is 520.94kH/s```
Line 35 in wrapper.ps1 looks like this
```If (($Line -like "*total*" -or $Line -like "*accepted*" -or $Line -like ">*") -and $Line -like "*/s*") {```
But none of the words matches the new printing layout of the miner. If however the line is changed to this
```if (($Line -like "*total*" -or $Line -like "*accepted*" -or $line -like "*speed*" -or $Line -like ">*") -and $Line -like "*/s*") {```
It successfully reads the output of the miner. Perhaps this could be updated?

**Comment by papacheal** [comment]
That particular output text is done per card. MPM is interested in the aggregate hash rate from all the cards, which this miner only currently outputs every 20 accepted shares or so. The "wrapper" picks this up aggregate output from the "Share accepted, " text. Unfortunately, this output doesn't happen often enough to avoid getting flagged by the watchdog once the share submission rate slows down (i.e. pool changes to harder stratum difficulty).

If you've only got one card, you could look for that one line but PalginPav is supposedly going to fix this issue in 1.0.2 anyway.

**Comment by grantemsley** [comment]
Closing outdated issue.  If this is still a problem (and there currently isn't an open issue for it) please open a new one.
