### ISSUE TITLE
issues during benchmark

### ISSUE THREAD

**Issue by mr-oli** [MultiPoolMiner/MultiPoolMiner#992]
hello

i have issue with benchmarking in multipoolminer, I was using nemos miner so far but now, when miningpoolhubstats.com could alert me by mail I am trying to mine on multipoolminer
But I have problem with benchmarking, it takes 4 hours, with 5 PC restarts so far (I wasnt restarting my PC)
Also, I thing that miner program got stuck beacuse it keep mining zcach (for example) for 30min, not going to next coin

I got 7x 1070
maybe I choose too many algo?
[2018-01-10_14-29-58.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1619004/2018-01-10_14-29-58.txt)
[2018-01-10_14-07-32.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1619106/2018-01-10_14-07-32.txt)

**Comment by UselessGuru** [comment]
Do you have you the watchdog enabled?

**Comment by mr-oli** [comment]
> Do you have you the watchdog enabled?

-donate 10 -watchdog -MPHApiKey

**Comment by grantemsley** [comment]
The initial benchmarking can take a LONG time.  If your computer is crashing, you have some hardware issues or some of the miners aren't compatible with your system.

Make sure you have the latest NVIDIA drivers.

If you are still getting crashes/reboots, disable all but one algorithm, let it benchmark those, then add another, wait until those are benchmarked, and keep repeating until you have all the algorithms you want.  If you start getting more crashes while it's benchmarking, figure out which miner it was benchmarking at the time and disable just that one.

**Comment by mr-oli** [comment]
Thanks!
I downloaded latest drivers and remove some miners.
But still MPM is crashing, could you please help?

[2018-01-11_13-56-27.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1622876/2018-01-11_13-56-27.txt)

**Comment by UselessGuru** [comment]
>  still MPM is crashing

What do you mean with MPM is crashing? Miners crash, MPM at worst writes red errors. However there are no errors in your uploaded log.
So: What miner crashes?

> If you are still getting crashes/reboots

And if it has not been mentioned: Disable all overclock! Revert to stock.

**Comment by mr-oli** [comment]
So everytime when opening bat file I got this:
![image](https://user-images.githubusercontent.com/35300201/34831776-32498982-f6e8-11e7-94d5-76ba53df5810.png)

then:
![image](https://user-images.githubusercontent.com/35300201/34831846-7029ff66-f6e8-11e7-875f-f8c1364ce5fa.png)

when it finally start to benchmark it reboot from time to time during benchmark

**Comment by UselessGuru** [comment]
> Why should I disable all overclock?
Answer: when it finally start to benchmark it reboot from time to time during benchmark
and really often it stuck on one miner during benchmark.

> Only during benchmark or normally?
Answer: when it finally start to benchmark it reboot from time to time during benchmark
and really often it stuck on one miner during benchmark.

Overclocking is fine, but not so much that you get crashes.
MPM uses a lot of algorithms, some which are soppoted by nemo. Some are harder on GPU, CPU & powersupply than others. That's why you think that you HAD a stable system, but when being puched it'll teach you something else.

**Comment by UselessGuru** [comment]
> So everytime when opening bat file I got this:

This may have been caused by your constant crashes. It appears that one of your pool files is corrupt. Can you please re-install them?
