### ISSUE TITLE
btc/Day and btc/GH/Day showing 0 across all algorithms

### ISSUE THREAD

**Issue by corbinschwartz** [MultiPoolMiner/MultiPoolMiner#994]
Reporting 0 across all algos.

As of latest commit (a302cd217eff850725c469499e97ff785080a7ba).

Of note: BTC/GH/Day is showing accurately, it's the new one that doesn't work (btc in my case, but in general selected currency)

**Comment by jweber018** [comment]
+1 here. It obviously affects which miner is invoked (for example, my rig mines with ETH only mode, instead of dual-mining).

**Comment by UselessGuru** [comment]
Upload logs please.

> It obviously affects which miner is invoked (for example, my rig mines with ETH only mode, instead of dual-mining).

That certainly must have a different reason. The tape of miners & it options are totally seprate from the tiny change that was made.

> Reporting 0 across all algos.

Did you see a message saying 'Coinbase is down'? Then that is why.

**Comment by jweber018** [comment]
My rig actually crashed while I was extracting the logs 👎 I'll upload then as soon as I get it up and running again.

**Comment by UselessGuru** [comment]
What have you configured as first currency in your start.bat?

**Comment by TVanAusdall** [comment]
I stated getting this just after the last update

**Comment by UselessGuru** [comment]
> The one tagged "Fix MinigPoolHub (API does not report hash rate on algo)	2 days ago"

That is definitely impossble. That change reverted a change that broke something. Plus it has absolute nothing to do with the error you are reporting.

**Comment by TVanAusdall** [comment]
Just a coincidence then :-)

**Comment by Nasjba** [comment]
I believe i have the same issue, added the logs.

[2018-01-10_23-02-41.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1620669/2018-01-10_23-02-41.txt)

**Comment by UselessGuru** [comment]
Can you see if these two fixes help? I think you have BTC configured as first currency

[fix local currency if currency[0] is BTC](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/1381b201cc29fa7b994dba6e529a89d0bcf6fad5
)
[fix local currency if currency[0] is BTC](https://github.com/MultiPoolMiner/MultiPoolMiner/commit/8a2c7f1c7626b9321f8ebd793cc54c4519c3debe)

**Comment by Nasjba** [comment]
flawlessly, thanks
