### ISSUE TITLE
MPH vs Zpool in 2.7.1.4 from 2.7.1.2

### ISSUE THREAD

**Issue by trinitron79** [MultiPoolMiner/MultiPoolMiner#995]
I just upgraded my setup from MPM 2.7.1.2 to 2.7.1.4 and noticed that over the last hour zpool isn't even on the list, yet when I run the same setup on 2.7.1.2 I see a mix of zpool and MPH.

Did a change happen that changed the weight of zpool vs MPH, just seems strange that with the latest update + MPHStats release all I see is MPH.

To make it wasn't something old in my setup I went ahead and did a fresh deployment, changed the zpool.pl file to c=LTC, then setup the Start.bat to how I had it.   During the benchmarks again zero zpool tries.

At times i've seen one or the other pool on the complete list but not for very long, at this point it's been over an hour and I haven't seen zpool once.

**Comment by aaronsace** [comment]
v2.7.1.4 is working correctly.
