### ISSUE TITLE
MPM API failing at MPH?

### ISSUE THREAD

**Issue by btwice916** [MultiPoolMiner/MultiPoolMiner#996]
This just started today, was running fine then started pushing the "WARNING: Pool API (MiningPoolHub) has failed." message (currently also failing at MiningPoolHubCoins, Nicehash, and Zpool). If I run from the Ethash-Claymore bin directly, it seems to work fine mining to MPH. Haven't changed any settings, is this a MPH issue as they just updated their web server recently?

**Comment by cmbconcretefire** [comment]
Before the real experts come along < no sarcasm > , as an IT guy I always default to the KISS rule. 
1) Have you shut down / restarted your router / and rigs? (Because what you describe sure sounds like a basic internet connection issue to me) 
2) Do you even use MPH, Nicehash, or zpool?

**Comment by btwice916** [comment]
So the odd thing is I did go through the usual stuff of resetting everything, and I have been mining using MPH (not Nicehash/Zpool, just figured I would mention those), but nothing worked other than going directly to the miner bin and starting it up there, where it connects to MPH just fine. If it was connection based I would think nothing would be able to connect to MPH.

**Comment by jitaek** [comment]
Had this exact same problem and simply restarting the router fixed it. Good stuff @cmbconcretefire

**Comment by hiewliwen** [comment]
I have the warning occasionally but it did not affect the mining. So I leave it be.

**Comment by btwice916** [comment]
Well, a transformer exploded on my block and shut all power down for a few hours. MPM is working fine now, so whatever I missed was reset by the power outage haha.
