### ISSUE TITLE
MultiPoolMiner Setup+Benchmark Troubles

### ISSUE THREAD

**Issue by diduncan** [MultiPoolMiner/MultiPoolMiner#997]
Hi there, I'm relatively new to MultiPoolMiner (and even mining in general). but I've been using it on my first rig with great success. Setup was smooth, and benchmarking was easy as well. However, I have recently tried to mine with MultiPoolMiner on my second rig. I had previously setup MPM on this second rig for benchmarking and initial testing about two weeks ago, and everything ran flawlessly. However, when I tried this past week, errors and unresponsive miners were present. 

After uninstalling and reinstalling MPM, I was met with even more issues. "Could not find [miner] @ [file directory]" and "Could not download [miner] from [link]" messages were popping up. However, the miners were in fact being downloaded. 

![github](https://user-images.githubusercontent.com/35312462/34797447-6a38fbe2-f626-11e7-84a8-b5ba8454720e.PNG)

![github2](https://user-images.githubusercontent.com/35312462/34797449-6a66af7e-f626-11e7-8dfd-521b59c34526.PNG)

When miners were found and opened, hashrates and GPU usage remained at 0. In my most recent attempt, I remember there was a red message displaying that APIs for GPU0 and GPU1 could not be established (or something of that nature). EthDcrMiner64 also displayed that it could not find libcurl.dll and another component as well (sorry, couldn't remember). I will post images of the issue if that helps. 

![github1](https://user-images.githubusercontent.com/35312462/34797448-6a4c7118-f626-11e7-9b54-80fe02925f59.PNG)

I tried many times to get MPM to work. I've tried modifying Start.bat, downloading miners manually, copying and pasting miners and files from my 1st rig's MPM folder... I would really like to get MPM up and running. If anyone has had similar issues and have found solutions, your assistance would be greatly appreciated.

Thanks in advance, 

Duncan

**Comment by aaronsace** [comment]
You need this: 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.1.4/MultiPoolMinerV2.7.1.4.zip

And this: 
https://github.com/nicehash/excavator/releases

**Comment by diduncan** [comment]
The releases .zip is what I've been using. I have excavator downloaded, but only the AMD compatible version 1.2.11. Do I need to replace it with/include the 1.3.8a NVIDIA version?

**Comment by aaronsace** [comment]
Excavator dropped AMD support and there is no date as to when it will be added back. Consider it NVidia only for now. 

You dowloaded the souce instead of the release package though as the libcurl is here: 
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.1.4/MultiPoolMinerV2.7.1.4.zip

**Comment by diduncan** [comment]
I have been using the releases package downloaded from the link you have provided. I have tried using both 2.7.1.4 and 2.7.0.2 versions. The previously working version I used was 2.7.1.2.

![github4](https://user-images.githubusercontent.com/35312462/34798845-881a1088-f62b-11e7-8b04-7a22720779e7.PNG)

For excavator, should I still download the 1.3.8a NVIDIA files? Or should I continue using the 1.2.11 folder that in currently in bin?

Perhaps it is a GPU issue? I am running a Radeon Pro Duo, essentially two R9 Nanos on a single board.

**Comment by aaronsace** [comment]
OK, defintley use 2.7.1.4. 

Check libcurl is there in the zip then check the folder.

**Comment by diduncan** [comment]
libcurl.dll is in both the .zip and the \MultiPoolMinerV2.7.1.4\Bin\Ethash-Claymore folder. I have also found the other missing component, cudart64_80.dll, in the folder as well. However, the miner is still experiencing the same start-up issues as it did before. (reporting that it cannot find both mentioned components) 

With regards to the non-existent hashrate and GPU utilization while benchmarking Equihash and Cryptonight, is there any solution to this? The miners seem to function properly, and are at least beginning the benchmarking process. However, they don't seem to communicate with the GPUs and no hashrate is present as a result (check the first two pictures I've uploaded in my original post).

I really do appreciate the help, I understand that diagnosing the issue without a remote access is difficult.

**Comment by papacheal** [comment]
As best practice, I would try extracting the latest release ZIP into an empty folder off the root without spaces in the name:

e.g. C:\MPM

Though the system *should* work in deeper directory paths with spaces in them (as you're doing), MPM is a collection of various scripts and miners that may not all function in that configuration.

You'll need to set up your Start.bat again with appropriate settings in the new folder, but it couldn't hurt to try to see if it helps you out.

**Comment by UselessGuru** [comment]
> For excavator, should I still download the 1.3.8a NVIDIA files? Or should I continue using the 1.2.11 folder that in currently in bin?

I recommend to always go for the latest version, currently https://github.com/nicehash/excavator/releases/tag/v1.4.0a

**Comment by UselessGuru** [comment]
Is this still an issue? If not then please close - TIA.
