### ISSUE TITLE
zclassic mining with multipoolminer

### ISSUE THREAD

**Issue by ihansoli** [MultiPoolMiner/MultiPoolMiner#998]
Hi, there. I started to use multipoolminer 2 days ago.
But it did not benchmark zclassic coin.
is there any reason about this?
![image](https://user-images.githubusercontent.com/35319822/34806110-b187fa54-f6c4-11e7-8b93-fa293e01078f.png)

Thanks.

**Comment by bbgobie** [comment]
Have you been stuck on the benchmark for 2 days?Are you still running Groestl, restart the multipoolminer man

**Comment by ihansoli** [comment]
No...MPM did not mining zclassic, so, I restart MPM for benchmark a few minutes ago...
and still cannot find zclassic..

**Comment by hiewliwen** [comment]
Zencash, Zclassic, Zcash & Gitcoin-Gold uses the Equihash algor. 
I believe then benching for one is equivalent to benching for all. The pool then tells MPM which coin is more profitable and it switches accordingly.

**Comment by UselessGuru** [comment]
> I believe then benching for one is equivalent to benching for all. 

Correct!

**Comment by ihansoli** [comment]
Thank you for all reply. then, I will just believe MPM and waiting for zclassic or Most profitable coin
